// Which engine speaks the English audio.
//
// Shared by server code (settings action, pages) and the client listening engine, so this file
// must stay free of "use client", of imports and of browser globals.
//
//  - "microsoft": Microsoft Edge neural voices, generated by our own /api/tts route and played
//                 through a normal <audio> element. Needs an internet connection.
//  - "google":    the voice built into the device (Web Speech API). On Android that is Google's
//                 voice, on iPhone it is Apple's. Works offline.

export const AUDIO_PROVIDERS = ["microsoft", "google"] as const;

export type AudioProvider = (typeof AUDIO_PROVIDERS)[number];

/** Microsoft's neural voices sound far more natural, so they are the default. */
export const DEFAULT_AUDIO_PROVIDER: AudioProvider = "microsoft";

/** Anything that is not a known provider (old rows, bad input) falls back to the default. */
export function normalizeAudioProvider(value: unknown): AudioProvider {
  return value === "google" || value === "microsoft" ? value : DEFAULT_AUDIO_PROVIDER;
}
