# -*- coding: utf-8 -*-
"""Generate Day 89 and Day 90 for Stage 9 - Completing the 90-Day Curriculum."""

import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from curriculum_engine import write_day

# ==============================================================================
# DAY 89: Reflections (Memories and lessons learned)
# Grammar: Wish + Narrative + Used to Review
# ==============================================================================

vocab_89 = [
    # Nostalgia, Memory & Childhood Keepsakes
    {"headword": "poignant memory", "pronunciation": "/ˈpɔɪnjənt ˈmeməri/", "partOfSpeech": "noun", "definition": "A deeply moving, emotionally touching remembrance that evokes profound tenderness or sorrow.", "example": "A poignant memory of her grandfather playing the cello brought tears of gratitude to her eyes.", "translation": "ذكرى مؤثرة ومفعمة بالمشاعر العميقة", "collocations": ["evoke a poignant memory", "cherish a poignant memory"], "synonyms": ["touching recollection"], "antonyms": ["faded memory"], "tags": ["memory", "emotions"]},
    {"headword": "hard-won wisdom", "pronunciation": "/hɑːd wʌn ˈwɪzdəm/", "partOfSpeech": "noun", "definition": "Deep, mature understanding and judgment acquired through difficult challenges and enduring trials.", "example": "Her hard-won wisdom helped her guide younger colleagues through organizational upheavals with calm authority.", "translation": "الحكمة المستخلصة بعد عناء ومشقة وتجارب", "collocations": ["share hard-won wisdom", "accrue hard-won wisdom"], "synonyms": ["tested insight"], "antonyms": ["naive ignorance"], "tags": ["wisdom", "growth"]},
    {"headword": "formative life lesson", "pronunciation": "/ˈfɔːmətɪv laɪf ˈlesn/", "partOfSpeech": "noun", "definition": "A pivotal experience during youth or early career that permanently shapes character and values.", "example": "Losing that student election was a formative life lesson about resilience and graceful humility.", "translation": "درس حياتي تأسيسي ومؤثر في تكوين الشخصية", "collocations": ["learn a formative life lesson", "impart a formative life lesson"], "synonyms": ["foundational life experience"], "antonyms": [], "tags": ["growth", "learning"]},
    {"headword": "nostalgic reflection", "pronunciation": "/nɒˈstældʒɪk rɪˈflekʃn/", "partOfSpeech": "noun", "definition": "Sentimental contemplation of past eras, cherished acquaintances, or bygone childhood days.", "example": "Looking through dusty photo albums sparked an evening of nostalgic reflection with old university friends.", "translation": "التأمل والحنين إلى الماضي الجميل والذكريات", "collocations": ["engage in nostalgic reflection", "indulge in nostalgic reflection"], "synonyms": ["wistful contemplation"], "antonyms": [], "tags": ["reflection", "nostalgia"]},
    {"headword": "cherished childhood keepsake", "pronunciation": "/ˈtʃerɪʃt ˈtʃaɪldhʊd ˈkiːpseɪk/", "partOfSpeech": "noun", "definition": "A treasured personal relic—such as a pocketknife, toy, or ribbon—retained from early youth.", "example": "A tarnished silver compass given by his father remained his most cherished childhood keepsake.", "translation": "تذكار طفولة عزيز ومحفوظ بعناية", "collocations": ["keep a cherished childhood keepsake", "treasured childhood keepsake"], "synonyms": ["youthful memento"], "antonyms": [], "tags": ["memory", "childhood"]},
    {"headword": "past mistake realization", "pronunciation": "/pɑːst mɪˈsteɪk ˌriːəlaɪˈzeɪʃn/", "partOfSpeech": "noun", "definition": "The sudden or gradual awareness that an earlier decision was misguided, sparking self-correction.", "example": "His past mistake realization prompted him to write an apology letter to his former business partner.", "translation": "إدراك والاعتراف بخطأ من أخطاء الماضي", "collocations": ["arrive at a past mistake realization", "painful past mistake realization"], "synonyms": ["realization of error"], "antonyms": ["stubborn denial"], "tags": ["learning", "growth"]},
    {"headword": "turning point moment", "pronunciation": "/ˈtɜːnɪŋ pɔɪnt ˈməʊmənt/", "partOfSpeech": "noun", "definition": "A decisive instant in life where circumstances, convictions, or directions alter fundamentally.", "example": "Surviving the car accident was a turning point moment that caused him to abandon a toxic career.", "translation": "لحظة ومحطة التحول الفارقة في مجرى الحياة", "collocations": ["mark a turning point moment", "experience a turning point moment"], "synonyms": ["watershed moment"], "antonyms": [], "tags": ["milestones", "transformation"]},
    {"headword": "transformative realization", "pronunciation": "/trænsˈfɔːmətɪv ˌriːəlaɪˈzeɪʃn/", "partOfSpeech": "noun", "definition": "A profound mental or emotional insight that completely revolutionizes how one perceives reality.", "example": "Realizing that happiness stems from contentment rather than wealth was a transformative realization for him.", "translation": "إدراك واستبصار تحويلي يغير النظرة للحياة", "collocations": ["reach a transformative realization", "spark a transformative realization"], "synonyms": ["epiphany"], "antonyms": [], "tags": ["epiphany", "growth"]},
    {"headword": "bittersweet recollection", "pronunciation": "/ˌbɪtəˈswiːt ˌrekəˈlekʃn/", "partOfSpeech": "noun", "definition": "A memory mingled with both joy for what was experienced and sadness because it has passed.", "example": "Visiting her university campus brought bittersweet recollections of lost youth and departed companions.", "translation": "ذكرى حلوة وممزوجة بالشجن والحزن على ما مضى", "collocations": ["evoke bittersweet recollections", "lost in bittersweet recollection"], "synonyms": ["poignant reminiscing"], "antonyms": [], "tags": ["memory", "emotions"]},
    {"headword": "gratitude reflection practice", "pronunciation": "/ˈɡrætɪtjuːd rɪˈflekʃn ˈpræktɪs/", "partOfSpeech": "noun", "definition": "The regular, deliberate contemplation of blessings, supportive mentors, and life privileges.", "example": "Starting each dawn with a gratitude reflection practice dissolved his chronic pessimism.", "translation": "ممارسة التأمل والتعبير عن الامتنان للنعم", "collocations": ["maintain a gratitude reflection practice", "daily gratitude reflection practice"], "synonyms": ["thankfulness contemplation"], "antonyms": ["chronic complaining"], "tags": ["gratitude", "habits"]},

    # Insight, Acceptance & Healing
    {"headword": "deep life insight", "pronunciation": "/diːp laɪf ˈɪnsaɪt/", "partOfSpeech": "noun", "definition": "A profound philosophical comprehension of human nature, purpose, or existential relationships.", "example": "Years of solitary mountain contemplation rewarded him with deep life insights about stillness and detachment.", "translation": "رؤية وبصيرة حياتية عميقة وشاملة", "collocations": ["gain a deep life insight", "share deep life insights"], "synonyms": ["profound philosophical perception"], "antonyms": ["shallow thinking"], "tags": ["wisdom", "philosophy"]},
    {"headword": "unforgettable life lesson", "pronunciation": "/ˌʌnfəˈɡetəbl laɪf ˈlesn/", "partOfSpeech": "noun", "definition": "A powerful truth absorbed through personal trial that remains permanently etched in memory.", "example": "Being saved by a complete stranger during a storm was an unforgettable life lesson in human kindness.", "translation": "درس وتجربة حياتية لا يمكن نسيانها", "collocations": ["absorb an unforgettable life lesson", "serve as an unforgettable life lesson"], "synonyms": ["indelible lesson"], "antonyms": [], "tags": ["learning", "memory"]},
    {"headword": "peaceful self-acceptance", "pronunciation": "/ˈpiːsfl self əkˈseptəns/", "partOfSpeech": "noun", "definition": "A tranquil state of inner harmony where one embraces personal strengths, flaws, and history without judgment.", "example": "After decades of self-doubt, she finally attained peaceful self-acceptance in her late forties.", "translation": "القبول الذاتي الهادئ والتصالح مع النفس", "collocations": ["attain peaceful self-acceptance", "cultivate peaceful self-acceptance"], "synonyms": ["serene self-reconciliation"], "antonyms": ["self-loathing"], "tags": ["peace", "psychology"]},
    {"headword": "childhood home memory", "pronunciation": "/ˈtʃaɪldhʊd həʊm ˈmeməri/", "partOfSpeech": "noun", "definition": "Sensory recollections of the rooms, smells, and gardens of the residence where one grew up.", "example": "The fragrance of blooming honeysuckle immediately unlocked a comforting childhood home memory.", "translation": "ذكرى بيت الطفولة ودفء النشأة الأولى", "collocations": ["cherish childhood home memories", "vivid childhood home memory"], "synonyms": ["childhood dwelling remembrance"], "antonyms": [], "tags": ["home", "childhood"]},
    {"headword": "overcoming past regret", "pronunciation": "/ˌəʊvəˈkʌmɪŋ pɑːst rɪˈɡret/", "partOfSpeech": "noun", "definition": "The psychological process of letting go of remorse over past mistakes and embracing the present.", "example": "Overcoming past regret allowed him to pursue new romantic happiness without lingering bitterness.", "translation": "تجاوز والتغلب على الندم على الماضي", "collocations": ["step toward overcoming past regret", "struggle with overcoming past regret"], "synonyms": ["releasing past remorse"], "antonyms": ["clinging to regret"], "tags": ["healing", "growth"]},
    {"headword": "personal resilience story", "pronunciation": "/ˈpɜːsənl rɪˈzɪliəns ˈstɔːri/", "partOfSpeech": "noun", "definition": "An autobiographical narrative detailing how an individual overcame severe crisis or illness.", "example": "Her personal resilience story inspired hundreds of cancer patients to maintain hope during chemotherapy.", "translation": "قصة الصمود والمثابرة وتجاوز المحن الشخصية", "collocations": ["share a personal resilience story", "inspiring personal resilience story"], "synonyms": ["overcoming adversity narrative"], "antonyms": [], "tags": ["resilience", "inspiration"]},
    {"headword": "quiet moment of reflection", "pronunciation": "/ˈkwaɪət ˈməʊmənt əv rɪˈflekʃn/", "partOfSpeech": "noun", "definition": "A peaceful, solitary interlude dedicated to meditating on life's path, decisions, and blessings.", "example": "Sitting on the porch at twilight provided a quiet moment of reflection after a hectic workweek.", "translation": "لحظة تأمل وهدوء وتفكير سكينة واسترجاع", "collocations": ["take a quiet moment of reflection", "enjoy a quiet moment of reflection"], "synonyms": ["peaceful meditative pause"], "antonyms": ["frenzied distraction"], "tags": ["reflection", "mindfulness"]},
    {"headword": "valuable life takeaway", "pronunciation": "/ˈvæljuəbl laɪf ˈteɪkəweɪ/", "partOfSpeech": "noun", "definition": "A key moral, practical principle, or learning derived from an experience or failed venture.", "example": "The most valuable life takeaway from that failed business was the critical necessity of honest communication.", "translation": "فائدة وعبرة حياتية ثمينة مستخلصة", "collocations": ["glean a valuable life takeaway", "primary valuable life takeaway"], "synonyms": ["crucial lesson"], "antonyms": [], "tags": ["learning", "wisdom"]},
    {"headword": "cherished family tradition", "pronunciation": "/ˈtʃerɪʃt ˈfæməli trəˈdɪʃn/", "partOfSpeech": "noun", "definition": "A beloved recurring custom—such as baking holiday bread—handed down through family generations.", "example": "Gathering around the hearth for storytelling remained our most cherished family tradition on winter solstices.", "translation": "تقليد وعادة عائلية متوارثة وعزيزة على القلب", "collocations": ["preserve a cherished family tradition", "beloved cherished family tradition"], "synonyms": ["treasured ancestral custom"], "antonyms": [], "tags": ["family", "tradition"]},
    {"headword": "forgiving past missteps", "pronunciation": "/fəˈɡɪvɪŋ pɑːst ˈmɪssteps/", "partOfSpeech": "noun", "definition": "Granting oneself or others emotional clemency and pardon for past poor decisions.", "example": "Forgiving past missteps is the cornerstone of psychological healing and emotional maturity.", "translation": "الصفح والمسامحة على عثرات وأخطاء الماضي", "collocations": ["practice forgiving past missteps", "necessity of forgiving past missteps"], "synonyms": ["pardoning past errors"], "antonyms": ["holding eternal grudges"], "tags": ["forgiveness", "healing"]},

    # Youthful Dreams, Core Values & Adversity
    {"headword": "youthful dream memory", "pronunciation": "/ˈjuːθfl driːm ˈmeməri/", "partOfSpeech": "noun", "definition": "Recalling the idealistic hopes, ambitions, and innocent fantasies of one's adolescent years.", "example": "A youthful dream memory of building astronomical telescopes resurfaced when he bought a stargazing app.", "translation": "ذكرى أحلام وطموحات فترة الشباب الغضة", "collocations": ["revisit a youthful dream memory", "cherished youthful dream memory"], "synonyms": ["adolescent aspiration remembrance"], "antonyms": [], "tags": ["dreams", "youth"]},
    {"headword": "life crossroad choice", "pronunciation": "/laɪf ˈkrɒsrəʊdz tʃɔɪs/", "partOfSpeech": "noun", "definition": "A critical fork in life where selecting one path permanently precludes another.", "example": "Deciding whether to study abroad or take over the family vineyard was his definitive life crossroad choice.", "translation": "خيار مفترق طرق الحياة الحاسم والمصيري", "collocations": ["face a life crossroad choice", "confront a life crossroad choice"], "synonyms": ["pivotal crossroads decision"], "antonyms": [], "tags": ["choices", "life"]},
    {"headword": "enduring core value", "pronunciation": "/ɪnˈdjʊərɪŋ kɔː ˈvæljuː/", "partOfSpeech": "noun", "definition": "A foundational moral compass principle—such as integrity or kindness—that never changes over time.", "example": "Uncompromising honesty remained an enduring core value instilled in her by her mother.", "translation": "قيمة ومبدأ جوهري راسخ وثابت عبر السنين", "collocations": ["uphold an enduring core value", "guided by enduring core values"], "synonyms": ["abiding fundamental principle"], "antonyms": ["shifting opinions"], "tags": ["values", "morals"]},
    {"headword": "growth through adversity", "pronunciation": "/ɡrəʊθ θruː ədˈvɜːsəti/", "partOfSpeech": "noun", "definition": "The psychological strengthening, resilience, and wisdom gained through enduring hardship.", "example": "Experiencing financial bankruptcy taught him that growth through adversity builds indestructible character.", "translation": "النمو والنضج واكتساب القوة من خلال المحن", "collocations": ["experience growth through adversity", "testament to growth through adversity"], "synonyms": ["post-traumatic maturation"], "antonyms": ["resignation to defeat"], "tags": ["resilience", "growth"]},
    {"headword": "fond nostalgic memory", "pronunciation": "/fɒnd nɒˈstældʒɪk ˈmeməri/", "partOfSpeech": "noun", "definition": "A warm, affectionate recollection of past holidays, childhood play, or cherished departed loved ones.", "example": "She smiled warmly as fond nostalgic memories of summer camp filled her evening thoughts.", "translation": "ذكرى دافئة ومحببة مفعمة بالحنين للماضي", "collocations": ["evoke fond nostalgic memories", "recount fond nostalgic memories"], "synonyms": ["warm reminiscence"], "antonyms": ["traumatic memory"], "tags": ["nostalgia", "memory"]},
    {"headword": "reflective journal entry", "pronunciation": "/rɪˈflektɪv ˈdʒɜːnl ˈentri/", "partOfSpeech": "noun", "definition": "A written personal diary passage analyzing thoughts, emotions, and lessons learned during the day.", "example": "Writing a reflective journal entry each evening helped the physician process the emotional weight of his work.", "translation": "تدوينة يوميات تأملية لمراجعة الذات والمشاعر", "collocations": ["write a reflective journal entry", "compose a reflective journal entry"], "synonyms": ["diary reflection"], "antonyms": [], "tags": ["writing", "reflection"]},
    {"headword": "humbling life experience", "pronunciation": "/ˈhʌmblɪŋ laɪf ɪkˈspɪəriəns/", "partOfSpeech": "noun", "definition": "An event that reveals one's human limitations, reduces arrogance, and deepens empathy for others.", "example": "Failing the bar exam on his first attempt was a humbling life experience that taught him true diligence.", "translation": "تجربة حياتية تغرس التواضع وتكسر الغرور", "collocations": ["undergo a humbling life experience", "serve as a humbling life experience"], "synonyms": ["grounding experience"], "antonyms": ["arrogant victory"], "tags": ["humility", "growth"]},
    {"headword": "inner peace realization", "pronunciation": "/ˈɪnə piːs ˌriːəlaɪˈzeɪʃn/", "partOfSpeech": "noun", "definition": "The awakening to the truth that peace resides within oneself rather than in external validations.", "example": "Her inner peace realization freed her from the exhausting race for corporate status symbols.", "translation": "إدراك واستشعار السلام الداخلي العميق", "collocations": ["experience an inner peace realization", "pathway to inner peace realization"], "synonyms": ["tranquility awakening"], "antonyms": ["inner turmoil"], "tags": ["peace", "spirituality"]},
    {"headword": "perspective shift moment", "pronunciation": "/pəˈspektɪv ʃɪft ˈməʊmənt/", "partOfSpeech": "noun", "definition": "An instant when a new viewpoint alters how one evaluates past hardships or future potentials.", "example": "Volunteering at the hospice hospital was a perspective shift moment that transformed his priorities.", "translation": "لحظة تغير وتبدل الرؤية والمنظور للحياة", "collocations": ["experience a perspective shift moment", "spark a perspective shift moment"], "synonyms": ["paradigm shift instant"], "antonyms": [], "tags": ["perspective", "transformation"]},
    {"headword": "cherished life milestone", "pronunciation": "/ˈtʃerɪʃt laɪf ˈmaɪlstəʊn/", "partOfSpeech": "noun", "definition": "A treasured personal achievement—such as marriage or completing a marathon—remembered with pride.", "example": "Publishing his first historical biography was a cherished life milestone celebrated with his entire family.", "translation": "محطة وإنجاز حياتي عزيز ومخلد في الذاكرة", "collocations": ["celebrate a cherished life milestone", "mark a cherished life milestone"], "synonyms": ["treasured landmark achievement"], "antonyms": [], "tags": ["milestones", "celebration"]},

    # Life Lessons, Retrospection & Hindsight
    {"headword": "lesson in humility", "pronunciation": "/ˈlesn ɪn hjuːˈmɪləti/", "partOfSpeech": "noun", "definition": "An instructive encounter that strips away hubris and teaches modest self-assessment.", "example": "Losing that tennis match to a novice was an invaluable lesson in humility for the arrogant champion.", "translation": "درس بليغ في التواضع وعدم التكبر", "collocations": ["absorb a lesson in humility", "receive a lesson in humility"], "synonyms": ["schooling in modesty"], "antonyms": [], "tags": ["humility", "wisdom"]},
    {"headword": "past triumph reflection", "pronunciation": "/pɑːst ˈtraɪəmf rɪˈflekʃn/", "partOfSpeech": "noun", "definition": "Reflecting on previous victories and accomplishments to rekindle confidence during present difficulties.", "example": "A quiet past triumph reflection reminded her that she had conquered even greater hardships before.", "translation": "استحضار والتأمل في انتصارات ونجاحات الماضي", "collocations": ["indulge in past triumph reflection", "draw strength from past triumph reflection"], "synonyms": ["victory reminiscence"], "antonyms": ["dwelling on defeat"], "tags": ["reflection", "confidence"]},
    {"headword": "healing old wounds", "pronunciation": "/ˈhiːlɪŋ əʊld wuːndz/", "partOfSpeech": "noun", "definition": "The gradual emotional mending of psychological pain, estrangements, or childhood traumas.", "example": "Reconciling with her estranged sister was an essential milestone in healing old wounds.", "translation": "التئام ومداواة الجروح والآلام القديمة", "collocations": ["process of healing old wounds", "commit to healing old wounds"], "synonyms": ["mending psychological scars"], "antonyms": ["reopening old wounds"], "tags": ["healing", "peace"]},
    {"headword": "treasured life lesson", "pronunciation": "/ˈtreʒəd laɪf ˈlesn/", "partOfSpeech": "noun", "definition": "A piece of wisdom passed down by an elder or learned through trial that one holds in highest esteem.", "example": "'Treat every stranger with dignity' was the treasured life lesson her grandmother bequeathed to her.", "translation": "درس وخبرة حياتية ثمينة وغالية", "collocations": ["pass down a treasured life lesson", "hold dear a treasured life lesson"], "synonyms": ["cherished wisdom nugget"], "antonyms": [], "tags": ["wisdom", "legacy"]},
    {"headword": "meaningful memory spark", "pronunciation": "/ˈmiːnɪŋfl ˈmeməri spɑːk/", "partOfSpeech": "noun", "definition": "A sensory trigger—such as an aroma, melody, or object—that abruptly ignites vivid remembrance.", "example": "The scent of cedar wood acted as a meaningful memory spark, transporting him to his father's workshop.", "translation": "شرارة ومثير يوقظ الذكريات ذات المعنى", "collocations": ["ignite a meaningful memory spark", "act as a meaningful memory spark"], "synonyms": ["memory catalyst"], "antonyms": [], "tags": ["memory", "inspiration"]},
    {"headword": "enduring personal truth", "pronunciation": "/ɪnˈdjʊərɪŋ ˈpɜːsənl truːθ/", "partOfSpeech": "noun", "definition": "An immutable conviction forged through lifetime experiences that guides one's actions unconditionally.", "example": "That kindness is never wasted remained an enduring personal truth that anchored his actions.", "translation": "حقيقة وقناعة شخصية راسخة لا تتزعزع", "collocations": ["affirm an enduring personal truth", "live by an enduring personal truth"], "synonyms": ["immutable inner conviction"], "antonyms": [], "tags": ["truth", "philosophy"]},
    {"headword": "wisdom of hindsight", "pronunciation": "/ˈwɪzdəm əv ˈhaɪndsaɪt/", "partOfSpeech": "noun", "definition": "The mature understanding that becomes clear only after events have unfolded and consequences are visible.", "example": "With the wisdom of hindsight, he understood that being rejected for that job was the greatest blessing of his career.", "translation": "حكمة الإدراك المتأخر بعد فوات الأوان وانكشاف الأمور", "collocations": ["benefit from the wisdom of hindsight", "clarity of the wisdom of hindsight"], "synonyms": ["retrospective understanding"], "antonyms": ["myopic foresight"], "tags": ["wisdom", "reflection"]},
    {"headword": "reflective life pause", "pronunciation": "/rɪˈflektɪv laɪf pɔːz/", "partOfSpeech": "noun", "definition": "A dedicated period of sabbatical or quiet solitude taken to evaluate life direction and priorities.", "example": "Taking a three-month reflective life pause in the countryside allowed the executive to recalibrate his goals.", "translation": "وقفة تأمل واستراحة لمراجعة مسار الحياة", "collocations": ["take a reflective life pause", "need a reflective life pause"], "synonyms": ["contemplative intermission"], "antonyms": ["relentless grind"], "tags": ["reflection", "lifestyle"]},
    {"headword": "childhood wonder memory", "pronunciation": "/ˈtʃaɪldhʊd ˈwʌndə ˈmeməri/", "partOfSpeech": "noun", "definition": "Recalling the pure awe, curiosity, and enchanted excitement experienced during early childhood.", "example": "Watching the fireflies flicker in the summer meadow rekindled a vivid childhood wonder memory.", "translation": "ذكرى الدهشة والانبهار البريء في الطفولة", "collocations": ["relive a childhood wonder memory", "treasure childhood wonder memories"], "synonyms": ["innocent awe remembrance"], "antonyms": [], "tags": ["childhood", "wonder"]},
    {"headword": "reconciling past choices", "pronunciation": "/ˈrekənsaɪlɪŋ pɑːst ˈtʃɔɪsɪz/", "partOfSpeech": "noun", "definition": "Making peace with earlier life paths taken and accepting that they shaped one's present identity.", "example": "Reconciling past choices helped him let go of bitter 'what-if' ruminations and focus on the future.", "translation": "التصالح مع القرارات والخيارات السابقة في الحياة", "collocations": ["process of reconciling past choices", "seek reconciling past choices"], "synonyms": ["accepting past decisions"], "antonyms": ["bitter regret"], "tags": ["healing", "acceptance"]},
    {"headword": "life journey gratitude", "pronunciation": "/laɪf ˈdʒɜːni ˈɡrætɪtjuːd/", "partOfSpeech": "noun", "definition": "A deep appreciation for the entirety of one's lived experience, including trials, triumphs, and mentors.", "example": "Celebrating his eightieth birthday filled his heart with profound life journey gratitude.", "translation": "الامتنان والشكر لمسيرة ورحلة الحياة بأكملها", "collocations": ["feel life journey gratitude", "express life journey gratitude"], "synonyms": ["total life thankfulness"], "antonyms": ["existential bitterness"], "tags": ["gratitude", "life"]},
    {"headword": "priceless life lesson", "pronunciation": "/ˈpraɪsləs laɪf ˈlesn/", "partOfSpeech": "noun", "definition": "An invaluable piece of wisdom acquired through experience whose worth cannot be quantified.", "example": "Learning to listen before speaking was a priceless life lesson taught by his grandfather.", "translation": "درس حياتي لا يقدر بثمن", "collocations": ["learn a priceless life lesson", "gift of a priceless life lesson"], "synonyms": ["invaluable lesson"], "antonyms": [], "tags": ["wisdom", "learning"]},
    {"headword": "revisiting old memories", "pronunciation": "/ˌriːˈvɪzɪtɪŋ əʊld ˈmeməriz/", "partOfSpeech": "noun", "definition": "The intentional act of reviewing past journals, photographs, or locations to recall former times.", "example": "Revisiting old memories at their hometown cafe brought laughter and sentimental tears.", "translation": "استرجاع وزيارة الذكريات القديمة", "collocations": ["enjoy revisiting old memories", "time spent revisiting old memories"], "synonyms": ["reminiscing on the past"], "antonyms": ["forgetting the past"], "tags": ["memory", "reflection"]},
    {"headword": "gratitude for hardships", "pronunciation": "/ˈɡrætɪtjuːd fə ˈhɑːdʃɪps/", "partOfSpeech": "noun", "definition": "The mature philosophical appreciation that severe struggles served as indispensable catalysts for growth.", "example": "She expressed genuine gratitude for hardships because they had forged her resilience and compassion.", "translation": "الشكر والامتنان للصعاب والمحن لصقلها الشخصية", "collocations": ["develop gratitude for hardships", "voice gratitude for hardships"], "synonyms": ["thankfulness for trials"], "antonyms": ["resentment of suffering"], "tags": ["gratitude", "resilience"]},
    {"headword": "clarity of hindsight", "pronunciation": "/ˈklærəti əv ˈhaɪndsaɪt/", "partOfSpeech": "noun", "definition": "The sharp, objective understanding of historical events and motives that emerges long after their occurrence.", "example": "With the clarity of hindsight, she recognized that the sudden project cancellation was a hidden blessing.", "translation": "وضوح الرؤية بأثر رجعي بعد مرور الأحداث", "collocations": ["see with the clarity of hindsight", "enjoy the clarity of hindsight"], "synonyms": ["retrospective lucidity"], "antonyms": ["confusion of the moment"], "tags": ["wisdom", "clarity"]},
    {"headword": "embracing life lessons", "pronunciation": "/ɪmˈbreɪsɪŋ laɪf ˈlesnz/", "partOfSpeech": "noun", "definition": "Actively welcoming every life encounter, whether sweet or painful, as an essential teaching opportunity.", "example": "Embracing life lessons with curiosity rather than fear allowed her to navigate change gracefully.", "translation": "تقبل واستيعاب دروس وتجارب الحياة بصدر رحب", "collocations": ["philosophy of embracing life lessons", "committed to embracing life lessons"], "synonyms": ["welcoming life teachings"], "antonyms": ["resisting life lessons"], "tags": ["wisdom", "growth"]},
    {"headword": "heartfelt personal reflection", "pronunciation": "/ˈhɑːtfelt ˈpɜːsənl rɪˈflekʃn/", "partOfSpeech": "noun", "definition": "An honest, deeply emotional examination of one's feelings, shortcomings, and hopes.", "example": "His retirement speech was a heartfelt personal reflection that brought tears to everyone in attendance.", "translation": "تأمل ومراجعة شخصية صادقة ونابعة من القلب", "collocations": ["share a heartfelt personal reflection", "deliver a heartfelt personal reflection"], "synonyms": ["sincere introspection"], "antonyms": ["superficial speech"], "tags": ["reflection", "honesty"]},
    {"headword": "treasured nostalgic moment", "pronunciation": "/ˈtreʒəd nɒˈstældʒɪk ˈməʊmənt/", "partOfSpeech": "noun", "definition": "A precious, warmly remembered instance from the past that continues to bring comfort.", "example": "Baking cinnamon rolls with her grandmother was a treasured nostalgic moment she recreated every winter.", "translation": "لحظة نوستالجيا دافئة ومحفورة في الوجدان", "collocations": ["cherish a treasured nostalgic moment", "relive a treasured nostalgic moment"], "synonyms": ["precious nostalgic remembrance"], "antonyms": [], "tags": ["nostalgia", "memory"]},
    {"headword": "serene life acceptance", "pronunciation": "/səˈriːn laɪf əkˈseptəns/", "partOfSpeech": "noun", "definition": "A calm, unshakeable state of peace regarding life's mysteries, aging, and unfolding destiny.", "example": "His gentle smile reflected serene life acceptance after walking through eighty fruitful years.", "translation": "الرضا والقبول الهادئ والسكينة تجاه مجريات الحياة", "collocations": ["attain serene life acceptance", "radiate serene life acceptance"], "synonyms": ["peaceful life equanimity"], "antonyms": ["bitter protest"], "tags": ["peace", "acceptance"]},
    {"headword": "culminating life wisdom", "pronunciation": "/ˈkʌlmɪneɪtɪŋ laɪf ˈwɪzdəm/", "partOfSpeech": "noun", "definition": "The pinnacle of insight, empathy, and philosophical balance accumulated across an entire lifetime.", "example": "His final book represented the culminating life wisdom of a philosopher who had seen war and peace.", "translation": "خلاصة وذروة الحكمة والتجارب الحياتية المتراكمة", "collocations": ["distill culminating life wisdom", "embody culminating life wisdom"], "synonyms": ["pinnacle of life wisdom"], "antonyms": ["folly"], "tags": ["wisdom", "legacy"]}
]

grammar_89 = [
    {
        "title": "Wish + Narrative + Used to Review",
        "explanation": "Reflecting on memories, past decisions, and transformative life lessons requires narrative tenses and structures expressing retrospection and regret:\n\n1. 'Wish' and 'If only' for Past Regrets (Wish + Past Perfect):\n   - 'I wish I had realized that past mistake earlier.'\n   - 'If only they had understood the formative life lesson at the time.'\n\n2. 'Wish' for Present Desires (Wish + Past Simple):\n   - 'I wish I possessed greater peaceful self-acceptance today.'\n   - 'She wishes she were closer to her childhood home.'\n\n3. 'Used to' vs 'Would' for Past Habits and States:\n   - 'Used to' for past states and habits that are no longer true: 'We used to cherish that family tradition every December.'\n   - 'Would' for repeated past actions in nostalgic storytelling: 'Every summer, grandfather would tell poignant memories by the fireside.'\n\n4. Narrative Tenses in Retrospection (Past Simple, Past Continuous, Past Perfect):\n   - 'While I was journaling my reflective journal entry, I realized that growth through adversity had transformed me.'\n   - 'After he had overcome past regrets, he finally found serene life acceptance.'",
        "structures": [
            {"pattern": "Past Regret: Subject + wish + Subject + had + V3: 'I wish I had appreciated the wisdom of hindsight sooner.'"},
            {"pattern": "Nostalgic Habit: Subject + would + base form: 'In the evenings, we would share fond nostalgic memories.'"},
            {"pattern": "Past State: Subject + used to + base form: 'My grandmother used to preserve this cherished childhood keepsake.'"}
        ],
        "examples": [
            {
                "sentence": "I wish I had recognized that turning point moment when it occurred.",
                "arabic": "أتمنى لو أنني أدركت تلك اللحظة الفارقة عندما حدثت.",
                "usesVocabulary": ["turning point moment"]
            },
            {
                "sentence": "Every autumn, we would gather on the porch, sharing poignant memories and hard-won wisdom.",
                "arabic": "في كل خريف، كنا نجتمع على الشرفة، نتشارك ذكريات مؤثرة وحكمة مستخلصة بعد عناء.",
                "usesVocabulary": ["poignant memory", "hard-won wisdom"]
            },
            {
                "sentence": "He used to struggle with remorse, but he is now overcoming past regret through peaceful self-acceptance.",
                "arabic": "كان يعاني من لوم النفس، لكنه الآن يتجاوز ندم الماضي من خلال القبول الذاتي الهادئ.",
                "usesVocabulary": ["overcoming past regret", "peaceful self-acceptance"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "I wish I knew that before I made the decision.",
                "right": "I wish I had known that before I made the decision.",
                "explanation": "To express regret about a past action or event, use 'wish' + Past Perfect ('had known'), not Past Simple."
            },
            {
                "wrong": "I would live in that house when I was a child.",
                "right": "I used to live in that house when I was a child.",
                "explanation": "'Would' cannot be used for past states (like living somewhere); use 'used to' for states."
            }
        ]
    }
]

convs_89 = [
    {
        "title": "Evening Fireside Dialogue: Memories and Keepsakes",
        "titleArabic": "حوار المساء بجانب المدفأة: الذكريات والمقتنيات العزيزة",
        "setting": "An elderly grandmother and her adult grandson reminisce while looking through old heirlooms.",
        "lines": [
            {"speaker": "Grandson", "text": "Grandmother, look at this silver locket. Is this your cherished childhood keepsake?"},
            {"speaker": "Grandmother", "text": "Yes, it is! Holding it brings back poignant memories of my mother and a vivid childhood home memory."},
            {"speaker": "Grandson", "text": "Every winter, we would sit right here, listening to your fond nostalgic memories and personal resilience story."},
            {"speaker": "Grandmother", "text": "I used to worry about the future constantly. I wish I had discovered peaceful self-acceptance when I was young."},
            {"speaker": "Grandson", "text": "Your stories taught me that growth through adversity is our most valuable life takeaway."},
            {"speaker": "Grandmother", "text": "Every trial was a formative life lesson and an unforgettable life lesson in gratitude."},
            {"speaker": "Grandson", "text": "Looking at old pictures is an evening of bittersweet recollections and deep life insights."},
            {"speaker": "Grandmother", "text": "Preserving our cherished family tradition keeps our ancestors' love alive."}
        ],
        "vocabularyUsed": ["cherished childhood keepsake", "poignant memory", "childhood home memory", "fond nostalgic memory", "personal resilience story", "peaceful self-acceptance", "growth through adversity", "valuable life takeaway", "formative life lesson", "unforgettable life lesson", "bittersweet recollection", "deep life insight", "cherished family tradition"]
    },
    {
        "title": "Reflective Mentorship: Lessons in Hindsight",
        "titleArabic": "إرشاد تأملي: دروس الحكمة واسترجاع الماضي",
        "setting": "A retiring university dean reflects on leadership and lessons learned with a young professor.",
        "lines": [
            {"speaker": "Professor", "text": "Dean Roberts, when you look back on your forty-year tenure, what represents your defining turning point moment?"},
            {"speaker": "Dean", "text": "Failing my first administrative tenure review. It was a humbling life experience and an invaluable lesson in humility."},
            {"speaker": "Professor", "text": "Did that past mistake realization alter your leadership philosophy?"},
            {"speaker": "Dean", "text": "Profoundly. With the wisdom of hindsight and clarity of hindsight, I realized that forgiving past missteps is vital."},
            {"speaker": "Professor", "text": "I often read your reflective journal entries on upholding enduring core values."},
            {"speaker": "Dean", "text": "Every leader must take a reflective life pause to separate ego from purpose."},
            {"speaker": "Professor", "text": "Your career is a masterclass in reconciling past choices and embracing life lessons."},
            {"speaker": "Dean", "text": "That culminates in serene life acceptance and life journey gratitude."}
        ],
        "vocabularyUsed": ["turning point moment", "humbling life experience", "lesson in humility", "past mistake realization", "wisdom of hindsight", "clarity of hindsight", "forgiving past missteps", "reflective journal entry", "enduring core value", "reflective life pause", "reconciling past choices", "embracing life lessons", "serene life acceptance", "life journey gratitude"]
    },
    {
        "title": "Quiet Solitude: Gratitude and Overcoming Regret",
        "titleArabic": "سكينة العزلة: الامتنان وتجاوز الندم",
        "setting": "Two lifelong friends sit on a lake dock at dawn, sharing personal reflections.",
        "lines": [
            {"speaker": "Friend A", "text": "A quiet moment of reflection here reminds me of our youthful dream memories when we were eighteen."},
            {"speaker": "Friend B", "text": "We faced major life crossroad choices back then. I spent years regretting not taking that European fellowship."},
            {"speaker": "Friend A", "text": "Are you finally overcoming past regret and healing old wounds?"},
            {"speaker": "Friend B", "text": "Yes, my daily gratitude reflection practice led to a transformative realization and inner peace realization."},
            {"speaker": "Friend A", "text": "A meaningful memory spark from music helped me cultivate genuine gratitude for hardships."},
            {"speaker": "Friend B", "text": "Every struggle carried a priceless life lesson and treasured life lesson for us."},
            {"speaker": "Friend A", "text": "Revisiting old memories now brings smiles rather than sorrow."},
            {"speaker": "Friend B", "text": "This heartfelt personal reflection embodies our culminating life wisdom."}
        ],
        "vocabularyUsed": ["quiet moment of reflection", "youthful dream memory", "life crossroad choice", "overcoming past regret", "healing old wounds", "gratitude reflection practice", "transformative realization", "inner peace realization", "meaningful memory spark", "gratitude for hardships", "priceless life lesson", "treasured life lesson", "revisiting old memories", "heartfelt personal reflection", "culminating life wisdom"]
    }
]

paras_89 = [
    {
        "title": "Childhood Keepsakes, Nostalgia, and the Tapestry of Memory",
        "titleArabic": "مقتنيات الطفولة، الحنين، ونسيج الذكريات العميقة",
        "text": "Human memory functions as an intricate emotional tapestry woven from sensory recollections and lived experiences. Stumbling upon a cherished childhood keepsake or hearing an old melody often acts as a meaningful memory spark, unlocking vivid childhood home memories and poignant memories of departed loved ones. Engaging in nostalgic reflections and revisiting old memories evokes bittersweet recollections that remind us of how rapidly seasons pass. Families who faithfully preserve cherished family traditions pass down treasured nostalgic moments across generations. Ultimately, when individuals look back at childhood wonder memories with warmth rather than sorrow, they discover that nostalgic retrospection enriches the soul, grounding present existence in love and gratitude.",
        "vocabularyUsed": ["cherished childhood keepsake", "meaningful memory spark", "childhood home memory", "poignant memory", "nostalgic reflection", "revisiting old memories", "bittersweet recollection", "cherished family tradition", "treasured nostalgic moment", "childhood wonder memory"]
    },
    {
        "title": "Adversity, Turning Points, and Hard-Won Wisdom",
        "titleArabic": "المحن، نقاط التحول، والحكمة المستخلصة بعد عناء",
        "text": "True character is forged not in times of ease, but within the furnace of unexpected adversity. Every crisis presents a formative life lesson, marking a turning point moment where old assumptions shatter. When individuals experience humbling life experiences and absorb lessons in humility, they undergo profound perspective shift moments. Rather than succumbing to despair, those who practice growth through adversity discover enduring personal truths and cultivate deep life insights. Through rigorous past triumph reflections and honest past mistake realizations, they transform stumbling blocks into stepping stones. In retrospect, what seemed like unbearable failure emerges as an unforgettable life lesson, bequeathing hard-won wisdom that anchors a lifetime of leadership.",
        "vocabularyUsed": ["formative life lesson", "turning point moment", "humbling life experience", "lesson in humility", "perspective shift moment", "growth through adversity", "enduring personal truth", "deep life insight", "past triumph reflection", "past mistake realization", "unforgettable life lesson", "hard-won wisdom"]
    },
    {
        "title": "Reconciliation, Inner Peace, and Culminating Wisdom",
        "titleArabic": "التصالح مع الذات، السلام الداخلي، وذروة الحكمة",
        "text": "The crowning achievement of human maturation is arriving at peaceful self-acceptance and healing old wounds. For decades, many ruminate over life crossroad choices, wishing they had chosen differently. However, through regular gratitude reflection practices and quiet moments of reflection, one learns the art of forgiving past missteps and overcoming past regret. With the wisdom of hindsight and clarity of hindsight, reconciling past choices becomes natural, fostering gratitude for hardships that strengthened resilience. By embracing life lessons and recording heartfelt personal reflections, seekers arrive at an inner peace realization. This serene life acceptance and life journey gratitude represent the culminating life wisdom of a life courageously lived.",
        "vocabularyUsed": ["peaceful self-acceptance", "healing old wounds", "life crossroad choice", "gratitude reflection practice", "quiet moment of reflection", "forgiving past missteps", "overcoming past regret", "wisdom of hindsight", "clarity of hindsight", "reconciling past choices", "gratitude for hardships", "embracing life lessons", "heartfelt personal reflection", "inner peace realization", "serene life acceptance", "life journey gratitude", "culminating life wisdom"]
    }
]


# ==============================================================================
# DAY 90: Real-Life English Integration (Putting it all together)
# Grammar: Integrated Review of the 90-Day Journey
# ==============================================================================

vocab_90 = [
    # Fluency, Confidence & Autonomy
    {"headword": "communicative confidence", "pronunciation": "/kəˈmjuːnɪkətɪv ˈkɒnfɪdəns/", "partOfSpeech": "noun", "definition": "The assured, calm self-belief to express ideas clearly and without social hesitation in English.", "example": "Her communicative confidence soared after completing ninety consecutive days of spoken English practice.", "translation": "الثقة والجرأة في التواصل والتحدث بالإنجليزية", "collocations": ["gain communicative confidence", "radiate communicative confidence"], "synonyms": ["linguistic self-assurance"], "antonyms": ["speech inhibition"], "tags": ["fluency", "confidence"]},
    {"headword": "expressive fluency", "pronunciation": "/ɪkˈspresɪv ˈfluːənsi/", "partOfSpeech": "noun", "definition": "The effortless, rhythmic flow of spoken thoughts, nuances, and emotions without mental translation.", "example": "His expressive fluency allowed him to captivate international audiences during the keynote lecture.", "translation": "الطلاقة التعبيرية والقدرة على التعبير السلس", "collocations": ["develop expressive fluency", "demonstrate expressive fluency"], "synonyms": ["natural articulate flow"], "antonyms": ["halting speech"], "tags": ["fluency", "speaking"]},
    {"headword": "linguistic autonomy", "pronunciation": "/lɪŋˈɡwɪstɪk ɔːˈtɒnəmi/", "partOfSpeech": "noun", "definition": "The complete independence to read, write, converse, and learn in English without relying on a translator.", "example": "Achieving linguistic autonomy enabled the researcher to publish papers directly in international journals.", "translation": "الاستقلالية اللغوية والاعتماد الكامل على النفس", "collocations": ["attain linguistic autonomy", "foster linguistic autonomy"], "synonyms": ["language independence"], "antonyms": ["translation dependency"], "tags": ["autonomy", "learning"]},
    {"headword": "authentic voice discovery", "pronunciation": "/ɔːˈθentɪk vɔɪs dɪˈskʌvəri/", "partOfSpeech": "noun", "definition": "Finding one's true personal tone, humor, and intellectual character when communicating in a foreign language.", "example": "Writing essays daily led to her authentic voice discovery in contemporary English literature.", "translation": "اكتشاف الصوت والأسلوب التعبيري الأصيل للشخص", "collocations": ["culminate in authentic voice discovery", "pathway to authentic voice discovery"], "synonyms": ["personal expression emergence"], "antonyms": ["robotic repetition"], "tags": ["voice", "identity"]},
    {"headword": "mastery of nuance", "pronunciation": "/ˈmɑːstəri əv ˈnjuːɑːns/", "partOfSpeech": "noun", "definition": "The refined skill of understanding and using subtle shades of meaning, tone, sarcasm, and politeness.", "example": "Her mastery of nuance ensured that her diplomatic negotiations were both firm and exquisitely polite.", "translation": "إتقان الفروق الدقيقة والظلال اللغوية في التعبير", "collocations": ["exhibit mastery of nuance", "demonstrate mastery of nuance"], "synonyms": ["subtlety expertise"], "antonyms": ["blunt literalism"], "tags": ["nuance", "advanced"]},
    {"headword": "conversational ease", "pronunciation": "/ˌkɒnvəˈseɪʃənl iːz/", "partOfSpeech": "noun", "definition": "The natural, relaxed comfort experienced when engaging in small talk or deep dialogues with native speakers.", "example": "He chats with foreign tourists with a delightful conversational ease that instantly puts people at rest.", "translation": "السهولة والارتياح التام في إدارة الحوار والمحادثة", "collocations": ["speak with conversational ease", "develop conversational ease"], "synonyms": ["dialogue comfort"], "antonyms": ["conversational awkwardness"], "tags": ["speaking", "confidence"]},
    {"headword": "refined language intuition", "pronunciation": "/rɪˈfaɪnd ˈlæŋɡwɪdʒ ˌɪntjuˈɪʃn/", "partOfSpeech": "noun", "definition": "An instinctive feeling for what sounds grammatically natural without consciously recalling rules.", "example": "Through extensive reading, he developed a refined language intuition that guided his phrasing effortlessly.", "translation": "الحس والحدس اللغوي المرهف للأصالة النحوية", "collocations": ["cultivate refined language intuition", "trust refined language intuition"], "synonyms": ["linguistic instinct"], "antonyms": ["rule-bound hesitation"], "tags": ["intuition", "mastery"]},
    {"headword": "effortless code-switching", "pronunciation": "/ˈefətləs ˈkəʊd swɪtʃɪŋ/", "partOfSpeech": "noun", "definition": "The smooth, instantaneous transition between one's native language and English during conversation.", "example": "Bilingual translators demonstrate effortless code-switching between Arabic and English during live summits.", "translation": "التنقل السلس والفوري بين اللغات دون تلعثم", "collocations": ["master effortless code-switching", "exhibit effortless code-switching"], "synonyms": ["seamless language alternation"], "antonyms": [], "tags": ["bilingualism", "fluency"]},
    {"headword": "spontaneous expression skill", "pronunciation": "/spɒnˈteɪniəs ɪkˈspreʃn skɪl/", "partOfSpeech": "noun", "definition": "The ability to articulate thoughts, feelings, and arguments on the spot without memorized scripts.", "example": "Debating unexpected topics honed his spontaneous expression skill under intense studio pressure.", "translation": "مهارة التعبير العفوي والتلقائي المباشر", "collocations": ["sharpen spontaneous expression skills", "rely on spontaneous expression skill"], "synonyms": ["improvised eloquence"], "antonyms": ["scripted dependence"], "tags": ["speaking", "skills"]},
    {"headword": "rich descriptive vocabulary", "pronunciation": "/rɪtʃ dɪˈskrɪptɪv vəˈkæbjələri/", "partOfSpeech": "noun", "definition": "An expansive repertoire of evocative adjectives, verbs, and idioms that bring language vividly alive.", "example": "Her travel memoir was celebrated for its rich descriptive vocabulary capturing the Himalayan peaks.", "translation": "الثروة اللغوية والمفردات الوصفية الغنية والثرية", "collocations": ["possess a rich descriptive vocabulary", "employ a rich descriptive vocabulary"], "synonyms": ["evocative lexical range"], "antonyms": ["repetitive basic vocabulary"], "tags": ["vocabulary", "expression"]},

    # Discourse, Cross-Cultural Fluency & Eloquence
    {"headword": "confident public speech", "pronunciation": "/ˈkɒnfɪdənt ˈpʌblɪk spiːtʃ/", "partOfSpeech": "noun", "definition": "Delivering persuasive, clear, and inspiring presentations before large audiences in English.", "example": "Giving a confident public speech at the international conference was the pinnacle of his training.", "translation": "الخطابة والإلقاء العام الواثق أمام الجمهور", "collocations": ["deliver a confident public speech", "master confident public speech"], "synonyms": ["poised public presentation"], "antonyms": ["stage fright speech"], "tags": ["speaking", "public"]},
    {"headword": "cross-cultural fluency", "pronunciation": "/krɒs ˈkʌltʃərəl ˈfluːənsi/", "partOfSpeech": "noun", "definition": "The empathetic ability to communicate effectively across diverse cultural norms, idioms, and worldviews.", "example": "Working in multinational teams demands high cross-cultural fluency alongside grammatical proficiency.", "translation": "الطلاقة والتواصل الفعال العابر للثقافات المختلفة", "collocations": ["demonstrate cross-cultural fluency", "essential cross-cultural fluency"], "synonyms": ["intercultural competence"], "antonyms": ["cultural parochialism"], "tags": ["culture", "communication"]},
    {"headword": "linguistic self-assurance", "pronunciation": "/lɪŋˈɡwɪstɪk self əˈʃɔːrəns/", "partOfSpeech": "noun", "definition": "Quiet, internal certainty that one can handle any linguistic interaction or debate with composure.", "example": "Linguistic self-assurance allowed her to interview for executive positions in London without anxiety.", "translation": "الثقة اللغوية الراسخة والاطمئنان في الحديث", "collocations": ["exude linguistic self-assurance", "build linguistic self-assurance"], "synonyms": ["language composure"], "antonyms": ["linguistic insecurity"], "tags": ["confidence", "fluency"]},
    {"headword": "natural discourse mastery", "pronunciation": "/ˈnætʃrəl ˈdɪskɔːs ˈmɑːstəri/", "partOfSpeech": "noun", "definition": "Command of conversational turn-taking, interrupting politely, and structuring complex arguments naturally.", "example": "His natural discourse mastery made his podcast interviews sound delightfully spontaneous and engaging.", "translation": "التمكن والإتقان الطبيعي لإدارة النقاش والخطاب", "collocations": ["showcase natural discourse mastery", "achieve natural discourse mastery"], "synonyms": ["conversational flow expertise"], "antonyms": [], "tags": ["discourse", "advanced"]},
    {"headword": "idiomatic eloquence", "pronunciation": "/ˌɪdiəˈmætɪk ˈeləkwəns/", "partOfSpeech": "noun", "definition": "The graceful, natural use of idioms, phrasal expressions, and collocations in speech and prose.", "example": "Her essays are renowned for their idiomatic eloquence, blending classic prose with contemporary expressions.", "translation": "الفصاحة والبلاغة التعبيرية في توظيف التعبيرات الاصطلاحية", "collocations": ["speak with idiomatic eloquence", "write with idiomatic eloquence"], "synonyms": ["idiomatic articulacy"], "antonyms": ["literal phrasing"], "tags": ["idioms", "eloquence"]},
    {"headword": "spontaneous speech delivery", "pronunciation": "/spɒnˈteɪniəs spiːtʃ dɪˈlɪvəri/", "partOfSpeech": "noun", "definition": "Producing fluid, organized spoken responses instantly without hesitation or reading from notes.", "example": "Her spontaneous speech delivery won over the judges during the impromptu debate finals.", "translation": "الإلقاء والتحدث الارتجالي العفوي المتقن", "collocations": ["flawless spontaneous speech delivery", "practice spontaneous speech delivery"], "synonyms": ["extemporaneous speaking"], "antonyms": ["hesitant stuttering"], "tags": ["speaking", "fluency"]},
    {"headword": "polyglot learning mindset", "pronunciation": "/ˈpɒliɡlɒt ˈlɜːnɪŋ ˈmaɪndset/", "partOfSpeech": "noun", "definition": "An open, curious, and fearless approach to language acquisition that treats mistakes as growth data.", "example": "Adopting a polyglot learning mindset transforms grammar study from a burden into an exhilarating puzzle.", "translation": "عقلية وفلسفة شغف تعلم اللغات المتعددة", "collocations": ["adopt a polyglot learning mindset", "embrace a polyglot learning mindset"], "synonyms": ["multilingual learning attitude"], "antonyms": ["language dread"], "tags": ["mindset", "learning"]},
    {"headword": "depth of comprehension", "pronunciation": "/depθ əv ˌkɒmprɪˈhenʃn/", "partOfSpeech": "noun", "definition": "The profound ability to understand complex literature, legal subtleties, fast dialogue, and subtext in English.", "example": "Her depth of comprehension allowed her to appreciate Victorian poetry and rapid American podcasts equally.", "translation": "عمق الاستيعاب والفهم الدقيق للمحتوى والسياق", "collocations": ["expand depth of comprehension", "remarkable depth of comprehension"], "synonyms": ["profound understanding"], "antonyms": ["superficial grasp"], "tags": ["listening", "reading"]},
    {"headword": "empowered language speaker", "pronunciation": "/ɪmˈpaʊəd ˈlæŋɡwɪdʒ ˈspiːkə/", "partOfSpeech": "noun", "definition": "A learner who has transcended fear and self-doubt to use English as an instrument of authority and agency.", "example": "Stepping onto the global stage, she spoke not as an anxious student, but as an empowered language speaker.", "translation": "المتحدث اللغوي المتمكن والمفوض بقدراته", "collocations": ["emerge as an empowered language speaker", "become an empowered language speaker"], "synonyms": ["self-directed speaker"], "antonyms": ["inhibited learner"], "tags": ["empowerment", "identity"]},
    {"headword": "articulate self-expression", "pronunciation": "/ɑːˈtɪkjələt self ɪkˈspreʃn/", "partOfSpeech": "noun", "definition": "The capacity to convey one's thoughts, emotions, and values with crystalline clarity and precision.", "example": "Articulate self-expression in a second language requires patience, wide vocabulary, and dedicated practice.", "translation": "التعبير الواضح والمفصح عن الذات والأفكار", "collocations": ["master articulate self-expression", "strive for articulate self-expression"], "synonyms": ["lucid self-articulation"], "antonyms": ["inarticulate rambling"], "tags": ["speaking", "expression"]},

    # Milestones, Breakthroughs & Empowerment
    {"headword": "autonomous language journey", "pronunciation": "/ɔːˈtɒnəməs ˈlæŋɡwɪdʒ ˈdʒɜːni/", "partOfSpeech": "noun", "definition": "The lifelong process of self-directed language exploration independent of classroom instruction.", "example": "Completing this course marks the beginning of your autonomous language journey as a lifelong reader and thinker.", "translation": "رحلة ومسيرة التعلم والتمكن اللغوي المستقلة", "collocations": ["continue an autonomous language journey", "embark on an autonomous language journey"], "synonyms": ["self-guided language voyage"], "antonyms": ["dependent learning"], "tags": ["learning", "autonomy"]},
    {"headword": "cultural communication bridge", "pronunciation": "/ˈkʌltʃərəl kəˌmjuːnɪˈkeɪʃn brɪdʒ/", "partOfSpeech": "noun", "definition": "An English speaker who acts as a connector, fostering harmony between disparate language communities.", "example": "Fluent bilinguals serve as living cultural communication bridges across international divides.", "translation": "جسر التواصل والتقارب الثقافي بين الشعوب", "collocations": ["act as a cultural communication bridge", "serve as a cultural communication bridge"], "synonyms": ["intercultural ambassador"], "antonyms": [], "tags": ["culture", "communication"]},
    {"headword": "celebration of progress", "pronunciation": "/ˌselɪˈbreɪʃn əv ˈprəʊɡres/", "partOfSpeech": "noun", "definition": "Joyfully honoring how far one has advanced from elementary basics to advanced communicative mastery.", "example": "Graduation day on Day 90 is an emotional celebration of progress, discipline, and perseverance.", "translation": "الاحتفال والاعتزاز بالتقدم والإنجاز المحرز", "collocations": ["join in celebration of progress", "mark a celebration of progress"], "synonyms": ["tribute to advancement"], "antonyms": ["minimizing achievements"], "tags": ["celebration", "milestones"]},
    {"headword": "linguistic empowerment", "pronunciation": "/lɪŋˈɡwɪstɪk ɪmˈpaʊəmənt/", "partOfSpeech": "noun", "definition": "The feeling of agency, freedom, and global opportunity bestowed by mastering world communication.", "example": "Linguistic empowerment unlocked international job opportunities and personal independence for him.", "translation": "التمكين والتحرر اللغوي لفتح آفاق العالم", "collocations": ["experience linguistic empowerment", "catalyst for linguistic empowerment"], "synonyms": ["communicative sovereignty"], "antonyms": ["linguistic marginalization"], "tags": ["empowerment", "confidence"]},
    {"headword": "triumphant milestone", "pronunciation": "/traɪˈʌmfənt ˈmaɪlstəʊn/", "partOfSpeech": "noun", "definition": "A glorious, hard-won benchmark signifying the successful completion of a monumental undertaking.", "example": "Finishing the final day of the ninety-day English curriculum was a triumphant milestone for all participants.", "translation": "محطة وإنجاز نصر تتويجي باهر ومشرّف", "collocations": ["reach a triumphant milestone", "celebrate a triumphant milestone"], "synonyms": ["crowning accomplishment"], "antonyms": ["aborted attempt"], "tags": ["milestones", "celebration"]},
    {"headword": "fluency breakthrough moment", "pronunciation": "/ˈfluːənsi ˈbreɪkθruː ˈməʊmənt/", "partOfSpeech": "noun", "definition": "The magical instant when one realizes they are speaking or thinking in English effortlessly without translating.", "example": "Laughing at an English joke without translating in his head was his definitive fluency breakthrough moment.", "translation": "لحظة وطفرة الاختراق والانطلاق في الطلاقة", "collocations": ["experience a fluency breakthrough moment", "celebrate a fluency breakthrough moment"], "synonyms": ["spontaneous fluency leap"], "antonyms": [], "tags": ["fluency", "breakthrough"]},
    {"headword": "lifelong language pursuit", "pronunciation": "/ˈlaɪflɒŋ ˈlæŋɡwɪdʒ pəˈsjuːt/", "partOfSpeech": "noun", "definition": "Viewing language mastery not as a finished course, but as an endless voyage of reading and growth.", "example": "True eloquence comes from treating English as a lifelong language pursuit filled with wonder.", "translation": "المسعى والرحلة اللغوية المستمرة مدى الحياة", "collocations": ["embrace a lifelong language pursuit", "commit to a lifelong language pursuit"], "synonyms": ["endless language quest"], "antonyms": ["temporary study cram"], "tags": ["learning", "dedication"]},
    {"headword": "natural English speaker", "pronunciation": "/ˈnætʃrəl ˈɪŋɡlɪʃ ˈspiːkə/", "partOfSpeech": "noun", "definition": "A communicator who uses English with organic ease, authentic phrasing, and intuitive rhythm.", "example": "With his effortless idioms and relaxed cadence, he communicates like a natural English speaker.", "translation": "المتحدث الطبيعي للإنجليزية بسلاسة وعفوية", "collocations": ["sound like a natural English speaker", "evolve into a natural English speaker"], "synonyms": ["instinctive English communicator"], "antonyms": ["mechanical speaker"], "tags": ["fluency", "speaking"]},
    {"headword": "expressive language mastery", "pronunciation": "/ɪkˈspresɪv ˈlæŋɡwɪdʒ ˈmɑːstəri/", "partOfSpeech": "noun", "definition": "The highest level of eloquence, enabling precise conveyance of abstract thoughts, art, and complex philosophy.", "example": "Her essays demonstrate expressive language mastery, blending analytical rigor with poetic grace.", "translation": "التمكن والإتقان التعبيري اللغوي الرفيع", "collocations": ["attain expressive language mastery", "showcase expressive language mastery"], "synonyms": ["supreme communicative command"], "antonyms": ["rudimentary expression"], "tags": ["mastery", "eloquence"]},
    {"headword": "confident debate skills", "pronunciation": "/ˈkɒnfɪdənt dɪˈbeɪt skɪlz/", "partOfSpeech": "noun", "definition": "The persuasive ability to defend complex arguments and counter differing viewpoints in English discussions.", "example": "Participating in model United Nations conferences polished her confident debate skills.", "translation": "مهارات المناظرة والنقاش الواثق والمقنع", "collocations": ["hone confident debate skills", "employ confident debate skills"], "synonyms": ["persuasive argumentation skill"], "antonyms": ["timid agreement"], "tags": ["debate", "speaking"]},

    # Nuances, Repertoire & Global Citizenship
    {"headword": "mastery of spoken nuances", "pronunciation": "/ˈmɑːstəri əv ˈspəʊkən ˈnjuːɑːnsɪz/", "partOfSpeech": "noun", "definition": "Comprehending and producing subtle intonations, irony, humor, and subtext in casual speech.", "example": "His mastery of spoken nuances allowed him to fit in immediately at British dinner parties.", "translation": "إتقان اللمسات والنبرات الدقيقة في الكلام المنطوق", "collocations": ["develop mastery of spoken nuances", "demonstrate mastery of spoken nuances"], "synonyms": ["conversational subtlety command"], "antonyms": [], "tags": ["speaking", "advanced"]},
    {"headword": "authentic communication flow", "pronunciation": "/ɔːˈθentɪk kəˌmjuːnɪˈkeɪʃn fləʊ/", "partOfSpeech": "noun", "definition": "An uninterrupted exchange of ideas where both speakers feel genuine emotional and intellectual connection.", "example": "Overcoming perfectionism unlocked an authentic communication flow between the foreign exchange partners.", "translation": "تدفق التواصل الطبيعي والصادق والحي", "collocations": ["achieve authentic communication flow", "foster authentic communication flow"], "synonyms": ["genuine dialogue cadence"], "antonyms": ["stilted interaction"], "tags": ["communication", "authenticity"]},
    {"headword": "linguistic versatility", "pronunciation": "/lɪŋˈɡwɪstɪk ˌvɜːsəˈtɪləti/", "partOfSpeech": "noun", "definition": "The adaptability to transition effortlessly from formal academic lectures to casual street banter.", "example": "A professional interpreter needs immense linguistic versatility to handle both diplomatic and cultural idioms.", "translation": "المرونة والتنوع اللغوي للتعامل مع مختلف السياقات", "collocations": ["exhibit linguistic versatility", "cultivate linguistic versatility"], "synonyms": ["verbal adaptability"], "antonyms": ["rigid monotony"], "tags": ["versatility", "mastery"]},
    {"headword": "deep language confidence", "pronunciation": "/diːp ˈlæŋɡwɪdʒ ˈkɒnfɪdəns/", "partOfSpeech": "noun", "definition": "A foundational inner composure that eliminates fear of making grammatical slips in public.", "example": "Having deep language confidence means knowing you can navigate any conversation gracefully.", "translation": "الثقة اللغوية الداخلية العميقة والراسخة", "collocations": ["instill deep language confidence", "radiate deep language confidence"], "synonyms": ["unshakeable linguistic poise"], "antonyms": ["speech anxiety"], "tags": ["confidence", "fluency"]},
    {"headword": "spontaneous spoken eloquence", "pronunciation": "/spɒnˈteɪniəs ˈspəʊkən ˈeləkwəns/", "partOfSpeech": "noun", "definition": "The gift of formulating poetic, moving, or brilliantly clear speech without written preparation.", "example": "His impromptu toast at the wedding was a stunning display of spontaneous spoken eloquence.", "translation": "البلاغة والفصاحة الشفهية الارتجالية الساحرة", "collocations": ["blessed with spontaneous spoken eloquence", "deliver spontaneous spoken eloquence"], "synonyms": ["impromptu articulacy"], "antonyms": ["awkward fumbling"], "tags": ["eloquence", "speaking"]},
    {"headword": "confident language user", "pronunciation": "/ˈkɒnfɪdənt ˈlæŋɡwɪdʒ ˈjuːzə/", "partOfSpeech": "noun", "definition": "A person who employs English actively and comfortably as a primary medium for living, working, and thinking.", "example": "Graduating from Day 90 transforms you into an independent, confident language user.", "translation": "المستخدم الواثق والمتمكن من توظيف اللغة", "collocations": ["become a confident language user", "traits of a confident language user"], "synonyms": ["autonomous English user"], "antonyms": ["hesitant learner"], "tags": ["identity", "confidence"]},
    {"headword": "mastery of idioms", "pronunciation": "/ˈmɑːstəri əv ˈɪdiəmz/", "partOfSpeech": "noun", "definition": "The comprehensive command of figurative expressions, sayings, and phrasal idioms in daily dialogue.", "example": "Her mastery of idioms made her speech sound vibrant, colorful, and naturally native.", "translation": "إتقان وحفظ واستخدام التعبيرات الاصطلاحية", "collocations": ["demonstrate mastery of idioms", "comprehensive mastery of idioms"], "synonyms": ["figurative fluency"], "antonyms": [], "tags": ["idioms", "vocabulary"]},
    {"headword": "rich conversational repertoire", "pronunciation": "/rɪtʃ ˌkɒnvəˈseɪʃənl ˈrepətwɑː/", "partOfSpeech": "noun", "definition": "An extensive range of discussion topics, anecdotes, questions, and rejoinders that keep dialogue lively.", "example": "His rich conversational repertoire made him the most popular and captivating guest at every dinner.", "translation": "رصيد وحصيلة حوارية ثرية لإثراء أي نقاش", "collocations": ["draw upon a rich conversational repertoire", "possess a rich conversational repertoire"], "synonyms": ["extensive dialogue range"], "antonyms": [], "tags": ["conversation", "speaking"]},
    {"headword": "joy of bilingualism", "pronunciation": "/dʒɔɪ əv baɪˈlɪŋɡwəlɪzəm/", "partOfSpeech": "noun", "definition": "The delightful cognitive and emotional expansion of seeing the world through two distinct linguistic lenses.", "example": "Reading poetry in both Arabic and English opened her mind to the exquisite joy of bilingualism.", "translation": "متعة وفرحة إتقان وازدواجية اللغتين", "collocations": ["experience the joy of bilingualism", "celebrate the joy of bilingualism"], "synonyms": ["dual-language fulfillment"], "antonyms": [], "tags": ["bilingualism", "joy"]},
    {"headword": "confident world communicator", "pronunciation": "/ˈkɒnfɪdənt wɜːld kəˈmjuːnɪkeɪtə/", "partOfSpeech": "noun", "definition": "A global citizen capable of interacting respectfully and articulately with people of all nationalities.", "example": "Her multicultural background shaped her into a confident world communicator bridging continents.", "translation": "المتواصل العالمي الواثق والمنفتح على العالم", "collocations": ["evolve into a confident world communicator", "global role as a confident world communicator"], "synonyms": ["international communicator"], "antonyms": [], "tags": ["global", "communication"]},
    {"headword": "seamless English fluency", "pronunciation": "/ˈsiːmləs ˈɪŋɡlɪʃ ˈfluːənsi/", "partOfSpeech": "noun", "definition": "A state of language mastery where words arise automatically without hesitation or grammatical friction.", "example": "Ninety days of immersive discipline culminated in seamless English fluency across business and social life.", "translation": "الطلاقة الإنجليزية السلسة والانسيابية تماماً", "collocations": ["achieve seamless English fluency", "attain seamless English fluency"], "synonyms": ["effortless English command"], "antonyms": ["halting language"], "tags": ["fluency", "mastery"]},
    {"headword": "elevated language style", "pronunciation": "/ˈelɪveɪtɪd ˈlæŋɡwɪdʒ staɪl/", "partOfSpeech": "noun", "definition": "A sophisticated, eloquent register of English appropriate for literature, formal diplomacy, and academic thought.", "example": "His essay was celebrated for its elevated language style, reminiscent of classic nineteenth-century prose.", "translation": "الأسلوب اللغوي الراقي والرفيع في التعبير", "collocations": ["adopt an elevated language style", "write with an elevated language style"], "synonyms": ["sophisticated linguistic register"], "antonyms": ["crude slang"], "tags": ["style", "advanced"]},
    {"headword": "lifelong English journey", "pronunciation": "/ˈlaɪflɒŋ ˈɪŋɡlɪʃ ˈdʒɜːni/", "partOfSpeech": "noun", "definition": "Viewing English as a lifelong companion for exploring global literature, business, and human relationships.", "example": "Day 90 is not the end of learning, but the glorious commencement of your lifelong English journey.", "translation": "رحلة ومسيرة تعلم واستخدام الإنجليزية مدى الحياة", "collocations": ["continue your lifelong English journey", "cherish the lifelong English journey"], "synonyms": ["enduring English voyage"], "antonyms": [], "tags": ["learning", "journey"]},
    {"headword": "proud learning achievement", "pronunciation": "/praʊd ˈlɜːnɪŋ əˈtʃiːvmənt/", "partOfSpeech": "noun", "definition": "A monumental educational triumph earned through consistent discipline that evokes deep satisfaction.", "example": "Mastering 4,500 words and ninety grammatical structures was a proud learning achievement for the entire cohort.", "translation": "إنجاز تعليمي فخور ومستحق يبعث على الاعتزاز", "collocations": ["celebrate a proud learning achievement", "represent a proud learning achievement"], "synonyms": ["honorable academic milestone"], "antonyms": [], "tags": ["achievement", "pride"]},
    {"headword": "communicative triumph", "pronunciation": "/kəˈmjuːnɪkətɪv ˈtraɪʌmf/", "partOfSpeech": "noun", "definition": "The victorious breakthrough of overcoming all language barriers and speaking with natural power.", "example": "Delivering an impromptu English presentation before foreign delegates was a personal communicative triumph.", "translation": "نصر وإنجاز تواصلي عظيم ومؤثر", "collocations": ["mark a communicative triumph", "experience a communicative triumph"], "synonyms": ["dialogue victory"], "antonyms": ["communication breakdown"], "tags": ["triumph", "fluency"]},
    {"headword": "empowered global citizen", "pronunciation": "/ɪmˈpaʊəd ˈɡləʊbl ˈsɪtɪzn/", "partOfSpeech": "noun", "definition": "An individual equipped with language mastery, cultural empathy, and agency to participate in international discourse.", "example": "Fluency in English transforms you into an empowered global citizen capable of advocating for world progress.", "translation": "المواطن العالمي المتمكن والقادر على التأثير دولياً", "collocations": ["become an empowered global citizen", "stand as an empowered global citizen"], "synonyms": ["cosmopolitan agent"], "antonyms": [], "tags": ["identity", "global"]},
    {"headword": "natural expressive flow", "pronunciation": "/ˈnætʃrəl ɪkˈspresɪv fləʊ/", "partOfSpeech": "noun", "definition": "The spontaneous, uninhibited streaming of spoken or written ideas in harmony with natural English cadence.", "example": "When she speaks, her natural expressive flow makes complex philosophical ideas feel effortlessly clear.", "translation": "الانسياب التعبيري الطبيعي والتلقائي للكلام", "collocations": ["maintain a natural expressive flow", "speak with natural expressive flow"], "synonyms": ["organic verbal rhythm"], "antonyms": ["stilted phrasing"], "tags": ["speaking", "fluency"]},
    {"headword": "confident conversationalist", "pronunciation": "/ˈkɒnfɪdənt ˌkɒnvəˈseɪʃənəlɪst/", "partOfSpeech": "noun", "definition": "A person who initiates, enriches, and navigates conversations on any topic with warmth, wit, and poise.", "example": "Completing this curriculum turned him from a shy listener into an engaging, confident conversationalist.", "translation": "المحاور والمحدث البارع الواثق من نفسه", "collocations": ["evolve into a confident conversationalist", "acclaimed confident conversationalist"], "synonyms": ["poised dialogue partner"], "antonyms": ["hesitant wallflower"], "tags": ["conversation", "identity"]},
    {"headword": "rich linguistic repertoire", "pronunciation": "/rɪtʃ lɪŋˈɡwɪstɪk ˈrepətwɑː/", "partOfSpeech": "noun", "definition": "A vast collection of vocabulary, idioms, grammar structures, and stylistic registers at one's command.", "example": "Mastering 4,500 unique headwords equips you with a rich linguistic repertoire for any professional field.", "translation": "الذخيرة والحصيلة اللغوية الثرية والمتنوعة", "collocations": ["command a rich linguistic repertoire", "expand a rich linguistic repertoire"], "synonyms": ["comprehensive language arsenal"], "antonyms": ["scanty vocabulary"], "tags": ["vocabulary", "mastery"]},
    {"headword": "enduring fluency commitment", "pronunciation": "/ɪnˈdjʊərɪŋ ˈfluːənsi kəˈmɪtmənt/", "partOfSpeech": "noun", "definition": "The lifelong pledge to read, listen, speak, and write in English daily to maintain and elevate mastery.", "example": "Graduation is not the end, but the confirmation of your enduring fluency commitment for years to come.", "translation": "الالتزام الدائم والمستمر بالحفاظ على الطلاقة وتطويرها", "collocations": ["honor an enduring fluency commitment", "renew your enduring fluency commitment"], "synonyms": ["perpetual fluency pledge"], "antonyms": ["abandoning practice"], "tags": ["commitment", "fluency"]}
]

grammar_90 = [
    {
        "title": "Integrated Review of the 90-Day Journey",
        "explanation": "Day 90 represents the culmination of our entire 90-day English mastery architecture. Across nine comprehensive stages and 4,500 unique vocabulary items, we have mastered every core dimension of English grammar and discourse:\n\n1. Foundational Tenses & Aspects (Stages 1–3):\n   - Present, Past, and Future Simple; Continuous and Perfect aspects.\n   - Stative verbs, time clauses, and natural frequency markers.\n\n2. Modality, Conditionals & Hypothetical Thought (Stages 4–6):\n   - Modal auxiliaries for deduction, obligation, permission, and polite requests.\n   - Real and unreal conditionals (Zero, First, Second, Third, and Mixed).\n   - Wish, hypothetical subjunctive, and reported discourse structures.\n\n3. Advanced Syntax, Inversion & Rhetorical Flow (Stages 7–9):\n   - Passive voice across all tenses and causative constructions ('have/get something done').\n   - Participle clauses, cleft sentences for emphasis ('It is... that...'), and negative inversion ('Not only... but also...').\n   - Nuanced transition connectors and stance markers for articulate debate.\n\nToday, these structures harmonize into seamless English fluency. You no longer analyze grammar rules mechanically; you embody them instinctively as an empowered global citizen.",
        "structures": [
            {"pattern": "Grand Synthesis with Inversion: 'Not only + auxiliary + Subject + verb, but Subject also + verb': 'Not only have you achieved communicative confidence, but you have also unlocked linguistic autonomy.'"},
            {"pattern": "Cleft Focus Sentence: 'What + Subject + verb + is / was + noun phrase': 'What this 90-day journey has forged is deep language confidence and an enduring fluency commitment.'"},
            {"pattern": "Concessive Participle Clause: 'Having + V3, Subject + verb': 'Having mastered 4,500 headwords, you stand today as an empowered language speaker and confident world communicator.'"}
        ],
        "examples": [
            {
                "sentence": "Not only have you achieved seamless English fluency, but you have also gained complete linguistic autonomy.",
                "arabic": "لم تكتسب فقط طلاقة إنجليزية سلسة، بل حزت أيضاً استقلالية لغوية كاملة.",
                "usesVocabulary": ["seamless English fluency", "linguistic autonomy"]
            },
            {
                "sentence": "What this ninety-day journey has forged is deep language confidence and an authentic voice discovery.",
                "arabic": "إن ما صنعته هذه الرحلة الممتدة لتسعين يوماً هو ثقة لغوية عميقة واكتشاف أصيل لصوتك وتعبيرك الخاص.",
                "usesVocabulary": ["deep language confidence", "authentic voice discovery"]
            },
            {
                "sentence": "Having mastered a rich linguistic repertoire, you stand today as an empowered global citizen.",
                "arabic": "بعد أن أتقنت حصيلة وذخيرة لغوية ثرية، تقف اليوم كمواطن عالمي متمكن قادر على العطاء.",
                "usesVocabulary": ["rich linguistic repertoire", "empowered global citizen"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "Not only I achieved fluency, but also I gained confidence.",
                "right": "Not only did I achieve fluency, but I also gained confidence.",
                "explanation": "When starting a sentence with negative/restrictive phrases like 'Not only', use subject-auxiliary inversion ('did I achieve')."
            },
            {
                "wrong": "Day 90 is the finish of my learning.",
                "right": "Day 90 is the celebration of my progress and the start of my lifelong English journey.",
                "explanation": "Language mastery is an ongoing journey ('lifelong English journey'), not a finite event."
            }
        ]
    }
]

convs_90 = [
    {
        "title": "Day 90 Commencement: Celebrating the 90-Day Summit",
        "titleArabic": "حفل التخرج في اليوم التسعين: الاحتفال بقمة الرحلة",
        "setting": "The lead curriculum instructor congratulates a graduating student on completing Day 90.",
        "lines": [
            {"speaker": "Instructor", "text": "Welcome to Day 90! Reaching this triumphant milestone is a proud learning achievement and a true communicative triumph."},
            {"speaker": "Graduate", "text": "Thank you! When I started on Day 1, I had severe speech hesitation. Today, I feel immense communicative confidence."},
            {"speaker": "Instructor", "text": "You have developed genuine expressive fluency, conversational ease, and a refined language intuition."},
            {"speaker": "Graduate", "text": "My fluency breakthrough moment happened when I realized I was speaking with spontaneous expression skills without mental translation."},
            {"speaker": "Instructor", "text": "Indeed! You command a rich descriptive vocabulary and complete mastery of idioms."},
            {"speaker": "Graduate", "text": "This celebration of progress marks my transformation into a confident language user and empowered language speaker."},
            {"speaker": "Instructor", "text": "You stand today as an empowered global citizen ready to conquer any international challenge."},
            {"speaker": "Graduate", "text": "I pledge an enduring fluency commitment to honor this autonomous language journey forever."}
        ],
        "vocabularyUsed": ["triumphant milestone", "proud learning achievement", "communicative triumph", "communicative confidence", "expressive fluency", "conversational ease", "refined language intuition", "fluency breakthrough moment", "spontaneous expression skill", "rich descriptive vocabulary", "mastery of idioms", "celebration of progress", "confident language user", "empowered language speaker", "empowered global citizen", "enduring fluency commitment", "autonomous language journey"]
    },
    {
        "title": "Global Summit Panel: Cultural Fluency and Discourse",
        "titleArabic": "ندوة القمة العالمية: الطلاقة الثقافية وإدارة الخطاب",
        "setting": "Two bilingual delegates converse before delivering keynotes at an international summit.",
        "lines": [
            {"speaker": "Delegate A", "text": "Delivering a confident public speech before two thousand international delegates requires complete linguistic self-assurance."},
            {"speaker": "Delegate B", "text": "True, but what makes dialogue memorable is natural discourse mastery and effortless code-switching between cultures."},
            {"speaker": "Delegate A", "text": "Our role as a cultural communication bridge demands deep cross-cultural fluency and mastery of nuance."},
            {"speaker": "Delegate B", "text": "When we speak with idiomatic eloquence, audiences immediately connect with our message."},
            {"speaker": "Delegate A", "text": "Your spontaneous speech delivery and confident debate skills during yesterday's round-table were magnificent."},
            {"speaker": "Delegate B", "text": "I simply embrace a polyglot learning mindset and trust my depth of comprehension."},
            {"speaker": "Delegate A", "text": "It is wonderful to experience the true joy of bilingualism together."},
            {"speaker": "Delegate B", "text": "We communicate not merely with words, but with heartfelt cultural empathy."}
        ],
        "vocabularyUsed": ["confident public speech", "linguistic self-assurance", "natural discourse mastery", "effortless code-switching", "cultural communication bridge", "cross-cultural fluency", "mastery of nuance", "idiomatic eloquence", "spontaneous speech delivery", "confident debate skills", "polyglot learning mindset", "depth of comprehension", "joy of bilingualism"]
    },
    {
        "title": "Lifelong Horizon: The Future of Your English",
        "titleArabic": "أفق الحياة المستمر: مستقبل لغتك الإنجليزية",
        "setting": "Two alumni reflect on their English transformation and plans for continuous reading.",
        "lines": [
            {"speaker": "Alum A", "text": "Reflecting on our journey, achieving linguistic autonomy was our greatest turning point."},
            {"speaker": "Alum B", "text": "I agree. Discovering my authentic voice gave me deep language confidence to write and speak freely."},
            {"speaker": "Alum A", "text": "Our mastery of spoken nuances and authentic communication flow makes conversations delightful."},
            {"speaker": "Alum B", "text": "I love drawing upon our rich conversational repertoire and switching between casual and elevated language styles."},
            {"speaker": "Alum A", "text": "Commanding a rich linguistic repertoire transforms us into confident world communicators and natural English speakers."},
            {"speaker": "Alum B", "text": "Our natural expressive flow and spontaneous spoken eloquence will open doors across the globe."},
            {"speaker": "Alum A", "text": "Day 90 is not a conclusion, but the doorway to our lifelong English journey."},
            {"speaker": "Alum B", "text": "We are equipped forever as confident conversationalists and passionate thinkers."}
        ],
        "vocabularyUsed": ["linguistic autonomy", "authentic voice discovery", "deep language confidence", "mastery of spoken nuances", "authentic communication flow", "rich conversational repertoire", "elevated language style", "rich linguistic repertoire", "confident world communicator", "natural English speaker", "natural expressive flow", "spontaneous spoken eloquence", "lifelong English journey", "confident conversationalist"]
    }
]

paras_90 = [
    {
        "title": "Communicative Confidence, Autonomy, and Authentic Voice Discovery",
        "titleArabic": "الثقة في التواصل، الاستقلالية اللغوية، واكتشاف الصوت الأصيل",
        "text": "The culmination of a rigorous ninety-day English immersion represents a profound transformation in human identity. Moving beyond fragmented word translation, learners cultivate genuine communicative confidence and effortless expressive fluency. By reading, listening, and speaking daily, students attain linguistic autonomy, trusting their refined language intuition without checking rules mechanically. This liberating process sparks an authentic voice discovery, allowing one's true humor, values, and intellectual depth to emerge in English with conversational ease. Whether engaging in spontaneous expression skills or demonstrating mastery of nuance, learners communicate with relaxed poise. Supported by a rich descriptive vocabulary, bilingual speakers navigate conversations with effortless code-switching, standing tall as empowered language speakers.",
        "vocabularyUsed": ["communicative confidence", "expressive fluency", "linguistic autonomy", "refined language intuition", "authentic voice discovery", "conversational ease", "spontaneous expression skill", "mastery of nuance", "rich descriptive vocabulary", "effortless code-switching", "empowered language speaker"]
    },
    {
        "title": "Cross-Cultural Fluency, Eloquence, and Discourse Command",
        "titleArabic": "الطلاقة عبر الثقافات، البلاغة، والتمكن من إدارة الخطاب",
        "text": "In our interconnected world, English operates as far more than an academic subject; it is the universal cultural communication bridge connecting diverse nations. True eloquence emerges when speakers unite confident public speech with deep cross-cultural fluency and natural discourse mastery. By absorbing an expansive depth of comprehension and practicing spontaneous speech delivery, learners master idiomatic eloquence, utilizing figurative phrases with instinctive grace. Backed by a polyglot learning mindset and linguistic self-assurance, speakers engage in confident debate skills without intimidation. They transcend basic transactional exchanges, fostering authentic communication flows and mastering the spoken nuances that underpin enduring international friendships and professional leadership.",
        "vocabularyUsed": ["cultural communication bridge", "confident public speech", "cross-cultural fluency", "natural discourse mastery", "depth of comprehension", "spontaneous speech delivery", "idiomatic eloquence", "polyglot learning mindset", "linguistic self-assurance", "confident debate skills", "authentic communication flow", "mastery of spoken nuances"]
    },
    {
        "title": "Triumphant Milestones, Global Citizenship, and the Lifelong Journey",
        "titleArabic": "محطات النصر، المواطنة العالمية، ورحلة العمر المستمرة",
        "text": "Reaching Day 90 is a triumphant milestone, a proud learning achievement, and an undeniable communicative triumph that will resonate throughout your lifetime. Mastering 4,500 unique headwords equips learners with a rich linguistic repertoire and an expansive conversational repertoire suitable for any professional sector. You now command seamless English fluency, an elevated language style, and deep language confidence, taking rightful place as an empowered global citizen and confident world communicator. Today's celebration of progress honors your discipline and dedication. As you continue this autonomous language journey, embrace English not as a finite test, but as a lifelong English journey and an enduring fluency commitment to human flourishing.",
        "vocabularyUsed": ["triumphant milestone", "proud learning achievement", "communicative triumph", "rich linguistic repertoire", "rich conversational repertoire", "seamless English fluency", "elevated language style", "deep language confidence", "empowered global citizen", "confident world communicator", "celebration of progress", "autonomous language journey", "lifelong English journey", "enduring fluency commitment"]
    }
]

if __name__ == "__main__":
    write_day(89, vocab_89, grammar_89, convs_89, paras_89)
    write_day(90, vocab_90, grammar_90, convs_90, paras_90)
    print("Day 89 and Day 90 generated successfully.")
