# -*- coding: utf-8 -*-
"""Generate Day 75 and Day 76 for Stage 8."""

import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from curriculum_engine import write_day

# ==============================================================================
# DAY 75: Society and Community (Community issues and citizenship)
# Grammar: Non-defining Relative Clauses
# ==============================================================================

vocab_75 = [
    # Civic Life, Activism & Governance
    {"headword": "civic engagement", "pronunciation": "/ˈsɪvɪk ɪnˈɡeɪdʒmənt/", "partOfSpeech": "noun", "definition": "Active participation by citizens in political, social, and community activities to address public concerns.", "example": "Voter registration drives and volunteer initiatives foster vibrant civic engagement across diverse neighborhoods.", "translation": "المشاركة المدنية الفعالة في القضايا العامة", "collocations": ["promote civic engagement", "high levels of civic engagement"], "synonyms": ["citizen participation"], "antonyms": ["civic apathy"], "tags": ["community", "politics"]},
    {"headword": "grassroots movement", "pronunciation": "/ˈɡrɑːsruːts ˈmuːvmənt/", "partOfSpeech": "noun", "definition": "A political or social movement organized from local community members at the bottom rather than top-down leaders.", "example": "What began as a localized grassroots movement quickly grew into an international climate coalition.", "translation": "حركة شعبية قاعدية نابعة من المجتمع المحلي", "collocations": ["lead a grassroots movement", "grassroots movement organized"], "synonyms": ["popular campaign", "bottom-up movement"], "antonyms": ["top-down initiative"], "tags": ["politics", "activism"]},
    {"headword": "community organizing", "pronunciation": "/kəˈmjuːnəti ˈɔːɡənaɪzɪŋ/", "partOfSpeech": "noun", "definition": "The process of bringing residents together to build collective power and resolve community challenges.", "example": "Through community organizing, local families persuaded the municipality to build a pedestrian crosswalk.", "translation": "تنظيم المجتمع وحشد طاقاته الأهلية", "collocations": ["skills in community organizing", "practice community organizing"], "synonyms": ["grassroots mobilizing"], "antonyms": [], "tags": ["community", "activism"]},
    {"headword": "social capital", "pronunciation": "/ˈsəʊʃl ˈkæpɪtl/", "partOfSpeech": "noun", "definition": "The networks of relationships, mutual trust, and shared norms enabling a society to function effectively.", "example": "High social capital within the neighborhood allowed residents to coordinate disaster relief rapidly.", "translation": "رأس المال الاجتماعي / شبكات الثقة والتكافل المجتمعي", "collocations": ["build social capital", "erode social capital"], "synonyms": ["social cohesion", "civic trust"], "antonyms": ["social fragmentation"], "tags": ["sociology", "community"]},
    {"headword": "collective action", "pronunciation": "/kəˈlektɪv ˈækʃn/", "partOfSpeech": "noun", "definition": "Collaborative action undertaken by a group of people to achieve a common goal or public good.", "example": "Collective action by tenants succeeded in halting unfair rent increases across the housing estate.", "translation": "العمل الجماعي المشترك لتحقيق مصلحة عامة", "collocations": ["engage in collective action", "mobilize collective action"], "synonyms": ["joint action", "coordinated effort"], "antonyms": ["individual inaction"], "tags": ["activism", "society"]},
    {"headword": "civil society", "pronunciation": "/ˈsɪvl səˈsaɪəti/", "partOfSpeech": "noun", "definition": "The realm of non-governmental organizations and institutions that manifest the interests of citizens.", "example": "A thriving civil society is essential for holding government officials accountable to the rule of law.", "translation": "المجتمع المدني ومؤسساته الأهلية غير الحكومية", "collocations": ["role of civil society", "vibrant civil society"], "synonyms": ["civic sector"], "antonyms": ["state apparatus"], "tags": ["politics", "society"]},
    {"headword": "advocacy group", "pronunciation": "/ˈædvəkəsi ɡruːp/", "partOfSpeech": "noun", "definition": "An organization that uses various forms of advocacy to influence public opinion and policy decisions.", "example": "The consumer advocacy group submitted petition signatures protesting deceptive banking fees.", "translation": "مجموعة مناصرة وحشد للتأثير في السياسات", "collocations": ["join an advocacy group", "leading advocacy group"], "synonyms": ["lobby group", "interest group"], "antonyms": [], "tags": ["politics", "activism"]},
    {"headword": "lobbying effort", "pronunciation": "/ˈlɒbiɪŋ ˈefət/", "partOfSpeech": "noun", "definition": "Coordinated activities aimed at directly persuading legislators to vote for specific legislation.", "example": "Environmental groups mounted a vigorous lobbying effort to pass the clean energy subsidy bill.", "translation": "مساعي وجهود الضغط على المشرعين وصناع القرار", "collocations": ["intense lobbying effort", "fund a lobbying effort"], "synonyms": ["lobbying campaign"], "antonyms": [], "tags": ["politics", "government"]},
    {"headword": "pressure group", "pronunciation": "/ˈpreʃə ɡruːp/", "partOfSpeech": "noun", "definition": "An organized group of people seeking to influence government policy on a specific issue without running candidates.", "example": "The cyclist pressure group campaigned successfully for protected bike lanes along major thoroughfares.", "translation": "جماعة ضغط لتوجيه السياسات نحو قضية معينة", "collocations": ["form a pressure group", "pressure group campaign"], "synonyms": ["action group", "lobby"], "antonyms": [], "tags": ["politics", "activism"]},
    {"headword": "think tank", "pronunciation": "/θɪŋk tæŋk/", "partOfSpeech": "noun", "definition": "An institute or research organization providing advice and ideas on political, economic, and social issues.", "example": "The economic think tank published independent forecasts on the impact of automation on employment.", "translation": "معهد أبحاث ودراسات استراتيجية / مركز فكر", "collocations": ["independent think tank", "research think tank"], "synonyms": ["policy institute"], "antonyms": [], "tags": ["research", "policy"]},
    {"headword": "policy brief", "pronunciation": "/ˈpɒləsi briːf/", "partOfSpeech": "noun", "definition": "A concise summary of an issue, policy options, and recommendations intended for government officials.", "example": "The researchers delivered a four-page policy brief to parliamentarians urging child care subsidies.", "translation": "ورقة إيجاز سياساتي وتقديم توصيات تنفيذية", "collocations": ["draft a policy brief", "circulate a policy brief"], "synonyms": ["policy memo"], "antonyms": [], "tags": ["policy", "government"]},
    {"headword": "public consultation", "pronunciation": "/ˈpʌblɪk ˌkɒnslˈteɪʃn/", "partOfSpeech": "noun", "definition": "A regulatory process in which the public is invited to provide input on proposed laws or development plans.", "example": "The municipal council opened a two-month public consultation on the zoning master plan.", "translation": "استشارة مجتمعية واستطلاع رأي الجمهور", "collocations": ["launch a public consultation", "feedback during public consultation"], "synonyms": ["civic inquiry"], "antonyms": ["closed deliberation"], "tags": ["governance", "public"]},
    {"headword": "town hall meeting", "pronunciation": "/taʊn hɔːl ˈmiːtɪŋ/", "partOfSpeech": "noun", "definition": "An informal public meeting where community members question elected politicians and voice concerns.", "example": "Hundreds of residents packed the local school gymnasium for the representative's town hall meeting.", "translation": "اجتماع بلدي مفتوح ومواجهة مباشرة مع المسؤولين", "collocations": ["host a town hall meeting", "attend a town hall meeting"], "synonyms": ["community assembly"], "antonyms": [], "tags": ["politics", "community"]},
    {"headword": "neighborhood watch", "pronunciation": "/ˈneɪbəhʊd wɒtʃ/", "partOfSpeech": "noun", "definition": "An organized group of citizens devoted to crime prevention and mutual safety in their local area.", "example": "Burglaries dropped substantially after residents formed an active neighborhood watch committee.", "translation": "لجان الحراسة والمراقبة الأهلية في الأحياء", "collocations": ["join the neighborhood watch", "neighborhood watch scheme"], "synonyms": ["community watch"], "antonyms": [], "tags": ["safety", "community"]},
    {"headword": "community policing", "pronunciation": "/kəˈmjuːnəti pəˈliːsɪŋ/", "partOfSpeech": "noun", "definition": "A law enforcement strategy emphasizing partnership and proactive dialogue between officers and residents.", "example": "By walking regular foot patrols, officers practicing community policing rebuilt trust with local youth.", "translation": "الشرطة المجتمعية القائمة على الشراكة وبناء الثقة", "collocations": ["implement community policing", "principles of community policing"], "synonyms": ["neighborhood policing"], "antonyms": ["militarized policing"], "tags": ["law", "community"]},

    # Social Cohesion, Welfare & Equity
    {"headword": "social cohesion", "pronunciation": "/ˈsəʊʃl kəʊˈhiːʒn/", "partOfSpeech": "noun", "definition": "The strength of interpersonal bonds and shared values holding individuals together in a society.", "example": "Investing in inclusive community centers and multicultural festivals bolsters social cohesion.", "translation": "التماسك والترابط الاجتماعي بين فئات المجتمع", "collocations": ["strengthen social cohesion", "foster social cohesion"], "synonyms": ["social solidarity"], "antonyms": ["social alienation"], "tags": ["sociology", "society"]},
    {"headword": "community resilience", "pronunciation": "/kəˈmjuːnəti rɪˈzɪliəns/", "partOfSpeech": "noun", "definition": "The sustained ability of a local population to withstand, recover from, and adapt to adversity or shocks.", "example": "Building local food networks and flood defenses increased the town's community resilience.", "translation": "مرونة المجتمع وقدرته على التعافي من الأزمات", "collocations": ["build community resilience", "enhance community resilience"], "synonyms": ["local resilience"], "antonyms": ["community vulnerability"], "tags": ["community", "disaster"]},
    {"headword": "voluntary sector", "pronunciation": "/ˈvɒləntri ˈsektə/", "partOfSpeech": "noun", "definition": "The non-profit organizations, charities, and volunteer groups providing services outside state or private markets.", "example": "During the pandemic, the voluntary sector filled critical welfare gaps by delivering emergency meals.", "translation": "القطاع التطوعي والخيري غير الربحي", "collocations": ["work in the voluntary sector", "support the voluntary sector"], "synonyms": ["third sector", "charity sector"], "antonyms": ["public sector", "private sector"], "tags": ["community", "charity"]},
    {"headword": "charitable foundation", "pronunciation": "/ˈtʃærɪtəbl faʊnˈdeɪʃn/", "partOfSpeech": "noun", "definition": "A non-profit organization established to provide grants and financial aid to worthy causes.", "example": "The charitable foundation awarded twenty educational grants to underprivileged medical students.", "translation": "مؤسسة خيرية مانحة لتمويل المبادرات", "collocations": ["establish a charitable foundation", "grant from a charitable foundation"], "synonyms": ["philanthropic trust"], "antonyms": [], "tags": ["charity", "finance"]},
    {"headword": "philanthropic giving", "pronunciation": "/ˌfɪlənˈθrɒpɪk ˈɡɪvɪŋ/", "partOfSpeech": "noun", "definition": "The voluntary donation of wealth, assets, or time by individuals or corporations for the public good.", "example": "The university's new science wing was financed entirely through generous philanthropic giving.", "translation": "العطاء الإنساني والتبرعات الخيرية التنموية", "collocations": ["culture of philanthropic giving", "increase philanthropic giving"], "synonyms": ["charitable donation"], "antonyms": [], "tags": ["philanthropy", "charity"]},
    {"headword": "corporate citizenship", "pronunciation": "/ˈkɔːpərət ˈsɪtɪzənʃɪp/", "partOfSpeech": "noun", "definition": "A corporation's recognized ethical responsibility toward society, the environment, and its stakeholders.", "example": "Demonstrating corporate citizenship, the software firm donated computers to local public schools.", "translation": "المواطنة المؤسسية والمسؤولية الأخلاقية للشركات", "collocations": ["practice corporate citizenship", "commitment to corporate citizenship"], "synonyms": ["corporate social responsibility", "CSR"], "antonyms": [], "tags": ["business", "ethics"]},
    {"headword": "environmental stewardship", "pronunciation": "/ɪnˌvaɪrənˈmentl ˈstjuːədʃɪp/", "partOfSpeech": "noun", "definition": "The responsible use and protection of the natural environment through conservation and sustainable practices.", "example": "Indigenous communities have practiced environmental stewardship across forest watersheds for millennia.", "translation": "الإشراف والوصاية البيئية لحماية الموارد الطبيعية", "collocations": ["promote environmental stewardship", "act of environmental stewardship"], "synonyms": ["conservation", "eco-stewardship"], "antonyms": ["environmental exploitation"], "tags": ["environment", "society"]},
    {"headword": "social enterprise", "pronunciation": "/ˈsəʊʃl ˈentəpraɪz/", "partOfSpeech": "noun", "definition": "A commercial business whose primary objective is creating positive social impact rather than private profit.", "example": "The social enterprise employs homeless youth and trains them as professional artisan bakers.", "translation": "مؤسسة ريادة أعمال اجتماعية تهدف للنفع العام", "collocations": ["launch a social enterprise", "model of a social enterprise"], "synonyms": ["mission-driven business"], "antonyms": ["for-profit corporation"], "tags": ["business", "social"]},
    {"headword": "community benefit", "pronunciation": "/kəˈmjuːnəti ˈbenɪfɪt/", "partOfSpeech": "noun", "definition": "Tangible positive outcomes or resources created by projects for the direct advantage of local residents.", "example": "The wind farm agreement included a community benefit clause funding local sports facilities.", "translation": "النفع العام والمكاسب العائدة على المجتمع المحلي", "collocations": ["generate community benefit", "community benefit agreement"], "synonyms": ["public welfare"], "antonyms": ["private profit"], "tags": ["community", "development"]},
    {"headword": "public goods", "pronunciation": "/ˈpʌblɪk ɡʊdz/", "partOfSpeech": "noun", "definition": "Commodities or services provided to all members of society without exclusion, such as clean air or street lighting.", "example": "Clean water and national defense are classic public goods that private markets fail to supply equitably.", "translation": "المنافع والسلع العامة المتاحة لكافة المواطنين", "collocations": ["provision of public goods", "protect public goods"], "synonyms": ["collective goods"], "antonyms": ["private goods"], "tags": ["economics", "society"]},
    {"headword": "common good", "pronunciation": "/ˈkɒmən ɡʊd/", "partOfSpeech": "noun", "definition": "The shared benefit, welfare, or advantage of all members of a given community.", "example": "Sacrificing individual convenience during water shortages serves the overarching common good.", "translation": "المصلحة العامة المشتركة لجميع أفراد المجتمع", "collocations": ["serve the common good", "for the common good"], "synonyms": ["general welfare", "public interest"], "antonyms": ["self-interest"], "tags": ["ethics", "philosophy"]},
    {"headword": "intergenerational equity", "pronunciation": "/ˌɪntəˌdʒenəˈreɪʃənl ˈekwəti/", "partOfSpeech": "noun", "definition": "The principle of fairness between current generations and future generations regarding resource use.", "example": "Preserving fiscal reserves and biological diversity is essential for intergenerational equity.", "translation": "العدالة بين الأجيال في توزيع الموارد والفرص", "collocations": ["ensure intergenerational equity", "principle of intergenerational equity"], "synonyms": ["intergenerational justice"], "antonyms": [], "tags": ["ethics", "sustainability"]},
    {"headword": "social mobility", "pronunciation": "/ˈsəʊʃl məʊˈbɪləti/", "partOfSpeech": "noun", "definition": "The ability of individuals or families to move between different social strata and economic brackets.", "example": "Tuition-free university education serves as the most potent engine of social mobility.", "translation": "الحراك الاجتماعي والانتقال بين الطبقات الاقتصادية", "collocations": ["enhance social mobility", "stifled social mobility"], "synonyms": ["socioeconomic progression"], "antonyms": ["social stagnation"], "tags": ["sociology", "economics"]},
    {"headword": "upward mobility", "pronunciation": "/ˈʌpwəd məʊˈbɪləti/", "partOfSpeech": "noun", "definition": "An increase in social or economic status and prosperity over time or between generations.", "example": "Access to affordable vocational training provides adult workers with genuine upward mobility.", "translation": "الارتقاء الطبقي والتقدم المعيشي نحو الأفضل", "collocations": ["pathway to upward mobility", "achieve upward mobility"], "synonyms": ["social advancement"], "antonyms": ["downward mobility"], "tags": ["economics", "society"]},
    {"headword": "glass ceiling", "pronunciation": "/ɡlɑːs ˈsiːlɪŋ/", "partOfSpeech": "noun", "definition": "An unacknowledged discriminatory barrier preventing women and minorities from reaching executive positions.", "example": "When she was appointed managing partner, she shattered an eighty-year-old glass ceiling.", "translation": "السقف الزجاجي / العائق الخفي أمام ترقي الفئات المهمشة", "collocations": ["break the glass ceiling", "shatter the glass ceiling"], "synonyms": ["invisible barrier"], "antonyms": ["equal opportunity"], "tags": ["equality", "career"]},
    {"headword": "systemic inequality", "pronunciation": "/sɪˈstemɪk ˌɪnɪˈkwɒləti/", "partOfSpeech": "noun", "definition": "Deeply ingrained institutional policies and practices that systematically disadvantage certain groups.", "example": "Reforming bail laws is critical to dismantling systemic inequality within the justice system.", "translation": "عدم المساواة الهيكلي والمترسخ في المؤسسات", "collocations": ["combat systemic inequality", "entrenched systemic inequality"], "synonyms": ["structural inequality"], "antonyms": ["systemic equity"], "tags": ["equality", "justice"]},
    {"headword": "digital inclusion", "pronunciation": "/ˈdɪdʒɪtl ɪnˈkluːʒn/", "partOfSpeech": "noun", "definition": "Activities ensuring that all individuals have access to and the skills to use modern information technologies.", "example": "The community library provides free tablets and digital inclusion classes for senior citizens.", "translation": "الشمول الرقمي وتمكين الجميع من استخدام التقنية", "collocations": ["promote digital inclusion", "initiatives for digital inclusion"], "synonyms": ["digital equity"], "antonyms": ["digital exclusion"], "tags": ["tech", "community"]},
    {"headword": "rural connectivity", "pronunciation": "/ˈrʊərəl kɒnekˈtɪvəti/", "partOfSpeech": "noun", "definition": "The provision of telecommunications, transportation, and internet infrastructure to isolated countryside areas.", "example": "Expanding fiber-optic broadband has significantly improved rural connectivity for remote farmers.", "translation": "ربط المناطق الريفية بالاتصالات والمواصلات", "collocations": ["improve rural connectivity", "invest in rural connectivity"], "synonyms": ["rural infrastructure"], "antonyms": ["rural isolation"], "tags": ["infrastructure", "rural"]},
    {"headword": "urban regeneration", "pronunciation": "/ˈɜːbən rɪˌdʒenəˈreɪʃn/", "partOfSpeech": "noun", "definition": "The revitalization of decaying or neglected urban neighborhoods through public and private investment.", "example": "The docks underwent extensive urban regeneration, transforming derelict warehouses into art studios.", "translation": "التجديد والإنعاش الحضري للمناطق المتدهورة", "collocations": ["drive urban regeneration", "urban regeneration project"], "synonyms": ["urban renewal"], "antonyms": ["urban blight"], "tags": ["urban", "development"]},
    {"headword": "gentrification", "pronunciation": "/ˌdʒentrɪfɪˈkeɪʃn/", "partOfSpeech": "noun", "definition": "The process of affluent people renovating deteriorating urban districts, often displacing poorer residents.", "example": "Rapid gentrification caused real estate prices and property taxes to triple within five years.", "translation": "الاستطباق / تهجير السكان الأصليين بسبب غلاء الأحياء المرممة", "collocations": ["rapid gentrification", "consequences of gentrification"], "synonyms": ["neighborhood upscaling"], "antonyms": [], "tags": ["urban", "society"]},

    # Housing, Mutual Aid & Sustainable Development
    {"headword": "affordable housing", "pronunciation": "/əˈfɔːdəbl ˈhaʊzɪŋ/", "partOfSpeech": "noun", "definition": "Housing units deemed affordable to households with median household income or below.", "example": "City planners passed ordinances requiring ten percent of new residential developments to be affordable housing.", "translation": "الإسكان الميسر لذوي الدخل المحدود والمتوسط", "collocations": ["supply of affordable housing", "lack of affordable housing"], "synonyms": ["low-cost housing"], "antonyms": ["luxury housing"], "tags": ["housing", "welfare"]},
    {"headword": "social housing", "pronunciation": "/ˈsəʊʃl ˈhaʊzɪŋ/", "partOfSpeech": "noun", "definition": "Subsidized housing provided by the state or non-profit housing associations for lower-income people.", "example": "The waitlist for municipal social housing has grown to over eight thousand families.", "translation": "الإسكان الاجتماعي المدعوم من الدولة", "collocations": ["invest in social housing", "tenants in social housing"], "synonyms": ["council housing", "public housing"], "antonyms": ["private real estate"], "tags": ["housing", "welfare"]},
    {"headword": "homelessness crisis", "pronunciation": "/ˈhəʊmləsnəs ˈkraɪsɪs/", "partOfSpeech": "noun", "definition": "A severe societal emergency characterized by escalating numbers of people lacking permanent shelter.", "example": "Emergency winter shelters were opened across the metropolitan area to confront the worsening homelessness crisis.", "translation": "أزمة التشرد وفقدان المأوى الحادة", "collocations": ["tackle the homelessness crisis", "address the homelessness crisis"], "synonyms": ["housing emergency"], "antonyms": [], "tags": ["housing", "crisis"]},
    {"headword": "food bank", "pronunciation": "/fuːd bæŋk/", "partOfSpeech": "noun", "definition": "A non-profit organization that distributes donated groceries directly to individuals facing food insecurity.", "example": "Volunteers packed emergency grocery parcels at the central food bank every Saturday morning.", "translation": "بنك الطعام لتوزيع المؤن الغذائية على المحتاجين", "collocations": ["volunteer at a food bank", "donate to the food bank"], "synonyms": ["food pantry"], "antonyms": [], "tags": ["charity", "food"]},
    {"headword": "community kitchen", "pronunciation": "/kəˈmjuːnəti ˈkɪtʃɪn/", "partOfSpeech": "noun", "definition": "A shared cooking facility or soup kitchen preparing free or affordable hot meals for the public.", "example": "The community kitchen serves two hundred hot lunches daily to pensioners and low-income neighbors.", "translation": "المطبخ المجتمعي لإعداد وجبات ساخنة للمحتاجين", "collocations": ["operate a community kitchen", "meals at the community kitchen"], "synonyms": ["soup kitchen"], "antonyms": [], "tags": ["food", "community"]},
    {"headword": "mutual aid", "pronunciation": "/ˈmjuːtʃuəl eɪd/", "partOfSpeech": "noun", "definition": "Voluntary reciprocal exchange of resources and services among community members for mutual benefit.", "example": "Neighborhood mutual aid networks distributed medicine and groceries to vulnerable elderly residents.", "translation": "التكافل والتضامن الشعبي التبادلي", "collocations": ["participate in mutual aid", "mutual aid group"], "synonyms": ["cooperative aid", "solidarity work"], "antonyms": [], "tags": ["solidarity", "community"]},
    {"headword": "peer support", "pronunciation": "/pɪə səˈpɔːt/", "partOfSpeech": "noun", "definition": "Assistance and emotional solidarity provided by people who share similar lived experiences or conditions.", "example": "Addiction recovery centers rely heavily on weekly peer support circles to maintain sobriety.", "translation": "الدعم والمساندة بين الأقران ذوي التجارب المشتركة", "collocations": ["offer peer support", "peer support group"], "synonyms": ["mutual support"], "antonyms": ["expert counseling"], "tags": ["health", "community"]},
    {"headword": "social prescribing", "pronunciation": "/ˈsəʊʃl prɪˈskraɪbɪŋ/", "partOfSpeech": "noun", "definition": "A healthcare approach where doctors refer patients to non-clinical community activities to boost wellbeing.", "example": "Through social prescribing, the physician connected the isolated senior to a local gardening club.", "translation": "الوصفات الاجتماعية بإحالة المرضى لأنشطة مجتمعية داعمة", "collocations": ["refer for social prescribing", "benefits of social prescribing"], "synonyms": ["community referral"], "antonyms": ["pharmacological treatment"], "tags": ["health", "wellbeing"]},
    {"headword": "wellbeing economy", "pronunciation": "/ˌwelˈbiːɪŋ ɪˈkɒnəmi/", "partOfSpeech": "noun", "definition": "An economic model prioritizing human and ecological wellbeing over narrow GDP output growth.", "example": "Governments adopting a wellbeing economy measure policy success by mental health, clean water, and civic trust.", "translation": "اقتصاد الرفاه الإنساني والبيئي المتجاوز لمؤشر الناتج المحلي", "collocations": ["transition to a wellbeing economy", "principles of a wellbeing economy"], "synonyms": ["economy of wellbeing"], "antonyms": ["growth-at-all-costs economy"], "tags": ["economics", "sustainability"]},
    {"headword": "circular economy", "pronunciation": "/ˈsɜːkjulər ɪˈkɒnəmi/", "partOfSpeech": "noun", "definition": "An economic model minimizing waste by regenerating natural systems and reusing products and materials.", "example": "Transitioning to a circular economy requires designing electronics that can be repaired and recycled indefinitely.", "translation": "الاقتصاد الدائري القائم على إعادة التدوير ومنع الهدر", "collocations": ["shift to a circular economy", "circular economy model"], "synonyms": ["zero-waste economy"], "antonyms": ["linear economy"], "tags": ["sustainability", "economics"]},
    {"headword": "sustainable development goal", "pronunciation": "/səˈsteɪnəbl dɪˈveləpmənt ɡəʊl/", "partOfSpeech": "noun", "definition": "One of seventeen global objectives set by the United Nations to end poverty and protect the planet.", "example": "Eradicating extreme poverty remains the foundational sustainable development goal adopted in 2015.", "translation": "أحد أهداف التنمية المستدامة للأمم المتحدة", "collocations": ["achieve a sustainable development goal", "UN sustainable development goal"], "synonyms": ["SDG"], "antonyms": [], "tags": ["un", "sustainability"]},
    {"headword": "green infrastructure", "pronunciation": "/ɡriːn ˈɪnfrəstrʌktʃə/", "partOfSpeech": "noun", "definition": "A strategically planned network of natural and semi-natural areas designed to deliver ecological services.", "example": "Permeable pavements, bioswales, and urban trees constitute resilient green infrastructure against flash floods.", "translation": "البنية التحتية الخضراء المستدامة والصديقة للبيئة", "collocations": ["invest in green infrastructure", "urban green infrastructure"], "synonyms": ["eco-infrastructure"], "antonyms": ["grey infrastructure"], "tags": ["urban", "environment"]},
    {"headword": "blue-green space", "pronunciation": "/bluː ɡriːn speɪs/", "partOfSpeech": "noun", "definition": "Urban areas combining water features (blue) and vegetation (green) that enhance health and cooling.", "example": "Creating a new blue-green space along the river canal reduced summer heat island temperatures by three degrees.", "translation": "المساحات الحضرية الزرقاء والخضراء (مسطحات مائية ونباتية)", "collocations": ["access to blue-green spaces", "design a blue-green space"], "synonyms": ["waterfront parkland"], "antonyms": ["concrete jungle"], "tags": ["urban", "environment"]},
    {"headword": "participatory budgeting", "pronunciation": "/pɑːˈtɪsɪpətəri ˈbʌdʒɪtɪŋ/", "partOfSpeech": "noun", "definition": "A democratic process where community residents directly vote on how to spend part of a public budget.", "example": "Through participatory budgeting, citizens allocated half a million dollars to build a new playground.", "translation": "الموازنة التشاركية بتصويت المواطنين على بنود الإنفاق", "collocations": ["conduct participatory budgeting", "participatory budgeting vote"], "synonyms": ["community budgeting"], "antonyms": ["top-down municipal budgeting"], "tags": ["democracy", "governance"]},
    {"headword": "community empowerment", "pronunciation": "/kəˈmjuːnəti ɪmˈpaʊəmənt/", "partOfSpeech": "noun", "definition": "The process of enabling local communities to increase control over the factors that affect their lives.", "example": "Community empowerment initiatives enable marginalized neighborhoods to negotiate directly with utility companies.", "translation": "التمكين المجتمعي وتعزيز استقلالية الأهالي", "collocations": ["foster community empowerment", "tools for community empowerment"], "synonyms": ["local self-determination"], "antonyms": ["community disenfranchisement"], "tags": ["community", "equality"]}
]

grammar_75 = [
    {
        "title": "Non-defining Relative Clauses",
        "explanation": "Non-defining relative clauses provide extra, non-essential information about a noun (person, thing, place, or concept) or comment on a whole previous clause. The sentence remains grammatically complete and makes sense if the clause is omitted.\n\n1. Key Rules:\n   - They MUST be separated from the rest of the sentence by commas (or a comma and full stop).\n   - You MUST NOT use 'that' — always use 'who', 'whom', 'whose', 'which', 'where', or 'when'.\n   - The relative pronoun can NEVER be omitted, even when it functions as the object.\n\n2. Comment Clauses with ', which...':\n   A non-defining clause starting with ', which...' can refer back to the ENTIRE preceding sentence or clause.\n   Example: 'Urban regeneration attracts wealthy developers, which often triggers severe gentrification.' (Here, 'which' refers to the whole process of attracting developers).\n\n3. Prepositions with Relative Pronouns:\n   In formal English, prepositions precede the relative pronoun: 'The charitable foundation, from which the hospital received funding, was founded in 1980.'",
        "structures": [
            {"pattern": "Noun, who / which / whose + extra info, Main Verb: 'The grassroots movement, which began with ten neighbors, now boasts five thousand members.'"},
            {"pattern": "Statement, which + comment verb: 'Municipal leaders approved participatory budgeting, which empowered hundreds of residents.'"},
            {"pattern": "Preposition + whom / which: 'The civic leaders, with whom we collaborated, champion intergenerational equity.'"}
        ],
        "examples": [
            {
                "sentence": "The grassroots movement, which started as a neighborhood petition, has evolved into a nationwide advocacy group.",
                "arabic": "الحركة الشعبية القاعدية، التي بدأت كعريضة في الحي، تطورت لتصبح مجموعة مناصرة وطنية.",
                "usesVocabulary": ["grassroots movement", "advocacy group"]
            },
            {
                "sentence": "The local council invested in green infrastructure, which significantly improved community resilience against severe flooding.",
                "arabic": "استثمر المجلس المحلي في البنية التحتية الخضراء، وهو ما حسّن بشكل ملحوظ مرونة المجتمع في مواجهة الفيضانات الشديدة.",
                "usesVocabulary": ["green infrastructure", "community resilience"]
            },
            {
                "sentence": "Social prescribing, which connects vulnerable patients to community kitchens and art circles, enhances holistic wellbeing.",
                "arabic": "الوصفات الاجتماعية، التي تربط المرضى الضعفاء بالمطابخ المجتمعية وحلقات الفنون، تعزز الرفاهية الشاملة.",
                "usesVocabulary": ["social prescribing", "community kitchen"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "The town hall meeting that took place yesterday was well attended.",
                "right": "The town hall meeting, which took place yesterday, was well attended.",
                "explanation": "If a relative clause adds extra descriptive information to a unique or specific event, use commas and 'which', not 'that'."
            },
            {
                "wrong": "The food bank which volunteers run it feeds hundreds of families.",
                "right": "The food bank, which volunteers run, feeds hundreds of families.",
                "explanation": "Do not repeat the object pronoun ('it') inside a relative clause when the relative pronoun ('which') already acts as the object."
            }
        ]
    }
]

convs_75 = [
    {
        "title": "Town Hall: Urban Regeneration and Affordable Housing",
        "titleArabic": "لقاء بلدي: التجديد الحضري والإسكان الميسر",
        "setting": "Residents debate an urban redevelopment plan with their city councilor.",
        "lines": [
            {"speaker": "Councilor", "text": "Welcome to our public consultation. Our new urban regeneration initiative, which covers forty acres, will modernize the district."},
            {"speaker": "Citizen A", "text": "With respect, rapid gentrification is pricing long-term families out of the neighborhood, which creates a severe homelessness crisis."},
            {"speaker": "Councilor", "text": "Our plan mandates twenty percent affordable housing and five percent social housing across all developments."},
            {"speaker": "Citizen B", "text": "Through collective action and community organizing, our advocacy group is demanding fifty percent affordable units to protect social cohesion."},
            {"speaker": "Councilor", "text": "We are also incorporating participatory budgeting, which gives residents direct voting power over the district's park budget."},
            {"speaker": "Citizen A", "text": "Investing in blue-green spaces and green infrastructure serves the common good and promotes environmental stewardship."},
            {"speaker": "Councilor", "text": "Agreed. Furthermore, every developer must sign a legally binding community benefit agreement."},
            {"speaker": "Citizen B", "text": "True community empowerment means listening to our grassroots movement before construction permits are signed."}
        ],
        "vocabularyUsed": ["public consultation", "urban regeneration", "gentrification", "homelessness crisis", "affordable housing", "social housing", "collective action", "community organizing", "advocacy group", "social cohesion", "participatory budgeting", "blue-green space", "green infrastructure", "common good", "environmental stewardship", "community benefit", "community empowerment", "grassroots movement"]
    },
    {
        "title": "Civic Forum: Social Cohesion and Mutual Aid",
        "titleArabic": "منتدى مدني: التماسك الاجتماعي والتكافل الشعبي",
        "setting": "Community organizers and social workers discuss welfare safety nets.",
        "lines": [
            {"speaker": "Organizer", "text": "Our mutual aid network, which was founded during the lockdowns, continues to deliver groceries from the local food bank."},
            {"speaker": "Social Worker", "text": "In addition, our volunteer staff operates a bustling community kitchen, which provides hot meals and essential peer support."},
            {"speaker": "Organizer", "text": "Local physicians are embracing social prescribing, which directs isolated seniors to our weekly social capital gardening sessions."},
            {"speaker": "Social Worker", "text": "That is vital for mental health. Expanding digital inclusion and rural connectivity helps bridge isolation across the county."},
            {"speaker": "Organizer", "text": "The voluntary sector, which relies on modest philanthropic giving from a local charitable foundation, cannot shoulder all welfare burdens alone."},
            {"speaker": "Social Worker", "text": "Indeed. Dismantling systemic inequality requires systemic public goods provided by the state, not just charity."},
            {"speaker": "Organizer", "text": "Corporations must also show genuine corporate citizenship by supporting social enterprises that pay living wages."},
            {"speaker": "Social Worker", "text": "Building community resilience ensures our neighborhoods can weather any future economic downturn."}
        ],
        "vocabularyUsed": ["mutual aid", "food bank", "community kitchen", "peer support", "social prescribing", "social capital", "digital inclusion", "rural connectivity", "voluntary sector", "philanthropic giving", "charitable foundation", "systemic inequality", "public goods", "corporate citizenship", "social enterprise", "community resilience"]
    },
    {
        "title": "Youth Leadership Dialogue: Social Mobility and Future Generations",
        "titleArabic": "حوار القيادات الشبابية: الحراك الاجتماعي وأجيال المستقبل",
        "setting": "A university panel discusses sustainable development goals and civic engagement.",
        "lines": [
            {"speaker": "Moderator", "text": "How can our society foster upward mobility while upholding intergenerational equity?"},
            {"speaker": "Youth Leader", "text": "Quality education is the primary pathway to social mobility, yet disadvantaged youth still confront a formidable glass ceiling."},
            {"speaker": "Policy Analyst", "text": "A renowned economic think tank released a policy brief urging transition toward a wellbeing economy and a circular economy."},
            {"speaker": "Youth Leader", "text": "Aligning our domestic laws with every sustainable development goal requires consistent civic engagement and lobbying efforts."},
            {"speaker": "Policy Analyst", "text": "Furthermore, community policing initiatives, which build trust between neighborhood watch volunteers and officers, keep streets secure."},
            {"speaker": "Youth Leader", "text": "When citizens exercise collective action through civil society, they pressure governments into prioritizing the common good."},
            {"speaker": "Policy Analyst", "text": "Exactly. That dynamic represents the essence of a pressure group advocating for democratic accountability."},
            {"speaker": "Moderator", "text": "Empowering youth to engage in public discourse will safeguard democracy for generations to come."}
        ],
        "vocabularyUsed": ["upward mobility", "intergenerational equity", "social mobility", "glass ceiling", "think tank", "policy brief", "wellbeing economy", "circular economy", "sustainable development goal", "civic engagement", "lobbying effort", "community policing", "neighborhood watch", "collective action", "civil society", "common good", "pressure group"]
    }
]

paras_75 = [
    {
        "title": "Civic Mobilization, Grassroots Democracy, and Policy Change",
        "titleArabic": "الحشد المدني، الديمقراطية القاعدية، وتغيير السياسات",
        "text": "A thriving democracy depends upon energetic civic engagement and organized collective action across all sectors of society. When local residents organize a grassroots movement, they generate substantial social capital that empowers communities to demand accountability. Supported by a dedicated advocacy group or public interest pressure group, ordinary citizens commission insightful policy briefs from independent think tanks to persuade legislators through targeted lobbying efforts. Through structured public consultation and transparent town hall meetings, municipal leaders gain invaluable perspectives from civil society. Ultimately, embracing participatory budgeting bridges political divides and achieves genuine community empowerment.",
        "vocabularyUsed": ["civic engagement", "collective action", "grassroots movement", "social capital", "advocacy group", "pressure group", "policy brief", "think tank", "lobbying effort", "public consultation", "town hall meeting", "civil society", "participatory budgeting", "community empowerment"]
    },
    {
        "title": "Urban Equity, Housing Justice, and Environmental Regeneration",
        "titleArabic": "العدالة الحضرية، الحق في السكن، والتجديد البيئي",
        "text": "Balancing modernization with social equity is the foremost challenge confronting contemporary urban development. When municipal councils initiate large-scale urban regeneration, unmonitored market speculation frequently triggers aggressive gentrification, leaving low-income families vulnerable to a devastating homelessness crisis. To safeguard neighborhood stability, city planners must mandate substantial ratios of affordable housing and state-funded social housing. Simultaneously, incorporating resilient green infrastructure and accessible blue-green spaces enhances environmental stewardship and protects the health of residents. By ensuring that every major development delivers a binding community benefit, cities serve the common good and advance intergenerational equity.",
        "vocabularyUsed": ["urban regeneration", "gentrification", "homelessness crisis", "affordable housing", "social housing", "green infrastructure", "blue-green space", "environmental stewardship", "community benefit", "common good", "intergenerational equity"]
    },
    {
        "title": "Community Resilience, Solidarity Networks, and Welfare Safety Nets",
        "titleArabic": "مرونة المجتمع، شبكات التكافل، وشبكات الأمان الاجتماعي",
        "text": "Fostering community resilience requires robust welfare safety nets and active mutual aid networks operating across neighborhoods. In times of hardship, the voluntary sector provides essential relief through dedicated food banks and welcoming community kitchens that serve vulnerable families. Innovative healthcare models increasingly incorporate social prescribing, connecting patients with peer support circles and artistic workshops that strengthen social cohesion. Furthermore, ethical social enterprises demonstrate how business can generate social returns while advancing the principles of a circular economy and a wellbeing economy. Together, these grassroots initiatives dismantle systemic inequality and advance global sustainable development goals.",
        "vocabularyUsed": ["community resilience", "mutual aid", "voluntary sector", "food bank", "community kitchen", "social prescribing", "peer support", "social cohesion", "social enterprise", "circular economy", "wellbeing economy", "systemic inequality", "sustainable development goal"]
    }
]

# ==============================================================================
# DAY 76: Telling Stories (Experiences and narratives)
# Grammar: Narrative Tenses Review
# ==============================================================================

vocab_76 = [
    # Narrative Structure & Story Craft
    {"headword": "narrative arc", "pronunciation": "/ˈnærətɪv ɑːk/", "partOfSpeech": "noun", "definition": "The chronological progression and emotional trajectory of a story through beginning, middle, and climax.", "example": "The novelist carefully structured the narrative arc to ensure the protagonist evolved through each crisis.", "translation": "القوس السردي / المنحنى الدرامي لتطور أحداث القصة", "collocations": ["develop a narrative arc", "satisfying narrative arc"], "synonyms": ["storyline trajectory"], "antonyms": [], "tags": ["literature", "writing"]},
    {"headword": "story twist", "pronunciation": "/ˈstɔːri twɪst/", "partOfSpeech": "noun", "definition": "An unexpected radical change in the direction or outcome of the plot in a story.", "example": "The shocking story twist at the end of the mystery thriller caught both critics and readers off guard.", "translation": "انعطافة مفاجئة في مجرى القصة والحبكة", "collocations": ["unexpected story twist", "clever story twist"], "synonyms": ["plot twist"], "antonyms": ["predictable plot"], "tags": ["literature", "storytelling"]},
    {"headword": "cliffhanger", "pronunciation": "/ˈklɪfhæŋə/", "partOfSpeech": "noun", "definition": "A dramatic and suspenseful ending to an episode or chapter that leaves the main character in a precarious dilemma.", "example": "Season four concluded on a breathless cliffhanger that left fans speculating on social media for months.", "translation": "نهاية مشوقة ومعلقة تبقي المتلقي في ترقب شديد", "collocations": ["end on a cliffhanger", "dramatic cliffhanger"], "synonyms": ["suspenseful ending"], "antonyms": ["resolved ending"], "tags": ["drama", "media"]},
    {"headword": "foreshadowing", "pronunciation": "/fɔːˈʃædəʊɪŋ/", "partOfSpeech": "noun", "definition": "A literary device in which a writer gives an advance hint of what is to come later in the story.", "example": "The raven tapping against the window pane in chapter one served as chilling foreshadowing of the tragedy.", "translation": "التلميح المسبق / الإرهاص السردي بأحداث قادمة", "collocations": ["subtle foreshadowing", "use foreshadowing"], "synonyms": ["premonition", "advance hint"], "antonyms": [], "tags": ["writing", "literature"]},
    {"headword": "flashback", "pronunciation": "/ˈflæʃbæk/", "partOfSpeech": "noun", "definition": "A scene set in a time earlier than the main story that reveals essential background context.", "example": "A vivid flashback to wartime Berlin explained why the elderly character refused to answer the telephone.", "translation": "استرجاع فني للماضي / فلاش باك في السرد", "collocations": ["trigger a flashback", "flashback sequence"], "synonyms": ["retrospection", "analepsis"], "antonyms": ["flashforward"], "tags": ["cinema", "literature"]},
    {"headword": "unreliable narrator", "pronunciation": "/ˌʌnrɪˈlaɪəbl nəˈreɪtə/", "partOfSpeech": "noun", "definition": "A storyteller whose credibility is compromised, intentionally deceiving or misleading the audience.", "example": "Agatha Christie famously employed an unreliable narrator in 'The Murder of Roger Ackroyd' to conceal the killer.", "translation": "الراوي غير الموثوق / راوٍ يضلل المتلقي أو تنقصه النزاهة", "collocations": ["classic unreliable narrator", "rely on an unreliable narrator"], "synonyms": ["deceptive narrator"], "antonyms": ["omniscient narrator"], "tags": ["literature", "narrative"]},
    {"headword": "omniscient narrator", "pronunciation": "/ɒmˈnɪsiənt nəˈreɪtə/", "partOfSpeech": "noun", "definition": "An all-knowing third-person storyteller who possesses total knowledge of all characters' thoughts and actions.", "example": "Tolstoy favored an omniscient narrator capable of shifting effortlessly between battlefields and ballroom gossip.", "translation": "الراوي العليم الكلي المعرفة بأفكار كافة الشخصيات", "collocations": ["third-person omniscient narrator", "omniscient narrator perspective"], "synonyms": ["all-knowing narrator"], "antonyms": ["first-person narrator"], "tags": ["literature", "writing"]},
    {"headword": "stream of consciousness", "pronunciation": "/striːm əv ˈkɒnʃəsnəs/", "partOfSpeech": "noun", "definition": "A narrative style depicting the continuous, unedited flow of a character's internal thoughts and sensations.", "example": "James Joyce used stream of consciousness to capture Leopold Bloom's spontaneous impressions wandering Dublin.", "translation": "تيار الوعي وتدفق الخواطر السردي الداخلي", "collocations": ["write in stream of consciousness", "stream of consciousness technique"], "synonyms": ["interior monologue"], "antonyms": ["structured dialogue"], "tags": ["literature", "style"]},
    {"headword": "dramatic irony", "pronunciation": "/drəˈmætɪk ˈaɪərəni/", "partOfSpeech": "noun", "definition": "A literary device where the audience understands the significance of events that characters do not.", "example": "Dramatic irony occurs when the audience knows Romeo believes Juliet is dead, while Juliet is merely sleeping.", "translation": "المفارقة الدرامية / علم الجمهور بما يجهله أبطال العمل", "collocations": ["employ dramatic irony", "heighten dramatic irony"], "synonyms": ["tragic irony"], "antonyms": [], "tags": ["theater", "literature"]},
    {"headword": "comic relief", "pronunciation": "/ˈkɒmɪk rɪˈliːf/", "partOfSpeech": "noun", "definition": "Humorous scenes or characters introduced into a serious play or novel to relieve emotional tension.", "example": "The foolish porter scene in Macbeth provides momentary comic relief following Duncan's assassination.", "translation": "التفريج الكوميدي لتخفيف التوتر في العمل التراجيدي", "collocations": ["provide comic relief", "moment of comic relief"], "synonyms": ["humorous interlude"], "antonyms": ["dramatic tension"], "tags": ["drama", "comedy"]},
    {"headword": "protagonist journey", "pronunciation": "/prəˈtæɡənɪst ˈdʒɜːni/", "partOfSpeech": "noun", "definition": "The transformative inner and outer journey undergone by the main character across a story.", "example": "The emotional depth of the film stems from the protagonist journey from cynical loner to selfless leader.", "translation": "رحلة البطل وتطوره المعنوي والفعلي في الرواية", "collocations": ["chart the protagonist journey", "heroic protagonist journey"], "synonyms": ["hero's journey", "character arc"], "antonyms": [], "tags": ["literature", "storytelling"]},
    {"headword": "antagonist motive", "pronunciation": "/ænˈtæɡənɪst ˈməʊtɪv/", "partOfSpeech": "noun", "definition": "The psychological reasons, desires, or trauma driving the primary opponent of the hero.", "example": "A convincing screenplay gives the antagonist motive clear ideological depth rather than simple malice.", "translation": "دوافع الخصم والأسباب المحركة للطرف المعادي للبطل", "collocations": ["explore antagonist motive", "compelling antagonist motive"], "synonyms": ["villain's motivation"], "antonyms": [], "tags": ["writing", "drama"]},
    {"headword": "supporting character", "pronunciation": "/səˈpɔːtɪŋ ˈkærəktə/", "partOfSpeech": "noun", "definition": "A secondary character who assists or complicates the journey of the central protagonist.", "example": "The loyal childhood friend acted as a wise supporting character who repeatedly grounded the troubled hero.", "translation": "شخصية مساندة وثانوية تعزز مسار القصة", "collocations": ["memorable supporting character", "cast of supporting characters"], "synonyms": ["minor character", "secondary character"], "antonyms": ["lead character", "protagonist"], "tags": ["literature", "cinema"]},
    {"headword": "backstory", "pronunciation": "/ˈbækstɔːri/", "partOfSpeech": "noun", "definition": "The history of events, relationships, and trauma that took place before the primary plot commenced.", "example": "The author revealed the veteran's tragic backstory in snippets scattered across the middle chapters.", "translation": "الخلفية الدرامية وتاريخ الشخصيات السابق لبدء القصة", "collocations": ["reveal a backstory", "elaborate backstory"], "synonyms": ["background story", "prequel context"], "antonyms": [], "tags": ["writing", "literature"]},
    {"headword": "subplot", "pronunciation": "/ˈsʌbplɒt/", "partOfSpeech": "noun", "definition": "A secondary storyline in a narrative that runs parallel to and supports the primary plot.", "example": "The romantic subplot between the two detectives enriched the otherwise grim murder investigation.", "translation": "الحبكة الفرعية الموازية للحبكة الرئيسية", "collocations": ["weave a subplot", "romantic subplot"], "synonyms": ["secondary plot", "underplot"], "antonyms": ["main plot"], "tags": ["literature", "drama"]},
    {"headword": "rising action", "pronunciation": "/ˈraɪzɪŋ ˈækʃn/", "partOfSpeech": "noun", "definition": "A series of escalating incidents and conflicts that create suspense, interest, and tension leading to the climax.", "example": "During the rising action, every attempt by the explorers to signal for rescue failed catastrophically.", "translation": "تصاعد وتنامي الأحداث والنزاع في القصة", "collocations": ["tension in the rising action", "stage of rising action"], "synonyms": ["escalation"], "antonyms": ["falling action"], "tags": ["literature", "writing"]},
    {"headword": "falling action", "pronunciation": "/ˈfɔːlɪŋ ˈækʃn/", "partOfSpeech": "noun", "definition": "The sequence of events following the climax that guides the story toward final resolution.", "example": "In the falling action, the wounded hero returned to his village to reconcile with his family.", "translation": "انحسار الأحداث وهدوء الصراع بعد الذروة", "collocations": ["pacing in the falling action", "during the falling action"], "synonyms": ["post-climax"], "antonyms": ["rising action"], "tags": ["writing", "literature"]},
    {"headword": "climactic moment", "pronunciation": "/klaɪˈmæktɪk ˈməʊmənt/", "partOfSpeech": "noun", "definition": "The turning point or point of highest dramatic intensity and maximum conflict in a narrative.", "example": "The climactic moment occurred when the defense attorney confronted the witness with the incriminating diary.", "translation": "لحظة الذروة الدرامية الأشد إثارة في العمل", "collocations": ["reach the climactic moment", "tense climactic moment"], "synonyms": ["climax", "turning point"], "antonyms": ["anticlimax"], "tags": ["drama", "literature"]},
    {"headword": "denouement", "pronunciation": "/deɪˈnuːmɒ̃/", "partOfSpeech": "noun", "definition": "The final outcome or unraveling of the intricacies of a plot following the climax.", "example": "The tranquil denouement revealed what became of the surviving crew decades after the shipwreck.", "translation": "الحل النهائي وعقدة الختام وفك خيوط الحبكة", "collocations": ["satisfying denouement", "reach the denouement"], "synonyms": ["resolution", "unraveling"], "antonyms": ["exposition"], "tags": ["literature", "french-borrowing"]},
    {"headword": "narrative tension", "pronunciation": "/ˈnærətɪv ˈtenʃn/", "partOfSpeech": "noun", "definition": "The feeling of anxiety, suspense, and emotional uncertainty that drives the reader to keep turning pages.", "example": "The author maintained taut narrative tension by cutting between the hostage room and the police van.", "translation": "التوتر والشد السردي الذي يبقي القارئ معلقاً", "collocations": ["maintain narrative tension", "heighten narrative tension"], "synonyms": ["story suspense"], "antonyms": ["narrative lull"], "tags": ["writing", "literature"]},
    {"headword": "suspense build-up", "pronunciation": "/səˈspens bɪld ʌp/", "partOfSpeech": "noun", "definition": "The deliberate, gradual amplification of tension and anticipation leading toward a revelation.", "example": "The eerie musical score and slow tracking shots created a terrifying suspense build-up.", "translation": "التصعيد التدريجي لوتيرة التشويق والترقب", "collocations": ["masterful suspense build-up", "slow suspense build-up"], "synonyms": ["escalation of suspense"], "antonyms": [], "tags": ["cinema", "writing"]},
    {"headword": "hook opening", "pronunciation": "/hʊk ˈəʊpənɪŋ/", "partOfSpeech": "noun", "definition": "An intriguing, dramatic, or shocking first sentence or scene that immediately grabs reader interest.", "example": "The novel begins with a brilliant hook opening: 'The clock struck thirteen on a morning nobody was supposed to die.'", "translation": "الاستهلال الخاطف / جملة البداية الجاذبة للقارئ فوراً", "collocations": ["craft a hook opening", "memorable hook opening"], "synonyms": ["narrative hook"], "antonyms": ["boring start"], "tags": ["writing", "journalism"]},
    {"headword": "exposition", "pronunciation": "/ˌekspəˈzɪʃn/", "partOfSpeech": "noun", "definition": "The insertion of crucial background information regarding setting, characters' past, or historical context.", "example": "Skillful writers integrate necessary exposition naturally through dialogue rather than heavy data dumps.", "translation": "التمهيد والفرش السردي / استعراض خلفية القصة وأبطالها", "collocations": ["clunky exposition", "seamless exposition"], "synonyms": ["introductory background"], "antonyms": ["denouement"], "tags": ["writing", "literature"]},
    {"headword": "rising stakes", "pronunciation": "/ˈraɪzɪŋ steɪks/", "partOfSpeech": "noun", "definition": "The progressive increase in what characters stand to gain or lose as conflicts intensify.", "example": "With rising stakes threatening his family rather than merely his career, the investigator risked everything.", "translation": "تصاعد وتفاقم الرهانات والمخاطر المهددة للشخصيات", "collocations": ["face rising stakes", "escalate rising stakes"], "synonyms": ["escalating risks"], "antonyms": ["low stakes"], "tags": ["writing", "drama"]},
    {"headword": "narrative voice", "pronunciation": "/ˈnærətɪv vɔɪs/", "partOfSpeech": "noun", "definition": "The distinctive tone, personality, and grammatical perspective adopted by the storyteller.", "example": "The memoir was praised for its cynical, sardonic narrative voice that made tragic events darkly hilarious.", "translation": "الصوت السردي ونبرة الحاكي المميزة", "collocations": ["distinctive narrative voice", "commanding narrative voice"], "synonyms": ["authorial voice"], "antonyms": [], "tags": ["writing", "style"]},

    # Perspectives, Devices & Non-Fiction
    {"headword": "point of view", "pronunciation": "/pɔɪnt əv vjuː/", "partOfSpeech": "noun", "definition": "The perspective or lens through which a story is communicated to the audience.", "example": "Switching point of view between chapters allowed the reader to empathize with both bitter rivals.", "translation": "زاوية الرؤية ومنظور السرد", "collocations": ["narrative point of view", "shift point of view"], "synonyms": ["POV", "perspective"], "antonyms": [], "tags": ["writing", "literature"]},
    {"headword": "first-person narrator", "pronunciation": "/ˌfɜːst ˈpɜːsn nəˈreɪtə/", "partOfSpeech": "noun", "definition": "A storyteller who relates the story from their own subjective perspective using 'I' or 'we'.", "example": "Using a first-person narrator creates an immediate sense of intimacy between the protagonist and reader.", "translation": "راوي ضمير المتكلم (أنا / نحن)", "collocations": ["intimate first-person narrator", "reliable first-person narrator"], "synonyms": ["first-person POV"], "antonyms": ["third-person narrator"], "tags": ["literature", "writing"]},
    {"headword": "third-person limited", "pronunciation": "/ˌθɜːd ˈpɜːsn ˈlɪmɪtɪd/", "partOfSpeech": "noun", "definition": "A storytelling mode where the narrator knows only the thoughts and experiences of a single character.", "example": "Writing in third-person limited preserved the mystery because readers only knew what detective Holmes knew.", "translation": "سرد ضمير الغائب المقيد بوعي شخصية واحدة فقط", "collocations": ["written in third-person limited", "third-person limited perspective"], "synonyms": ["close third-person"], "antonyms": ["third-person omniscient"], "tags": ["writing", "literature"]},
    {"headword": "frame narrative", "pronunciation": "/freɪm ˈnærətɪv/", "partOfSpeech": "noun", "definition": "A overarching storytelling structure that serves as a container or context for an embedded story.", "example": "'Heart of Darkness' utilizes a frame narrative where sailors on the Thames listen to Marlow's Congo voyage.", "translation": "السرد الإطاري / القصة الحاوية لحكايات فرعية داخلها", "collocations": ["classic frame narrative", "utilize a frame narrative"], "synonyms": ["framing device", "story within a story"], "antonyms": ["linear narrative"], "tags": ["literature", "structure"]},
    {"headword": "embedded story", "pronunciation": "/ɪmˈbedɪd ˈstɔːri/", "partOfSpeech": "noun", "definition": "A secondary tale narrated by a character within the context of a primary frame story.", "example": "Scheherazade's embedded stories in 'One Thousand and One Nights' deferred her execution night after night.", "translation": "القصة المضمنة في نسيج حكاية كبرى", "collocations": ["recount an embedded story", "fascinating embedded story"], "synonyms": ["tale within a tale"], "antonyms": ["framing narrative"], "tags": ["literature", "storytelling"]},
    {"headword": "anecdote opening", "pronunciation": "/ˈænɪkdəʊt ˈəʊpənɪŋ/", "partOfSpeech": "noun", "definition": "Beginning a speech, article, or chapter with a short, entertaining real-world story to illustrate a theme.", "example": "The keynote speaker captivated the auditorium with a humorous anecdote opening about his first failed interview.", "translation": "استهلال بحكاية واقعية طريفة لشد انتباه الحضور", "collocations": ["use an anecdote opening", "effective anecdote opening"], "synonyms": ["anecdotal hook"], "antonyms": ["statistical opening"], "tags": ["public speaking", "writing"]},
    {"headword": "vivid description", "pronunciation": "/ˈvɪvɪd dɪˈskrɪpʃn/", "partOfSpeech": "noun", "definition": "Clear, detailed, and evocative language that creates strong sensory pictures in the reader's imagination.", "example": "The travel writer's vivid description of the spice bazaar made readers feel the pungent turmeric and heat.", "translation": "وصف حي وتصوير بارع ينبض بالحياة", "collocations": ["paint a vivid description", "full of vivid description"], "synonyms": ["evocative imagery"], "antonyms": ["bland prose"], "tags": ["writing", "imagery"]},
    {"headword": "sensory detail", "pronunciation": "/ˈsensəri ˈdiːteɪl/", "partOfSpeech": "noun", "definition": "Descriptive language engaging the five senses: sight, sound, smell, taste, and touch.", "example": "Layering sensory details like sizzling garlic and cold cobblestones immerses readers into the setting.", "translation": "التفاصيل الحسية (السمعية والبصرية والشمية واللمسية)", "collocations": ["rich in sensory details", "appeal to sensory details"], "synonyms": ["sensory imagery"], "antonyms": ["abstract exposition"], "tags": ["writing", "style"]},
    {"headword": "figurative language", "pronunciation": "/ˈfɪɡərətɪv ˈlæŋɡwɪdʒ/", "partOfSpeech": "noun", "definition": "Language using figures of speech like metaphors, similes, and personification beyond literal meanings.", "example": "Poets rely on evocative figurative language to awaken emotions that literal words cannot convey.", "translation": "اللغة المجازية والبلاغية التعبيرية", "collocations": ["mastery of figurative language", "employ figurative language"], "synonyms": ["tropes", "figurative phrasing"], "antonyms": ["literal language"], "tags": ["linguistics", "literature"]},
    {"headword": "metaphorical expression", "pronunciation": "/ˌmetəˈfɒrɪkl ɪkˈspreʃn/", "partOfSpeech": "noun", "definition": "A phrase comparing two unrelated things by stating one is the other, without using 'like' or 'as'.", "example": "Describing life as 'a roller-coaster of triumph and despair' is a common metaphorical expression.", "translation": "تعبير استعاري تصويري", "collocations": ["use a metaphorical expression", "poetic metaphorical expression"], "synonyms": ["metaphor"], "antonyms": ["literal statement"], "tags": ["rhetoric", "literature"]},
    {"headword": "simile usage", "pronunciation": "/ˈsɪməli ˈjuːsɪdʒ/", "partOfSpeech": "noun", "definition": "The explicit comparison of one thing with another using comparative words like 'as' or 'like'.", "example": "The author's inventive simile usage compared the old diesel locomotive to a coughing dragon.", "translation": "استخدام أسلوب التشبيه الصريح بأدوات التشبيه", "collocations": ["effective simile usage", "creative simile usage"], "synonyms": ["simile phrasing"], "antonyms": ["metaphor"], "tags": ["literature", "style"]},
    {"headword": "personification", "pronunciation": "/pəˌsɒnɪfɪˈkeɪʃn/", "partOfSpeech": "noun", "definition": "A literary device attributing human traits, emotions, or behaviors to inanimate objects or abstractions.", "example": "The sentence 'The howling wind clawed at the fragile roof shingles' employs vivid personification.", "translation": "التشخيص وإضفاء صفات بشرية على الجماد", "collocations": ["use of personification", "vivid personification"], "synonyms": ["anthropomorphism"], "antonyms": [], "tags": ["literature", "rhetoric"]},
    {"headword": "hyperbole effect", "pronunciation": "/haɪˈpɜːbəli ɪˈfekt/", "partOfSpeech": "noun", "definition": "The deliberate rhetorical impact created by dramatic exaggeration not meant to be taken literally.", "example": "Saying 'I walked across the entire planet to find this coffee' creates a humorous hyperbole effect.", "translation": "أثر المبالغة البلاغية والتهويل التعبيري", "collocations": ["rely on hyperbole effect", "comedic hyperbole effect"], "synonyms": ["exaggeration impact"], "antonyms": ["understatement"], "tags": ["rhetoric", "humor"]},
    {"headword": "understatement", "pronunciation": "/ˈʌndəsteɪtmənt/", "partOfSpeech": "noun", "definition": "The presentation of something as being smaller, worse, or less important than it actually is.", "example": "Calling the devastating hurricane 'a bit of windy weather' is a classic British understatement.", "translation": "التهوين البلاغي / التقليل من شأن الحدث لغايات تعبيرية", "collocations": ["master of understatement", "classic understatement"], "synonyms": ["litotes", "downplaying"], "antonyms": ["hyperbole"], "tags": ["rhetoric", "humor"]},
    {"headword": "ironic twist", "pronunciation": "/aɪˈrɒnɪk twɪst/", "partOfSpeech": "noun", "definition": "An unexpected situation or plot turn where the outcome is humorously or tragically opposite to expectations.", "example": "In an ironic twist, the master locksmith accidentally locked himself inside his own vault.", "translation": "مفارقة ساخرة تقلب النتيجة عكس المتوقع", "collocations": ["savor the ironic twist", "cruel ironic twist"], "synonyms": ["situational irony"], "antonyms": ["expected outcome"], "tags": ["humor", "literature"]},
    {"headword": "surprise ending", "pronunciation": "/səˈpraɪz ˈendɪŋ/", "partOfSpeech": "noun", "definition": "An unforeseen conclusion to a story that radically reframes everything that preceded it.", "example": "O. Henry became internationally celebrated for short stories featuring a heart-wrenching surprise ending.", "translation": "نهاية مفاجئة وصادمة تقلب الموازين", "collocations": ["shocking surprise ending", "craft a surprise ending"], "synonyms": ["twist ending"], "antonyms": ["formulaic ending"], "tags": ["literature", "storytelling"]},
    {"headword": "ambiguous ending", "pronunciation": "/æmˈbɪɡjuəs ˈendɪŋ/", "partOfSpeech": "noun", "definition": "A conclusion open to more than one interpretation that leaves the final outcome unresolved in the reader's mind.", "example": "The spinning top at the conclusion of 'Inception' offers an ambiguous ending that puzzles audiences to this day.", "translation": "نهاية غامضة تحتمل تأويلات متعددة", "collocations": ["deliberately ambiguous ending", "interpret an ambiguous ending"], "synonyms": ["unresolved ending"], "antonyms": ["definitive resolution"], "tags": ["cinema", "literature"]},
    {"headword": "open-ended conclusion", "pronunciation": "/ˌəʊpən ˈendɪd kənˈkluːʒn/", "partOfSpeech": "noun", "definition": "A story termination that does not definitively resolve the main dilemma, prompting reader contemplation.", "example": "Rather than tying up every loose thread, the novella finishes with a haunting open-ended conclusion.", "translation": "خاتمة مفتوحة تترك مصير الشخصيات للتأمل", "collocations": ["opt for an open-ended conclusion", "provocative open-ended conclusion"], "synonyms": ["indeterminate ending"], "antonyms": ["neat resolution"], "tags": ["literature", "writing"]},
    {"headword": "poetic license", "pronunciation": "/pəʊˈetɪk ˈlaɪsns/", "partOfSpeech": "noun", "definition": "The liberty taken by an artist or writer to bend historical fact or grammatical rules for aesthetic effect.", "example": "The film director took considerable poetic license with historical dates to heighten dramatic stakes.", "translation": "الضرورة أو الرخصة الشعرية والفنية لتطويع القواعد", "collocations": ["invoke poetic license", "exercise poetic license"], "synonyms": ["artistic license"], "antonyms": ["literal accuracy"], "tags": ["art", "literature"]},
    {"headword": "creative nonfiction", "pronunciation": "/kriˈeɪtɪv ˌnɒnˈfɪkʃn/", "partOfSpeech": "noun", "definition": "A genre of writing that uses literary storytelling styles and techniques to narrate factual, true events.", "example": "Her book about deep-sea marine biology reads like a thriller because it is written as creative nonfiction.", "translation": "الأدب غير الروائي الإبداعي (سرد الحقائق بتقنيات الرواية)", "collocations": ["write creative nonfiction", "genre of creative nonfiction"], "synonyms": ["narrative nonfiction", "literary journalism"], "antonyms": ["fiction", "academic reporting"], "tags": ["literature", "journalism"]},
    {"headword": "memoir writing", "pronunciation": "/ˈmemwɑː ˈraɪtɪŋ/", "partOfSpeech": "noun", "definition": "The craft of writing a first-person historical account based on the author's personal memories and reflections.", "example": "Honesty, vulnerability, and selective memory are the foundational disciplines of great memoir writing.", "translation": "كتابة المذكرات والسير الذاتية الإبداعية", "collocations": ["excel in memoir writing", "masterclass in memoir writing"], "synonyms": ["autobiographical writing"], "antonyms": ["biography"], "tags": ["writing", "literature"]},
    {"headword": "storytelling craft", "pronunciation": "/ˈstɔːritelɪŋ krɑːft/", "partOfSpeech": "noun", "definition": "The deliberate artistic and technical skill involved in structuring and narrating compelling tales.", "example": "Studying classic cinema screenplays helped the young journalist refine her narrative storytelling craft.", "translation": "حرفة وفن السرد القصصي المشوق", "collocations": ["master the storytelling craft", "hone the storytelling craft"], "synonyms": ["narrative art"], "antonyms": [], "tags": ["writing", "craft"]},
    {"headword": "narrative coherence", "pronunciation": "/ˈnærətɪv kəʊˈhɪərəns/", "partOfSpeech": "noun", "definition": "The logical consistency, thematic integrity, and structural flow holding all parts of a story together.", "example": "Despite multiple time jumps and parallel subplots, the novel preserved immaculate narrative coherence.", "translation": "التماسك والترابط السردي بين خيوط الرواية", "collocations": ["maintain narrative coherence", "lack narrative coherence"], "synonyms": ["story unity"], "antonyms": ["narrative fragmentation"], "tags": ["writing", "analysis"]},
    {"headword": "compelling narrative", "pronunciation": "/kəmˈpelɪŋ ˈnærətɪv/", "partOfSpeech": "noun", "definition": "A gripping and irresistibly captivating story that commands the absolute attention of the audience.", "example": "By weaving personal sacrifice with geopolitical intrigue, she fashioned a deeply compelling narrative.", "translation": "رواية سردية آسرة وجذابة تشد الأنفاس", "collocations": ["construct a compelling narrative", "features of a compelling narrative"], "synonyms": ["gripping tale", "captivating story"], "antonyms": ["tedious story"], "tags": ["writing", "storytelling"]},
    {"headword": "authorial intent", "pronunciation": "/ɔːˈθɔːriəl ɪnˈtent/", "partOfSpeech": "noun", "definition": "The underlying meaning, purpose, or philosophical message the writer intended to communicate.", "example": "Literary critics debate whether authorial intent should dictate how modern audiences interpret classic drama.", "translation": "قصد ونية المؤلف والمعنى الذي أراد إيصاله", "collocations": ["discern authorial intent", "respect authorial intent"], "synonyms": ["author's purpose"], "antonyms": [], "tags": ["criticism", "literature"]}
]

grammar_76 = [
    {
        "title": "Narrative Tenses Review",
        "explanation": "Narrative tenses are the four past tenses used together in English to narrate events, tell stories, and recount past experiences with depth, rhythm, and clarity:\n\n1. Past Simple: The backbone of narration. Recounts finished main actions in chronological order.\n   Example: 'The detective stepped onto the deck, noticed the open safe, and pulled his notebook from his coat.'\n\n2. Past Continuous: Sets the scene, paints background atmosphere, or describes an ongoing action interrupted by a shorter event in the past simple.\n   Example: 'Torrential rain was pounding the windows while the protagonist was reviewing the manuscript.'\n\n3. Past Perfect Simple (had + V3): Establishes events that occurred earlier than the main story time (backstories, past causes, flashbacks).\n   Example: 'Before the shocking story twist occurred, the author had carefully planted clues in chapter one.'\n\n4. Past Perfect Continuous (had been + -ing): Describes continuous or repeated activities leading up to a specific past moment in the story.\n   Example: 'The unreliable narrator had been concealing his identity for months before the final confrontation.'",
        "structures": [
            {"pattern": "Past Simple sequence: Subject + V2, then Subject + V2: 'He heard the noise and reached for the door.'"},
            {"pattern": "Interrupted action: Past Continuous + when + Past Simple: 'I was examining the map when the lights failed.'"},
            {"pattern": "Past Perfect prior cause: Past Simple + because + Past Perfect: 'She gasped because she had recognized the handwriting.'"},
            {"pattern": "Duration before past event: Subject + had been + -ing: 'He had been tracking the suspect for weeks before making contact.'"}
        ],
        "examples": [
            {
                "sentence": "While the narrator was describing the stormy sea, a shocking story twist completely overturned reader expectations.",
                "arabic": "بينما كان الراوي يصف البحر الهائج، قلبت انعطافة صادمة في القصة توقعات القراء تماماً.",
                "usesVocabulary": ["story twist"]
            },
            {
                "sentence": "Before reaching the climactic moment, the protagonist had endured months of harrowing trials across foreign lands.",
                "arabic": "قبل بلوغ لحظة الذروة، كان البطل قد كابد شهوراً من التجارب المريرة عبر بلدان غريبة.",
                "usesVocabulary": ["climactic moment"]
            },
            {
                "sentence": "The audience had been anticipating a romantic subplot, but the author delivered a breathless cliffhanger instead.",
                "arabic": "كان الجمهور يترقب حبكة فرعية رومانسية، غير أن المؤلف قدم نهاية مشوقة معلقة بدلاً من ذلك.",
                "usesVocabulary": ["subplot", "cliffhanger"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "When the detective arrived, the thief already escaped.",
                "right": "When the detective arrived, the thief had already escaped.",
                "explanation": "Use the Past Perfect ('had already escaped') to show that an action occurred before another event in the past."
            },
            {
                "wrong": "As I walked home, it was raining and I was hearing a strange whistle.",
                "right": "As I was walking home, it was raining and I heard a strange whistle.",
                "explanation": "Verbs of instantaneous perception ('hear', 'notice', 'spot') generally take the Past Simple, not the continuous."
            }
        ]
    }
]

convs_76 = [
    {
        "title": "Creative Writing Workshop: Crafting the Climax",
        "titleArabic": "ورشة الكتابة الإبداعية: صناعة لحظة الذروة",
        "setting": "A published novelist critiques a student's novel draft during an intensive seminar.",
        "lines": [
            {"speaker": "Instructor", "text": "Your novel opens with a superb hook opening, but how is your overall narrative arc developing?"},
            {"speaker": "Student", "text": "In the rising action, I had been building tension steadily, weaving subtle foreshadowing into the veteran's backstory."},
            {"speaker": "Instructor", "text": "Excellent. But as you approached the climactic moment, did you maintain taut narrative tension?"},
            {"speaker": "Student", "text": "I tried to. However, my editor felt the comic relief scene dissipated the suspense build-up prematurely."},
            {"speaker": "Instructor", "text": "Comic relief is tricky. It should provide breathing space without deflating rising stakes."},
            {"speaker": "Student", "text": "After the confrontation, the falling action leads to an ironic twist before the denouement."},
            {"speaker": "Instructor", "text": "Consider whether a surprise ending or an ambiguous ending better serves your authorial intent."},
            {"speaker": "Student", "text": "I will study both. I want the open-ended conclusion to resonate long after readers finish the book."}
        ],
        "vocabularyUsed": ["hook opening", "narrative arc", "rising action", "foreshadowing", "backstory", "climactic moment", "narrative tension", "comic relief", "suspense build-up", "rising stakes", "falling action", "ironic twist", "denouement", "surprise ending", "ambiguous ending", "authorial intent", "open-ended conclusion"]
    },
    {
        "title": "Literary Podcast: Exploring Narrative Perspectives",
        "titleArabic": "بودكاست أدبي: استكشاف وجهات النظر السردية",
        "setting": "Two book critics record an episode analyzing modernist fiction techniques.",
        "lines": [
            {"speaker": "Host A", "text": "Welcome back. Today we examine point of view. What makes an unreliable narrator so intellectually thrilling?"},
            {"speaker": "Host B", "text": "Unlike an omniscient narrator, an unreliable first-person narrator conceals motives, forcing readers to untangle dramatic irony."},
            {"speaker": "Host A", "text": "Take Woolf's stream of consciousness style. She immerses us directly inside psychological sensations and memories."},
            {"speaker": "Host B", "text": "Precisely. The embedded story told within the frame narrative reveals the antagonist motive through flashbacks."},
            {"speaker": "Host A", "text": "And the vivid description of the old lighthouse layers sensory detail on top of metaphorical expression."},
            {"speaker": "Host B", "text": "Her inventive simile usage and striking personification transform the stormy sea into an active supporting character."},
            {"speaker": "Host A", "text": "Notice also how the author employs understatement rather than the hyperbole effect to heighten tragedy."},
            {"speaker": "Host B", "text": "Mastering the storytelling craft demands knowing exactly when figurative language elevates a narrative."}
        ],
        "vocabularyUsed": ["point of view", "unreliable narrator", "omniscient narrator", "first-person narrator", "dramatic irony", "stream of consciousness", "embedded story", "frame narrative", "antagonist motive", "flashback", "vivid description", "sensory detail", "metaphorical expression", "simile usage", "personification", "understatement", "hyperbole effect", "supporting character", "storytelling craft", "figurative language"]
    },
    {
        "title": "Masterclass in Non-Fiction: The Art of the Memoir",
        "titleArabic": "درس متقدم في الأدب الواقعي: فن كتابة المذكرات",
        "setting": "An author discusses the boundaries between creative nonfiction and historical veracity.",
        "lines": [
            {"speaker": "Interviewer", "text": "How does memoir writing differ from conventional historical documentation?"},
            {"speaker": "Author", "text": "Memoir writing belongs to creative nonfiction. You are recounting true events using the techniques of a compelling narrative."},
            {"speaker": "Interviewer", "text": "Do you exercise poetic license when recounting distant conversations from your youth?"},
            {"speaker": "Author", "text": "A writer might recreate dialogue for narrative coherence, but emotional honesty must never be compromised."},
            {"speaker": "Interviewer", "text": "Your book begins with an anecdote opening that immediately establishes your distinctive narrative voice."},
            {"speaker": "Author", "text": "Thank you. I had been experimenting with third-person limited before I embraced an intimate first-person voice."},
            {"speaker": "Interviewer", "text": "The protagonist journey through grief felt universal, especially the cliffhanger ending of chapter five."},
            {"speaker": "Author", "text": "That journey was painful to write, but sharing vulnerability is what makes memoirs resonate deeply."}
        ],
        "vocabularyUsed": ["memoir writing", "creative nonfiction", "compelling narrative", "poetic license", "narrative coherence", "anecdote opening", "narrative voice", "third-person limited", "first-person narrator", "protagonist journey", "cliffhanger"]
    }
]

paras_76 = [
    {
        "title": "The Architecture of Story: Pacing, Tension, and Plot",
        "titleArabic": "هندسة القصة: الإيقاع، التوتر، وتطور الحبكة",
        "text": "Every captivating novel relies on a thoughtfully structured narrative arc that guides readers through emotional highs and valleys. Beginning with an arresting hook opening, skillful authors weave essential exposition seamlessly into the rising action while escalating rising stakes. By planting subtle foreshadowing and revealing a character's poignant backstory through well-timed flashbacks, writers intensify narrative tension. As the plot hurtles toward the climactic moment, a shocking story twist or devastating cliffhanger leaves audiences breathless. Finally, in the falling action and elegant denouement, the lingering questions of the central plot and romantic subplot find their resolution.",
        "vocabularyUsed": ["narrative arc", "hook opening", "exposition", "rising action", "rising stakes", "foreshadowing", "backstory", "flashback", "narrative tension", "climactic moment", "story twist", "cliffhanger", "falling action", "denouement", "subplot"]
    },
    {
        "title": "Narrative Perspectives, Devices, and Literary Style",
        "titleArabic": "وجهات النظر السردية، التقنيات البلاغية، والأسلوب الأدبي",
        "text": "Choosing the appropriate point of view fundamentally shapes how readers experience a literary world. While an omniscient narrator offers a panoramic understanding of all characters, an intimate first-person narrator or an elusive unreliable narrator heightens psychological complexity. Modernists pioneered stream of consciousness to depict unfiltered internal monologues, often employing dramatic irony to highlight the gulf between perception and reality. Furthermore, layering prose with vivid description, evocative sensory detail, and imaginative figurative language elevates ordinary scenes into poetic art. Whether through delicate personification, creative simile usage, or subtle understatement, stylistic choices reflect deliberate authorial intent.",
        "vocabularyUsed": ["point of view", "omniscient narrator", "first-person narrator", "unreliable narrator", "stream of consciousness", "dramatic irony", "vivid description", "sensory detail", "figurative language", "personification", "simile usage", "understatement", "authorial intent"]
    },
    {
        "title": "Creative Nonfiction, Memoir Writing, and the Storyteller's Craft",
        "titleArabic": "الأدب غير الروائي الإبداعي، كتابة المذكرات، وحرفة الحكواتي",
        "text": "The flourishing genre of creative nonfiction proves that real-world truths can be told with the artistic intensity of great fiction. In contemporary memoir writing, authors craft a compelling narrative by organizing personal memories into a cohesive protagonist journey. Opening with an entertaining anecdote opening instantly connects the reader to the author's authentic narrative voice. While writers occasionally invoke poetic license to reconstruct historical conversations, preserving emotional veracity and narrative coherence remains paramount. Rather than relying on a predictable conclusion, gifted memoirists often conclude with a thought-provoking open-ended conclusion or ambiguous ending that invites enduring reflection.",
        "vocabularyUsed": ["creative nonfiction", "memoir writing", "compelling narrative", "protagonist journey", "anecdote opening", "narrative voice", "poetic license", "narrative coherence", "open-ended conclusion", "ambiguous ending"]
    }
]

if __name__ == "__main__":
    write_day(75, vocab_75, grammar_75, convs_75, paras_75)
    write_day(76, vocab_76, grammar_76, convs_76, paras_76)
    print("Day 75 and Day 76 generated successfully.")
