# -*- coding: utf-8 -*-
"""Builder for Day 63 and Day 64: Stage 7 (Problems, Decisions and Opinions)."""

import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts.curriculum_engine import write_day

# ==============================================================================
# DAY 63: Wishes and Regrets (Wanting things to be different)
# Grammar: ["Wish + Past; Wish + would / could"]
# ==============================================================================
vocab_63 = [
    # Wishes, Longing & Fantasies (15)
    {"headword": "wishful thinking", "pronunciation": "/ˈwɪʃfl ˈθɪŋkɪŋ/", "partOfSpeech": "noun", "definition": "The illusion that what one wishes for is actually true or will happen.", "example": "Hoping the market will double overnight is pure wishful thinking.", "translation": "تفكير بالتمني / أوهام رغائبية", "exampleArabic": "الرجاء بأن السوق سيتضاعف بين عشية وضحاها هو مجرد تفكير بالتمني.", "collocations": ["mere wishful thinking", "indulge in wishful thinking"], "synonyms": ["pipe dream", "fantasy"], "antonyms": ["hard reality"], "tags": ["wishes", "psychology"]},
    {"headword": "if only", "pronunciation": "/ɪf ˈəʊnli/", "partOfSpeech": "phrase", "definition": "Used to express a strong wish, yearning, or deep regret.", "example": "If only I had listened to my mentor's advice about diversified investing.", "translation": "يا ليت / لو أن فقط", "exampleArabic": "يا ليتني استمعت لنصيحة مرشدي بشأن التنويع في الاستثمار.", "collocations": ["if only I knew", "if only we could"], "synonyms": ["I wish that"], "antonyms": [], "tags": ["regrets", "idioms"]},
    {"headword": "in hindsight", "pronunciation": "/ɪn ˈhaɪndsaɪt/", "partOfSpeech": "phrase", "definition": "Understanding the nature of an event only after it has actually happened.", "example": "In hindsight, selling the family house during the recession was a tactical error.", "translation": "عند النظر للوراء / بأثر رجعي", "exampleArabic": "عند النظر للوراء بأثر رجعي، كان بيع منزل العائلة أثناء الركود خطأً تكتيكياً.", "collocations": ["easy in hindsight", "clear in hindsight"], "synonyms": ["retrospectively"], "antonyms": ["in foresight"], "tags": ["reflection", "idioms"]},
    {"headword": "with hindsight", "pronunciation": "/wɪð ˈhaɪndsaɪt/", "partOfSpeech": "phrase", "definition": "With the perception and clarity that comes from looking back at the past.", "example": "With hindsight, we wish we had retained the patent rights instead of licensing them.", "translation": "في ضوء ما تبين لاحقاً / بحكمة ما بعد التجربة", "exampleArabic": "في ضوء ما تبين لاحقاً، نتمنى لو احتفظنا بحقوق براءة الاختراع بدلاً من ترخيصها.", "collocations": ["blessed with hindsight", "view with hindsight"], "synonyms": ["with retrospective clarity"], "antonyms": [], "tags": ["reflection", "idioms"]},
    {"headword": "rue the day", "pronunciation": "/ruː ðə deɪ/", "partOfSpeech": "verb", "definition": "To bitterly regret a specific moment, decision, or past action.", "example": "He will rue the day he signed that predatory non-disclosure agreement.", "translation": "يلعن اليوم الذي فعل فيه ذلك / يندم أشد الندم", "exampleArabic": "سيندم أشد الندم ويلعن اليوم الذي وقع فيه اتفاقية عدم الإفصاح الجائرة تلك.", "verbForms": {"v1": "rue the day", "v2": "rued the day", "v3": "rued the day"}, "collocations": ["live to rue the day", "forever rue the day"], "synonyms": ["bitterly regret"], "antonyms": ["rejoice in the day"], "tags": ["regrets", "idioms"]},
    {"headword": "lament", "pronunciation": "/ləˈment/", "partOfSpeech": "verb", "definition": "To express deep sorrow, grief, or passionate regret about something.", "example": "Old scholars lament the loss of handwritten manuscript literacy in modern youth.", "translation": "يتحسر على / يندب حظه", "exampleArabic": "يتحسر العلماء القدامى على ضياع مهارة قراءة المخطوطات اليدوية بين شباب العصر.", "verbForms": {"v1": "lament", "v2": "lamented", "v3": "lamented"}, "collocations": ["lament the passing of", "openly lament"], "synonyms": ["bemoan", "mourn"], "antonyms": ["celebrate"], "tags": ["emotions", "actions"]},
    {"headword": "remorseful", "pronunciation": "/rɪˈmɔːsfl/", "partOfSpeech": "adjective", "definition": "Filled with deep, painful regret and guilt for past wrongs committed.", "example": "The remorseful witness apologized tearfully to the falsely accused defendant.", "translation": "نادم بعمق / يعتصره تأنيب الضمير", "exampleArabic": "اعتذر الشاهد النادم والباكي للمدعى عليه المتهم ظلماً.", "collocations": ["deeply remorseful", "appear remorseful"], "synonyms": ["contrite", "repentant"], "antonyms": ["unrepentant"], "tags": ["emotions", "guilt"]},
    {"headword": "pangs of conscience", "pronunciation": "/pæŋz əv ˈkɒnʃəns/", "partOfSpeech": "noun", "definition": "Sudden, sharp twinges of guilt, regret, or moral shame.", "example": "He felt sharp pangs of conscience after concealing the financial audit mistake.", "translation": "وخزات الضمير / لدغات الندم الأخلاقي", "exampleArabic": "شعر بوخزات ضمير حادة بعد إخفاء خطأ التدقيق المالي.", "collocations": ["suffer pangs of conscience", "ignore pangs of conscience"], "synonyms": ["qualms", "twinges of guilt"], "antonyms": ["clear conscience"], "tags": ["morals", "psychology"]},
    {"headword": "aching desire", "pronunciation": "/ˈeɪkɪŋ dɪˈzaɪə/", "partOfSpeech": "noun", "definition": "An intense, painful longing or persistent craving for someone or something.", "example": "She harbored an aching desire to return to her homeland and see the olive groves.", "translation": "شوق مؤلم / رغبة ملحة تعتصر القلب", "exampleArabic": "أضمرت في قلبها شوقاً مؤلماً للعودة إلى وطنها ورؤية بساتين الزيتون.", "collocations": ["feel an aching desire", "suppress an aching desire"], "synonyms": ["deep yearning"], "antonyms": ["indifference"], "tags": ["emotions", "desire"]},
    {"headword": "longing", "pronunciation": "/ˈlɒŋɪŋ/", "partOfSpeech": "noun", "definition": "A yearning desire, often accompanied by sadness or wistful distance.", "example": "His eyes reflected a quiet longing for the simpler peaceful days of his youth.", "translation": "حنين وشوق عميق", "exampleArabic": "عكست عيناه حنيناً هادئاً للأيام الأبسط والأكثر سكينة في شبابه.", "collocations": ["intense longing", "look of longing"], "synonyms": ["craving", "yearning"], "antonyms": ["contentment"], "tags": ["feelings", "nostalgia"]},
    {"headword": "wistful", "pronunciation": "/ˈwɪstfl/", "partOfSpeech": "adjective", "definition": "Having or showing a feeling of vague or regretful longing.", "example": "She cast a wistful glance at the ocean horizon as the departing ship sailed away.", "translation": "مليء بالحنين والأسى الهادئ / شارد بحسرة", "exampleArabic": "ألقت نظرة تفيض بالحنين والأسى الهادئ على أفق المحيط مع إبحار السفينة المغادرة.", "collocations": ["wistful smile", "wistful look"], "synonyms": ["nostalgic", "pensive"], "antonyms": ["cheerful"], "tags": ["mood", "feelings"]},
    {"headword": "nostalgic longing", "pronunciation": "/nɒˈstældʒɪk ˈlɒŋɪŋ/", "partOfSpeech": "noun", "definition": "A sentimental yearning for the happiness felt in a former place or time.", "example": "The scent of wild lavender stirred nostalgic longing for her grandmother's garden.", "translation": "شوق ونوستالجيا للماضي", "exampleArabic": "أثارت رائحة اللافندر البري شوقاً نوستالجياً لحديقة جدتها.", "collocations": ["stir nostalgic longing", "sense of nostalgic longing"], "synonyms": ["homesickness for the past"], "antonyms": [], "tags": ["nostalgia", "emotions"]},
    {"headword": "daydream", "pronunciation": "/ˈdeɪdriːm/", "partOfSpeech": "verb", "definition": "To indulge in a series of pleasant, visionary, but unrealizable thoughts.", "example": "I wish I did not daydream during corporate accounting presentations.", "translation": "يسرح بأحلام اليقظة", "exampleArabic": "أتمنى لو لم أسرح بأحلام اليقظة أثناء العروض التقديمية للمحاسبة المؤسسية.", "verbForms": {"v1": "daydream", "v2": "daydreamed", "v3": "daydreamed"}, "collocations": ["daydream about the future", "prone to daydream"], "synonyms": ["fantasize", "woolgather"], "antonyms": ["focus sharply"], "tags": ["imagination", "actions"]},
    {"headword": "pie in the sky", "pronunciation": "/ˌpaɪ ɪn ðə ˈskaɪ/", "partOfSpeech": "noun", "definition": "Something pleasant that is promised or wished for but very unlikely to happen.", "example": "Their proposal for automated zero-cost public healthcare proved to be pie in the sky.", "translation": "أمانٍ خيالية مستحيلة / أضغاث أحلام", "exampleArabic": "أثبت مقترحهم لرعاية صحية عامة مؤتمتة ومجانية تماماً أنه مجرد أمانٍ خيالية مستحيلة.", "collocations": ["dismiss as pie in the sky", "sound like pie in the sky"], "synonyms": ["unrealistic dream"], "antonyms": ["concrete reality"], "tags": ["unrealistic", "idioms"]},
    {"headword": "pipe dream", "pronunciation": "/ˈpaɪp driːm/", "partOfSpeech": "noun", "definition": "An unattainable, fantastic, or hopeless plan or hope.", "example": "Building a lunar colony by next year is a pure engineering pipe dream.", "translation": "حلم واهم مستحيل التحقيق", "exampleArabic": "بناء مستعمرة قمرية بحلول العام القادم هو مجرد حلم هندسي واهم مستحيل.", "collocations": ["shatter a pipe dream", "turn out to be a pipe dream"], "synonyms": ["chimera", "fantasy"], "antonyms": ["achievable objective"], "tags": ["unrealistic", "idioms"]},

    # Missed Chances & Heartbreak (15)
    {"headword": "castle in the air", "pronunciation": "/ˌkɑːsl ɪn ðə ˈeə/", "partOfSpeech": "noun", "definition": "A daydream, speculative vision, or visionary project that has no firm foundation.", "example": "Stop building castles in the air and draft a realistic, verifiable business budget.", "translation": "قصور في الرمال / أوهام لا أساس لها", "exampleArabic": "توقف عن بناء قصور في الهواء وضع ميزانية عمل واقعية وقابلة للتحقق.", "collocations": ["build castles in the air", "fanciful castles in the air"], "synonyms": ["daydream"], "antonyms": ["grounded plan"], "tags": ["fantasy", "idioms"]},
    {"headword": "lost chance", "pronunciation": "/lɒst tʃɑːns/", "partOfSpeech": "noun", "definition": "An opportunity that was allowed to slip away unutilized.", "example": "Failing to purchase shares before the technological revolution was a bitterly lost chance.", "translation": "فرصة ضائعة", "exampleArabic": "كان الإخفاق في شراء الأسهم قبل الثورة التكنولوجية فرصة ضائعة بمرارة.", "collocations": ["mourn a lost chance", "another lost chance"], "synonyms": ["missed opportunity"], "antonyms": ["seized moment"], "tags": ["opportunity", "loss"]},
    {"headword": "golden opportunity missed", "pronunciation": "/ˈɡəʊldən ˌɒpəˈtjuːnəti mɪst/", "partOfSpeech": "noun", "definition": "A uniquely favorable, rare occasion that was neglected or overlooked.", "example": "Rejecting that university scholarship was a golden opportunity missed.", "translation": "فرصة ذهبية مهدرة", "exampleArabic": "كان رفض تلك المنحة الجامعية فرصة ذهبية مهدرة لن تتكرر.", "collocations": ["regret a golden opportunity missed", "classic golden opportunity missed"], "synonyms": ["squandered chance"], "antonyms": ["opportunity seized"], "tags": ["regrets", "opportunities"]},
    {"headword": "second thoughts", "pronunciation": "/ˈsekənd θɔːts/", "partOfSpeech": "noun", "definition": "A reconsideration of an earlier decision or opinion, accompanied by doubt.", "example": "I wish I had listened to my second thoughts before signing the apartment lease.", "translation": "شكوك وتفكير متأخر / تردد بعد الاتفاق", "exampleArabic": "أتمنى لو استمعت لشكوكي وتفكيري المتأخر قبل توقيع عقد إيجار الشقة.", "collocations": ["have second thoughts", "give cause for second thoughts"], "synonyms": ["reconsideration", "qualms"], "antonyms": ["unwavering conviction"], "tags": ["doubt", "decisions"]},
    {"headword": "change of heart", "pronunciation": "/ˈtʃeɪndʒ əv hɑːt/", "partOfSpeech": "noun", "definition": "A reversal of one's opinions, feelings, intentions, or loyalties.", "example": "He had a sudden change of heart and decided to forgive his estranged brother.", "translation": "تبدل في المشاعر والموقف / انقلاب في الرأي", "exampleArabic": "حدث له تبدل مفاجئ في المشاعر والموقف وقرر أن يصفح عن شقيقه المبتعد.", "collocations": ["experience a change of heart", "sudden change of heart"], "synonyms": ["turnabout"], "antonyms": ["stubborn stance"], "tags": ["transformation", "emotions"]},
    {"headword": "bitter regret", "pronunciation": "/ˈbɪtə rɪˈɡret/", "partOfSpeech": "noun", "definition": "A harsh, agonizing feeling of sorrow for what might have been done.", "example": "She felt bitter regret that she had never reconciled with her grandfather before his death.", "translation": "ندم مرير ومؤلم", "exampleArabic": "شعرت بندم مرير ومؤلم لكونها لم تتصالح مع جدها قبل وفاته.", "collocations": ["filled with bitter regret", "endure bitter regret"], "synonyms": ["deep remorse"], "antonyms": ["pure satisfaction"], "tags": ["emotions", "sorrow"]},
    {"headword": "deep remorse", "pronunciation": "/diːp rɪˈmɔːs/", "partOfSpeech": "noun", "definition": "An intense, gnawing psychological pain arising from moral fault.", "example": "The convicted driver showed deep remorse throughout the emotional courtroom hearing.", "translation": "ندم عميق يعتصر الفؤاد", "exampleArabic": "أظهر السائق المدان ندماً عميقاً يعتصر الفؤاد طوال جلسة المحكمة المؤثرة.", "collocations": ["express deep remorse", "burdened by deep remorse"], "synonyms": ["heartfelt contrition"], "antonyms": ["callous indifference"], "tags": ["guilt", "morals"]},
    {"headword": "unfulfilled desire", "pronunciation": "/ˌʌnfʊlˈfɪld dɪˈzaɪə/", "partOfSpeech": "noun", "definition": "A profound yearning or longing that has never been satisfied.", "example": "His unfulfilled desire to publish a historical novel lingered into his retirement years.", "translation": "رغبة دفينة لم تتحقق", "exampleArabic": "ظلت رغبته الدفينة في نشر رواية تاريخية تراوده حتى سنوات تقاعده.", "collocations": ["ache of unfulfilled desire", "harbor unfulfilled desires"], "synonyms": ["unrealized craving"], "antonyms": ["fulfilled wish"], "tags": ["desire", "disappointment"]},
    {"headword": "unrequited wish", "pronunciation": "/ˌʌnrɪˈkwaɪtɪd wɪʃ/", "partOfSpeech": "noun", "definition": "A wish or hope that remains completely unanswered, unreturned, or ignored.", "example": "Her long letters seemed like an unrequited wish cast into an empty canyon.", "translation": "أمنية بلا صدى ولا استجابة", "exampleArabic": "بدت رسائلها الطويلة كأنها أمنية بلا صدى أُلقيت في وادٍ سحيق فارغ.", "collocations": ["mourn an unrequited wish", "live with unrequited wishes"], "synonyms": ["unanswered hope"], "antonyms": ["answered prayer"], "tags": ["longing", "unrequited"]},
    {"headword": "what might have been", "pronunciation": "/wɒt maɪt həv biːn/", "partOfSpeech": "phrase", "definition": "Reflective contemplation about hypothetical alternate outcomes of one's past.", "example": "It is agonizing to constantly brood over what might have been instead of moving forward.", "translation": "ما كان يمكن أن يكون / لو جرت الأمور بشكل آخر", "exampleArabic": "من المؤلم والمضني أن يظل المرء ينوح على ما كان يمكن أن يكون بدلاً من المضي قدماً.", "collocations": ["wonder what might have been", "mourn what might have been"], "synonyms": ["unrealized paths"], "antonyms": ["present reality"], "tags": ["regrets", "idioms"]},
    {"headword": "spilt milk", "pronunciation": "/spɪlt mɪlk/", "partOfSpeech": "noun", "definition": "An error, misfortune, or damage that has occurred and cannot be altered.", "example": "The lost grant money is spilt milk; we must look for fresh private benefactors.", "translation": "لبن مسكوب / ضرر فات أوانه ولا سبيل لإصلاحه", "exampleArabic": "أموال المنحة المفقودة هي لبن مسكوب؛ يجب علينا البحث عن ممولين خواص جدد.", "collocations": ["view as spilt milk", "merely spilt milk"], "synonyms": ["irreversible loss"], "antonyms": [], "tags": ["idioms", "acceptance"]},
    {"headword": "cry over spilt milk", "pronunciation": "/kraɪ ˈəʊvə spɪlt mɪlk/", "partOfSpeech": "verb", "definition": "To waste time and emotional energy mourning past mistakes that cannot be undone.", "example": "Do not cry over spilt milk; focus your intelligence on the upcoming quarterly rollout.", "translation": "يبكي على اللبن المسكوب", "exampleArabic": "لا تبكِ على اللبن المسكوب؛ بل ركز ذكاءك على إطلاق الربع القادم.", "verbForms": {"v1": "cry over spilt milk", "v2": "cried over spilt milk", "v3": "cried over spilt milk"}, "collocations": ["no use crying over spilt milk", "refuse to cry over spilt milk"], "synonyms": ["lament the irreversible"], "antonyms": ["look forward"], "tags": ["idioms", "actions"]},
    {"headword": "turn back clock", "pronunciation": "/tɜːn bæk klɒk/", "partOfSpeech": "verb", "definition": "To return to the past or recreate bygone conditions.", "example": "If only I could turn back the clock and redo that critical investor pitch.", "translation": "يعيد عقارب الساعة للوراء", "exampleArabic": "يا ليتني أستطيع إعادة عقارب الساعة للوراء وإعادة ذلك العرض الحاسم للمستثمرين.", "verbForms": {"v1": "turn back clock", "v2": "turned back clock", "v3": "turned back clock"}, "collocations": ["wish to turn back clock", "impossible to turn back clock"], "synonyms": ["rewind time"], "antonyms": ["march forward"], "tags": ["time", "idioms"]},
    {"headword": "consolation prize", "pronunciation": "/ˌkɒnsəˈleɪʃn praɪz/", "partOfSpeech": "noun", "definition": "A minor reward given to someone who fails to win the primary contest.", "example": "The runner-up certificate felt like an empty consolation prize after losing the championship.", "translation": "جائزة ترضية", "exampleArabic": "بدت شهادة الوصيف وكأنها مجرد جائزة ترضية فارغة بعد خسارة البطولة.", "collocations": ["mere consolation prize", "offer a consolation prize"], "synonyms": ["token reward"], "antonyms": ["grand prize"], "tags": ["rewards", "disappointment"]},
    {"headword": "cold comfort", "pronunciation": "/ˌkəʊld ˈkʌmfət/", "partOfSpeech": "noun", "definition": "Sympathy, consolation, or reassurance that offers little or no genuine comfort.", "example": "Knowing that other competitors also failed was cold comfort to the bankrupted inventor.", "translation": "عزاء بارد لا يسمن ولا يغني من جوع", "exampleArabic": "كانت معرفة أن المنافسين الآخرين قد فشلوا أيضاً مجرد عزاء بارد للمخترع المفلس.", "collocations": ["provide cold comfort", "derive cold comfort"], "synonyms": ["scant consolation"], "antonyms": ["heartfelt solace"], "tags": ["consolation", "idioms"]},

    # Redress, Healing & Bittersweet Acceptance (20)
    {"headword": "silver lining", "pronunciation": "/ˌsɪlvə ˈlaɪnɪŋ/", "partOfSpeech": "noun", "definition": "A comforting or hopeful aspect present within an otherwise bleak or miserable situation.", "example": "The silver lining of the factory closure was that it prompted her to start her own firm.", "translation": "الجانب الإيجابي المشرق في قلب المحنة", "exampleArabic": "كان الجانب الإيجابي المشرق لإغلاق المصنع أنه دفعها لتأسيس شركتها الخاصة.", "collocations": ["find the silver lining", "every cloud has a silver lining"], "synonyms": ["bright side"], "antonyms": ["dark cloud"], "tags": ["optimism", "idioms"]},
    {"headword": "make amends", "pronunciation": "/meɪk əˈmendz/", "partOfSpeech": "verb", "definition": "To compensate someone for a grievance or undo the harm caused by one's fault.", "example": "I wish I could make amends to those I wronged during my arrogant early twenties.", "translation": "يكفّر عن خطئه / يصلح ما أفسده", "exampleArabic": "أتمنى لو أستطيع التكفير عن أخطائي لمن أسأت إليهم أثناء غرور أوائل عشرينياتي.", "verbForms": {"v1": "make amends", "v2": "made amends", "v3": "made amends"}, "collocations": ["sincerely make amends", "try to make amends"], "synonyms": ["atone", "compensate"], "antonyms": ["compound injury"], "tags": ["morals", "actions"]},
    {"headword": "redress a mistake", "pronunciation": "/rɪˈdres ə mɪsˈteɪk/", "partOfSpeech": "verb", "definition": "To set right, remedy, or rectify an unfair or erroneous past deed.", "example": "The municipal authority took immediate measures to redress a mistake in property tax rates.", "translation": "يصحح خطأً / يعالج مظلمة سابقة", "exampleArabic": "اتخذت سلطة البلدية تدابير فورية لتصحيح خطأ في أسعار ضريبة العقارات.", "verbForms": {"v1": "redress a mistake", "v2": "redressed a mistake", "v3": "redressed a mistake"}, "collocations": ["strive to redress a mistake", "opportunity to redress a mistake"], "synonyms": ["rectify error"], "antonyms": ["perpetuate wrong"], "tags": ["justice", "actions"]},
    {"headword": "pine for", "pronunciation": "/paɪn fɔː/", "partOfSpeech": "verb", "definition": "To yearn intensely and persistently for someone or something, often while wasting away.", "example": "She pined for the majestic mountains of her childhood throughout her stay in the desert city.", "translation": "يحن ويتلهف بشوق يضني البدن", "exampleArabic": "حنت وتلهفت بشوق يضني القلب لجبال طفولتها الشامخة طوال إقامتها بالمدينة الصحراوية.", "verbForms": {"v1": "pine for", "v2": "pined for", "v3": "pined for"}, "collocations": ["pine for home", "pine for past love"], "synonyms": ["yearn deeply", "languish for"], "antonyms": ["forget completely"], "tags": ["longing", "actions"]},
    {"headword": "mourn the loss", "pronunciation": "/mɔːn ðə lɒs/", "partOfSpeech": "verb", "definition": "To feel or express deep grief for the demise or passing of someone or something treasured.", "example": "The artistic community continues to mourn the loss of the brilliant playwright.", "translation": "ينعى الفقد / ينوح على خسارة عزيزة", "exampleArabic": "يواصل المجتمع الفني نعي الفقد والحداد على رحيل الكاتب المسرحي العبقري.", "verbForms": {"v1": "mourn the loss", "v2": "mourned the loss", "v3": "mourned the loss"}, "collocations": ["deeply mourn the loss", "nation mourns the loss"], "synonyms": ["grieve over"], "antonyms": ["celebrate recovery"], "tags": ["grief", "actions"]},
    {"headword": "bemoan", "pronunciation": "/bɪˈməʊn/", "partOfSpeech": "verb", "definition": "To express deep discontent, sorrow, or regret over an unfavorable condition.", "example": "Critics bemoan the decline of classical literature in secondary school curricula.", "translation": "يندب وينعى / يتشكى بمرارة", "exampleArabic": "ينعى النقاد بمرارة تراجع الأدب الكلاسيكي في مناهج المدارس الثانوية.", "verbForms": {"v1": "bemoan", "v2": "bemoaned", "v3": "bemoaned"}, "collocations": ["bemoan the fate of", "constantly bemoan"], "synonyms": ["lament", "bewail"], "antonyms": ["applaud"], "tags": ["complaint", "actions"]},
    {"headword": "self-reproach", "pronunciation": "/ˌself rɪˈprəʊtʃ/", "partOfSpeech": "noun", "definition": "Reproach or blame directed against oneself for personal failures.", "example": "He spent years consumed by bitter self-reproach after causing the family business rupture.", "translation": "لوم النفس / تأنيب الذات القاسي", "exampleArabic": "أمضى سنوات ينهشه لوم النفس وتأنيب الذات بعد تسببه في انهيار أعمال العائلة.", "collocations": ["burden of self-reproach", "voice self-reproach"], "synonyms": ["self-blame"], "antonyms": ["self-congratulation"], "tags": ["psychology", "guilt"]},
    {"headword": "guilt trip", "pronunciation": "/ˈɡɪlt trɪp/", "partOfSpeech": "noun", "definition": "A feeling of guilt, especially when intentionally induced by someone else.", "example": "Do not let your relatives lay a guilt trip on you for prioritizing your career.", "translation": "عقدة ذنب / ابتزاز عاطفي بتأنيب الضمير", "exampleArabic": "لا تدع أقاربك يفرضون عليك عقدة ذنب لكونك تعطي الأولوية لمسارك المهني.", "collocations": ["lay a guilt trip on", "fall for a guilt trip"], "synonyms": ["induced remorse"], "antonyms": [], "tags": ["psychology", "relationships"]},
    {"headword": "heavy heart", "pronunciation": "/ˌhevi ˈhɑːt/", "partOfSpeech": "noun", "definition": "A profound feeling of deep sorrow, sadness, or reluctance.", "example": "With a heavy heart, the headmaster announced the permanent closure of the rural school.", "translation": "قلب مثقل بالأسى والحزن", "exampleArabic": "بقلب مثقل بالأسى، أعلن مدير المدرسة الإغلاق النهائي للمدرسة الريفية.", "collocations": ["with a heavy heart", "leave with a heavy heart"], "synonyms": ["deep sorrow"], "antonyms": ["light heart"], "tags": ["sorrow", "idioms"]},
    {"headword": "haunted by past", "pronunciation": "/ˈhɔːntɪd baɪ pɑːst/", "partOfSpeech": "adjective", "definition": "Continually troubled, disturbed, or plagued by painful memories of past deeds.", "example": "The veteran explorer was haunted by past mistakes committed in the arctic expedition.", "translation": "تطارده أشباح الماضي / أسير لذكرياته الأليمة", "exampleArabic": "كان المستكشف المخضرم مطارداً بأشباح أخطاء الماضي التي وقعت في الحملة القطبية.", "collocations": ["remained haunted by past", "haunted by past trauma"], "synonyms": ["plagued by memories"], "antonyms": ["peaceful with past"], "tags": ["psychology", "trauma"]},
    {"headword": "look back with regret", "pronunciation": "/lʊk bæk wɪð rɪˈɡret/", "partOfSpeech": "verb", "definition": "To reflect on previous choices with sorrow, wishing they had been different.", "example": "I wish I did not look back with regret on my creative decisions during university.", "translation": "ينظر للوراء بأسف وندم", "exampleArabic": "أتمنى لو لم أنظر للوراء بأسف وندم على قراراتي الإبداعية أثناء دراستي الجامعية.", "verbForms": {"v1": "look back with regret", "v2": "looked back with regret", "v3": "looked back with regret"}, "collocations": ["look back with regret on", "never look back with regret"], "synonyms": ["retrospect sorrowfully"], "antonyms": ["look back with pride"], "tags": ["reflection", "actions"]},
    {"headword": "letdown", "pronunciation": "/ˈletdaʊn/", "partOfSpeech": "noun", "definition": "A disappointment or disillusionment following high hopes.", "example": "The much-anticipated technological sequel was a colossal letdown to gamers.", "translation": "خيبة أمل / إحباط شديد", "exampleArabic": "كان الجزء الثاني المرتقب للعبة خيبة أمل كبرى للاعبين.", "collocations": ["bitter letdown", "major letdown"], "synonyms": ["disappointment"], "antonyms": ["triumph"], "tags": ["feelings", "disappointment"]},
    {"headword": "unmet expectation", "pronunciation": "/ʌnˈmet ˌekspekˈteɪʃn/", "partOfSpeech": "noun", "definition": "A standard, hope, or goal that was not achieved or satisfied.", "example": "Unmet expectations in early marriage often lead to preventable friction.", "translation": "توقعات لم تتحقق / آمال خائبة", "exampleArabic": "غالباً ما تؤدي التوقعات غير المتحققة في بداية الزواج إلى خلافات كان يمكن تفاديها.", "collocations": ["cope with unmet expectations", "burden of unmet expectations"], "synonyms": ["disappointed hopes"], "antonyms": ["fulfilled expectations"], "tags": ["disappointment", "psychology"]},
    {"headword": "harsh awakening", "pronunciation": "/hɑːʃ əˈweɪknɪŋ/", "partOfSpeech": "noun", "definition": "A painful, abrupt realization of the unpleasant truth of a situation.", "example": "Graduating into an economic depression was a harsh awakening for young scholars.", "translation": "يقظة قاسية على الواقع / صدمة الحقيقة المرة", "exampleArabic": "كان التخرج في خضم ركود اقتصادي يقظة قاسية وصدمة مريرة للباحثين الشباب.", "collocations": ["suffer a harsh awakening", "rude or harsh awakening"], "synonyms": ["rude awakening", "cold reality check"], "antonyms": ["blissful ignorance"], "tags": ["realization", "events"]},
    {"headword": "shattered dream", "pronunciation": "/ˈʃætəd driːm/", "partOfSpeech": "noun", "definition": "A deeply cherished hope or ambition that has been completely destroyed.", "example": "His shattered dream of becoming an Olympic gymnast left him directionless for months.", "translation": "حلم محطم / أمل متبدد", "exampleArabic": "تركه حلمه المحطم بأن يصبح بطلاً أولمبياً في الجمباز تائهاً لعدة أشهر.", "collocations": ["mourn a shattered dream", "pieces of a shattered dream"], "synonyms": ["destroyed ambition"], "antonyms": ["realized ambition"], "tags": ["loss", "tragedy"]},
    {"headword": "faded hope", "pronunciation": "/ˈfeɪdɪd həʊp/", "partOfSpeech": "noun", "definition": "An optimism or confidence that has gradually weakened and nearly vanished.", "example": "Faded hopes for an early diplomatic breakthrough prompted families to flee.", "translation": "أمل خافت متلاشٍ", "exampleArabic": "دفعت الآمال المتلاشية في تحقيق اختراق دبلوماسي مبكر العائلات إلى الفرار.", "collocations": ["clinging to faded hope", "revive faded hope"], "synonyms": ["dwindling optimism"], "antonyms": ["bright hope"], "tags": ["emotions", "despair"]},
    {"headword": "unreachable ideal", "pronunciation": "/ʌnˈriːtʃəbl aɪˈdiːəl/", "partOfSpeech": "noun", "definition": "A perfect standard or model that cannot possibly be attained in real life.", "example": "Striving for an unreachable ideal of physical flawlessness fuels chronic anxiety.", "translation": "نموذج مثالي مستحيل المنال", "exampleArabic": "يغذي السعي وراء نموذج مثالي مستحيل المنال للكمال الجسدي القلق المزمن.", "collocations": ["pursue an unreachable ideal", "chasing an unreachable ideal"], "synonyms": ["unattainable perfection"], "antonyms": ["practical standard"], "tags": ["perfectionism", "ideals"]},
    {"headword": "forlorn hope", "pronunciation": "/fəˈlɔːn həʊp/", "partOfSpeech": "noun", "definition": "A persistent hope that has virtually no chance of being fulfilled.", "example": "Searching the wreckage after three weeks was a forlorn hope for the rescue squad.", "translation": "رجاء يائس / أمل شبه مستحيل", "exampleArabic": "كان البحث في الحطام بعد ثلاثة أسابيع رجاءً يائساً وأملاً شبه مستحيل لفرقة الإنقاذ.", "collocations": ["clasp a forlorn hope", "engage in a forlorn hope"], "synonyms": ["desperate chance"], "antonyms": ["certain prospect"], "tags": ["despair", "hope"]},
    {"headword": "yearn for", "pronunciation": "/jɜːn fɔː/", "partOfSpeech": "verb", "definition": "To feel an intense longing, craving, or deep affection for something absent.", "example": "Prisoners yearning for freedom looked out at the birds beyond the watchtower wire.", "translation": "يتوق إلى / يهفو قلبه لـ", "exampleArabic": "نظر السجناء التائقون إلى الحرية للطيور المحلقة خلف أسلاك برج المراقبة.", "verbForms": {"v1": "yearn for", "v2": "yearned for", "v3": "yearned for"}, "collocations": ["yearn for peace", "yearn for justice"], "synonyms": ["long for", "ache for"], "antonyms": ["despise"], "tags": ["longing", "actions"]},
    {"headword": "sigh with regret", "pronunciation": "/saɪ wɪð rɪˈɡret/", "partOfSpeech": "verb", "definition": "To emit a deep, audible breath expressing sadness, sorrow, or past failure.", "example": "The retired captain sighed with regret as he locked the vessel logbook forever.", "translation": "يتنهد بحسرة وأسف", "exampleArabic": "تنهد القبطان المتقاعد بحسرة وأسف وهو يغلق سجل السفينة إلى الأبد.", "verbForms": {"v1": "sigh with regret", "v2": "sighed with regret", "v3": "sighed with regret"}, "collocations": ["heavily sigh with regret", "pause and sigh with regret"], "synonyms": ["heave a sorrowful sigh"], "antonyms": [], "tags": ["emotions", "actions"]}
]

grammar_63 = [
    {
        "title": "Wish + Past; Wish + would / could",
        "titleArabic": "التعبير عن التمني والندم (Wish + Past; Wish + would / could)",
        "explanation": "We use 'wish' (and 'If only') to express that we want situations to be different from reality: 1) 'Wish + Past Simple' expresses a wish about a present situation that we want to be different ('I wish I knew more about finance'; 'If only we were richer'). 2) 'Wish + Past Perfect' expresses regret about a past action or event ('I wish I had accepted that overseas transfer'; 'If only we had not signed the contract'). 3) 'Wish + would + base verb' expresses annoyance or a desire for someone or something to change their behavior ('I wish it would stop raining'; 'I wish you would listen'). Note: We do NOT use 'I wish I would' for ourselves; instead, we use 'I wish I could'. 4) 'Wish + could + base verb' expresses regret about personal lack of ability in the present or future ('I wish I could turn back the clock').",
        "explanationArabic": "نستخدم الفعل 'wish' (وكذلك العبارة 'If only') للتعبير عن رغبتنا في أن تكون الأمور مختلفة عما هي عليه في الواقع: 1) Wish + Past Simple: للتعبير عن تمني تغيير واقع حاضر غير مرغوب ('أتمنى لو كنت أعرف المزيد عن التمويل'; 'يا ليتنا كنا أغنى'). 2) Wish + Past Perfect (had + V3): للتعبير عن الندم على حدث وقع في الماضي ('أتمنى لو كنت قد قبلت العرض'; 'يا ليتنا لم نوقع العقد'). 3) Wish + would + المصدر: للتعبير عن التبرم والانزعاج ورغبة في أن يُغير شخص آخر سلوكه ('أتمنى لو تتوقف عن المقاطعة'). تنبيه: لا تقل 'I wish I would' لنفسك؛ بل قل 'I wish I could'. 4) Wish + could + المصدر: للتعبير عن العجز عن فعل شيء في الحاضر أو المستقبل ('أتمنى لو أستطيع إعادة عقارب الساعة للوراء').",
        "structures": [
            {"label": "Present Wish · تمني تغيير الحاضر", "pattern": "Subject + wish(es) + Subject + Past Simple (or were)", "explanation": "Expresses that we want our present reality to be different.", "explanationArabic": "يعبر عن الرغبة في تغيير أمر قائم في الحاضر."},
            {"label": "Past Regret · الندم على ماضٍ فات", "pattern": "Subject + wish(es) + Subject + had + Past Participle (V3)", "explanation": "Expresses sadness or remorse about something done or omitted in the past.", "explanationArabic": "يعبر عن الحزن أو الأسف على تصرف تم أو فات في الماضي."},
            {"label": "Desire for Change / Annoyance · التذمر من سلوك (Would)", "pattern": "Subject + wish(es) + Subject + would + Base Verb", "explanation": "Used when annoyed by someone's persistent habit, asking for change.", "explanationArabic": "يُستخدم لإظهار الانزعاج من عادة شخص والمطالبة بتغييرها."},
            {"label": "Ability / Opportunity Wish · تمني القدرة (Could)", "pattern": "Subject + wish(es) + Subject + could + Base Verb", "explanation": "Expresses regret about lacking the ability or permission to do something.", "explanationArabic": "يعبر عن التمني لو كانت هناك قدرة أو ترخيص لفعل شيء."}
        ],
        "examples": [
            {"sentence": "I wish I could turn back the clock and redress that critical mistake.", "translation": "أتمنى لو أستطيع إعادة عقارب الساعة للوراء وتصحيح ذلك الخطأ الحاسم.", "usesVocabulary": ["turn back clock", "redress a mistake"]},
            {"sentence": "If only we had recognized that golden opportunity missed, we would not endure bitter regret.", "translation": "يا ليتنا أدركنا تلك الفرصة الذهبية المهدرة، لما عانينا من ندم مرير.", "usesVocabulary": ["golden opportunity missed", "bitter regret"]},
            {"sentence": "She wishes her supervisor would stop dwelling on spilt milk and look for the silver lining.", "translation": "تتمنى لو يتوقف مشرفها عن البكاء على اللبن المسكوب ويبحث عن الجانب المشرق.", "usesVocabulary": ["spilt milk", "silver lining"]},
            {"sentence": "In hindsight, they wish they had not indulged in mere wishful thinking about the merger.", "translation": "عند النظر للوراء بأثر رجعي، يتمنون لو لم ينغمسوا في مجرد تفكير بالتمني بشأن الاندماج.", "usesVocabulary": ["in hindsight", "wishful thinking"]}
        ],
        "commonMistakes": [
            {"wrong": "I wish I would have more free time to travel.", "right": "I wish I had more free time to travel. (OR: I wish I could travel more)", "note": "Do not use 'wish + would' for yourself; use Past Simple for present states, or 'could' for ability.", "noteArabic": "لا تستخدم would مع الضمير I بعد wish؛ بل استخدم الماضي البسيط أو could."},
            {"wrong": "I wish I didn't go to that party last night; I caught a cold.", "right": "I wish I hadn't gone to that party last night; I caught a cold.", "note": "Use 'hadn't + past participle' to express regret about past events, not didn't.", "noteArabic": "استخدم hadn't + التصريف الثالث للندم على ما حدث في الماضي وليس didn't."}
        ],
        "commonUsage": [
            "Reflecting on missed chances: 'I wish I had accepted that scholarship.' (تُستخدم للتحسر والتأمل في الفرص الماضية.)",
            "Expressing work frustration: 'I wish clients would respond to invoices on time.' (تُستخدم لإبداء الضيق من سلوكيات العمل.)",
            "Longing for distant realities: 'She wishes she could pine less for home and thrive abroad.' (تُستخدم للتعبير عن الحنين والشوق.)"
        ]
    }
]

convs_63 = [
    {
        "title": "Reflecting on a Lost Venture",
        "titleArabic": "التأمل في مشروع تجاري ضائع",
        "setting": "Two retired business partners drink coffee on a veranda, reminiscing about their early tech enterprise.",
        "lines": [
            {"speaker": "Marcus", "text": "Do you ever find yourself looking back with regret on that patent we sold in our twenties, Elena?"},
            {"speaker": "Elena", "text": "With hindsight, I realize it was a golden opportunity missed, but it is spilt milk now."},
            {"speaker": "Marcus", "text": "I wish we had retained fifty percent equity! If only we had not been so easily intimidated."},
            {"speaker": "Elena", "text": "Marcus, we cannot turn back the clock. Brooding over what might have been will only bring bitter regret."},
            {"speaker": "Marcus", "text": "I know. When I see their global valuation today, I still sigh with regret."},
            {"speaker": "Elena", "text": "Remember the silver lining: that seed payout allowed you to buy your vineyard debt-free."},
            {"speaker": "Marcus", "text": "That is true. Aching desire for past riches is mere wishful thinking anyway."},
            {"speaker": "Elena", "text": "Exactly. Let us toast to the lessons we learned and the rich memories we made!"}
        ],
        "vocabularyUsed": ["look back with regret", "with hindsight", "golden opportunity missed", "spilt milk", "if only", "turn back clock", "what might have been", "bitter regret", "sigh with regret", "silver lining", "aching desire", "wishful thinking"]
    },
    {
        "title": "Atoning for an Old Misunderstanding",
        "titleArabic": "التكفير عن سوء تفاهم قديم بين صديقين",
        "setting": "An older professional meets an estranged former colleague at a quiet library garden.",
        "lines": [
            {"speaker": "Julian", "text": "I invited you here because I felt sharp pangs of conscience about our boardroom dispute years ago."},
            {"speaker": "Arthur", "text": "That fallout was painful; I felt deep remorse over the harsh words I traded back then."},
            {"speaker": "Julian", "text": "I had second thoughts immediately, and I have felt truly remorseful ever since."},
            {"speaker": "Arthur", "text": "I carried a heavy heart too, and no professional consolation prize could replace our lost partnership."},
            {"speaker": "Julian", "text": "I wish I could make amends for taking that unfair credit on our joint publication."},
            {"speaker": "Arthur", "text": "I do not lament our shared history anymore; knowing that you wish to redress a mistake brings genuine peace of mind."},
            {"speaker": "Julian", "text": "I was haunted by the past and feared you would reject my invitation."},
            {"speaker": "Arthur", "text": "Better late than never, Julian; let us move forward as trusted friends."}
        ],
        "vocabularyUsed": ["pangs of conscience", "deep remorse", "second thoughts", "remorseful", "heavy heart", "consolation prize", "make amends", "lament", "redress a mistake", "haunted by past"]
    },
    {
        "title": "Chasing Illusions vs Facing Reality",
        "titleArabic": "مطاردة الأوهام ومواجهة الواقع",
        "setting": "A senior mentor counsels a frustrated apprentice who dreams of overnight musical fame.",
        "lines": [
            {"speaker": "Apprentice", "text": "I wish recording studios would answer my demo tapes; waiting is pure agony!"},
            {"speaker": "Mentor", "text": "Relying on sudden viral discovery is building castles in the air, my friend."},
            {"speaker": "Apprentice", "text": "Is pursuing international stardom really just a pipe dream?"},
            {"speaker": "Mentor", "text": "It becomes a pie in the sky when you ignore daily deliberate craft practice."},
            {"speaker": "Apprentice", "text": "I feel such an unfulfilled desire whenever I see packed amphitheaters."},
            {"speaker": "Mentor", "text": "Do not let unmet expectations poison your creative spirit or invite a harsh awakening."},
            {"speaker": "Apprentice", "text": "I understand. I should stop daydreaming and dedicate six hours daily to piano scales."},
            {"speaker": "Mentor", "text": "Grounded work will transform those wistful daydreams into durable reality."}
        ],
        "vocabularyUsed": ["castle in the air", "pipe dream", "pie in the sky", "unfulfilled desire", "unmet expectation", "harsh awakening", "daydream", "wistful"]
    }
]

paras_63 = [
    {
        "title": "The Emotional Weight of Unresolved Regrets",
        "titleArabic": "العبء العاطفي للندم والذكريات العالقة",
        "text": "Human memory is often shadowed by nostalgic longing and painful memories of what might have been. When individuals look back with regret upon a lost chance or golden opportunity missed, bitter regret can fester into crippling self-reproach. Many people rue the day they allowed fear to dictate their choices, living burdened with a heavy heart and haunted by the past. Yet philosophers wisely remind us that mourning over spilt milk will never turn back the clock. The true antidote to lingering sorrow is not to bemoan past errors, but to sincerely make amends and seek the silver lining in every trial.",
        "vocabularyUsed": ["nostalgic longing", "what might have been", "look back with regret", "lost chance", "golden opportunity missed", "bitter regret", "self-reproach", "rue the day", "heavy heart", "haunted by past", "spilt milk", "turn back clock", "bemoan", "make amends", "silver lining"]
    },
    {
        "title": "From Wishful Daydreams to Grounded Reality",
        "titleArabic": "من أحلام اليقظة الوردية إلى الواقع الصلب",
        "text": "It is delightfully easy to build a castle in the air and daydream about instant triumphs, but unanchored fantasies often collapse into a pipe dream or pie in the sky. When young entrepreneurs fall prey to mere wishful thinking, encountering an inevitable market downturn feels like a brutal harsh awakening. Experiencing a bitter letdown or suffering from an unfulfilled desire is an unavoidable part of personal development. Rather than chasing an unreachable ideal or clinging to a forlorn hope, mature achievers channel their aching desire into rigorous discipline, refusing to wallow in scanted cold comfort.",
        "vocabularyUsed": ["castle in the air", "daydream", "pipe dream", "pie in the sky", "wishful thinking", "harsh awakening", "letdown", "unfulfilled desire", "unreachable ideal", "forlorn hope", "aching desire", "cold comfort"]
    },
    {
        "title": "Healing the Wounds of Conscience and Past Wrongs",
        "titleArabic": "شفاء جراح الضمير والتكفير عن زلات الماضي",
        "text": "When an ethical transgression damages a sacred relationship, genuine remorseful reflection is the only path toward restoration. Those who endure painful pangs of conscience understand that trying to bury a fault under defensive pride only deepens moral guilt. A sincere person will not allow an estranged friend to pine for recognition or mourn the loss of friendship alone. Instead of allowing sorrow to linger as an unrequited wish, taking prompt action to redress a mistake and vocalize deep remorse liberates both the offender and the wronged party, restoring enduring dignity to both souls.",
        "vocabularyUsed": ["remorseful", "pangs of conscience", "pine for", "mourn the loss", "unrequited wish", "redress a mistake", "deep remorse"]
    }
]

# Write Day 63
write_day(63, vocab_63, grammar_63, convs_63, paras_63)

# ==============================================================================
# DAY 64: Opinions and Arguments (Agreeing, disagreeing and reasons)
# Grammar: ["Contrast: although / despite / in spite of"]
# ==============================================================================
vocab_64 = [
    # Reasoning & Philosophical Standpoints (15)
    {"headword": "viewpoint", "pronunciation": "/ˈvjuːpɔɪnt/", "partOfSpeech": "noun", "definition": "A particular attitude, perspective, or way of considering a matter.", "example": "Although he defended a traditional viewpoint, he listened respectfully to progressive reforms.", "translation": "وجهة نظر / زاوية رؤية", "exampleArabic": "على الرغم من أنه دافع عن وجهة نظر تقليدية، إلا أنه استمع باحترام للإصلاحات التقدمية.", "collocations": ["from my viewpoint", "divergent viewpoints"], "synonyms": ["perspective", "standpoint"], "antonyms": [], "tags": ["opinion", "philosophy"]},
    {"headword": "stance", "pronunciation": "/stɑːns/", "partOfSpeech": "noun", "definition": "The attitude of a person or organization toward something; a public posture.", "example": "Despite intense public protests, the trade federation maintained an unyielding stance on tariffs.", "translation": "موقف معلن / وقفة مبدئية", "exampleArabic": "على الرغم من الاحتجاجات الشعبية العارمة، حافظ اتحاد التجارة على موقف صارم بشأن الرسوم.", "collocations": ["adopt a firm stance", "uncompromising stance"], "synonyms": ["posture", "position"], "antonyms": [], "tags": ["debate", "opinion"]},
    {"headword": "standpoint", "pronunciation": "/ˈstændpɔɪnt/", "partOfSpeech": "noun", "definition": "An attitude to or way of considering something from a specific vantage point.", "example": "From a purely biological standpoint, human sleep serves essential neural cleansing functions.", "translation": "منظور / وجهة نظر تخصصية", "exampleArabic": "من منظور بيولوجي بحت، يؤدي النوم البشري وظائف حيوية لتنقية الخلايا العصبية.", "collocations": ["from a legal standpoint", "philosophical standpoint"], "synonyms": ["vantage point"], "antonyms": [], "tags": ["analysis", "opinion"]},
    {"headword": "line of reasoning", "pronunciation": "/laɪn əv ˈriːznɪŋ/", "partOfSpeech": "noun", "definition": "A systematic, connected sequence of thoughts and arguments leading to a conclusion.", "example": "Although her line of reasoning seemed unorthodox, her mathematical proofs stood up to review.", "translation": "مسار استدلالي / تسلسل منطقي للأفكار", "exampleArabic": "مع أن مسارها الاستدلالي بدا غير تقليدي، إلا أن براهينها الرياضية صمدت أمام المراجعة.", "collocations": ["flawed line of reasoning", "follow this line of reasoning"], "synonyms": ["logical chain", "rationale"], "antonyms": [], "tags": ["logic", "debate"]},
    {"headword": "premise", "pronunciation": "/ˈpremɪs/", "partOfSpeech": "noun", "definition": "A previous statement or proposition from which another is inferred or follows as a conclusion.", "example": "Despite the flawed premise of the economic study, its practical tax recommendations were sound.", "translation": "مقدمة منطقية / فرضية أساسية", "exampleArabic": "على الرغم من الفرضية والمقدمة المنطقية المعيبة للدراسة الاقتصادية، كانت توصياتها الضريبية سليمة.", "collocations": ["underlying premise", "based on the premise"], "synonyms": ["presupposition", "assumption"], "antonyms": ["conclusion"], "tags": ["logic", "arguments"]},
    {"headword": "counterargument", "pronunciation": "/ˈkaʊntərɑːɡjumənt/", "partOfSpeech": "noun", "definition": "An argument or set of reasons put forward to oppose an idea or theory.", "example": "In spite of presenting a brilliant counterargument, the debater was disqualified for exceeding time.", "translation": "حجة مضادة / حجة داحضة", "exampleArabic": "على الرغم من تقديمه حجة مضادة بارعة، استُبعد المتناظر لتجاوزه الوقت المحدد.", "collocations": ["formulate a counterargument", "anticipate counterarguments"], "synonyms": ["rebuttal argument"], "antonyms": ["supporting claim"], "tags": ["debate", "rhetoric"]},
    {"headword": "rebuttal", "pronunciation": "/rɪˈbʌtl/", "partOfSpeech": "noun", "definition": "A refutation or contradiction offered against an opposing argument.", "example": "Although the defense delivered a fiery rebuttal, the jury voted to convict the suspect.", "translation": "رد مفحم / تفنيد ودحض", "exampleArabic": "على الرغم من أن الدفاع قدم تفنيداً ورداً نارياً، إلا أن هيئة المحلفين أدانت المشتبه به.", "collocations": ["deliver a rebuttal", "convincing rebuttal"], "synonyms": ["refutation", "counter-statement"], "antonyms": ["concurrence"], "tags": ["legal", "debate"]},
    {"headword": "refutation", "pronunciation": "/ˌrefjuˈteɪʃn/", "partOfSpeech": "noun", "definition": "The action of proving a statement or theory to be completely wrong or false.", "example": "The scientist published a decisive refutation of the counterfeit energy hypothesis.", "translation": "دحض وتفنيد قاطع بالدليل", "exampleArabic": "نشر العالم دحضاً قاطعاً ومفحماً لفرضية الطاقة المزيفة.", "collocations": ["conclusive refutation", "demand a refutation"], "synonyms": ["disproof", "invalidation"], "antonyms": ["validation", "proof"], "tags": ["logic", "science"]},
    {"headword": "fallacy", "pronunciation": "/ˈfæləsi/", "partOfSpeech": "noun", "definition": "A mistaken belief or a failure in reasoning that renders an argument invalid.", "example": "Despite spotting the obvious logical fallacy, the moderator allowed the senator to conclude.", "translation": "مغالطة منطقية", "exampleArabic": "على الرغم من رصد المغالطة المنطقية الواضحة، سمح مدير الجلسة للسيناتور بالاختتام.", "collocations": ["logical fallacy", "common fallacy"], "synonyms": ["delusion", "misconception"], "antonyms": ["sound logic"], "tags": ["logic", "philosophy"]},
    {"headword": "reluctant admission", "pronunciation": "/rɪˈlʌktənt ədˈmɪʃn/", "partOfSpeech": "noun", "definition": "An unwilling acknowledgment of a truth, fault, or defeat.", "example": "In spite of his reluctant admission that tariffs raised consumer prices, he voted for the bill.", "translation": "اعتراف قسري على مضض", "exampleArabic": "على الرغم من اعترافه على مضض بأن الرسوم رفعت أسعار المستهلك، إلا أنه صوت للمشروع.", "collocations": ["make a reluctant admission", "wring a reluctant admission"], "synonyms": ["grudging concession"], "antonyms": ["proud claim"], "tags": ["debate", "admission"]},
    {"headword": "argumentative thesis", "pronunciation": "/ˌɑːɡjuˈmentətɪv ˈθiːsɪs/", "partOfSpeech": "noun", "definition": "The central claim or proposition that an essay, debate, or dissertation defends.", "example": "Although his argumentative thesis challenged mainstream dogma, historians applauded his research.", "translation": "أطروحة جدلية / الفكرة المحورية للحجة", "exampleArabic": "مع أن أطروحته الجدلية تحدت المفاهيم السائدة، إلا أن المؤرخين أشادوا بأبحاثه.", "collocations": ["defend an argumentative thesis", "clarify the argumentative thesis"], "synonyms": ["central proposition"], "antonyms": [], "tags": ["academic", "writing"]},
    {"headword": "assertion", "pronunciation": "/əˈsɜːʃn/", "partOfSpeech": "noun", "definition": "A confident and forceful statement of fact or belief.", "example": "Despite her bold assertion that the vaccine was safe, clinical trials were paused for tests.", "translation": "ادعاء جازم / توكيد قاطع", "exampleArabic": "على الرغم من توكيدها القاطع بأن اللقاح كان آمناً، تم إيقاف التجارب السريرية للفحص.", "collocations": ["bold assertion", "bare assertion"], "synonyms": ["affirmation", "declaration"], "antonyms": ["denial"], "tags": ["rhetoric", "opinion"]},
    {"headword": "bone of contention", "pronunciation": "/ˌbəʊn əv kənˈtenʃn/", "partOfSpeech": "noun", "definition": "A subject or issue over which there is continuing disagreement or dispute.", "example": "In spite of signing the peace protocol, boundary demarcation remained a bitter bone of contention.", "translation": "محل خلاف ونزاع دائم / تفاحة النزاع", "exampleArabic": "على الرغم من توقيع بروتوكول السلام، ظل ترسيم الحدود محل خلاف ونزاع مستمر.", "collocations": ["remain a bone of contention", "major bone of contention"], "synonyms": ["apple of discord", "point of dispute"], "antonyms": ["point of agreement"], "tags": ["conflict", "idioms"]},
    {"headword": "middle ground", "pronunciation": "/ˌmɪdl ˈɡraʊnd/", "partOfSpeech": "noun", "definition": "An intermediate position or area of compromise between contrasting extremes.", "example": "Although both political wings seemed polarized, skilled envoys sought reasonable middle ground.", "translation": "أرضية وسطى / منطقة حل وسط", "exampleArabic": "على الرغم من استقطاب الجناحين السياسيين، سعى مبعوثون مهرة إلى أرضية وسطى معقولة.", "collocations": ["find middle ground", "occupy the middle ground"], "synonyms": ["compromise", "median"], "antonyms": ["extreme fringe"], "tags": ["compromise", "politics"]},
    {"headword": "polarizing issue", "pronunciation": "/ˈpəʊləraɪzɪŋ ˈɪʃuː/", "partOfSpeech": "noun", "definition": "A topic that divides society or groups into sharply contrasting, hostile factions.", "example": "Despite being an intensely polarizing issue, public transit funding passed with bipartisan support.", "translation": "قضية استقطابية تقسم الآراء بشدة", "exampleArabic": "على الرغم من كونه قضية استقطابية تقسم الآراء بشدة، فقد تم تمرير تمويل النقل العام.", "collocations": ["debate a polarizing issue", "avoid polarizing issues"], "synonyms": ["divisive topic"], "antonyms": ["unifying cause"], "tags": ["politics", "society"]},

    # Fallacies & Rhetorical Devices (15)
    {"headword": "polarization", "pronunciation": "/ˌpəʊləraɪˈzeɪʃn/", "partOfSpeech": "noun", "definition": "Division into two sharply contrasting groups or sets of opinions or beliefs.", "example": "In spite of deepening political polarization, local charitable communities cooperated seamlessly.", "translation": "استقطاب حاد / انقسام فكري", "exampleArabic": "على الرغم من تعمق الاستقطاب السياسي، تعاونت الجمعيات الخيرية المحلية بسلاسة.", "collocations": ["growing polarization", "combat societal polarization"], "synonyms": ["division", "bifurcation"], "antonyms": ["social cohesion"], "tags": ["politics", "sociology"]},
    {"headword": "play devils advocate", "pronunciation": "/pleɪ ˈdevlz ˈædvəkət/", "partOfSpeech": "verb", "definition": "To express an opposing opinion solely to test the strength of an argument.", "example": "Although she favored the proposal, she played devil's advocate to stress-test financial projections.", "translation": "يتقمص دور محامي الشيطان لاختبار متانة الحجة", "exampleArabic": "مع أنها أيدت المقترح، إلا أنها تقمصت دور محامي الشيطان لاختبار متانة التوقعات المالية.", "verbForms": {"v1": "play devils advocate", "v2": "played devils advocate", "v3": "played devils advocate"}, "collocations": ["willing to play devil's advocate", "merely playing devil's advocate"], "synonyms": ["challenge for debate"], "antonyms": [], "tags": ["debate", "idioms"]},
    {"headword": "food for thought", "pronunciation": "/ˌfuːd fə ˈθɔːt/", "partOfSpeech": "noun", "definition": "Something that warrants serious, deep, and prolonged contemplation.", "example": "Despite the harshness of the critique, the guest speaker provided rich food for thought.", "translation": "مادة غنية للتأمل والتفكير العميق", "exampleArabic": "على الرغم من قسوة النقد، قدم المتحدث الضيف مادة غنية للتأمل والتفكير العميق.", "collocations": ["provide food for thought", "give food for thought"], "synonyms": ["intellectual stimulus"], "antonyms": ["shallow clichÃ©"], "tags": ["thinking", "idioms"]},
    {"headword": "point of contention", "pronunciation": "/ˌpɔɪnt əv kənˈtenʃn/", "partOfSpeech": "noun", "definition": "A specific assertion, matter, or clause over which parties argue heatedly.", "example": "In spite of mutual respect, the intellectual property royalty remained a point of contention.", "translation": "نقطة خلاف وتنازع", "exampleArabic": "على الرغم من الاحترام المتبادل، ظلت عائدات الملكية الفكرية نقطة خلاف وتنازع.", "collocations": ["settle a point of contention", "crucial point of contention"], "synonyms": ["disputed issue"], "antonyms": ["settled term"], "tags": ["negotiation", "dispute"]},
    {"headword": "valid counterpoint", "pronunciation": "/ˈvælɪd ˈkaʊntəpɔɪnt/", "partOfSpeech": "noun", "definition": "A legitimate, reasonable, and relevant argument raised against a statement.", "example": "Although the professor dismissed student complaints, the teaching assistant raised a valid counterpoint.", "translation": "رأي مقابل وجيه / حجة معاكسة صائبة", "exampleArabic": "مع أن الأستاذ استخف بشكاوى الطلاب، إلا أن المعيد المعاون طرح رأياً مقابلاً وجيهاً.", "collocations": ["raise a valid counterpoint", "offer a valid counterpoint"], "synonyms": ["legitimate objection"], "antonyms": ["irrelevant diversion"], "tags": ["debate", "logic"]},
    {"headword": "unfounded assertion", "pronunciation": "/ʌnˈfaʊndɪd əˈsɜːʃn/", "partOfSpeech": "noun", "definition": "A confident claim made without evidence, foundation, or factual corroboration.", "example": "Despite the speaker's eloquent delivery, journalists debunked his speech as an unfounded assertion.", "translation": "ادعاء لا أساس له من الصحة / زعم باطل", "exampleArabic": "على الرغم من إلقاء المتحدث البليغ، فند الصحفيون خطابه كادعاء لا أساس له من الصحة.", "collocations": ["dismiss as an unfounded assertion", "repeat unfounded assertions"], "synonyms": ["baseless claim"], "antonyms": ["verified fact"], "tags": ["fallacies", "journalism"]},
    {"headword": "persuasive argument", "pronunciation": "/pəˈsweɪsɪv ˈɑːɡjumənt/", "partOfSpeech": "noun", "definition": "A set of reasons that successfully convinces others to believe or do something.", "example": "In spite of corporate resistance, environmentalists presented a persuasive argument for solar subsidies.", "translation": "حجة مقنعة ومؤثرة", "exampleArabic": "على الرغم من مقاومة الشركات، قدم المدافعون عن البيئة حجة مقنعة لدعم الطاقة الشمسية.", "collocations": ["make a persuasive argument", "highly persuasive argument"], "synonyms": ["compelling case"], "antonyms": ["unconvincing plea"], "tags": ["persuasion", "rhetoric"]},
    {"headword": "specious reasoning", "pronunciation": "/ˈspiːʃəs ˈriːznɪŋ/", "partOfSpeech": "noun", "definition": "Arguments that appear superficially plausible, plausible, or correct, but are actually fallacious.", "example": "Although the defense attorney used specious reasoning, the seasoned judge saw through the trick.", "translation": "استدلال مخادع ظاهره الصواب وباطنه الخطأ", "exampleArabic": "مع أن محامي الدفاع استخدم استدلالاً مخادعاً، إلا أن القاضي المتمرس أدرك الخدعة.", "collocations": ["expose specious reasoning", "rely on specious reasoning"], "synonyms": ["sophistry", "deceptive logic"], "antonyms": ["cogent analysis"], "tags": ["fallacies", "logic"]},
    {"headword": "straw man argument", "pronunciation": "/ˌstrɔː ˈmæn ˈɑːɡjumənt/", "partOfSpeech": "noun", "definition": "An intentionally misrepresented proposition that is set up because it is easier to defeat.", "example": "Despite being warned against unfair debate tricks, the politician attacked a straw man argument.", "translation": "حجة رجل القش / تحريف كلام الخصم لإسقاطه", "exampleArabic": "على الرغم من تحذيره من حيل المناظرة غير النزيهة، هاجم السياسي حجة رجل القش المحرفة.", "collocations": ["resort to a straw man argument", "classic straw man argument"], "synonyms": ["caricature argument"], "antonyms": ["steel man argument"], "tags": ["fallacies", "debate"]},
    {"headword": "circular logic", "pronunciation": "/ˌsɜːkjələ ˈlɒdʒɪk/", "partOfSpeech": "noun", "definition": "A logical fallacy in which the reasoner begins with what they are trying to end with.", "example": "Although the manuscript was printed by an academic press, reviewers exposed its circular logic.", "translation": "منطق دائري / مصادرة على المطلوب", "exampleArabic": "مع أن المخطوطة طُبعت لدى دار نشر أكاديمية، كشف المراجعون منطقها الدائري السقيم.", "collocations": ["trap of circular logic", "guilty of circular logic"], "synonyms": ["begging the question"], "antonyms": ["linear proof"], "tags": ["fallacies", "logic"]},
    {"headword": "hasty generalization", "pronunciation": "/ˌheɪsti ˌdʒenrəlaɪˈzeɪʃn/", "partOfSpeech": "noun", "definition": "Drawing a broad, sweeping conclusion based on insufficient or unrepresentative evidence.", "example": "In spite of interviewing only three tourists, the reporter made a hasty generalization about visitors.", "translation": "تعميم متسرع ومبتسر", "exampleArabic": "على الرغم من مقابلة ثلاثة سياح فقط، أطلق المراسل تعميماً متسرعاً عن جميع الزوار.", "collocations": ["commit a hasty generalization", "avoid hasty generalizations"], "synonyms": ["premature deduction"], "antonyms": ["representative sampling"], "tags": ["fallacies", "logic"]},
    {"headword": "slippery slope", "pronunciation": "/ˌslɪpəri ˈsləʊp/", "partOfSpeech": "noun", "definition": "An argument claiming that a relatively small initial step will inevitably lead to disastrous extremes.", "example": "Although opponents invoked the slippery slope fallacy, municipal bike lanes caused zero chaos.", "translation": "مغالطة المنحدر الزلق", "exampleArabic": "على الرغم من أن المعارضين استدعوا مغالطة المنحدر الزلق، لم تسبب مسارات الدراجات أي فوضى.", "collocations": ["warn of a slippery slope", "classic slippery slope"], "synonyms": ["domino fallacy"], "antonyms": [], "tags": ["fallacies", "rhetoric"]},
    {"headword": "red herring", "pronunciation": "/ˌred ˈherɪŋ/", "partOfSpeech": "noun", "definition": "A clue or topic that is or is intended to be misleading or distracting from the central issue.", "example": "Despite the prosecutor introducing a red herring about offshore accounts, the jury focused on the theft.", "translation": "مغالطة الرنجة الحمراء / حيلة تشتيت الانتباه", "exampleArabic": "على الرغم من أن المدعي العام ألقى بحيلة الرنجة الحمراء لتشتيت الانتباه، ركزت الهيئة على السرقة.", "collocations": ["merely a red herring", "introduce a red herring"], "synonyms": ["diversion", "smokescreen"], "antonyms": ["core matter"], "tags": ["fallacies", "rhetoric"]},
    {"headword": "ad hominem", "pronunciation": "/ˌæd ˈhɒmɪnem/", "partOfSpeech": "adjective", "definition": "Directed against a person rather than the position or argument they are maintaining.", "example": "In spite of repeated warnings by the chair, the debater launched an ad hominem attack on his rival.", "translation": "شخصنة الحوار / هجوم موجه ضد شخص القائل لا حجته", "exampleArabic": "على الرغم من التحذيرات المتكررة للرئيس، شن المتناظر هجوماً شخصياً على منافسه.", "collocations": ["ad hominem attack", "resort to ad hominem"], "synonyms": ["personal smear"], "antonyms": ["objective critique"], "tags": ["fallacies", "debate"]},
    {"headword": "take a stand", "pronunciation": "/teɪk ə stænd/", "partOfSpeech": "verb", "definition": "To adopt a firm, unambiguous position on an issue and defend it publicly.", "example": "Although it threatened his popularity, the councilor took a stand against corporate tax exemptions.", "translation": "يتخذ موقفاً حازماً ومعلناً", "exampleArabic": "على الرغم من أنه هدد شعبيته، اتخذ المستشار موقفاً حازماً ضد الإعفاءات الضريبية للشركات.", "verbForms": {"v1": "take a stand", "v2": "took a stand", "v3": "taken a stand"}, "collocations": ["take a firm stand", "time to take a stand"], "synonyms": ["stand up for"], "antonyms": ["remain neutral"], "tags": ["courage", "actions"]},

    # Nuance, Rebuttal & Consensus Building (20)
    {"headword": "weigh both sides", "pronunciation": "/weɪ bəʊθ saɪdz/", "partOfSpeech": "verb", "definition": "To carefully and impartially consider contrasting arguments before forming a conclusion.", "example": "Despite public media frenzy, the appellate judges weighed both sides with exemplary neutrality.", "translation": "يزن كلا الجانبين بحيادية وإنصاف", "exampleArabic": "على الرغم من الهياج الإعلامي العام، وزن قضاة الاستئناف كلا الجانبين بحيادية نموذجية.", "verbForms": {"v1": "weigh both sides", "v2": "weighed both sides", "v3": "weighed both sides"}, "collocations": ["fail to weigh both sides", "obligation to weigh both sides"], "synonyms": ["consider both perspectives"], "antonyms": ["show bias"], "tags": ["fairness", "actions"]},
    {"headword": "see both sides", "pronunciation": "/siː bəʊθ saɪdz/", "partOfSpeech": "verb", "definition": "To comprehend and empathize with the opposing arguments in a dispute.", "example": "Although he held strong personal views, the seasoned mediator could always see both sides.", "translation": "يتفهم وجهتي النظر", "exampleArabic": "مع أنه حمل آراء شخصية قوية، كان الوسيط المتمرس قادراً دوماً على تفهم وجهتي النظر.", "verbForms": {"v1": "see both sides", "v2": "saw both sides", "v3": "seen both sides"}, "collocations": ["ability to see both sides", "refuse to see both sides"], "synonyms": ["appreciate opposing perspectives"], "antonyms": ["exhibit tunnel vision"], "tags": ["empathy", "actions"]},
    {"headword": "beg to differ", "pronunciation": "/beɡ tə ˈdɪfə/", "partOfSpeech": "verb", "definition": "A polite, diplomatic formula used to express respectful disagreement.", "example": "In spite of the director's status, the senior engineer begged to differ regarding structural safety.", "translation": "يسمح لنفسه بالاعتراض بكل احترام", "exampleArabic": "على الرغم من مكانة المدير، سمح كبير المهندسين لنفسه بالاعتراض بكل احترام على السلامة الإنشائية.", "verbForms": {"v1": "beg to differ", "v2": "begged to differ", "v3": "begged to differ"}, "collocations": ["must beg to differ", "respectfully beg to differ"], "synonyms": ["politely disagree"], "antonyms": ["wholeheartedly concur"], "tags": ["politeness", "idioms"]},
    {"headword": "meet halfway", "pronunciation": "/miːt ˌhɑːfˈweɪ/", "partOfSpeech": "verb", "definition": "To compromise with someone by making reciprocal concessions.", "example": "Although negotiations stalled initially, both union reps and executives agreed to meet halfway.", "translation": "يلتقي في منتصف الطريق / يقدم تنازلات متبادلة", "exampleArabic": "على الرغم من تعثر المفاوضات في البداية، وافق كل من ممثلي النقابة والمديرين على اللقاء في منتصف الطريق.", "verbForms": {"v1": "meet halfway", "v2": "met halfway", "v3": "met halfway"}, "collocations": ["willing to meet halfway", "refusal to meet halfway"], "synonyms": ["reach compromise"], "antonyms": ["demand total surrender"], "tags": ["negotiation", "actions"]},
    {"headword": "agree on principle", "pronunciation": "/əˈɡriː ɒn ˈprɪnsəpl/", "partOfSpeech": "verb", "definition": "To reach broad philosophical consensus while leaving specific details for later.", "example": "In spite of tactical disagreements on funding, all nations agreed on principle to limit deforestation.", "translation": "يتفق من حيث المبدأ", "exampleArabic": "على الرغم من الخلافات التكتيكية على التمويل، اتفقت جميع الدول من حيث المبدأ على وقف إزالة الغابات.", "verbForms": {"v1": "agree on principle", "v2": "agreed on principle", "v3": "agreed on principle"}, "collocations": ["readily agree on principle", "agree on principle only"], "synonyms": ["concur in theory"], "antonyms": ["reject fundamentally"], "tags": ["consensus", "actions"]},
    {"headword": "strongly dispute", "pronunciation": "/ˈstrɒŋli dɪˈspjuːt/", "partOfSpeech": "verb", "definition": "To challenge, contest, or argue against an assertion or finding with intense vigor.", "example": "Although the agency released its report, independent analysts strongly disputed the job figures.", "translation": "يحتج بشدة / يطعن بقوة في صحة الشيء", "exampleArabic": "على الرغم من أن الوكالة أصدرت تقريرها، إلا أن المحللين المستقلين طعنوا بقوة في أرقام الوظائف.", "verbForms": {"v1": "strongly dispute", "v2": "strongly disputed", "v3": "strongly disputed"}, "collocations": ["strongly dispute claim", "right to strongly dispute"], "synonyms": ["fiercely contest"], "antonyms": ["accept uncritically"], "tags": ["challenge", "actions"]},
    {"headword": "call into question", "pronunciation": "/kɔːl ˈɪntə ˈkwestʃən/", "partOfSpeech": "verb", "definition": "To cause people to doubt, challenge, or critically examine something.", "example": "Despite the executive's clean record, forensic accounting called into question his expense claims.", "translation": "يضع موضع تساؤل وشك / يثير الشبهات حول", "exampleArabic": "على الرغم من السجل النظيف للمسؤول، وضع التدقيق المحاسبي الجنائي مطالبات نفقاته موضع شك.", "verbForms": {"v1": "call into question", "v2": "called into question", "v3": "called into question"}, "collocations": ["call integrity into question", "call findings into question"], "synonyms": ["cast doubt upon"], "antonyms": ["verify definitively"], "tags": ["skepticism", "actions"]},
    {"headword": "cast doubt on", "pronunciation": "/kɑːst daʊt ɒn/", "partOfSpeech": "verb", "definition": "To cause something to be regarded as uncertain, suspect, or untrustworthy.", "example": "In spite of initial celebrations, fresh seismic readings cast doubt on the dam's stability.", "translation": "يلقي بظلال من الشك على", "exampleArabic": "على الرغم من الاحتفالات الأولية، ألقت القراءات الزلزالية الجديدة بظلال من الشك على استقرار السد.", "verbForms": {"v1": "cast doubt on", "v2": "cast doubt on", "v3": "cast doubt on"}, "collocations": ["cast serious doubt on", "tend to cast doubt on"], "synonyms": ["question validity"], "antonyms": ["reassure"], "tags": ["doubt", "actions"]},
    {"headword": "bring to light", "pronunciation": "/brɪŋ tə laɪt/", "partOfSpeech": "verb", "definition": "To make something hidden, forgotten, or secret widely known and visible.", "example": "Although archives were classified for fifty years, declassified files brought to light covert treaties.", "translation": "يسلط الضوء على / يُظهر للعلن ما كان خفياً", "exampleArabic": "على الرغم من تصنيف الأرشيف كسري لخمسين عاماً، أظهرت الملفات المفرج عنها معاهدات سرية للعلن.", "verbForms": {"v1": "bring to light", "v2": "brought to light", "v3": "brought to light"}, "collocations": ["bring new facts to light", "bring injustice to light"], "synonyms": ["reveal", "uncover"], "antonyms": ["conceal"], "tags": ["discovery", "actions"]},
    {"headword": "substantiate claim", "pronunciation": "/səbˈstænʃieɪt kleɪm/", "partOfSpeech": "verb", "definition": "To provide empirical evidence, documents, or data that support the truth of a claim.", "example": "Despite testifying under oath, the witness could not substantiate his claim with bank slips.", "translation": "يُثبت الادعاء بالأدلة / يدعم الزعم بالبراهين", "exampleArabic": "على الرغم من الإدلاء بشهادته تحت القسم، لم يستطع الشاهد إثبات ادعائه بإيصالات مصرفية.", "verbForms": {"v1": "substantiate claim", "v2": "substantiated claim", "v3": "substantiated claim"}, "collocations": ["fail to substantiate claim", "adequately substantiate claim"], "synonyms": ["corroborate", "verify"], "antonyms": ["disprove"], "tags": ["evidence", "actions"]},
    {"headword": "refute claim", "pronunciation": "/rɪˈfjuːt kleɪm/", "partOfSpeech": "verb", "definition": "To prove definitively that an accusation, charge, or theory is false and groundless.", "example": "In spite of relentless online rumors, the scientist refuted the claim with public lab replications.", "translation": "يدحض الادعاء ويفنده بالدليل القاطع", "exampleArabic": "على الرغم من الشائعات المتواصلة على الإنترنت، دحض العالم الادعاء بإعادة التجارب علناً في المختبر.", "verbForms": {"v1": "refute claim", "v2": "refuted claim", "v3": "refuted claim"}, "collocations": ["conclusively refute claim", "attempt to refute claim"], "synonyms": ["demolish assertion"], "antonyms": ["confirm"], "tags": ["debate", "actions"]},
    {"headword": "concede point", "pronunciation": "/kənˈsiːd pɔɪnt/", "partOfSpeech": "verb", "definition": "To admit or acknowledge that the opponent has made a valid or true point.", "example": "Although he won the overall debate, the senator conceded a fair point about fiscal deficits.", "translation": "يقر بصحة النقطة للخصم / يعترف بوجاهة الحجة", "exampleArabic": "على الرغم من فوزه بالمناظرة عموماً، أقر السيناتور بنقطة وجيهة للخصم حول العجز المالي.", "verbForms": {"v1": "concede point", "v2": "conceded point", "v3": "conceded point"}, "collocations": ["graciously concede point", "forced to concede point"], "synonyms": ["grant validity"], "antonyms": ["contest blindly"], "tags": ["sportsmanship", "debate"]},
    {"headword": "acknowledge merit", "pronunciation": "/əkˈnɒlɪdʒ ˈmerɪt/", "partOfSpeech": "verb", "definition": "To recognize, respect, and validate the quality, value, or virtue of another's position.", "example": "In spite of deep ideological differences, the rival scholars acknowledged the merit of each other's works.", "translation": "يعترف بجدارة واستحقاق الآخر", "exampleArabic": "على الرغم من الاختلافات الأيديولوجية العميقة، اعترف العالمان المتنافسان بجدارة أعمال بعضهما.", "verbForms": {"v1": "acknowledge merit", "v2": "acknowledged merit", "v3": "acknowledged merit"}, "collocations": ["readily acknowledge merit", "fail to acknowledge merit"], "synonyms": ["give credit where due"], "antonyms": ["belittle"], "tags": ["respect", "actions"]},
    {"headword": "differing perspective", "pronunciation": "/ˈdɪfərɪŋ pəˈspektɪv/", "partOfSpeech": "noun", "definition": "A contrasting or alternative viewpoint held by another individual or group.", "example": "Although they arrived with differing perspectives, the interfaith panel discovered universal shared ethics.", "translation": "منظور متباين / وجهة نظر مغايرة", "exampleArabic": "على الرغم من وصولهم بوجهات نظر متباينة، اكتشفت اللجنة المشتركة أخلاقيات إنسانية عالمية جامعة.", "collocations": ["bring differing perspectives", "harmonize differing perspectives"], "synonyms": ["divergent view"], "antonyms": ["uniform viewpoint"], "tags": ["pluralism", "diversity"]},
    {"headword": "nuanced opinion", "pronunciation": "/ˈnjuːɑːnst əˈpɪnjən/", "partOfSpeech": "noun", "definition": "A subtle, sophisticated, and balanced judgment that avoids simplistic binaries.", "example": "Despite political demands for soundbites, the editorial offered a beautifully nuanced opinion.", "translation": "رأي دقيق ومتوازن / وجهة نظر تتسم بالعمق والإنصاف", "exampleArabic": "على الرغم من المطالب السياسية بالشعارات الرنانة السطحية، قدم المقال الافتتاحي رأياً دقيقاً ومتوازناً.", "collocations": ["express a nuanced opinion", "need for nuanced opinions"], "synonyms": ["sophisticated judgment"], "antonyms": ["black-and-white view"], "tags": ["subtlety", "opinion"]},
    {"headword": "one-sided view", "pronunciation": "/ˌwʌn ˈsaɪdɪd vjuː/", "partOfSpeech": "noun", "definition": "An unfair, biased perspective that considers only one dimension of a controversy.", "example": "In spite of promoting itself as objective, the documentary presented a glaringly one-sided view.", "translation": "نظرة أحادية الجانب / وجهة نظر متحيزة", "exampleArabic": "على الرغم من ترويج نفسه كفيلم موضوعي، قدم الوثائقي نظرة أحادية الجانب متحيزة بشكل صارخ.", "collocations": ["reject a one-sided view", "guilty of a one-sided view"], "synonyms": ["partisan bias"], "antonyms": ["balanced appraisal"], "tags": ["bias", "critique"]},
    {"headword": "unbiased standpoint", "pronunciation": "/ʌnˈbaɪəst ˈstændpɔɪnt/", "partOfSpeech": "noun", "definition": "An impartial, neutral attitude free from prejudice or personal favoritism.", "example": "Although funded by industry grants, the clinical observatory maintained an unbiased standpoint.", "translation": "موقف محايد غير متحيز / منظور منصف", "exampleArabic": "على الرغم من تمويله بمنح صناعية، حافظ المرصد السريري على موقف محايد غير متحيز.", "collocations": ["maintain an unbiased standpoint", "judge from an unbiased standpoint"], "synonyms": ["impartial perspective"], "antonyms": ["prejudiced posture"], "tags": ["objectivity", "ethics"]},
    {"headword": "clashing viewpoints", "pronunciation": "/ˈklæʃɪŋ ˈvjuːpɔɪnts/", "partOfSpeech": "noun", "definition": "Opposing beliefs or convictions that conflict sharply and irreconcilably with one another.", "example": "Despite clashing viewpoints on urban development, council members drafted an accord.", "translation": "وجهات نظر متصادمة ومتناحرة", "exampleArabic": "على الرغم من وجهات النظر المتصادمة بشأن التنمية الحضرية، صاغ أعضاء المجلس اتفاقاً.", "collocations": ["reconcile clashing viewpoints", "spark clashing viewpoints"], "synonyms": ["conflicting stances"], "antonyms": ["harmonious views"], "tags": ["conflict", "debate"]},
    {"headword": "rebut point", "pronunciation": "/rɪˈbʌt pɔɪnt/", "partOfSpeech": "verb", "definition": "To contradict, challenge, and prove erroneous a specific claim made in debate.", "example": "In spite of intense pressure, the young debater systematically rebutted every point.", "translation": "يدحض النقطة / يرد على الحجة ويفندها", "exampleArabic": "على الرغم من الضغط الهائل، دحض المتناظر الشاب كل نقطة وأبطلها منهجياً.", "verbForms": {"v1": "rebut point", "v2": "rebutted point", "v3": "rebutted point"}, "collocations": ["effectively rebut point", "seek to rebut points"], "synonyms": ["counter point"], "antonyms": ["concur with point"], "tags": ["debate", "actions"]},
    {"headword": "common ground found", "pronunciation": "/ˈkɒmən ɡraʊnd faʊnd/", "partOfSpeech": "phrase", "definition": "The realization or achievement of mutual agreement and shared interests amid disagreement.", "example": "Although ideological differences persisted, common ground was found regarding ecological conservation.", "translation": "أرضية مشتركة تم التوصل إليها", "exampleArabic": "على الرغم من استمرار الخلافات الأيديولوجية، تم التوصل إلى أرضية مشتركة فيما يتعلق بالحفاظ البيئي.", "collocations": ["celebrate common ground found", "hope common ground found"], "synonyms": ["shared basis established"], "antonyms": ["irreconcilable division"], "tags": ["consensus", "idioms"]}
]

grammar_64 = [
    {
        "title": "Contrast: although / despite / in spite of",
        "titleArabic": "أدوات التناقض والتعارض (Contrast: Although / Even though / Despite / In spite of)",
        "explanation": "We use contrast linkers to connect two ideas when one makes the other surprising, unexpected, or contradictory: 1) 'Although', 'Even though', and 'Though' are followed by a full clause (Subject + Verb): 'Although he defended an unpopular viewpoint, his logic was sound'; 'Even though the thesis was complex, the jury praised it'. 2) 'Despite' and 'In spite of' are prepositions and must be followed by a noun phrase, a pronoun, or a gerund (Verb-ing): 'Despite intense public polarization, lawmakers passed the bill'; 'In spite of being exhausted, she presented a persuasive rebuttal'. 3) To follow 'despite / in spite of' with a full subject and verb clause, use the phrase 'the fact that': 'Despite the fact that he was inexperienced, he spoke with great authority.'",
        "explanationArabic": "نستخدم أدوات التناقض لربط فكرتين عندما تكون إحداهما مفاجئة أو متناقضة مع الأخرى: 1) Although و Even though (على الرغم من / مع أن): يتبعهما جملة كاملة تحتوي على فاعل وفعل (Subject + Verb). 2) Despite و In spite of (بالرغم من): حروف جر ويجب أن يتبعهما اسم (Noun Phrase)، أو ضمير (Pronoun)، أو فعل ينتهي بـ -ing (Gerund). 3) إذا أردت استخدام جملة كاملة بعد despite أو in spite of، فيجب إضافة العبارة 'the fact that' (مثل: 'Despite the fact that the evidence was scarce...').",
        "structures": [
            {"label": "Conjunction Clause · جملة الربط (Although / Even though)", "pattern": "Although / Even though + Subject + Verb, Main Clause", "explanation": "Connects two contrasting clauses where one outcome is surprising.", "explanationArabic": "يربط بين جملتين متعارضتين تتضمن إحداهما نتيجة مفاجئة."},
            {"label": "Prepositional Gerund / Noun · شبه جملة الاسم أو المصدر (Despite / In spite of)", "pattern": "Despite / In spite of + Noun Phrase / Gerund (-ing), Main Clause", "explanation": "Takes a noun or -ing verb to introduce the contrasting obstacle.", "explanationArabic": "يأخذ اسماً أو مصدراً مضافاً له ing لتقديم العائق المعاكس."},
            {"label": "Fact-that Construction · تركيبة حقيقة أن (Despite the fact that)", "pattern": "Despite the fact that + Subject + Verb, Main Clause", "explanation": "Allows a full clause to follow despite / in spite of formally.", "explanationArabic": "تسمح بإتباع despite بجملة فعلية كاملة بأسلوب رسمي رصين."}
        ],
        "examples": [
            {"sentence": "Although the politician delivered an emotional speech, it was based on an unfounded assertion.", "translation": "على الرغم من أن السياسي ألقى خطاباً عاطفياً، إلا أنه استند إلى ادعاء لا أساس له من الصحة.", "usesVocabulary": ["unfounded assertion"]},
            {"sentence": "Despite clashing viewpoints on municipal spending, the committee found reasonable middle ground.", "translation": "على الرغم من وجهات النظر المتصادمة حول الإنفاق البلدي، وجدت اللجنة أرضية وسطى معقولة.", "usesVocabulary": ["clashing viewpoints", "middle ground"]},
            {"sentence": "In spite of facing intense polarization, the mediator managed to bring both sides to an accord.", "translation": "على الرغم من مواجهة استقطاب حاد، تمكن الوسيط من تقريب الجانبين للاتفاق.", "usesVocabulary": ["polarization"]},
            {"sentence": "Although he spotted a logical fallacy in the premise, he offered a polite rebuttal.", "translation": "على الرغم من أنه رصد مغالطة منطقية في الفرضية، إلا أنه قدم تفنيداً مهذباً.", "usesVocabulary": ["fallacy", "premise", "rebuttal"]}
        ],
        "commonMistakes": [
            {"wrong": "Despite of the heavy rain, we attended the academic debate.", "right": "Despite the heavy rain, we attended the academic debate. (OR: In spite of the heavy rain)", "note": "Never use 'of' with 'despite'; 'of' is only used with 'in spite of'.", "noteArabic": "لا تضع 'of' إطلاقاً مع 'despite'؛ فـ of تأتي فقط مع 'in spite of'."},
            {"wrong": "Although of his great intellect, he used specious reasoning.", "right": "Although he possessed great intellect, he used specious reasoning. (OR: Despite his great intellect)", "note": "Never put 'of' or a bare noun phrase after 'although'; use a full clause (subject + verb).", "noteArabic": "لا تستخدم 'of' أو اسماً مجرداً بعد although؛ بل يلزم استخدام جملة كاملة بها فاعل وفعل."}
        ],
        "commonUsage": [
            "Formal debate argumentation: 'Although my opponent raised a valid counterpoint, empirical records contradict his premise.' (تُستخدم في المناظرات الفكرية والأكاديمية.)",
            "Editorial commentary: 'In spite of widespread skepticism, the new environmental legislation offers significant progress.' (تُستخدم في المقالات التحليلية والافتتاحيات الصحفية.)",
            "Negotiation and diplomacy: 'Despite lingering bones of contention, both delegations agreed on principle.' (تُستخدم في تقارير الدبلوماسية والتفاوض.)"
        ]
    }
]

convs_64 = [
    {
        "title": "Debating Urban Transportation Policy",
        "titleArabic": "مناظرة حول سياسة النقل الحضري",
        "setting": "An urban planner debates a transportation lobbyist at an open municipal forum.",
        "lines": [
            {"speaker": "Planner", "text": "Although our city budget is strained, expanding electric light rail presents a persuasive argument for sustainability."},
            {"speaker": "Lobbyist", "text": "I beg to differ! Despite your noble intentions, adopting an unyielding stance on light rail is exorbitant."},
            {"speaker": "Planner", "text": "Your claim that rail harms local retail is an unfounded assertion; international data refutes that claim entirely."},
            {"speaker": "Lobbyist", "text": "In spite of those foreign studies, suburban shopkeepers fear foot-traffic disruption during construction."},
            {"speaker": "Planner", "text": "That is a valid counterpoint, but we can phase development to mitigate commercial losses."},
            {"speaker": "Lobbyist", "text": "If you concede that point, let us seek reasonable middle ground on downtown bus lanes instead."},
            {"speaker": "Planner", "text": "Although we hold differing perspectives on rail, I appreciate your willingness to meet halfway."},
            {"speaker": "Lobbyist", "text": "Excellent! When debaters acknowledge merit in opposing views, common ground is easily found."}
        ],
        "vocabularyUsed": ["viewpoint", "persuasive argument", "beg to differ", "stance", "unfounded assertion", "refute claim", "valid counterpoint", "concede point", "middle ground", "differing perspective", "meet halfway", "acknowledge merit", "common ground found"]
    },
    {
        "title": "Uncovering Logical Fallacies in Seminar",
        "titleArabic": "كشف المغالطات المنطقية في حلقة نقاش أكاديمية",
        "setting": "A logic professor critiques an undergraduate debate team in a university seminar hall.",
        "lines": [
            {"speaker": "Professor", "text": "In spite of your energetic delivery today, when you tried to play devil's advocate, your rebuttal relied on specious reasoning."},
            {"speaker": "Student A", "text": "Which part of our argumentative thesis contained a logical fallacy, Professor?"},
            {"speaker": "Professor", "text": "When your opponent offered a thoughtful counterargument for solar energy, you attacked a straw man argument about banning all fuels."},
            {"speaker": "Student B", "text": "We also warned that allowing one small subsidy would trigger complete economic collapse."},
            {"speaker": "Professor", "text": "Precisely; that line of reasoning is a classic slippery slope, accompanied by a distracting red herring."},
            {"speaker": "Student A", "text": "Although it was tempting in the heat of debate, I make a reluctant admission that we avoided the core premise."},
            {"speaker": "Professor", "text": "Do not despair; learning to spot fallacies gives you invaluable food for thought for future tournaments."},
            {"speaker": "Student B", "text": "We will substantiate our claims with empirical data next time rather than rely on hasty generalizations."}
        ],
        "vocabularyUsed": ["play devils advocate", "rebuttal", "specious reasoning", "argumentative thesis", "fallacy", "counterargument", "straw man argument", "line of reasoning", "slippery slope", "red herring", "reluctant admission", "premise", "food for thought", "substantiate claim", "hasty generalization"]
    },
    {
        "title": "Diplomatic Reconciliation Talks",
        "titleArabic": "محادثات مصالحة دبلوماسية رفيعة المستوى",
        "setting": "Two senior diplomats review contentious border territory treaties with an impartial observer.",
        "lines": [
            {"speaker": "Diplomat A", "text": "Despite deep national polarization, our delegation took a stand to attend these peace talks."},
            {"speaker": "Diplomat B", "text": "Although water rights remain a painful bone of contention, we agreed on principle to freeze troop deployments."},
            {"speaker": "Observer", "text": "From an unbiased standpoint, both of you deserve praise for refusing to indulge in ad hominem attacks."},
            {"speaker": "Diplomat A", "text": "In spite of historical grievances that brought past treaties into question, we are ready to see both sides."},
            {"speaker": "Diplomat B", "text": "We must not let a one-sided view derail this historic opportunity to draft lasting bilateral accords."},
            {"speaker": "Observer", "text": "If both nations weigh both sides with mutual respect, this polarizing issue will finally be settled."},
            {"speaker": "Diplomat A", "text": "We will bring to light all border water telemetry data to ensure total transparency."},
            {"speaker": "Diplomat B", "text": "A nuanced opinion rooted in scientific hydrology will serve both our populations well."}
        ],
        "vocabularyUsed": ["polarization", "take a stand", "bone of contention", "agree on principle", "unbiased standpoint", "ad hominem", "call into question", "see both sides", "one-sided view", "weigh both sides", "polarizing issue", "bring to light", "nuanced opinion"]
    }
]

paras_64 = [
    {
        "title": "The Art of Principled Intellectual Debate",
        "titleArabic": "فن المناظرة الفكرية المبدئية والبناءة",
        "text": "In a democratic society, healthy discourse thrives when participants present a well-structured argumentative thesis supported by verified facts. Although impassioned speakers often hold clashing viewpoints, the hallmark of mature debate is the willingness to see both sides and acknowledge merit in opposing views. In spite of facing a polarizing issue that divides communities, ethical debaters refuse to distort the truth through a straw man argument or distract audiences with an irrelevant red herring. When scholars weigh both sides from an unbiased standpoint, they enrich collective understanding and build lasting consensus.",
        "vocabularyUsed": ["argumentative thesis", "clashing viewpoints", "see both sides", "acknowledge merit", "polarizing issue", "straw man argument", "red herring", "weigh both sides", "unbiased standpoint"]
    },
    {
        "title": "Guarding Against Logical Fallacies and Specious Rhetoric",
        "titleArabic": "الحذر من المغالطات المنطقية والبلاغة الزائفة",
        "text": "Every rigorous thinker must develop the intellectual discernment required to dismantle deceptive sophistry. Despite an orator's charismatic delivery, critical listeners must examine whether a central premise rests upon an unfounded assertion or circular logic. In spite of aggressive attempts to silence critics with a hostile ad hominem attack, truth seekers remain calm and deliver a methodical, evidence-based rebuttal. When analysts expose specious reasoning and reject a hasty generalization, they bring to light verified truths and stimulate genuine food for thought.",
        "vocabularyUsed": ["premise", "unfounded assertion", "circular logic", "ad hominem", "rebuttal", "specious reasoning", "hasty generalization", "bring to light", "food for thought"]
    },
    {
        "title": "Finding Common Ground Beyond Polarized Divides",
        "titleArabic": "إيجاد أرضية مشتركة خارج حدود الانقسام والاستقطاب",
        "text": "Deep political polarization often locks rival factions into rigid dogmatic postures where neither side is willing to budge. Although a controversial bone of contention may generate fiery rhetoric, responsible leaders recognize the danger of maintaining an obstinate, one-sided view. In spite of fierce partisan resistance, courageous statesmen take a stand, agree on principle to de-escalate tensions, and meet halfway. By offering a nuanced opinion that respects differing perspectives, civil society discovers that common ground can always be found when goodwill triumphs over hostility.",
        "vocabularyUsed": ["polarization", "bone of contention", "one-sided view", "take a stand", "agree on principle", "meet halfway", "nuanced opinion", "differing perspective", "common ground found"]
    }
]

# Write Day 64
write_day(64, vocab_64, grammar_64, convs_64, paras_64)

print("Day 63 and Day 64 written successfully.")
