# -*- coding: utf-8 -*-
"""Builder for Day 67 and Day 68: Stage 7 (Problems, Decisions and Opinions)."""

import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts.curriculum_engine import write_day

# ==============================================================================
# DAY 67: Solving Conflicts (Mediation and compromise)
# Grammar: ["Should have / Could have (Past Modals)"]
# ==============================================================================
vocab_67 = [
    # Mediation, Diplomacy & Accords (15)
    {"headword": "arbitrator", "pronunciation": "/ˈɑːbɪtreɪtə/", "partOfSpeech": "noun", "definition": "An independent individual officially appointed to settle an industrial or legal dispute.", "example": "The feuding corporations agreed that an impartial arbitrator should have been appointed sooner.", "translation": "مُحكّم محايد / قاضي تحكيم", "exampleArabic": "وافقت الشركات المتنازعة على أنه كان ينبغي تعيين محكّم محايد في وقت أبكر.", "collocations": ["independent arbitrator", "appoint an arbitrator"], "synonyms": ["adjudicator", "umpire"], "antonyms": [], "tags": ["dispute", "legal"]},
    {"headword": "arbitration", "pronunciation": "/ˌɑːbɪˈtreɪʃn/", "partOfSpeech": "noun", "definition": "The formal hearing and determination of a dispute by an impartial third party.", "example": "Both management and labor unions should have submitted their wage grievances to binding arbitration.", "translation": "تحكيم / قضاء تحكيمي", "exampleArabic": "كان ينبغي على كل من الإدارة والنقابات إحالة نزاعات أجورهم إلى تحكيم ملزم.", "collocations": ["binding arbitration", "submit to arbitration"], "synonyms": ["adjudication", "mediation"], "antonyms": ["litigation"], "tags": ["dispute", "resolution"]},
    {"headword": "peace negotiations", "pronunciation": "/piːs nɪˌɡəʊʃiˈeɪʃnz/", "partOfSpeech": "noun", "definition": "Official diplomatic talks held between warring factions to conclude hostilities.", "example": "The diplomatic envoys could have concluded peace negotiations if neither faction had violated the ceasefire.", "translation": "مفاوضات ومحادثات السلام", "exampleArabic": "كان بإمكان المبعوثين الدبلوماسيين إبرام مفاوضات السلام لو لم ينتهك أي طرف وقف إطلاق النار.", "collocations": ["conclude peace negotiations", "delicate peace negotiations"], "synonyms": ["peace talks"], "antonyms": ["hostilities"], "tags": ["peace", "diplomacy"]},
    {"headword": "cessation of hostilities", "pronunciation": "/seˈseɪʃn əv hɒˈstɪlətiz/", "partOfSpeech": "noun", "definition": "An official, formal agreement to halt armed fighting and aggressive military operations.", "example": "The United Nations declared that an immediate cessation of hostilities should have been enforced earlier.", "translation": "وقف الأعمال العدائية / وقف القتال", "exampleArabic": "أعلنت الأمم المتحدة أنه كان ينبغي فرض وقف فوري للأعمال العدائية في وقت أبكر.", "collocations": ["declare a cessation of hostilities", "temporary cessation of hostilities"], "synonyms": ["truce", "armistice"], "antonyms": ["outbreak of war"], "tags": ["peace", "military"]},
    {"headword": "olive branch", "pronunciation": "/ˈɒlɪv brɑːntʃ/", "partOfSpeech": "noun", "definition": "An offer of peace, goodwill, reconciliation, or cessation of conflict.", "example": "The CEO could have extended an olive branch by inviting union leaders to breakfast.", "translation": "غصن الزيتون / بادرة سلام وتصالح", "exampleArabic": "كان بإمكان الرئيس التنفيذي مد غصن الزيتون بدعوة قادة النقابة لتناول الإفطار.", "collocations": ["extend an olive branch", "hold out an olive branch"], "synonyms": ["peace offering"], "antonyms": ["declaration of war"], "tags": ["peace", "idioms"]},
    {"headword": "bury the hatchet", "pronunciation": "/ˈberi ðə ˈhætʃɪt/", "partOfSpeech": "verb", "definition": "To officially end a conflict and make peace with a former adversary.", "example": "Both former political rivals should have buried the hatchet for the economic good of the city.", "translation": "يدفن الأحقاد / ينهي الخصومة القديمة", "exampleArabic": "كان ينبغي على الخصمين السياسيين السابقين دفن أحقادهما من أجل مصلحة المدينة الاقتصادية.", "verbForms": {"v1": "bury the hatchet", "v2": "buried the hatchet", "v3": "buried the hatchet"}, "collocations": ["agree to bury the hatchet", "time to bury the hatchet"], "synonyms": ["make peace", "reconcile"], "antonyms": ["take up arms"], "tags": ["reconciliation", "idioms"]},
    {"headword": "defuse tension", "pronunciation": "/diːˈfjuːz ˈtenʃn/", "partOfSpeech": "verb", "definition": "To make a hostile, precarious situation calmer, friendlier, and less dangerous.", "example": "The skilled mediator could have defused tension by acknowledging both parties' valid grievances.", "translation": "ينزع فتيل التوتر / يهدئ المشاحنات", "exampleArabic": "كان بإمكان الوسيط الماهر نزع فتيل التوتر بالاعتراف بمظالم كلا الطرفين الوجيهة.", "verbForms": {"v1": "defuse tension", "v2": "defused tension", "v3": "defused tension"}, "collocations": ["help defuse tension", "act to defuse tension"], "synonyms": ["de-escalate", "mollify"], "antonyms": ["inflame tension"], "tags": ["diplomacy", "actions"]},
    {"headword": "bridge the divide", "pronunciation": "/brɪdʒ ðə dɪˈvaɪd/", "partOfSpeech": "verb", "definition": "To reduce, reconcile, or overcome substantial differences separating conflicting groups.", "example": "Civic leaders should have built youth community centers to bridge the divide between rival neighborhoods.", "translation": "يرأب الصدع / يقرب بين الفرقاء", "exampleArabic": "كان ينبغي على قادة المجتمع بناء مراكز شبابية لرأب الصدع والتقريب بين الأحياء المتنافسة.", "verbForms": {"v1": "bridge the divide", "v2": "bridged the divide", "v3": "bridged the divide"}, "collocations": ["effort to bridge the divide", "bridge the cultural divide"], "synonyms": ["heal divisions"], "antonyms": ["deepen divisions"], "tags": ["unity", "actions"]},
    {"headword": "reconcile differences", "pronunciation": "/ˈrekənsaɪl ˈdɪfrənsɪz/", "partOfSpeech": "verb", "definition": "To resolve disputes, settle antagonisms, and restore amicable relations.", "example": "The feuding founders could have reconciled differences if they had hired an impartial executive coach.", "translation": "يوفق بين الخلافات / يسوي التباينات", "exampleArabic": "كان بإمكان المؤسسين المتنازعين التوفيق بين خلافاتهما لو استعانا بمدرب تنفيذي محايد.", "verbForms": {"v1": "reconcile differences", "v2": "reconciled differences", "v3": "reconciled differences"}, "collocations": ["attempt to reconcile differences", "fail to reconcile differences"], "synonyms": ["settle disagreements"], "antonyms": ["widen rift"], "tags": ["reconciliation", "actions"]},
    {"headword": "common denominator", "pronunciation": "/ˈkɒmən dɪˈnɒmɪneɪtə/", "partOfSpeech": "noun", "definition": "A shared feature, interest, or belief that unites disparate people or opposing parties.", "example": "Economic self-interest was the vital common denominator that brought both nations to the conference.", "translation": "القاسم المشترك / النقطة الجامعة", "exampleArabic": "كانت المصلحة الاقتصادية الذاتية هي القاسم المشترك الحيوي الذي جمع كلا الأمتين في المؤتمر.", "collocations": ["find a common denominator", "serve as a common denominator"], "synonyms": ["shared basis"], "antonyms": ["irreconcilable division"], "tags": ["compromise", "logic"]},
    {"headword": "deadlock breaker", "pronunciation": "/ˈdedlɒk ˈbreɪkə/", "partOfSpeech": "noun", "definition": "A decisive concession, proposal, or mechanism that resolves a complete stalemate.", "example": "The surprise agreement on cross-border transport tariffs served as the crucial deadlock breaker.", "translation": "مفتاح حلحلة الجمود / مبادرة كسر الطريق المسدود", "exampleArabic": "كان الاتفاق المفاجئ على رسوم النقل عبر الحدود بمثابة مفتاح حاسم لكسر الجمود.", "collocations": ["act as a deadlock breaker", "introduce a deadlock breaker"], "synonyms": ["stalemate breaker"], "antonyms": [], "tags": ["negotiation", "solutions"]},
    {"headword": "stubborn standoff", "pronunciation": "/ˈstʌbən ˈstændɒf/", "partOfSpeech": "noun", "definition": "A protracted, unyielding deadlock where neither side will yield an inch.", "example": "The diplomatic mission should have intervened before the maritime dispute hardened into a stubborn standoff.", "translation": "مواجهة متعنتة / طريق مسدود مستعصٍ", "exampleArabic": "كان ينبغي للبعثة الدبلوماسية التدخل قبل أن يتحول النزاع البحري إلى مواجهة متعنتة وطريق مسدود.", "collocations": ["end a stubborn standoff", "caught in a stubborn standoff"], "synonyms": ["protracted impasse"], "antonyms": ["fluid dialogue"], "tags": ["conflict", "stalemate"]},
    {"headword": "non-negotiable term", "pronunciation": "/ˌnɒn nɪˈɡəʊʃiəbl tɜːm/", "partOfSpeech": "noun", "definition": "A mandatory stipulation or demand that a party refuses to alter, soften, or discuss.", "example": "Immediate troop withdrawals remained a non-negotiable term for signing the peace protocol.", "translation": "شرط غير قابل للتفاوض أو المساومة", "exampleArabic": "ظل الانسحاب الفوري للقوات شرطاً غير قابل للتفاوض لتوقيع بروتوكول السلام.", "collocations": ["insist on non-negotiable terms", "lay down a non-negotiable term"], "synonyms": ["red line", "absolute prerequisite"], "antonyms": ["flexible condition"], "tags": ["negotiations", "demands"]},
    {"headword": "middle way", "pronunciation": "/ˌmɪdl ˈweɪ/", "partOfSpeech": "noun", "definition": "A moderate, balanced course of action between two extreme, conflicting positions.", "example": "The veteran chancellor could have chosen a sensible middle way between austerity and reckless spending.", "translation": "المسلك الوسط / نهج الاعتدال المتوازن", "exampleArabic": "كان بإمكان المستشار المخضرم اختيار مسلك وسط عقلاني بين التقشف والإنفاق المتهور.", "collocations": ["seek the middle way", "steer a middle way"], "synonyms": ["golden mean", "compromise course"], "antonyms": ["extreme path"], "tags": ["moderation", "diplomacy"]},
    {"headword": "de-escalate crisis", "pronunciation": "/diː ˈeskəleɪt ˈkraɪsɪs/", "partOfSpeech": "verb", "definition": "To reduce the intensity, danger, or hostility of a dangerous political or social confrontation.", "example": "Both regional superpowers should have de-escalated the border crisis before artillery fire commenced.", "translation": "يخفض حدة الأزمة / يهدئ التصعيد", "exampleArabic": "كان ينبغي للقوتين الإقليميتين تخفيض حدة أزمة الحدود قبل بدء القصف المدفعي.", "verbForms": {"v1": "de-escalate crisis", "v2": "de-escalated crisis", "v3": "de-escalated crisis"}, "collocations": ["strive to de-escalate crisis", "measures to de-escalate crisis"], "synonyms": ["diffuse confrontation"], "antonyms": ["escalate crisis"], "tags": ["peace", "actions"]},

    # Consensus, Conciliation & Concessions (15)
    {"headword": "diplomatic envoy", "pronunciation": "/ˌdɪpləˈmætɪk ˈenvɔɪ/", "partOfSpeech": "noun", "definition": "An official government representative dispatched on a special mission of foreign negotiation.", "example": "The diplomatic envoy could have prevented retaliatory trade tariffs by delivering a timely compromise draft.", "translation": "مبعوث دبلوماسي رسمي", "exampleArabic": "كان بإمكان المبعوث الدبلوماسي منع الرسوم التجارية الانتقامية بتقديم مسودة تسوية في الوقت المناسب.", "collocations": ["special diplomatic envoy", "dispatch a diplomatic envoy"], "synonyms": ["emissary", "ambassador"], "antonyms": [], "tags": ["diplomacy", "profession"]},
    {"headword": "round table discussion", "pronunciation": "/ˌraʊnd ˈteɪbl dɪˈskʌʃn/", "partOfSpeech": "noun", "definition": "A conference where participants debate and deliberate on an equal footing without hierarchical status.", "example": "Union leaders and executive directors should have sat in an open round table discussion months ago.", "translation": "حلقة نقاش طاولة مستديرة", "exampleArabic": "كان ينبغي لقادة النقابة والمديرين التنفيذيين الجلوس في حلقة نقاش طاولة مستديرة منذ أشهر.", "collocations": ["host a round table discussion", "convene a round table discussion"], "synonyms": ["egalitarian conference"], "antonyms": [], "tags": ["dialogue", "meetings"]},
    {"headword": "consensus building", "pronunciation": "/kənˈsensəs ˈbɪldɪŋ/", "partOfSpeech": "noun", "definition": "A collaborative mediation process that seeks widespread agreement among all stakeholder groups.", "example": "Patient consensus building could have averted the bitter municipal strike.", "translation": "بناء التوافق والإجماع الوطني أو المؤسسي", "exampleArabic": "كان من الممكن لبناء التوافق الصبور أن يجنب المدينة الإضراب البلدي المرير.", "collocations": ["engage in consensus building", "skilled in consensus building"], "synonyms": ["collaborative agreement"], "antonyms": ["unilateral mandate"], "tags": ["governance", "agreement"]},
    {"headword": "appease party", "pronunciation": "/əˈpiːz ˈpɑːti/", "partOfSpeech": "verb", "definition": "To pacify or placate an aggrieved side by acceding to their demands or grievances.", "example": "Management should not have attempted to appease the militant party with superficial bonuses.", "translation": "يسترضي الطرف المتنازع / يهدئ روعه", "exampleArabic": "لم يكن ينبغي للإدارة محاولة استرضاء الطرف المتشدد بمكافآت سطحية.", "verbForms": {"v1": "appease party", "v2": "appeased party", "v3": "appeased party"}, "collocations": ["seek to appease party", "fail to appease party"], "synonyms": ["placate", "propitiate"], "antonyms": ["provoke party"], "tags": ["diplomacy", "actions"]},
    {"headword": "de-escalation", "pronunciation": "/diː ˌeskəˈleɪʃn/", "partOfSpeech": "noun", "definition": "The reduction of the intensity or scale of a conflict, military confrontation, or crisis.", "example": "Military advisors insisted that reciprocal de-escalation should have started along the northern frontier.", "translation": "خفض التصعيد / نزع فتيل الاحتقان", "exampleArabic": "أصر المستشارون العسكريون على أنه كان ينبغي أن يبدأ خفض التصعيد المتبادل على طول الحدود الشمالية.", "collocations": ["bilateral de-escalation", "encourage de-escalation"], "synonyms": ["reduction of hostility"], "antonyms": ["escalation"], "tags": ["peace", "military"]},
    {"headword": "grievance procedure", "pronunciation": "/ˈɡriːvəns prəˈsiːdʒə/", "partOfSpeech": "noun", "definition": "An official, formal sequence established in workplaces to address and resolve employee complaints.", "example": "The aggrieved worker should have followed the formal grievance procedure before lodging an external complaint.", "translation": "إجراءات التظلم والشكاوى النظامية", "exampleArabic": "كان ينبغي على العامل المتضرر اتباع إجراءات التظلم الرسمية قبل رفع شكوى خارجية.", "collocations": ["initiate a grievance procedure", "formal grievance procedure"], "synonyms": ["complaint resolution process"], "antonyms": [], "tags": ["workplace", "rules"]},
    {"headword": "dispute resolution", "pronunciation": "/dɪˈspjuːt ˌrezəˈluːʃn/", "partOfSpeech": "noun", "definition": "Processes such as negotiation, conciliation, and mediation applied to resolve conflicts peacefully.", "example": "Alternative dispute resolution could have saved both firms millions in protracted court fees.", "translation": "فض النزاعات وتسوية الخلافات", "exampleArabic": "كان بإمكان وسائل فض النزاعات البديلة أن توفر على كلا الشركتين الملايين في أتعاب المحاكم الطويلة.", "collocations": ["alternative dispute resolution", "effective dispute resolution"], "synonyms": ["conflict resolution"], "antonyms": ["protracted litigation"], "tags": ["legal", "dispute"]},
    {"headword": "neutral arbiter", "pronunciation": "/ˈnjuːtrəl ˈɑːbɪtə/", "partOfSpeech": "noun", "definition": "An unbiased mediator or judge who holds no stake in the dispute's final outcome.", "example": "Both nations agreed that a neutral arbiter should have presided over the maritime demarcation talks.", "translation": "حَكَم محايد منصف", "exampleArabic": "اتفقت الدولتان على أنه كان ينبغي لحَكَم محايد أن يرأس محادثات ترسيم الحدود البحرية.", "collocations": ["serve as a neutral arbiter", "appoint a neutral arbiter"], "synonyms": ["impartial judge"], "antonyms": ["partisan participant"], "tags": ["justice", "diplomacy"]},
    {"headword": "goodwill gesture", "pronunciation": "/ˌɡʊdˈwɪl ˈdʒestʃə/", "partOfSpeech": "noun", "definition": "An intentional, conciliatory action undertaken to demonstrate peaceful, cooperative intent.", "example": "Releasing maritime detainees was an important goodwill gesture that restored diplomatic dialogue.", "translation": "بادرة حسن نية / لفتة إيجابية للمصالحة", "exampleArabic": "كان إطلاق سراح المحتجزين البحريين بادرة حسن نية مهمة أعادت الحوار الدبلوماسي.", "collocations": ["make a goodwill gesture", "in a goodwill gesture"], "synonyms": ["conciliatory token"], "antonyms": ["provocative act"], "tags": ["diplomacy", "trust"]},
    {"headword": "restore trust", "pronunciation": "/rɪˈstɔː trʌst/", "partOfSpeech": "verb", "definition": "To rebuild mutual confidence, faith, and reliability after a bitter betrayal or feud.", "example": "Both executive committees should have collaborated transparently to restore trust among public shareholders.", "translation": "يستعيد الثقة / يبني جسور الثقة مجدداً", "exampleArabic": "كان ينبغي على كلا اللجنتين التنفيذيتين التعاون بشفافية لاستعادة الثقة بين المساهمين.", "verbForms": {"v1": "restore trust", "v2": "restored trust", "v3": "restored trust"}, "collocations": ["work to restore trust", "essential to restore trust"], "synonyms": ["rebuild confidence"], "antonyms": ["destroy trust"], "tags": ["relationships", "actions"]},
    {"headword": "patch differences", "pronunciation": "/pætʃ ˈdɪfrənsɪz/", "partOfSpeech": "verb", "definition": "To resolve disputes, settle antagonisms, and reconcile amicably after a quarrel.", "example": "The estranged brothers could have patched their differences before their father's milestone anniversary.", "translation": "يرأب الصدع ويسوي الخلافات بين الطرفين", "exampleArabic": "كان بإمكان الشقيقين المتباعدين تسوية خلافاتهما ورأب الصدع قبل الذكرى السنوية لوالدهما.", "verbForms": {"v1": "patch differences", "v2": "patched differences", "v3": "patched differences"}, "collocations": ["patch up differences", "ready to patch differences"], "synonyms": ["reconcile", "heal rift"], "antonyms": ["deepen animosity"], "tags": ["reconciliation", "actions"]},
    {"headword": "reach an accord", "pronunciation": "/riːtʃ ən əˈkɔːd/", "partOfSpeech": "verb", "definition": "To arrive at an official, formal agreement, compact, or treaty between factions.", "example": "Diplomats could have reached an accord if international observers had monitored border traffic.", "translation": "يتوصل إلى اتفاق رسمي / يبرم وفاقاً", "exampleArabic": "كان بإمكان الدبلوماسيين التوصل إلى اتفاق رسمي لو قام مراقبون دوليون بمراقبة حركة الحدود.", "verbForms": {"v1": "reach an accord", "v2": "reached an accord", "v3": "reached an accord"}, "collocations": ["finally reach an accord", "fail to reach an accord"], "synonyms": ["sign agreement"], "antonyms": ["break off talks"], "tags": ["diplomacy", "actions"]},
    {"headword": "pact", "pronunciation": "/pækt/", "partOfSpeech": "noun", "definition": "A formal, solemn agreement between individuals, political parties, or sovereign states.", "example": "Both nations should have ratified the mutual non-aggression pact before border skirmishes began.", "translation": "ميثاق / عهد واتفاقية رسمية", "exampleArabic": "كان ينبغي لكلا الدولتين التصديق على ميثاق عدم الاعتداء المتبادل قبل بدء المناوشات الحدودية.", "collocations": ["sign a pact", "non-aggression pact"], "synonyms": ["covenant", "treaty"], "antonyms": [], "tags": ["treaties", "politics"]},
    {"headword": "treaty negotiation", "pronunciation": "/ˈtriːti nɪˌɡəʊʃiˈeɪʃn/", "partOfSpeech": "noun", "definition": "The formal diplomatic process of drafting, revising, and agreeing on an international pact.", "example": "Senior legal scholars could have guided the treaty negotiation to avoid territorial ambiguity.", "translation": "مفاوضات المعاهدات الدولية", "exampleArabic": "كان بإمكان كبار علماء القانون توجيه مفاوضات المعاهدة لتفادي الغموض الإقليمي.", "collocations": ["conduct treaty negotiations", "delicate treaty negotiation"], "synonyms": ["bilateral accord talks"], "antonyms": [], "tags": ["international", "diplomacy"]},
    {"headword": "hostile standoff", "pronunciation": "/ˈhɒstaɪl ˈstændɒf/", "partOfSpeech": "noun", "definition": "A tense confrontation where opposing armed or ideological forces face each other aggressively.", "example": "The navy could have avoided a hostile standoff by communicating through international radio frequencies.", "translation": "مواجهة عدائية متوترة", "exampleArabic": "كان بإمكان القوات البحرية تجنب مواجهة عدائية متوترة بالتواصل عبر ترددات الراديو الدولية.", "collocations": ["dangerous hostile standoff", "end the hostile standoff"], "synonyms": ["confrontational deadlock"], "antonyms": ["peaceful summit"], "tags": ["military", "conflict"]},

    # Concessions, Settlements & Lasting Harmony (20)
    {"headword": "bitter enmity", "pronunciation": "/ˈbɪtər ˈenməti/", "partOfSpeech": "noun", "definition": "Deep-seated, active, and persistent mutual hatred, ill will, or hostility.", "example": "Decades of bitter enmity should not have prevented the cultural youth exchange program.", "translation": "عداء مستحكم ومرير / بغضاء دفينة", "exampleArabic": "لم يكن ينبغي لعقود من العداء المستحكم والمرير أن تمنع برنامج التبادل الثقافي للشباب.", "collocations": ["harbor bitter enmity", "overcome bitter enmity"], "synonyms": ["deep animosity", "hostility"], "antonyms": ["warm camaraderie"], "tags": ["hatred", "conflict"]},
    {"headword": "mend fences", "pronunciation": "/mend ˈfensɪz/", "partOfSpeech": "verb", "definition": "To repair damaged personal or political relationships through conciliatory efforts.", "example": "The foreign minister could have mended fences by visiting the neighboring capital personally.", "translation": "يرمم العلاقات / يصلح ما تصدع بين الأطراف", "exampleArabic": "كان بإمكان وزير الخارجية ترميم العلاقات بزيارة عاصمة الجوار شخصياً.", "verbForms": {"v1": "mend fences", "v2": "mended fences", "v3": "mended fences"}, "collocations": ["time to mend fences", "attempt to mend fences"], "synonyms": ["rebuild bridges"], "antonyms": ["burn bridges"], "tags": ["reconciliation", "idioms"]},
    {"headword": "clear the air", "pronunciation": "/klɪə ðə ˈeə/", "partOfSpeech": "verb", "definition": "To remove hidden tensions, suspicions, or bad feelings by talking about them openly.", "example": "An open departmental meeting could have cleared the air before resentments solidified.", "translation": "يصفي الأجواء / يزيل سوء التفاهم بمكاشفة صريحة", "exampleArabic": "كان بإمكان اجتماع مفتوح للقسم تصفية الأجواء قبل أن تتصلب مشاعر الاستياء.", "verbForms": {"v1": "clear the air", "v2": "cleared the air", "v3": "cleared the air"}, "collocations": ["help clear the air", "opportunity to clear the air"], "synonyms": ["dispel tension"], "antonyms": ["suppress resentment"], "tags": ["communication", "idioms"]},
    {"headword": "mutual concessions", "pronunciation": "/ˈmjuːtʃuəl kənˈseʃnz/", "partOfSpeech": "noun", "definition": "Reciprocal compromises made by both sides to facilitate an overarching agreement.", "example": "Both management and staff unions should have offered mutual concessions regarding shift lengths.", "translation": "تنازلات متبادلة من كلا الجانبين", "exampleArabic": "كان ينبغي على كل من الإدارة ونقابات العمال تقديم تنازلات متبادلة بشأن أطوال الورديات.", "collocations": ["agree on mutual concessions", "require mutual concessions"], "synonyms": ["reciprocal compromises"], "antonyms": ["unilateral demands"], "tags": ["negotiations", "compromise"]},
    {"headword": "arbitration panel", "pronunciation": "/ˌɑːbɪˈtreɪʃn ˈpænl/", "partOfSpeech": "noun", "definition": "A designated group of independent experts convened to resolve a commercial dispute.", "example": "The arbitration panel ruled that the multinational contractor should have compensated subcontractors.", "translation": "لجنة وهيئة التحكيم", "exampleArabic": "قضت هيئة التحكيم بأنه كان ينبغي على المقاول متعدد الجنسيات تعويض مقاولي الباطن.", "collocations": ["convene an arbitration panel", "before an arbitration panel"], "synonyms": ["tribunal"], "antonyms": [], "tags": ["legal", "business"]},
    {"headword": "peaceful settlement", "pronunciation": "/ˈpiːsfl ˈsetlmənt/", "partOfSpeech": "noun", "definition": "The official resolution of a conflict, territorial dispute, or war without further violence.", "example": "International diplomats could have negotiated a peaceful settlement if border treaties were clarified.", "translation": "تسوية سلمية شاملة", "exampleArabic": "كان بإمكان الدبلوماسيين الدوليين التفاوض على تسوية سلمية لو تم توضيح معاهدات الحدود.", "collocations": ["reach a peaceful settlement", "commit to a peaceful settlement"], "synonyms": ["amicable accord"], "antonyms": ["armed confrontation"], "tags": ["peace", "diplomacy"]},
    {"headword": "restoration of ties", "pronunciation": "/ˌrestəˈreɪʃn əv taɪz/", "partOfSpeech": "noun", "definition": "The formal re-establishment of severed diplomatic, economic, or bilateral relations.", "example": "The reopening of embassies marked the historic restoration of ties after thirty years of hostility.", "translation": "استئناف وتطبيع العلاقات الدبلوماسية", "exampleArabic": "مثل إعادة فتح السفارات الاستئناف التاريخي للعلاقات بعد ثلاثين عاماً من العداء.", "collocations": ["herald the restoration of ties", "negotiate restoration of ties"], "synonyms": ["rapprochement", "re-establishment of relations"], "antonyms": ["severing of ties"], "tags": ["diplomacy", "peace"]},
    {"headword": "win-win outcome", "pronunciation": "/ˌwɪn ˈwɪn ˈaʊtkʌm/", "partOfSpeech": "noun", "definition": "A resolution in which all participating parties gain mutually beneficial advantages.", "example": "Creative mediation could have engineered a win-win outcome that benefited both firms.", "translation": "نتيجة مكسب للجميع (رابح-رابح)", "exampleArabic": "كان بإمكان الوساطة المبتكرة هندسة نتيجة رابح-رابح يستفيد منها كلا الشركتين.", "collocations": ["seek a win-win outcome", "engineer a win-win outcome"], "synonyms": ["mutually beneficial resolution"], "antonyms": ["zero-sum game"], "tags": ["compromise", "negotiation"]},
    {"headword": "give-and-take", "pronunciation": "/ˌɡɪv ən ˈteɪk/", "partOfSpeech": "noun", "definition": "Willingness to compromise, accommodate, and make mutual concessions in discussions.", "example": "A successful durable treaty requires honest, patient give-and-take from both delegations.", "translation": "أخذ وعطاء / مرونة وتنازلات متبادلة", "exampleArabic": "تتطلب المعاهدة الناجحة والدائمة أخذاً وعطاءً صبوراً ونزيهاً من كلا الوفدين.", "collocations": ["spirit of give-and-take", "healthy give-and-take"], "synonyms": ["reciprocal accommodation"], "antonyms": ["inflexibility"], "tags": ["diplomacy", "idioms"]},
    {"headword": "reach a settlement", "pronunciation": "/riːtʃ ə ˈsetlmənt/", "partOfSpeech": "verb", "definition": "To arrive at an official agreement that resolves a legal dispute or financial claim.", "example": "Both commercial litigators should have reached a settlement before jury deliberations began.", "translation": "يتوصل إلى تسوية قانونية أو مالية", "exampleArabic": "كان ينبغي على كلا المحاميين التجاريين التوصل إلى تسوية قبل بدء مداولات هيئة المحلفين.", "verbForms": {"v1": "reach a settlement", "v2": "reached a settlement", "v3": "reached a settlement"}, "collocations": ["reach a fair settlement", "refuse to reach a settlement"], "synonyms": ["settle out of court"], "antonyms": ["fight to the end"], "tags": ["legal", "actions"]},
    {"headword": "heated confrontation", "pronunciation": "/ˈhiːtɪd ˌkɒnfrʌnˈteɪʃn/", "partOfSpeech": "noun", "definition": "An angry, turbulent, and hostile face-to-face clash between opposing factions.", "example": "The municipal police could have prevented the heated confrontation by establishing safety barricades.", "translation": "مواجهة ساخنة ومشحونة", "exampleArabic": "كان بإمكان شرطة البلدية تفادي المواجهة الساخنة والمشحونة بإنشاء حواجز أمان.", "collocations": ["erupt into a heated confrontation", "avoid a heated confrontation"], "synonyms": ["violent clash", "angry altercation"], "antonyms": ["calm summit"], "tags": ["conflict", "events"]},
    {"headword": "aggrieved party", "pronunciation": "/əˈɡriːvd ˈpɑːti/", "partOfSpeech": "noun", "definition": "The individual, company, or state that has suffered an injury, wrong, or loss.", "example": "The corporate council should have compensated the aggrieved party before lawsuits were drafted.", "translation": "الطرف المتضرر وصاحب المظلمة", "exampleArabic": "كان ينبغي على مجلس إدارة الشركة تعويض الطرف المتضرر قبل صياغة الدعاوى القضائية.", "collocations": ["compensate the aggrieved party", "rights of the aggrieved party"], "synonyms": ["injured party"], "antonyms": ["wrongdoer"], "tags": ["legal", "justice"]},
    {"headword": "break the deadlock", "pronunciation": "/breɪk ðə ˈdedlɒk/", "partOfSpeech": "verb", "definition": "To find a solution that resolves an unyielding stalemate in negotiations.", "example": "A bold compromise on tariff exemptions could have broken the deadlock at the trade summit.", "translation": "يكسر الجمود ويحلحل المأزق التفاوضي", "exampleArabic": "كان بإمكان تنازل جريء بشأن الإعفاءات الجمركية أن يكسر الجمود في القمة التجارية.", "verbForms": {"v1": "break the deadlock", "v2": "broke the deadlock", "v3": "broken the deadlock"}, "collocations": ["strive to break the deadlock", "finally break the deadlock"], "synonyms": ["resolve stalemate"], "antonyms": ["prolong deadlock"], "tags": ["negotiations", "actions"]},
    {"headword": "armistice", "pronunciation": "/ˈɑːmɪstɪs/", "partOfSpeech": "noun", "definition": "An official agreement between warring nations to cease combat operations permanently or provisionally.", "example": "The sovereign states should have honored the armistice signed at the conclusion of border hostilities.", "translation": "هدنة عسكرية رسمية", "exampleArabic": "كان ينبغي على الدول ذات السيادة احترام الهدنة العسكرية الموقعة في ختام القتال الحدودي.", "collocations": ["sign an armistice", "armistice treaty"], "synonyms": ["ceasefire pact"], "antonyms": ["resumption of war"], "tags": ["military", "peace"]},
    {"headword": "bilateral talks", "pronunciation": "/baɪˈlætrəl tɔːks/", "partOfSpeech": "noun", "definition": "Official diplomatic negotiations held between two sovereign governments or parties.", "example": "Both foreign ministers could have initiated bilateral talks to resolve territorial fishing disputes.", "translation": "محادثات ثنائية بين طرفين", "exampleArabic": "كان بإمكان كلا وزيري الخارجية الشروع في محادثات ثنائية لحل نزاعات الصيد الإقليمية.", "collocations": ["conduct bilateral talks", "resume bilateral talks"], "synonyms": ["two-party negotiations"], "antonyms": ["multilateral summit"], "tags": ["diplomacy", "dialogue"]},
    {"headword": "conciliatory tone", "pronunciation": "/kənˈsɪliətəri təʊn/", "partOfSpeech": "noun", "definition": "An attitude or manner of speaking intended to placate hostility and pacify anger.", "example": "The CEO should have adopted a conciliatory tone when addressing the striking factory workers.", "translation": "نبرة توفيقية تصالحية ومهدئة", "exampleArabic": "كان ينبغي على الرئيس التنفيذي تبني نبرة تصالحية وتوفيقية عند مخاطبة عمال المصنع المضربين.", "collocations": ["adopt a conciliatory tone", "speak in a conciliatory tone"], "synonyms": ["appeasing manner"], "antonyms": ["belligerent tone"], "tags": ["communication", "diplomacy"]},
    {"headword": "broker a peace", "pronunciation": "/ˈbrəʊkər ə piːs/", "partOfSpeech": "verb", "definition": "To arrange, negotiate, and mediate a formal peace treaty between warring parties.", "example": "Neutral diplomats could have brokered a peace before innocent civilian infrastructure was demolished.", "translation": "يتوسط لإبرام السلام ورعاية الهدنة", "exampleArabic": "كان بإمكان الدبلوماسيين المحايدين التوسط لإبرام السلام قبل تدمير البنية التحتية المدنية.", "verbForms": {"v1": "broker a peace", "v2": "brokered a peace", "v3": "brokered a peace"}, "collocations": ["help broker a peace", "successfully broker a peace"], "synonyms": ["mediate a treaty"], "antonyms": ["incite conflict"], "tags": ["diplomacy", "actions"]},
    {"headword": "unresolved friction", "pronunciation": "/ˌʌnrɪˈzɒlvd ˈfrɪkʃn/", "partOfSpeech": "noun", "definition": "Ongoing, simmering interpersonal or inter-organizational conflict and irritation.", "example": "Unresolved friction between department heads should have been mediated by human resources.", "translation": "احتكاك وتوتر مكتوم لم يُسوَّ بعد", "exampleArabic": "كان ينبغي على الموارد البشرية تسوية الاحتكاك المكتوم المستمر بين رؤساء الأقسام.", "collocations": ["address unresolved friction", "lingering unresolved friction"], "synonyms": ["simmering tension"], "antonyms": ["harmonious relations"], "tags": ["conflict", "workplace"]},
    {"headword": "bitter dispute", "pronunciation": "/ˈbɪtə dɪˈspjuːt/", "partOfSpeech": "noun", "definition": "An intense, prolonged, and acrimonious disagreement between competing parties.", "example": "The heirs could have settled their bitter dispute over family estates out of court.", "translation": "نزاع مرير وخلاف حاد", "exampleArabic": "كان بإمكان الورثة تسوية نزاعهم المرير والخادش على تركات العائلة خارج أروقة القضاء.", "collocations": ["end a bitter dispute", "embroiled in a bitter dispute"], "synonyms": ["acrimonious conflict"], "antonyms": ["amicable accord"], "tags": ["dispute", "conflict"]},
    {"headword": "lasting peace", "pronunciation": "/ˈlɑːstɪŋ piːs/", "partOfSpeech": "noun", "definition": "An enduring, stable state of security and tranquility that withstands trials.", "example": "Generations of statesmen struggled to establish lasting peace across the European continent.", "translation": "سلام دائم ومستقر", "exampleArabic": "ناضل أجيال من رجال الدولة لإرساء سلام دائم ومستقر عبر القارة الأوروبية.", "collocations": ["build lasting peace", "foundation for lasting peace"], "synonyms": ["enduring tranquility"], "antonyms": ["perpetual conflict"], "tags": ["peace", "history"]}
]

grammar_67 = [
    {
        "title": "Should have / Could have (Past Modals)",
        "titleArabic": "الأفعال الناقصة للماضي: اللوم والندم والقدرات الضائعة (Should have / Could have / Would have)",
        "explanation": "We use past modal verbs (Modal + have + Past Participle / V3) to evaluate past actions with the benefit of hindsight: 1) 'Should have + V3' expresses criticism, regret, or advice about what was the right or desirable thing to do in the past, but did not happen ('They should have signed the ceasefire accord'; 'I should have listened to the mediator'). Negative: 'Shouldn't have + V3' criticizes a past action that did happen ('He shouldn't have launched that aggressive lawsuit'). 2) 'Could have + V3' expresses an ability, opportunity, or alternative possibility in the past that was not utilized ('Diplomats could have broken the deadlock, but neither side made concessions'). 3) 'Would have + V3' expresses a hypothetical certainty that depended on an unfulfilled past condition ('We would have reached an accord if they had attended').",
        "explanationArabic": "نستخدم الأفعال الناقصة في زمن الماضي (Modal + have + التصريف الثالث V3) لتقييم أفعال وقرارات الماضي في ضوء ما تبين لاحقاً: 1) Should have + V3 (كان ينبغي أن...): تعبر عن لوم أو ندم أو نقد لفعل كان من الصواب أو الأفضل فعله في الماضي ولكنه لم يحدث ('كان ينبغي أن يوقعوا اتفاق وقف إطلاق النار'). ومنفيها: Shouldn't have + V3 (ما كان ينبغي أن...): لنقد فعل حدث بالفعل في الماضي وكان خطأً. 2) Could have + V3 (كان بإمكانه أن...): تعبر عن قدرة أو فرصة أو إمكانية كانت متاحة في الماضي ولكن لم يتم استغلالها ('كان بإمكان الدبلوماسيين كسر الجمود'). 3) Would have + V3 (لكان قد حدث...): تعبر عن نتيجة ماضية افتراضية كانت ستتحقق لو توفر شرط معين.",
        "structures": [
            {"label": "Past Regret / Criticism · اللوم والنصح بأثر رجعي (Should have)", "pattern": "Subject + should have + Past Participle (V3)", "explanation": "Used to say what was the sensible, moral, or correct past action.", "explanationArabic": "يُستخدم لبيان ما كان ينبغي فعله منطقياً أو أخلاقياً في الماضي."},
            {"label": "Past Missed Opportunity · الفرصة الضائعة في الماضي (Could have)", "pattern": "Subject + could have + Past Participle (V3)", "explanation": "Used to express an unfulfilled past ability or alternative path.", "explanationArabic": "يُستخدم للتعبير عن فرصة أو بديل كان متاحاً في الماضي ولم يُستغل."},
            {"label": "Past Mistake Critique · التنديد بخطأ ماضٍ (Shouldn't have)", "pattern": "Subject + shouldn't have + Past Participle (V3)", "explanation": "Expresses that a past action was wrong, harmful, or regrettable.", "explanationArabic": "يُستخدم لبيان أن تصرفاً ما وقع في الماضي وكان خاطئاً وضاراً."}
        ],
        "examples": [
            {"sentence": "Both corporate factions should have hired an impartial arbitrator before litigation.", "translation": "كان ينبغي لكلا الطرفين المؤسسيين الاستعانة بمحكم محايد قبل اللجوء للقضاء.", "usesVocabulary": ["arbitrator"]},
            {"sentence": "The diplomatic envoy could have defused tension by extending an olive branch.", "translation": "كان بإمكان المبعوث الدبلوماسي نزع فتيل التوتر بمد غصن الزيتون.", "usesVocabulary": ["diplomatic envoy", "defuse tension", "olive branch"]},
            {"sentence": "They shouldn't have allowed the border dispute to solidify into a stubborn standoff.", "translation": "ما كان ينبغي لهم السماح للنزاع الحدودي بالتصلب إلى مواجهة متعنتة وطريق مسدود.", "usesVocabulary": ["stubborn standoff"]},
            {"sentence": "A neutral arbiter could have helped both sides bridge the divide and reach an accord.", "translation": "كان بإمكان حَكَم محايد مساعدة الجانبين على رأب الصدع والتوصل إلى اتفاق.", "usesVocabulary": ["neutral arbiter", "bridge the divide", "reach an accord"]}
        ],
        "commonMistakes": [
            {"wrong": "You should of called the mediator earlier.", "right": "You should have called the mediator earlier.", "note": "Never write 'should of'; it is a phonetic spelling error for 'should have' (or 'should've').", "noteArabic": "لا تكتب 'should of' إطلاقاً؛ فهي خطأ إملائي ناشئ عن النطق الشفهي لـ 'should have'."},
            {"wrong": "They could had reached a settlement yesterday.", "right": "They could have reached a settlement yesterday.", "note": "Modal verbs must always be followed by the base form 'have', never 'had'.", "noteArabic": "يجب أن يتبع الأفعال الناقصة المصدر 'have' دائماً وليس had."}
        ],
        "commonUsage": [
            "Reviewing past business negotiations: 'We should have offered mutual concessions.' (تُستخدم لتقييم مسار المفاوضات التجارية السابقة.)",
            "Diplomatic analysis: 'International monitors could have prevented the hostile standoff.' (تُستخدم في التحليلات السياسية والدبلوماسية للأزمات.)",
            "Personal conflict resolution: 'I shouldn't have lost my temper; we should have cleared the air.' (تُستخدم في مراجعة الخلافات الشخصية والتصالح.)"
        ]
    }
]

convs_67 = [
    {
        "title": "Mediation Debriefing After a Labor Strike",
        "titleArabic": "جلسة مراجعة وساطة بعد إضراب عمالي",
        "setting": "A senior labor arbitrator consults with a human resources director after a painful warehouse workers strike.",
        "lines": [
            {"speaker": "Arbitrator", "text": "Looking back at the strike, both management and the union should have submitted to binding arbitration weeks ago."},
            {"speaker": "HR Director", "text": "I agree. We could have averted this strike if executive leadership had adopted a conciliatory tone early on."},
            {"speaker": "Arbitrator", "text": "Our arbitration panel noted that management should have extended an olive branch instead of refusing to budge."},
            {"speaker": "HR Director", "text": "Our CEO insisted that shift hours were a non-negotiable term, failing to appease the party that felt ignored."},
            {"speaker": "Arbitrator", "text": "A skilled mediator could have defused tension by engineering creative mutual concessions."},
            {"speaker": "HR Director", "text": "We should have recognized employee safety concerns as our vital common denominator."},
            {"speaker": "Arbitrator", "text": "Now, both sides must collaborate in a round table discussion to restore trust and rebuild worker morale."},
            {"speaker": "HR Director", "text": "We are ready to reconcile differences, bury the hatchet, and implement fair dispute resolution."}
        ],
        "vocabularyUsed": ["arbitrator", "arbitration", "conciliatory tone", "arbitration panel", "olive branch", "non-negotiable term", "appease party", "defuse tension", "mutual concessions", "common denominator", "round table discussion", "restore trust", "reconcile differences", "bury the hatchet", "dispute resolution"]
    },
    {
        "title": "International Border De-escalation",
        "titleArabic": "خفض التصعيد الحدودي الدولي بين دبلوماسيين",
        "setting": "Two ambassadors meet at a neutral embassy to resolve a volatile naval border dispute.",
        "lines": [
            {"speaker": "Ambassador A", "text": "Our foreign ministries should have initiated peace negotiations and bilateral talks before naval patrol boats clashed."},
            {"speaker": "Ambassador B", "text": "A specialized diplomatic envoy could have signaled via international radio before crossing the demarcation channel."},
            {"speaker": "Ambassador A", "text": "We must prioritize de-escalation, de-escalate this crisis immediately, and declare an immediate cessation of hostilities."},
            {"speaker": "Ambassador B", "text": "I concur; our governments must not allow this friction to harden into a stubborn standoff."},
            {"speaker": "Ambassador A", "text": "If both fleets pull back ten nautical miles, that goodwill gesture will break the deadlock."},
            {"speaker": "Ambassador B", "text": "Let us request a neutral arbiter from the maritime court to oversee border coordinates."},
            {"speaker": "Ambassador A", "text": "That compromise will pave the way toward signing an armistice and a mutual non-aggression pact."},
            {"speaker": "Ambassador B", "text": "Our legal teams can proceed with treaty negotiations to reach an accord and ensure lasting peace."}
        ],
        "vocabularyUsed": ["peace negotiations", "bilateral talks", "diplomatic envoy", "de-escalation", "de-escalate crisis", "cessation of hostilities", "stubborn standoff", "goodwill gesture", "break the deadlock", "neutral arbiter", "armistice", "pact", "treaty negotiation", "reach an accord", "lasting peace"]
    },
    {
        "title": "Healing Corporate Executive Feuds",
        "titleArabic": "رأب الصدع في خلافات الإدارة العليا",
        "setting": "An executive coach mediates a bitter dispute between co-founders of an enterprise software company.",
        "lines": [
            {"speaker": "Coach", "text": "Both of you could have reached a settlement and settled this bitter dispute months ago if you had agreed to clear the air."},
            {"speaker": "Founder A", "text": "I felt that I was the aggrieved party when client accounts were restructured without my assent."},
            {"speaker": "Founder B", "text": "We should have avoided that heated confrontation at the annual retreat; I made decisions alone."},
            {"speaker": "Coach", "text": "Instead of harboring bitter enmity, an early dialogue could have bridged the divide between founders."},
            {"speaker": "Founder A", "text": "I am ready to mend fences and seek a balanced middle way if we establish transparent governance."},
            {"speaker": "Founder B", "text": "I agree. We should have remembered that our enterprise software was born from healthy give-and-take."},
            {"speaker": "Coach", "text": "I am delighted to broker a peace; a win-win outcome is within reach if both of you commit to consensus building."},
            {"speaker": "Founder A", "text": "Let us patch our differences today and focus our energy on global expansion."}
        ],
        "vocabularyUsed": ["reach a settlement", "bitter dispute", "clear the air", "aggrieved party", "heated confrontation", "bitter enmity", "bridge the divide", "mend fences", "middle way", "give-and-take", "broker a peace", "win-win outcome", "consensus building", "patch differences"]
    }
]

paras_67 = [
    {
        "title": "The Strategic Architecture of Conflict Resolution",
        "titleArabic": "الهندسة الاستراتيجية لفض النزاعات الدولية والمؤسسية",
        "text": "When ideological disputes or commercial friction escalate into a hostile standoff, responsible leaders must act decisively before violence or bankruptcy occurs. Protracted confrontations should have been prevented through proactive consensus building and early bilateral talks. In many historical negotiations, an impartial arbitrator or neutral arbiter served as the indispensable deadlock breaker by identifying a hidden common denominator. By establishing structured round table discussions and demonstrating genuine give-and-take, adversarial factions learn that reciprocal mutual concessions are not a humiliating defeat, but the essential prerequisite for crafting an enduring peaceful settlement.",
        "vocabularyUsed": ["hostile standoff", "consensus building", "bilateral talks", "arbitrator", "neutral arbiter", "deadlock breaker", "common denominator", "round table discussion", "give-and-take", "mutual concessions", "peaceful settlement"]
    },
    {
        "title": "De-escalation and the Rebuilding of Broken Trust",
        "titleArabic": "خفض التصعيد واستعادة جسور الثقة المنهارة",
        "text": "In the volatile arena of international statecraft, preventing an armed clash demands that superpowers de-escalate crises with utmost diplomatic maturity. When border skirmishes erupt, both military commands should have implemented an immediate cessation of hostilities and signed an armistice. Rather than allowing pride to feed bitter enmity, extending a courageous olive branch or offering an initial goodwill gesture breaks the psychological deadlock. When sovereign states bury the hatchet and achieve the full restoration of ties, historical rivals discover that long-term security depends on building lasting peace rather than maintaining aggressive militarization.",
        "vocabularyUsed": ["de-escalate crisis", "cessation of hostilities", "armistice", "bitter enmity", "olive branch", "goodwill gesture", "break the deadlock", "bury the hatchet", "restoration of ties", "lasting peace"]
    },
    {
        "title": "Healing Interpersonal and Organizational Rifts",
        "titleArabic": "معالجة التصدعات الإنسانية والمهنية داخل المؤسسات",
        "text": "Within corporate enterprises, unresolved friction between key partners often paralyzes organizational growth. Rather than allowing petty rivalries to devolve into a bitter dispute that alienates clients, mature colleagues understand that they could have cleared the air through honest dialogue. When an aggrieved party feels heard and respected, leaders can mend fences and adopt a conciliatory tone. By discovering a sensible middle way that engineers a win-win outcome, teams patch their differences, restore mutual trust, and build a resilient culture grounded in mutual respect.",
        "vocabularyUsed": ["unresolved friction", "bitter dispute", "clear the air", "aggrieved party", "mend fences", "conciliatory tone", "middle way", "win-win outcome", "patch differences", "restore trust"]
    }
]

# Write Day 67
write_day(67, vocab_67, grammar_67, convs_67, paras_67)

# ==============================================================================
# DAY 68: Giving Suggestions (Recommending and proposing)
# Grammar: ["Suggestion Structures (suggest + -ing, Why don't we...?)"]
# ==============================================================================
vocab_68 = [
    # Proposing, Pitching & Floating Ideas (15)
    {"headword": "trial balloon", "pronunciation": "/ˈtraɪəl bəˌluːn/", "partOfSpeech": "noun", "definition": "A tentative proposal or measure floated experimentally to test public or stakeholder reaction.", "example": "Why don't we float a trial balloon regarding flexible summer working hours?", "translation": "بالون اختبار لمعرفة ردود الفعل", "exampleArabic": "لمَ لا نطلق بالون اختبار لمعرفة ردود الفعل تجاه ساعات العمل الصيفية المرنة؟", "collocations": ["float a trial balloon", "launch a trial balloon"], "synonyms": ["test proposal"], "antonyms": ["binding decree"], "tags": ["strategy", "ideas"]},
    {"headword": "constructive input", "pronunciation": "/kənˈstrʌktɪv ˈɪnpʊt/", "partOfSpeech": "noun", "definition": "Helpful, practical suggestions or feedback intended to improve a project or process.", "example": "I suggest soliciting constructive input from senior factory floor operators.", "translation": "مساهمة وملاحظات بناءة ومفيدة", "exampleArabic": "أقترح استطلاع مساهمات وملاحظات بناءة من كبار مشغلي أرضية المصنع.", "collocations": ["provide constructive input", "welcome constructive input"], "synonyms": ["valuable feedback"], "antonyms": ["destructive criticism"], "tags": ["feedback", "improvement"]},
    {"headword": "solicit feedback", "pronunciation": "/səˈlɪsɪt ˈfiːdbæk/", "partOfSpeech": "verb", "definition": "To formally ask for, request, or seek reactions, opinions, and evaluations.", "example": "Why don't we solicit feedback from early beta testers before committing to the product rollout?", "translation": "يطلب الآراء والملاحظات رسمياً", "exampleArabic": "لمَ لا نطلب آراء وملاحظات مجربي النسخة التجريبية قبل الالتزام بإطلاق المنتج؟", "verbForms": {"v1": "solicit feedback", "v2": "solicited feedback", "v3": "solicited feedback"}, "collocations": ["actively solicit feedback", "solicit customer feedback"], "synonyms": ["request evaluation"], "antonyms": ["ignore feedback"], "tags": ["research", "actions"]},
    {"headword": "pilot a project", "pronunciation": "/ˈpaɪlət ə ˈprɒdʒekt/", "partOfSpeech": "verb", "definition": "To test an initiative or program on a small exploratory scale before full introduction.", "example": "I suggest piloting a project in two regional branch offices before national implementation.", "translation": "يدير مشروعاً تجريبياً استطلاعياً", "exampleArabic": "أقترح إدارة مشروع تجريبي في فرعين إقليميين قبل التطبيق على المستوى الوطني.", "verbForms": {"v1": "pilot a project", "v2": "piloted a project", "v3": "piloted a project"}, "collocations": ["decide to pilot a project", "funds to pilot a project"], "synonyms": ["test-run an initiative"], "antonyms": ["roll out nationally immediately"], "tags": ["testing", "actions"]},
    {"headword": "moot an idea", "pronunciation": "/muːt ən aɪˈdɪə/", "partOfSpeech": "verb", "definition": "To raise, introduce, or propose an idea for discussion and consideration.", "example": "How about mooting the idea of a four-day workweek at the upcoming executive summit?", "translation": "يطرح فكرة للنقاش والتباحث", "exampleArabic": "ما رأيك في طرح فكرة أسبوع العمل المكون من أربعة أيام في القمة التنفيذية القادمة؟", "verbForms": {"v1": "moot an idea", "v2": "mooted an idea", "v3": "mooted an idea"}, "collocations": ["first mooted the idea", "moot an idea tentatively"], "synonyms": ["put forward", "broach an idea"], "antonyms": ["suppress idea"], "tags": ["proposals", "actions"]},
    {"headword": "table a proposal", "pronunciation": "/ˈteɪbl ə prəˈpəʊzl/", "partOfSpeech": "verb", "definition": "In British English: to formally present a proposal for discussion; in US: to postpone consideration.", "example": "The finance director suggested tabling a proposal to increase research endowments.", "translation": "يطرح مقترحاً رسمياً للنقاش (بريطاني) / يرجئ بحثه (أمريكي)", "exampleArabic": "اقترح المدير المالي طرح مقترح رسمي على الطاولة لزيادة أوقاف البحوث.", "verbForms": {"v1": "table a proposal", "v2": "tabled a proposal", "v3": "tabled a proposal"}, "collocations": ["formally table a proposal", "table a counter-proposal"], "synonyms": ["submit proposal"], "antonyms": ["withdraw proposal"], "tags": ["meetings", "actions"]},
    {"headword": "counter-proposal", "pronunciation": "/ˈkaʊntə prəˌpəʊzl/", "partOfSpeech": "noun", "definition": "An alternative proposal made in response to an initial offer during negotiations.", "example": "Why don't we draft a counter-proposal that combines lower base rent with revenue sharing?", "translation": "مقترح مضاد / عرض بديل", "exampleArabic": "لمَ لا نصوغ مقترحاً بديلاً يجمع بين إيجار أساسي مخفض ومشاركة في الأرباح؟", "verbForms": {}, "collocations": ["submit a counter-proposal", "consider counter-proposals"], "synonyms": ["alternative offer"], "antonyms": [], "tags": ["negotiation", "proposals"]},
    {"headword": "put forward", "pronunciation": "/pʊt ˈfɔːwəd/", "partOfSpeech": "verb", "definition": "To submit, advance, or suggest an idea, plan, or person for consideration.", "example": "I suggest putting forward Sarah's name for the technical director vacancy.", "translation": "يقترح / يقدم فكرة أو مرشحاً للاعتبار", "exampleArabic": "أقترح تقديم اسم سارة لشغل منصب المدير التقني الشاغر.", "verbForms": {"v1": "put forward", "v2": "put forward", "v3": "put forward"}, "collocations": ["put forward a hypothesis", "put forward a candidate"], "synonyms": ["propose", "advance"], "antonyms": ["withdraw"], "tags": ["proposals", "actions"]},
    {"headword": "advocate for", "pronunciation": "/ˈædvəkeɪt fɔː/", "partOfSpeech": "verb", "definition": "To publicly recommend, champion, or support a particular cause or policy.", "example": "Why don't we advocate for green building materials across all municipal construction projects?", "translation": "يدافع عن / يدعو بقوة إلى تأييد قضية", "exampleArabic": "لمَ لا ندعو بقوة لتأييد مواد البناء الخضراء في جميع مشاريع البناء البلدية؟", "verbForms": {"v1": "advocate for", "v2": "advocated for", "v3": "advocated for"}, "collocations": ["passionately advocate for", "advocate for reform"], "synonyms": ["champion", "champion the cause of"], "antonyms": ["oppose"], "tags": ["advocacy", "actions"]},
    {"headword": "champion an idea", "pronunciation": "/ˈtʃæmpiən ən aɪˈdɪə/", "partOfSpeech": "verb", "definition": "To vigorously defend, support, and promote a novel idea through institutional skepticism.", "example": "How about championing the idea of automated electric delivery vans to the executive committee?", "translation": "يتبنى فكرة ويدافع عنها بحماس", "exampleArabic": "ما رأيك في تبني فكرة شاحنات التوصيل الكهربائية المؤتمتة والدفاع عنها أمام اللجنة؟", "verbForms": {"v1": "champion an idea", "v2": "championed an idea", "v3": "championed an idea"}, "collocations": ["champion an idea vigorously", "find someone to champion an idea"], "synonyms": ["sponsor", "promote"], "antonyms": ["abandon idea"], "tags": ["leadership", "actions"]},
    {"headword": "sound out", "pronunciation": "/saʊnd aʊt/", "partOfSpeech": "verb", "definition": "To question someone discreetly or cautiously to discover their intentions or views.", "example": "Why don't we sound out the board chairman over lunch before formally proposing the acquisition?", "translation": "يستطلع رأي فلان بحذر / يجس النبض", "exampleArabic": "لمَ لا نستطلع رأي رئيس مجلس الإدارة على الغداء لجس النبض قبل طرح الاستحواذ رسمياً؟", "verbForms": {"v1": "sound out", "v2": "sounded out", "v3": "sounded out"}, "collocations": ["sound out opinions", "sound out the committee"], "synonyms": ["gauge interest", "probe discreetly"], "antonyms": [], "tags": ["diplomacy", "actions"]},
    {"headword": "float an idea", "pronunciation": "/fləʊt ən aɪˈdɪə/", "partOfSpeech": "verb", "definition": "To suggest an idea casually or provisionally to see if it meets with approval.", "example": "I suggest floating an idea about summer internship exchanges during tomorrow's faculty meeting.", "translation": "يطرح فكرة بشكل غير رسمي لاستطلاع الرأي", "exampleArabic": "أقترح طرح فكرة عن تبادل التدريب الصيفي بشكل غير رسمي في اجتماع الكلية غداً.", "verbForms": {"v1": "float an idea", "v2": "floated an idea", "v3": "floated an idea"}, "collocations": ["float an idea past colleagues", "worth floating an idea"], "synonyms": ["test the waters", "propose informally"], "antonyms": [], "tags": ["creativity", "actions"]},
    {"headword": "think outside box", "pronunciation": "/θɪŋk ˌaʊtˈsaɪd bɒks/", "partOfSpeech": "verb", "definition": "To think unconventionally, creatively, and from a fresh, non-traditional perspective.", "example": "Why don't we think outside the box and turn empty warehouse roofs into urban honey farms?", "translation": "يفكر خارج الصندوق / يبتكر بلا قيود تقليدية", "exampleArabic": "لمَ لا نفكر خارج الصندوق ونحول أسطح المستودعات الفارغة إلى مزارع عسل حضرية؟", "verbForms": {"v1": "think outside box", "v2": "thought outside box", "v3": "thought outside box"}, "collocations": ["encourage thinking outside the box", "time to think outside the box"], "synonyms": ["innovate creatively"], "antonyms": ["stick to dogma"], "tags": ["creativity", "idioms"]},
    {"headword": "viable alternative", "pronunciation": "/ˈvaɪəbl ɔːlˈtɜːnətɪv/", "partOfSpeech": "noun", "definition": "A feasible, workable, and realistic substitute option.", "example": "I suggest presenting offshore wind generation as a commercially viable alternative to coal.", "translation": "بديل عملي وقابل للتطبيق", "exampleArabic": "أقترح تقديم توليد الرياح البحرية كبديل عملي ومجدٍ تجارياً للفحم.", "collocations": ["offer a viable alternative", "explore viable alternatives"], "synonyms": ["feasible option"], "antonyms": ["impractical fantasy"], "tags": ["options", "strategy"]},
    {"headword": "actionable advice", "pronunciation": "/ˈækʃənəbl ədˈvaɪs/", "partOfSpeech": "noun", "definition": "Practical, clear recommendations that can be implemented and put into immediate effect.", "example": "Why don't we provide actionable advice on data encryption in our weekly subscriber bulletin?", "translation": "نصائح وإرشادات قابلة للتطبيق الفوري", "exampleArabic": "لمَ لا نقدم نصائح وإرشادات قابلة للتطبيق الفوري حول تشفير البيانات في نشرتنا الأسبوعية؟", "collocations": ["deliver actionable advice", "practical actionable advice"], "synonyms": ["concrete guidance"], "antonyms": ["vague generalities"], "tags": ["guidance", "practical"]},

    # Nudges, Endorsements & Proof of Concept (15)
    {"headword": "friendly nudge", "pronunciation": "/ˈfrendli nʌdʒ/", "partOfSpeech": "noun", "definition": "A gentle, encouraging reminder or push to prompt someone toward a desirable decision.", "example": "How about giving overdue invoice accounts a friendly nudge before initiating legal collection?", "translation": "تنبيه ودي لطيف / دفعة تشجيعية رقيقة", "exampleArabic": "ما رأيك في إعطاء الحسابات متأخرة الدفع تنبيهاً ودياً لطيفاً قبل الشروع في التحصيل القانوني؟", "collocations": ["give a friendly nudge", "gentle friendly nudge"], "synonyms": ["polite prompt"], "antonyms": ["harsh ultimatum"], "tags": ["persuasion", "manners"]},
    {"headword": "gentle steer", "pronunciation": "/ˈdʒentl stɪə/", "partOfSpeech": "noun", "definition": "Subtle, non-coercive guidance directed to help someone reach the optimal choice.", "example": "The mentor provided a gentle steer to help the student select an accredited postgraduate course.", "translation": "توجيه ناعم وحكيم", "exampleArabic": "قدم المرشد توجيهاً ناعماً وحكيماً لمساعدة الطالب في اختيار دورة دراسات عليا معتمدة.", "collocations": ["give a gentle steer", "benefit from a gentle steer"], "synonyms": ["subtle guidance"], "antonyms": ["rigid dictation"], "tags": ["mentorship", "guidance"]},
    {"headword": "vote of confidence", "pronunciation": "/vəʊt əv ˈkɒnfɪdəns/", "partOfSpeech": "noun", "definition": "A formal or informal show of support expressing confidence in a leader, plan, or team.", "example": "Why don't we give the junior developer a vote of confidence by letting him lead the sprint?", "translation": "تصويت بالثقة / منح الثقة والدعم", "exampleArabic": "لمَ لا نمنح المطور المبتدئ تصويتاً بالثقة وندعمه عبر تركه يقود مرحلة التطوير السريعة؟", "collocations": ["pass a vote of confidence", "major vote of confidence"], "synonyms": ["endorsement", "backing"], "antonyms": ["vote of no confidence"], "tags": ["leadership", "trust"]},
    {"headword": "endorse recommendation", "pronunciation": "/ɪnˈdɔːs ˌrekəmenˈdeɪʃn/", "partOfSpeech": "verb", "definition": "To officially approve, back, and declare agreement with an advisory proposal.", "example": "I suggest endorsing the safety task force's recommendation for automated fire barriers.", "translation": "يعتمد ويزكي التوصية رسمياً", "exampleArabic": "أقترح اعتماد وتزكية توصية فريق مهام السلامة الخاصة بحواجز الحريق المؤتمتة.", "verbForms": {"v1": "endorse recommendation", "v2": "endorsed recommendation", "v3": "endorsed recommendation"}, "collocations": ["fully endorse recommendations", "readily endorse recommendation"], "synonyms": ["officially approve"], "antonyms": ["reject recommendation"], "tags": ["governance", "actions"]},
    {"headword": "green-light proposal", "pronunciation": "/ɡriːn ˈlaɪt prəˈpəʊzl/", "partOfSpeech": "verb", "definition": "To officially authorize, give permission for, and permit a proposed venture to proceed.", "example": "How about green-lighting the mobile application redesign proposal this afternoon?", "translation": "يمنح الضوء الأخضر للمقترح", "exampleArabic": "ما رأيك في منح الضوء الأخضر لمقترح إعادة تصميم تطبيق الهاتف بعد ظهر اليوم؟", "verbForms": {"v1": "green-light proposal", "v2": "green-lighted proposal", "v3": "green-lighted proposal"}, "collocations": ["ready to green-light proposal", "board green-lighted proposal"], "synonyms": ["authorize venture", "approve project"], "antonyms": ["veto proposal"], "tags": ["approval", "actions"]},
    {"headword": "test the waters", "pronunciation": "/test ðə ˈwɔːtəz/", "partOfSpeech": "verb", "definition": "To judge the likely response or success of an action by trying it out discreetly first.", "example": "Why don't we test the waters by launching a targeted social media poll before building the product?", "translation": "يجس النبض ويستطلع الأجواء / يختبر المياه", "exampleArabic": "لمَ لا نجس النبض ونستطلع الأجواء بإطلاق استطلاع رأي موجه قبل بناء المنتج؟", "verbForms": {"v1": "test the waters", "v2": "tested the waters", "v3": "tested the waters"}, "collocations": ["test the waters cautiously", "safe to test the waters"], "synonyms": ["gauge sentiment"], "antonyms": ["plunge blindly"], "tags": ["prudence", "idioms"]},
    {"headword": "pilot phase", "pronunciation": "/ˈpaɪlət feɪz/", "partOfSpeech": "noun", "definition": "The introductory trial stage of an innovation conducted with a limited target audience.", "example": "I suggest launching a three-month pilot phase in two suburban library branches.", "translation": "المرحلة التجريبية الاستطلاعية", "exampleArabic": "أقترح إطلاق مرحلة تجريبية لمدة ثلاثة أشهر في فرعين من مكتبات الضواحي.", "collocations": ["during the pilot phase", "successful pilot phase"], "synonyms": ["trial period"], "antonyms": ["full-scale deployment"], "tags": ["innovation", "projects"]},
    {"headword": "proof of concept", "pronunciation": "/ˌpruːf əv ˈkɒnsept/", "partOfSpeech": "noun", "definition": "Evidence, typically derived from an experiment or prototype, proving that a design is feasible.", "example": "Why don't we build a basic software proof of concept to demonstrate blockchain latency?", "translation": "إثبات المفهوم / نموذج تجريبي لإثبات الجدوى", "exampleArabic": "لمَ لا نبني نموذجاً برمجياً أولياً لإثبات المفهوم وإظهار سرعة استجابة البلوكتشين؟", "verbForms": {}, "collocations": ["working proof of concept", "develop a proof of concept"], "synonyms": ["feasibility prototype"], "antonyms": [], "tags": ["technology", "engineering"]},
    {"headword": "draft resolution", "pronunciation": "/drɑːft ˌrezəˈluːʃn/", "partOfSpeech": "noun", "definition": "A preliminary, written formal proposal put forward for voting in a legislative body.", "example": "The diplomatic envoy suggested submitting a draft resolution regarding ocean plastic pollution.", "translation": "مشروع قرار مكتوب للتصويت", "exampleArabic": "اقترح المبعوث الدبلوماسي تقديم مشروع قرار مكتوب بشأن تلوث المحيطات بالبلاستيك.", "collocations": ["circulate a draft resolution", "sponsor a draft resolution"], "synonyms": ["preliminary motion"], "antonyms": [], "tags": ["policy", "law"]},
    {"headword": "exploratory talk", "pronunciation": "/ɪkˈsplɒrətri tɔːk/", "partOfSpeech": "noun", "definition": "Preliminary discussions undertaken to discover whether formal negotiations are possible.", "example": "Why don't we initiate exploratory talks with regional logistics vendors next week?", "translation": "محادثات استكشافية تمهيدية", "exampleArabic": "لمَ لا نبدأ محادثات استكشافية تمهيدية مع موردي الخدمات اللوجستية الإقليميين الأسبوع القادم؟", "collocations": ["engage in exploratory talks", "hold exploratory talks"], "synonyms": ["preliminary dialogue"], "antonyms": ["concluding treaty"], "tags": ["negotiations", "meetings"]},
    {"headword": "consultative meeting", "pronunciation": "/kənˈsʌltətɪv ˈmiːtɪŋ/", "partOfSpeech": "noun", "definition": "A gathering convened to provide expert advice, professional opinions, and mutual feedback.", "example": "I suggest convening a consultative meeting with environmental biologists before breaking ground.", "translation": "اجتماع تشاوري واستشاري", "exampleArabic": "أقترح عقد اجتماع تشاوري مع علماء البيولوجيا البيئية قبل البدء في أعمال البناء.", "collocations": ["convene a consultative meeting", "regular consultative meeting"], "synonyms": ["advisory session"], "antonyms": [], "tags": ["meetings", "collaboration"]},
    {"headword": "feedback mechanism", "pronunciation": "/ˈfiːdbæk ˈmekənɪzəm/", "partOfSpeech": "noun", "definition": "A structured loop or channel through which users and employees submit observations and complaints.", "example": "Why don't we integrate an automated feedback mechanism inside our customer portal?", "translation": "آلية وقناة جمع التغذية الراجعة والملاحظات", "exampleArabic": "لمَ لا ندمج آلية مؤتمتة لجمع الملاحظات داخل بوابة عملائنا؟", "collocations": ["robust feedback mechanism", "create a feedback mechanism"], "synonyms": ["response channel"], "antonyms": [], "tags": ["systems", "operations"]},
    {"headword": "brainstorming session", "pronunciation": "/ˈbreɪnstɔːmɪŋ ˈseʃn/", "partOfSpeech": "noun", "definition": "A collaborative meeting where participants generate creative ideas freely without immediate criticism.", "example": "How about holding a two-hour brainstorming session to invent a brand name for our snack line?", "translation": "جلسة عصف ذهني إبداعية", "exampleArabic": "ما رأيك في عقد جلسة عصف ذهني لساعتين لابتكار اسم علامة تجارية لخط وجباتنا؟", "collocations": ["facilitate a brainstorming session", "productive brainstorming session"], "synonyms": ["ideation workshop"], "antonyms": [], "tags": ["creativity", "workplace"]},
    {"headword": "actionable proposal", "pronunciation": "/ˈækʃənəbl prəˈpəʊzl/", "partOfSpeech": "noun", "definition": "A clear, realistic, and detailed plan designed for prompt executive implementation.", "example": "I suggest refining the draft into an actionable proposal with clear quarterly deliverables.", "translation": "مقترح عملي قابل للتنفيذ الفوري", "exampleArabic": "أقترح تنقيح المسودة وتحويلها إلى مقترح عملي قابل للتنفيذ بنتائج ربع سنوية واضحة.", "collocations": ["draft an actionable proposal", "submit an actionable proposal"], "synonyms": ["executable plan"], "antonyms": ["vague concept"], "tags": ["planning", "business"]},
    {"headword": "novel approach", "pronunciation": "/ˈnɒvl əˈprəʊtʃ/", "partOfSpeech": "noun", "definition": "An original, inventive, and unprecedented way of addressing a challenge.", "example": "Why don't we adopt a novel approach by utilizing artificial neural networks for seismic detection?", "translation": "نهج مبتكر غير مسبوق / أسلوب جديد تماماً", "exampleArabic": "لمَ لا نتبنى نهجاً مبتكراً غير مسبوق باستخدام الشبكات العصبية الاصطناعية للرصد الزلزالي؟", "collocations": ["pioneer a novel approach", "novel approach to learning"], "synonyms": ["innovative method"], "antonyms": ["conventional formula"], "tags": ["innovation", "creativity"]},

    # Deliberate Refinement & Collaborative Proposals (20)
    {"headword": "pragmatic suggestion", "pronunciation": "/præɡˈmætɪk səˈdʒestʃən/", "partOfSpeech": "noun", "definition": "A sensible, realistic recommendation grounded in actual conditions rather than pure theory.", "example": "The lead accountant made a pragmatic suggestion to lease office servers instead of buying them.", "translation": "اقتراح عملي وواقعي", "exampleArabic": "قدم كبير المحاسبين اقتراحاً عملياً واقعياً باستئجار خوادم المكاتب بدلاً من شرائها.", "collocations": ["offer a pragmatic suggestion", "welcome pragmatic suggestions"], "synonyms": ["realistic proposal"], "antonyms": ["idealistic daydream"], "tags": ["practical", "ideas"]},
    {"headword": "innovative tweak", "pronunciation": "/ˈɪnəvətɪv twiːk/", "partOfSpeech": "noun", "definition": "A small, inventive adjustment that noticeably enhances efficiency or performance.", "example": "How about making an innovative tweak to the turbine blade curvature to boost output?", "translation": "تعديل ابتكاري ذكي ومتقن", "exampleArabic": "ما رأيك في إجراء تعديل ابتكاري ذكي على انحناء شفرة التوربين لزيادة الإنتاج؟", "verbForms": {}, "collocations": ["clever innovative tweak", "implement an innovative tweak"], "synonyms": ["clever fine-tuning"], "antonyms": ["clumsy blunder"], "tags": ["engineering", "refinement"]},
    {"headword": "adopt suggestion", "pronunciation": "/əˈdɒpt səˈdʒestʃən/", "partOfSpeech": "verb", "definition": "To formally choose, accept, and put an advisory recommendation into practice.", "example": "The architectural committee unanimously agreed to adopt her suggestion for rooftop solar glass.", "translation": "يتبنى الاقتراح ويعمل به", "exampleArabic": "وافقت اللجنة المعمارية بالإجماع على تبني اقتراحها الخاص بزجاج الطاقة الشمسية للأسطح.", "verbForms": {"v1": "adopt suggestion", "v2": "adopted suggestion", "v3": "adopted suggestion"}, "collocations": ["readily adopt suggestion", "vote to adopt suggestion"], "synonyms": ["embrace recommendation"], "antonyms": ["reject suggestion"], "tags": ["implementation", "actions"]},
    {"headword": "discard proposal", "pronunciation": "/dɪˈskɑːd prəˈpəʊzl/", "partOfSpeech": "verb", "definition": "To reject, cast aside, and abandon a plan deemed unfeasible or unsuitable.", "example": "I suggest discarding the proposal to relocate downtown offices until rail links are restored.", "translation": "يستبعد المقترح ويرفضه", "exampleArabic": "أقترح استبعاد مقترح نقل مكاتب وسط المدينة حتى يتم إصلاح خطوط السكك الحديدية.", "verbForms": {"v1": "discard proposal", "v2": "discarded proposal", "v3": "discarded proposal"}, "collocations": ["sensible to discard proposal", "decide to discard proposal"], "synonyms": ["scrap plan", "ditch proposal"], "antonyms": ["adopt proposal"], "tags": ["decisions", "actions"]},
    {"headword": "refine proposal", "pronunciation": "/rɪˈfaɪn prəˈpəʊzl/", "partOfSpeech": "verb", "definition": "To make minor adjustments, polish, and improve a plan before formal submission.", "example": "Why don't we refine the proposal by tightening the budget allocation before pitching investors?", "translation": "ينقح المقترح ويهذبه / يصقل الفكرة", "exampleArabic": "لمَ لا ننقح المقترح بضبط بنود الميزانية بدقة قبل عرضه على المستثمرين؟", "verbForms": {"v1": "refine proposal", "v2": "refined proposal", "v3": "refined proposal"}, "collocations": ["take time to refine proposal", "further refine proposal"], "synonyms": ["polish plan", "hone proposal"], "antonyms": ["ruin plan"], "tags": ["refinement", "actions"]},
    {"headword": "tentative suggestion", "pronunciation": "/ˈtentətɪv səˈdʒestʃən/", "partOfSpeech": "noun", "definition": "A provisional, cautious recommendation offered subject to further review or alteration.", "example": "She made a tentative suggestion that we test our promotional marketing exclusively in college towns.", "translation": "اقتراح مبدئي غير ملزم / طرح استرشادي", "exampleArabic": "قدمت اقتراحاً مبدئياً باختبار تسويقنا الترويجي حصرياً في المدن الجامعية.", "collocations": ["offer a tentative suggestion", "mere tentative suggestion"], "synonyms": ["provisional recommendation"], "antonyms": ["categorical demand"], "tags": ["ideas", "polite"]},
    {"headword": "food for reflection", "pronunciation": "/ˌfuːd fə rɪˈflekʃn/", "partOfSpeech": "noun", "definition": "Thoughts, observations, or wisdom that stimulate mature, contemplative evaluation.", "example": "The guest speaker's presentation on workplace dignity gave everyone rich food for reflection.", "translation": "مادة ثرية للتأمل والمراجعة الذاتية", "exampleArabic": "منح عرض المتحدث الضيف حول الكرامة في بيئة العمل الجميع مادة ثرية للتأمل والمراجعة.", "collocations": ["provide food for reflection", "valuable food for reflection"], "synonyms": ["contemplative insight"], "antonyms": [], "tags": ["wisdom", "reflection"]},
    {"headword": "put on the table", "pronunciation": "/pʊt ɒn ðə ˈteɪbl/", "partOfSpeech": "verb", "definition": "To offer an option, concession, or proposal for open consideration and discussion.", "example": "Why don't we put a generous profit-sharing model on the table during union negotiations?", "translation": "يطرح على طاولة البحث والتفاوض", "exampleArabic": "لمَ لا نطرح نموذجاً سخياً لمشاركة الأرباح على طاولة البحث أثناء المفاوضات النقابية؟", "verbForms": {"v1": "put on the table", "v2": "put on the table", "v3": "put on the table"}, "collocations": ["put an offer on the table", "everything is on the table"], "synonyms": ["propose openly"], "antonyms": ["keep under wraps"], "tags": ["negotiations", "idioms"]},
    {"headword": "brainchild", "pronunciation": "/ˈbreɪntʃaɪld/", "partOfSpeech": "noun", "definition": "An idea, invention, or creation produced by a person's individual intellect or imagination.", "example": "The celebrated global educational exchange platform was the brainchild of two college room-mates.", "translation": "وليد الفكر / نتاج العقل والابتكار الخالص", "exampleArabic": "كانت منصة التبادل التعليمي العالمية الشهيرة وليد فكر ونتاج ابتكار اثنين من زملاء السكن الجامعي.", "collocations": ["original brainchild of", "personal brainchild"], "synonyms": ["creation", "invention"], "antonyms": [], "tags": ["innovation", "creativity"]},
    {"headword": "pitch an idea", "pronunciation": "/pɪtʃ ən aɪˈdɪə/", "partOfSpeech": "verb", "definition": "To present, explain, and promote a business idea or creative concept persuasively to buyers.", "example": "How about pitching our machine-learning health app to medical venture capitalists on Friday?", "translation": "يعرض فكرة ويسوقها بحماس للإقناع", "exampleArabic": "ما رأيك في عرض فكرة تطبيقنا الصحي للتعلم الآلي على مستثمري رأس المال المغامر يوم الجمعة؟", "verbForms": {"v1": "pitch an idea", "v2": "pitched an idea", "v3": "pitched an idea"}, "collocations": ["pitch an idea to investors", "successfully pitch an idea"], "synonyms": ["present pitch"], "antonyms": [], "tags": ["business", "actions"]},
    {"headword": "take under advisement", "pronunciation": "/teɪk ˈʌndər ədˈvaɪzmənt/", "partOfSpeech": "verb", "definition": "To accept a recommendation formally for careful, private deliberation before ruling.", "example": "The judge announced that she would take the defense counsel's constitutional motion under advisement.", "translation": "يأخذ الأمر بعين الاعتبار والتدبر قبل القرار", "exampleArabic": "أعلنت القاضية أنها ستأخذ دفع محامي الدفاع الدستوري بعين الاعتبار والتدبر قبل الحكم.", "verbForms": {"v1": "take under advisement", "v2": "took under advisement", "v3": "taken under advisement"}, "collocations": ["promise to take under advisement", "take proposal under advisement"], "synonyms": ["consider carefully"], "antonyms": ["dismiss out of hand"], "tags": ["formality", "law"]},
    {"headword": "welcome suggestions", "pronunciation": "/ˈwelkəm səˈdʒestʃənz/", "partOfSpeech": "verb", "definition": "To openly invite, embrace, and encourage input and recommendations from stakeholders.", "example": "The newly elected municipal council announced that they welcome suggestions on green parks.", "translation": "يرحب بالاقتراحات والآراء", "exampleArabic": "أعلن المجلس البلدي المنتخب حديثاً أنه يرحب بالاقتراحات والآراء حول الحدائق الخضراء.", "verbForms": {"v1": "welcome suggestions", "v2": "welcomed suggestions", "v3": "welcomed suggestions"}, "collocations": ["always welcome suggestions", "warmly welcome suggestions"], "synonyms": ["invite ideas"], "antonyms": ["shut out input"], "tags": ["collaboration", "actions"]},
    {"headword": "fresh perspective", "pronunciation": "/freʃ pəˈspektɪv/", "partOfSpeech": "noun", "definition": "A novel, unjaded way of looking at a traditional or stagnant problem.", "example": "I suggest hiring an independent foreign consultant to bring a fresh perspective to our logistics.", "translation": "رؤية جديدة ومنظور متجدد", "exampleArabic": "أقترح تعيين مستشار أجنبي مستقل لتقديم رؤية جديدة ومنظور متجدد لخدماتنا اللوجستية.", "collocations": ["bring a fresh perspective", "offer a fresh perspective"], "synonyms": ["novel viewpoint"], "antonyms": ["stale view"], "tags": ["insight", "diversity"]},
    {"headword": "creative input", "pronunciation": "/kriˈeɪtɪv ˈɪnpʊt/", "partOfSpeech": "noun", "definition": "Original, artistic, or unconventional contributions offered during collaborative development.", "example": "Why don't we seek creative input from art students to design our annual sustainability report?", "translation": "مساهمة إبداعية / لمسة فكرية مبتكرة", "exampleArabic": "لمَ لا نسعى للحصول على مساهمة إبداعية من طلاب الفنون لتصميم تقرير الاستدامة السنوي؟", "collocations": ["value creative input", "provide creative input"], "synonyms": ["artistic contribution"], "antonyms": [], "tags": ["art", "ideas"]},
    {"headword": "solicit opinions", "pronunciation": "/səˈlɪsɪt əˈpɪnjənz/", "partOfSpeech": "verb", "definition": "To ask for and gather the views, attitudes, and evaluations of a target group.", "example": "The board suggested soliciting opinions from neighborhood parents before revising bus schedules.", "translation": "يستطلع الآراء ويسبر التوجهات", "exampleArabic": "اقترح مجلس الإدارة استطلاع آراء أولياء الأمور في الحي قبل تعديل جداول الحافلات.", "verbForms": {"v1": "solicit opinions", "v2": "solicited opinions", "v3": "solicited opinions"}, "collocations": ["actively solicit opinions", "solicit public opinions"], "synonyms": ["gather views"], "antonyms": [], "tags": ["research", "actions"]},
    {"headword": "unsolicited advice", "pronunciation": "/ˌʌnsəˈlɪsɪtɪd ədˈvaɪs/", "partOfSpeech": "noun", "definition": "Recommendations or guidance offered to someone without their asking for or seeking it.", "example": "He irritated his colleagues by continuously dispensing unsolicited advice on code styling.", "translation": "نصيحة غير مطلوبة وغير مدعوة", "exampleArabic": "أثار استياء زملائه بتقديم نصائح غير مطلوبة باستمرار حول أسلوب كتابة الشيفرة البرمجية.", "collocations": ["dispense unsolicited advice", "resist unsolicited advice"], "synonyms": ["unasked counsel"], "antonyms": ["requested guidance"], "tags": ["manners", "communication"]},
    {"headword": "strategic recommendation", "pronunciation": "/strəˈtiːdʒɪk ˌrekəmenˈdeɪʃn/", "partOfSpeech": "noun", "definition": "A formal, high-level proposal aimed at securing long-term institutional advantage.", "example": "The advisory management consultants submitted five strategic recommendations on digital transformation.", "translation": "توصية استراتيجية عليا", "exampleArabic": "قدم المستشارون الإداريون خمس توصيات استراتيجية عليا بشأن التحول الرقمي.", "collocations": ["formulate strategic recommendations", "core strategic recommendation"], "synonyms": ["high-level guidance"], "antonyms": ["tactical detail"], "tags": ["business", "strategy"]},
    {"headword": "propose a motion", "pronunciation": "/prəˈpəʊz ə ˈməʊʃn/", "partOfSpeech": "verb", "definition": "To formally introduce a proposal for debate and voting in a parliamentary assembly.", "example": "During the general meeting, the treasurer proposed a motion to audit corporate travel accounts.", "translation": "يطرح اقتراحاً أو طلباً للتصويت في الجمعية", "exampleArabic": "خلال الاجتماع العام، طرح أمين الصندوق اقتراحاً للتصويت للتدقيق في حسابات سفر الشركة.", "verbForms": {"v1": "propose a motion", "v2": "proposed a motion", "v3": "proposed a motion"}, "collocations": ["stand to propose a motion", "right to propose a motion"], "synonyms": ["move a resolution"], "antonyms": [], "tags": ["formal", "governance"]},
    {"headword": "second a motion", "pronunciation": "/ˈsekənd ə ˈməʊʃn/", "partOfSpeech": "verb", "definition": "To formally express support for a proposal introduced by another member so it can be voted on.", "example": "The vice-chair immediately seconded the motion to allocate emergency funds for flood relief.", "translation": "يثنّي على الاقتراح / يؤيد طرحه رسمياً للتصويت", "exampleArabic": "ثنى نائب الرئيس على الفور على الاقتراح لتخصيص أموال طوارئ لإغاثة المتضررين من الفيضانات.", "verbForms": {"v1": "second a motion", "v2": "seconded a motion", "v3": "seconded a motion"}, "collocations": ["rise to second a motion", "proud to second a motion"], "synonyms": ["support a proposal formally"], "antonyms": ["oppose motion"], "tags": ["formal", "governance"]},
    {"headword": "viable proposition", "pronunciation": "/ˈvaɪəbl ˌprɒpəˈzɪʃn/", "partOfSpeech": "noun", "definition": "A project, business offer, or proposal that has a realistic prospect of commercial success.", "example": "Venture investors confirmed that building micro-warehouses near commuter hubs was a viable proposition.", "translation": "مشروع أو عرض ذو جدوى حقيقية", "exampleArabic": "أكد مستثمرو المشاريع أن بناء مستودعات صغرى بالقرب من مراكز النقل مشروع ذو جدوى حقيقية.", "collocations": ["prove a viable proposition", "financially viable proposition"], "synonyms": ["workable venture"], "antonyms": ["unviable scheme"], "tags": ["business", "finance"]}
]

grammar_68 = [
    {
        "title": "Suggestion Structures (suggest + -ing, Why don't we...?)",
        "titleArabic": "صيغ الاقتراح والتوصية (Suggestion Structures: Suggest / Recommend / Why don't we / How about / What if)",
        "explanation": "In English, there are multiple polite and natural ways to propose ideas and recommend actions: 1) 'Suggest / Recommend + Gerund (Verb-ing)': Used when the speaker includes themselves or speaks generally ('I suggest piloting a project first'; 'She recommended soliciting feedback'). Note: NEVER say 'suggest to do'! 2) 'Suggest / Recommend + that + Subject + Base Verb' (Subjunctive in formal English): 'I suggest that we refine the proposal'; 'He recommended that the board green-light the initiative'. 3) Conversational question forms: 'Why don't we + Base Verb...?' ('Why don't we test the waters with a pilot?'); 'How about / What about + Gerund (-ing)...?' ('How about pitching our idea on Friday?'); 'What if we + Past Simple / Present Simple...?' ('What if we thought outside the box and leased the equipment?'). 4) Indirect modal suggestions: 'We could always...', 'It might be worth + Gerund...'.",
        "explanationArabic": "في اللغة الإنجليزية، تتعدد صيغ تقديم الاقتراحات والتوصيات بأسلوب لبق وطبيعي: 1) Suggest / Recommend + Verb-ing: يُستخدم عندما يشارك المتحدث في الفعل أو يقترحه بشكل عام ('أقترح البدء بمشروع تجريبي'; 'أوصي باستطلاع الآراء'). تنبيه هام: لا تقل أبداً 'suggest to do'! 2) Suggest / Recommend + that + الفاعل + المصدر المجرد (صيغة Subjunctive الرسمية): 'I suggest that we refine the proposal'. 3) صيغ الاستفهام التحاورية: 'Why don't we + المصدر...؟' (لمَ لا نفعل كذا؟)؛ 'How about / What about + Verb-ing...؟' (ما رأيك في فعل كذا؟)؛ 'What if we + فعل...؟' (ماذا لو فعلنا كذا؟). 4) الاقتراحات الاحتمالية غير المباشرة: 'We could always...' (يمكننا دائماً أن...)؛ 'It might be worth + -ing' (قد يجدر بنا أن...).",
        "structures": [
            {"label": "Gerund Suggestion · الاقتراح بالمصدر (Suggest / Recommend + -ing)", "pattern": "Subject + suggest / recommend + Verb-ing", "explanation": "The standard natural formula for proposing a shared activity.", "explanationArabic": "الصيغة الطبيعية الأكثر شيوعاً لاقتراح نشاط مشترك دون ذكر مفعول به."},
            {"label": "Direct Question Suggestion · الاستفهام الاقتراحي (Why don't we...?)", "pattern": "Why don't we + Base Verb...?", "explanation": "A friendly, collaborative conversational invitation to act.", "explanationArabic": "صيغة استفهامية ودية وتشاركية تدعو للبدء في الفعل بحماس."},
            {"label": "Informal Inquiry · الاستفسار الحواري (How about + -ing...?)", "pattern": "How about / What about + Verb-ing...?", "explanation": "Casual and inviting formula for proposing a trial or new angle.", "explanationArabic": "أسلوب حواري غير رسمي ومحبب لطرح فكرة أو تجربة جديدة."},
            {"label": "Subjunctive That-Clause · الاقتراح الرسمي بجملة That", "pattern": "Subject + suggest / recommend + that + Subject + Base Verb", "explanation": "Formal business or legal format for official resolutions.", "explanationArabic": "صيغة رسمية راقية مستخدمة في محاضر الاجتماعات وقرارات الأعمال."}
        ],
        "examples": [
            {"sentence": "I suggest piloting a project in two regional hubs before rolling it out nationally.", "translation": "أقترح إدارة مشروع تجريبي في مركزين إقليميين قبل تعميمه على المستوى الوطني.", "usesVocabulary": ["pilot a project"]},
            {"sentence": "Why don't we solicit feedback from consumers to refine our proposal?", "translation": "لمَ لا نطلب آراء المستهلكين وملاحظاتهم لتنقيح مقترحنا وصقله؟", "usesVocabulary": ["solicit feedback", "refine proposal"]},
            {"sentence": "How about championing that innovative tweak during tomorrow's brainstorming session?", "translation": "ما رأيك في تبني ذلك التعديل الابتكاري والدفاع عنه في جلسة العصف الذهني غداً؟", "usesVocabulary": ["champion an idea", "innovative tweak", "brainstorming session"]},
            {"sentence": "She recommended that the board endorse the safety task force's strategic recommendation.", "translation": "أوصت بأن يعتمد مجلس الإدارة التوصية الاستراتيجية لفريق مهام السلامة.", "usesVocabulary": ["endorse recommendation", "strategic recommendation"]}
        ],
        "commonMistakes": [
            {"wrong": "I suggest you to take a break and sleep on it.", "right": "I suggest you take a break and sleep on it. (OR: I suggest that you take / I suggest taking)", "note": "Never use 'suggest someone to do'; use 'suggest that someone do' or 'suggest doing'.", "noteArabic": "لا تستخدم إطلاقاً 'suggest someone to do'؛ بل استخدم 'suggest that someone do' أو 'suggest doing'."},
            {"wrong": "Why don't we to invite a guest speaker for advice?", "right": "Why don't we invite a guest speaker for advice?", "note": "After 'Why don't we', use the bare infinitive (Base Verb) without 'to'.", "noteArabic": "استخدم مصدر الفعل المجرد دون to بعد التركيب 'Why don't we'."}
        ],
        "commonUsage": [
            "Team brainstorms: 'How about testing the waters with a social media poll?' (تُستخدم لتوليد الأفكار في ورش العمل.)",
            "Executive board pitches: 'I suggest tabling a proposal for expanding cloud storage.' (تُستخدم لتقديم المبادرات في اجتماعات الإدارة.)",
            "Mentoring advice: 'Why don't we break down the deliverable into weekly sprints?' (تُستخدم في توجيه الموظفين والطلاب بلباقة.)"
        ]
    }
]

convs_68 = [
    {
        "title": "Brainstorming a Product Innovation",
        "titleArabic": "عصف ذهني لابتكار وتطوير منتج جديد",
        "setting": "A product lead and an engineering architect discuss new features in a creative design studio.",
        "lines": [
            {"speaker": "Lead", "text": "Our user retention has plateaued. Why don't we think outside the box and try a novel approach?"},
            {"speaker": "Architect", "text": "I suggest building a small proof of concept that introduces gamified daily language challenges."},
            {"speaker": "Lead", "text": "That sounds promising! How about floating that idea past our user experience researchers this afternoon?"},
            {"speaker": "Architect", "text": "Why don't we test the waters by launching a prototype pilot phase with two hundred university students?"},
            {"speaker": "Lead", "text": "Excellent! I suggest integrating a seamless automated feedback mechanism to solicit user opinions."},
            {"speaker": "Architect", "text": "If users love it, we can champion the idea and pitch the proposal to executive investors."},
            {"speaker": "Lead", "text": "Let us schedule a formal consultative meeting tomorrow to refine the proposal with financial metrics."},
            {"speaker": "Architect", "text": "Agreed! That actionable proposal will give our creative roadmap a major vote of confidence."}
        ],
        "vocabularyUsed": ["think outside box", "novel approach", "proof of concept", "float an idea", "test the waters", "pilot phase", "feedback mechanism", "solicit opinions", "champion an idea", "pitch an idea", "consultative meeting", "refine proposal", "actionable proposal", "vote of confidence"]
    },
    {
        "title": "Strategy Session in the Boardroom",
        "titleArabic": "جلسة استراتيجية في غرفة مجلس الإدارة",
        "setting": "A managing director discusses organizational restructuring with senior strategy advisors.",
        "lines": [
            {"speaker": "Director", "text": "I welcome suggestions on how to streamline our European shipping distribution network."},
            {"speaker": "Advisor A", "text": "I suggest tabling a proposal to partner with local electric delivery cooperatives."},
            {"speaker": "Advisor B", "text": "Why don't we moot the idea of regional fulfillment hubs as a viable alternative to single megastores?"},
            {"speaker": "Director", "text": "That is a pragmatic suggestion. Did our operational research team provide constructive input?"},
            {"speaker": "Advisor A", "text": "Yes, they recommended adopting the suggestion and green-lighting the pilot phase immediately."},
            {"speaker": "Advisor B", "text": "How about putting forward Sarah's name to lead this strategic recommendation as project manager?"},
            {"speaker": "Director", "text": "I will take that under advisement, but she has definitely earned a vote of confidence."},
            {"speaker": "Advisor A", "text": "Let us prepare a draft resolution so the board can vote to green-light the proposal next Tuesday."}
        ],
        "vocabularyUsed": ["welcome suggestions", "table a proposal", "moot an idea", "viable alternative", "pragmatic suggestion", "constructive input", "adopt suggestion", "green-light proposal", "put forward", "strategic recommendation", "take under advisement", "vote of confidence", "draft resolution"]
    },
    {
        "title": "Creative Pitch for a Community Campaign",
        "titleArabic": "عرض إبداعي لمبادرة مجتمعية بيئية",
        "setting": "A junior marketing specialist presents campaign concepts to the creative director.",
        "lines": [
            {"speaker": "Specialist", "text": "Why don't we float a trial balloon regarding our rooftop urban farming campaign?"},
            {"speaker": "Director", "text": "I love the concept! It brings a refreshing fresh perspective to municipal sustainability."},
            {"speaker": "Specialist", "text": "This whole initiative was actually the brainchild of our summer high-school design interns."},
            {"speaker": "Director", "text": "How about soliciting constructive feedback from local neighborhood council representatives?"},
            {"speaker": "Specialist", "text": "I suggest giving them a friendly nudge via our community newsletter this Thursday."},
            {"speaker": "Director", "text": "Instead of dispensing unsolicited advice, let us listen to what citizens put on the table."},
            {"speaker": "Specialist", "text": "If we make this innovative tweak to our solar glass mockups, it will prove a viable proposition."},
            {"speaker": "Director", "text": "Brilliant! Your actionable advice will turn this trial balloon into a triumph."}
        ],
        "vocabularyUsed": ["trial balloon", "fresh perspective", "brainchild", "solicit feedback", "constructive input", "friendly nudge", "unsolicited advice", "put on the table", "innovative tweak", "viable proposition", "actionable advice"]
    }
]

paras_68 = [
    {
        "title": "The Dynamic Lifecycle of Collaborative Innovation",
        "titleArabic": "دورة الحياة الديناميكية للابتكار التشاركي",
        "text": "Every great business breakthrough begins when creative thinkers dare to think outside the box and moot an idea that challenges orthodox dogmas. Rather than rushing blindly into full commercial deployment, prudent leaders float a trial balloon to test the waters and solicit feedback from grassroots consumers. Hosting an energetic brainstorming session allows team members to provide constructive input and offer a fresh perspective on stubborn bottlenecks. When managers discover a viable alternative that solves user frustrations, they build a functional proof of concept to validate technical feasibility, ensuring that innovative tweaks are grounded in actionable advice.",
        "vocabularyUsed": ["think outside box", "moot an idea", "trial balloon", "test the waters", "solicit feedback", "brainstorming session", "constructive input", "fresh perspective", "viable alternative", "proof of concept", "innovative tweak", "actionable advice"]
    },
    {
        "title": "From Exploratory Concepts to Executable Strategy",
        "titleArabic": "من المفاهيم الاستكشافية إلى استراتيجيات التنفيذ",
        "text": "Translating an intellectual brainchild into an enterprise standard requires formal discipline and institutional consensus. A visionary employee must learn to pitch an idea persuasively, table a proposal with transparent financial projections, and advocate for sustainable reforms. In progressive organizations, executives warmly welcome suggestions, establish clear feedback mechanisms, and sponsor consultative meetings before finalizing budgets. When leaders review an actionable proposal, they evaluate whether to adopt the suggestion immediately or discard the proposal if capital constraints arise. By taking time to refine proposals and secure a firm vote of confidence, companies ensure that approved projects thrive.",
        "vocabularyUsed": ["brainchild", "pitch an idea", "table a proposal", "advocate for", "welcome suggestions", "feedback mechanism", "consultative meeting", "actionable proposal", "adopt suggestion", "discard proposal", "refine proposal", "vote of confidence"]
    },
    {
        "title": "Strategic Prototyping and Institutional Backing",
        "titleArabic": "النماذج الأولية الاستراتيجية والدعم المؤسسي",
        "text": "Before committing millions to complex automated infrastructure, forward-looking corporations pilot a project through a carefully controlled pilot phase. Rather than ignoring valuable consumer sentiment, smart directors actively solicit opinions and incorporate pragmatic suggestions into revised draft resolutions. Offering a gentle steer and giving overdue initiatives a friendly nudge ensures that teams stay aligned on core milestones without feeling micromanaged. When stakeholders see verified performance data confirming that an initiative is a viable proposition, executive boards eagerly endorse recommendations and green-light proposals for nationwide deployment.",
        "vocabularyUsed": ["pilot a project", "pilot phase", "solicit opinions", "pragmatic suggestion", "draft resolution", "gentle steer", "friendly nudge", "viable proposition", "endorse recommendation", "green-light proposal"]
    }
]

# Write Day 68
write_day(68, vocab_68, grammar_68, convs_68, paras_68)

print("Day 67 and Day 68 written successfully.")
