# -*- coding: utf-8 -*-
"""Builder for Day 71 and Day 72: Stage 8 (Advanced Everyday English)."""

import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts.curriculum_engine import write_day

# ==============================================================================
# DAY 71: Discussions and Debates (Structured discussion)
# Grammar: ["Advanced Connectors: however, moreover, on the other hand"]
# ==============================================================================
vocab_71 = [
    # Argumentation & Debate Structure (17)
    {"headword": "present an argument", "pronunciation": "/prɪˈzent ən ˈɑːɡjumənt/", "partOfSpeech": "verb", "definition": "To formally state and explain a reasoned case to persuade an audience.", "example": "She was asked to present an argument supporting renewable energy subsidies.", "translation": "يقدم حجة / يطرح موقفاً مستنداً للأدلة", "verbForms": {"v1": "present an argument", "v2": "presented an argument", "v3": "presented an argument"}, "collocations": ["present a compelling argument", "present an argument for"], "synonyms": ["make a case"], "antonyms": ["concede"], "tags": ["debate", "rhetoric"]},
    {"headword": "counter-argument", "pronunciation": "/ˈkaʊntər ˌɑːɡjumənt/", "partOfSpeech": "noun", "definition": "A rebuttal that challenges and refutes an opposing position or claim.", "example": "The professor developed a sophisticated counter-argument to the prevailing economic theory.", "translation": "حجة مضادة / رد على الحجة المقابلة", "collocations": ["offer a counter-argument", "anticipate counter-arguments"], "synonyms": ["rebuttal", "refutation"], "antonyms": ["supporting argument"], "tags": ["debate", "logic"]},
    {"headword": "rebut claim", "pronunciation": "/rɪˈbʌt kleɪm/", "partOfSpeech": "verb", "definition": "To formally prove an assertion false using evidence or logical analysis.", "example": "Defense attorneys successfully rebutted the prosecution's primary forensic claim.", "translation": "يدحض الادعاء / يفند الحجة بالدليل", "verbForms": {"v1": "rebut claim", "v2": "rebutted claim", "v3": "rebutted claim"}, "collocations": ["strongly rebut claim", "fail to rebut claim"], "synonyms": ["refute", "disprove"], "antonyms": ["validate"], "tags": ["logic", "legal"]},
    {"headword": "logical fallacy", "pronunciation": "/ˈlɒdʒɪkl ˈfæləsi/", "partOfSpeech": "noun", "definition": "An error in reasoning that invalidates an argument's logical structure.", "example": "The climate skeptic's argument contained an obvious logical fallacy.", "translation": "مغالطة منطقية / خطأ في الاستدلال", "collocations": ["commit a logical fallacy", "identify a logical fallacy"], "synonyms": ["reasoning error"], "antonyms": ["sound argument"], "tags": ["logic", "debate"]},
    {"headword": "fallacious reasoning", "pronunciation": "/fəˈleɪʃəs ˈriːzənɪŋ/", "partOfSpeech": "noun", "definition": "Thinking that is based on false or misleading assumptions producing flawed conclusions.", "example": "His fallacious reasoning about vaccine safety alarmed the medical community.", "translation": "استدلال مغلوط ومبني على مقدمات خاطئة", "collocations": ["expose fallacious reasoning", "based on fallacious reasoning"], "synonyms": ["flawed logic"], "antonyms": ["sound reasoning"], "tags": ["logic", "critique"]},
    {"headword": "argumentative flaw", "pronunciation": "/ˌɑːɡjuˈmentətɪv flɔː/", "partOfSpeech": "noun", "definition": "A specific weakness or gap in the logical structure of a presented argument.", "example": "The panel identified an argumentative flaw in the candidate's economic policy position.", "translation": "ثغرة في بناء الحجة وتسلسلها المنطقي", "collocations": ["expose an argumentative flaw", "major argumentative flaw"], "synonyms": ["reasoning gap"], "antonyms": ["tight argument"], "tags": ["debate", "analysis"]},
    {"headword": "burden of proof", "pronunciation": "/ˈbɜːdn əv pruːf/", "partOfSpeech": "noun", "definition": "The obligation to provide sufficient evidence supporting a disputed claim.", "example": "In criminal law, the burden of proof always rests with the prosecution.", "translation": "عبء الإثبات / مسؤولية تقديم الدليل", "collocations": ["shift the burden of proof", "meet the burden of proof"], "synonyms": ["evidential responsibility"], "antonyms": ["presumption of innocence"], "tags": ["legal", "debate"]},
    {"headword": "devil's advocate", "pronunciation": "/ˈdevlz ˈædvəkət/", "partOfSpeech": "noun", "definition": "A person who argues an opposite position to test the strength of prevailing reasoning.", "example": "To stress-test our plan, our consultant volunteered to play devil's advocate.", "translation": "محامي الشيطان / من يتبنى الرأي المعاكس لاختبار الحجة", "collocations": ["play devil's advocate", "act as devil's advocate"], "synonyms": ["dissenter"], "antonyms": ["true believer"], "tags": ["debate", "strategy"]},
    {"headword": "steel man", "pronunciation": "/stiːl mæn/", "partOfSpeech": "verb", "definition": "To articulate the strongest possible version of an opponent's argument before critiquing it.", "example": "The philosophy professor always steelmanned opposing positions before addressing them critically.", "translation": "يصيغ أقوى نسخة من حجة الخصم ليرد عليها", "verbForms": {"v1": "steel man", "v2": "steelmanned", "v3": "steelmanned"}, "collocations": ["steel man the argument", "try to steel man"], "synonyms": ["strengthen opponent's case"], "antonyms": ["straw man"], "tags": ["philosophy", "debate"]},
    {"headword": "crux of debate", "pronunciation": "/krʌks əv dɪˈbeɪt/", "partOfSpeech": "noun", "definition": "The most critical and decisive issue at the heart of a controversy.", "example": "The crux of debate centred on whether economic growth outweighs environmental costs.", "translation": "جوهر النقاش / صميم النزاع الفكري", "collocations": ["identify the crux of debate", "get to the crux of debate"], "synonyms": ["core issue", "central question"], "antonyms": ["peripheral concern"], "tags": ["debate", "discourse"]},
    {"headword": "open floor", "pronunciation": "/ˌəʊpən ˈflɔː/", "partOfSpeech": "noun", "definition": "An invitation allowing any audience member to speak or ask questions freely.", "example": "After the keynote, the moderator announced an open floor for questions.", "translation": "فرصة مفتوحة للجمهور للمشاركة والتعليق", "collocations": ["open the floor", "take the open floor"], "synonyms": ["open discussion"], "antonyms": ["closed session"], "tags": ["meetings", "debate"]},
    {"headword": "moderator role", "pronunciation": "/ˈmɒdəreɪtə rəʊl/", "partOfSpeech": "noun", "definition": "The function of impartially chairing a debate to ensure balanced discussion.", "example": "She expertly fulfilled the moderator role, ensuring all voices received equal time.", "translation": "دور المحكّم أو المدير المحايد للنقاش", "collocations": ["assume the moderator role", "take the moderator role"], "synonyms": ["chairperson function"], "antonyms": ["partisan role"], "tags": ["meetings", "facilitation"]},
    {"headword": "panelist", "pronunciation": "/ˈpænəlɪst/", "partOfSpeech": "noun", "definition": "An expert or representative invited to participate in a structured public discussion.", "example": "The conference panelist challenged the prevailing consensus on artificial intelligence regulation.", "translation": "عضو لجنة نقاش / مشارك في حلقة نقاشية", "collocations": ["distinguished panelist", "invite as panelist"], "synonyms": ["discussant", "participant"], "antonyms": [], "tags": ["events", "debate"]},
    {"headword": "proposition side", "pronunciation": "/ˌprɒpəˈzɪʃn saɪd/", "partOfSpeech": "noun", "definition": "The team in a formal debate that argues in favour of a proposed motion.", "example": "The proposition side must persuasively demonstrate why the motion deserves support.", "translation": "الفريق المؤيد للاقتراح في النقاش الرسمي", "collocations": ["argue the proposition side", "represent the proposition side"], "synonyms": ["affirmative team"], "antonyms": ["opposition bench"], "tags": ["debate", "structure"]},
    {"headword": "opposition bench", "pronunciation": "/ˌɒpəˈzɪʃn bentʃ/", "partOfSpeech": "noun", "definition": "The team or group in a debate or parliament that argues against a proposed motion.", "example": "The opposition bench launched a fierce rebuttal against the government's spending bill.", "translation": "مقاعد المعارضة / الفريق الرافض للاقتراح", "collocations": ["sit on the opposition bench", "lead the opposition bench"], "synonyms": ["opposing side"], "antonyms": ["proposition side"], "tags": ["politics", "debate"]},
    {"headword": "formal debate", "pronunciation": "/ˈfɔːml dɪˈbeɪt/", "partOfSpeech": "noun", "definition": "A structured discussion governed by rules, time limits, and clear procedural frameworks.", "example": "University students are trained to excel in formal debate competitions.", "translation": "نقاش رسمي منظم وفق قواعد وإجراءات محددة", "collocations": ["participate in formal debate", "organize a formal debate"], "synonyms": ["structured discussion"], "antonyms": ["informal chat"], "tags": ["debate", "education"]},
    {"headword": "point of order", "pronunciation": "/pɔɪnt əv ˈɔːdə/", "partOfSpeech": "noun", "definition": "A procedural challenge raised when meeting rules or debate protocols are violated.", "example": "The committee chairperson raised a point of order when speakers exceeded allotted time.", "translation": "نقطة نظام / اعتراض إجرائي على سير الجلسة", "collocations": ["raise a point of order", "rule on a point of order"], "synonyms": ["procedural objection"], "antonyms": [], "tags": ["procedure", "meetings"]},

    # Formal Procedure & Structured Response (16)
    {"headword": "raise an objection", "pronunciation": "/reɪz ən əbˈdʒekʃn/", "partOfSpeech": "verb", "definition": "To formally state disagreement or challenge a proceeding in a structured context.", "example": "Opposition lawyers raised an objection to the admission of the disputed evidence.", "translation": "يرفع اعتراضاً رسمياً / يثير مانعاً قانونياً أو إجرائياً", "verbForms": {"v1": "raise an objection", "v2": "raised an objection", "v3": "raised an objection"}, "collocations": ["formally raise an objection", "sustain a raised objection"], "synonyms": ["lodge a protest"], "antonyms": ["withdraw objection"], "tags": ["legal", "debate"]},
    {"headword": "overrule objection", "pronunciation": "/ˌəʊvəˈruːl əbˈdʒekʃn/", "partOfSpeech": "verb", "definition": "To officially reject a raised objection and permit the proceeding to continue.", "example": "The presiding judge overruled the objection, instructing the witness to answer.", "translation": "يرفض الاعتراض ويُسقطه رسمياً", "verbForms": {"v1": "overrule objection", "v2": "overruled objection", "v3": "overruled objection"}, "collocations": ["promptly overrule objection", "overrule the objection"], "synonyms": ["dismiss objection"], "antonyms": ["sustain objection"], "tags": ["legal", "debate"]},
    {"headword": "closing statement", "pronunciation": "/ˈkləʊzɪŋ ˈsteɪtmənt/", "partOfSpeech": "noun", "definition": "Final summarizing remarks delivered at the conclusion of a debate or legal proceeding.", "example": "The defense attorney's closing statement moved several jurors to reconsider their verdict.", "translation": "الخطاب الختامي / بيان الإغلاق والخلاصة", "collocations": ["deliver closing statement", "powerful closing statement"], "synonyms": ["final argument"], "antonyms": ["opening statement"], "tags": ["legal", "debate"]},
    {"headword": "opening statement", "pronunciation": "/ˈəʊpənɪŋ ˈsteɪtmənt/", "partOfSpeech": "noun", "definition": "Introductory remarks outlining the argument and key evidence a side plans to present.", "example": "The prosecution's opening statement outlined a clear chronology of alleged corporate fraud.", "translation": "بيان الافتتاح / الطرح التمهيدي في النقاش", "collocations": ["deliver an opening statement", "compelling opening statement"], "synonyms": ["introductory remarks"], "antonyms": ["closing statement"], "tags": ["legal", "debate"]},
    {"headword": "motion carried", "pronunciation": "/ˈməʊʃn ˈkærid/", "partOfSpeech": "phrase", "definition": "A formal announcement that a proposed resolution has been approved by the majority.", "example": "The chair declared that the motion was carried after a twenty-seven to twelve vote.", "translation": "تمت الموافقة على المقترح بالأغلبية", "collocations": ["motion carried unanimously", "motion carried by majority"], "synonyms": ["proposal approved"], "antonyms": ["motion defeated"], "tags": ["governance", "procedure"]},
    {"headword": "motion defeated", "pronunciation": "/ˈməʊʃn dɪˈfiːtɪd/", "partOfSpeech": "phrase", "definition": "A formal announcement that a proposed resolution has been rejected by the majority.", "example": "The motion was defeated narrowly, with only two votes separating both sides.", "translation": "رُفض المقترح بالأغلبية / سقط الاقتراح", "collocations": ["motion defeated by a majority", "declare the motion defeated"], "synonyms": ["proposal rejected"], "antonyms": ["motion carried"], "tags": ["governance", "procedure"]},
    {"headword": "casting vote", "pronunciation": "/ˈkɑːstɪŋ vəʊt/", "partOfSpeech": "noun", "definition": "A chairperson's deciding vote used to break a tie in a legislative or committee vote.", "example": "The chair exercised her casting vote in favour of the infrastructure amendment.", "translation": "صوت الترجيح / الصوت الفاصل في التعادل", "collocations": ["use casting vote", "exercise the casting vote"], "synonyms": ["deciding vote", "tiebreaker vote"], "antonyms": [], "tags": ["governance", "procedure"]},
    {"headword": "speaker's podium", "pronunciation": "/ˈspiːkəz ˈpəʊdiəm/", "partOfSpeech": "noun", "definition": "The raised platform or lectern from which an orator formally addresses an audience.", "example": "As the vice chancellor stepped up to the speaker's podium, the hall fell silent.", "translation": "منصة المتحدث / المنبر الخطابي الرسمي", "collocations": ["step to the speaker's podium", "address from the speaker's podium"], "synonyms": ["lectern", "rostrum"], "antonyms": [], "tags": ["events", "public speaking"]},
    {"headword": "floor speaker", "pronunciation": "/flɔː ˈspiːkə/", "partOfSpeech": "noun", "definition": "An attendee granted permission to address an assembly or legislative chamber.", "example": "A floor speaker raised a practical concern about funding mechanisms for the proposal.", "translation": "المتحدث من القاعة / الممثل المُعطى الكلمة في الجمعية", "collocations": ["recognize a floor speaker", "call a floor speaker"], "synonyms": ["contributor from the floor"], "antonyms": ["panel moderator"], "tags": ["governance", "public speaking"]},
    {"headword": "deliberative assembly", "pronunciation": "/dɪˈlɪbərətɪv əˈsembli/", "partOfSpeech": "noun", "definition": "A formal body of people who meet to discuss and decide on matters by majority vote.", "example": "A deliberative assembly must follow Roberts Rules to ensure procedural fairness.", "translation": "هيئة تداولية / جمعية مداولة وتقرير رسمية", "collocations": ["chair a deliberative assembly", "rules of a deliberative assembly"], "synonyms": ["legislative body"], "antonyms": ["executive authority"], "tags": ["governance", "law"]},
    {"headword": "parliamentary procedure", "pronunciation": "/ˌpɑːləˈmentri prəˈsiːdʒə/", "partOfSpeech": "noun", "definition": "The established formal rules governing how legislative and deliberative bodies conduct meetings.", "example": "The student union followed strict parliamentary procedure during its annual general meeting.", "translation": "اللوائح والنظام البرلماني الرسمي للجلسات", "collocations": ["observe parliamentary procedure", "violate parliamentary procedure"], "synonyms": ["rules of order"], "antonyms": ["informal discussion"], "tags": ["law", "governance"]},
    {"headword": "on the contrary", "pronunciation": "/ɒn ðə ˈkɒntrəri/", "partOfSpeech": "phrase", "definition": "A discourse connector expressing strong disagreement with what was just said.", "example": "On the contrary, our quarterly data clearly shows rising consumer confidence.", "translation": "على النقيض / بل على العكس تماماً", "collocations": ["on the contrary however", "quite on the contrary"], "synonyms": ["conversely", "in contrast"], "antonyms": ["likewise"], "tags": ["connectors", "discourse"]},
    {"headword": "by the same token", "pronunciation": "/baɪ ðə seɪm ˈtəʊkən/", "partOfSpeech": "phrase", "definition": "For the same reason or by the same logic, used to extend an argument coherently.", "example": "If we cut corporate taxes, by the same token we should reduce regulatory burdens.", "translation": "وبالمنطق نفسه / وعلى المنوال ذاته", "collocations": ["and by the same token", "by the same token therefore"], "synonyms": ["similarly", "by the same logic"], "antonyms": ["conversely"], "tags": ["connectors", "logic"]},
    {"headword": "conversely", "pronunciation": "/ˈkɒnvɜːsli/", "partOfSpeech": "adverb", "definition": "Introducing a statement that reverses or contrasts with what was previously said.", "example": "Higher interest rates slow spending; conversely, lower rates stimulate economic growth.", "translation": "وعلى العكس / في المقابل", "collocations": ["conversely however", "conversely speaking"], "synonyms": ["on the other hand", "in contrast"], "antonyms": ["likewise", "similarly"], "tags": ["connectors", "discourse"]},
    {"headword": "notwithstanding", "pronunciation": "/ˌnɒtwɪðˈstændɪŋ/", "partOfSpeech": "preposition", "definition": "In spite of; without being prevented by a constraint or circumstance.", "example": "Notwithstanding significant budget cuts, the research team delivered remarkable clinical results.", "translation": "على الرغم من / بصرف النظر عن", "collocations": ["notwithstanding the above", "notwithstanding challenges"], "synonyms": ["despite", "in spite of"], "antonyms": ["because of"], "tags": ["connectors", "formal"]},
    {"headword": "with that said", "pronunciation": "/wɪð ðæt sed/", "partOfSpeech": "phrase", "definition": "An acknowledgment of a prior point before introducing a contrasting or qualifying idea.", "example": "His research methods are questionable. With that said, his conclusions merit serious consideration.", "translation": "وبالرغم مما قيل / مع أخذ ذلك بعين الاعتبار", "collocations": ["with that said however", "with that said though"], "synonyms": ["that said", "having said that"], "antonyms": [], "tags": ["connectors", "discourse"]},
    {"headword": "to that end", "pronunciation": "/tuː ðæt end/", "partOfSpeech": "phrase", "definition": "For that purpose; in order to achieve or fulfil the goal previously mentioned.", "example": "We aim to reduce carbon emissions by forty percent. To that end, we are investing in solar.", "translation": "لذلك الغرض / وتحقيقاً لتلك الغاية", "collocations": ["and to that end", "to that end specifically"], "synonyms": ["for this purpose"], "antonyms": ["contrary to that aim"], "tags": ["connectors", "formal"]},

    # Critical Thinking & Rhetorical Devices (17)
    {"headword": "by extension", "pronunciation": "/baɪ ɪkˈstenʃn/", "partOfSpeech": "phrase", "definition": "Applying the same logic or principle to a broader, related context or conclusion.", "example": "If we accept this precedent, by extension we must apply it to all comparable cases.", "translation": "وبالتوسع / وامتداداً لهذا المنطق", "collocations": ["by extension therefore", "and by extension"], "synonyms": ["as a consequence"], "antonyms": ["in isolation"], "tags": ["connectors", "logic"]},
    {"headword": "draw a distinction", "pronunciation": "/drɔː ə dɪˈstɪŋkʃn/", "partOfSpeech": "verb", "definition": "To clearly identify and articulate the difference between two concepts or positions.", "example": "It is important to draw a distinction between correlation and direct causal relationships.", "translation": "يضع فاصلاً بين مفهومين / يميز بوضوح بين حالتين", "verbForms": {"v1": "draw a distinction", "v2": "drew a distinction", "v3": "drawn a distinction"}, "collocations": ["draw a clear distinction", "fail to draw a distinction"], "synonyms": ["differentiate clearly"], "antonyms": ["conflate"], "tags": ["logic", "analysis"]},
    {"headword": "nuanced position", "pronunciation": "/ˈnjuːɑːnst pəˈzɪʃn/", "partOfSpeech": "noun", "definition": "A carefully qualified stance that acknowledges complexity and avoids oversimplification.", "example": "The senator's nuanced position on immigration rejected both extreme ends of the debate.", "translation": "موقف دقيق متعدد الأبعاد ورافض للتبسيط المخل", "collocations": ["adopt a nuanced position", "defend a nuanced position"], "synonyms": ["balanced stance"], "antonyms": ["black-and-white position"], "tags": ["opinion", "debate"]},
    {"headword": "categorical claim", "pronunciation": "/ˌkætəˈɡɒrɪkl kleɪm/", "partOfSpeech": "noun", "definition": "An absolute, unconditional assertion that applies universally without exceptions.", "example": "Making the categorical claim that all economic migrants are criminal is clearly false.", "translation": "ادعاء قطعي مطلق / تأكيد لا استثناء فيه", "collocations": ["make a categorical claim", "challenge a categorical claim"], "synonyms": ["absolute assertion"], "antonyms": ["qualified statement"], "tags": ["debate", "logic"]},
    {"headword": "empirical evidence", "pronunciation": "/ɪmˈpɪrɪkl ˈevɪdəns/", "partOfSpeech": "noun", "definition": "Data derived from direct observation or experiment rather than speculation or theory.", "example": "Scientific policies must be grounded in robust empirical evidence from peer-reviewed studies.", "translation": "دليل تجريبي مستند للملاحظة والتجربة المباشرة", "collocations": ["provide empirical evidence", "rely on empirical evidence"], "synonyms": ["observational data"], "antonyms": ["speculation", "conjecture"], "tags": ["science", "debate"]},
    {"headword": "anecdotal evidence", "pronunciation": "/ˌænɪkˈdəʊtl ˈevɪdəns/", "partOfSpeech": "noun", "definition": "Informal evidence based on individual personal accounts rather than systematic data.", "example": "Patient anecdotes are valuable, but anecdotal evidence cannot replace clinical trial results.", "translation": "دليل استئناسي غير منهجي / شهادات فردية غير موثقة", "collocations": ["rely on anecdotal evidence", "dismiss anecdotal evidence"], "synonyms": ["personal testimony"], "antonyms": ["empirical evidence"], "tags": ["research", "debate"]},
    {"headword": "cherry-picking", "pronunciation": "/ˈtʃeri ˌpɪkɪŋ/", "partOfSpeech": "noun", "definition": "Selectively presenting only the data or facts that support one's position while ignoring contrary evidence.", "example": "The think tank was accused of cherry-picking statistics to exaggerate economic inequality.", "translation": "انتقاء الأدلة المناسبة وتجاهل المعاكس / الاختيار الانتقائي المتحيز", "collocations": ["accuse of cherry-picking", "engage in cherry-picking"], "synonyms": ["selective presentation"], "antonyms": ["balanced analysis"], "tags": ["bias", "rhetoric"]},
    {"headword": "confirmation bias", "pronunciation": "/ˌkɒnfəˈmeɪʃn ˈbaɪəs/", "partOfSpeech": "noun", "definition": "The tendency to search for and interpret information that confirms pre-existing beliefs.", "example": "Confirmation bias leads people to dismiss objective data that challenges their worldview.", "translation": "تحيز التأكيد / الميل للبحث عما يؤكد المعتقدات المسبقة", "collocations": ["suffer from confirmation bias", "overcome confirmation bias"], "synonyms": ["selective perception"], "antonyms": ["critical objectivity"], "tags": ["psychology", "cognition"]},
    {"headword": "false premise", "pronunciation": "/fɔːls ˈpremɪs/", "partOfSpeech": "noun", "definition": "An incorrect or unproven foundational assumption on which an argument depends.", "example": "The entire economic theory rests on a false premise about consumer rationality.", "translation": "مقدمة خاطئة / افتراض أساسي مغلوط", "collocations": ["built on a false premise", "challenge the false premise"], "synonyms": ["wrong assumption"], "antonyms": ["true premise"], "tags": ["logic", "debate"]},
    {"headword": "begging the question", "pronunciation": "/ˈbeɡɪŋ ðə ˈkwestʃən/", "partOfSpeech": "noun", "definition": "A circular argument where the conclusion is assumed within the premise itself.", "example": "Saying the law is right because it is the law commits the fallacy of begging the question.", "translation": "المصادرة على المطلوب / الحجة الدائرية", "collocations": ["guilty of begging the question", "this begs the question"], "synonyms": ["circular argument"], "antonyms": ["valid syllogism"], "tags": ["logic", "fallacy"]},
    {"headword": "false dichotomy", "pronunciation": "/fɔːls daɪˈkɒtəmi/", "partOfSpeech": "noun", "definition": "Presenting only two options as if they are the sole possibilities when others exist.", "example": "Framing the debate as growth versus environment commits a false dichotomy.", "translation": "الثنائية الزائفة / حصر الخيارات في اثنين خطأً", "collocations": ["create a false dichotomy", "fall into a false dichotomy"], "synonyms": ["either/or fallacy"], "antonyms": ["spectrum of options"], "tags": ["logic", "fallacy"]},
    {"headword": "appeal to authority", "pronunciation": "/əˈpiːl tuː ɔːˈθɒrɪti/", "partOfSpeech": "noun", "definition": "Using an expert or prominent figure to validate a claim regardless of the evidence quality.", "example": "Citing a celebrity endorsement rather than research constitutes an appeal to authority.", "translation": "الاحتجاج بالسلطة / التعويل على الشهرة دون دليل", "collocations": ["commit appeal to authority", "improper appeal to authority"], "synonyms": ["argumentum ad verecundiam"], "antonyms": ["evidence-based argument"], "tags": ["fallacy", "rhetoric"]},
    {"headword": "post hoc fallacy", "pronunciation": "/pəʊst hɒk ˈfæləsi/", "partOfSpeech": "noun", "definition": "Assuming causation from mere temporal sequence: 'A happened before B, so A caused B'.", "example": "Attributing economic recovery solely to the new tax cut commits a post hoc fallacy.", "translation": "مغالطة ما بعد هذا إذاً بسببه / الخلط بين التسلسل والسببية", "collocations": ["commit the post hoc fallacy", "classic post hoc fallacy"], "synonyms": ["false causation"], "antonyms": ["causal proof"], "tags": ["fallacy", "logic"]},
    {"headword": "sweeping claim", "pronunciation": "/ˈswiːpɪŋ kleɪm/", "partOfSpeech": "noun", "definition": "A broad, unqualified assertion that applies a generalization without adequate justification.", "example": "Politicians frequently make sweeping claims about crime statistics without disaggregated data.", "translation": "ادعاء شامل وعريض يفتقر للتدقيق والتخصيص", "collocations": ["make a sweeping claim", "challenge a sweeping claim"], "synonyms": ["overgeneralization"], "antonyms": ["qualified claim"], "tags": ["debate", "rhetoric"]},
    {"headword": "circular reasoning", "pronunciation": "/ˈsɜːkjulə ˈriːzənɪŋ/", "partOfSpeech": "noun", "definition": "An argument where the conclusion is used as a premise to prove itself.", "example": "His argument used circular reasoning: the product is popular because people love it.", "translation": "الحجة الدائرية / استخدام النتيجة كدليل على نفسها", "collocations": ["guilty of circular reasoning", "expose circular reasoning"], "synonyms": ["petitio principii"], "antonyms": ["linear reasoning"], "tags": ["logic", "fallacy"]},
    {"headword": "reductio ad absurdum", "pronunciation": "/rɪˈdʌktɪəʊ æd əbˈsɜːdəm/", "partOfSpeech": "noun", "definition": "A technique that disproves a claim by showing it leads to an absurd or impossible conclusion.", "example": "She used reductio ad absurdum to show the regulation would inevitably ban all outdoor activities.", "translation": "الاختزال إلى السخافة / إثبات بطلان الحجة بإيصالها لنتيجة سخيفة", "collocations": ["employ reductio ad absurdum", "illustrate via reductio ad absurdum"], "synonyms": ["proof by contradiction"], "antonyms": ["constructive argument"], "tags": ["logic", "philosophy"]}
]

grammar_71 = [
    {
        "title": "Advanced Connectors: however, moreover, on the other hand",
        "explanation": "Advanced connectors give structured discourse its cohesion, helping writers and speakers signal contrast, addition, consequence, and concession with precision. Key categories: (1) Contrast: 'however', 'nevertheless', 'notwithstanding', 'conversely', 'on the contrary'; (2) Addition: 'moreover', 'furthermore', 'by the same token', 'by extension'; (3) Concession: 'with that said', 'that said', 'admittedly', 'granted'; (4) Consequence: 'to that end', 'as a result', 'consequently'. Unlike basic connectors, advanced connectors are formal, often precede a comma, and may begin a sentence. Avoid overusing any single connector: vary them to demonstrate discourse sophistication.",
        "structures": [
            {"pattern": "Contrast: Statement A. However / Nevertheless / Conversely / On the contrary, Statement B."},
            {"pattern": "Addition: Statement A. Moreover / Furthermore / By the same token, Statement B."},
            {"pattern": "Concession: Statement A. With that said / Notwithstanding this, Statement B."}
        ],
        "examples": [
            {
                "sentence": "The empirical evidence is compelling; however, the opposition bench has raised a valid counter-argument about methodology.",
                "arabic": "الدليل التجريبي مقنع؛ غير أن المعارضة أثارت حجة مضادة وجيهة بشأن المنهجية.",
                "usesVocabulary": ["empirical evidence", "opposition bench", "counter-argument"]
            },
            {
                "sentence": "The policy would reduce emissions. Moreover, by extension it would create tens of thousands of green jobs.",
                "arabic": "ستُخفض السياسة الانبعاثات. علاوةً على ذلك، وامتداداً لهذا المنطق، ستخلق عشرات الآلاف من الوظائف الخضراء.",
                "usesVocabulary": ["by extension"]
            },
            {
                "sentence": "The defendant's closing statement was eloquent. With that said, it failed to rebut the most damaging claim.",
                "arabic": "كان الخطاب الختامي للمدعى عليه بليغاً. ومع ذلك، فشل في دحض الادعاء الأشد ضرراً.",
                "usesVocabulary": ["closing statement", "rebut claim"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "The plan is sound. However we must address the false premise.",
                "right": "The plan is sound. However, we must address the false premise.",
                "explanation": "When 'however' begins a sentence as a connector, it must be followed by a comma."
            },
            {
                "wrong": "The burden of proof lies with them, furthermore the motion was carried.",
                "right": "The burden of proof lies with them. Furthermore, the motion was carried.",
                "explanation": "Do not join two independent clauses with a comma and 'furthermore' — use a full stop or semicolon."
            }
        ]
    }
]

convs_71 = [
    {
        "title": "University Debate: Artificial Intelligence Regulation",
        "titleArabic": "نقاش جامعي: تنظيم الذكاء الاصطناعي",
        "setting": "A university debate club holds a formal debate on AI governance.",
        "lines": [
            {"speaker": "Chair", "text": "The floor is now open. Proposition side, you may present an argument in favour of mandatory AI audits."},
            {"speaker": "Nadia", "text": "Thank you. The burden of proof lies with those claiming AI audits impede innovation. On the contrary, empirical evidence from the EU demonstrates improved consumer trust."},
            {"speaker": "Leon", "text": "I must rebut that claim. The proposition side commits a false premise by assuming all AI systems carry equal risks, which is simply untrue."},
            {"speaker": "Nadia", "text": "With that said, we acknowledge diverse risk profiles. By extension, however, this strengthens our case for tiered regulatory frameworks."},
            {"speaker": "Leon", "text": "The opposition bench raises a point of order. Our panelist has exceeded the two-minute speaking limit."},
            {"speaker": "Chair", "text": "Point of order noted. Notwithstanding the procedural concern, the argument is substantive. Please continue briefly."},
            {"speaker": "Nadia", "text": "To that end, we call upon this deliberative assembly to draw a distinction between regulative oversight and bureaucratic overreach."},
            {"speaker": "Leon", "text": "By the same token, sweeping claims about risk must be backed by anecdotal evidence at minimum, if not rigorous empirical data."}
        ],
        "vocabularyUsed": ["present an argument", "burden of proof", "on the contrary", "empirical evidence", "rebut claim", "false premise", "opposition bench", "point of order", "notwithstanding", "by extension", "with that said", "deliberative assembly", "draw a distinction", "anecdotal evidence", "sweeping claim", "panelist", "to that end", "by the same token"]
    },
    {
        "title": "Policy Forum: Steel-Manning the Climate Debate",
        "titleArabic": "منتدى السياسات: تعزيز حجج الخصوم في نقاش المناخ",
        "setting": "A think tank forum where analysts debate climate finance mechanisms.",
        "lines": [
            {"speaker": "Host", "text": "Before we address the formal debate, could you steel man the opposing view on carbon taxation?"},
            {"speaker": "Dr. Park", "text": "Certainly. Playing devil's advocate, one might argue that carbon taxes disproportionately burden lower-income households without achieving measurable emissions targets."},
            {"speaker": "Ms. Stein", "text": "That is a nuanced position, and it avoids the false dichotomy between economic growth and environmental protection."},
            {"speaker": "Dr. Park", "text": "Precisely. Cherry-picking individual economic data without systemic context is a textbook case of fallacious reasoning."},
            {"speaker": "Ms. Stein", "text": "Conversely, confirmation bias leads policymakers to dismiss contrary evidence from diverse national fiscal experiments."},
            {"speaker": "Dr. Park", "text": "Moreover, categorical claims about carbon tax efficacy must be grounded in long-term empirical evidence, not anecdotal success stories."},
            {"speaker": "Host", "text": "With that said, does the crux of debate not lie in revenue recycling mechanisms rather than the tax itself?"},
            {"speaker": "Ms. Stein", "text": "Precisely. To that end, the opening statement of any climate finance bill should draw a clear distinction between revenue allocation models."}
        ],
        "vocabularyUsed": ["steel man", "devil's advocate", "nuanced position", "false dichotomy", "cherry-picking", "fallacious reasoning", "conversely", "confirmation bias", "categorical claim", "empirical evidence", "anecdotal evidence", "crux of debate", "with that said", "to that end", "opening statement", "draw a distinction"]
    },
    {
        "title": "Legal Moot Court: Ruling on the Motion",
        "titleArabic": "محكمة افتراضية: البت في الاقتراح",
        "setting": "A law school moot court session addressing procedural and substantive debate.",
        "lines": [
            {"speaker": "Judge", "text": "The respondent may now deliver the opening statement and rebut the applicant's primary claim."},
            {"speaker": "Counsel A", "text": "My Lord, we draw a distinction between procedural irregularity and substantive denial of rights. Our counter-argument rests on three pillars of constitutional law."},
            {"speaker": "Judge", "text": "The applicant's counsel, you may raise an objection when ready."},
            {"speaker": "Counsel B", "text": "I raise an objection to the characterization of the evidence. The argument commits begging the question by assuming the contested interpretation."},
            {"speaker": "Judge", "text": "Objection overruled. The floor speaker may continue. However, circular reasoning will not advance your case."},
            {"speaker": "Counsel A", "text": "Furthermore, the post hoc fallacy embedded in their submission confuses temporal correlation with legal causation."},
            {"speaker": "Counsel B", "text": "On the contrary, by reductio ad absurdum, their interpretation would negate every precedent established since 1948."},
            {"speaker": "Judge", "text": "After weighing the closing statement from both sides, we are ready to rule. The motion carried by majority ruling."}
        ],
        "vocabularyUsed": ["opening statement", "rebut claim", "draw a distinction", "counter-argument", "raise an objection", "overrule objection", "begging the question", "floor speaker", "circular reasoning", "post hoc fallacy", "on the contrary", "reductio ad absurdum", "closing statement", "motion carried"]
    }
]

paras_71 = [
    {
        "title": "Mastering Structured Debate: From Evidence to Conclusion",
        "titleArabic": "إتقان النقاش المنظم: من الدليل إلى الخلاصة",
        "text": "Effective participation in a formal debate requires more than passion; it demands the ability to present an argument built on empirical evidence while anticipating every counter-argument the opposition bench may raise. Skilled debaters always draw a distinction between sound analytical reasoning and fallacious reasoning, exposing any false premise buried within rival claims. When a panelist opens with an opening statement, careful moderators identify categorical claims requiring verification. By the same token, speakers representing the proposition side must refrain from cherry-picking statistics that commit confirmation bias, choosing instead to acknowledge nuanced positions that reflect reality.",
        "vocabularyUsed": ["formal debate", "present an argument", "empirical evidence", "counter-argument", "opposition bench", "draw a distinction", "fallacious reasoning", "false premise", "panelist", "opening statement", "categorical claim", "by the same token", "cherry-picking", "confirmation bias", "nuanced position", "proposition side"]
    },
    {
        "title": "Logical Fallacies and the Integrity of Public Discourse",
        "titleArabic": "المغالطات المنطقية ونزاهة الخطاب العام",
        "text": "Public discourse loses credibility when participants resort to rhetorical shortcuts rather than reasoned analysis. A false dichotomy constrains debate to two extreme positions when multiple policy options actually exist. Circular reasoning undermines credibility because the conclusion becomes part of the very premise being debated. The post hoc fallacy misleads audiences into believing sequential events prove causation. Similarly, sweeping claims based purely on anecdotal evidence, rather than systematic study, invite a reductio ad absurdum challenge. To that end, deliberative assemblies must champion the burden of proof as a shared civic standard.",
        "vocabularyUsed": ["false dichotomy", "circular reasoning", "post hoc fallacy", "sweeping claim", "anecdotal evidence", "reductio ad absurdum", "to that end", "deliberative assembly", "burden of proof"]
    },
    {
        "title": "Advanced Connectors: The Architecture of Persuasive Argument",
        "titleArabic": "روابط الخطاب المتقدمة: بنية الحجة الإقناعية",
        "text": "Advanced discourse connectors transform isolated sentences into compelling chains of reasoning. 'Conversely' signals a reversal of the preceding idea, while 'notwithstanding' introduces a concession without abandoning the main argument. When a floor speaker says 'on the contrary', they signal direct rebuttal of the prior claim. 'By extension' widens the logical scope of an established principle, and 'with that said' acknowledges a valid point before pivoting. Parliamentary procedure demands that every point of order and casting vote be recorded transparently. Mastering these connectors enables participants to rebut claim and speak with crux of debate clarity.",
        "vocabularyUsed": ["conversely", "notwithstanding", "floor speaker", "on the contrary", "rebut claim", "by extension", "with that said", "point of order", "casting vote", "parliamentary procedure", "crux of debate"]
    }
]

write_day(71, vocab_71, grammar_71, convs_71, paras_71)


# ==============================================================================
# DAY 72: News Around the World (World events and media)
# Grammar: ["Noun Clauses (that, what, whether)"]
# ==============================================================================
vocab_72 = [
    # News Reporting & Journalism Practice (17)
    {"headword": "breaking story", "pronunciation": "/ˈbreɪkɪŋ ˈstɔːri/", "partOfSpeech": "noun", "definition": "An urgent, developing news event of significant public importance being reported as it happens.", "example": "The newsroom scrambled to cover the breaking story of the earthquake in real time.", "translation": "خبر عاجل / قصة إخبارية متطورة ومستجدة", "collocations": ["cover a breaking story", "report on a breaking story"], "synonyms": ["developing story", "flash news"], "antonyms": ["old news"], "tags": ["journalism", "news"]},
    {"headword": "headline news", "pronunciation": "/ˈhedlaɪn njuːz/", "partOfSpeech": "noun", "definition": "The most important news stories featured prominently at the top of broadcasts or publications.", "example": "The prime minister's unexpected resignation dominated headline news globally for three days.", "translation": "أبرز الأخبار / عناوين النشرات الإخبارية الرئيسية", "collocations": ["make headline news", "dominate headline news"], "synonyms": ["top stories", "leading news"], "antonyms": ["minor report"], "tags": ["journalism", "broadcasting"]},
    {"headword": "on-the-ground reporting", "pronunciation": "/ɒn ðə ɡraʊnd rɪˈpɔːtɪŋ/", "partOfSpeech": "noun", "definition": "Journalism conducted directly from the physical location of an event rather than remotely.", "example": "On-the-ground reporting from the conflict zone revealed facts contradicting official statements.", "translation": "التغطية الميدانية المباشرة / الصحافة على أرض الواقع", "collocations": ["provide on-the-ground reporting", "rely on on-the-ground reporting"], "synonyms": ["field journalism"], "antonyms": ["desk reporting"], "tags": ["journalism", "field"]},
    {"headword": "embedded journalist", "pronunciation": "/ɪmˈbedɪd ˈdʒɜːnəlɪst/", "partOfSpeech": "noun", "definition": "A reporter who travels and lives with a military unit or organization to provide first-hand coverage.", "example": "The embedded journalist filed daily dispatches directly from the frontline positions.", "translation": "صحفي مدمج مع الوحدات العسكرية", "collocations": ["serve as embedded journalist", "allow an embedded journalist"], "synonyms": ["attached correspondent"], "antonyms": ["independent journalist"], "tags": ["journalism", "military"]},
    {"headword": "news conference", "pronunciation": "/njuːz ˈkɒnfrəns/", "partOfSpeech": "noun", "definition": "A formal meeting where an official or spokesperson addresses journalists and takes questions.", "example": "The health minister called an emergency news conference to address the outbreak.", "translation": "مؤتمر صحفي / جلسة استجواب الصحافة", "collocations": ["hold a news conference", "call a news conference"], "synonyms": ["press conference"], "antonyms": ["media silence"], "tags": ["journalism", "events"]},
    {"headword": "media blackout", "pronunciation": "/ˈmiːdiə ˈblækaʊt/", "partOfSpeech": "noun", "definition": "An intentional restriction or prohibition on publishing news about a specific event or topic.", "example": "Military authorities imposed a media blackout during the sensitive hostage negotiation.", "translation": "حظر إعلامي / تعتيم على الأخبار", "collocations": ["impose a media blackout", "lift a media blackout"], "synonyms": ["news blackout", "press ban"], "antonyms": ["full press access"], "tags": ["journalism", "censorship"]},
    {"headword": "press agent", "pronunciation": "/pres ˈeɪdʒənt/", "partOfSpeech": "noun", "definition": "A professional hired to manage and promote a public figure's media image.", "example": "The celebrity's press agent carefully orchestrated every public statement to manage her image.", "translation": "وكيل صحفي / مسؤول العلاقات الإعلامية لشخصية عامة", "collocations": ["hire a press agent", "consult with press agent"], "synonyms": ["publicist", "PR representative"], "antonyms": [], "tags": ["journalism", "PR"]},
    {"headword": "journalistic freedom", "pronunciation": "/ˌdʒɜːnəˈlɪstɪk ˈfriːdəm/", "partOfSpeech": "noun", "definition": "The right of journalists and media to report news without censorship or government interference.", "example": "Journalists worldwide marched to demand journalistic freedom and protection from prosecution.", "translation": "حرية الصحافة / استقلالية الإعلام عن القيود الحكومية", "collocations": ["defend journalistic freedom", "violate journalistic freedom"], "synonyms": ["press liberty"], "antonyms": ["media censorship"], "tags": ["rights", "journalism"]},
    {"headword": "editorial slant", "pronunciation": "/ˌedɪˈtɔːriəl slænt/", "partOfSpeech": "noun", "definition": "The ideological or political bias reflected in a news outlet's editorial choices.", "example": "The newspaper's editorial slant favoured market-based healthcare solutions consistently.", "translation": "التوجه التحريري / الانحياز السياسي في الخط التحريري", "collocations": ["identify editorial slant", "editorial slant toward"], "synonyms": ["editorial bias", "ideological leaning"], "antonyms": ["editorial neutrality"], "tags": ["journalism", "media-bias"]},
    {"headword": "sensationalism", "pronunciation": "/senˈseɪʃənəlɪzəm/", "partOfSpeech": "noun", "definition": "The deliberate exaggeration or dramatization of news to provoke excitement or emotional reaction.", "example": "Critics condemned the network for sensationalism in its coverage of the kidnapping case.", "translation": "الإثارة والتهويل الإعلامي / الإفراط في الإبهار", "collocations": ["resort to sensationalism", "accuse of sensationalism"], "synonyms": ["tabloid journalism", "yellow journalism"], "antonyms": ["sober reporting"], "tags": ["journalism", "ethics"]},
    {"headword": "fact-checker", "pronunciation": "/ˈfækt ˌtʃekə/", "partOfSpeech": "noun", "definition": "A professional who verifies the accuracy of statements, claims, and stories before publication.", "example": "The editorial team employed a dedicated fact-checker to verify every statistic in the report.", "translation": "مدقق الحقائق / المختص بالتحقق من صحة المعلومات", "collocations": ["employ a fact-checker", "fact-checker confirms"], "synonyms": ["verifier", "accuracy checker"], "antonyms": [], "tags": ["journalism", "accuracy"]},
    {"headword": "source verification", "pronunciation": "/sɔːs ˌverɪfɪˈkeɪʃn/", "partOfSpeech": "noun", "definition": "The rigorous process of confirming the credibility and accuracy of an information source.", "example": "Source verification is a fundamental ethical obligation for any responsible journalist.", "translation": "التحقق من مصداقية المصادر الإخبارية", "collocations": ["require source verification", "undergo source verification"], "synonyms": ["source authentication"], "antonyms": ["unverified publication"], "tags": ["journalism", "ethics"]},
    {"headword": "background briefing", "pronunciation": "/ˈbækɡraʊnd ˈbriːfɪŋ/", "partOfSpeech": "noun", "definition": "Information provided to journalists to contextualize a story that cannot be directly attributed.", "example": "Officials gave a background briefing to help reporters understand the diplomatic complexity.", "translation": "إحاطة خلفية / معلومات تمهيدية غير منسوبة للمصدر", "collocations": ["receive a background briefing", "conduct a background briefing"], "synonyms": ["background information session"], "antonyms": ["on-record statement"], "tags": ["journalism", "sources"]},
    {"headword": "exclusive scoop", "pronunciation": "/ɪkˈskluːsɪv skuːp/", "partOfSpeech": "noun", "definition": "A news story that a single journalist or outlet publishes before all other competitors.", "example": "The investigative reporter secured an exclusive scoop on the government's secret surveillance program.", "translation": "الانفراد الصحفي / قصة وحيدة تنشرها جهة إعلامية قبل غيرها", "collocations": ["land an exclusive scoop", "publish an exclusive scoop"], "synonyms": ["exclusive story", "news exclusive"], "antonyms": ["widely reported story"], "tags": ["journalism", "competition"]},
    {"headword": "news feed", "pronunciation": "/njuːz fiːd/", "partOfSpeech": "noun", "definition": "A continuously updated stream of news headlines or stories delivered digitally.", "example": "She refreshed her news feed compulsively during the election results night.", "translation": "تغذية إخبارية / تدفق مستمر للأخبار على الإنترنت", "collocations": ["scroll the news feed", "curate a news feed"], "synonyms": ["news stream", "headline feed"], "antonyms": [], "tags": ["digital", "media"]},
    {"headword": "news syndicate", "pronunciation": "/njuːz ˈsɪndɪkɪt/", "partOfSpeech": "noun", "definition": "An agency that distributes content, articles, or news to multiple subscribing media outlets.", "example": "The article was distributed internationally through a major news syndicate.", "translation": "وكالة توزيع إخبارية / تكتل إعلامي ناشر", "collocations": ["distribute through a news syndicate", "major news syndicate"], "synonyms": ["wire agency", "press association"], "antonyms": [], "tags": ["journalism", "distribution"]},
    {"headword": "press corps", "pronunciation": "/pres kɔː/", "partOfSpeech": "noun", "definition": "The collective body of journalists assigned to cover a specific institution or geographic area.", "example": "The White House press corps gathered daily for the afternoon briefing with senior officials.", "translation": "هيئة الصحافة / مجموعة الصحفيين المعتمدين لتغطية مؤسسة بعينها", "collocations": ["briefing the press corps", "accredited press corps"], "synonyms": ["press pool", "media corps"], "antonyms": [], "tags": ["journalism", "institutions"]},

    # Newsroom Standards & Digital Media (16)
    {"headword": "foreign correspondent", "pronunciation": "/ˈfɒrən ˌkɒrɪˈspɒndənt/", "partOfSpeech": "noun", "definition": "A journalist stationed abroad to report on international events for a home-country outlet.", "example": "The foreign correspondent filed dispatches from three conflict zones within a single month.", "translation": "مراسل أجنبي / صحفي معتمد في الخارج", "collocations": ["veteran foreign correspondent", "assign a foreign correspondent"], "synonyms": ["international reporter"], "antonyms": ["domestic reporter"], "tags": ["journalism", "international"]},
    {"headword": "bureau chief", "pronunciation": "/ˈbjʊərəʊ tʃiːf/", "partOfSpeech": "noun", "definition": "The senior journalist who leads a news organization's regional or overseas bureau.", "example": "The Cairo bureau chief coordinated coverage of the regional summit.", "translation": "رئيس المكتب الإعلامي / مدير الفرع الصحفي الإقليمي", "collocations": ["appoint a bureau chief", "work under the bureau chief"], "synonyms": ["regional news director"], "antonyms": [], "tags": ["journalism", "management"]},
    {"headword": "photo essay", "pronunciation": "/ˈfəʊtəʊ ˈeseɪ/", "partOfSpeech": "noun", "definition": "A curated series of photographs that collectively tell a narrative or document an event.", "example": "The photographer's haunting photo essay on refugee camps won international acclaim.", "translation": "مقالة فوتوغرافية / تحقيق بالصور المتسلسلة", "collocations": ["publish a photo essay", "compelling photo essay"], "synonyms": ["photographic reportage"], "antonyms": ["text-only report"], "tags": ["journalism", "photography"]},
    {"headword": "citizen journalism", "pronunciation": "/ˈsɪtɪzn ˈdʒɜːnəlɪzəm/", "partOfSpeech": "noun", "definition": "News gathering and reporting by ordinary members of the public using smartphones and social media.", "example": "Citizen journalism during the street protests provided footage that mainstream media lacked.", "translation": "الصحافة الشعبية / التغطية الإخبارية من المواطنين", "collocations": ["rise of citizen journalism", "enabled by citizen journalism"], "synonyms": ["participatory journalism"], "antonyms": ["professional journalism"], "tags": ["digital", "journalism"]},
    {"headword": "first-hand account", "pronunciation": "/ˌfɜːst ˈhænd əˈkaʊnt/", "partOfSpeech": "noun", "definition": "A personal testimony from someone who directly experienced or witnessed an event.", "example": "Survivors provided first-hand accounts that challenged the government's official narrative.", "translation": "رواية مباشرة / شهادة من شاهد أو عايش الحدث مباشرة", "collocations": ["obtain a first-hand account", "publish a first-hand account"], "synonyms": ["direct testimony"], "antonyms": ["secondhand report"], "tags": ["journalism", "witnesses"]},
    {"headword": "official communique", "pronunciation": "/əˈfɪʃl kəˈmjuːnɪkeɪ/", "partOfSpeech": "noun", "definition": "A formal, official communication or statement released by a government or organization.", "example": "The joint official communique confirmed the ceasefire agreement signed by both nations.", "translation": "البيان الرسمي / البلاغ الحكومي أو المؤسسي", "collocations": ["issue an official communique", "read the official communique"], "synonyms": ["official statement", "formal dispatch"], "antonyms": ["unofficial leak"], "tags": ["politics", "journalism"]},
    {"headword": "press release", "pronunciation": "/pres rɪˈliːs/", "partOfSpeech": "noun", "definition": "An official written statement distributed to journalists to announce news or policy.", "example": "The corporation issued a press release denying the merger rumours circulating on social media.", "translation": "بيان صحفي / إعلان رسمي موزع على وسائل الإعلام", "collocations": ["issue a press release", "draft a press release"], "synonyms": ["media statement"], "antonyms": [], "tags": ["journalism", "PR"]},
    {"headword": "news aggregator", "pronunciation": "/njuːz ˈæɡrɪɡeɪtə/", "partOfSpeech": "noun", "definition": "A digital platform that collects and displays news content from multiple sources in one place.", "example": "Many users rely on a news aggregator rather than visiting individual news websites.", "translation": "جامع الأخبار / منصة رقمية تجمع الأخبار من مصادر متعددة", "collocations": ["popular news aggregator", "use a news aggregator"], "synonyms": ["news portal", "feed reader"], "antonyms": ["single-source outlet"], "tags": ["digital", "technology"]},
    {"headword": "digital newsroom", "pronunciation": "/ˈdɪdʒɪtl ˈnjuːzruːm/", "partOfSpeech": "noun", "definition": "A fully online editorial operation producing and distributing content across digital platforms.", "example": "The digital newsroom operates twenty-four hours a day with reporters across five continents.", "translation": "غرفة الأخبار الرقمية / التحرير الإخباري الإلكتروني المتكامل", "collocations": ["run a digital newsroom", "launch a digital newsroom"], "synonyms": ["online newsroom"], "antonyms": ["print newsroom"], "tags": ["digital", "journalism"]},
    {"headword": "paparazzi", "pronunciation": "/ˌpæpəˈrætsi/", "partOfSpeech": "noun", "definition": "Freelance photographers who aggressively pursue celebrities to capture candid photographs.", "example": "A swarm of paparazzi surrounded the actress as she exited the awards ceremony.", "translation": "المصورون الصحفيون المتعقبون للمشاهير / المحترفون بتصوير النجوم", "collocations": ["mobbed by paparazzi", "dodging paparazzi"], "synonyms": ["celebrity photographers"], "antonyms": [], "tags": ["journalism", "celebrity"]},
    {"headword": "tabloid journalism", "pronunciation": "/ˈtæblɔɪd ˈdʒɜːnəlɪzəm/", "partOfSpeech": "noun", "definition": "A style of journalism emphasizing sensational, celebrity, and crime stories over serious news.", "example": "Critics argued that tabloid journalism had undermined public trust in all media.", "translation": "صحافة التابلويد / صحافة الإثارة والفضائح والجرائم", "collocations": ["resort to tabloid journalism", "criticized as tabloid journalism"], "synonyms": ["yellow press", "gossip journalism"], "antonyms": ["quality journalism"], "tags": ["journalism", "ethics"]},
    {"headword": "quality newspaper", "pronunciation": "/ˈkwɒlɪti ˈnjuːzˌpeɪpə/", "partOfSpeech": "noun", "definition": "A serious, broadsheet-format newspaper prioritizing in-depth reporting over sensationalism.", "example": "The quality newspaper won three press awards for its investigative refugee coverage.", "translation": "الصحيفة الجادة الرصينة / الصحيفة ذات المحتوى الرفيع", "collocations": ["read a quality newspaper", "publish in a quality newspaper"], "synonyms": ["serious newspaper", "broadsheet"], "antonyms": ["tabloid"], "tags": ["journalism", "media"]},
    {"headword": "investigative piece", "pronunciation": "/ɪnˈvestɪɡətɪv piːs/", "partOfSpeech": "noun", "definition": "An in-depth, original journalistic report uncovering hidden facts through research and interviews.", "example": "The investigative piece exposed systemic corruption within the city's housing authority.", "translation": "التقرير الاستقصائي المعمّق / قطعة صحفية تكشف حقائق مخفية", "collocations": ["publish an investigative piece", "major investigative piece"], "synonyms": ["investigative report"], "antonyms": ["press release"], "tags": ["journalism", "investigation"]},
    {"headword": "whistleblower protection", "pronunciation": "/ˈwɪslbləʊə prəˈtekʃn/", "partOfSpeech": "noun", "definition": "Legal safeguards preventing retaliation against individuals who expose wrongdoing publicly.", "example": "Stronger whistleblower protection laws encouraged insiders to report financial irregularities.", "translation": "حماية المبلغين عن الفساد / الضمانات القانونية للمُبلِّغين", "collocations": ["enact whistleblower protection", "lack whistleblower protection"], "synonyms": ["informant safeguards"], "antonyms": ["persecution of sources"], "tags": ["legal", "journalism"]},
    {"headword": "news embargo", "pronunciation": "/njuːz ɪmˈbɑːɡəʊ/", "partOfSpeech": "noun", "definition": "A formal instruction to journalists not to publish information until a specified release time.", "example": "The scientific journal placed a strict news embargo until midnight on publication date.", "translation": "الحظر الإخباري المؤقت / التعهد بعدم النشر قبل الموعد المحدد", "collocations": ["honour a news embargo", "break a news embargo"], "synonyms": ["release restriction"], "antonyms": ["immediate publication"], "tags": ["journalism", "procedure"]},
    {"headword": "retraction notice", "pronunciation": "/rɪˈtrækʃn ˈnəʊtɪs/", "partOfSpeech": "noun", "definition": "A formal public withdrawal of a previously published article or claim found to be inaccurate.", "example": "The magazine issued a prominent retraction notice after the story's key source was found unreliable.", "translation": "إشعار التراجع والتكذيب / إعلان سحب مادة صحفية خاطئة", "collocations": ["publish a retraction notice", "demand a retraction notice"], "synonyms": ["retraction statement"], "antonyms": ["confirmation"], "tags": ["journalism", "accuracy"]},

    # Media Ethics, Accountability & Influence (17)
    {"headword": "correction published", "pronunciation": "/kəˈrekʃn ˈpʌblɪʃt/", "partOfSpeech": "noun", "definition": "A publicly printed acknowledgment and amendment of an error in a previous report.", "example": "Following the complaint, the outlet printed a correction published on the front page.", "translation": "نشر تصحيح / إصلاح رسمي لخطأ صحفي منشور سابقاً", "collocations": ["issue a correction published", "run correction published"], "synonyms": ["error correction"], "antonyms": ["unchanged publication"], "tags": ["journalism", "ethics"]},
    {"headword": "journalistic integrity", "pronunciation": "/ˌdʒɜːnəˈlɪstɪk ɪnˈteɡrɪti/", "partOfSpeech": "noun", "definition": "The adherence to ethical standards of accuracy, fairness, and independence in journalism.", "example": "The editor insisted that journalistic integrity must never be compromised for commercial interests.", "translation": "النزاهة الصحفية / الالتزام الأخلاقي في العمل الإعلامي", "collocations": ["uphold journalistic integrity", "question journalistic integrity"], "synonyms": ["press ethics"], "antonyms": ["yellow journalism"], "tags": ["ethics", "journalism"]},
    {"headword": "named source", "pronunciation": "/neɪmd sɔːs/", "partOfSpeech": "noun", "definition": "An information provider who is identified by name in a published news report.", "example": "The investigation carried significant weight because every claim came from a named source.", "translation": "مصدر إخباري مُسمّى / مصدر مُعلن عن هويته في المقال", "collocations": ["quote a named source", "rely on named source"], "synonyms": ["identified source"], "antonyms": ["anonymous source"], "tags": ["journalism", "sources"]},
    {"headword": "attributed quote", "pronunciation": "/əˈtrɪbjuːtɪd kwəʊt/", "partOfSpeech": "noun", "definition": "A statement clearly credited to a specific speaker in a published report.", "example": "Every attributed quote in the profile was recorded verbatim and approved by the subject.", "translation": "اقتباس منسوب لصاحبه / تصريح موثق ومنسوب رسمياً", "collocations": ["include an attributed quote", "verify an attributed quote"], "synonyms": ["direct quotation"], "antonyms": ["paraphrase", "anonymous tip"], "tags": ["journalism", "writing"]},
    {"headword": "unverified claim", "pronunciation": "/ˌʌnˈverɪfaɪd kleɪm/", "partOfSpeech": "noun", "definition": "An assertion that has not been independently confirmed or cross-checked by reliable sources.", "example": "Responsible journalists do not broadcast an unverified claim, regardless of competitive pressure.", "translation": "ادعاء غير موثق / معلومة لم يُتحقق منها بعد", "collocations": ["spread an unverified claim", "repeat an unverified claim"], "synonyms": ["unconfirmed report"], "antonyms": ["verified fact"], "tags": ["journalism", "accuracy"]},
    {"headword": "clickbait headline", "pronunciation": "/ˈklɪkbeɪt ˈhedlaɪn/", "partOfSpeech": "noun", "definition": "A deliberately provocative or misleading title designed to attract clicks rather than inform.", "example": "The clickbait headline generated enormous traffic but undermined the outlet's journalistic credibility.", "translation": "عنوان استدراجي / عنوان صُمم لاستجلاب النقرات بدلاً من الإخبار الحقيقي", "collocations": ["publish a clickbait headline", "avoid clickbait headlines"], "synonyms": ["bait headline"], "antonyms": ["accurate headline"], "tags": ["digital", "ethics"]},
    {"headword": "news cycle", "pronunciation": "/njuːz ˈsaɪkl/", "partOfSpeech": "noun", "definition": "The recurring period during which a news story is prominently covered before attention moves elsewhere.", "example": "Political strategists timed announcements carefully to dominate the news cycle for forty-eight hours.", "translation": "الدورة الإخبارية / الفترة التي يبقى فيها الخبر في الواجهة", "collocations": ["dominate the news cycle", "control the news cycle"], "synonyms": ["media cycle"], "antonyms": [], "tags": ["media", "strategy"]},
    {"headword": "round-the-clock news", "pronunciation": "/raʊnd ðə klɒk njuːz/", "partOfSpeech": "noun", "definition": "Continuous twenty-four-hour news broadcasting without interruption.", "example": "Round-the-clock news coverage intensified public anxiety during the pandemic's first wave.", "translation": "الأخبار على مدار الساعة / التغطية الإخبارية المستمرة", "collocations": ["provide round-the-clock news", "rely on round-the-clock news"], "synonyms": ["24/7 news", "continuous news"], "antonyms": ["scheduled bulletin"], "tags": ["broadcasting", "media"]},
    {"headword": "opinion columnist", "pronunciation": "/əˈpɪnjən ˈkɒləmnɪst/", "partOfSpeech": "noun", "definition": "A journalist who writes regular opinion articles expressing personal views.", "example": "The opinion columnist sparked controversy by advocating capital punishment for financial crimes.", "translation": "كاتب العمود الرأي / الصحفي المعتمد على التعليق وإبداء الرأي", "collocations": ["veteran opinion columnist", "syndicated opinion columnist"], "synonyms": ["commentator", "op-ed writer"], "antonyms": ["news reporter"], "tags": ["journalism", "opinion"]},
    {"headword": "editorial independence", "pronunciation": "/ˌedɪˈtɔːriəl ˌɪndɪˈpendəns/", "partOfSpeech": "noun", "definition": "The freedom of an editorial team to make publishing decisions without owner or advertiser pressure.", "example": "The broadcasting charter legally guaranteed editorial independence from government interference.", "translation": "الاستقلالية التحريرية / حرية التحرير من تدخل الملاك أو المعلنين", "collocations": ["protect editorial independence", "undermine editorial independence"], "synonyms": ["journalistic autonomy"], "antonyms": ["editorial interference"], "tags": ["journalism", "governance"]},
    {"headword": "public broadcaster", "pronunciation": "/ˈpʌblɪk ˈbrɔːdkɑːstə/", "partOfSpeech": "noun", "definition": "A media organization funded by the government or license fees to serve the public interest.", "example": "The public broadcaster is required by law to offer balanced representation of political perspectives.", "translation": "المُذيع العام / المؤسسة الإعلامية الممولة من الحكومة لخدمة الصالح العام", "collocations": ["national public broadcaster", "fund the public broadcaster"], "synonyms": ["state broadcaster"], "antonyms": ["commercial broadcaster"], "tags": ["media", "governance"]},
    {"headword": "state-controlled media", "pronunciation": "/steɪt kənˈtrəʊld ˈmiːdiə/", "partOfSpeech": "noun", "definition": "News organizations that are owned, managed, or directed by a national government.", "example": "Reports from state-controlled media were viewed skeptically by international observers.", "translation": "وسائل إعلام تحت السيطرة الحكومية / إعلام الدولة", "collocations": ["rely on state-controlled media", "criticize state-controlled media"], "synonyms": ["government-owned media"], "antonyms": ["independent press"], "tags": ["media", "politics"]},
    {"headword": "independent press", "pronunciation": "/ˌɪndɪˈpendənt pres/", "partOfSpeech": "noun", "definition": "Media outlets that operate free from government or corporate ownership control.", "example": "Civil society organizations raised funds to sustain an independent press in the region.", "translation": "الصحافة المستقلة / الإعلام غير المرتبط بالحكومة أو الشركات الكبرى", "collocations": ["support independent press", "build independent press"], "synonyms": ["free press"], "antonyms": ["state-controlled media"], "tags": ["journalism", "freedom"]},
    {"headword": "watchdog journalism", "pronunciation": "/ˈwɒtʃdɒɡ ˈdʒɜːnəlɪzəm/", "partOfSpeech": "noun", "definition": "Reporting that monitors, investigates, and exposes abuse of power by public officials.", "example": "Watchdog journalism is widely credited with exposing the corporate accounting scandal.", "translation": "صحافة الرقابة على السلطة / صحافة حراسة المال العام والديمقراطية", "collocations": ["practice watchdog journalism", "award for watchdog journalism"], "synonyms": ["accountability journalism"], "antonyms": ["propaganda"], "tags": ["journalism", "accountability"]},
    {"headword": "press accreditation", "pronunciation": "/pres əˌkredɪˈteɪʃn/", "partOfSpeech": "noun", "definition": "Official certification granting a journalist access to cover specific events or institutions.", "example": "Without press accreditation, reporters could not enter the restricted summit conference hall.", "translation": "الاعتماد الصحفي / الشهادة الرسمية لتغطية الفعاليات المحمية", "collocations": ["grant press accreditation", "apply for press accreditation"], "synonyms": ["press credentials"], "antonyms": ["denied access"], "tags": ["journalism", "access"]},
    {"headword": "news framing", "pronunciation": "/njuːz ˈfreɪmɪŋ/", "partOfSpeech": "noun", "definition": "The way news stories are presented, emphasizing certain aspects to influence audience perception.", "example": "Researchers studied news framing of immigration to reveal systematic media stereotyping.", "translation": "إطار تأطير الأخبار / كيفية تقديم الأحداث لتوجيه رأي الجمهور", "collocations": ["analyze news framing", "study news framing"], "synonyms": ["media framing", "story angle"], "antonyms": ["neutral reporting"], "tags": ["media", "theory"]},
    {"headword": "misinformation campaign", "pronunciation": "/ˌmɪsɪnfəˈmeɪʃn kæmˈpeɪn/", "partOfSpeech": "noun", "definition": "An organized effort to spread false or misleading information to manipulate public opinion.", "example": "Social media platforms struggled to contain the coordinated misinformation campaign during elections.", "translation": "حملة التضليل والأخبار الكاذبة / حملة منظمة لنشر المعلومات المزيفة", "collocations": ["launch a misinformation campaign", "counter a misinformation campaign"], "synonyms": ["disinformation drive"], "antonyms": ["fact-based campaign"], "tags": ["media", "manipulation"]}
]

grammar_72 = [
    {
        "title": "Noun Clauses (that, what, whether)",
        "explanation": "Noun clauses function as subjects, objects, or complements within a sentence. They often replace simple nouns and add complexity to reporting and describing knowledge. (1) 'That' clauses: 'Journalists reported that the minister had resigned.' (2) 'What' clauses (free relatives): 'What the fact-checker discovered shocked the editorial board.' (3) 'Whether/if' clauses for indirect questions and uncertainty: 'We do not know whether the story is verified.' Key patterns with reporting verbs: report, confirm, reveal, announce, deny, discover, believe + that/what/whether. In news language, noun clauses are essential for citing sources, reporting speech, and expressing editorial stance.",
        "structures": [
            {"pattern": "Subject + reporting verb + that + Subject + Verb (Indirect statement)"},
            {"pattern": "What + Subject + Verb + is/was (What-clause as subject or object)"},
            {"pattern": "Subject + Verb + whether/if + Subject + Verb (Indirect yes/no question)"}
        ],
        "examples": [
            {
                "sentence": "The fact-checker confirmed that the clickbait headline had misrepresented the research findings.",
                "arabic": "أكد مدقق الحقائق أن العنوان الاستدراجي قد أساء تمثيل نتائج البحث.",
                "usesVocabulary": ["fact-checker", "clickbait headline"]
            },
            {
                "sentence": "What the investigative piece revealed was that the bureau chief had suppressed the exclusive scoop.",
                "arabic": "ما كشفه التقرير الاستقصائي هو أن رئيس المكتب قد أخفى الانفراد الصحفي.",
                "usesVocabulary": ["investigative piece", "bureau chief", "exclusive scoop"]
            },
            {
                "sentence": "Citizens questioned whether the public broadcaster had maintained its editorial independence.",
                "arabic": "تساءل المواطنون عما إذا كان المذيع العام قد حافظ على استقلاليته التحريرية.",
                "usesVocabulary": ["public broadcaster", "editorial independence"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "The press corps reported what did the minister say about the media blackout.",
                "right": "The press corps reported what the minister said about the media blackout.",
                "explanation": "In a noun clause introduced by 'what', use statement word order (Subject + Verb), not question order."
            },
            {
                "wrong": "We do not know that the story is verified or not.",
                "right": "We do not know whether the story is verified or not.",
                "explanation": "Use 'whether' (not 'that') when there is an implicit 'or not' or a yes/no uncertainty."
            }
        ]
    }
]

convs_72 = [
    {
        "title": "Breaking Story: Covering the Crisis",
        "titleArabic": "التغطية الميدانية: قصة خبرية عاجلة",
        "setting": "A news director and an embedded journalist discuss coverage of a breaking story.",
        "lines": [
            {"speaker": "Director", "text": "I can confirm that we have a breaking story developing at the northern border. The embedded journalist reported that shots were fired near the checkpoint."},
            {"speaker": "Correspondent", "text": "I obtained a first-hand account from a named source confirming that the media blackout was imposed three hours ago."},
            {"speaker": "Director", "text": "Whether the official communique contradicts these reports is what our fact-checker is investigating right now."},
            {"speaker": "Correspondent", "text": "The foreign correspondent from the eastern bureau said that on-the-ground reporting is being obstructed by military authorities."},
            {"speaker": "Director", "text": "The press corps is demanding accreditation. We cannot broadcast any unverified claim under our journalistic integrity standards."},
            {"speaker": "Correspondent", "text": "What the witness told me directly was that state-controlled media is framing this as a training exercise."},
            {"speaker": "Director", "text": "Publish a correction notice if needed, but only after source verification. Citizens must know what happened."},
            {"speaker": "Correspondent", "text": "Understood. I will send the full report through the news syndicate by nineteen hundred hours."}
        ],
        "vocabularyUsed": ["breaking story", "embedded journalist", "first-hand account", "named source", "media blackout", "official communique", "fact-checker", "foreign correspondent", "on-the-ground reporting", "press corps", "press accreditation", "unverified claim", "journalistic integrity", "state-controlled media", "news framing", "source verification", "news syndicate"]
    },
    {
        "title": "Editorial Meeting: Standards Under Pressure",
        "titleArabic": "اجتماع تحريري: صمود الأخلاقيات تحت الضغط",
        "setting": "An editor-in-chief chairs a digital newsroom editorial meeting about an investigative piece.",
        "lines": [
            {"speaker": "Editor", "text": "Our fact-checker confirmed that the attribution was wrong. We need a retraction notice published by midday."},
            {"speaker": "Reporter A", "text": "What bothers me is whether the clickbait headline alone destroyed the credibility of an otherwise accurate investigative piece."},
            {"speaker": "Editor", "text": "The opinion columnist argued that sensationalism in the headline framing undermined our editorial independence."},
            {"speaker": "Reporter B", "text": "I believe that watchdog journalism must never compromise on source verification, even under news cycle pressure."},
            {"speaker": "Editor", "text": "Agreed. Whether we publish tonight or tomorrow, I must know that every attributed quote is fully verified."},
            {"speaker": "Reporter A", "text": "The bureau chief asked whether the whistleblower protection clause covers our named source adequately."},
            {"speaker": "Editor", "text": "Confirm that it does before we publish. The independent press cannot afford legal exposure now."},
            {"speaker": "Reporter B", "text": "Noted. I will also check whether the news embargo on the parliamentary documents expired at midnight."}
        ],
        "vocabularyUsed": ["fact-checker", "retraction notice", "clickbait headline", "investigative piece", "editorial independence", "journalistic integrity", "sensationalism", "watchdog journalism", "source verification", "news cycle", "attributed quote", "whistleblower protection", "named source", "independent press", "news embargo", "bureau chief"]
    },
    {
        "title": "Media Literacy Seminar: Navigating Digital News",
        "titleArabic": "ندوة محو الأمية الإعلامية: الإبحار في عالم الأخبار الرقمية",
        "setting": "A journalism professor and a student discuss how audiences engage with digital news.",
        "lines": [
            {"speaker": "Professor", "text": "Research confirms that what most audiences see first is a clickbait headline, not the actual news content."},
            {"speaker": "Student", "text": "Does that mean that citizen journalism and news aggregators are fundamentally changing how people consume news?"},
            {"speaker": "Professor", "text": "Exactly. What the data shows is that misinformation campaigns spread six times faster through social media news feeds."},
            {"speaker": "Student", "text": "I wondered whether round-the-clock news coverage actually increases anxiety without improving understanding."},
            {"speaker": "Professor", "text": "That is a key question. Whether a public broadcaster or state-controlled media frames a story determines what citizens believe."},
            {"speaker": "Student", "text": "So the news framing and editorial slant of a quality newspaper differ significantly from tabloid journalism?"},
            {"speaker": "Professor", "text": "Precisely. A photo essay in a quality newspaper can reveal what a press release deliberately conceals."},
            {"speaker": "Student", "text": "This confirms that journalistic freedom and editorial independence remain essential for a functioning democracy."}
        ],
        "vocabularyUsed": ["clickbait headline", "citizen journalism", "news aggregator", "misinformation campaign", "news feed", "round-the-clock news", "public broadcaster", "state-controlled media", "news framing", "editorial slant", "quality newspaper", "tabloid journalism", "photo essay", "press release", "journalistic freedom", "editorial independence"]
    }
]

paras_72 = [
    {
        "title": "The Evolving Ecosystem of Global News Reporting",
        "titleArabic": "النظام البيئي المتطور للتغطية الإخبارية العالمية",
        "text": "The modern newsroom operates in a dramatically transformed landscape where breaking story coverage demands speed, and where embedded journalist dispatches compete with citizen journalism posts appearing seconds after events occur. A bureau chief must now decide whether first-hand accounts or official communiques should guide editorial strategy. Every investigative piece benefits from rigorous source verification, ensuring that no unverified claim reaches the public. The rise of the news aggregator means that a clickbait headline can mislead millions before the fact-checker even begins reviewing the published report.",
        "vocabularyUsed": ["breaking story", "embedded journalist", "citizen journalism", "bureau chief", "first-hand account", "official communique", "investigative piece", "source verification", "unverified claim", "news aggregator", "clickbait headline", "fact-checker"]
    },
    {
        "title": "Media Ethics: Upholding Journalistic Integrity in a Polarized World",
        "titleArabic": "أخلاقيات الإعلام: الحفاظ على النزاهة الصحفية في عالم منقسم",
        "text": "What distinguishes quality journalism from tabloid journalism is fundamentally the commitment to journalistic integrity. Responsible editorial boards insist that every attributed quote carries a named source, and that retraction notices are published promptly whenever errors occur. Watchdog journalism has uncovered evidence confirming that state-controlled media suppresses news framing that contradicts government narratives. Independent press organizations champion editorial independence and journalistic freedom, recognizing that whether a story is reported fairly often determines whether citizens trust their institutions.",
        "vocabularyUsed": ["quality newspaper", "tabloid journalism", "journalistic integrity", "attributed quote", "named source", "retraction notice", "watchdog journalism", "state-controlled media", "news framing", "independent press", "editorial independence", "journalistic freedom"]
    },
    {
        "title": "Digital Media and the Battle Against Misinformation",
        "titleArabic": "الإعلام الرقمي ومعركة مكافحة التضليل الإعلامي",
        "text": "Combating a coordinated misinformation campaign requires cooperation between fact-checkers, public broadcasters, and digital newsrooms. What researchers discovered is that round-the-clock news coverage accelerates the spread of unverified claims before corrections reach affected audiences. News embargoes protect sensitive diplomatic negotiations, while whistleblower protection laws ensure insiders can speak truthfully without fear. Foreign correspondents conducting on-the-ground reporting provide context that press releases and news conferences cannot, reinforcing the irreplaceable value of direct, independent reporting for an informed citizenry.",
        "vocabularyUsed": ["misinformation campaign", "fact-checker", "public broadcaster", "digital newsroom", "round-the-clock news", "unverified claim", "news embargo", "whistleblower protection", "foreign correspondent", "on-the-ground reporting", "press release", "news conference"]
    }
]

write_day(72, vocab_72, grammar_72, convs_72, paras_72)

print("Day 71 and Day 72 written successfully.")
