# -*- coding: utf-8 -*-
"""Generate Day 83 and Day 84 for Stage 9."""

import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from curriculum_engine import write_day

# ==============================================================================
# DAY 83: People Who Shaped Me (Influential people and memories)
# Grammar: Relative Clauses + Narrative Tenses
# ==============================================================================

vocab_83 = [
    # Mentors, Role Models & Guiding Influences
    {"headword": "formative mentor", "pronunciation": "/ˈfɔːmətɪv ˈmentɔː/", "partOfSpeech": "noun", "definition": "An experienced advisor whose guidance profoundly shapes a person's early development and character.", "example": "Her high school biology teacher was a formative mentor who sparked her passion for genetic research.", "translation": "مرشد وموجّه تكويني شكّل الشخصية في الصغر", "collocations": ["act as a formative mentor", "role of a formative mentor"], "synonyms": ["foundational guide"], "antonyms": [], "tags": ["mentorship", "relationships"]},
    {"headword": "guiding light", "pronunciation": "/ˈɡaɪdɪŋ laɪt/", "partOfSpeech": "noun", "definition": "A person whose moral principles, wisdom, and example illuminate the right path for others.", "example": "Throughout difficult corporate transitions, our grandmother remained the spiritual guiding light of our family.", "translation": "النبراس والمنارة الهادية في الحياة", "collocations": ["serve as a guiding light", "family guiding light"], "synonyms": ["beacon", "moral guide"], "antonyms": [], "tags": ["inspiration", "family"]},
    {"headword": "role model figure", "pronunciation": "/rəʊl ˈmɒdl ˈfɪɡə/", "partOfSpeech": "noun", "definition": "A respected person whose behavior, achievements, and ethics serve as an example for others to emulate.", "example": "Dr. Sarah Gilbert became an inspiring role model figure for young female scientists globally.", "translation": "شخصية القدوة والنموذج المحتذى به", "collocations": ["positive role model figure", "admire as a role model figure"], "synonyms": ["exemplar"], "antonyms": ["bad influence"], "tags": ["leadership", "inspiration"]},
    {"headword": "inspiring teacher", "pronunciation": "/ɪnˈspaɪərɪŋ ˈtiːtʃə/", "partOfSpeech": "noun", "definition": "An educator whose enthusiasm, dedication, and pedagogical excellence awaken latent talents in students.", "example": "Every writer remembers at least one inspiring teacher who praised their early creative voice.", "translation": "المعلم الملهم الذي يوقظ شغف المعرفة", "collocations": ["blessed with an inspiring teacher", "unforgettable inspiring teacher"], "synonyms": ["dedicated educator"], "antonyms": [], "tags": ["education", "inspiration"]},
    {"headword": "childhood companion", "pronunciation": "/ˈtʃaɪldhʊd kəmˈpænjən/", "partOfSpeech": "noun", "definition": "A peer with whom one shared deep play, school memories, and emotional bonding during early youth.", "example": "Reuniting with my childhood companion thirty years later felt as though no time had passed.", "translation": "رفيق الطفولة والصبا المقرب", "collocations": ["lifelong childhood companion", "cherished childhood companion"], "synonyms": ["early friend"], "antonyms": [], "tags": ["friendship", "memories"]},
    {"headword": "fatherly wisdom", "pronunciation": "/ˈfɑːðəli ˈwɪzdəm/", "partOfSpeech": "noun", "definition": "Wise, compassionate, and practical advice given by a father or paternal figure.", "example": "His fatherly wisdom regarding financial discipline saved me from reckless debt during my university years.", "translation": "الحكمة الأبوية والتوجيه الرشيد من الأب", "collocations": ["dispense fatherly wisdom", "benefit from fatherly wisdom"], "synonyms": ["paternal counsel"], "antonyms": [], "tags": ["family", "wisdom"]},
    {"headword": "motherly warmth", "pronunciation": "/ˈmʌðəli wɔːmθ/", "partOfSpeech": "noun", "definition": "The tender, unconditionally nurturing affection and comfort characteristically provided by a mother.", "example": "Her kitchen was always filled with motherly warmth, fragrant stews, and heartfelt listening.", "translation": "دفء وحنان الأمومة الفياض", "collocations": ["radiate motherly warmth", "embrace of motherly warmth"], "synonyms": ["maternal affection"], "antonyms": ["cold indifference"], "tags": ["family", "love"]},
    {"headword": "grandparent legacy", "pronunciation": "/ˈɡrænpeərənt ˈleɡəsi/", "partOfSpeech": "noun", "definition": "The enduring traditions, moral values, and cultural wisdom passed down by grandparents.", "example": "Our family honors our grandparent legacy by gathering for traditional Sunday dinners every week.", "translation": "إرث الأجداد وتقاليدهم المتوارثة", "collocations": ["preserve the grandparent legacy", "cherished grandparent legacy"], "synonyms": ["ancestral heritage"], "antonyms": [], "tags": ["heritage", "family"]},
    {"headword": "trusted confidant", "pronunciation": "/ˈtrʌstɪd ˌkɒnfɪˈdænt/", "partOfSpeech": "noun", "definition": "A deeply loyal friend to whom one entrusts private secrets, vulnerabilities, and intimate thoughts.", "example": "Throughout the grueling political campaign, her campaign manager served as her most trusted confidant.", "translation": "المستودع الأمين للأسرار والكاتم الموثوق", "collocations": ["act as a trusted confidant", "turn to a trusted confidant"], "synonyms": ["intimate friend", "bosom friend"], "antonyms": ["rival", "betrayer"], "tags": ["friendship", "trust"]},
    {"headword": "pillar of strength", "pronunciation": "/ˈpɪlər əv streŋθ/", "partOfSpeech": "noun", "definition": "A steadfast and emotionally resilient person who supports others during difficult crises.", "example": "When the family business burned down, my elder sister was an unshakable pillar of strength.", "translation": "سند وركيزة القوة والثبات في المحن", "collocations": ["act as a pillar of strength", "remain a pillar of strength"], "synonyms": ["rock of support"], "antonyms": [], "tags": ["support", "strength"]},
    {"headword": "ethical lodestar", "pronunciation": "/ˈeθɪkl ˈləʊdstɑː/", "partOfSpeech": "noun", "definition": "A foundational moral standard or ethical person that guides one's conscientious choices.", "example": "His grandfather's strict honesty served as an unswerving ethical lodestar throughout his corporate career.", "translation": "النجم الهادي والمحدد الأخلاقي للسلوك", "collocations": ["serve as an ethical lodestar", "true ethical lodestar"], "synonyms": ["moral compass", "guiding principle"], "antonyms": [], "tags": ["ethics", "values"]},
    {"headword": "unwavering support", "pronunciation": "/ʌnˈweɪvərɪŋ səˈpɔːt/", "partOfSpeech": "noun", "definition": "Constant, steadfast encouragement and assistance that never diminishes regardless of circumstance.", "example": "My parents offered unwavering support throughout my seven arduous years of medical school.", "translation": "الدعم والمساندة الراسخة التي لا تتزعزع", "collocations": ["provide unwavering support", "grateful for unwavering support"], "synonyms": ["steadfast backing"], "antonyms": ["fickle support"], "tags": ["support", "loyalty"]},
    {"headword": "lifelong ally", "pronunciation": "/ˈlaɪflɒŋ ˈælaɪ/", "partOfSpeech": "noun", "definition": "A devoted companion who stands by your side across decades of triumphs and setbacks.", "example": "Having met in kindergarten, the two women remained lifelong allies through every chapter of adulthood.", "translation": "الحليف والصديق الدائم مدى الحياة", "collocations": ["remain a lifelong ally", "cherish a lifelong ally"], "synonyms": ["enduring friend"], "antonyms": ["lifelong adversary"], "tags": ["loyalty", "friendship"]},
    {"headword": "inspirational figure", "pronunciation": "/ˌɪnspəˈreɪʃənl ˈfɪɡə/", "partOfSpeech": "noun", "definition": "A person whose remarkable achievements and courage stimulate creative ideas and moral resolve.", "example": "Nelson Mandela stands as an inspirational figure whose forgiveness transformed a divided nation.", "translation": "شخصية ملهمة تبعث على الإعجاب والاقتداء", "collocations": ["become an inspirational figure", "widely admired inspirational figure"], "synonyms": ["source of inspiration"], "antonyms": [], "tags": ["inspiration", "heroes"]},
    {"headword": "generous benefactor", "pronunciation": "/ˈdʒenərəs ˌbenɪˈfæktə/", "partOfSpeech": "noun", "definition": "A benevolent person who provides substantial financial or material resources to help someone flourish.", "example": "An anonymous generous benefactor funded the construction of the village community library.", "translation": "المحسن والكريم صاحب الفضل والعطاء", "collocations": ["thanks to a generous benefactor", "supported by a generous benefactor"], "synonyms": ["patron", "philanthropist"], "antonyms": [], "tags": ["charity", "gratitude"]},

    # Foundational Influences, Nurturers & Enduring Wisdom
    {"headword": "firm disciplinarian", "pronunciation": "/fɜːm ˌdɪsəplɪˈneəriən/", "partOfSpeech": "noun", "definition": "A teacher or parent who enforces strict behavioral standards while genuinely caring for development.", "example": "Our track coach was a firm disciplinarian who taught us that punctuality is the foundation of excellence.", "translation": "الشخص الحازم والمنضبط الذي يربي على الصرامة", "collocations": ["known as a firm disciplinarian", "strict but fair firm disciplinarian"], "synonyms": ["strict mentor"], "antonyms": ["permissive guardian"], "tags": ["discipline", "education"]},
    {"headword": "empathetic listener", "pronunciation": "/ˌempəˈθetɪk ˈlɪsnə/", "partOfSpeech": "noun", "definition": "A person who listens with profound understanding, validating emotions without premature judgment.", "example": "Being an empathetic listener made the school counselor a sanctuary for troubled teenagers.", "translation": "المستمع المتعاطف الذي ينصت بوعي وتفهم", "collocations": ["skilled empathetic listener", "act as an empathetic listener"], "synonyms": ["compassionate listener"], "antonyms": ["dismissive listener"], "tags": ["empathy", "communication"]},
    {"headword": "sympathetic soul", "pronunciation": "/ˌsɪmpəˈθetɪk səʊl/", "partOfSpeech": "noun", "definition": "A warm, caring individual possessing deep emotional gentleness and capacity for compassion.", "example": "In times of grief, Aunt Clara was the sympathetic soul who sat beside you in comforting silence.", "translation": "الروح المتعاطفة الودودة الرقيقة", "collocations": ["gentle sympathetic soul", "kind sympathetic soul"], "synonyms": ["caring spirit"], "antonyms": ["callous person"], "tags": ["kindness", "people"]},
    {"headword": "wise elder", "pronunciation": "/waɪz ˈeldə/", "partOfSpeech": "noun", "definition": "A senior member of a family or community respected for accumulated life experience and prudent counsel.", "example": "The villagers consulted the wise elder before undertaking any major agricultural negotiations.", "translation": "كبير العائلة الحكيم صاحب الرأي السديد", "collocations": ["counsel of a wise elder", "revered as a wise elder"], "synonyms": ["venerated elder", "sage"], "antonyms": [], "tags": ["wisdom", "elders"]},
    {"headword": "family anchor", "pronunciation": "/ˈfæməli ˈæŋkə/", "partOfSpeech": "noun", "definition": "The central family member whose presence and leadership provide stability, cohesion, and peace.", "example": "Our grandmother was the family anchor who kept all branches of our extended family united.", "translation": "مرساة العائلة وصمام أمان تماسكها", "collocations": ["serve as the family anchor", "loss of the family anchor"], "synonyms": ["keystone of the family"], "antonyms": [], "tags": ["family", "stability"]},
    {"headword": "mentor figure", "pronunciation": "/ˈmentɔː ˈfɪɡə/", "partOfSpeech": "noun", "definition": "A senior individual who takes personal interest in nurturing a junior person's career and character.", "example": "Having an experienced mentor figure early in residency helped the young physician withstand hospital stress.", "translation": "الشخصية الموجهة والراعية مهنياً وشخصياً", "collocations": ["find a mentor figure", "depend on a mentor figure"], "synonyms": ["adviser", "sponsor"], "antonyms": [], "tags": ["mentorship", "career"]},
    {"headword": "unsung hero", "pronunciation": "/ʌnˈsʌŋ ˈhɪərəʊ/", "partOfSpeech": "noun", "definition": "A person who performs extraordinary, selfless acts of service without seeking public praise or fanfare.", "example": "Hospital sanitation workers were the unsung heroes who kept operating theaters sterile during the epidemic.", "translation": "البطل المجهول الذي يبذل التضحيات دون صخب", "collocations": ["praise the unsung hero", "community unsung hero"], "synonyms": ["unrecognized hero"], "antonyms": ["public celebrity"], "tags": ["heroes", "gratitude"]},
    {"headword": "positive influence", "pronunciation": "/ˈpɒzətɪv ˈɪnfluəns/", "partOfSpeech": "noun", "definition": "A person whose presence, advice, and habits encourage wholesome development in others.", "example": "Joining the debate team surrounded him with peers who exerted a powerfully positive influence on his study habits.", "translation": "التأثير الإيجابي المحفز على الخير والنمو", "collocations": ["exert a positive influence", "act as a positive influence"], "synonyms": ["wholesome guide"], "antonyms": ["negative influence"], "tags": ["influence", "growth"]},
    {"headword": "nurturing guide", "pronunciation": "/ˈnɜːtʃərɪŋ ɡaɪd/", "partOfSpeech": "noun", "definition": "A supportive person who gently encourages, protects, and fosters another's talents and self-worth.", "example": "Her piano tutor was a patient, nurturing guide who turned every technical stumble into a learning moment.", "translation": "المرشد الحنون والمربي الراعي للمواهب", "collocations": ["act as a nurturing guide", "grateful for a nurturing guide"], "synonyms": ["caring mentor"], "antonyms": [], "tags": ["education", "care"]},
    {"headword": "source of comfort", "pronunciation": "/sɔːs əv ˈkʌmfət/", "partOfSpeech": "noun", "definition": "A person, memory, or presence that brings consolation, solace, and relief during periods of distress.", "example": "Her grandfather's calm voice on the telephone was an immediate source of comfort during finals week.", "translation": "مصدر السكينة والعزاء وبلسم الأحزان", "collocations": ["provide a source of comfort", "constant source of comfort"], "synonyms": ["solace", "refuge"], "antonyms": ["source of anxiety"], "tags": ["comfort", "empathy"]},
    {"headword": "formative influence", "pronunciation": "/ˈfɔːmətɪv ˈɪnfluəns/", "partOfSpeech": "noun", "definition": "A decisive person, experience, or environment that shapes someone's worldview during youth.", "example": "Growing up in a multilingual port city was a formative influence that inspired her passion for translation.", "translation": "التأثير التكويني الجوهري في نشأة الإنسان", "collocations": ["major formative influence", "enduring formative influence"], "synonyms": ["foundational impact"], "antonyms": [], "tags": ["development", "influence"]},
    {"headword": "treasured memory", "pronunciation": "/ˈtreʒəd ˈmeməri/", "partOfSpeech": "noun", "definition": "A deeply cherished, emotionally precious recollection of a person, event, or shared experience.", "example": "Walking along the misty beach with my father at sunrise remains an indelible, treasured memory.", "translation": "الذكرى الغالية والعزيزة المحفورة في القلب", "collocations": ["hold a treasured memory", "cherish as a treasured memory"], "synonyms": ["precious recollection"], "antonyms": ["painful memory"], "tags": ["memories", "nostalgia"]},
    {"headword": "unforgettable teacher", "pronunciation": "/ˌʌnfəˈɡetəbl ˈtiːtʃə/", "partOfSpeech": "noun", "definition": "An exceptional educator whose wisdom, passion, and personal kindness leave an everlasting mark on students.", "example": "Mr. Davies was an unforgettable teacher whose literature readings brought Shakespeare vividly to life.", "translation": "المعلم الذي لا يُنسى صاحب الأثر الخالد", "collocations": ["tribute to an unforgettable teacher", "remember an unforgettable teacher"], "synonyms": ["memorable educator"], "antonyms": [], "tags": ["education", "memories"]},
    {"headword": "guardian angel", "pronunciation": "/ˈɡɑːdiən ˈeɪndʒl/", "partOfSpeech": "noun", "definition": "A benevolent person who watches over, protects, and rescues someone in times of extreme vulnerability.", "example": "When I was stranded with a broken vehicle in the blizzard, that stranger acted like a true guardian angel.", "translation": "الملاك الحارس والمنقذ في الشدائد", "collocations": ["act as a guardian angel", "my personal guardian angel"], "synonyms": ["protector", "savior"], "antonyms": [], "tags": ["gratitude", "protection"]},
    {"headword": "guiding hand", "pronunciation": "/ˈɡaɪdɪŋ hænd/", "partOfSpeech": "noun", "definition": "Gentle, experienced leadership and supervision that steers someone safely toward success.", "example": "Without the guiding hand of our senior research director, our laboratory team would have lost funding.", "translation": "اليد المرشدة والموجهة بحكمة وعناية", "collocations": ["rely on a guiding hand", "steady guiding hand"], "synonyms": ["wise direction"], "antonyms": [], "tags": ["guidance", "leadership"]},

    # Character Builders, Allies & Enduring Gratitude
    {"headword": "patient instructor", "pronunciation": "/ˈpeɪʃnt ɪnˈstrʌktə/", "partOfSpeech": "noun", "definition": "A teacher who explains challenging concepts calmly and repeatedly without exhibiting frustration.", "example": "Learning to play the violin requires a patient instructor who understands that mastery takes years.", "translation": "المعلم والمدرب الصبور والمتأني", "collocations": ["blessed with a patient instructor", "role of a patient instructor"], "synonyms": ["forbearing teacher"], "antonyms": ["impatient tutor"], "tags": ["education", "patience"]},
    {"headword": "supportive peer", "pronunciation": "/səˈpɔːtɪv pɪə/", "partOfSpeech": "noun", "definition": "An equal, classmate, or colleague who encourages, assists, and celebrates your achievements.", "example": "Having a supportive peer during the grueling bar exam study sessions made all the difference.", "translation": "الزميل والقرين الداعم والمشجع", "collocations": ["work alongside a supportive peer", "surround yourself with supportive peers"], "synonyms": ["encouraging colleague"], "antonyms": ["toxic rival"], "tags": ["peers", "support"]},
    {"headword": "loyal companion", "pronunciation": "/ˈlɔɪəl kəmˈpænjən/", "partOfSpeech": "noun", "definition": "A faithful friend whose steadfast devotion and companionship never falter through hardships.", "example": "Through every cross-country relocation, his golden retriever was an affectionate and loyal companion.", "translation": "الرفيق المخلص والوفي في كل الظروف", "collocations": ["cherished loyal companion", "remain a loyal companion"], "synonyms": ["devoted friend"], "antonyms": ["fair-weather friend"], "tags": ["loyalty", "friendship"]},
    {"headword": "humble role model", "pronunciation": "/ˈhʌmbl rəʊl ˈmɒdl/", "partOfSpeech": "noun", "definition": "An accomplished person who leads by virtuous example while remaining completely devoid of arrogance.", "example": "Despite winning the Nobel Prize, the professor remained a humble role model who ate lunch with undergraduates.", "translation": "القدوة المتواضعة المجردة من الكبرياء والغرور", "collocations": ["admire as a humble role model", "serve as a humble role model"], "synonyms": ["modest exemplar"], "antonyms": ["arrogant idol"], "tags": ["humility", "leadership"]},
    {"headword": "sympathetic mentor", "pronunciation": "/ˌsɪmpəˈθetɪk ˈmentɔː/", "partOfSpeech": "noun", "definition": "An advisor who pairs professional guidance with deep emotional sensitivity toward their protégé's challenges.", "example": "A sympathetic mentor helped the young resident doctor cope with the traumatic loss of her first patient.", "translation": "المرشد المتعاطف الذي يراعي الجوانب الإنسانية", "collocations": ["guidance from a sympathetic mentor", "appreciate a sympathetic mentor"], "synonyms": ["compassionate advisor"], "antonyms": [], "tags": ["mentorship", "empathy"]},
    {"headword": "cherished elder", "pronunciation": "/ˈtʃerɪʃt ˈeldə/", "partOfSpeech": "noun", "definition": "An elderly family or tribal member who is deeply loved, revered, and cared for by younger generations.", "example": "The village gathered to celebrate the one-hundredth birthday of their most cherished elder.", "translation": "كبير السن العزيز والمحبوب والموقر", "collocations": ["honor a cherished elder", "wisdom of a cherished elder"], "synonyms": ["beloved senior"], "antonyms": [], "tags": ["elders", "respect"]},
    {"headword": "trusted advisor", "pronunciation": "/ˈtrʌstɪd ədˈvaɪzə/", "partOfSpeech": "noun", "definition": "An expert whose integrity and judgment have proven dependable across critical life choices.", "example": "The prime minister relied on his trusted advisor to navigate complex foreign policy disputes.", "translation": "المستشار المؤتمن ذو الرأي الموثوق", "collocations": ["rely on a trusted advisor", "act as a trusted advisor"], "synonyms": ["confidential counselor"], "antonyms": [], "tags": ["trust", "advisory"]},
    {"headword": "motivational coach", "pronunciation": "/ˌməʊtɪˈveɪʃənl kəʊtʃ/", "partOfSpeech": "noun", "definition": "A trainer who inspires individuals to transcend self-doubt and realize their maximum athletic or personal potential.", "example": "Our motivational coach taught us that true mental toughness begins when physical energy runs out.", "translation": "المدرب التحفيزي الذي يبث العزيمة والإصرار", "collocations": ["hire a motivational coach", "listen to a motivational coach"], "synonyms": ["performance coach"], "antonyms": [], "tags": ["motivation", "sports"]},
    {"headword": "forgiving parent", "pronunciation": "/fəˈɡɪvɪŋ ˈpeərənt/", "partOfSpeech": "noun", "definition": "A mother or father who responds to mistakes with understanding, redemption, and unconditional love.", "example": "Having a forgiving parent taught him that honest mistakes are opportunities for maturity, not condemnation.", "translation": "الأب أو الأم المتسامحة صاحبة القلب الرحيم", "collocations": ["blessed with a forgiving parent", "warmth of a forgiving parent"], "synonyms": ["merciful guardian"], "antonyms": ["punitive parent"], "tags": ["family", "forgiveness"]},
    {"headword": "courageous pioneer", "pronunciation": "/kəˈreɪdʒəs ˌpaɪəˈnɪə/", "partOfSpeech": "noun", "definition": "An early trailblazer who braves severe danger, prejudice, or hardship to open pathways for others.", "example": "Rosa Parks was a courageous pioneer whose quiet defiance ignited the modern civil rights movement.", "translation": "الرائد الشجاع الذي يمهد الطريق للأجيال", "collocations": ["honor a courageous pioneer", "memory of a courageous pioneer"], "synonyms": ["brave trailblazer"], "antonyms": [], "tags": ["courage", "history"]},
    {"headword": "generous soul", "pronunciation": "/ˈdʒenərəs səʊl/", "partOfSpeech": "noun", "definition": "A genuinely kind-hearted individual whose disposition is defined by benevolence, charity, and warmth.", "example": "Uncle Robert was a generous soul who never allowed a hungry neighbor to leave his kitchen empty-handed.", "translation": "الشخص السخي ذو النفس الكريمة المعطاءة", "collocations": ["known as a generous soul", "rare generous soul"], "synonyms": ["magnanimous person"], "antonyms": ["miser"], "tags": ["kindness", "generosity"]},
    {"headword": "beloved relative", "pronunciation": "/bɪˈlʌvɪd ˈrelətɪv/", "partOfSpeech": "noun", "definition": "A family member held in high affection and deep fondness by their kin.", "example": "Every summer holiday was spent at the coastal cottage of our beloved relative, Aunt Helen.", "translation": "القريب المحبوب والعزيز على القلب", "collocations": ["visit a beloved relative", "mourn a beloved relative"], "synonyms": ["cherished kinsman"], "antonyms": [], "tags": ["family", "love"]},
    {"headword": "compassionate friend", "pronunciation": "/kəmˈpæʃənət frend/", "partOfSpeech": "noun", "definition": "A friend who deeply empathizes with your pain and offers heartfelt solace without judgment.", "example": "When she suffered a sudden bereavement, having a compassionate friend beside her brought immense relief.", "translation": "الصديق الرحيم والمواسي في الأحزان", "collocations": ["turn to a compassionate friend", "blessed with a compassionate friend"], "synonyms": ["sympathetic friend"], "antonyms": [], "tags": ["friendship", "compassion"]},
    {"headword": "encouraging mentor", "pronunciation": "/ɪnˈkʌrɪdʒɪŋ ˈmentɔː/", "partOfSpeech": "noun", "definition": "An advisor whose primary pedagogical method is instilling confidence and praising effort.", "example": "An encouraging mentor can dispel years of imposter syndrome in a talented young artist.", "translation": "المرشد المشجع الذي يزرع الثقة في النفس", "collocations": ["guidance of an encouraging mentor", "find an encouraging mentor"], "synonyms": ["supportive advisor"], "antonyms": ["hypercritical critic"], "tags": ["mentorship", "confidence"]},
    {"headword": "faithful confidant", "pronunciation": "/ˈfeɪθfl ˌkɒnfɪˈdænt/", "partOfSpeech": "noun", "definition": "A steadfast friend whose trustworthiness in keeping confidential disclosures is absolute.", "example": "Throughout decades of public scrutiny, his spouse remained his most faithful confidant.", "translation": "المؤتمن الوفي الذي يحفظ السر ولا يخون الأمانة", "collocations": ["confide in a faithful confidant", "remain a faithful confidant"], "synonyms": ["loyal confidant"], "antonyms": [], "tags": ["loyalty", "trust"]},
    {"headword": "inspiring leader", "pronunciation": "/ɪnˈspaɪərɪŋ ˈliːdə/", "partOfSpeech": "noun", "definition": "A leader whose vision, moral integrity, and charisma motivate teams to achieve extraordinary goals.", "example": "An inspiring leader unites diverse teams by focusing on shared human purpose rather than petty divisions.", "translation": "القائد الملهم الذي يشحذ الهمم ويوحد الصفوف", "collocations": ["revered as an inspiring leader", "qualities of an inspiring leader"], "synonyms": ["visionary leader"], "antonyms": ["demoralizing boss"], "tags": ["leadership", "inspiration"]},
    {"headword": "selfless volunteer", "pronunciation": "/ˈselfləs ˌvɒlənˈtɪə/", "partOfSpeech": "noun", "definition": "A person who generously donates time and labor to serve others without expecting material reward.", "example": "The disaster relief camp was staffed by selfless volunteers who worked eighteen-hour shifts in monsoon mud.", "translation": "المتطوع المتفاني الذي يؤثر غيره على نفسه", "collocations": ["effort of a selfless volunteer", "corps of selfless volunteers"], "synonyms": ["altruistic worker"], "antonyms": [], "tags": ["service", "charity"]},
    {"headword": "steadfast friend", "pronunciation": "/ˈstedfɑːst frend/", "partOfSpeech": "noun", "definition": "A loyal friend whose support remains firm, unwavering, and constant through all life changes.", "example": "A steadfast friend is a rare treasure whose fidelity does not waver when financial fortunes change.", "translation": "الصديق الصدوق الثابت والوفي على العهد", "collocations": ["remain a steadfast friend", "rely on a steadfast friend"], "synonyms": ["constant friend", "staunch ally"], "antonyms": ["unfaithful friend"], "tags": ["friendship", "loyalty"]},
    {"headword": "wise counselor", "pronunciation": "/waɪz ˈkaʊnsələ/", "partOfSpeech": "noun", "definition": "A prudent advisor who helps people navigate complex moral, legal, or personal dilemmas.", "example": "The retired judge served as a wise counselor to community mediators resolving ethnic tensions.", "translation": "المستشار والموجه الحكيم الخبير بالحياة", "collocations": ["seek a wise counselor", "advice of a wise counselor"], "synonyms": ["sagacious advisor"], "antonyms": [], "tags": ["wisdom", "guidance"]},
    {"headword": "formative bond", "pronunciation": "/ˈfɔːmətɪv bɒnd/", "partOfSpeech": "noun", "definition": "A foundational emotional relationship during youth that permanently influences personality and character.", "example": "The formative bond forged between the brothers during wartime hardship endured throughout their long lives.", "translation": "الرابطة التكوينية الوثيقة التي تصقل الشخصية", "collocations": ["forge a formative bond", "strength of a formative bond"], "synonyms": ["foundational attachment"], "antonyms": [], "tags": ["relationships", "family"]}
]

grammar_83 = [
    {
        "title": "Relative Clauses + Narrative Tenses",
        "explanation": "Describing influential people who shaped our lives requires weaving relative clauses (defining and non-defining) together with narrative tenses (Past Simple, Past Continuous, Past Perfect):\n\n1. Defining Relative Clauses with Narrative Tenses:\n   Specifies exactly which person or influence is meant:\n   - 'She was the inspiring teacher who had recognized my talent when I was struggling.'\n   - 'I called the trusted confidant whom I had known since early childhood.'\n\n2. Non-defining Relative Clauses for Rich Contextual Tributes:\n   Enclosed in commas, these add respectful background information:\n   - 'My grandfather, who had worked in the coal mines for forty years, instilled in us an ethical lodestar.'\n   - 'Dr. Miller, whose fatherly wisdom had guided me during medical residency, retired last autumn.'\n\n3. Past Perfect inside Relative Clauses:\n   Establishes actions completed before a past milestone:\n   - 'When I received the award, I thanked the formative mentor who had supported my research from day one.'\n\n4. Past Continuous for Past Background Actions of Mentors:\n   - 'While my coach was encouraging us from the sideline, we broke the national relay record.'",
        "structures": [
            {"pattern": "Non-defining clause + Past Simple: Subject, who / whose + background, + Main Verb: 'My mentor, who had guided me for years, celebrated my graduation.'"},
            {"pattern": "Defining clause + Past Perfect: Person + who / that + had + V3: 'She was the unsung hero who had sacrificed everything for our education.'"},
            {"pattern": "Past Continuous background + Relative clause: 'While she was serving as a pillar of strength, her wisdom inspired our entire family.'"}
        ],
        "examples": [
            {
                "sentence": "My grandfather, whose fatherly wisdom had anchored our family, was an unforgettable teacher to all his grandchildren.",
                "arabic": "جدي، الذي كانت حكمته الأبوية قد أرست عائلتنا، كان معلماً لا يُنسى لجميع أحفاده.",
                "usesVocabulary": ["fatherly wisdom", "unforgettable teacher"]
            },
            {
                "sentence": "She was the formative mentor who had provided unwavering support when my confidence was faltering.",
                "arabic": "لقد كانت المرشدة التكوينية التي قدمت دعماً راسخاً لا يتزعزع عندما كانت ثقتي بنفسي تتلاشى.",
                "usesVocabulary": ["formative mentor", "unwavering support"]
            },
            {
                "sentence": "We gathered to honor the selfless volunteer who had spent twenty years running the local food pantry.",
                "arabic": "اجتمعنا لتكريم المتطوع المتفاني الذي قضى عشرين عاماً في إدارة بنك الطعام المحلي.",
                "usesVocabulary": ["selfless volunteer"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "My uncle that had been a pillar of strength passed away last year.",
                "right": "My uncle, who had been a pillar of strength, passed away last year.",
                "explanation": "Use 'who' (not 'that') with commas for a non-defining relative clause referring to a specific person."
            },
            {
                "wrong": "She was the mentor which helped me through medical school.",
                "right": "She was the mentor who helped me through medical school.",
                "explanation": "Always use 'who' or 'whom' (never 'which') when referring to human beings."
            }
        ]
    }
]

convs_83 = [
    {
        "title": "Tribute to a Life Mentor: Graduation Speech Prep",
        "titleArabic": "تحية لمرشد الحياة: التحضير لخطاب التخرج",
        "setting": "A university graduate discusses her valedictorian address with her elder brother.",
        "lines": [
            {"speaker": "Aiden", "text": "Who are you highlighting in your graduation speech tomorrow?"},
            {"speaker": "Clara", "text": "I am dedicating it to Professor Vance, the formative mentor who served as my intellectual guiding light."},
            {"speaker": "Aiden", "text": "He truly was a humble role model who offered unwavering support throughout your four years of research."},
            {"speaker": "Clara", "text": "Indeed. Whenever I doubted my abilities, he acted as a patient instructor and an empathetic listener."},
            {"speaker": "Aiden", "text": "Our grandfather also instilled in you that same ethical lodestar and fatherly wisdom."},
            {"speaker": "Clara", "text": "Grandpa was our family anchor. His motherly warmth and quiet strength shaped my moral compass."},
            {"speaker": "Aiden", "text": "He was an unsung hero who worked double shifts so we could attend college."},
            {"speaker": "Clara", "text": "I will share that treasured memory. Honoring those who shaped us gives meaning to this milestone."}
        ],
        "vocabularyUsed": ["formative mentor", "guiding light", "humble role model", "unwavering support", "patient instructor", "empathetic listener", "ethical lodestar", "fatherly wisdom", "family anchor", "motherly warmth", "unsung hero", "treasured memory"]
    },
    {
        "title": "Childhood Reunion: Remembering Early Influences",
        "titleArabic": "لقاء رفقاء الصبا: استرجاع الذكريات والمؤثرين الأوائل",
        "setting": "Two lifelong friends meet in their hometown after years living in different countries.",
        "lines": [
            {"speaker": "Samir", "text": "Walking down our old street brings back every memory of growing up with you as my childhood companion."},
            {"speaker": "Tarek", "text": "You were my steadfast friend and trusted confidant through every schoolyard crisis."},
            {"speaker": "Samir", "text": "Do you remember Coach Miller? He was a firm disciplinarian, but he was an inspiring teacher at heart."},
            {"speaker": "Tarek", "text": "He was a motivational coach who pushed us to develop true resilience on the track."},
            {"speaker": "Samir", "text": "And Mrs. Higgins, our gentle neighborhood elder, was a generous benefactor who provided books for everyone."},
            {"speaker": "Tarek", "text": "She was a sympathetic soul and a true guardian angel to struggling families in the village."},
            {"speaker": "Samir", "text": "That formative bond we shared with our community taught us values that still guide us today."},
            {"speaker": "Tarek", "text": "Surrounding ourselves with positive influences gave us the courage to build meaningful lives."}
        ],
        "vocabularyUsed": ["childhood companion", "steadfast friend", "trusted confidant", "firm disciplinarian", "inspiring teacher", "motivational coach", "generous benefactor", "sympathetic soul", "guardian angel", "formative bond", "positive influence"]
    },
    {
        "title": "Family Fireside: Honoring the Ancestral Legacy",
        "titleArabic": "جلسة عائلية دافئة: تكريم إرث الأجداد والآباء",
        "setting": "An uncle and niece look through vintage family photo albums on a winter evening.",
        "lines": [
            {"speaker": "Niece", "text": "Look at this photograph of Great-Aunt Sarah. She had such a dignified, serene presence."},
            {"speaker": "Uncle", "text": "She was a courageous pioneer who opened the first women's medical dispensary in this province."},
            {"speaker": "Niece", "text": "Everyone described her as a generous soul and a source of comfort for the entire town."},
            {"speaker": "Uncle", "text": "She was also a wise counselor to my father when he was starting his legal practice."},
            {"speaker": "Niece", "text": "Our grandparent legacy is filled with role model figures who lived with remarkable humility."},
            {"speaker": "Uncle", "text": "Your mother inherited that same nurturing guide quality; she has been a pillar of strength for decades."},
            {"speaker": "Niece", "text": "She is my lifelong ally. Having a forgiving parent and encouraging mentor made all the difference."},
            {"speaker": "Uncle", "text": "Passing down these values preserves our family's greatest treasure."}
        ],
        "vocabularyUsed": ["courageous pioneer", "generous soul", "source of comfort", "wise counselor", "grandparent legacy", "role model figure", "nurturing guide", "pillar of strength", "lifelong ally", "forgiving parent", "encouraging mentor"]
    }
]

paras_83 = [
    {
        "title": "The Formative Guides Who Shape Human Character",
        "titleArabic": "الموجهون التكوينيون الذين يصقلون الشخصية الإنسانية",
        "text": "Every accomplished individual stands upon the shoulders of remarkable mentors who shaped their earliest aspirations. In early youth, blessed is the student who encounters an inspiring teacher or an unforgettable teacher whose pedagogical passion awakens intellectual curiosity. Such educators act as a nurturing guide and patient instructor, offering unwavering support through academic trials. Beyond the classroom, a formative mentor functions as an ethical lodestar, guiding young professionals away from moral compromises. When doubts cloud judgment, turning to a humble role model or wise counselor restores clarity. Ultimately, these formative influences instill lasting values that endure through every chapter of adult life.",
        "vocabularyUsed": ["inspiring teacher", "unforgettable teacher", "nurturing guide", "patient instructor", "unwavering support", "formative mentor", "ethical lodestar", "humble role model", "wise counselor", "formative influence"]
    },
    {
        "title": "Family Foundations: Pillars of Strength and Generational Love",
        "titleArabic": "أركان العائلة: ركائز القوة والمحبة عبر الأجيال",
        "text": "Within the sanctuary of family life, foundational virtues are absorbed through loving examples rather than formal instruction. A home enveloped in motherly warmth and anchored by fatherly wisdom provides children with an unshakable psychological bedrock. When adversity strikes, a steadfast elder acts as a pillar of strength and a dependable family anchor, weathering grief with quiet dignity. Treasuring our grandparent legacy connects current generations with ancestral sacrifices that made modern opportunities possible. Guided by a forgiving parent whose compassion transcends human missteps, children learn to navigate relationships with profound empathy. These enduring family bonds provide a lifelong source of comfort across every storm.",
        "vocabularyUsed": ["motherly warmth", "fatherly wisdom", "pillar of strength", "family anchor", "grandparent legacy", "forgiving parent", "source of comfort"]
    },
    {
        "title": "Allies, Companions, and the Quiet Heroes of Community Life",
        "titleArabic": "الحلفاء، الرفقاء، والأبطال المجهولون في المجتمع",
        "text": "Human resilience is sustained by compassionate connections forged across communities. Growing up alongside a loyal childhood companion establishes an enduring formative bond that defies geographic distance. Throughout life, having a trusted confidant and steadfast friend provides a safe harbor where vulnerabilities can be voiced without judgment. In society, unsung heroes and selfless volunteers embody the spirit of a generous soul, extending a guiding hand and acting as a guardian angel to those in distress. Whether as a supportive peer in the workplace or a compassionate friend during bereavement, these individuals leave an indelible treasured memory in the hearts of those they touch.",
        "vocabularyUsed": ["childhood companion", "formative bond", "trusted confidant", "steadfast friend", "unsung hero", "selfless volunteer", "generous soul", "guiding hand", "guardian angel", "supportive peer", "compassionate friend", "treasured memory"]
    }
]

# ==============================================================================
# DAY 84: Travel Stories (Journeys and memories)
# Grammar: Narrative Tenses + Used to / Would
# ==============================================================================

vocab_84 = [
    # Scenic Expeditions, Discoveries & Unplanned Detours
    {"headword": "scenic detour", "pronunciation": "/ˈsiːnɪk ˈdiːtʊə/", "partOfSpeech": "noun", "definition": "An intentional deviation from the main highway to enjoy beautiful natural landscapes and views.", "example": "We took a two-hour scenic detour through the rolling vineyard hills instead of the busy motorway.", "translation": "انحراف وانعطاف عن الطريق للاستمتاع بالمناظر الطبيعية", "collocations": ["take a scenic detour", "worth the scenic detour"], "synonyms": ["picturesque detour"], "antonyms": ["direct expressway"], "tags": ["travel", "scenery"]},
    {"headword": "breathtaking vista", "pronunciation": "/ˈbreθteɪkɪŋ ˈvɪstə/", "partOfSpeech": "noun", "definition": "An extraordinarily magnificent, awe-inspiring panoramic view of mountains, ocean, or countryside.", "example": "Reaching the mountain pass revealed a breathtaking vista of snow-capped alpine peaks and emerald lakes.", "translation": "إطلالة بانورامية تأخذ الألباب وتحبس الأنفاس", "collocations": ["enjoy a breathtaking vista", "admire the breathtaking vista"], "synonyms": ["stunning panorama"], "antonyms": ["drab scenery"], "tags": ["scenery", "travel"]},
    {"headword": "mountain pass trek", "pronunciation": "/ˈmaʊntɪn pɑːs trek/", "partOfSpeech": "noun", "definition": "A demanding hiking expedition navigating high altitude saddles between mountain summits.", "example": "The five-day mountain pass trek across the Pyrenees tested our stamina against sudden hail and winds.", "translation": "مسار المشي الجبلي الشاق عبر الممرات المرتفعة", "collocations": ["embark on a mountain pass trek", "complete a mountain pass trek"], "synonyms": ["alpine crossing"], "antonyms": [], "tags": ["hiking", "adventure"]},
    {"headword": "winding coastal road", "pronunciation": "/ˈwaɪndɪŋ ˈkəʊstl rəʊd/", "partOfSpeech": "noun", "definition": "A scenic, curving highway running adjacent to rugged seaside cliffs and ocean shorelines.", "example": "Driving along the winding coastal road of the Amalfi coast was exhilarating yet white-knuckle terrifying.", "translation": "طريق ساحلي متعرج بمحاذاة الشاطئ والجبال", "collocations": ["drive the winding coastal road", "cruise the winding coastal road"], "synonyms": ["clifftop highway"], "antonyms": ["straight inland road"], "tags": ["travel", "roads"]},
    {"headword": "remote village stay", "pronunciation": "/rɪˈməʊt ˈvɪlɪdʒ steɪ/", "partOfSpeech": "noun", "definition": "An authentic overnight travel accommodation in an isolated, traditional countryside hamlet.", "example": "A week-long remote village stay in the Atlas Mountains gave us firsthand appreciation for Berber hospitality.", "translation": "الإقامة في قرية ريفية نائية للاستجمام", "collocations": ["book a remote village stay", "experience a remote village stay"], "synonyms": ["rural homestay"], "antonyms": ["city center hotel"], "tags": ["travel", "culture"]},
    {"headword": "train journey memory", "pronunciation": "/treɪn ˈdʒɜːni ˈmeməri/", "partOfSpeech": "noun", "definition": "A cherished personal recollection of traveling across countries by passenger railway.", "example": "My favorite train journey memory was watching the sunrise over Lake Baikal from the Trans-Siberian.", "translation": "ذكرى رحلة القطار العابرة للبلدان", "collocations": ["fond train journey memory", "vivid train journey memory"], "synonyms": ["rail travel recollection"], "antonyms": [], "tags": ["transit", "memories"]},
    {"headword": "missed connection mishap", "pronunciation": "/mɪst kəˈnekʃn ˈmɪshæp/", "partOfSpeech": "noun", "definition": "An unfortunate travel accident where an initial transport delay causes one to miss a connecting flight or train.", "example": "A missed connection mishap in Frankfurt stranded us overnight without our checked luggage.", "translation": "ورطة تفويت رحلة المواصلات الترانزيت", "collocations": ["suffer a missed connection mishap", "resolve a missed connection mishap"], "synonyms": ["transit delay incident"], "antonyms": ["seamless connection"], "tags": ["mishaps", "transit"]},
    {"headword": "lost luggage adventure", "pronunciation": "/lɒst ˈlʌɡɪdʒ ədˈventʃə/", "partOfSpeech": "noun", "definition": "A humorous or chaotic travel experience resulting from an airline misplacing one's suitcases.", "example": "Our lost luggage adventure forced us to buy handwoven wool sweaters from a local harbor fisherman.", "translation": "مغامرة فقدان حقائب السفر وتدارك الموقف", "collocations": ["survive a lost luggage adventure", "turn into a lost luggage adventure"], "synonyms": ["baggage mishap"], "antonyms": [], "tags": ["travel", "humor"]},
    {"headword": "unplanned detour", "pronunciation": "/ʌnˈplænd ˈdiːtʊə/", "partOfSpeech": "noun", "definition": "An unforeseen change of route caused by road closures, spontaneous curiosity, or navigational errors.", "example": "An unplanned detour due to a washed-out bridge brought us to an enchanting medieval castle.", "translation": "انعطاف ومسار بديل غير مخطط له مسبقاً", "collocations": ["make an unplanned detour", "lead to an unplanned detour"], "synonyms": ["spontaneous diversion"], "antonyms": ["planned itinerary"], "tags": ["adventure", "travel"]},
    {"headword": "hidden gem discovery", "pronunciation": "/ˈhɪdn dʒem dɪˈskʌvəri/", "partOfSpeech": "noun", "definition": "Uncovering a secluded, remarkable, and unpublicized place unknown to mass tourist crowds.", "example": "Finding an uncrowded cove with crystalline turquoise water was our greatest hidden gem discovery.", "translation": "اكتشاف جوهرة ومعلم سياحي مخفي عن الأنظار", "collocations": ["stumble upon a hidden gem discovery", "thrill of a hidden gem discovery"], "synonyms": ["secret spot find"], "antonyms": ["tourist trap"], "tags": ["discovery", "travel"]},

    # Cultural Immersion, Local Enclaves & Transit Tales
    {"headword": "vibrant bazaar visit", "pronunciation": "/ˈvaɪbrənt bəˈzɑː ˈvɪzɪt/", "partOfSpeech": "noun", "definition": "An excursion through an energetic, bustling traditional marketplace full of spices, crafts, and bartering.", "example": "Our vibrant bazaar visit in Istanbul overwhelmed our senses with saffron aromas and patterned rugs.", "translation": "زيارة البازار والسوق الشعبي النابض بالحياة", "collocations": ["enjoy a vibrant bazaar visit", "photographs from a vibrant bazaar visit"], "synonyms": ["market exploration"], "antonyms": [], "tags": ["culture", "shopping"]},
    {"headword": "historic landmark tour", "pronunciation": "/hɪˈstɒrɪk ˈlændmɑːk tʊə/", "partOfSpeech": "noun", "definition": "A guided exploration of architectural monuments, cathedrals, or fortresses of great historical significance.", "example": "The historic landmark tour of Granada's Alhambra illuminated centuries of Moorish architecture.", "translation": "جولة استكشاف المعالم التاريخية الأثرية", "collocations": ["take a historic landmark tour", "book a historic landmark tour"], "synonyms": ["heritage tour"], "antonyms": [], "tags": ["history", "tourism"]},
    {"headword": "local homestay", "pronunciation": "/ˈləʊkl ˈhəʊmsteɪ/", "partOfSpeech": "noun", "definition": "Staying as a paying guest in a local resident's home to immerse deeply in cultural daily life.", "example": "Booking a local homestay in rural Kyoto allowed us to experience authentic morning tea ceremonies.", "translation": "الإقامة والضيافة في منزل عائلة محلية", "collocations": ["arrange a local homestay", "warmth of a local homestay"], "synonyms": ["family stay"], "antonyms": ["commercial resort"], "tags": ["culture", "accommodation"]},
    {"headword": "off-the-beaten-track route", "pronunciation": "/ɒf ðə ˈbiːtn træk ruːt/", "partOfSpeech": "noun", "definition": "A travel itinerary exploring secluded places far removed from conventional tourist circuits.", "example": "Hiring a rugged four-wheel drive allowed us to navigate an off-the-beaten-track route through Patagonia.", "translation": "مسار سياحي غير مطروق وبعيد عن الزحام", "collocations": ["explore an off-the-beaten-track route", "travel along an off-the-beaten-track route"], "synonyms": ["remote itinerary"], "antonyms": ["mainstream tourist route"], "tags": ["adventure", "travel"]},
    {"headword": "cultural immersion trip", "pronunciation": "/ˈkʌltʃərəl ɪˈmɜːʃn trɪp/", "partOfSpeech": "noun", "definition": "A travel journey designed specifically to live, eat, and speak alongside indigenous communities.", "example": "Her three-month cultural immersion trip in Oaxaca transformed her Spanish fluency and culinary knowledge.", "translation": "رحلة الانغماس الثقافي والمعايشة مع السكان", "collocations": ["embark on a cultural immersion trip", "deep cultural immersion trip"], "synonyms": ["cultural exchange journey"], "antonyms": ["resort vacation"], "tags": ["culture", "learning"]},
    {"headword": "picturesque alleyway", "pronunciation": "/ˌpɪktʃəˈresk ˈæliweɪ/", "partOfSpeech": "noun", "definition": "A charming, narrow pedestrian street flanked by quaint historic buildings and blooming flower boxes.", "example": "Lost in a picturesque alleyway in Venice, we stumbled upon a tiny glassblowing artisan workshop.", "translation": "زقاق وممر عتيق خلاب كلوحة فنية", "collocations": ["wander through a picturesque alleyway", "photograph a picturesque alleyway"], "synonyms": ["quaint lane"], "antonyms": ["drab thoroughfare"], "tags": ["architecture", "scenery"]},
    {"headword": "sun-drenched coastline", "pronunciation": "/sʌn drentʃt ˈkəʊstlaɪn/", "partOfSpeech": "noun", "definition": "A bright seaside shore that enjoys long, radiant hours of direct sunshine and azure water.", "example": "The Mediterranean's sun-drenched coastline beckoned sailing enthusiasts from across the continent.", "translation": "الساحل المشمس المغمور بنور الشمس", "collocations": ["sail the sun-drenched coastline", "relax on a sun-drenched coastline"], "synonyms": ["sunny shoreline"], "antonyms": ["gloomy coast"], "tags": ["beaches", "scenery"]},
    {"headword": "rugged mountain trail", "pronunciation": "/ˈrʌɡɪd ˈmaʊntɪn treɪl/", "partOfSpeech": "noun", "definition": "A steep, rocky, unpaved outdoor footpath cutting across wild wilderness terrain.", "example": "Scrambling up the rugged mountain trail required sturdy hiking boots and trekking poles.", "translation": "المسار الجبلي الوعر والصخري", "collocations": ["hike a rugged mountain trail", "navigate a rugged mountain trail"], "synonyms": ["stony mountain path"], "antonyms": ["paved pathway"], "tags": ["hiking", "nature"]},
    {"headword": "bustling night market", "pronunciation": "/ˈbʌslɪŋ naɪt ˈmɑːkɪt/", "partOfSpeech": "noun", "definition": "A lively open-air evening marketplace offering street street foods, souvenirs, and vibrant socializing.", "example": "Sampling steamed dumplings at Taipei's bustling night market is an unforgettable culinary adventure.", "translation": "السوق الليلي الصاخب والمفعم بالحيوية", "collocations": ["visit a bustling night market", "explore the bustling night market"], "synonyms": ["evening street bazaar"], "antonyms": [], "tags": ["food", "culture"]},
    {"headword": "tranquil lakeside retreat", "pronunciation": "/ˈtræŋkwɪl ˈleɪksaɪd rɪˈtriːt/", "partOfSpeech": "noun", "definition": "A peaceful holiday cabin or lodge situated on the serene shores of an uncrowded lake.", "example": "Renting a tranquil lakeside retreat in Finland allowed us to disconnect completely from urban stress.", "translation": "ملاذ ومنتجع هادئ على ضفاف البحيرة", "collocations": ["book a tranquil lakeside retreat", "stay at a tranquil lakeside retreat"], "synonyms": ["lakefront sanctuary"], "antonyms": [], "tags": ["relaxation", "nature"]},
    {"headword": "ancient ruins exploration", "pronunciation": "/ˈeɪnʃənt ˈruːɪnz ˌekspləˈreɪʃn/", "partOfSpeech": "noun", "definition": "Investigating archaeological remains of historic temples, amphitheaters, and stone cities.", "example": "Our ancient ruins exploration across Petra left us awestruck by Nabataean engineering ingenuity.", "translation": "استكشاف الآثار والأطلال التاريخية القديمة", "collocations": ["conduct an ancient ruins exploration", "day of ancient ruins exploration"], "synonyms": ["archaeological tour"], "antonyms": [], "tags": ["archaeology", "history"]},
    {"headword": "cross-country road trip", "pronunciation": "/krɒs ˈkʌntri rəʊd trɪp/", "partOfSpeech": "noun", "definition": "An extended driving journey traversing an entire nation from one coast to the other.", "example": "Driving Route 66 on a month-long cross-country road trip introduced us to vintage roadside diners.", "translation": "رحلة برية بالسيارة تجوب أرجاء البلاد", "collocations": ["take a cross-country road trip", "plan a cross-country road trip"], "synonyms": ["transcontinental drive"], "antonyms": [], "tags": ["road trip", "travel"]},
    {"headword": "overnight sleeper train", "pronunciation": "/ˌəʊvəˈnaɪt ˈsliːpə treɪn/", "partOfSpeech": "noun", "definition": "A passenger train equipped with private sleeper berths allowing travelers to rest during nighttime transit.", "example": "Boarding the overnight sleeper train from Cairo to Aswan saved both hotel expenses and travel time.", "translation": "قطار النوم الليلي المجهز بالأسرة", "collocations": ["ride the overnight sleeper train", "book an overnight sleeper train"], "synonyms": ["night train", "sleeper rail"], "antonyms": [], "tags": ["transit", "trains"]},
    {"headword": "quaint harbor village", "pronunciation": "/kweɪnt ˈhɑːbə ˈvɪlɪdʒ/", "partOfSpeech": "noun", "definition": "A charming, picturesque seaside fishing hamlet with colorful boats and stone cottages.", "example": "We enjoyed freshly grilled sea bass overlooking the bobbing skiffs in a quaint harbor village.", "translation": "قرية الميناء العتيقة والجميلة", "collocations": ["stroll through a quaint harbor village", "stay in a quaint harbor village"], "synonyms": ["picturesque fishing port"], "antonyms": ["industrial dock"], "tags": ["seaside", "architecture"]},
    {"headword": "desert dune safari", "pronunciation": "/ˈdezət djuːn səˈfɑːri/", "partOfSpeech": "noun", "definition": "An off-road excursion across massive wind-sculpted sand dunes, often featuring camel rides and star-gazing.", "example": "Camping beneath a carpet of stars after a thrilling desert dune safari was the highlight of Oman.", "translation": "رحلة سفاري الكثبان الرملية في الصحراء", "collocations": ["embark on a desert dune safari", "thrilling desert dune safari"], "synonyms": ["dune bashing excursion"], "antonyms": [], "tags": ["adventure", "desert"]},

    # Wilderness Expeditions, Encounters & Enduring Memories
    {"headword": "backpacking expedition", "pronunciation": "/ˈbækpækɪŋ ˌekspəˈdɪʃn/", "partOfSpeech": "noun", "definition": "An extended hiking or budget travel voyage carrying all shelter, food, and supplies in a rucksack.", "example": "A summer backpacking expedition through Southeast Asia taught him resourceful travel budgeting.", "translation": "رحلة ومغامرة السفر بحقيبة الظهر والترحال", "collocations": ["set off on a backpacking expedition", "rigors of a backpacking expedition"], "synonyms": ["wilderness trek"], "antonyms": ["luxury cruise"], "tags": ["travel", "budget"]},
    {"headword": "ferry crossing experience", "pronunciation": "/ˈferi ˈkrɒsɪŋ ɪkˈspɪəriəns/", "partOfSpeech": "noun", "definition": "A scenic voyage across a strait, fjord, or river aboard a passenger watercraft.", "example": "The ferry crossing experience through the Norwegian fjords offered majestic views of plunging waterfalls.", "translation": "تجربة عبور المياه وركوب العبّارة البحرية", "collocations": ["enjoy a ferry crossing experience", "turbulent ferry crossing experience"], "synonyms": ["water crossing"], "antonyms": [], "tags": ["transit", "nautical"]},
    {"headword": "charming seaside cafe", "pronunciation": "/ˈtʃɑːmɪŋ ˈsiːsaɪd kæˈfeɪ/", "partOfSpeech": "noun", "definition": "An attractive, welcoming small eatery situated directly on the shore overlooking the waves.", "example": "Sipping espresso at a charming seaside cafe while watching fishing boats was my morning bliss.", "translation": "مقهى ساحلي بديع يطل على البحر", "collocations": ["dine at a charming seaside cafe", "sit in a charming seaside cafe"], "synonyms": ["coastal bistro"], "antonyms": [], "tags": ["food", "seaside"]},
    {"headword": "bumpy dirt track", "pronunciation": "/ˈbʌmpi dɜːt træk/", "partOfSpeech": "noun", "definition": "An unpaved, uneven rural road riddled with ruts, rocks, and dust.", "example": "Our old jeep rattled violently as we bounced along the bumpy dirt track toward the mountain lodge.", "translation": "طريق ترابي وعر مليء بالمطبات والحفر", "collocations": ["navigate a bumpy dirt track", "rattle along a bumpy dirt track"], "synonyms": ["rough unpaved road"], "antonyms": ["smooth asphalt"], "tags": ["transit", "roads"]},
    {"headword": "panoramic lookout point", "pronunciation": "/ˌpænəˈræmɪk ˈlʊkaʊt pɔɪnt/", "partOfSpeech": "noun", "definition": "A designated elevated viewing platform offering wide unobstructed views of surrounding scenery.", "example": "Tourists gathered at the panoramic lookout point to capture the sunset reflecting across the canyon.", "translation": "مطل ونقطة مراقبة بانورامية للمناظر الطبيعية", "collocations": ["stop at a panoramic lookout point", "hike to a panoramic lookout point"], "synonyms": ["scenic viewpoint"], "antonyms": [], "tags": ["scenery", "views"]},
    {"headword": "local food tasting", "pronunciation": "/ˈləʊkl fuːd ˈteɪstɪŋ/", "partOfSpeech": "noun", "definition": "An experiential culinary activity sampling regional delicacies and indigenous recipes.", "example": "The gastronomic walking tour included a delicious local food tasting of smoked cheeses and flatbreads.", "translation": "تذوق وتجربة الأكلات والأطباق المحلية الأصيلة", "collocations": ["attend a local food tasting", "guided local food tasting"], "synonyms": ["regional food sampling"], "antonyms": [], "tags": ["food", "culinary"]},
    {"headword": "spontaneous itinerary", "pronunciation": "/spɒnˈteɪniəs aɪˈtɪnərəri/", "partOfSpeech": "noun", "definition": "A flexible travel schedule formed impulsively on the fly without rigid advance bookings.", "example": "Following a spontaneous itinerary allowed us to stay an extra week in the enchanting mountain village.", "translation": "برنامج رحلة عفوي ومفتوح دون مواعيد مسبقة", "collocations": ["adopt a spontaneous itinerary", "prefer a spontaneous itinerary"], "synonyms": ["unplanned travel schedule"], "antonyms": ["rigid itinerary"], "tags": ["travel", "flexibility"]},
    {"headword": "bilingual tour guide", "pronunciation": "/baɪˈlɪŋɡwəl tʊə ɡaɪd/", "partOfSpeech": "noun", "definition": "A licensed sightseeing guide fluent in two languages who interprets local history for foreign guests.", "example": "Our knowledgeable bilingual tour guide translated local legends and historical inscriptions flawlessly.", "translation": "مرشد سياحي ثنائي اللغة بطلاقة", "collocations": ["hire a bilingual tour guide", "accompanied by a bilingual tour guide"], "synonyms": ["multilingual guide"], "antonyms": [], "tags": ["tourism", "language"]},
    {"headword": "harrowing flight delay", "pronunciation": "/ˈhærəʊɪŋ flaɪt dɪˈleɪ/", "partOfSpeech": "noun", "definition": "An agonizingly long, stressful airport postponement caused by mechanical issues or severe storms.", "example": "A harrowing flight delay of fourteen hours in an overcrowded terminal tested everyone's patience.", "translation": "تأخير الرحلة الجوية المرهق للأعصاب", "collocations": ["endure a harrowing flight delay", "survive a harrowing flight delay"], "synonyms": ["excruciating flight delay"], "antonyms": ["on-time flight"], "tags": ["travel", "aviation"]},
    {"headword": "scenic overlook stop", "pronunciation": "/ˈsiːnɪk ˈəʊvəlʊk stɒp/", "partOfSpeech": "noun", "definition": "A roadside turnout designed for motorists to park safely and admire an expansive landscape.", "example": "We pulled into a scenic overlook stop along the canyon rim to photograph the roaring river below.", "translation": "استراحة جانبية لمشاهدة وتصوير المناظر الخلابة", "collocations": ["pull into a scenic overlook stop", "quick scenic overlook stop"], "synonyms": ["roadside viewpoint"], "antonyms": [], "tags": ["travel", "roads"]},
    {"headword": "remote hiking trail", "pronunciation": "/rɪˈməʊt ˈhaɪkɪŋ treɪl/", "partOfSpeech": "noun", "definition": "An isolated, quiet trekking path winding through pristine uninhabited natural wilderness.", "example": "The remote hiking trail led past glacial tarns where we encountered deer and golden eagles.", "translation": "مسار مشي ناءٍ في قلب الطبيعة البكر", "collocations": ["trek along a remote hiking trail", "secluded remote hiking trail"], "synonyms": ["wilderness trail"], "antonyms": ["paved city path"], "tags": ["hiking", "nature"]},
    {"headword": "peaceful countryside escape", "pronunciation": "/ˈpiːsfl ˈkʌntrisaɪd ɪˈskeɪp/", "partOfSpeech": "noun", "definition": "A rejuvenating getaway to a rural pastoral area to break away from metropolitan noise.", "example": "Spending a long bank holiday weekend in a stone cottage was the peaceful countryside escape we needed.", "translation": "مهرب وملاذ ريفي هادئ بعيداً عن صخب المدينة", "collocations": ["enjoy a peaceful countryside escape", "plan a peaceful countryside escape"], "synonyms": ["rural retreat"], "antonyms": ["chaotic city trip"], "tags": ["relaxation", "rural"]},
    {"headword": "historic cobblestone street", "pronunciation": "/hɪˈstɒrɪk ˈkɒblstəʊn striːt/", "partOfSpeech": "noun", "definition": "An ancient roadway paved with rounded natural river stones dating from earlier centuries.", "example": "Footsteps echoed rhythmically as we strolled down the historic cobblestone street in old Prague.", "translation": "شارع أثري معبد بالحجارة المرصوفة العتيقة", "collocations": ["walk along a historic cobblestone street", "quaint historic cobblestone street"], "synonyms": ["cobbled lane"], "antonyms": ["asphalt road"], "tags": ["architecture", "history"]},
    {"headword": "tropical island getaway", "pronunciation": "/ˈtrɒpɪkl ˈaɪlənd ˈɡetəweɪ/", "partOfSpeech": "noun", "definition": "A vacation journey to an exotic, palm-fringed island surrounded by warm turquoise seas.", "example": "After months of grueling winter cold, our tropical island getaway to Bali was pure paradise.", "translation": "عطلة واستجمام في جزيرة استوائية ساحرة", "collocations": ["book a tropical island getaway", "dream tropical island getaway"], "synonyms": ["exotic island holiday"], "antonyms": [], "tags": ["vacation", "islands"]},
    {"headword": "cultural festival experience", "pronunciation": "/ˈkʌltʃərəl ˈfestɪvl ɪkˈspɪəriəns/", "partOfSpeech": "noun", "definition": "Attending an authentic regional celebration featuring traditional costumes, dances, and ceremonies.", "example": "Dancing alongside lantern-bearing crowds during the cultural festival experience created lasting memories.", "translation": "تجربة حضور المهرجان الثقافي والاحتفال التراثي", "collocations": ["unforgettable cultural festival experience", "participate in a cultural festival experience"], "synonyms": ["traditional festival attendance"], "antonyms": [], "tags": ["culture", "events"]},
    {"headword": "mountain peak ascent", "pronunciation": "/ˈmaʊntɪn piːk əˈsent/", "partOfSpeech": "noun", "definition": "The challenging physical climb leading to the very highest summit of a mountain.", "example": "Starting our mountain peak ascent at three in the morning allowed us to reach the crest at sunrise.", "translation": "تسلق وصعود قمة الجبل الشاهقة", "collocations": ["attempt a mountain peak ascent", "rewarding mountain peak ascent"], "synonyms": ["summit climb"], "antonyms": ["descent"], "tags": ["mountains", "climbing"]},
    {"headword": "local hospitality gesture", "pronunciation": "/ˈləʊkl ˌhɒspɪˈtæləti ˈdʒestʃə/", "partOfSpeech": "noun", "definition": "An act of heartfelt generosity or welcoming kindness extended to travelers by native residents.", "example": "Inviting us to share their evening mint tea was a touching local hospitality gesture we will never forget.", "translation": "لفتة كرم وضيافة نابعة من أهالي المنطقة", "collocations": ["touched by a local hospitality gesture", "warm local hospitality gesture"], "synonyms": ["welcoming act"], "antonyms": ["hostile reception"], "tags": ["hospitality", "culture"]},
    {"headword": "travel journal entry", "pronunciation": "/ˈtrævl ˈdʒɜːnl ˈentri/", "partOfSpeech": "noun", "definition": "A written personal reflection recording the sensory details, emotions, and discoveries of a journey.", "example": "She concluded each adventurous day by writing a detailed travel journal entry beside her lantern.", "translation": "تدوينة في مذكرات ويوميات السفر", "collocations": ["write a travel journal entry", "poetic travel journal entry"], "synonyms": ["travel diary entry"], "antonyms": [], "tags": ["writing", "travel"]},
    {"headword": "unforgettable travel memory", "pronunciation": "/ˌʌnfəˈɡetəbl ˈtrævl ˈmeməri/", "partOfSpeech": "noun", "definition": "A vivid and deeply emotional travel moment that remains permanently etched in one's mind.", "example": "Watching the northern lights dance across the Arctic sky is an unforgettable travel memory.", "translation": "ذكرى سفر خالدة ومحفورة في الوجدان", "collocations": ["cherish an unforgettable travel memory", "spark an unforgettable travel memory"], "synonyms": ["indelible travel recollection"], "antonyms": [], "tags": ["memories", "travel"]},
    {"headword": "winding riverboat cruise", "pronunciation": "/ˈwaɪndɪŋ ˈrɪvəbəʊt kruːz/", "partOfSpeech": "noun", "definition": "A relaxed aquatic voyage aboard a riverboat navigating the meandering curves of a scenic river.", "example": "Our winding riverboat cruise down the Danube drifted past fairy-tale castles and terraced vineyards.", "translation": "رحلة نهرية بالقارب في مسارات النهر المتعرجة", "collocations": ["take a winding riverboat cruise", "relaxing winding riverboat cruise"], "synonyms": ["river cruise"], "antonyms": [], "tags": ["boats", "scenery"]},
    {"headword": "lively street scene", "pronunciation": "/ˈlaɪvli striːt siːn/", "partOfSpeech": "noun", "definition": "An energetic urban tableau of street vendors, performers, pedestrians, and open-air cafes.", "example": "Sitting outside with a gelato, we watched the lively street scene unfold across the Roman piazza.", "translation": "مشهد حيوي وصاخب ينبض بالحياة في شوارع المدينة", "collocations": ["observe a lively street scene", "vibrant lively street scene"], "synonyms": ["bustling urban scene"], "antonyms": ["deserted street"], "tags": ["city", "culture"]},
    {"headword": "majestic waterfall visit", "pronunciation": "/məˈdʒestɪk ˈwɔːtəfɔːl ˈvɪzɪt/", "partOfSpeech": "noun", "definition": "An excursion to stand beneath a towering, thundering cascade of rushing river water.", "example": "The deafening spray from our majestic waterfall visit at Victoria Falls drenched us from head to toe.", "translation": "زيارة شلالات المياه المهيبة والتمتع برذاذها", "collocations": ["awe-inspiring majestic waterfall visit", "plan a majestic waterfall visit"], "synonyms": ["cascade excursion"], "antonyms": [], "tags": ["nature", "water"]},
    {"headword": "foggy morning drive", "pronunciation": "/ˈfɒɡi ˈmɔːnɪŋ draɪv/", "partOfSpeech": "noun", "definition": "Traveling through dense early mist while navigating countryside roads or mountain passes.", "example": "A foggy morning drive across the Scottish Highlands lent an eerie, mythical atmosphere to the lochs.", "translation": "القيادة الصباحية الهادئة وسط الضباب الكثيف", "collocations": ["cautious foggy morning drive", "atmospheric foggy morning drive"], "synonyms": ["misty drive"], "antonyms": ["clear sunny drive"], "tags": ["roads", "weather"]},
    {"headword": "traditional handicraft market", "pronunciation": "/trəˈdɪʃənl ˈhændikrɑːft ˈmɑːkɪt/", "partOfSpeech": "noun", "definition": "A public venue where local artisans sell handmade pottery, textiles, woodwork, and jewelry.", "example": "We bought hand-painted ceramic bowls directly from the potter at the traditional handicraft market.", "translation": "سوق الحرف اليدوية والمصنوعات التقليدية", "collocations": ["browse a traditional handicraft market", "artisans at the traditional handicraft market"], "synonyms": ["artisan fair"], "antonyms": ["mass-market mall"], "tags": ["crafts", "shopping"]},
    {"headword": "sunset horizon view", "pronunciation": "/ˈsʌnset həˈraɪzn vjuː/", "partOfSpeech": "noun", "definition": "The breathtaking sight of the sun sinking below the edge of the sea or land in brilliant colors.", "example": "We lingered on the lighthouse terrace, mesmerized by the golden and crimson sunset horizon view.", "translation": "مشهد غروب الشمس الآسر في الأفق البعيد", "collocations": ["admire a sunset horizon view", "spectacular sunset horizon view"], "synonyms": ["dusk horizon panorama"], "antonyms": ["sunrise view"], "tags": ["sunset", "scenery"]}
]

grammar_84 = [
    {
        "title": "Narrative Tenses + Used to / Would",
        "explanation": "Mastering travel storytelling requires shifting seamlessly between past habitual actions and specific chronological incidents:\n\n1. 'Used to' for Past States and Discontinued Travel Habits:\n   - 'We used to prefer luxury resorts, but now we seek authentic local homestays.'\n   - 'There used to be an ancient cobblestone street where the highway now runs.'\n\n2. 'Would' for Repeated Past Narrative Actions (Atmospheric Habits):\n   - 'Every morning in the fishing village, we would wake early and stroll through the picturesque alleyway.'\n   - 'At dusk, we would sit by the charming seaside cafe, watching the sunset horizon view.'\n   (Note: 'Would' cannot describe past states like 'I would live in Spain'; use 'used to live').\n\n3. Narrative Tenses for Specific Incidents and Travel Mishaps:\n   - Past Continuous for scene-setting: 'The fog was drifting across the valley as we were driving along the winding coastal road.'\n   - Past Simple for main plot actions: 'Suddenly, our engine sputtered, and we took an unplanned detour.'\n   - Past Perfect for prior events: 'Before we reached the mountain pass, a local shepherd had warned us about the snow.'",
        "structures": [
            {"pattern": "Past Habit (would + base verb) + Specific Incident (Past Simple): 'We would wander through the village every afternoon until we discovered a hidden gem.'"},
            {"pattern": "Past State (used to + base verb) vs Present: 'I used to book packaged tours, but now I prefer an off-the-beaten-track route.'"},
            {"pattern": "Narrative Interruption: Past Continuous + when + Past Simple: 'While we were enjoying our ferry crossing experience, a pod of dolphins surfaced.'"}
        ],
        "examples": [
            {
                "sentence": "When we were traveling through Andalusia, we would often stop at a charming seaside cafe for breakfast.",
                "arabic": "عندما كنا نسافر عبر الأندلس، كنا نتوقف غالباً عند مقهى ساحلي بديع لتناول الإفطار.",
                "usesVocabulary": ["charming seaside cafe"]
            },
            {
                "sentence": "While we were navigating the winding coastal road, a sudden flat tire triggered an unplanned detour.",
                "arabic": "بينما كنا نعبر الطريق الساحلي المتعرج، أدى عطل مفاجئ في الإطار إلى انعطاف ومسار بديل غير مخطط له.",
                "usesVocabulary": ["winding coastal road", "unplanned detour"]
            },
            {
                "sentence": "Our family used to take an annual cross-country road trip, which left us with countless unforgettable travel memories.",
                "arabic": "اعتادت عائلتنا القيام برحلة برية تجوب أرجاء البلاد سنوياً، وهو ما ترك لنا ذكريات سفر خالدة لا تُحصى.",
                "usesVocabulary": ["cross-country road trip", "unforgettable travel memory"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "When I was young, I would live in a remote village stay.",
                "right": "When I was young, I used to live in a remote village / I used to book remote village stays.",
                "explanation": "Use 'used to' (never 'would') for past states and situations of residence, belonging, or state of being."
            },
            {
                "wrong": "Yesterday we would take a scenic detour to the lake.",
                "right": "Yesterday we took a scenic detour to the lake.",
                "explanation": "For a single, specific event on a particular day, use the Past Simple ('took'), not 'would'."
            }
        ]
    }
]

convs_84 = [
    {
        "title": "Traveler's Tale: The Himalayan Odyssey",
        "titleArabic": "حكاية مسافر: ملحمة الهيمالايا",
        "setting": "Two backpackers exchange stories in a mountain lodge tea house.",
        "lines": [
            {"speaker": "Leo", "text": "Did you take the main tourist bus, or did you venture along the off-the-beaten-track route?"},
            {"speaker": "Tara", "text": "We hired an old jeep! We rattled along a bumpy dirt track and took an unplanned detour when a landslide blocked the bridge."},
            {"speaker": "Leo", "text": "That sounds like a true backpacking expedition! How was the mountain pass trek?"},
            {"speaker": "Tara", "text": "Exhausting but sublime. When we reached the crest, a breathtaking vista of snow peaks greeted us."},
            {"speaker": "Leo", "text": "We used to stay at standard hotels, but on this journey we opted for a remote village stay with a local homestay."},
            {"speaker": "Tara", "text": "Their evening dinner was a touching local hospitality gesture that warmed our spirits."},
            {"speaker": "Leo", "text": "At dusk, we would sit by the stove writing each day's travel journal entry beside the villagers."},
            {"speaker": "Tara", "text": "That shared warmth remains my most cherished, unforgettable travel memory."}
        ],
        "vocabularyUsed": ["off-the-beaten-track route", "bumpy dirt track", "unplanned detour", "backpacking expedition", "mountain pass trek", "breathtaking vista", "remote village stay", "local homestay", "local hospitality gesture", "travel journal entry", "unforgettable travel memory"]
    },
    {
        "title": "Mediterranean Voyage: Coastal Discoveries",
        "titleArabic": "رحلة متوسطية: اكتشافات ساحلية",
        "setting": "Two friends review photos from their summer voyage through Greece and Italy.",
        "lines": [
            {"speaker": "Marcus", "text": "Look at this photograph of the sun-drenched coastline! Driving along that winding coastal road was magical."},
            {"speaker": "Chloe", "text": "Every morning, we would wander through a picturesque alleyway in that quaint harbor village."},
            {"speaker": "Marcus", "text": "And remember our hidden gem discovery? A tiny cove beside a charming seaside cafe."},
            {"speaker": "Chloe", "text": "Our ferry crossing experience was slightly delayed, but watching the sunset horizon view from the deck made up for it."},
            {"speaker": "Marcus", "text": "Before that, our lost luggage adventure in Athens had forced us to shop at a bustling night market."},
            {"speaker": "Chloe", "text": "We bought handmade sandals at a traditional handicraft market, and the lively street scene was unforgettable!"},
            {"speaker": "Marcus", "text": "A knowledgeable bilingual tour guide also led our ancient ruins exploration of the temple."},
            {"speaker": "Chloe", "text": "It was the ultimate peaceful countryside escape and coastal voyage combined."}
        ],
        "vocabularyUsed": ["sun-drenched coastline", "winding coastal road", "picturesque alleyway", "quaint harbor village", "hidden gem discovery", "charming seaside cafe", "ferry crossing experience", "sunset horizon view", "lost luggage adventure", "bustling night market", "traditional handicraft market", "lively street scene", "bilingual tour guide", "ancient ruins exploration", "peaceful countryside escape"]
    },
    {
        "title": "Cross-Country Transit: Trains, Dunes, and Detours",
        "titleArabic": "عبر البلاد: القطارات، الكثبان، والمسارات البديلة",
        "setting": "A travel writer is interviewed on a radio broadcast about epic transit journeys.",
        "lines": [
            {"speaker": "Host", "text": "You have traveled across six continents. What stands out as your most vivid train journey memory?"},
            {"speaker": "Writer", "text": "Boarding the overnight sleeper train across Egypt. At dawn, the golden dunes emerged outside the compartment window."},
            {"speaker": "Host", "text": "You also endured a harrowing flight delay before embarking on your desert dune safari, didn't you?"},
            {"speaker": "Writer", "text": "Yes, eighteen hours stranded! But we turned it into a spontaneous itinerary and booked a local food tasting."},
            {"speaker": "Host", "text": "Did you take a scenic detour to visit the waterfalls in the south?"},
            {"speaker": "Writer", "text": "We did! Pulling into a scenic overlook stop before our majestic waterfall visit took our breath away."},
            {"speaker": "Host", "text": "And the winding riverboat cruise along the upper Nile?"},
            {"speaker": "Writer", "text": "Every evening, the crew would play lutes as we drifted past date palm groves under a starry sky."}
        ],
        "vocabularyUsed": ["train journey memory", "overnight sleeper train", "harrowing flight delay", "desert dune safari", "spontaneous itinerary", "local food tasting", "scenic detour", "scenic overlook stop", "majestic waterfall visit", "winding riverboat cruise"]
    }
]

paras_84 = [
    {
        "title": "The Thrill of Adventure, Unplanned Detours, and Mountain Passes",
        "titleArabic": "إثارة المغامرة، المسارات البديلة، والممرات الجبلية",
        "text": "True travel magic rarely follows a rigid commercial brochure; it blossoms when adventurers embrace the unexpected. Setting off on an ambitious backpacking expedition or rugged mountain pass trek requires resilience against unpredictable weather. When sudden landslides block the main highway, taking an unplanned detour along a bumpy dirt track frequently leads to a stunning hidden gem discovery. After navigating a challenging mountain peak ascent, trekkers are rewarded with a breathtaking vista that redefines their understanding of natural majesty. By choosing an off-the-beaten-track route through remote hiking trails, travelers connect with pristine landscapes untouched by commercial tourist hordes.",
        "vocabularyUsed": ["backpacking expedition", "mountain pass trek", "unplanned detour", "bumpy dirt track", "hidden gem discovery", "mountain peak ascent", "breathtaking vista", "off-the-beaten-track route", "remote hiking trail"]
    },
    {
        "title": "Coastal Charms, Island Escapes, and Local Encounters",
        "titleArabic": "سحر السواحل، رحلات الجزر، واللقاءات المحلية الأصيلة",
        "text": "Few travel experiences surpass cruising along a sun-drenched coastline bordered by a winding coastal road. Arriving at a quaint harbor village, visitors wander through each picturesque alleyway paved as a historic cobblestone street, eventually resting at a charming seaside cafe. During a tropical island getaway, enjoying an unhurried ferry crossing experience allows one to savor the golden sunset horizon view across azure waters. Furthermore, opting for a local homestay rather than a generic hotel reveals heartwarming local hospitality gestures. Whether sampling street delicacies during a local food tasting or browsing a vibrant bazaar visit, cultural immersion enriches the traveler's soul.",
        "vocabularyUsed": ["sun-drenched coastline", "winding coastal road", "quaint harbor village", "picturesque alleyway", "historic cobblestone street", "charming seaside cafe", "tropical island getaway", "ferry crossing experience", "sunset horizon view", "local homestay", "local hospitality gesture", "local food tasting", "vibrant bazaar visit"]
    },
    {
        "title": "Transit Odysseys, Historical Ruins, and Enduring Memories",
        "titleArabic": "ملاحم السفر، الأطلال التاريخية، والذكريات الخالدة",
        "text": "Long-distance transit often generates the most treasured stories of any voyage. Boarding an overnight sleeper train transforms a simple commute into a cherished train journey memory, watching misty countryside awaken through compartment windows. Even travel mishaps—from an agonizing harrowing flight delay to an amusing lost luggage adventure—become legendary anecdotes recounted for decades. Conducting an ancient ruins exploration under the guidance of a bilingual tour guide or participating in an energetic cultural festival experience connects travelers to living history. Long after returning home, reading a personal travel journal entry preserves every unforgettable travel memory in vibrant clarity.",
        "vocabularyUsed": ["overnight sleeper train", "train journey memory", "harrowing flight delay", "lost luggage adventure", "ancient ruins exploration", "bilingual tour guide", "cultural festival experience", "travel journal entry", "unforgettable travel memory"]
    }
]

if __name__ == "__main__":
    write_day(83, vocab_83, grammar_83, convs_83, paras_83)
    write_day(84, vocab_84, grammar_84, convs_84, paras_84)
    print("Day 83 and Day 84 generated successfully.")
