# -*- coding: utf-8 -*-
"""Generate Day 73 and Day 74 for Stage 8."""

import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from curriculum_engine import write_day

# ==============================================================================
# DAY 73: Professional Communication (Workplace English in depth)
# Grammar: Participle Clauses (Basic)
# ==============================================================================

vocab_73 = [
    # Governance & Project Management
    {"headword": "executive summary", "pronunciation": "/ɪɡˈzekjətɪv ˈsʌməri/", "partOfSpeech": "noun", "definition": "A concise overview of a comprehensive report summarizing key findings and recommendations.", "example": "The executive summary synthesized the two-hundred-page audit into three actionable pages.", "translation": "ملخص تنفيذي / إيجاز قيادي لأهم نتائج التقرير", "collocations": ["read the executive summary", "prepare an executive summary"], "synonyms": ["management summary", "synopsis"], "antonyms": ["full report"], "tags": ["business", "reports"]},
    {"headword": "minutes of meeting", "pronunciation": "/ˈmɪnɪts əv ˈmiːtɪŋ/", "partOfSpeech": "noun", "definition": "The official written record of discussions, resolutions, and actions taken during a formal meeting.", "example": "The corporate secretary circulated the minutes of meeting within twenty-four hours.", "translation": "محضر الاجتماع / السجل الرسمي المكتوب لمجريات الجلسة", "collocations": ["approve the minutes of meeting", "record minutes of meeting"], "synonyms": ["meeting record", "official minutes"], "antonyms": [], "tags": ["business", "admin"]},
    {"headword": "standing agenda", "pronunciation": "/ˈstændɪŋ əˈdʒendə/", "partOfSpeech": "noun", "definition": "A permanent list of topics addressed regularly at every recurring meeting.", "example": "Risk assessment remains a permanent item on the board's standing agenda.", "translation": "جدول أعمال دائم / البنود الثابتة المتكررة في كل اجتماع", "collocations": ["adopt a standing agenda", "item on the standing agenda"], "synonyms": ["fixed agenda"], "antonyms": ["ad-hoc agenda"], "tags": ["meetings", "business"]},
    {"headword": "open action point", "pronunciation": "/ˈəʊpən ˈækʃn pɔɪnt/", "partOfSpeech": "noun", "definition": "A designated task from a meeting that has not yet been resolved or completed.", "example": "We have five open action points carrying over from last week's steering committee.", "translation": "بند إجرائي معلق / مهمة عمل غير منجزة بعد الاجتماع", "collocations": ["review open action points", "resolve an open action point"], "synonyms": ["pending action item"], "antonyms": ["closed action point"], "tags": ["projects", "meetings"]},
    {"headword": "follow-up task", "pronunciation": "/ˈfɒləʊ ʌp tɑːsk/", "partOfSpeech": "noun", "definition": "An assigned duty required as a consequence of previous discussions or decisions.", "example": "Assessing vendor compliance was assigned as a critical follow-up task for procurement.", "translation": "مهمة متابعة لاحقة / واجب تنفيذي تالٍ", "collocations": ["assign a follow-up task", "complete follow-up tasks"], "synonyms": ["subsequent task"], "antonyms": ["initial task"], "tags": ["workplace", "tasks"]},
    {"headword": "deliverable deadline", "pronunciation": "/dɪˈlɪvərəbl ˈdedlaɪn/", "partOfSpeech": "noun", "definition": "The formal agreed date by which a tangible project outcome must be submitted.", "example": "Meeting the deliverable deadline is crucial to maintain client confidence and contractual compliance.", "translation": "الموعد النهائي لتسليم المخرج التعاقدي", "collocations": ["miss a deliverable deadline", "meet the deliverable deadline"], "synonyms": ["submission date", "due date"], "antonyms": [], "tags": ["projects", "workplace"]},
    {"headword": "stakeholder update", "pronunciation": "/ˈsteɪkhəʊldə ˈʌpdeɪt/", "partOfSpeech": "noun", "definition": "A formal periodic report informing affected parties about project progress and milestones.", "example": "The quarterly stakeholder update outlined major infrastructure milestones and cost variances.", "translation": "إحاطة أصحاب المصلحة / تقرير إخباري دوري للأطراف المعنية", "collocations": ["provide a stakeholder update", "circulate a stakeholder update"], "synonyms": ["progress bulletin"], "antonyms": [], "tags": ["communication", "projects"]},
    {"headword": "due diligence report", "pronunciation": "/djuː ˈdɪlɪdʒəns rɪˈpɔːt/", "partOfSpeech": "noun", "definition": "A detailed assessment investigating the financial, legal, and operational status of an entity.", "example": "Before finalizing the acquisition, the board commissioned a due diligence report from external advisors.", "translation": "تقرير العناية الواجبة والفحص النافي للجهالة", "collocations": ["commission a due diligence report", "findings of the due diligence report"], "synonyms": ["investigative report"], "antonyms": [], "tags": ["finance", "legal"]},
    {"headword": "memo of understanding", "pronunciation": "/ˈmeməʊ əv ˌʌndəˈstændɪŋ/", "partOfSpeech": "noun", "definition": "A non-binding formal bilateral agreement outlining mutually agreed cooperation terms.", "example": "The two universities signed a memo of understanding to facilitate student research exchanges.", "translation": "مذكرة تفاهم رسمية بين طرفين", "collocations": ["sign a memo of understanding", "draft a memo of understanding"], "synonyms": ["memorandum of understanding", "MOU"], "antonyms": ["binding contract"], "tags": ["legal", "business"]},
    {"headword": "non-disclosure clause", "pronunciation": "/nɒn dɪsˈkləʊʒə klɔːz/", "partOfSpeech": "noun", "definition": "A contractual provision prohibiting parties from sharing proprietary or confidential information.", "example": "Every consultant must sign a contract containing a strict non-disclosure clause.", "translation": "بند عدم الإفصاح والسرية في العقد", "collocations": ["include a non-disclosure clause", "violate a non-disclosure clause"], "synonyms": ["confidentiality clause"], "antonyms": [], "tags": ["legal", "contracts"]},
    {"headword": "scope of work", "pronunciation": "/skəʊp əv wɜːk/", "partOfSpeech": "noun", "definition": "The formal contractual document describing specific deliverables, boundaries, and activities.", "example": "The vendor refused the extra customization because it fell outside the agreed scope of work.", "translation": "نطاق العمل المحدد تعاقدياً", "collocations": ["define the scope of work", "outside the scope of work"], "synonyms": ["statement of work", "SOW"], "antonyms": [], "tags": ["contracts", "projects"]},
    {"headword": "terms of reference", "pronunciation": "/tɜːmz əv ˈrefrəns/", "partOfSpeech": "noun", "definition": "The formal definitions and boundaries guiding an inquiry, committee, or consultancy project.", "example": "The parliamentary committee published clear terms of reference prior to launching the investigation.", "translation": "الشروط المرجعية / اختصاصات ومحددات عمل اللجنة", "collocations": ["set the terms of reference", "within the terms of reference"], "synonyms": ["mandate", "scope of inquiry"], "antonyms": [], "tags": ["governance", "projects"]},
    {"headword": "initiative roadmap", "pronunciation": "/ɪˈnɪʃətɪv ˈrəʊdmæp/", "partOfSpeech": "noun", "definition": "A high-level strategic timeline visualizing the phases and milestones of a program.", "example": "The technology director presented a three-year initiative roadmap for enterprise cloud transition.", "translation": "خارطة طريق المبادرة الاستراتيجية", "collocations": ["present an initiative roadmap", "execute the initiative roadmap"], "synonyms": ["strategic roadmap", "implementation plan"], "antonyms": [], "tags": ["strategy", "planning"]},
    {"headword": "risk register", "pronunciation": "/rɪsk ˈredʒɪstə/", "partOfSpeech": "noun", "definition": "A management document logging identified potential risks, their severity, and mitigation plans.", "example": "Supply chain disruption was categorized as high probability and added to the risk register.", "translation": "سجل المخاطر وتدابير معالجتها", "collocations": ["maintain a risk register", "log in the risk register"], "synonyms": ["risk log"], "antonyms": [], "tags": ["risk", "projects"]},
    {"headword": "issue log", "pronunciation": "/ˈɪʃuː lɒɡ/", "partOfSpeech": "noun", "definition": "A tracking record of actual problems and hurdles currently impacting project execution.", "example": "The technical lead updated the issue log daily during the critical testing phase.", "translation": "سجل المعضلات والمشاكل التشغيلية القائمة", "collocations": ["update the issue log", "escalate from the issue log"], "synonyms": ["problem tracker"], "antonyms": [], "tags": ["projects", "operations"]},
    {"headword": "change request", "pronunciation": "/tʃeɪndʒ rɪˈkwest/", "partOfSpeech": "noun", "definition": "A formal proposal to modify project scope, specifications, timeline, or agreed budget.", "example": "Any alteration to the architectural blueprint requires an approved formal change request.", "translation": "طلب تغيير رسمي في بنود المشروع أو نطاقه", "collocations": ["submit a change request", "approve a change request"], "synonyms": ["scope modification request"], "antonyms": [], "tags": ["projects", "processes"]},
    {"headword": "sign-off authority", "pronunciation": "/ˈsaɪn ɒf ɔːˈθɒrɪti/", "partOfSpeech": "noun", "definition": "The designated institutional power or executive position authorized to give formal approval.", "example": "Only the chief financial officer has the sign-off authority for expenditures exceeding fifty thousand dollars.", "translation": "صلاحية التوقيع والمصادقة النهائية الرسمية", "collocations": ["hold sign-off authority", "delegate sign-off authority"], "synonyms": ["approval authority"], "antonyms": [], "tags": ["management", "governance"]},
    {"headword": "escalation path", "pronunciation": "/ˌeskəˈleɪʃn pɑːθ/", "partOfSpeech": "noun", "definition": "The formal hierarchical sequence used to refer unresolved issues to senior leadership.", "example": "Support staff followed the predefined escalation path when server outage exceeded thirty minutes.", "translation": "مسار التصعيد الإداري للمشاكل العالقة", "collocations": ["trigger the escalation path", "follow the escalation path"], "synonyms": ["escalation procedure"], "antonyms": [], "tags": ["management", "operations"]},

    # Organizational Structure & Collaboration
    {"headword": "organizational chart", "pronunciation": "/ˌɔːɡənaɪˈzeɪʃənl tʃɑːt/", "partOfSpeech": "noun", "definition": "A diagram illustrating the internal hierarchy, roles, and reporting relationships of an enterprise.", "example": "The revised organizational chart clarified department divisions following the merger.", "translation": "الهيكل التنظيمي / المخطط الهرمي للمؤسسة", "collocations": ["publish an organizational chart", "consult the organizational chart"], "synonyms": ["org chart", "hierarchy diagram"], "antonyms": [], "tags": ["hr", "management"]},
    {"headword": "reporting line", "pronunciation": "/rɪˈpɔːtɪŋ laɪn/", "partOfSpeech": "noun", "definition": "The direct formal chain of authority connecting an employee to their supervising manager.", "example": "Establishing a direct reporting line to the CEO ensured that compliance received top priority.", "translation": "خط التبعية الإدارية والمسؤولية المباشرة", "collocations": ["direct reporting line", "clear reporting line"], "synonyms": ["chain of command"], "antonyms": [], "tags": ["hr", "management"]},
    {"headword": "dotted-line reporting", "pronunciation": "/ˈdɒtɪd laɪn rɪˈpɔːtɪŋ/", "partOfSpeech": "noun", "definition": "A secondary, advisory reporting relationship alongside an employee's primary direct manager.", "example": "The regional financial controller has dotted-line reporting to the global head of ethics.", "translation": "التبعية الإدارية غير المباشرة / خط تقارير استشاري ثانوي", "collocations": ["maintain dotted-line reporting", "dotted-line reporting relationship"], "synonyms": ["secondary reporting"], "antonyms": ["solid-line reporting"], "tags": ["hr", "management"]},
    {"headword": "matrix organization", "pronunciation": "/ˈmeɪtrɪks ˌɔːɡənaɪˈzeɪʃn/", "partOfSpeech": "noun", "definition": "An organizational structure where employees report to multiple managers across functions and projects.", "example": "Working in a matrix organization requires superior communication and prioritization skills.", "translation": "الهيكل التنظيمي المصفوفي متعدد المدراء", "collocations": ["operate as a matrix organization", "transition to a matrix organization"], "synonyms": ["matrix structure"], "antonyms": ["hierarchical organization"], "tags": ["management", "strategy"]},
    {"headword": "cross-functional team", "pronunciation": "/krɒs ˈfʌŋkʃənl tiːm/", "partOfSpeech": "noun", "definition": "A group composed of members from different departmental disciplines working toward a common goal.", "example": "The cross-functional team included representatives from engineering, design, marketing, and legal.", "translation": "فريق متعدد الوظائف والتخصصات", "collocations": ["lead a cross-functional team", "assemble a cross-functional team"], "synonyms": ["interdisciplinary team"], "antonyms": ["siloed team"], "tags": ["teamwork", "management"]},
    {"headword": "working group", "pronunciation": "/ˈwɜːkɪŋ ɡruːp/", "partOfSpeech": "noun", "definition": "A focused committee formed to study, report on, or resolve a particular operational issue.", "example": "The regulatory working group produced a white paper on autonomous vehicle liability.", "translation": "فريق عمل استشاري مصغر ومكلف بمهمة محددة", "collocations": ["convene a working group", "chair a working group"], "synonyms": ["study group", "committee"], "antonyms": [], "tags": ["governance", "projects"]},
    {"headword": "task force", "pronunciation": "/ˈtɑːsk fɔːs/", "partOfSpeech": "noun", "definition": "A temporary team assembled specifically to tackle an urgent, high-stakes operational problem.", "example": "The hospital appointed an emergency task force to manage the winter flu surge.", "translation": "فريق عمل طارئ لمهمة خاصة وعاجلة", "collocations": ["deploy a task force", "form a task force"], "synonyms": ["action team", "special commission"], "antonyms": ["standing committee"], "tags": ["management", "operations"]},

    # Performance, HR & Talent Management
    {"headword": "key performance indicator", "pronunciation": "/kiː pəˈfɔːməns ˈɪndɪkeɪtə/", "partOfSpeech": "noun", "definition": "A quantifiable metric used to measure progress toward achieving critical operational objectives.", "example": "Customer retention rate serves as a key performance indicator for the customer success team.", "translation": "مؤشر أداء رئيسي لقياس الإنجاز", "collocations": ["track key performance indicators", "meet key performance indicators"], "synonyms": ["KPI"], "antonyms": [], "tags": ["management", "metrics"]},
    {"headword": "balanced scorecard", "pronunciation": "/ˈbælənst ˈskɔːkɑːd/", "partOfSpeech": "noun", "definition": "A strategic management performance metric used to identify and improve various internal business functions.", "example": "The executive team used a balanced scorecard to evaluate financial, customer, and internal process performance.", "translation": "بطاقة الأداء المتوازن الشاملة", "collocations": ["implement a balanced scorecard", "review the balanced scorecard"], "synonyms": ["performance scorecard"], "antonyms": [], "tags": ["strategy", "metrics"]},
    {"headword": "benchmarking exercise", "pronunciation": "/ˈbentʃmɑːkɪŋ ˈeksəsaɪz/", "partOfSpeech": "noun", "definition": "A structured comparative evaluation of company processes and metrics against industry leaders.", "example": "The benchmarking exercise demonstrated that our billing turnaround was twenty percent slower than competitors.", "translation": "دراسة المقارنة المعيارية بأفضل الممارسات", "collocations": ["conduct a benchmarking exercise", "benchmarking exercise findings"], "synonyms": ["comparative study"], "antonyms": [], "tags": ["strategy", "analytics"]},
    {"headword": "gap analysis", "pronunciation": "/ɡæp əˈnæləsɪs/", "partOfSpeech": "noun", "definition": "An assessment method determining the difference between current capabilities and desired targets.", "example": "Conducting a comprehensive gap analysis revealed severe deficiencies in our cyber-defense readiness.", "translation": "تحليل الفجوة بين الواقع الحالي والمستهدف", "collocations": ["perform a gap analysis", "gap analysis results"], "synonyms": ["needs assessment"], "antonyms": [], "tags": ["analytics", "strategy"]},
    {"headword": "needs assessment", "pronunciation": "/niːdz əˈsesmənt/", "partOfSpeech": "noun", "definition": "A systematic process for determining and addressing needs or gaps between current and desired conditions.", "example": "The human resources division completed a training needs assessment across all regional offices.", "translation": "تقييم وتحديد الاحتياجات التدريبية والتشغيلية", "collocations": ["conduct a needs assessment", "comprehensive needs assessment"], "synonyms": ["needs analysis"], "antonyms": [], "tags": ["hr", "planning"]},
    {"headword": "corrective action report", "pronunciation": "/kəˈrektɪv ˈækʃn rɪˈpɔːt/", "partOfSpeech": "noun", "definition": "A formal documentation outlining remedial steps taken to resolve a discovered defect or violation.", "example": "Following the safety inspection, the factory manager drafted a corrective action report for regulators.", "translation": "تقرير الإجراءات التصحيحية لتدارك الخلل", "collocations": ["file a corrective action report", "review a corrective action report"], "synonyms": ["remediation report", "CAR"], "antonyms": [], "tags": ["quality", "compliance"]},
    {"headword": "preventive measure", "pronunciation": "/prɪˈventɪv ˈmeʒə/", "partOfSpeech": "noun", "definition": "An action implemented beforehand to avert future operational failures or risk exposure.", "example": "Installing multi-factor authentication was a vital preventive measure against data breaches.", "translation": "تدبير وقائي استباقي لمنع وقوع الخطأ", "collocations": ["take preventive measures", "implement preventive measures"], "synonyms": ["precautionary action"], "antonyms": ["reactive response"], "tags": ["risk", "safety"]},
    {"headword": "knowledge transfer", "pronunciation": "/ˈnɒlɪdʒ ˈtrænsfɜː/", "partOfSpeech": "noun", "definition": "The practical sharing of expertise, information, and skills from experienced staff to colleagues.", "example": "Effective knowledge transfer ensures institutional memory is preserved when senior engineers retire.", "translation": "نقل المعرفة والخبرات المؤسسية وتداولها", "collocations": ["facilitate knowledge transfer", "structured knowledge transfer"], "synonyms": ["information sharing", "expertise handoff"], "antonyms": ["knowledge hoarding"], "tags": ["hr", "management"]},
    {"headword": "onboarding process", "pronunciation": "/ˈɒnbɔːdɪŋ ˈprəʊses/", "partOfSpeech": "noun", "definition": "The formal orientation and integration procedure for assimilating newly hired employees.", "example": "A well-structured onboarding process boosts retention and shortens the ramp-up time for new hires.", "translation": "إجراءات التهيئة والتأهيل والاندماج للموظفين الجدد", "collocations": ["streamline the onboarding process", "complete the onboarding process"], "synonyms": ["induction program"], "antonyms": ["offboarding process"], "tags": ["hr", "recruitment"]},
    {"headword": "offboarding checklist", "pronunciation": "/ˈɒfbɔːdɪŋ ˈtʃeklɪst/", "partOfSpeech": "noun", "definition": "A systematic protocol ensuring all departure duties, access revocations, and asset returns occur.", "example": "The IT team finalized the offboarding checklist to revoke database access on the employee's last day.", "translation": "قائمة التحقق الرسمية لإنهاء خدمة الموظف", "collocations": ["follow the offboarding checklist", "complete the offboarding checklist"], "synonyms": ["exit checklist"], "antonyms": ["onboarding checklist"], "tags": ["hr", "security"]},
    {"headword": "exit interview", "pronunciation": "/ˈeksɪt ˈɪntəvjuː/", "partOfSpeech": "noun", "definition": "A final formal interview with a departing employee to gather honest feedback on workplace culture.", "example": "During her exit interview, the software architect highlighted chronic delays in procurement.", "translation": "مقابلة نهاية الخدمة واستطلاع آراء المغادر", "collocations": ["conduct an exit interview", "feedback during the exit interview"], "synonyms": ["departure interview"], "antonyms": [], "tags": ["hr", "culture"]},
    {"headword": "appraisal cycle", "pronunciation": "/əˈpreɪzl ˈsaɪkl/", "partOfSpeech": "noun", "definition": "The recurring annual or biannual period during which employee job performance is formally evaluated.", "example": "Managers are expected to submit all performance reviews before the annual appraisal cycle concludes.", "translation": "دورة التقييم الدوري لأداء الموظفين", "collocations": ["annual appraisal cycle", "launch the appraisal cycle"], "synonyms": ["performance review cycle"], "antonyms": [], "tags": ["hr", "management"]},
    {"headword": "360-degree feedback", "pronunciation": "/ˌθriː ˈsɪksti dɪˌɡriː ˈfiːdbæk/", "partOfSpeech": "noun", "definition": "A performance evaluation method gathering confidential ratings from peers, subordinates, and managers.", "example": "The leadership development program utilized 360-degree feedback to identify blind spots in executives.", "translation": "التقييم الشامل بزاوية 360 درجة من كافة الزملاء والرؤساء", "collocations": ["gather 360-degree feedback", "receive 360-degree feedback"], "synonyms": ["multi-rater feedback"], "antonyms": ["top-down evaluation"], "tags": ["hr", "leadership"]},
    {"headword": "stretch goal", "pronunciation": "/stretʃ ɡəʊl/", "partOfSpeech": "noun", "definition": "An ambitious, challenging performance target intentionally set beyond standard expectations.", "example": "Achieving thirty percent growth was a stretch goal that inspired the marketing team to innovate.", "translation": "هدف طموح وفائق التحدي لتحفيز الأداء الاستثنائي", "collocations": ["set a stretch goal", "reach a stretch goal"], "synonyms": ["ambitious target"], "antonyms": ["baseline target"], "tags": ["goals", "motivation"]},
    {"headword": "professional development plan", "pronunciation": "/prəˈfeʃənl dɪˈveləpmənt plæn/", "partOfSpeech": "noun", "definition": "A tailored roadmap documenting an employee's career goals, skill gaps, and learning activities.", "example": "Each employee collaborates with their supervisor to draft a personalized professional development plan.", "translation": "خطة التطوير والنمو المهني الفردية", "collocations": ["create a professional development plan", "execute a professional development plan"], "synonyms": ["PDP", "career roadmap"], "antonyms": [], "tags": ["hr", "career"]},
    {"headword": "mentoring relationship", "pronunciation": "/ˈmentɔːrɪŋ rɪˈleɪʃnʃɪp/", "partOfSpeech": "noun", "definition": "A developmental partnership where an experienced professional guides and advises a less-experienced colleague.", "example": "A strong mentoring relationship helped the junior lawyer navigate complex courtroom procedures.", "translation": "علاقة توجيه ورعاية مهنية بين خبير ومبتدئ", "collocations": ["foster a mentoring relationship", "benefit from a mentoring relationship"], "synonyms": ["mentorship"], "antonyms": [], "tags": ["career", "leadership"]},
    {"headword": "coaching session", "pronunciation": "/ˈkəʊtʃɪŋ ˈseʃn/", "partOfSpeech": "noun", "definition": "A structured one-on-one meeting aimed at improving specific practical workplace competencies.", "example": "The sales executive attended a weekly coaching session to refine her negotiation skills.", "translation": "جلسة تدريب وتطوير مهني مخصصة", "collocations": ["schedule a coaching session", "attend a coaching session"], "synonyms": ["training session"], "antonyms": [], "tags": ["hr", "training"]},
    {"headword": "competency framework", "pronunciation": "/ˈkɒmpɪtənsi ˈfreɪmwɜːk/", "partOfSpeech": "noun", "definition": "A structured model detailing the specific knowledge, skills, and attributes required for roles.", "example": "The human capital team redesigned the competency framework to emphasize digital fluency.", "translation": "إطار الجدارات والكفاءات الوظيفية المعتمد", "collocations": ["align with the competency framework", "establish a competency framework"], "synonyms": ["skill framework"], "antonyms": [], "tags": ["hr", "standards"]},
    {"headword": "succession planning", "pronunciation": "/səkˈseʃn ˈplænɪŋ/", "partOfSpeech": "noun", "definition": "A business strategy for identifying and developing future leaders to replace departing executives.", "example": "Prudent succession planning guarantees organizational stability when senior leaders step down.", "translation": "التخطيط للتعاقب الوظيفي وإعداد قادة المستقبل", "collocations": ["engage in succession planning", "strategic succession planning"], "synonyms": ["leadership succession"], "antonyms": [], "tags": ["hr", "leadership"]},
    {"headword": "talent pipeline", "pronunciation": "/ˈtælənt ˈpaɪplaɪn/", "partOfSpeech": "noun", "definition": "A pool of qualified potential candidates prepared to fill future organizational vacancies.", "example": "Our internship initiative feeds a steady talent pipeline of skilled young engineers.", "translation": "رافد الكفاءات / بنك المواهب المرشحة للتوظيف المستقبلي", "collocations": ["build a talent pipeline", "strengthen the talent pipeline"], "synonyms": ["candidate pool"], "antonyms": [], "tags": ["recruitment", "hr"]},
    {"headword": "workforce planning", "pronunciation": "/ˈwɜːkfɔːs ˈplænɪŋ/", "partOfSpeech": "noun", "definition": "The strategic alignment of enterprise business goals with its human resources requirements.", "example": "Long-term workforce planning anticipates demographic shifts and rising automation in manufacturing.", "translation": "تخطيط القوى العاملة والاحتياجات البشرية", "collocations": ["strategic workforce planning", "conduct workforce planning"], "synonyms": ["headcount planning"], "antonyms": [], "tags": ["hr", "strategy"]},
    {"headword": "organizational development", "pronunciation": "/ˌɔːɡənaɪˈzeɪʃənl dɪˈveləpmənt/", "partOfSpeech": "noun", "definition": "A planned, organization-wide effort to increase effectiveness through structured behavioral interventions.", "example": "The director of organizational development oversaw culture transformation and leadership alignment.", "translation": "التطوير المؤسسي والتنظيمي الشامل", "collocations": ["specialize in organizational development", "drive organizational development"], "synonyms": ["OD"], "antonyms": [], "tags": ["hr", "management"]},
    {"headword": "change management", "pronunciation": "/tʃeɪndʒ ˈmænɪdʒmənt/", "partOfSpeech": "noun", "definition": "A systematic approach to transitioning individuals, teams, and enterprises to desired future states.", "example": "Effective change management mitigated staff resistance during the corporate software rollout.", "translation": "إدارة التغيير المؤسسي والتكيف معه", "collocations": ["lead change management", "change management strategy"], "synonyms": ["transformation management"], "antonyms": [], "tags": ["management", "leadership"]},
    {"headword": "business continuity plan", "pronunciation": "/ˈbɪznəs ˌkɒntɪˈnjuːəti plæn/", "partOfSpeech": "noun", "definition": "A documented system for preventing and recovering from potential enterprise operational threats.", "example": "The cyber-attack prompted executive activation of the corporate business continuity plan.", "translation": "خطة استمرارية الأعمال ومجابهة الطوارئ والأزمات", "collocations": ["activate the business continuity plan", "update the business continuity plan"], "synonyms": ["BCP", "disaster recovery plan"], "antonyms": [], "tags": ["risk", "operations"]},
    {"headword": "internal audit", "pronunciation": "/ɪnˈtɜːnl ˈɔːdɪt/", "partOfSpeech": "noun", "definition": "An independent, objective assurance activity designed to improve an organization's operations.", "example": "An exhaustive internal audit verified that compliance procedures conformed to international standards.", "translation": "تدقيق ومراجعة داخلية مستقلة للعمليات", "collocations": ["conduct an internal audit", "findings of the internal audit"], "synonyms": ["internal review"], "antonyms": ["external audit"], "tags": ["audit", "compliance"]}
]

grammar_73 = [
    {
        "title": "Participle Clauses (Basic)",
        "explanation": "Participle clauses (-ing or -ed clauses) allow us to combine ideas economically and express relationships such as time, cause, condition, or result without unnecessary conjunctions. They are especially prevalent in formal, business, and academic registers.\n\n1. Present Participle (-ing): Active meaning, representing simultaneous actions, causes, or immediate sequences.\n   Example: 'Reviewing the risk register, the director noticed three open action points.' (= While / Because she was reviewing...)\n\n2. Past Participle (-ed): Passive meaning, representing actions done to the subject.\n   Example: 'Outlined in the scope of work, all deliverable deadlines must be respected.' (= Because they are outlined...)\n\n3. Perfect Participle (Having + past participle): Emphasizes that an action was completed before the main action occurred.\n   Example: 'Having completed the gap analysis, the team designed a customized coaching session.'\n\nCRITICAL RULE (Dangling Participles): The implied subject of the participle clause must match the grammatical subject of the main clause. Writing 'Reviewing the minutes of meeting, the decision was made' is incorrect because 'the decision' cannot review minutes; you must write: 'Reviewing the minutes of meeting, the board confirmed the decision.'",
        "structures": [
            {"pattern": "Present Participle (-ing clause), Subject + Verb: 'Leading the cross-functional team, Sarah resolved several bottlenecks.'"},
            {"pattern": "Past Participle (-ed clause), Subject + Verb: 'Documented in the issue log, the technical glitches were escalated immediately.'"},
            {"pattern": "Perfect Participle (Having + V3), Subject + Verb: 'Having signed the memo of understanding, both executives celebrated the partnership.'"}
        ],
        "examples": [
            {
                "sentence": "Having finalized the executive summary, the director presented the findings to the steering committee.",
                "arabic": "بعد أن أتم الملخص التنفيذي، استعرض المدير النتائج أمام لجنة التوجيه.",
                "usesVocabulary": ["executive summary"]
            },
            {
                "sentence": "Conducting a rigorous internal audit, the compliance officer uncovered deficiencies in the risk register.",
                "arabic": "أثناء إجرائه تدقيقاً داخلياً صارماً، كشف مسؤول الامتثال عن أوجه قصور في سجل المخاطر.",
                "usesVocabulary": ["internal audit", "risk register"]
            },
            {
                "sentence": "Presented with the balanced scorecard, the executive board approved a new talent pipeline initiative.",
                "arabic": "عند عرض بطاقة الأداء المتوازن عليهم، وافق مجلس الإدارة التنفيذي على مبادرة جديدة لرافد الكفاءات.",
                "usesVocabulary": ["balanced scorecard", "talent pipeline"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "Reviewing the minutes of meeting, several errors were discovered by the secretary.",
                "right": "Reviewing the minutes of meeting, the secretary discovered several errors.",
                "explanation": "Avoid dangling participles. The subject performing the action ('the secretary') must be the subject of the main clause, not 'several errors'."
            },
            {
                "wrong": "Having sign the memo of understanding, they began project execution.",
                "right": "Having signed the memo of understanding, they began project execution.",
                "explanation": "A perfect participle requires 'Having' followed by the past participle (V3), not the base form."
            }
        ]
    }
]

convs_73 = [
    {
        "title": "Quarterly Steering Committee: Governance and Deliverables",
        "titleArabic": "لجنة التوجيه الربع سنوية: الحوكمة والمخرجات",
        "setting": "Senior executives meet in the corporate boardroom to review project status.",
        "lines": [
            {"speaker": "Chairperson", "text": "Having reviewed the executive summary, I propose we approve the minutes of meeting from last month."},
            {"speaker": "Project Director", "text": "Agreed. Moving to the standing agenda, we still have one open action point regarding the deliverable deadline for phase two."},
            {"speaker": "Operations VP", "text": "Outlined in the scope of work, that deadline depends on vendor sign-off authority. We submitted a formal change request yesterday."},
            {"speaker": "Project Director", "text": "Noting the vendor delay, I updated both the risk register and the issue log this morning."},
            {"speaker": "Chairperson", "text": "Good diligence. If unaddressed, does this follow-up task trigger the formal escalation path?"},
            {"speaker": "Operations VP", "text": "Yes. However, consulting the terms of reference, we have three business days before leadership intervention is mandated."},
            {"speaker": "Project Director", "text": "I will prepare an emergency stakeholder update so external partners remain fully informed."},
            {"speaker": "Chairperson", "text": "Excellent. Make sure our non-disclosure clause is respected during any external communications."}
        ],
        "vocabularyUsed": ["executive summary", "minutes of meeting", "standing agenda", "open action point", "deliverable deadline", "scope of work", "sign-off authority", "change request", "risk register", "issue log", "follow-up task", "escalation path", "terms of reference", "stakeholder update", "non-disclosure clause"]
    },
    {
        "title": "HR Strategy Session: Restructuring and Talent Management",
        "titleArabic": "جلسة استراتيجية الموارد البشرية: إعادة الهيكلة وإدارة المواهب",
        "setting": "The HR Director and an Organizational Development Consultant discuss structural reforms.",
        "lines": [
            {"speaker": "HR Director", "text": "Examine our revised organizational chart. We are transitioning toward a matrix organization across our international branches."},
            {"speaker": "Consultant", "text": "Having observed similar transitions, I recommend establishing clear reporting lines alongside dotted-line reporting to prevent role ambiguity."},
            {"speaker": "HR Director", "text": "We assembled a cross-functional team and a dedicated working group to draft the competency framework."},
            {"speaker": "Consultant", "text": "Completing a thorough gap analysis should be your top priority before scheduling any coaching session."},
            {"speaker": "HR Director", "text": "We also completed a needs assessment and introduced 360-degree feedback for our upcoming appraisal cycle."},
            {"speaker": "Consultant", "text": "Splendid. Linking that feedback to each employee's professional development plan will nurture a robust talent pipeline."},
            {"speaker": "HR Director", "text": "Precisely. Our leadership succession planning depends on building these internal capabilities."},
            {"speaker": "Consultant", "text": "Setting an ambitious stretch goal for middle management will further accelerate the transformation."}
        ],
        "vocabularyUsed": ["organizational chart", "matrix organization", "reporting line", "dotted-line reporting", "cross-functional team", "working group", "competency framework", "gap analysis", "coaching session", "needs assessment", "360-degree feedback", "appraisal cycle", "professional development plan", "talent pipeline", "succession planning", "stretch goal"]
    },
    {
        "title": "Audit Review and Operational Risk Meeting",
        "titleArabic": "مراجعة التدقيق واجتماع المخاطر التشغيلية",
        "setting": "The Chief Risk Officer and Head of Internal Audit review post-inspection findings.",
        "lines": [
            {"speaker": "Chief Risk Officer", "text": "Having examined the corrective action report, what are the primary findings from the internal audit?"},
            {"speaker": "Head of Audit", "text": "Highlighted during the benchmarking exercise, our business continuity plan lacks automated disaster recovery tests."},
            {"speaker": "Chief Risk Officer", "text": "That poses a systemic threat. Implementing an immediate preventive measure must be our primary deliverable."},
            {"speaker": "Head of Audit", "text": "Furthermore, analyzing departing staff feedback from the exit interview, knowledge transfer between retiring specialists and new hires is deficient."},
            {"speaker": "Chief Risk Officer", "text": "Let us deploy a specialized task force to standardize the offboarding checklist and overhaul the onboarding process."},
            {"speaker": "Head of Audit", "text": "Applying structured change management principles will ensure widespread compliance across all regional divisions."},
            {"speaker": "Chief Risk Officer", "text": "Agreed. I will also incorporate mentoring relationship benchmarks into our annual balanced scorecard."},
            {"speaker": "Head of Audit", "text": "Excellent. We shall monitor every key performance indicator diligently throughout next quarter."}
        ],
        "vocabularyUsed": ["corrective action report", "internal audit", "benchmarking exercise", "business continuity plan", "preventive measure", "exit interview", "knowledge transfer", "task force", "offboarding checklist", "onboarding process", "change management", "mentoring relationship", "balanced scorecard", "key performance indicator"]
    }
]

paras_73 = [
    {
        "title": "Strategic Project Management and Governance",
        "titleArabic": "إدارة المشاريع الاستراتيجية والحوكمة المؤسسية",
        "text": "Effective corporate governance requires systematic tools to monitor complex deliverables. Beginning with a comprehensive executive summary, project sponsors review the initiative roadmap to verify strategic alignment. Formulating clear terms of reference establishes explicit accountability across the cross-functional team. When operational challenges emerge, team leads record anomalies in the issue log while updating the enterprise risk register. Faced with unanticipated obstacles, project managers follow a structured escalation path rather than improvising unapproved solutions. By submitting a formal change request, teams ensure that budget modifications receive proper sign-off authority before implementation begins.",
        "vocabularyUsed": ["executive summary", "initiative roadmap", "terms of reference", "cross-functional team", "issue log", "risk register", "escalation path", "change request", "sign-off authority"]
    },
    {
        "title": "People Operations and Organizational Excellence",
        "titleArabic": "العمليات التشغيلية للموارد البشرية والتميز المؤسسي",
        "text": "Modern enterprises rely on structured human capital processes to sustain high performance. Conducting a rigorous needs assessment allows talent managers to tailor the onboarding process to departmental demands. During the annual appraisal cycle, employees receive comprehensive 360-degree feedback that informs their professional development plan. Supported by a regular coaching session and an authentic mentoring relationship, high-potential employees pursue ambitious stretch goals with confidence. Furthermore, strategic workforce planning and deliberate succession planning ensure that the talent pipeline remains resilient against unexpected executive departures.",
        "vocabularyUsed": ["needs assessment", "onboarding process", "appraisal cycle", "360-degree feedback", "professional development plan", "coaching session", "mentoring relationship", "stretch goal", "workforce planning", "succession planning", "talent pipeline"]
    },
    {
        "title": "Organizational Development and Continuous Improvement",
        "titleArabic": "التطوير التنظيمي والتحسين المستمر للأعمال",
        "text": "Sustaining long-term competitive advantage requires rigorous organizational development and vigilant operational oversight. Undertaking a detailed benchmarking exercise helps enterprises identify capability deficits through targeted gap analysis. Having evaluated internal processes, leadership formulates an actionable corrective action report reinforced by robust preventive measures. Tracking every key performance indicator through a balanced scorecard enables executives to evaluate strategic execution accurately. Moreover, when undergoing major transitions, embedding change management protocols guarantees seamless knowledge transfer and safeguards the corporate business continuity plan.",
        "vocabularyUsed": ["organizational development", "benchmarking exercise", "gap analysis", "corrective action report", "preventive measure", "key performance indicator", "balanced scorecard", "change management", "knowledge transfer", "business continuity plan"]
    }
]

# ==============================================================================
# DAY 74: Technology and Society (The impact of technology)
# Grammar: Passive with Modals (must be, can be, should be)
# ==============================================================================

vocab_74 = [
    # AI & Core Technologies
    {"headword": "algorithmic bias", "pronunciation": "/ˌælɡəˈrɪðmɪk ˈbaɪəs/", "partOfSpeech": "noun", "definition": "Systematic and unfair prejudice in computer automated decisions caused by flawed training data or assumptions.", "example": "Facial recognition models frequently exhibit algorithmic bias against minority demographic groups.", "translation": "التحيز الخوارزمي في مخرجات الذكاء الاصطناعي", "collocations": ["mitigate algorithmic bias", "detect algorithmic bias"], "synonyms": ["machine bias"], "antonyms": ["algorithmic fairness"], "tags": ["tech", "ai", "ethics"]},
    {"headword": "data sovereignty", "pronunciation": "/ˈdeɪtə ˈsɒvrənti/", "partOfSpeech": "noun", "definition": "The legal concept that digital data is subject to the laws and governance of the nation where it is collected.", "example": "National data sovereignty legislation requires cloud providers to store citizen data within domestic borders.", "translation": "السيادة على البيانات / خضوع البيانات لقوانين بلد جمعها", "collocations": ["enforce data sovereignty", "respect data sovereignty"], "synonyms": ["digital sovereignty"], "antonyms": [], "tags": ["law", "tech", "governance"]},
    {"headword": "digital divide", "pronunciation": "/ˈdɪdʒɪtl dɪˈvaɪd/", "partOfSpeech": "noun", "definition": "The socioeconomic gap between demographic groups having access to modern information tech and those without.", "example": "Subsidizing rural broadband infrastructure is essential to bridge the persistent digital divide.", "translation": "الفجوة الرقمية بين من يملكون الوصول للتقنية والمحرومين منها", "collocations": ["bridge the digital divide", "narrow the digital divide"], "synonyms": ["digital disparity"], "antonyms": ["digital inclusion"], "tags": ["society", "tech"]},
    {"headword": "surveillance capitalism", "pronunciation": "/sɜːˈveɪləns ˈkæpɪtəlɪzəm/", "partOfSpeech": "noun", "definition": "An economic system centered on commodifying personal human experience through behavioral data capture.", "example": "Critics argue that surveillance capitalism exploits personal user interactions for predictive advertising revenue.", "translation": "رأسمالية المراقبة / تسليع البيانات السلوكية للأفراد", "collocations": ["critique of surveillance capitalism", "rise of surveillance capitalism"], "synonyms": ["data capitalism"], "antonyms": [], "tags": ["economics", "tech", "society"]},
    {"headword": "platform economy", "pronunciation": "/ˈplætfɔːm ɪˈkɒnəmi/", "partOfSpeech": "noun", "definition": "Economic and social activity facilitated by digital platforms that match service providers with consumers.", "example": "The platform economy has disrupted traditional hospitality and urban transport industries globally.", "translation": "اقتصاد المنصات الرقمية الوسيطة", "collocations": ["growth of the platform economy", "regulate the platform economy"], "synonyms": ["digital platform ecosystem"], "antonyms": ["traditional brick-and-mortar economy"], "tags": ["economics", "tech"]},
    {"headword": "gig economy worker", "pronunciation": "/ɡɪɡ ɪˈkɒnəmi ˈwɜːkə/", "partOfSpeech": "noun", "definition": "An independent freelance contractor engaged in on-demand service jobs via digital matching apps.", "example": "Labor tribunals debate whether a gig economy worker should qualify for standard employee benefits.", "translation": "عامل في اقتصاد الأعمال الحرة المؤقتة عبر التطبيقات", "collocations": ["rights of gig economy workers", "protect gig economy workers"], "synonyms": ["on-demand worker", "freelance contractor"], "antonyms": ["salaried employee"], "tags": ["work", "tech", "society"]},
    {"headword": "artificial general intelligence", "pronunciation": "/ˌɑːtɪˈfɪʃl ˈdʒenrəl ɪnˈtelɪdʒəns/", "partOfSpeech": "noun", "definition": "Hypothetical software possessing the broad cognitive capacity to match or exceed human intellect across any domain.", "example": "Scientists debate whether artificial general intelligence will emerge within the next two decades.", "translation": "الذكاء الاصطناعي العام ذو القدرات الإدراكية البشرية الشاملة", "collocations": ["pursue artificial general intelligence", "safety of artificial general intelligence"], "synonyms": ["AGI", "strong AI"], "antonyms": ["narrow AI"], "tags": ["ai", "tech"]},
    {"headword": "machine learning model", "pronunciation": "/məˈʃiːn ˈlɜːnɪŋ ˈmɒdl/", "partOfSpeech": "noun", "definition": "A mathematical algorithm trained on datasets to perform specific prediction or classification tasks.", "example": "Engineers trained the machine learning model on millions of medical scans to detect tumors early.", "translation": "نموذج تعلم الآلة الرياضي المدرب", "collocations": ["train a machine learning model", "deploy a machine learning model"], "synonyms": ["ML model", "predictive model"], "antonyms": [], "tags": ["ai", "tech"]},
    {"headword": "neural network", "pronunciation": "/ˈnjʊərəl ˈnetwɜːk/", "partOfSpeech": "noun", "definition": "A computational architecture inspired by the human brain, composed of interconnected processing nodes.", "example": "A deep neural network can recognize speech patterns with human-level accuracy.", "translation": "الشبكة العصبية الاصطناعية الحاسوبية", "collocations": ["train a neural network", "artificial neural network"], "synonyms": ["ANN", "deep network"], "antonyms": [], "tags": ["ai", "tech"]},
    {"headword": "deep learning", "pronunciation": "/diːp ˈlɜːnɪŋ/", "partOfSpeech": "noun", "definition": "A subfield of machine learning based on multilayer neural networks with representation learning.", "example": "Breakthroughs in deep learning have accelerated autonomous driving and voice transcription.", "translation": "التعلم العميق متعدد الطبقات العصبية", "collocations": ["advances in deep learning", "deep learning algorithms"], "synonyms": ["hierarchical learning"], "antonyms": [], "tags": ["ai", "tech"]},
    {"headword": "natural language processing", "pronunciation": "/ˈnætʃrəl ˈlæŋɡwɪdʒ ˈprəʊsesɪŋ/", "partOfSpeech": "noun", "definition": "A branch of AI enabling machines to understand, interpret, and generate human spoken and written languages.", "example": "Modern chatbots rely on advanced natural language processing to hold fluent customer service dialogues.", "translation": "معالجة اللغات الطبيعية حاسوبياً", "collocations": ["applications of natural language processing", "NLP techniques"], "synonyms": ["NLP"], "antonyms": [], "tags": ["ai", "linguistics"]},
    {"headword": "computer vision", "pronunciation": "/kəmˈpjuːtə ˈvɪʒn/", "partOfSpeech": "noun", "definition": "An interdisciplinary field that deals with how computers gain high-level understanding from digital images or videos.", "example": "Automated warehouse robots use computer vision to sort packages and navigate factory aisles safely.", "translation": "الرؤية الحاسوبية ومعالجة الصور رقمياً", "collocations": ["advances in computer vision", "computer vision system"], "synonyms": ["machine vision"], "antonyms": [], "tags": ["ai", "tech"]},
    {"headword": "autonomous vehicle", "pronunciation": "/ɔːˈtɒnəməs ˈviːəkl/", "partOfSpeech": "noun", "definition": "A self-driving automobile capable of sensing its environment and navigating without human intervention.", "example": "Regulators are creating safety standards before an autonomous vehicle can operate without a backup driver.", "translation": "مركبة ذاتية القيادة دون تدخل بشري", "collocations": ["deploy autonomous vehicles", "autonomous vehicle fleet"], "synonyms": ["self-driving car", "driverless car"], "antonyms": ["human-driven vehicle"], "tags": ["automotive", "tech"]},
    {"headword": "drone delivery", "pronunciation": "/drəʊn dɪˈlɪvəri/", "partOfSpeech": "noun", "definition": "The transportation of packages or medical supplies to designated locations via unmanned aerial vehicles.", "example": "Rural hospitals are testing drone delivery to transport urgent blood units across mountainous terrain.", "translation": "التوصيل عبر الطائرات المسيرة بدون طيار", "collocations": ["commercial drone delivery", "drone delivery network"], "synonyms": ["UAV delivery"], "antonyms": ["ground delivery"], "tags": ["logistics", "tech"]},
    {"headword": "smart city", "pronunciation": "/smɑːt ˈsɪti/", "partOfSpeech": "noun", "definition": "An urban area that uses IoT sensors and data technology to manage assets, resources, and public services efficiently.", "example": "Singapore is widely recognized as a pioneering smart city with automated traffic management.", "translation": "مدينة ذكية مدعومة بتقنيات إنترنت الأشياء والبيانات", "collocations": ["develop a smart city", "smart city infrastructure"], "synonyms": ["connected city"], "antonyms": [], "tags": ["urban", "tech"]},
    {"headword": "internet of things", "pronunciation": "/ˈɪntənet əv θɪŋz/", "partOfSpeech": "noun", "definition": "The global network of physical devices embedded with sensors and software that connect and exchange data.", "example": "The proliferation of the internet of things allows smart home thermostats to optimize household energy use.", "translation": "إنترنت الأشياء وربط الأجهزة المتصلة", "collocations": ["internet of things devices", "IoT sensors"], "synonyms": ["IoT"], "antonyms": [], "tags": ["hardware", "tech"]},
    {"headword": "edge computing", "pronunciation": "/edʒ kəmˈpjuːtɪŋ/", "partOfSpeech": "noun", "definition": "A distributed computing paradigm that brings computation and data storage closer to sources of data.", "example": "Edge computing reduces latency by processing video analytics locally on street cameras rather than distant cloud servers.", "translation": "حوسبة الحافة ومعالجة البيانات محلياً عند المصدر", "collocations": ["deploy edge computing", "edge computing architecture"], "synonyms": ["distributed computing"], "antonyms": ["centralized cloud computing"], "tags": ["infrastructure", "tech"]},
    {"headword": "quantum computing", "pronunciation": "/ˈkwɒntəm kəmˈpjuːtɪŋ/", "partOfSpeech": "noun", "definition": "Computation leveraging quantum mechanics principles such as superposition to solve intractable calculations exponentially faster.", "example": "Researchers predict quantum computing will revolutionize pharmaceutical molecular discovery and cryptography.", "translation": "الحوسبة الكمية المعقدة وفائقة السرعة", "collocations": ["breakthrough in quantum computing", "quantum computing hardware"], "synonyms": [], "antonyms": ["classical computing"], "tags": ["physics", "tech"]},
    {"headword": "blockchain ledger", "pronunciation": "/ˈblɒktʃeɪn ˈledʒə/", "partOfSpeech": "noun", "definition": "A decentralized, distributed, and immutable digital database recording transactions across a peer-to-peer network.", "example": "Recording land titles on a blockchain ledger prevents fraudulent deed alterations.", "translation": "سجل البلوكتشين الرقمي المشفر والموزع", "collocations": ["immutable blockchain ledger", "verify on the blockchain ledger"], "synonyms": ["distributed ledger"], "antonyms": ["centralized database"], "tags": ["crypto", "tech"]},
    {"headword": "decentralized finance", "pronunciation": "/diːˈsentrəlaɪzd ˈfaɪnæns/", "partOfSpeech": "noun", "definition": "A blockchain-based financial technology eliminating central financial intermediaries through smart contracts.", "example": "Decentralized finance enables peer-to-peer lending without requiring a traditional banking institution.", "translation": "التمويل اللامركزي المستقل عن البنوك التقليدية", "collocations": ["protocols in decentralized finance", "DeFi platforms"], "synonyms": ["DeFi"], "antonyms": ["centralized finance", "CeFi"], "tags": ["finance", "crypto"]},
    {"headword": "non-fungible token", "pronunciation": "/nɒn ˈfʌndʒəbl ˈtəʊkən/", "partOfSpeech": "noun", "definition": "A unique cryptographic digital identifier recorded on a blockchain proving ownership of a specific asset.", "example": "The digital artist authenticated her original illustration by minting it as a non-fungible token.", "translation": "رمز غير قابل للاستبدال يثبت الملكية الرقمية للأصل", "collocations": ["mint a non-fungible token", "NFT marketplace"], "synonyms": ["NFT"], "antonyms": ["fungible token"], "tags": ["crypto", "art"]},
    {"headword": "augmented reality", "pronunciation": "/ɔːɡˈmentɪd riˈæləti/", "partOfSpeech": "noun", "definition": "An interactive experience where computer-generated perceptual information is overlaid onto the real-world environment.", "example": "Surgeons use augmented reality headsets to project three-dimensional patient anatomy during surgery.", "translation": "الواقع المعزز بدمج العناصر الرقمية مع الواقع", "collocations": ["augmented reality glasses", "AR applications"], "synonyms": ["AR"], "antonyms": ["virtual reality"], "tags": ["tech", "graphics"]},
    {"headword": "virtual reality", "pronunciation": "/ˈvɜːtʃuəl riˈæləti/", "partOfSpeech": "noun", "definition": "A simulated three-dimensional computer environment that immerses the user in an interactive artificial sensory world.", "example": "Pilot trainees practice emergency landings in high-fidelity virtual reality flight simulators.", "translation": "الواقع الافتراضي الانغماسي الكامل", "collocations": ["virtual reality headset", "immerse in virtual reality"], "synonyms": ["VR"], "antonyms": ["augmented reality"], "tags": ["tech", "graphics"]},
    {"headword": "mixed reality", "pronunciation": "/mɪkst riˈæləti/", "partOfSpeech": "noun", "definition": "A blending of real and virtual worlds where physical and digital objects co-exist and interact in real time.", "example": "Industrial designers use mixed reality to manipulate holographic prototypes anchored to physical workshop tables.", "translation": "الواقع المختلط الجامع بين الحقيقي والافتراضي", "collocations": ["mixed reality platform", "MR headset"], "synonyms": ["MR", "extended reality"], "antonyms": [], "tags": ["tech", "graphics"]},
    {"headword": "digital twin", "pronunciation": "/ˈdɪdʒɪtl twɪn/", "partOfSpeech": "noun", "definition": "A virtual dynamic software representation of a physical object, process, or system updated in real time.", "example": "Engineers built a digital twin of the wind turbine to simulate stress tolerances and predict component failure.", "translation": "التوأم الرقمي / المحاكاة الافتراضية المطابقة لكيان فيزيائي", "collocations": ["create a digital twin", "digital twin simulation"], "synonyms": ["virtual replica"], "antonyms": ["physical entity"], "tags": ["engineering", "tech"]},

    # Cybersecurity, Big Data & Regulation
    {"headword": "predictive analytics", "pronunciation": "/prɪˈdɪktɪv ˌænəˈlɪtɪks/", "partOfSpeech": "noun", "definition": "Statistical and machine learning techniques analyzing current and historical facts to make predictions.", "example": "Hospitals apply predictive analytics to forecast patient admission spikes during winter seasons.", "translation": "التحليلات التنبؤية القائمة على البيانات والنماذج الإحصائية", "collocations": ["utilize predictive analytics", "predictive analytics software"], "synonyms": ["predictive modeling"], "antonyms": ["descriptive analytics"], "tags": ["analytics", "data"]},
    {"headword": "big data analytics", "pronunciation": "/bɪɡ ˈdeɪtə ˌænəˈlɪtɪks/", "partOfSpeech": "noun", "definition": "The complex process of examining massive and diverse datasets to uncover hidden patterns and correlations.", "example": "Retailers leverage big data analytics to customize shopping recommendations in real time.", "translation": "تحليلات البيانات الضخمة المعقدة", "collocations": ["power of big data analytics", "conduct big data analytics"], "synonyms": ["data mining"], "antonyms": [], "tags": ["data", "analytics"]},
    {"headword": "cloud migration", "pronunciation": "/klaʊd maɪˈɡreɪʃn/", "partOfSpeech": "noun", "definition": "The organizational process of moving digital assets, databases, and IT processes into cloud computing environments.", "example": "Completing the cloud migration enabled the bank to reduce local server maintenance costs by forty percent.", "translation": "الانتقال والترحيل إلى السحابة الإلكترونية", "collocations": ["seamless cloud migration", "accelerate cloud migration"], "synonyms": ["cloud transition"], "antonyms": ["on-premises hosting"], "tags": ["it", "cloud"]},
    {"headword": "zero-day vulnerability", "pronunciation": "/ˈzɪərəʊ deɪ ˌvʌlnərəˈbɪləti/", "partOfSpeech": "noun", "definition": "A software security flaw unknown to the developer, leaving systems exposed to exploits before a patch exists.", "example": "Cybersecurity analysts discovered a zero-day vulnerability in the web browser's encryption module.", "translation": "ثغرة اليوم صفر الأمنية غير المكتشفة من المطورين", "collocations": ["exploit a zero-day vulnerability", "patch a zero-day vulnerability"], "synonyms": ["zero-day exploit"], "antonyms": ["patched vulnerability"], "tags": ["security", "tech"]},
    {"headword": "ransomware attack", "pronunciation": "/ˈrænsəmweər əˈtæk/", "partOfSpeech": "noun", "definition": "A malicious cyber assault that encrypts an organization's files until a ransom is paid.", "example": "The city government refused to pay criminals following a disruptive ransomware attack on public utility servers.", "translation": "هجوم برامج الفدية الخبيثة لتشفير البيانات", "collocations": ["suffer a ransomware attack", "prevent a ransomware attack"], "synonyms": ["ransomware extortion"], "antonyms": [], "tags": ["security", "crime"]},
    {"headword": "phishing attempt", "pronunciation": "/ˈfɪʃɪŋ əˈtempt/", "partOfSpeech": "noun", "definition": "A deceptive fraudulent communication designed to manipulate individuals into disclosing sensitive credentials.", "example": "Employees were trained to spot a sophisticated phishing attempt disguised as an executive email.", "translation": "محاولة تصيد احتيالي لسرقة كلمات المرور والبيانات", "collocations": ["detect a phishing attempt", "fall victim to a phishing attempt"], "synonyms": ["email phishing scam"], "antonyms": [], "tags": ["security", "fraud"]},
    {"headword": "multi-step verification", "pronunciation": "/ˈmʌlti step ˌverɪfɪˈkeɪʃn/", "partOfSpeech": "noun", "definition": "A security process where a user provides two or more distinct authentication factors to prove their identity.", "example": "Enabling multi-step verification prevents unauthorized logins even if passwords are leaked.", "translation": "التحقق متعدد الخطوات لحماية الحسابات", "collocations": ["enable multi-step verification", "require multi-step verification"], "synonyms": ["two-factor authentication", "MFA"], "antonyms": ["single-factor authentication"], "tags": ["security", "tech"]},
    {"headword": "end-to-end encryption", "pronunciation": "/ˌend tuː ˈend ɪnˈkrɪpʃn/", "partOfSpeech": "noun", "definition": "A communication security system where only the communicating users can decrypt and read the transmitted messages.", "example": "Messaging applications featuring end-to-end encryption ensure telecom carriers cannot eavesdrop on private chats.", "translation": "التشفير التام من طرف إلى طرف", "collocations": ["implement end-to-end encryption", "feature end-to-end encryption"], "synonyms": ["E2EE"], "antonyms": ["unencrypted communication"], "tags": ["privacy", "security"]},
    {"headword": "open-source software", "pronunciation": "/ˌəʊpən ˈsɔːs ˈsɒftweə/", "partOfSpeech": "noun", "definition": "Computer software released under a license granting users rights to inspect, modify, and distribute its source code.", "example": "The Linux operating system is the most famous example of community-developed open-source software.", "translation": "برمجيات مفتوحة المصدر متاحة للجميع", "collocations": ["contribute to open-source software", "rely on open-source software"], "synonyms": ["FOSS"], "antonyms": ["proprietary software"], "tags": ["programming", "tech"]},
    {"headword": "proprietary system", "pronunciation": "/prəˈpraɪətri ˈsɪstəm/", "partOfSpeech": "noun", "definition": "Software or hardware owned exclusively by a single enterprise with closed, restricted code and architecture.", "example": "Vendors lock clients into their proprietary system by using non-standard file formats.", "translation": "نظام احتكاري مغلق المصدر وخاص بالشركة", "collocations": ["lock-in to a proprietary system", "replace a proprietary system"], "synonyms": ["closed system"], "antonyms": ["open-source system", "open standard"], "tags": ["business", "tech"]},
    {"headword": "tech monopoly", "pronunciation": "/tek məˈnɒpəli/", "partOfSpeech": "noun", "definition": "A single giant technology corporation that dominates an entire digital market without meaningful competition.", "example": "Antitrust regulators are investigating whether the search giant constitutes an illegal tech monopoly.", "translation": "احتكار تقني واستحواذ مطلق على السوق الرقمي", "collocations": ["break up a tech monopoly", "curb tech monopolies"], "synonyms": ["digital monopoly"], "antonyms": ["competitive tech market"], "tags": ["business", "law"]},
    {"headword": "antitrust regulation", "pronunciation": "/ˌæntiˈtrʌst ˌreɡjuˈleɪʃn/", "partOfSpeech": "noun", "definition": "Legislation and state oversight preventing predatory corporate practices and maintaining commercial market competition.", "example": "New antitrust regulation aims to prevent platform giants from prioritizing their own products unfairly.", "translation": "تشريعات مكافحة الاحتكار وحماية المنافسة السوقية", "collocations": ["enact antitrust regulation", "subject to antitrust regulation"], "synonyms": ["competition law"], "antonyms": ["monopolistic deregulation"], "tags": ["law", "business"]},
    {"headword": "digital regulation", "pronunciation": "/ˈdɪdʒɪtl ˌreɡjuˈleɪʃn/", "partOfSpeech": "noun", "definition": "Government policies and statutory frameworks governing digital platforms, data privacy, and online conduct.", "example": "European digital regulation sets strict accountability standards for how online intermediaries handle personal data.", "translation": "التنظيم والتشريع الرقمي للأنشطة والمنصات", "collocations": ["comply with digital regulation", "framework for digital regulation"], "synonyms": ["cyberlaw", "internet governance"], "antonyms": ["unregulated internet"], "tags": ["governance", "law"]},
    {"headword": "net neutrality", "pronunciation": "/net njuːˈtræləti/", "partOfSpeech": "noun", "definition": "The principle that internet service providers must treat all internet data equally without discrimination or throttling.", "example": "Upholding net neutrality guarantees that small startups receive the same transmission speeds as media conglomerates.", "translation": "حيادية الإنترنت / معاملة كافة البيانات على قدم المساواة", "collocations": ["advocate for net neutrality", "repeal net neutrality"], "synonyms": ["open internet principle"], "antonyms": ["traffic throttling"], "tags": ["policy", "tech"]},
    {"headword": "content moderation", "pronunciation": "/ˈkɒntent ˌmɒdəˈreɪʃn/", "partOfSpeech": "noun", "definition": "The systematic screening and monitoring of user-generated content to enforce community standards and legal rules.", "example": "Social media platforms combine human reviewers and automated filters to perform content moderation.", "translation": "الإشراف على المحتوى الرقمي وفلترته وفق القواعد", "collocations": ["automated content moderation", "policies of content moderation"], "synonyms": ["content filtering"], "antonyms": ["unfiltered publishing"], "tags": ["media", "ethics"]},
    {"headword": "algorithmic transparency", "pronunciation": "/ˌælɡəˈrɪðmɪk trænsˈpærənsi/", "partOfSpeech": "noun", "definition": "The principle that the logic and scoring mechanisms inside algorithms should be open to public inspection.", "example": "Civil rights advocates argue that credit rating software must offer full algorithmic transparency.", "translation": "الشفافية الخوارزمية وتوضيح آليات اتخاذ القرار الآلي", "collocations": ["demand algorithmic transparency", "ensure algorithmic transparency"], "synonyms": ["algorithmic accountability"], "antonyms": ["black-box algorithms"], "tags": ["ethics", "ai"]},
    {"headword": "explainable AI", "pronunciation": "/ɪkˈspleɪnəbl eɪ ˈaɪ/", "partOfSpeech": "noun", "definition": "Artificial intelligence designed such that its actions, decisions, and reasoning can be understood by humans.", "example": "In medical diagnosis, explainable AI is essential so oncologists understand why a specific therapy was recommended.", "translation": "الذكاء الاصطناعي القابل للتفسير والشرح البشري", "collocations": ["develop explainable AI", "principles of explainable AI"], "synonyms": ["XAI", "interpretable machine learning"], "antonyms": ["black-box AI"], "tags": ["ai", "ethics"]},
    {"headword": "responsible AI", "pronunciation": "/rɪˈspɒnsəbl eɪ ˈaɪ/", "partOfSpeech": "noun", "definition": "A governance framework establishing ethical, transparent, and fair practices for designing and deploying AI systems.", "example": "Leading tech research labs instituted responsible AI charters to prevent weaponization of automated tools.", "translation": "الذكاء الاصطناعي المسؤول والملتزم بالمعايير الأخلاقية", "collocations": ["commit to responsible AI", "responsible AI framework"], "synonyms": ["ethical AI"], "antonyms": ["unrestricted AI"], "tags": ["ai", "ethics"]},
    {"headword": "tech ethics", "pronunciation": "/tek ˈeθɪks/", "partOfSpeech": "noun", "definition": "The branch of ethics addressing moral dilemmas arising from the creation, deployment, and impact of digital technologies.", "example": "Courses in tech ethics prepare computer science students to anticipate societal repercussions of autonomous code.", "translation": "أخلاقيات التقنية والمسؤولية القيمية في تطويرها", "collocations": ["field of tech ethics", "debate tech ethics"], "synonyms": ["digital ethics"], "antonyms": [], "tags": ["ethics", "philosophy"]},
    {"headword": "digital wellbeing", "pronunciation": "/ˈdɪdʒɪtl ˌwelˈbiːɪŋ/", "partOfSpeech": "noun", "definition": "The state of maintaining a healthy, balanced, and intentional relationship with technology and connected devices.", "example": "Smartphone operating systems now incorporate digital wellbeing dashboards to curb compulsive app usage.", "translation": "الرفاه الرقمي والتوازن الصحي في استخدام الشاشات", "collocations": ["promote digital wellbeing", "tools for digital wellbeing"], "synonyms": ["tech-life balance"], "antonyms": ["digital addiction"], "tags": ["health", "lifestyle"]},
    {"headword": "screen time", "pronunciation": "/skriːn taɪm/", "partOfSpeech": "noun", "definition": "The total amount of time spent looking at and using electronic screens on smartphones, tablets, computers, or TVs.", "example": "Pediatricians recommend capping daily recreational screen time for young children to under one hour.", "translation": "وقت استخدام الشاشات الإلكترونية", "collocations": ["limit screen time", "reduce screen time"], "synonyms": ["device time"], "antonyms": ["offline time"], "tags": ["lifestyle", "health"]},
    {"headword": "attention economy", "pronunciation": "/əˈtenʃn ɪˈkɒnəmi/", "partOfSpeech": "noun", "definition": "An economic perspective that treats human attention as a scarce commodity monetized by digital platforms.", "example": "Social media feeds are engineered by behavioral psychologists to harvest attention in the attention economy.", "translation": "اقتصاد الانتباه وتسييل اهتمام المستخدمين رقمياً", "collocations": ["dynamics of the attention economy", "thrive in the attention economy"], "synonyms": ["attention marketplace"], "antonyms": [], "tags": ["media", "psychology"]},
    {"headword": "filter bubble", "pronunciation": "/ˈfɪltə bʌbl/", "partOfSpeech": "noun", "definition": "A state of intellectual isolation resulting from personalized algorithms showing only agreeing content.", "example": "Living inside a political filter bubble prevents users from seeing valid counter-arguments or diverse perspectives.", "translation": "فقاعة الترشيح الخوارزمية العازلة للرأي المخالف", "collocations": ["escape a filter bubble", "trapped in a filter bubble"], "synonyms": ["algorithmic cocoon"], "antonyms": ["diverse information environment"], "tags": ["media", "society"]},
    {"headword": "echo chamber", "pronunciation": "/ˈekəʊ ˌtʃeɪmbə/", "partOfSpeech": "noun", "definition": "An environment where beliefs are amplified and reinforced by communication within a closed system of like-minded individuals.", "example": "Online forums frequently degenerate into an ideological echo chamber hostile to differing perspectives.", "translation": "غرفة الصدى المعرفي حيث تتكرر نفس القناعات دون نقد", "collocations": ["fall into an echo chamber", "break out of an echo chamber"], "synonyms": ["ideological silo"], "antonyms": ["open forum"], "tags": ["society", "communication"]},
    {"headword": "data exhaust", "pronunciation": "/ˈdeɪtə ɪɡˈzɔːst/", "partOfSpeech": "noun", "definition": "The trail of secondary digital metadata generated by users as a byproduct of their online actions and device use.", "example": "Companies aggregate location logs, search cookies, and app timestamps as valuable data exhaust.", "translation": "عوادم البيانات / الآثار الرقمية الثانوية المتروكة خلف المستخدم", "collocations": ["collect data exhaust", "harvest data exhaust"], "synonyms": ["digital footprint", "data trail"], "antonyms": [], "tags": ["privacy", "data"]}
]

grammar_74 = [
    {
        "title": "Passive with Modals (must be, can be, should be)",
        "explanation": "Passive modal structures combine modal auxiliary verbs (must, can, should, could, may, might, ought to) with the passive voice. They are essential in academic, journalistic, policy, and technical discourse to describe necessity, possibility, obligation, and recommendations without emphasizing the agent.\n\n1. Present / Future Modals in Passive:\n   Modal + be + Past Participle (V3)\n   - 'Algorithmic bias must be eliminated through rigorous testing.' (Necessity / Obligation)\n   - 'Data sovereignty can be protected with national legislation.' (Possibility / Capability)\n   - 'Digital divide issues should be addressed by governments.' (Recommendation / Moral Duty)\n\n2. Past Modals in Passive:\n   Modal + have been + Past Participle (V3)\n   - 'The zero-day vulnerability should have been patched earlier.' (Unfulfilled past recommendation)\n   - 'The ransomware attack could have been prevented with multi-step verification.' (Past capability / hypothetical)\n   - 'The company's digital twin must have been updated overnight.' (Logical deduction about the past)\n\n3. Register Note: Passive with modals allows objective, authoritative policy writing by focusing attention on the action or affected technology rather than personal opinions.",
        "structures": [
            {"pattern": "Subject + modal + be + past participle: 'Zero-day vulnerabilities must be patched immediately.'"},
            {"pattern": "Subject + modal + have been + past participle: 'The ransomware attack could have been mitigated by multi-step verification.'"},
            {"pattern": "Subject + negative modal + be + past participle: 'Surveillance capitalism cannot be sustained without user consent.'"}
        ],
        "examples": [
            {
                "sentence": "Algorithmic bias must be mitigated before any machine learning model is deployed commercially.",
                "arabic": "يجب الحد من التحيز الخوارزمي قبل نشر أي نموذج لتعلم الآلة تجارياً.",
                "usesVocabulary": ["algorithmic bias", "machine learning model"]
            },
            {
                "sentence": "Data sovereignty can be reinforced when cloud migration complies with international digital regulation.",
                "arabic": "يمكن تعزيز السيادة على البيانات عندما يتوافق الانتقال السحابي مع التنظيم الرقمي الدولي.",
                "usesVocabulary": ["data sovereignty", "cloud migration", "digital regulation"]
            },
            {
                "sentence": "The destructive ransomware attack should have been anticipated by IT security analysts.",
                "arabic": "كان ينبغي على محللي أمن تقنية المعلومات توقع هجوم برامج الفدية المدمر.",
                "usesVocabulary": ["ransomware attack"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "The filter bubble must addressed by tech companies.",
                "right": "The filter bubble must be addressed by tech companies.",
                "explanation": "A passive modal structure requires the auxiliary verb 'be' before the past participle: 'must be addressed', not 'must addressed'."
            },
            {
                "wrong": "Multi-step verification should has been enforced earlier.",
                "right": "Multi-step verification should have been enforced earlier.",
                "explanation": "After any modal verb, the base form 'have' must always be used in perfect passives: 'should have been', never 'should has been'."
            }
        ]
    }
]

convs_74 = [
    {
        "title": "Parliamentary Hearing: Big Tech Regulation and Ethics",
        "titleArabic": "جلسة استماع برلمانية: تنظيم شركات التقنية الكبرى والأخلاقيات",
        "setting": "A parliamentary committee questions a tech policy director about market power and AI oversight.",
        "lines": [
            {"speaker": "Committee Chair", "text": "Can a tech monopoly be trusted to regulate itself, or must strict antitrust regulation be imposed?"},
            {"speaker": "Policy Director", "text": "Self-regulation is clearly insufficient. Concrete digital regulation must be enacted to dismantle algorithmic bias and protect consumers."},
            {"speaker": "Committee Chair", "text": "How can explainable AI and algorithmic transparency be enforced across proprietary systems?"},
            {"speaker": "Policy Director", "text": "Independent auditing standards should be mandated, requiring companies to disclose training architectures without exposing intellectual property."},
            {"speaker": "Committee Chair", "text": "Many citizens feel trapped within an echo chamber or filter bubble orchestrated by the attention economy."},
            {"speaker": "Policy Director", "text": "Indeed. Content moderation policies should be reformed, and data exhaust generated by teenagers must never be commodified."},
            {"speaker": "Committee Chair", "text": "What about artificial general intelligence? Should development be paused until safety guardrails exist?"},
            {"speaker": "Policy Director", "text": "Responsible AI principles can be codified into law, ensuring foundational models benefit humanity equitably."}
        ],
        "vocabularyUsed": ["tech monopoly", "antitrust regulation", "digital regulation", "algorithmic bias", "explainable AI", "algorithmic transparency", "echo chamber", "filter bubble", "attention economy", "content moderation", "data exhaust", "artificial general intelligence", "responsible AI"]
    },
    {
        "title": "Cybersecurity Briefing: Critical Infrastructure Defense",
        "titleArabic": "إحاطة الأمن السيبراني: الدفاع عن البنية التحتية الحيوية",
        "setting": "The Chief Information Security Officer briefs the municipal government on emergency protocols.",
        "lines": [
            {"speaker": "CISO", "text": "A severe zero-day vulnerability was exploited last night, launching a coordinated ransomware attack against our municipal grid."},
            {"speaker": "Mayor", "text": "Could vital city records have been protected with multi-step verification and end-to-end encryption?"},
            {"speaker": "CISO", "text": "Yes, but legacy protocols allowed phishing attempts to bypass older firewall filters."},
            {"speaker": "Mayor", "text": "Should our ongoing cloud migration be accelerated, or should we rely on edge computing nodes?"},
            {"speaker": "CISO", "text": "Both strategies must be integrated. Edge computing will handle real-time traffic for autonomous vehicle fleets in our smart city."},
            {"speaker": "Mayor", "text": "And what of the internet of things sensors monitoring our water treatment plants?"},
            {"speaker": "CISO", "text": "They must be isolated on an encrypted network to safeguard national data sovereignty."},
            {"speaker": "Mayor", "text": "Ensure that our digital twin simulations are updated hourly so potential failures can be remediated instantly."}
        ],
        "vocabularyUsed": ["zero-day vulnerability", "ransomware attack", "multi-step verification", "end-to-end encryption", "cloud migration", "edge computing", "autonomous vehicle", "smart city", "internet of things", "data sovereignty", "digital twin"]
    },
    {
        "title": "Future Tech Summit: Emerging Realities and Decentralization",
        "titleArabic": "قمة تقنيات المستقبل: الحقائق الناشئة واللامركزية",
        "setting": "Two tech futurists discuss decentralized technologies and digital wellbeing at an international conference.",
        "lines": [
            {"speaker": "Futurist A", "text": "Do you believe decentralized finance can transform banking through the immutable blockchain ledger?"},
            {"speaker": "Futurist B", "text": "Certainly. Financial intermediaries can be replaced by smart contracts, though volatility must be managed responsibly."},
            {"speaker": "Futurist A", "text": "Beyond finance, non-fungible tokens are altering copyright, while augmented reality and virtual reality merge into mixed reality."},
            {"speaker": "Futurist B", "text": "As users immerse themselves in simulated worlds, screen time metrics should be monitored to safeguard digital wellbeing."},
            {"speaker": "Futurist A", "text": "Surveillance capitalism threatens to exploit immersive sensory data unless open-source software alternatives are promoted."},
            {"speaker": "Futurist B", "text": "Meanwhile, the digital divide leaves gig economy workers and rural families without adequate broadband access."},
            {"speaker": "Futurist A", "text": "Net neutrality must be defended vigorously so emerging decentralized services can compete on an equal footing."},
            {"speaker": "Futurist B", "text": "Indeed. Universal access can only be achieved when tech ethics and public investment converge."}
        ],
        "vocabularyUsed": ["decentralized finance", "blockchain ledger", "non-fungible token", "augmented reality", "virtual reality", "mixed reality", "screen time", "digital wellbeing", "surveillance capitalism", "open-source software", "digital divide", "gig economy worker", "net neutrality", "tech ethics"]
    }
]

paras_74 = [
    {
        "title": "Artificial Intelligence and the Imperative of Algorithmic Ethics",
        "titleArabic": "الذكاء الاصطناعي وضرورة الأخلاقيات الخوارزمية",
        "text": "The rapid ascent of deep learning and complex neural network architectures has transformed computing capability across industries. Today, natural language processing and computer vision enable machines to interpret text and visual media with unprecedented accuracy. However, without stringent oversight, algorithmic bias can be codified into critical judicial and banking systems. To safeguard public equity, explainable AI must be championed so automated decisions can be audited transparently. Furthermore, as researchers pursue artificial general intelligence, principles of responsible AI and tech ethics must be prioritized to ensure machine learning models remain beneficial and aligned with human values.",
        "vocabularyUsed": ["deep learning", "neural network", "natural language processing", "computer vision", "algorithmic bias", "explainable AI", "artificial general intelligence", "responsible AI", "tech ethics", "machine learning model"]
    },
    {
        "title": "Digital Infrastructure, Urban Connectivity, and Data Governance",
        "titleArabic": "البنية التحتية الرقمية، الترابط الحضري، وحوكمة البيانات",
        "text": "Building a resilient smart city demands cutting-edge infrastructure that blends edge computing with comprehensive cloud migration. By deploying countless internet of things sensors alongside autonomous vehicles and drone delivery systems, municipal governments optimize urban traffic flow. However, maintaining public trust requires that data sovereignty must be preserved against overseas jurisdictional reach. Furthermore, by harnessing big data analytics and predictive analytics through a virtual digital twin, city planners forecast infrastructure maintenance before failures happen. Meanwhile, bridging the digital divide ensures that every citizen benefits equally from advanced urban technological innovations.",
        "vocabularyUsed": ["smart city", "edge computing", "cloud migration", "internet of things", "autonomous vehicle", "drone delivery", "data sovereignty", "big data analytics", "predictive analytics", "digital twin", "digital divide"]
    },
    {
        "title": "Platform Governance, Cybersecurity, and Cognitive Wellbeing",
        "titleArabic": "حوكمة المنصات، الأمن السيبراني، والرفاه الإدراكي",
        "text": "Navigating the modern platform economy presents formidable technological and societal dilemmas. Defending against zero-day vulnerability exploits and dangerous ransomware attacks demands universal adoption of multi-step verification and end-to-end encryption. Simultaneously, the relentless pursuit of engagement in the attention economy exacerbates excessive screen time, leaving users trapped within an echo chamber. To protect digital wellbeing, robust digital regulation and net neutrality must be upheld against predatory tech monopolies. Finally, algorithmic transparency and transparent content moderation must be established to prevent user manipulation and protect societal cohesion.",
        "vocabularyUsed": ["platform economy", "zero-day vulnerability", "ransomware attack", "multi-step verification", "end-to-end encryption", "attention economy", "screen time", "echo chamber", "digital wellbeing", "digital regulation", "net neutrality", "tech monopoly", "algorithmic transparency", "content moderation"]
    }
]

if __name__ == "__main__":
    write_day(73, vocab_73, grammar_73, convs_73, paras_73)
    write_day(74, vocab_74, grammar_74, convs_74, paras_74)
    print("Day 73 and Day 74 generated successfully.")
