# -*- coding: utf-8 -*-
"""Generate Day 85 and Day 86 for Stage 9."""

import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from curriculum_engine import write_day

# ==============================================================================
# DAY 85: Technology in My Life (Personal technology integration)
# Grammar: Passive Voice + Technology Vocabulary Review
# ==============================================================================

vocab_85 = [
    # Smart Living, Devices & Automated Daily Workflows
    {"headword": "smart home device", "pronunciation": "/smɑːt həʊm dɪˈvaɪs/", "partOfSpeech": "noun", "definition": "An internet-connected electronic gadget that automates household appliances via voice or mobile apps.", "example": "Every smart home device in our apartment can be controlled through a unified voice command hub.", "translation": "جهاز المنزل الذكي المتصل بالإنترنت", "collocations": ["install a smart home device", "configure smart home devices"], "synonyms": ["connected home appliance"], "antonyms": ["analog appliance"], "tags": ["tech", "home"]},
    {"headword": "cloud backup service", "pronunciation": "/klaʊd ˈbækʌp ˈsɜːvɪs/", "partOfSpeech": "noun", "definition": "A remote online data storage utility that automatically preserves files and prevents catastrophic data loss.", "example": "Subscribing to a secure cloud backup service ensures your photographs and documents are safeguاردed.", "translation": "خدمة النسخ الاحتياطي السحابي لحفظ البيانات", "collocations": ["subscribe to a cloud backup service", "automated cloud backup service"], "synonyms": ["online backup solution"], "antonyms": ["local storage only"], "tags": ["cloud", "data"]},
    {"headword": "wearable fitness tracker", "pronunciation": "/ˈweərəbl ˈfɪtnəs ˈtrækə/", "partOfSpeech": "noun", "definition": "An electronic wristband or smartwatch that monitors physical activity, heart rate, and sleep metrics.", "example": "Her wearable fitness tracker buzzed gently to remind her that she had reached ten thousand steps.", "translation": "سوار تتبع اللياقة والنشاط البدني القابل للارتداء", "collocations": ["wear a fitness tracker", "sync the wearable fitness tracker"], "synonyms": ["activity monitor", "smart wristband"], "antonyms": [], "tags": ["fitness", "gadgets"]},
    {"headword": "virtual meeting tool", "pronunciation": "/ˈvɜːtʃuəl ˈmiːtɪŋ tuːl/", "partOfSpeech": "noun", "definition": "Video conferencing software that facilitates real-time remote communication between dispersed teams.", "example": "Adopting an intuitive virtual meeting tool allowed the multinational team to collaborate across twelve time zones.", "translation": "أداة وبرنامج الاجتماعات الافتراضية المرئية", "collocations": ["launch a virtual meeting tool", "rely on virtual meeting tools"], "synonyms": ["video conferencing platform"], "antonyms": ["in-person meeting"], "tags": ["work", "software"]},
    {"headword": "digital note-taking app", "pronunciation": "/ˈdɪdʒɪtl ˈnəʊt teɪkɪŋ æp/", "partOfSpeech": "noun", "definition": "A software application designed for recording, organizing, and synchronizing handwritten or typed notes.", "example": "Using a digital note-taking app on his tablet enabled the law student to search thousands of lecture pages instantly.", "translation": "تطبيق تدوين وتنظيم الملاحظات الرقمية", "collocations": ["use a digital note-taking app", "sync via digital note-taking app"], "synonyms": ["electronic notebook"], "antonyms": ["paper notebook"], "tags": ["productivity", "apps"]},
    {"headword": "wireless earbud convenience", "pronunciation": "/ˈwaɪələs ˈɪəbʌd kənˈviːniəns/", "partOfSpeech": "noun", "definition": "The practical freedom and mobility offered by cord-free Bluetooth headphones during exercise and calls.", "example": "The wireless earbud convenience allows commuters to listen to lectures without tangled cords.", "translation": "راحة وسهولة استخدام سماعات الأذن اللاسلكية", "collocations": ["enjoy wireless earbud convenience", "benefit from wireless earbud convenience"], "synonyms": ["cordless earbud utility"], "antonyms": [], "tags": ["gadgets", "convenience"]},
    {"headword": "smartphone addiction check", "pronunciation": "/ˈsmɑːtfəʊn əˈdɪkʃn tʃek/", "partOfSpeech": "noun", "definition": "A conscious self-assessment or software metric monitoring compulsive screen unlocking and app usage.", "example": "Doing a weekly smartphone addiction check prompted him to delete several distracting social media apps.", "translation": "فحص وتقييم إدمان الهاتف الذكي ومعدل الاستخدام", "collocations": ["run a smartphone addiction check", "conduct a smartphone addiction check"], "synonyms": ["digital dependency audit"], "antonyms": [], "tags": ["habits", "wellbeing"]},
    {"headword": "automated backup routine", "pronunciation": "/ˈɔːtəmeɪtɪd ˈbækʌp ruːˈtiːn/", "partOfSpeech": "noun", "definition": "A scheduled background computer process that duplicates critical system files without human intervention.", "example": "An automated backup routine runs every midnight to archive customer transactions safely.", "translation": "روتين النسخ الاحتياطي الآلي المجدول", "collocations": ["set up an automated backup routine", "schedule an automated backup routine"], "synonyms": ["scheduled backup process"], "antonyms": ["manual file copying"], "tags": ["security", "tech"]},
    {"headword": "smart home thermostat", "pronunciation": "/smɑːt həʊm ˈθɜːməstæt/", "partOfSpeech": "noun", "definition": "A programmable climate control device that learns household patterns to optimize heating and cooling.", "example": "Installing a smart home thermostat reduced the household's winter electricity bill by twenty-five percent.", "translation": "منظم الحرارة الذكي المبرمج للمنزل", "collocations": ["adjust the smart home thermostat", "install a smart home thermostat"], "synonyms": ["intelligent thermostat"], "antonyms": ["manual thermostat"], "tags": ["home", "energy"]},
    {"headword": "app notification clutter", "pronunciation": "/æp ˌnəʊtɪfɪˈkeɪʃn ˈklʌtə/", "partOfSpeech": "noun", "definition": "The overwhelming barrage of pop-up banners, badges, and alerts that disrupt mental focus.", "example": "Disabling marketing alerts cleared out persistent app notification clutter from his phone screen.", "translation": "فوضى وتراكم إشعارات التطبيقات المشتتة", "collocations": ["reduce app notification clutter", "silence app notification clutter"], "synonyms": ["notification overload"], "antonyms": ["peaceful screen"], "tags": ["tech", "productivity"]},

    # Workspace Ergonomics, Digital Hygiene & Connectivity
    {"headword": "home office setup", "pronunciation": "/həʊm ˈɒfɪs ˈsetʌp/", "partOfSpeech": "noun", "definition": "The ergonomic arrangement of desk, chair, monitors, and peripherals designed for remote work.", "example": "Investing in an adjustable standing desk transformed her home office setup into an ergonomic sanctuary.", "translation": "تجهيز وترتيب المكتب المنزلي للعمل عن بُعد", "collocations": ["upgrade home office setup", "ergonomic home office setup"], "synonyms": ["remote workspace"], "antonyms": [], "tags": ["work", "home"]},
    {"headword": "digital cleanup session", "pronunciation": "/ˈdɪdʒɪtl ˈkliːnʌp ˈseʃn/", "partOfSpeech": "noun", "definition": "A dedicated period spent purging unused apps, duplicate photos, and archived emails from devices.", "example": "A monthly digital cleanup session freed up sixty gigabytes of solid-state drive storage on his laptop.", "translation": "جلسة تنظيف وترتيب الملفات والبيانات الرقمية", "collocations": ["do a digital cleanup session", "schedule a digital cleanup session"], "synonyms": ["digital declutter"], "antonyms": [], "tags": ["productivity", "data"]},
    {"headword": "paperless office shift", "pronunciation": "/ˈpeɪpələs ˈɒfɪs ʃɪft/", "partOfSpeech": "noun", "definition": "The organizational transition from physical paper documentation to cloud-based digital records.", "example": "Embracing a paperless office shift eliminated ten bulky filing cabinets from the accounting firm.", "translation": "التحول نحو بيئة عمل رقمية لا ورقية", "collocations": ["accelerate the paperless office shift", "achieve a paperless office shift"], "synonyms": ["digital documentation transition"], "antonyms": ["paper-heavy office"], "tags": ["business", "environment"]},
    {"headword": "smart assistant prompt", "pronunciation": "/smɑːt əˈsɪstənt prɒmpt/", "partOfSpeech": "noun", "definition": "A vocal command or question given to an AI assistant like Alexa or Siri to trigger an action.", "example": "A simple smart assistant prompt turns on the porch lights and locks the front door each evening.", "translation": "الأمر الصوتي الموجه للمساعد الذكي", "collocations": ["issue a smart assistant prompt", "voice smart assistant prompt"], "synonyms": ["voice command"], "antonyms": [], "tags": ["ai", "gadgets"]},
    {"headword": "high-speed broadband plan", "pronunciation": "/haɪ spiːd ˈbrɔːdbænd plæn/", "partOfSpeech": "noun", "definition": "A fiber-optic or gigabit internet subscription providing ultra-fast download and upload bandwidth.", "example": "Upgrading to a high-speed broadband plan eliminated video buffering during concurrent family calls.", "translation": "باقة اشتراك الإنترنت فائق السرعة", "collocations": ["upgrade to a high-speed broadband plan", "reliable high-speed broadband plan"], "synonyms": ["fiber internet package"], "antonyms": ["dial-up connection"], "tags": ["internet", "telecom"]},
    {"headword": "online banking app", "pronunciation": "/ˌɒnˈlaɪn ˈbæŋkɪŋ æp/", "partOfSpeech": "noun", "definition": "A secure mobile application enabling users to transfer funds, pay utilities, and track balances.", "example": "Our online banking app sends real-time fraud alerts whenever an anomalous foreign purchase occurs.", "translation": "تطبيق الخدمات المصرفية والبنكية عبر الهاتف", "collocations": ["check the online banking app", "features of an online banking app"], "synonyms": ["mobile banking portal"], "antonyms": ["physical bank teller"], "tags": ["finance", "apps"]},
    {"headword": "streaming subscription", "pronunciation": "/ˈstriːmɪŋ səbˈskrɪpʃn/", "partOfSpeech": "noun", "definition": "A recurring paid service granting on-demand access to libraries of movies, television shows, or music.", "example": "Auditing each monthly streaming subscription saved our household fifty dollars in unused services.", "translation": "اشتراك منصات البث الرقمي للمحتوى", "collocations": ["cancel a streaming subscription", "monthly streaming subscription"], "synonyms": ["on-demand media membership"], "antonyms": [], "tags": ["entertainment", "media"]},
    {"headword": "password manager tool", "pronunciation": "/ˈpɑːswɜːd ˈmænɪdʒə tuːl/", "partOfSpeech": "noun", "definition": "An encrypted software application that generates, stores, and autofills complex unique passwords.", "example": "Using a reputable password manager tool ensures you never reuse identical credentials across accounts.", "translation": "أداة وتطبيق إدارة وحفظ كلمات المرور المشفرة", "collocations": ["install a password manager tool", "rely on a password manager tool"], "synonyms": ["credential vault"], "antonyms": ["plaintext password list"], "tags": ["security", "software"]},
    {"headword": "software update alert", "pronunciation": "/ˈsɒftweər ˈʌpdeɪt əˈlɜːt/", "partOfSpeech": "noun", "definition": "An operating system notification informing the user that new security patches or features are available.", "example": "Never ignore a software update alert, as patches protect against newly discovered security vulnerabilities.", "translation": "تنبيه توفر تحديثات البرامج الأمنية", "collocations": ["receive a software update alert", "install a software update alert"], "synonyms": ["system patch prompt"], "antonyms": [], "tags": ["it", "security"]},
    {"headword": "ergonomic workspace gadget", "pronunciation": "/ˌɜːɡəˈnɒmɪk ˈwɜːkspeɪs ˈɡædʒɪt/", "partOfSpeech": "noun", "definition": "A peripheral designed to prevent repetitive strain, such as a vertical mouse or wrist rest.", "example": "Purchasing an ergonomic workspace gadget like a split keyboard relieved his chronic wrist pain.", "translation": "أداة مكتبية مريحة مصممة لصحة الجسم وبيئة العمل", "collocations": ["use an ergonomic workspace gadget", "beneficial ergonomic workspace gadget"], "synonyms": ["orthopedic workstation tool"], "antonyms": [], "tags": ["ergonomics", "health"]},

    # Hardware, Privacy & Device Management
    {"headword": "remote desktop tool", "pronunciation": "/rɪˈməʊt ˈdesktɒp tuːl/", "partOfSpeech": "noun", "definition": "Software allowing a user to access, view, and operate a computer terminal from a distant device.", "example": "Using a secure remote desktop tool allowed the engineer to run simulation scripts on the office server from home.", "translation": "أداة التحكم بالكمبيوتر وسطح المكتب عن بُعد", "collocations": ["connect via remote desktop tool", "secure remote desktop tool"], "synonyms": ["remote access software"], "antonyms": [], "tags": ["it", "work"]},
    {"headword": "digital clutter removal", "pronunciation": "/ˈdɪdʒɪtl ˈklʌtə rɪˈmuːvl/", "partOfSpeech": "noun", "definition": "The intentional elimination of obsolete files, old screenshots, and disorganized folders.", "example": "Regular digital clutter removal accelerates computer operating speeds and improves mental focus.", "translation": "حذف وإزالة الفوضى الرقمية والملفات المتراكمة", "collocations": ["perform digital clutter removal", "routine digital clutter removal"], "synonyms": ["file system decluttering"], "antonyms": ["digital hoarding"], "tags": ["productivity", "data"]},
    {"headword": "dual-monitor workstation", "pronunciation": "/ˌdjuːəl ˈmɒnɪtə ˈwɜːksteɪʃn/", "partOfSpeech": "noun", "definition": "A desktop computer setup utilizing two display screens side-by-side to boost multitasking efficiency.", "example": "Software developers favor a dual-monitor workstation so code can be written on one screen and tested on the other.", "translation": "محطة عمل مزودة بشاشتي عرض لزيادة الإنتاجية", "collocations": ["build a dual-monitor workstation", "efficiency of a dual-monitor workstation"], "synonyms": ["twin-display setup"], "antonyms": ["single-monitor setup"], "tags": ["hardware", "work"]},
    {"headword": "tech troubleshooting step", "pronunciation": "/tek ˈtrʌblʃuːtɪŋ step/", "partOfSpeech": "noun", "definition": "A diagnostic action taken to isolate and resolve computer hardware or software glitches.", "example": "Powering down the router for thirty seconds is the foundational tech troubleshooting step for internet drops.", "translation": "خطوة تشخيص وحل الأعطال والمشاكل التقنية", "collocations": ["follow a tech troubleshooting step", "basic tech troubleshooting steps"], "synonyms": ["diagnostic action"], "antonyms": [], "tags": ["it", "troubleshooting"]},
    {"headword": "portable power bank", "pronunciation": "/ˈpɔːtəbl ˈpaʊə bæŋk/", "partOfSpeech": "noun", "definition": "A rechargeable external battery used to charge smartphones and electronics on the go.", "example": "Carrying a high-capacity portable power bank saved my battery during a twelve-hour train delay.", "translation": "شاحن متنقل / بنك طاقة محمول للأجهزة", "collocations": ["charge with a portable power bank", "high-capacity portable power bank"], "synonyms": ["external battery pack"], "antonyms": ["wall outlet"], "tags": ["hardware", "travel"]},
    {"headword": "smart lighting preset", "pronunciation": "/smɑːt ˈlaɪtɪŋ ˈpriːset/", "partOfSpeech": "noun", "definition": "A programmed configuration of home LED bulbs matching brightness and color warmth to specific moods.", "example": "Selecting the 'Reading' smart lighting preset dims overhead fixtures and bathes the room in warm amber light.", "translation": "الإعداد المبرمج مسبقاً للإضاءة المنزلية الذكية", "collocations": ["activate a smart lighting preset", "custom smart lighting preset"], "synonyms": ["automated lighting scene"], "antonyms": [], "tags": ["home", "tech"]},
    {"headword": "e-reader screen", "pronunciation": "/ˈiː riːdə skriːn/", "partOfSpeech": "noun", "definition": "An electronic paper display that mimics physical ink on paper without harmful backlight glare.", "example": "The matte e-reader screen prevents eye strain during long hours of outdoor reading in direct sunlight.", "translation": "شاشة القارئ الإلكتروني ذات الحبر الإلكتروني", "collocations": ["read on an e-reader screen", "glare-free e-reader screen"], "synonyms": ["electronic ink display"], "antonyms": ["backlit LCD screen"], "tags": ["books", "gadgets"]},
    {"headword": "noise-canceling headset", "pronunciation": "/nɔɪz ˈkænsəlɪŋ ˈhedset/", "partOfSpeech": "noun", "definition": "Headphones that produce inverse sound waves to neutralize ambient background office or transit noise.", "example": "Wearing a noise-canceling headset allowed him to concentrate in an overcrowded open-plan office.", "translation": "سماعة رأس عازلة للضوضاء والتشويش المحيط", "collocations": ["wear a noise-canceling headset", "active noise-canceling headset"], "synonyms": ["ANC headphones"], "antonyms": ["open-back headphones"], "tags": ["audio", "gadgets"]},
    {"headword": "voice dictation feature", "pronunciation": "/vɔɪs dɪkˈteɪʃn ˈfiːtʃə/", "partOfSpeech": "noun", "definition": "Speech-to-text software functionality transcribing spoken words into typed text in real time.", "example": "Enabling the voice dictation feature allowed the journalist to draft articles while pacing around her study.", "translation": "خاصية الإملاء الصوتي وتحويل الصوت إلى نص مكتوب", "collocations": ["use the voice dictation feature", "accuracy of the voice dictation feature"], "synonyms": ["speech-to-text functionality"], "antonyms": ["manual keyboard typing"], "tags": ["software", "ai"]},
    {"headword": "cloud storage sync", "pronunciation": "/klaʊd ˈstɔːrɪdʒ sɪŋk/", "partOfSpeech": "noun", "definition": "The continuous automatic alignment of files across personal devices and remote cloud servers.", "example": "Instant cloud storage sync ensures that edits made on your office laptop appear on your home desktop immediately.", "translation": "المزامنة الفورية مع مساحات التخزين السحابي", "collocations": ["enable cloud storage sync", "pause cloud storage sync"], "synonyms": ["cloud synchronization"], "antonyms": ["local isolation"], "tags": ["cloud", "data"]},

    # Automation, Digital Wellbeing & Device Health
    {"headword": "mobile payment convenience", "pronunciation": "/ˈməʊbaɪl ˈpeɪmənt kənˈviːniəns/", "partOfSpeech": "noun", "definition": "The ease of purchasing goods at terminals using smartphone near-field communication instead of cash or cards.", "example": "The mobile payment convenience allows commuters to tap through subway turnstiles with a wristwatch.", "translation": "سهولة الدفع الإلكتروني عبر الهاتف المحمول", "collocations": ["enjoy mobile payment convenience", "rely on mobile payment convenience"], "synonyms": ["contactless payment utility"], "antonyms": ["cash transaction"], "tags": ["finance", "convenience"]},
    {"headword": "smart calendar reminder", "pronunciation": "/smɑːt ˈkælɪndə rɪˈmaɪndə/", "partOfSpeech": "noun", "definition": "An automated notification that alerts users to upcoming appointments and factors in travel transit times.", "example": "A smart calendar reminder notified him to leave twenty minutes early due to unexpected freeway congestion.", "translation": "تنبيه التقويم الذكي المجدول للمواعيد", "collocations": ["receive a smart calendar reminder", "set a smart calendar reminder"], "synonyms": ["automated calendar alert"], "antonyms": [], "tags": ["productivity", "planning"]},
    {"headword": "device battery lifespan", "pronunciation": "/dɪˈvaɪs ˈbætəri ˈlaɪfspæn/", "partOfSpeech": "noun", "definition": "The total operational duration or degradation longevity of a rechargeable battery over months of charge cycles.", "example": "Capping charge levels at eighty percent preserves device battery lifespan across several years.", "translation": "العمر الافتراضي والتشغيلي لبطارية الجهاز", "collocations": ["extend device battery lifespan", "degrade device battery lifespan"], "synonyms": ["battery longevity"], "antonyms": ["battery death"], "tags": ["hardware", "maintenance"]},
    {"headword": "screen glare filter", "pronunciation": "/skriːn ɡleə ˈfɪltə/", "partOfSpeech": "noun", "definition": "A physical anti-reflective overlay or software mode that reduces harsh specular reflections from displays.", "example": "Attaching a screen glare filter to his office monitor eliminated late-afternoon tension headaches.", "translation": "مرشح وفلتر تقليل توهج وانعكاسات الشاشة", "collocations": ["install a screen glare filter", "matte screen glare filter"], "synonyms": ["anti-glare protector"], "antonyms": ["glossy screen"], "tags": ["health", "hardware"]},
    {"headword": "tech-free evening", "pronunciation": "/tek friː ˈiːvnɪŋ/", "partOfSpeech": "noun", "definition": "An evening deliberately spent without checking computers, smartphones, televisions, or electronic gaming devices.", "example": "Every Sunday, the household observes a tech-free evening dedicated to board games and home cooking.", "translation": "أمسية خالية تماماً من الأجهزة والشاشات", "collocations": ["enjoy a tech-free evening", "commit to a tech-free evening"], "synonyms": ["unplugged evening"], "antonyms": ["screen binge evening"], "tags": ["wellness", "lifestyle"]},
    {"headword": "smart home hub", "pronunciation": "/smɑːt həʊm hʌb/", "partOfSpeech": "noun", "definition": "A central hardware or software controller connecting diverse smart home protocols into a single network.", "example": "The wireless smart home hub bridges communication between smart lights, door sensors, and thermostats.", "translation": "وحدة التحكم المركزية لأجهزة المنزل الذكي", "collocations": ["connect to the smart home hub", "configure the smart home hub"], "synonyms": ["central automation controller"], "antonyms": [], "tags": ["home", "iot"]},
    {"headword": "digital declutter routine", "pronunciation": "/ˈdɪdʒɪtl diːˈklʌtə ruːˈtiːn/", "partOfSpeech": "noun", "definition": "A regular habit of organizing digital files, deleting unused software, and archiving project data.", "example": "Establishing a Friday digital declutter routine keeps desktops clean and folders impeccably indexed.", "translation": "روتين التخلص من الفوضى وتنظيم الملفات الرقمية", "collocations": ["follow a digital declutter routine", "weekly digital declutter routine"], "synonyms": ["data organization habit"], "antonyms": ["digital hoarding"], "tags": ["productivity", "habits"]},
    {"headword": "backup hard drive", "pronunciation": "/ˈbækʌp hɑːd draɪv/", "partOfSpeech": "noun", "definition": "A physical external storage disk used to maintain redundant offline copies of vital files.", "example": "In addition to cloud backups, she stores an encrypted copy of her manuscript on a backup hard drive.", "translation": "قرص التخزين الصلب الخارجي للنسخ الاحتياطي", "collocations": ["plug in a backup hard drive", "encrypted backup hard drive"], "synonyms": ["external hard disk"], "antonyms": [], "tags": ["hardware", "storage"]},
    {"headword": "touchscreen responsiveness", "pronunciation": "/ˈtʌtʃskriːn rɪˈspɒnsɪvnəs/", "partOfSpeech": "noun", "definition": "The speed and accuracy with which a touch-sensitive electronic display registers finger gestures.", "example": "The new tablet was praised for its instantaneous touchscreen responsiveness and stylus tracking.", "translation": "سرعة ودقة استجابة الشاشة التي تعمل باللمس", "collocations": ["flawless touchscreen responsiveness", "test touchscreen responsiveness"], "synonyms": ["touch sensitivity"], "antonyms": ["touchscreen lag"], "tags": ["hardware", "performance"]},
    {"headword": "app ecosystem integration", "pronunciation": "/æp ˈiːkəʊsɪstəm ˌɪntɪˈɡreɪʃn/", "partOfSpeech": "noun", "definition": "The seamless interoperability between various mobile applications, desktop software, and cloud tools.", "example": "Smooth app ecosystem integration allows users to open calendar events directly from email text.", "translation": "التكامل والترابط السلس بين منظومة التطبيقات", "collocations": ["seamless app ecosystem integration", "benefit from app ecosystem integration"], "synonyms": ["software interoperability"], "antonyms": ["siloed apps"], "tags": ["software", "tech"]},
    {"headword": "video conferencing background", "pronunciation": "/ˈvɪdiəʊ ˈkɒnfərənsɪŋ ˈbækɡraʊnd/", "partOfSpeech": "noun", "definition": "A virtual or blurred digital image chosen to hide a messy room during online video calls.", "example": "Applying a professional video conferencing background concealed the laundry drying in her home office.", "translation": "الخلفية الرقمية المخصصة لمكالمات الفيديو", "collocations": ["set a video conferencing background", "blur the video conferencing background"], "synonyms": ["virtual background"], "antonyms": ["live physical background"], "tags": ["work", "video"]},
    {"headword": "smart door lock", "pronunciation": "/smɑːt dɔː lɒk/", "partOfSpeech": "noun", "definition": "An electromechanical lock designed to lock and unlock a portal upon receiving authorized digital signals.", "example": "Installing a biometric smart door lock allows family members to enter using fingerprint scans.", "translation": "قفل الباب الذكي الذي يعمل بالبصمة أو الهاتف", "collocations": ["install a smart door lock", "features of a smart door lock"], "synonyms": ["electronic door lock"], "antonyms": ["traditional keyed lock"], "tags": ["security", "home"]},
    {"headword": "wearable health metric", "pronunciation": "/ˈweərəbl helθ ˈmetrɪk/", "partOfSpeech": "noun", "definition": "Biological data tracked continuously by smart garments or watches, such as heart rate variability or oxygen saturation.", "example": "Her doctor evaluated six months of wearable health metrics to assess recovery from cardiac surgery.", "translation": "المؤشر الحيوي والصحي المقاس بالأجهزة القابلة للارتداء", "collocations": ["monitor wearable health metrics", "track wearable health metrics"], "synonyms": ["biometric reading"], "antonyms": [], "tags": ["health", "wearables"]},
    {"headword": "cable management solution", "pronunciation": "/ˈkeɪbl ˈmænɪdʒmənt səˈluːʃn/", "partOfSpeech": "noun", "definition": "Clips, sleeves, and under-desk trays used to organize and conceal unsightly computer cords.", "example": "Implementing an under-desk cable management solution transformed the tangled mess into an orderly workspace.", "translation": "حلول تنظيم وترتيب كابلات وأسلاك الأجهزة", "collocations": ["install a cable management solution", "effective cable management solution"], "synonyms": ["wire organizer"], "antonyms": ["tangled wires"], "tags": ["ergonomics", "hardware"]},
    {"headword": "digital workspace setup", "pronunciation": "/ˈdɪdʒɪtl ˈwɜːkspeɪs ˈsetʌp/", "partOfSpeech": "noun", "definition": "The customized configuration of computer software, browser bookmarks, and cloud directories for efficiency.", "example": "A minimalist digital workspace setup with pinned task dashboards eliminates daily administrative clutter.", "translation": "تهيئة وتخصيص بيئة العمل الرقمية على الكمبيوتر", "collocations": ["optimize digital workspace setup", "streamlined digital workspace setup"], "synonyms": ["virtual desktop environment"], "antonyms": [], "tags": ["productivity", "software"]},
    {"headword": "personal cloud server", "pronunciation": "/ˈpɜːsənl klaʊd ˈsɜːvə/", "partOfSpeech": "noun", "definition": "A private network-attached storage device hosted in one's home offering cloud convenience with total privacy.", "example": "Hosting a personal cloud server allows the photographer to access RAW archives without third-party fees.", "translation": "خادم السحابة الشخصي المنزلي المستقل", "collocations": ["host a personal cloud server", "build a personal cloud server"], "synonyms": ["home NAS server"], "antonyms": ["public cloud server"], "tags": ["hardware", "cloud"]},
    {"headword": "automated workflow trigger", "pronunciation": "/ˈɔːtəmeɪtɪd ˈwɜːkfləʊ ˈtrɪɡə/", "partOfSpeech": "noun", "definition": "A condition in software that automatically initiates a subsequent task, such as archiving emailed attachments.", "example": "Setting an automated workflow trigger automatically saves incoming PDF invoices directly to Dropbox.", "translation": "محفز ومنطلق تدفق المهام الآلي", "collocations": ["configure an automated workflow trigger", "create an automated workflow trigger"], "synonyms": ["automation rule"], "antonyms": ["manual trigger"], "tags": ["automation", "productivity"]},
    {"headword": "wi-fi signal booster", "pronunciation": "/ˈwaɪ faɪ ˈsɪɡnl ˈbuːstə/", "partOfSpeech": "noun", "definition": "A hardware repeater or mesh node designed to extend wireless internet coverage to distant dead zones.", "example": "Installing a wi-fi signal booster in the upstairs hallway eliminated buffering during evening video streaming.", "translation": "جهاز تقوية وتوسيع نطاق إشارة الواي فاي", "collocations": ["plug in a wi-fi signal booster", "dual-band wi-fi signal booster"], "synonyms": ["wireless range extender", "mesh node"], "antonyms": ["dead zone"], "tags": ["networking", "hardware"]},
    {"headword": "digital productivity suite", "pronunciation": "/ˈdɪdʒɪtl ˌprɒdʌkˈtɪvəti swiːt/", "partOfSpeech": "noun", "definition": "A bundled collection of business applications including word processors, spreadsheets, and cloud storage.", "example": "Google Workspace and Microsoft 365 are ubiquitous examples of a comprehensive digital productivity suite.", "translation": "حزمة برامج وتطبيقات الإنتاجية المكتبية الرقمية", "collocations": ["adopt a digital productivity suite", "enterprise digital productivity suite"], "synonyms": ["office suite"], "antonyms": [], "tags": ["software", "productivity"]},
    {"headword": "device sync status", "pronunciation": "/dɪˈvaɪs sɪŋk ˈsteɪtəs/", "partOfSpeech": "noun", "definition": "The system confirmation indicating whether files on a device are fully harmonized with the cloud repository.", "example": "A green checkmark in the taskbar confirms that your device sync status is completely up to date.", "translation": "حالة اكتمال مزامنة وتطابق بيانات الجهاز مع السحابة", "collocations": ["check device sync status", "verify device sync status"], "synonyms": ["synchronization state"], "antonyms": ["sync conflict"], "tags": ["cloud", "data"]}
]

grammar_85 = [
    {
        "title": "Passive Voice + Technology Vocabulary Review",
        "explanation": "Describing technology in daily life relies heavily on passive voice structures across all tenses to focus on how devices, files, and systems are processed, configured, or updated without centering the user:\n\n1. Present Passive (is / are + V3):\n   - 'All confidential files are encrypted before cloud storage sync is initiated.'\n   - 'Smart home devices are managed through a central smart home hub.'\n\n2. Past Passive (was / were + V3):\n   - 'An automated backup routine was executed at midnight by the personal cloud server.'\n   - 'The software update alert was delivered to all registered devices.'\n\n3. Modal Passives (can / must / should + be + V3):\n   - 'Device battery lifespan can be extended by avoiding overnight charging.'\n   - 'A reputable password manager tool must be installed to prevent identity theft.'\n   - 'Screen glare filters should be attached to office monitors to reduce eye fatigue.'\n\n4. Perfect Passives (has / have been + V3):\n   - 'The home office setup has been upgraded with a dual-monitor workstation.'\n   - 'App notification clutter has been eliminated across all smartphone home screens.'",
        "structures": [
            {"pattern": "Present Passive: Subject + is / are + V3: 'Files are synchronized automatically through cloud storage sync.'"},
            {"pattern": "Modal Passive: Subject + modal + be + V3: 'App notification clutter must be silenced to preserve mental focus.'"},
            {"pattern": "Perfect Passive: Subject + have / has been + V3: 'A high-speed broadband plan has been configured in the home office.'"}
        ],
        "examples": [
            {
                "sentence": "Every smart home device in the building is connected to an encrypted personal cloud server.",
                "arabic": "كل جهاز من أجهزة المنزل الذكي في المبنى متصل بخادم سحابي شخصي مشفر.",
                "usesVocabulary": ["smart home device", "personal cloud server"]
            },
            {
                "sentence": "An automated backup routine was configured to run whenever device sync status is confirmed.",
                "arabic": "تم تكوين روتين نسخ احتياطي آلي ليعمل كلما تم تأكيد حالة مزامنة الجهاز.",
                "usesVocabulary": ["automated backup routine", "device sync status"]
            },
            {
                "sentence": "Device battery lifespan can be maximized when background app refresh is disabled.",
                "arabic": "يمكن زيادة العمر الافتراضي لبطارية الجهاز إلى أقصى حد عندما يتم تعطيل تحديث التطبيقات في الخلفية.",
                "usesVocabulary": ["device battery lifespan"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "The files are sync automatically every midnight.",
                "right": "The files are synced automatically every midnight.",
                "explanation": "Passive voice always requires the Past Participle (V3), e.g., 'synced', not the base form."
            },
            {
                "wrong": "The password manager tool must to be updated immediately.",
                "right": "The password manager tool must be updated immediately.",
                "explanation": "Modal passive structures use modal + 'be' (without 'to') + past participle."
            }
        ]
    }
]

convs_85 = [
    {
        "title": "Home Tech Upgrade: Smart Living and Ergonomics",
        "titleArabic": "ترقية تقنيات المنزل: المعيشة الذكية وبيئة العمل",
        "setting": "Two remote professionals discuss upgrading their home workspace and devices.",
        "lines": [
            {"speaker": "Oliver", "text": "I finally overhauled my home office setup with a dual-monitor workstation and an ergonomic workspace gadget."},
            {"speaker": "Nora", "text": "That sounds magnificent! Is your workstation equipped with an effective cable management solution?"},
            {"speaker": "Oliver", "text": "Yes, everything is neatly routed. I also attached a screen glare filter and use a virtual meeting tool with a custom video conferencing background."},
            {"speaker": "Nora", "text": "Did you connect your smart home devices to a central smart home hub?"},
            {"speaker": "Oliver", "text": "Indeed. A single smart assistant prompt adjusts our smart home thermostat and activates the smart lighting preset."},
            {"speaker": "Nora", "text": "Our new wi-fi signal booster eliminated dead zones, and our high-speed broadband plan handles concurrent video calls effortlessly."},
            {"speaker": "Oliver", "text": "I also installed a biometric smart door lock for seamless keyless entry."},
            {"speaker": "Nora", "text": "Technology is wonderful when it is seamlessly integrated into domestic routines."}
        ],
        "vocabularyUsed": ["home office setup", "dual-monitor workstation", "ergonomic workspace gadget", "cable management solution", "screen glare filter", "virtual meeting tool", "video conferencing background", "smart home device", "smart home hub", "smart assistant prompt", "smart home thermostat", "smart lighting preset", "wi-fi signal booster", "high-speed broadband plan", "smart door lock"]
    },
    {
        "title": "Digital Wellbeing Dialogue: Curing Screen Fatigue",
        "titleArabic": "حوار الرفاه الرقمي: علاج إجهاد الشاشات",
        "setting": "A wellness consultant advises a client on digital minimalism and tech habits.",
        "lines": [
            {"speaker": "Consultant", "text": "When did you last run a smartphone addiction check on your screen time dashboard?"},
            {"speaker": "Client", "text": "Last Sunday, and the statistics were alarming. App notification clutter was interrupting my concentration every ten minutes."},
            {"speaker": "Consultant", "text": "A thorough digital cleanup session and a regular digital declutter routine should be established immediately."},
            {"speaker": "Client", "text": "I disabled push alerts and instituted a mandatory tech-free evening every Wednesday."},
            {"speaker": "Consultant", "text": "Excellent. To rest your eyes before bed, read on a glare-free e-reader screen rather than an illuminated tablet."},
            {"speaker": "Client", "text": "During work, wearing a noise-canceling headset helps me ignore ambient chatter."},
            {"speaker": "Consultant", "text": "Monitoring your wearable health metrics and checking your wearable fitness tracker will confirm that your physical stress declines."},
            {"speaker": "Client", "text": "Embracing digital minimalism has already restored my mental composure."}
        ],
        "vocabularyUsed": ["smartphone addiction check", "app notification clutter", "digital cleanup session", "digital declutter routine", "tech-free evening", "e-reader screen", "noise-canceling headset", "wearable health metric", "wearable fitness tracker"]
    },
    {
        "title": "IT Security and Data Protection Consultation",
        "titleArabic": "استشارة أمن المعلومات وحماية البيانات الرقمية",
        "setting": "A freelance designer consults an IT security specialist about data backups and tools.",
        "lines": [
            {"speaker": "Designer", "text": "I lost three days of illustration files last year. What automated backup routine do you recommend?"},
            {"speaker": "IT Specialist", "text": "Pair a reliable cloud backup service with a secondary encrypted backup hard drive and a personal cloud server."},
            {"speaker": "Designer", "text": "How do I ensure that device sync status is maintained across my laptop and tablet?"},
            {"speaker": "IT Specialist", "text": "Enable cloud storage sync, and verify your automated workflow triggers whenever a software update alert appears."},
            {"speaker": "Designer", "text": "I started using a password manager tool and an online banking app featuring biometric verification."},
            {"speaker": "IT Specialist", "text": "Splendid! When traveling, keep a high-capacity portable power bank to safeguard device battery lifespan."},
            {"speaker": "Designer", "text": "Our studio is also accelerating our paperless office shift with a unified digital productivity suite."},
            {"speaker": "IT Specialist", "text": "That guarantees total workflow security and client confidentiality."}
        ],
        "vocabularyUsed": ["automated backup routine", "cloud backup service", "backup hard drive", "personal cloud server", "device sync status", "cloud storage sync", "automated workflow trigger", "software update alert", "password manager tool", "online banking app", "portable power bank", "device battery lifespan", "paperless office shift", "digital productivity suite"]
    }
]

paras_85 = [
    {
        "title": "Smart Living, Home Automation, and Domestic Integration",
        "titleArabic": "المعيشة الذكية، أتمتة المنازل، والتكامل التقني المنزلي",
        "text": "Modern domestic life has been fundamentally revolutionized by connected technology. Within an integrated smart home, every smart home device communicates seamlessly through a central smart home hub. With a single smart assistant prompt, the smart home thermostat adjusts room temperatures, while the smart lighting preset transitions overhead bulbs to warm evening hues. Security is reinforced because biometric smart door locks are operated remotely via encrypted apps. Supported by a dependable high-speed broadband plan and strategic wi-fi signal boosters, households enjoy uninterrupted streaming subscriptions and wireless earbud convenience without network dropouts. Residents also benefit from daily mobile payment convenience and reliable smart calendar reminders that coordinate busy family schedules.",
        "vocabularyUsed": ["smart home device", "smart home hub", "smart assistant prompt", "smart home thermostat", "smart lighting preset", "smart door lock", "high-speed broadband plan", "wi-fi signal booster", "streaming subscription", "wireless earbud convenience", "mobile payment convenience", "smart calendar reminder"]
    },
    {
        "title": "Digital Workspace Ergonomics, Productivity, and Workflow Security",
        "titleArabic": "بيئة العمل الرقمية، الإنتاجية، وأمن تدفق العمليات",
        "text": "Transitioning to remote employment requires an intentional home office setup and an optimized digital workspace setup that protects physical health and data security. Setting up a dual-monitor workstation alongside beneficial ergonomic workspace gadgets relieves muscular fatigue, while under-desk cable management solutions keep floors clear. Knowledge workers rely on a secure remote desktop tool and a versatile digital note-taking app to collaborate across distances. On the software side, companies accelerate their paperless office shift by deploying a cloud-based digital productivity suite. To safeguard valuable commercial assets, an automated backup routine is maintained through a secure cloud backup service and physical backup hard drive. Furthermore, by configuring automated workflow triggers, teams streamline administrative tasks and verify device sync status effortlessly.",
        "vocabularyUsed": ["home office setup", "digital workspace setup", "dual-monitor workstation", "ergonomic workspace gadget", "cable management solution", "remote desktop tool", "digital note-taking app", "paperless office shift", "digital productivity suite", "automated backup routine", "cloud backup service", "backup hard drive", "automated workflow trigger", "device sync status"]
    },
    {
        "title": "Digital Hygiene, Data Sovereignty, and Cognitive Wellbeing",
        "titleArabic": "النظافة الرقمية، سيادة البيانات، والرفاه الإدراكي",
        "text": "Maintaining a healthy relationship with personal technology requires consistent digital hygiene. Conducting a weekly smartphone addiction check helps users recognize addictive scrolling, prompting deliberate digital cleanup sessions to silence app notification clutter and perform thorough digital clutter removal. During intensive knowledge work, wearing a noise-canceling headset creates deep concentration, while screen glare filters prevent visual fatigue. In private computing, hosting a personal cloud server and utilizing a reputable password manager tool guarantees privacy. Meanwhile, monitoring steps with a wearable fitness tracker encourages outdoor movement away from displays. Finally, disconnecting completely during a weekly tech-free evening restores mental tranquility, ensuring technology remains a tool for human flourishing rather than cognitive entrapment.",
        "vocabularyUsed": ["smartphone addiction check", "digital cleanup session", "app notification clutter", "digital clutter removal", "noise-canceling headset", "screen glare filter", "personal cloud server", "password manager tool", "wearable fitness tracker", "tech-free evening"]
    }
]

# ==============================================================================
# DAY 86: Health and Choices (Lifestyle decisions)
# Grammar: Modals + Conditionals Review
# ==============================================================================

vocab_86 = [
    # Mindful Nutrition, Restorative Sleep & Preventative Habits
    {"headword": "mindful eating habit", "pronunciation": "/ˈmaɪndfl ˈiːtɪŋ ˈhæbɪt/", "partOfSpeech": "noun", "definition": "The practice of eating slowly, savoring flavors, and paying conscious attention to hunger and fullness cues.", "example": "Cultivating a mindful eating habit prevented him from overeating while working at his computer.", "translation": "عادة الأكل الواعي والمتأني مع تذوق الطعام", "collocations": ["develop a mindful eating habit", "practice a mindful eating habit"], "synonyms": ["conscious eating"], "antonyms": ["distracted eating"], "tags": ["nutrition", "mindfulness"]},
    {"headword": "restorative sleep cycle", "pronunciation": "/rɪˈstɔːrətɪv sliːp ˈsaɪkl/", "partOfSpeech": "noun", "definition": "A complete, uninterrupted nighttime sleep rhythm featuring adequate deep sleep and REM phases.", "example": "Protecting a restorative sleep cycle of eight hours enhances immune defense and cognitive sharpness.", "translation": "دورة النوم العميق والمجدد للحيوية", "collocations": ["enjoy a restorative sleep cycle", "disrupt the restorative sleep cycle"], "synonyms": ["rejuvenating sleep"], "antonyms": ["fragmented sleep"], "tags": ["sleep", "health"]},
    {"headword": "daily step target", "pronunciation": "/ˈdeɪli step ˈtɑːɡɪt/", "partOfSpeech": "noun", "definition": "A predetermined goal of walking a specific number of steps (such as ten thousand) each day.", "example": "Hitting his daily step target became effortless once he started walking to the railway station.", "translation": "هدف عدد الخطوات اليومية المحدد للمشي", "collocations": ["reach a daily step target", "track a daily step target"], "synonyms": ["daily step goal"], "antonyms": [], "tags": ["fitness", "walking"]},
    {"headword": "balanced meal plate", "pronunciation": "/ˈbælənst miːl pleɪt/", "partOfSpeech": "noun", "definition": "A nutritional portioning model dividing a plate into equal portions of lean protein, greens, and complex carbohydrates.", "example": "Her nutritionist recommended a balanced meal plate rich in colorful vegetables and olive oil.", "translation": "طبق الوجبة المتوازنة غذائياً وصحياً", "collocations": ["build a balanced meal plate", "principles of a balanced meal plate"], "synonyms": ["nutritious plate"], "antonyms": ["nutrient-deficient meal"], "tags": ["nutrition", "food"]},
    {"headword": "hydration routine", "pronunciation": "/haɪˈdreɪʃn ruːˈtiːn/", "partOfSpeech": "noun", "definition": "A disciplined schedule for drinking adequate fresh water consistently from morning until evening.", "example": "Her morning hydration routine begins with drinking a large glass of warm lemon water before coffee.", "translation": "روتين شرب الماء وترطيب الجسم المنتظم", "collocations": ["follow a hydration routine", "strict hydration routine"], "synonyms": ["water-drinking schedule"], "antonyms": ["dehydration"], "tags": ["health", "habits"]},
    {"headword": "stress relief practice", "pronunciation": "/stres rɪˈliːf ˈpræktɪs/", "partOfSpeech": "noun", "definition": "A regular therapeutic technique—such as yoga or deep breathing—designed to lower cortisol and anxiety.", "example": "Daily gardening operates as his primary stress relief practice after high-pressure corporate negotiations.", "translation": "ممارسة تخفيف الضغوط والتوتر النفسي", "collocations": ["adopt a stress relief practice", "effective stress relief practice"], "synonyms": ["relaxation technique"], "antonyms": [], "tags": ["wellness", "stress"]},
    {"headword": "mindfulness meditation session", "pronunciation": "/ˈmaɪndflnəs ˌmedɪˈteɪʃn ˈseʃn/", "partOfSpeech": "noun", "definition": "A dedicated period of sitting quietly and anchoring awareness non-judgmentally to the present moment.", "example": "A fifteen-minute mindfulness meditation session at dawn centers her mind for complex surgery.", "translation": "جلسة التأمل الواعي وحضور الذهن", "collocations": ["attend a mindfulness meditation session", "daily mindfulness meditation session"], "synonyms": ["meditation practice"], "antonyms": [], "tags": ["mindfulness", "meditation"]},
    {"headword": "morning stretching routine", "pronunciation": "/ˈmɔːnɪŋ ˈstretʃɪŋ ruːˈtiːn/", "partOfSpeech": "noun", "definition": "A sequence of mobility exercises performed upon waking to elongate tight muscles and mobilize joints.", "example": "Committing to a ten-minute morning stretching routine completely relieved his chronic lower back pain.", "translation": "روتين تمارين التمدد والإطالة الصباحية", "collocations": ["follow a morning stretching routine", "gentle morning stretching routine"], "synonyms": ["morning mobility routine"], "antonyms": [], "tags": ["fitness", "morning"]},
    {"headword": "healthy snack swap", "pronunciation": "/ˈhelθi snæk swɒp/", "partOfSpeech": "noun", "definition": "Replacing processed potato crisps or sugary biscuits with nutritious alternatives like almonds or fresh berries.", "example": "Making a simple healthy snack swap from candy bars to walnuts lowered her cholesterol within months.", "translation": "استبدال المقرمشات الضارة بوجبات خفيفة صحية", "collocations": ["make a healthy snack swap", "smart healthy snack swap"], "synonyms": ["nutritious substitution"], "antonyms": [], "tags": ["nutrition", "diet"]},
    {"headword": "outdoor cardio workout", "pronunciation": "/ˈaʊtdɔː ˈkɑːdiəʊ ˈwɜːkaʊt/", "partOfSpeech": "noun", "definition": "Cardiovascular exercise performed in fresh air, such as trail running, road cycling, or rowing.", "example": "An invigorating outdoor cardio workout along the riverbanks lifts his mood far more than an indoor treadmill.", "translation": "التمرين الهوائي القلبي في الهواء الطلق", "collocations": ["enjoy an outdoor cardio workout", "invigorating outdoor cardio workout"], "synonyms": ["open-air exercise"], "antonyms": ["gym treadmill workout"], "tags": ["fitness", "exercise"]},

    # Medical Prevention, Mental Health & Physical Conditioning
    {"headword": "preventative check-up", "pronunciation": "/prɪˈventətɪv ˈtʃek ʌp/", "partOfSpeech": "noun", "definition": "A routine medical consultation and screening designed to detect diseases early before symptoms arise.", "example": "Scheduling an annual preventative check-up is the cornerstone of proactive long-term wellness.", "translation": "الفحص الطبي الوقائي الدوري للكشف المبكر", "collocations": ["schedule a preventative check-up", "annual preventative check-up"], "synonyms": ["routine health screening"], "antonyms": ["emergency visit"], "tags": ["medicine", "health"]},
    {"headword": "mental health day", "pronunciation": "/ˈmentl helθ deɪ/", "partOfSpeech": "noun", "definition": "A leave of absence taken from work or school specifically to relieve psychological stress and burnout.", "example": "Recognizing severe emotional exhaustion, she took a well-deserved mental health day to walk in the forest.", "translation": "يوم إجازة مخصص للصحة النفسية والاستشفاء", "collocations": ["take a mental health day", "need a mental health day"], "synonyms": ["burnout recovery day"], "antonyms": [], "tags": ["mental health", "wellness"]},
    {"headword": "posture correction habit", "pronunciation": "/ˈpɒstʃə kəˈrekʃn ˈhæbɪt/", "partOfSpeech": "noun", "definition": "The regular practice of aligning spine, shoulders, and neck properly while sitting or standing.", "example": "Setting a gentle chime on his smartwatch helped him build an automatic posture correction habit.", "translation": "عادة تعديل وتصحيح وضعية الجلوس والقامة", "collocations": ["build a posture correction habit", "reinforce a posture correction habit"], "synonyms": ["ergonomic posture discipline"], "antonyms": ["slouching"], "tags": ["ergonomics", "health"]},
    {"headword": "sugar intake reduction", "pronunciation": "/ˈʃʊɡər ˈɪnteɪk rɪˈdʌkʃn/", "partOfSpeech": "noun", "definition": "The deliberate dietary limitation of added sugars in sodas, desserts, and processed condiments.", "example": "A noticeable increase in daytime energy accompanied his gradual sugar intake reduction.", "translation": "تقليل والحد من تناول واستهلاك السكر", "collocations": ["achieve sugar intake reduction", "commit to sugar intake reduction"], "synonyms": ["sugar limitation"], "antonyms": ["excessive sugar consumption"], "tags": ["diet", "health"]},
    {"headword": "strength training routine", "pronunciation": "/streŋθ ˈtreɪnɪŋ ruːˈtiːn/", "partOfSpeech": "noun", "definition": "A structured exercise program using weights or resistance bands to increase muscle mass and bone density.", "example": "Maintaining a biweekly strength training routine prevents muscle loss and osteoporosis as adults age.", "translation": "روتين تمارين القوة وبناء العضلات", "collocations": ["stick to a strength training routine", "effective strength training routine"], "synonyms": ["resistance training program"], "antonyms": ["sedentary habits"], "tags": ["fitness", "exercise"]},
    {"headword": "herbal tea habit", "pronunciation": "/ˈhɜːbl tiː ˈhæbɪt/", "partOfSpeech": "noun", "definition": "The relaxing daily practice of drinking caffeine-free infusions like chamomile, peppermint, or ginger.", "example": "Replacing late-night coffee with a soothing herbal tea habit significantly deepened his sleep.", "translation": "عادة شرب شاي الأعشاب الطبيعي المهدئ", "collocations": ["cultivate a herbal tea habit", "evening herbal tea habit"], "synonyms": ["herbal infusion habit"], "antonyms": [], "tags": ["nutrition", "beverages"]},
    {"headword": "guided breathing exercise", "pronunciation": "/ˈɡaɪdɪd ˈbriːðɪŋ ˈeksəsaɪz/", "partOfSpeech": "noun", "definition": "A controlled inhalation and exhalation protocol paced by an instructor or audio guide to reduce heart rate.", "example": "A four-minute guided breathing exercise helped the executive overcome stage fright before her speech.", "translation": "تمرين التنفس الموجه لتهدئة ضربات القلب", "collocations": ["practice a guided breathing exercise", "follow a guided breathing exercise"], "synonyms": ["paced breathwork"], "antonyms": [], "tags": ["wellness", "breath"]},
    {"headword": "active recovery day", "pronunciation": "/ˈæktɪv rɪˈkʌvəri deɪ/", "partOfSpeech": "noun", "definition": "A rest day from intense workouts involving low-intensity movement like walking or gentle yoga to promote blood flow.", "example": "Sunday was an active recovery day featuring an unhurried bike ride along the country canal.", "translation": "يوم الاستشفاء النشط بالحركة الخفيفة", "collocations": ["plan an active recovery day", "benefit of an active recovery day"], "synonyms": ["light movement day"], "antonyms": ["strenuous training day"], "tags": ["fitness", "rest"]},
    {"headword": "clean eating philosophy", "pronunciation": "/kliːn ˈiːtɪŋ fəˈlɒsəfi/", "partOfSpeech": "noun", "definition": "A dietary approach focused on consuming whole, unrefined, minimally processed foods free of artificial additives.", "example": "Her clean eating philosophy prioritizes organic seasonal produce and pasture-raised eggs.", "translation": "فلسفة الغذاء النظيف والطبيعي غير المصنع", "collocations": ["adopt a clean eating philosophy", "follow a clean eating philosophy"], "synonyms": ["whole-foods approach"], "antonyms": ["processed food diet"], "tags": ["nutrition", "philosophy"]},
    {"headword": "sleep quality tracker", "pronunciation": "/sliːp ˈkwɒləti ˈtrækə/", "partOfSpeech": "noun", "definition": "A device or mobile app analyzing sleep latency, deep sleep duration, and nighttime awakenings.", "example": "Consulting his sleep quality tracker revealed that drinking alcohol ruined his restorative REM cycles.", "translation": "متتبع ومقياس جودة النوم وعمقه", "collocations": ["monitor via sleep quality tracker", "insights from a sleep quality tracker"], "synonyms": ["sleep monitor"], "antonyms": [], "tags": ["sleep", "gadgets"]},

    # Daily Movement, Nutrition & Holistic Vitality
    {"headword": "walking lunch break", "pronunciation": "/ˈwɔːkɪŋ lʌntʃ breɪk/", "partOfSpeech": "noun", "definition": "Using midday work intermission to take a brisk outdoor walk rather than remaining seated at a desk.", "example": "A twenty-minute walking lunch break through the botanical gardens re-energized his afternoon productivity.", "translation": "استراحة غداء مخصصة للمشي في الهواء الطلق", "collocations": ["take a walking lunch break", "benefit from a walking lunch break"], "synonyms": ["midday stroll"], "antonyms": ["desk dining"], "tags": ["fitness", "work"]},
    {"headword": "daily meditation practice", "pronunciation": "/ˈdeɪli ˌmedɪˈteɪʃn ˈpræktɪs/", "partOfSpeech": "noun", "definition": "The consistent commitment to sit quietly each day to cultivate stillness, emotional balance, and clarity.", "example": "A ten-minute daily meditation practice significantly lowered her anxiety during medical examinations.", "translation": "الممارسة اليومية الثابتة للتأمل والسكينة", "collocations": ["maintain a daily meditation practice", "commit to a daily meditation practice"], "synonyms": ["daily mindfulness habit"], "antonyms": [], "tags": ["mindfulness", "habits"]},
    {"headword": "portion control strategy", "pronunciation": "/ˈpɔːʃn kənˈtrəʊl ˈstrætədʒi/", "partOfSpeech": "noun", "definition": "A deliberate technique—such as using smaller plates—to regulate the quantity of food consumed.", "example": "Using smaller salad bowls was a simple portion control strategy that prevented overeating at dinner.", "translation": "استراتيجية ضبط وتقنين حصص وكميات الطعام", "collocations": ["adopt a portion control strategy", "effective portion control strategy"], "synonyms": ["serving size management"], "antonyms": ["unrestricted binging"], "tags": ["nutrition", "diet"]},
    {"headword": "home workout circuit", "pronunciation": "/həʊm ˈwɜːkaʊt ˈsɜːkɪt/", "partOfSpeech": "noun", "definition": "A sequence of bodyweight exercises performed consecutively in one's living room without bulky equipment.", "example": "Her twenty-minute home workout circuit combines push-ups, squats, and lunges before work.", "translation": "دورة تمارين اللياقة المنزلية المتتابعة", "collocations": ["complete a home workout circuit", "do a home workout circuit"], "synonyms": ["bodyweight circuit"], "antonyms": ["gym routine"], "tags": ["fitness", "home"]},
    {"headword": "fresh fruit intake", "pronunciation": "/freʃ fruːt ˈɪnteɪk/", "partOfSpeech": "noun", "definition": "The daily consumption of raw apples, berries, citrus, or bananas providing vitamins and natural fiber.", "example": "Increasing his fresh fruit intake provided sustained afternoon energy without sugary confectionery crashes.", "translation": "تناول واستهلاك الفواكه الطازجة الغنية بالفيتامينات", "collocations": ["boost fresh fruit intake", "daily fresh fruit intake"], "synonyms": ["fruit consumption"], "antonyms": [], "tags": ["nutrition", "food"]},
    {"headword": "sedentary habit reduction", "pronunciation": "/ˈsedntri ˈhæbɪt rɪˈdʌkʃn/", "partOfSpeech": "noun", "definition": "Actively minimizing prolonged sitting by using standing desks, taking walking meetings, and pacing.", "example": "Using a standing desk was a vital step in his sedentary habit reduction plan.", "translation": "تقليل العادات الخاملة والحد من كثرة الجلوس", "collocations": ["focus on sedentary habit reduction", "sedentary habit reduction strategy"], "synonyms": ["sitting reduction"], "antonyms": ["sedentary lifestyle"], "tags": ["health", "ergonomics"]},
    {"headword": "evening herbal brew", "pronunciation": "/ˈiːvnɪŋ ˈhɜːbl bruː/", "partOfSpeech": "noun", "definition": "A warm infusion of chamomile, valerian root, or lavender prepared before bed to induce relaxation.", "example": "Sipping a hot evening herbal brew while reading a novel helped her wind down peacefully.", "translation": "مشروب الأعشاب المسائي الساخن والمهدئ", "collocations": ["sip an evening herbal brew", "prepare an evening herbal brew"], "synonyms": ["bedtime herbal infusion"], "antonyms": [], "tags": ["beverages", "sleep"]},
    {"headword": "ergonomic seating choice", "pronunciation": "/ˌɜːɡəˈnɒmɪk ˈsiːtɪŋ tʃɔɪs/", "partOfSpeech": "noun", "definition": "Selecting an orthopedic desk chair or kneeling stool designed to maintain proper spinal alignment.", "example": "Switching to an ergonomic seating choice with adjustable lumbar support relieved his sciatic nerve irritation.", "translation": "اختيار المقعد والكرسي المريح لصحة الظهر", "collocations": ["invest in an ergonomic seating choice", "sensible ergonomic seating choice"], "synonyms": ["orthopedic chair selection"], "antonyms": ["unsupportive chair"], "tags": ["ergonomics", "health"]},
    {"headword": "screen break habit", "pronunciation": "/skriːn breɪk ˈhæbɪt/", "partOfSpeech": "noun", "definition": "The regular practice of looking away from displays every twenty minutes to rest eye muscles.", "example": "Following the 20-20-20 rule established a healthy screen break habit that prevented optical fatigue.", "translation": "عادة أخذ استراحة دورية من النظر للشاشات", "collocations": ["build a screen break habit", "maintain a screen break habit"], "synonyms": ["visual rest habit"], "antonyms": ["continuous staring"], "tags": ["wellness", "eyes"]},
    {"headword": "positive lifestyle change", "pronunciation": "/ˈpɒzətɪv ˈlaɪfstaɪl tʃeɪndʒ/", "partOfSpeech": "noun", "definition": "A constructive modification in diet, sleep, or exercise habits that enhances longevity and vitality.", "example": "Quitting smoking and walking daily was the most significant positive lifestyle change he ever made.", "translation": "تغيير إيجابي وبنّاء في نمط وأسلوب الحياة", "collocations": ["make a positive lifestyle change", "commit to a positive lifestyle change"], "synonyms": ["healthy transformation"], "antonyms": ["destructive lifestyle choice"], "tags": ["transformation", "wellness"]},
    {"headword": "mindful breathing technique", "pronunciation": "/ˈmaɪndfl ˈbriːðɪŋ tekˈniːk/", "partOfSpeech": "noun", "definition": "A conscious breath control method that activates the parasympathetic nervous system to dissolve panic.", "example": "Employing the box breathing mindful breathing technique instantly calmed his racing pulse during the turbulence.", "translation": "تقنية التنفس الواعي والعميق لتهدئة الأعصاب", "collocations": ["apply a mindful breathing technique", "master a mindful breathing technique"], "synonyms": ["conscious respiration"], "antonyms": [], "tags": ["breath", "relaxation"]},
    {"headword": "whole grain diet", "pronunciation": "/həʊl ɡreɪn ˈdaɪət/", "partOfSpeech": "noun", "definition": "A nutritional regimen emphasizing unrefined grains such as oats, brown rice, barley, and quinoa.", "example": "Adopting a whole grain diet supplied sustained complex carbohydrates and improved gut digestion.", "translation": "نظام غذائي غني بالحبوب الكاملة غير المكررة", "collocations": ["transition to a whole grain diet", "benefits of a whole grain diet"], "synonyms": ["unrefined grain diet"], "antonyms": ["refined grain diet"], "tags": ["nutrition", "diet"]},
    {"headword": "immune system boost", "pronunciation": "/ɪˈmjuːn ˈsɪstəm buːst/", "partOfSpeech": "noun", "definition": "An enhancement in the body's natural defense mechanisms achieved through balanced nutrition, sleep, and exercise.", "example": "Consuming citrus, ginger, and garlic provides a natural immune system boost during winter flu season.", "translation": "تعزيز وتقوية كفاءة الجهاز المناعي", "collocations": ["provide an immune system boost", "give an immune system boost"], "synonyms": ["immune enhancement"], "antonyms": ["immune suppression"], "tags": ["immunity", "health"]},
    {"headword": "daily wellness routine", "pronunciation": "/ˈdeɪli ˈwelnəs ruːˈtiːn/", "partOfSpeech": "noun", "definition": "A consistent personal timetable of healthy habits integrating movement, nutrition, and mental peace.", "example": "Her balanced daily wellness routine includes herbal tea, a morning jog, and evening stretching.", "translation": "الروتين اليومي للعناية بالصحة والعافية الشاملة", "collocations": ["follow a daily wellness routine", "establish a daily wellness routine"], "synonyms": ["holistic health schedule"], "antonyms": [], "tags": ["wellness", "lifestyle"]},
    {"headword": "weekend hike tradition", "pronunciation": "/ˌwiːkˈend haɪk trəˈdɪʃn/", "partOfSpeech": "noun", "definition": "A cherished recurring custom of exploring nature trails and hills every Saturday or Sunday.", "example": "Our family weekend hike tradition keeps us connected to mountain forests and physically fit.", "translation": "تقليد المشي الجبلي الأسبوعي في أحضان الطبيعة", "collocations": ["enjoy a weekend hike tradition", "beloved weekend hike tradition"], "synonyms": ["weekly nature walk custom"], "antonyms": [], "tags": ["nature", "hiking"]},
    {"headword": "mental clarity exercise", "pronunciation": "/ˈmentl ˈklærəti ˈeksəsaɪz/", "partOfSpeech": "noun", "definition": "A brain-training or meditative practice aimed at clearing cognitive fog and sharpening focus.", "example": "Writing down five priorities in silence acts as an effective mental clarity exercise before busy meetings.", "translation": "تمرين صفاء الذهن وتنقيد التفكير", "collocations": ["practice a mental clarity exercise", "quick mental clarity exercise"], "synonyms": ["focus exercise"], "antonyms": [], "tags": ["mindfulness", "productivity"]},
    {"headword": "balanced lifestyle choice", "pronunciation": "/ˈbælənst ˈlaɪfstaɪl tʃɔɪs/", "partOfSpeech": "noun", "definition": "A conscious decision that harmonizes career ambitions with family, physical fitness, and mental rest.", "example": "Choosing to leave the office promptly at five was a conscious balanced lifestyle choice that improved his health.", "translation": "خيار نمط الحياة المتوازن والصحي", "collocations": ["make a balanced lifestyle choice", "promote balanced lifestyle choices"], "synonyms": ["harmonious life decision"], "antonyms": [], "tags": ["lifestyle", "wellness"]},
    {"headword": "sleep routine discipline", "pronunciation": "/sliːp ruːˈtiːn ˈdɪsəplɪn/", "partOfSpeech": "noun", "definition": "The steadfast habit of going to bed and waking up at consistent hours seven days a week.", "example": "Strict sleep routine discipline cured his circadian rhythm disruption after international travel.", "translation": "الانضباط في مواعيد النوم والاستيقاظ المنتظم", "collocations": ["maintain sleep routine discipline", "practice sleep routine discipline"], "synonyms": ["sleep schedule consistency"], "antonyms": ["erratic sleep hours"], "tags": ["sleep", "habits"]},
    {"headword": "caloric balance awareness", "pronunciation": "/kəˈlɒrɪk ˈbæləns əˈweənəs/", "partOfSpeech": "noun", "definition": "Conscious understanding of matching energy intake from food with energy expended through daily activity.", "example": "Developing caloric balance awareness enabled the athlete to maintain lean muscle mass effortlessly.", "translation": "الوعي بتوازن السعرات الحرارية الداخلة والمستهلكة", "collocations": ["develop caloric balance awareness", "practice caloric balance awareness"], "synonyms": ["energy balance consciousness"], "antonyms": [], "tags": ["nutrition", "fitness"]},
    {"headword": "morning sunlight exposure", "pronunciation": "/ˈmɔːnɪŋ ˈsʌnlaɪt ɪkˈspəʊʒə/", "partOfSpeech": "noun", "definition": "Getting natural outdoor sun in the eyes and on the skin early in the day to regulate circadian melatonin.", "example": "Neuroscientists recommend fifteen minutes of direct morning sunlight exposure immediately after waking.", "translation": "التعرض لأشعة شمس الصباح الباكر لضبط الساعة البيولوجية", "collocations": ["get morning sunlight exposure", "benefits of morning sunlight exposure"], "synonyms": ["dawn sun exposure"], "antonyms": ["dim room confinement"], "tags": ["health", "morning"]},
    {"headword": "stretching exercise break", "pronunciation": "/ˈstretʃɪŋ ˈeksəsaɪz breɪk/", "partOfSpeech": "noun", "definition": "A brief pause during sedentary desk work to stretch hamstring, hip flexor, and shoulder muscles.", "example": "Taking a two-minute stretching exercise break every hour eliminated her tension headaches.", "translation": "استراحة قصيرة لتمارين الإطالة وتمديد العضلات", "collocations": ["take a stretching exercise break", "hourly stretching exercise break"], "synonyms": ["mobility intermission"], "antonyms": [], "tags": ["fitness", "ergonomics"]},
    {"headword": "healthy habit streak", "pronunciation": "/ˈhelθi ˈhæbɪt striːk/", "partOfSpeech": "noun", "definition": "An unbroken sequence of consecutive days completing a beneficial wellness or exercise routine.", "example": "Celebrating a sixty-day healthy habit streak of drinking two liters of water kept her motivated.", "translation": "سلسلة الأيام المتواصلة في ممارسة عادة صحية", "collocations": ["maintain a healthy habit streak", "build a healthy habit streak"], "synonyms": ["habit consistency run"], "antonyms": ["broken streak"], "tags": ["habits", "motivation"]},
    {"headword": "refined sugar avoidance", "pronunciation": "/rɪˈfaɪnd ˈʃʊɡər əˈvɔɪdəns/", "partOfSpeech": "noun", "definition": "The conscious elimination of processed cane sugar, corn syrup, and sweetened confectionery from one's diet.", "example": "Her strict refined sugar avoidance stabilized her blood glucose and eliminated late-afternoon mood swings.", "translation": "تجنب وتفادي السكريات المكررة والمصنعة", "collocations": ["practice refined sugar avoidance", "commit to refined sugar avoidance"], "synonyms": ["no-sugar commitment"], "antonyms": ["sugar consumption"], "tags": ["nutrition", "diet"]},
    {"headword": "physical wellness check", "pronunciation": "/ˈfɪzɪkl ˈwelnəs tʃek/", "partOfSpeech": "noun", "definition": "A comprehensive physical examination assessing blood pressure, mobility, body mass, and cardiovascular fitness.", "example": "Her annual physical wellness check confirmed that her cardiovascular biomarkers were outstanding.", "translation": "الفحص والتقييم الشامل للصحة والعافية البدنية", "collocations": ["undergo a physical wellness check", "routine physical wellness check"], "synonyms": ["physical health evaluation"], "antonyms": [], "tags": ["medicine", "health"]},
    {"headword": "body flexibility routine", "pronunciation": "/ˈbɒdi ˌfleksəˈbɪləti ruːˈtiːn/", "partOfSpeech": "noun", "definition": "A structured series of dynamic and static stretching drills designed to increase joint range of motion.", "example": "Practicing an evening body flexibility routine prevents joint stiffness and improves athletic agility.", "translation": "روتين تمارين مرونة وليونة الجسم والمفاصل", "collocations": ["follow a body flexibility routine", "daily body flexibility routine"], "synonyms": ["mobility regimen"], "antonyms": ["joint stiffness"], "tags": ["fitness", "mobility"]},
    {"headword": "mindful walking stroll", "pronunciation": "/ˈmaɪndfl ˈwɔːkɪŋ strəʊl/", "partOfSpeech": "noun", "definition": "A calm, meditative walk where one focuses sensory attention completely on footsteps, breath, and natural sounds.", "example": "A ten-minute mindful walking stroll through the autumn leaves relieved his afternoon cognitive fatigue.", "translation": "نزهة ومشي واعي يركز على الحواس والحضور الذهني", "collocations": ["take a mindful walking stroll", "enjoy a mindful walking stroll"], "synonyms": ["meditative walk"], "antonyms": ["rushed walk"], "tags": ["mindfulness", "walking"]},
    {"headword": "healthy cooking choice", "pronunciation": "/ˈhelθi ˈkʊkɪŋ tʃɔɪs/", "partOfSpeech": "noun", "definition": "Opting for steaming, baking, or grilling methods using fresh herbs instead of deep frying in saturated fats.", "example": "Steaming broccoli with lemon and garlic was a delicious, healthy cooking choice for dinner.", "translation": "اختيار أساليب الطهي الصحية والمغذية", "collocations": ["make a healthy cooking choice", "favor healthy cooking choices"], "synonyms": ["nutritious culinary method"], "antonyms": ["deep frying"], "tags": ["food", "cooking"]},
    {"headword": "deep relaxation technique", "pronunciation": "/diːp ˌriːlækˈseɪʃn tekˈniːk/", "partOfSpeech": "noun", "definition": "A proven clinical method—such as progressive muscle relaxation or autogenic training—to induce profound somatic calm.", "example": "Learning a deep relaxation technique helped the insomnia patient fall asleep without pharmaceutical sedatives.", "translation": "تقنية الاسترخاء العضلي والنفسي العميق", "collocations": ["master a deep relaxation technique", "practice a deep relaxation technique"], "synonyms": ["somatic relaxation method"], "antonyms": [], "tags": ["relaxation", "health"]},
    {"headword": "daily health commitment", "pronunciation": "/ˈdeɪli helθ kəˈmɪtmənt/", "partOfSpeech": "noun", "definition": "A non-negotiable personal pledge to prioritize physical movement, balanced nutrition, and restorative rest every day.", "example": "Drinking two liters of water and walking outside was her foundational daily health commitment.", "translation": "الالتزام والعهد اليومي برعاية الصحة البدنية", "collocations": ["honor a daily health commitment", "renew your daily health commitment"], "synonyms": ["daily wellness pledge"], "antonyms": ["health neglect"], "tags": ["health", "habits"]},
    {"headword": "vitality restoration", "pronunciation": "/vaɪˈtæləti ˌrestəˈreɪʃn/", "partOfSpeech": "noun", "definition": "The renewal of physical vigor, mental energy, and enthusiastic life force following fatigue or illness.", "example": "A week of clean eating, mountain air, and restorative sleep led to complete vitality restoration.", "translation": "استعادة وتجديد الحيوية والنشاط والطاقة", "collocations": ["achieve vitality restoration", "pathway to vitality restoration"], "synonyms": ["energy rejuvenation"], "antonyms": ["exhaustion"], "tags": ["vitality", "wellness"]}
]

grammar_86 = [
    {
        "title": "Modals + Conditionals Review",
        "explanation": "Discussing health decisions, preventative lifestyle habits, and medical outcomes requires combining modal verbs (should, must, can, could, might, ought to) with conditional sentences:\n\n1. Zero & First Conditional with Modals for Health Principles:\n   - 'If you maintain a mindful eating habit, your digestion will improve dramatically.'\n   - 'If you experience severe fatigue, you should schedule a preventative check-up.'\n   - 'If you drink enough water, your hydration routine can boost mental focus.'\n\n2. Second Conditional with Modals for Hypothetical Lifestyle Upgrades:\n   - 'If more office workers embraced an outdoor cardio workout, public health costs would decrease.'\n   - 'If you reduced your screen time at night, you might enjoy a restorative sleep cycle.'\n\n3. Third & Mixed Conditionals for Retrospective Health Insights:\n   - 'If he had followed his strength training routine consistently, he wouldn't suffer from back stiffness today.'\n   - 'If she had committed to sugar intake reduction earlier, she could have prevented metabolic complications.'",
        "structures": [
            {"pattern": "First Conditional with modal advice: If + Present Simple, Subject + should / ought to + Base Form: 'If you feel overwhelmed, you should take a mental health day.'"},
            {"pattern": "Second Conditional hypothetical: If + Past Simple, Subject + could / might + Base Form: 'If they adopted a whole grain diet, their energy levels would stabilize.'"},
            {"pattern": "Mixed Conditional (Past habit -> Present vitality): 'If I had not established a daily meditation practice, I would be far more anxious today.'"}
        ],
        "examples": [
            {
                "sentence": "If you adopt a clean eating philosophy, your body can achieve genuine vitality restoration.",
                "arabic": "إذا تبنيت فلسفة الغذاء النظيف، يمكن لجسدك أن يحقق استعادة حقيقية للحيوية والنشاط.",
                "usesVocabulary": ["clean eating philosophy", "vitality restoration"]
            },
            {
                "sentence": "If you maintain your daily step target, you will notice an immediate immune system boost.",
                "arabic": "إذا حافظت على هدف خطواتك اليومية، فستلاحظ تعزيزاً فورياً لكفاءة جهازك المناعي.",
                "usesVocabulary": ["daily step target", "immune system boost"]
            },
            {
                "sentence": "If she had committed to refined sugar avoidance earlier, she wouldn't suffer from afternoon energy crashes today.",
                "arabic": "لو كانت قد التزمت بتجنب السكريات المكررة مبكراً، لما كانت تعاني من هبوط الطاقة بعد الظهيرة اليوم.",
                "usesVocabulary": ["refined sugar avoidance"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "If you will drink herbal tea, you should sleep better.",
                "right": "If you drink herbal tea, you will sleep better. / If you drink herbal tea, you should sleep better.",
                "explanation": "Do not put 'will' into the conditional 'if' clause. Use the Present Simple ('If you drink')."
            },
            {
                "wrong": "If he practiced daily meditation, he will feel less stressed.",
                "right": "If he practiced daily meditation, he would feel less stressed.",
                "explanation": "Match the past simple condition ('practiced') with 'would' or 'could' in the second conditional, not 'will'."
            }
        ]
    }
]

convs_86 = [
    {
        "title": "Wellness Consultation: Overcoming Burnout",
        "titleArabic": "استشارة صحية: التغلب على الإرهاق والاحتراق النفسي",
        "setting": "A preventative health physician reviews lifestyle habits with a stressed corporate executive.",
        "lines": [
            {"speaker": "Doctor", "text": "Having reviewed your preventative check-up, your cortisol markers indicate chronic fatigue. How is your sleep?"},
            {"speaker": "Executive", "text": "Fragmented. My sleep quality tracker shows I rarely achieve a restorative sleep cycle."},
            {"speaker": "Doctor", "text": "If you want to restore deep sleep, you must practice strict sleep routine discipline and avoid screens late at night."},
            {"speaker": "Executive", "text": "I started an evening herbal brew and ten minutes of bedtime guided breathing exercises."},
            {"speaker": "Doctor", "text": "Splendid! Combine that with morning sunlight exposure and a twenty-minute walking lunch break."},
            {"speaker": "Executive", "text": "I also took a mental health day last Friday to initiate my positive lifestyle change."},
            {"speaker": "Doctor", "text": "That was a wise, balanced lifestyle choice. Small daily health commitments yield profound long-term vitality."},
            {"speaker": "Executive", "text": "I feel determined to maintain this healthy habit streak for the rest of the year."}
        ],
        "vocabularyUsed": ["preventative check-up", "sleep quality tracker", "restorative sleep cycle", "sleep routine discipline", "evening herbal brew", "guided breathing exercise", "morning sunlight exposure", "walking lunch break", "mental health day", "positive lifestyle change", "balanced lifestyle choice", "daily health commitment", "healthy habit streak"]
    },
    {
        "title": "Nutrition and Fitness Coaching: Building Vitality",
        "titleArabic": "تدريب التغذية واللياقة: بناء الحيوية والنشاط",
        "setting": "A personal trainer and client review workout benchmarks and meal habits.",
        "lines": [
            {"speaker": "Trainer", "text": "You reached your daily step target five days this week! How does your strength training routine feel?"},
            {"speaker": "Client", "text": "Energizing! But my lower back tightens up after hours of desk work."},
            {"speaker": "Trainer", "text": "You should adopt a posture correction habit and take an hourly stretching exercise break."},
            {"speaker": "Client", "text": "I also invested in an ergonomic seating choice and started an outdoor cardio workout on Saturdays."},
            {"speaker": "Trainer", "text": "What about nutrition? Have you committed to sugar intake reduction and refined sugar avoidance?"},
            {"speaker": "Client", "text": "Yes, I made a healthy snack swap to walnuts and boosted my fresh fruit intake."},
            {"speaker": "Trainer", "text": "Building a balanced meal plate around a whole grain diet will optimize your caloric balance awareness."},
            {"speaker": "Client", "text": "Coupled with our weekend hike tradition, I feel my physical wellness check will show great progress."}
        ],
        "vocabularyUsed": ["daily step target", "strength training routine", "posture correction habit", "stretching exercise break", "ergonomic seating choice", "outdoor cardio workout", "sugar intake reduction", "refined sugar avoidance", "healthy snack swap", "fresh fruit intake", "balanced meal plate", "whole grain diet", "caloric balance awareness", "weekend hike tradition", "physical wellness check"]
    },
    {
        "title": "Mind-Body Seminar: Mindfulness and Stress Reduction",
        "titleArabic": "ندوة العقل والجسد: التأمل الواعي وخفض التوتر",
        "setting": "A meditation instructor leads a community workshop on holistic health.",
        "lines": [
            {"speaker": "Instructor", "text": "Welcome. If we master a mindful breathing technique, our parasympathetic nervous system can dissolve somatic tension."},
            {"speaker": "Participant", "text": "I struggle with racing thoughts during our morning mindfulness meditation session."},
            {"speaker": "Instructor", "text": "That is entirely natural. Try taking a mindful walking stroll outdoors or doing a gentle morning stretching routine."},
            {"speaker": "Participant", "text": "My doctor recommended a daily meditation practice as a primary stress relief practice."},
            {"speaker": "Instructor", "text": "Practicing deep relaxation techniques and body flexibility routines promotes lasting vitality restoration."},
            {"speaker": "Participant", "text": "I also follow a strict hydration routine and practice a mindful eating habit at meal times."},
            {"speaker": "Instructor", "text": "Combining conscious nutrition with mental stillness gives your immune system an extraordinary boost."},
            {"speaker": "Participant", "text": "Making these conscious choices has completely transformed my daily sense of calm."}
        ],
        "vocabularyUsed": ["mindful breathing technique", "mindfulness meditation session", "mindful walking stroll", "morning stretching routine", "daily meditation practice", "stress relief practice", "deep relaxation technique", "body flexibility routine", "vitality restoration", "hydration routine", "mindful eating habit", "immune system boost"]
    }
]

paras_86 = [
    {
        "title": "Holistic Nutrition, Mindful Eating, and Metabolic Health",
        "titleArabic": "التغذية الشاملة، الأكل الواعي، والصحة الأيضية",
        "text": "True physiological health begins in the kitchen through conscious, nourishing dietary choices. Cultivating an authentic mindful eating habit encourages individuals to savor each mouthful while honoring satiety signals. By building every meal around a balanced meal plate and embracing a whole grain diet rich in vibrant vegetables, cells receive optimal micronutrients. Choosing smart healthy snack swaps and prioritizing refined sugar avoidance eliminates energy crashes and promotes long-term metabolic health. Concurrently, pairing clean eating philosophies with consistent hydration routines and fresh fruit intake provides an indispensable immune system boost that protects the body against illness.",
        "vocabularyUsed": ["mindful eating habit", "balanced meal plate", "whole grain diet", "healthy snack swap", "refined sugar avoidance", "clean eating philosophy", "hydration routine", "fresh fruit intake", "immune system boost"]
    },
    {
        "title": "Restorative Sleep, Circadian Rhythms, and Daily Balance",
        "titleArabic": "النوم المجدد، الساعات البيولوجية، والتوازن اليومي",
        "text": "Sleep is the non-negotiable biological foundation upon which mental clarity and physical vitality depend. Adhering to strict sleep routine discipline enables the brain to enter deep restorative sleep cycles night after night. Monitoring rest through a sleep quality tracker highlights how late-night screen exposure damages cellular recovery. To wind down peacefully, sipping an evening herbal brew while practicing a guided breathing exercise calms the autonomic nervous system. Furthermore, stepping outside for early morning sunlight exposure resets circadian melatonin production. When modern professionals respect natural rhythms, waking hours are imbued with enduring energy and cognitive focus.",
        "vocabularyUsed": ["sleep routine discipline", "restorative sleep cycle", "sleep quality tracker", "evening herbal brew", "guided breathing exercise", "morning sunlight exposure"]
    },
    {
        "title": "Active Movement, Mental Peace, and Preventative Longevity",
        "titleArabic": "الحركة النشطة، السكينة النفسية، والوقاية من أجل طول العمر",
        "text": "Sustaining lifelong physical vitality requires integrating movement and mindfulness into daily life. Hitting an intentional daily step target through brisk walking lunch breaks and outdoor cardio workouts keeps the cardiovascular system resilient. At the office, building posture correction habits and taking regular stretching exercise breaks counteracts the hazards of prolonged sedentary sitting. To safeguard psychological tranquility, establishing a daily meditation practice serves as an essential stress relief practice. By honoring annual preventative check-ups and maintaining healthy habit streaks, individuals make balanced lifestyle choices that ensure genuine vitality restoration.",
        "vocabularyUsed": ["daily step target", "walking lunch break", "outdoor cardio workout", "posture correction habit", "stretching exercise break", "daily meditation practice", "stress relief practice", "preventative check-up", "healthy habit streak", "balanced lifestyle choice", "vitality restoration"]
    }
]

if __name__ == "__main__":
    write_day(85, vocab_85, grammar_85, convs_85, paras_85)
    write_day(86, vocab_86, grammar_86, convs_86, paras_86)
    print("Day 85 and Day 86 generated successfully.")
