# -*- coding: utf-8 -*-
"""Generate Day 79 and Day 80 for Stage 8."""

import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from curriculum_engine import write_day

# ==============================================================================
# DAY 79: Natural Spoken English (Real conversation patterns)
# Grammar: Spoken Grammar: Ellipsis, Response Words, Informal Structures
# ==============================================================================

vocab_79 = [
    # Discourse Dynamics, Pragmatics & Conversation Mechanics
    {"headword": "ellipsis", "pronunciation": "/ɪˈlɪpsɪs/", "partOfSpeech": "noun", "definition": "The omission of words from a clause that are understood from contextual clues or prior statements.", "example": "In conversational ellipsis, speakers drop the subject pronoun, saying 'Sounds good' instead of 'That sounds good.'", "translation": "الحذف البلاغي والتركيبي للكلمات المفهومة من السياق", "collocations": ["situational ellipsis", "conversational ellipsis"], "synonyms": ["omission"], "antonyms": ["explicit phrasing"], "tags": ["linguistics", "grammar"]},
    {"headword": "tag question", "pronunciation": "/tæɡ ˈkwestʃən/", "partOfSpeech": "noun", "definition": "A mini-question added to the end of a statement to invite confirmation, agreement, or checking.", "example": "Adding the tag question 'It is quite chilly, isn't it?' encourages conversational warmth.", "translation": "السؤال المذيل التوكيدي في نهاية الجملة", "collocations": ["use a tag question", "intonation in tag questions"], "synonyms": ["question tag"], "antonyms": [], "tags": ["grammar", "conversation"]},
    {"headword": "discourse particle", "pronunciation": "/ˈdɪskɔːs ˈpɑːtɪkl/", "partOfSpeech": "noun", "definition": "A word or expression that structures spoken interaction without altering core propositional truth.", "example": "Words like 'well', 'now', and 'you know' function as discourse particles guiding listener attention.", "translation": "أداة تنظيم الخطاب الشفاهي (مثل حسناً، أتعلم)", "collocations": ["function of a discourse particle", "spoken discourse particles"], "synonyms": ["pragmatic marker"], "antonyms": [], "tags": ["linguistics", "pragmatics"]},
    {"headword": "filler word", "pronunciation": "/ˈfɪlə wɜːd/", "partOfSpeech": "noun", "definition": "A meaningless sound or word used by speakers to pause or signal thinking time without relinquishing the floor.", "example": "Relying on the filler word 'um' or 'like' gives the brain split seconds to formulate complex thoughts.", "translation": "كلمة حشو للتفكير وكسب الوقت في الحديث الشفاهي", "collocations": ["avoid filler words", "use filler words"], "synonyms": ["hesitation marker"], "antonyms": ["precise terminology"], "tags": ["speech", "conversation"]},
    {"headword": "hedging expression", "pronunciation": "/ˈhedʒɪŋ ɪkˈspreʃn/", "partOfSpeech": "noun", "definition": "A spoken phrase softening the directness or certainty of a statement to avoid dogmatism.", "example": "Using a hedging expression like 'sort of' or 'more or less' prevents sounding confrontational.", "translation": "عبارة تحوط وتلطيف لتقليل القطعية والحدة", "collocations": ["soften with a hedging expression", "common hedging expressions"], "synonyms": ["qualifying phrase"], "antonyms": ["absolute statement"], "tags": ["pragmatics", "politeness"]},
    {"headword": "vague language", "pronunciation": "/veɪɡ ˈlæŋɡwɪdʒ/", "partOfSpeech": "noun", "definition": "Words that deliberately lack exact precision, used to signal informality, familiarity, and shared understanding.", "example": "Phrases like 'and that sort of thing' or 'stuff like that' are classic examples of vague language.", "translation": "اللغة التقريبية الفضفاضة في المحادثات العفوية", "collocations": ["rely on vague language", "use vague language"], "synonyms": ["imprecise language"], "antonyms": ["exact language"], "tags": ["conversation", "sociolinguistics"]},
    {"headword": "approximator", "pronunciation": "/əˈprɒksɪmeɪtə/", "partOfSpeech": "noun", "definition": "A word indicating that an amount, time, or quantity is approximate rather than scientifically exact.", "example": "In colloquial speech, 'roughly', 'about', and 'around' act as useful approximators.", "translation": "مؤشر التقريب (تقريباً، زهاء، نحو)", "collocations": ["serve as an approximator", "use an approximator"], "synonyms": ["rough indicator"], "antonyms": ["exact number"], "tags": ["linguistics", "speech"]},
    {"headword": "softening device", "pronunciation": "/ˈsɒfnɪŋ dɪˈvaɪs/", "partOfSpeech": "noun", "definition": "A polite grammatical or lexical technique used to make requests or criticisms less blunt.", "example": "Adding 'I was wondering if' operates as an effective softening device when asking for favors.", "translation": "أداة تلطيف وتخفيف حدة الطلب أو النقد", "collocations": ["employ a softening device", "act as a softening device"], "synonyms": ["mitigator", "politeness marker"], "antonyms": ["blunt demand"], "tags": ["politeness", "pragmatics"]},
    {"headword": "face-saving strategy", "pronunciation": "/feɪs ˈseɪvɪŋ ˈstrætədʒi/", "partOfSpeech": "noun", "definition": "A communicative technique designed to protect a speaker's or listener's dignity and social standing.", "example": "Indirectly blaming the printer was a diplomatic face-saving strategy that protected the intern.", "translation": "استراتيجية حفظ ماء الوجه والكرامة الاجتماعية", "collocations": ["adopt a face-saving strategy", "use a face-saving strategy"], "synonyms": ["politeness strategy"], "antonyms": ["face-threatening act"], "tags": ["pragmatics", "sociology"]},
    {"headword": "indirect speech act", "pronunciation": "/ˌɪndaɪˈrekt ˈspiːtʃ ækt/", "partOfSpeech": "noun", "definition": "An utterance whose underlying pragmatic intent differs from its surface grammatical form.", "example": "Saying 'Can you pass the salt?' is an indirect speech act: a request phrased grammatically as a question.", "translation": "الفعل الكلامي غير المباشر (مثل صياغة الطلب في صورة سؤال)", "collocations": ["perform an indirect speech act", "interpret an indirect speech act"], "synonyms": ["implicit request"], "antonyms": ["direct command"], "tags": ["pragmatics", "linguistics"]},
    {"headword": "implicature", "pronunciation": "/ˌɪmplɪˈkeɪtʃə/", "partOfSpeech": "noun", "definition": "What is suggested or understood in an utterance, even though neither expressed nor strictly entailed.", "example": "Saying 'The room is rather warm' carries the conversational implicature that someone should open a window.", "translation": "المعنى المستلزم تخاطبياً والمفهوم ضمناً", "collocations": ["conversational implicature", "derive an implicature"], "synonyms": ["implied meaning", "subtext"], "antonyms": ["literal meaning"], "tags": ["pragmatics", "philosophy"]},
    {"headword": "conversational maxim", "pronunciation": "/ˌkɒnvəˈseɪʃənl ˈmæksɪm/", "partOfSpeech": "noun", "definition": "A foundational cooperative principle of communication formulated by philosopher Paul Grice.", "example": "Violating the conversational maxim of quantity occurs when someone provides far too much irrelevant detail.", "translation": "المبدأ الحواري التخاطبي لقواعد غرايس للتواصل", "collocations": ["flout a conversational maxim", "Grice's conversational maxims"], "synonyms": ["cooperative principle"], "antonyms": [], "tags": ["pragmatics", "philosophy"]},
    {"headword": "turn-taking signal", "pronunciation": "/ˈtɜːn ˌteɪkɪŋ ˈsɪɡnl/", "partOfSpeech": "noun", "definition": "A vocal inflection, gesture, or pause indicating that a speaker is ready to yield the conversation floor.", "example": "Falling vocal pitch and prolonged eye contact serve as an intuitive turn-taking signal in conversation.", "translation": "إشارة تبادل وتناوب الأدوار في الحديث الشفاهي", "collocations": ["give a turn-taking signal", "recognize turn-taking signals"], "synonyms": ["floor-yielding cue"], "antonyms": [], "tags": ["conversation", "interaction"]},
    {"headword": "back-channeling", "pronunciation": "/ˈbæk ˌtʃænəlɪŋ/", "partOfSpeech": "noun", "definition": "Listener feedback sounds and words that show attentiveness without attempting to seize the speaking turn.", "example": "Nodding while murmuring 'uh-huh' and 'right' is natural back-channeling that shows active listening.", "translation": "التغذية الراجعة التفاعلية للتأكيد على المتابعة والإنصات", "collocations": ["practice back-channeling", "forms of back-channeling"], "synonyms": ["listener feedback", "minimal feedback"], "antonyms": ["interruption"], "tags": ["conversation", "linguistics"]},
    {"headword": "repair strategy", "pronunciation": "/rɪˈpeə ˈstrætədʒi/", "partOfSpeech": "noun", "definition": "A communicative technique used to correct a slip, misunderstanding, or speech error in real-time talk.", "example": "Saying 'I mean' to rephrase an ambiguous phrase is an essential conversational repair strategy.", "translation": "استراتيجية تصحيح وتدارك العثرات الكلامية", "collocations": ["initiate a repair strategy", "effective repair strategy"], "synonyms": ["conversational repair"], "antonyms": [], "tags": ["conversation", "linguistics"]},

    # Spoken Fluency, Speech Repair & Flow Markers
    {"headword": "reformulation", "pronunciation": "/ˌriːfɔːmjuˈleɪʃn/", "partOfSpeech": "noun", "definition": "Expressing something in a different way in conversation to clarify meaning or improve precision.", "example": "Her sudden reformulation from 'He was angry' to 'He felt betrayed' captured the nuance accurately.", "translation": "إعادة الصياغة الكلامية لتوضيح المعنى", "collocations": ["conversational reformulation", "prompt a reformulation"], "synonyms": ["rephrasing", "recasting"], "antonyms": [], "tags": ["speech", "clarity"]},
    {"headword": "self-correction", "pronunciation": "/self kəˈrekʃn/", "partOfSpeech": "noun", "definition": "An immediate verbal fix made by a speaker right after committing a grammatical or factual slip.", "example": "Spontaneous self-correction is a sign of high language proficiency and communicative monitoring.", "translation": "التصحيح الذاتي التلقائي للأخطاء أثناء الكلام", "collocations": ["spontaneous self-correction", "engage in self-correction"], "synonyms": ["self-repair"], "antonyms": ["unnoticed error"], "tags": ["fluency", "speech"]},
    {"headword": "false start", "pronunciation": "/fɔːls stɑːt/", "partOfSpeech": "noun", "definition": "Beginning an utterance and then immediately abandoning it to rephrase the thought differently.", "example": "In spontaneous speech, false starts like 'I was going—well, actually we decided to stay' are normal.", "translation": "البداية الزائفة والتعثر العفوي قبل تصحيح الجملة", "collocations": ["contain a false start", "make a false start"], "synonyms": ["restart", "abandoned utterance"], "antonyms": ["fluent delivery"], "tags": ["speech", "fluency"]},
    {"headword": "filled pause", "pronunciation": "/fɪld pɔːz/", "partOfSpeech": "noun", "definition": "A vocal hesitation sound like 'er', 'erm', or 'uh' produced while formulating the next sentence segment.", "example": "Public speaking coaches train executives to replace filled pauses with quiet, deliberate breathing.", "translation": "الوقفة الصوتية الممتلئة بأصوات التردد (مثل آاه، إمم)", "collocations": ["eliminate filled pauses", "rely on filled pauses"], "synonyms": ["voiced hesitation"], "antonyms": ["unfilled pause", "silent pause"], "tags": ["speech", "rhetoric"]},
    {"headword": "unfilled pause", "pronunciation": "/ʌnˈfɪld pɔːz/", "partOfSpeech": "noun", "definition": "A brief period of complete silence in spoken conversation used for breath, emphasis, or cognitive retrieval.", "example": "A dramatic unfilled pause before announcing the winner heightened audience anticipation.", "translation": "الوقفة الصامتة التامة للتأمل أو التشويق", "collocations": ["a deliberate unfilled pause", "use of unfilled pauses"], "synonyms": ["silent pause"], "antonyms": ["filled pause"], "tags": ["speech", "delivery"]},
    {"headword": "topic shift", "pronunciation": "/ˈtɒpɪk ʃɪft/", "partOfSpeech": "noun", "definition": "A deliberate transition in conversation from one subject of discussion to a completely different one.", "example": "The diplomat smoothly executed a topic shift away from defense spending toward cultural trade.", "translation": "التحول والانتقال لموضوع حديث جديد", "collocations": ["execute a topic shift", "subtle topic shift"], "synonyms": ["subject change"], "antonyms": ["topic continuation"], "tags": ["conversation", "discourse"]},
    {"headword": "topic change marker", "pronunciation": "/ˈtɒpɪk tʃeɪndʒ ˈmɑːkə/", "partOfSpeech": "noun", "definition": "A discourse phrase such as 'by the way' or 'incidentally' explicitly announcing a thematic pivot.", "example": "Using 'Speaking of which' serves as an organic topic change marker connecting related thoughts.", "translation": "مؤشر الانتقال الموضعي (بالمناسبة، على ذكر ذلك)", "collocations": ["use a topic change marker", "common topic change markers"], "synonyms": ["conversational transition marker"], "antonyms": [], "tags": ["conversation", "pragmatics"]},
    {"headword": "phatic communion", "pronunciation": "/ˈfætɪk kəˈmjuːnjən/", "partOfSpeech": "noun", "definition": "Communication used for establishing a social atmosphere or bonding rather than conveying factual data.", "example": "Saying 'Lovely weather today, isn't it?' is classic phatic communion designed to build rapport.", "translation": "التواصل الأنسي والمجاملات الاجتماعية لبناء الألفة", "collocations": ["engage in phatic communion", "function of phatic communion"], "synonyms": ["social grooming talk", "rapport building"], "antonyms": ["transactional talk"], "tags": ["sociolinguistics", "anthropology"]},
    {"headword": "small talk formula", "pronunciation": "/smɔːl tɔːk ˈfɔːmjələ/", "partOfSpeech": "noun", "definition": "A predictable conventional phrase used to open or maintain polite casual conversation.", "example": "In networking receptions, 'What brings you to the conference?' is an essential small talk formula.", "translation": "صيغة وقالب الحديث العفوي الودي", "collocations": ["master small talk formulas", "use a small talk formula"], "synonyms": ["icebreaker formula"], "antonyms": [], "tags": ["conversation", "social"]},
    {"headword": "formulaic expression", "pronunciation": "/ˌfɔːmjuˈleɪɪk ɪkˈspreʃn/", "partOfSpeech": "noun", "definition": "A fixed sequence of words retrieved from memory as a single prefabricated linguistic chunk.", "example": "Phrases like 'Take care' and 'Safe travels' are formulaic expressions processed automatically in social life.", "translation": "تعبير اصطلاحي نمطي مسبق التجهيز ومحفوظ كقالب", "collocations": ["rely on formulaic expressions", "acquire formulaic expressions"], "synonyms": ["prefabricated chunk"], "antonyms": ["spontaneous construction"], "tags": ["linguistics", "vocabulary"]},
    {"headword": "idiom in context", "pronunciation": "/ˈɪdiəm ɪn ˈkɒntekst/", "partOfSpeech": "noun", "definition": "An idiomatic phrase understood and used appropriately within its natural cultural and pragmatic setting.", "example": "Learning an idiom in context ensures you know when it is witty rather than bizarre or offensive.", "translation": "التعبير الاصطلاحي في سياقه الطبيعي الملائم", "collocations": ["learn an idiom in context", "interpret an idiom in context"], "synonyms": ["contextual idiom"], "antonyms": ["isolated idiom"], "tags": ["idioms", "learning"]},
    {"headword": "colloquial register", "pronunciation": "/kəˈləʊkwiəl ˈredʒɪstə/", "partOfSpeech": "noun", "definition": "The informal variety of language used in relaxed everyday conversation with family and peers.", "example": "Switching to a colloquial register helped the politician connect with factory workers on the shop floor.", "translation": "السجل اللغوي العامي واليومي غير الرسمي", "collocations": ["switch to a colloquial register", "speak in a colloquial register"], "synonyms": ["informal register", "vernacular"], "antonyms": ["formal register"], "tags": ["sociolinguistics", "style"]},
    {"headword": "informal contraction", "pronunciation": "/ɪnˈfɔːml kənˈtrækʃn/", "partOfSpeech": "noun", "definition": "A shortened form of words common in fast speech, such as 'gonna', 'wanna', or 'dunno'.", "example": "While appropriate in casual chat, an informal contraction should never appear in formal academic essays.", "translation": "الدمج والاختصار غير الرسمي في الكلام السريع (مثل wanna)", "collocations": ["use an informal contraction", "avoid informal contractions"], "synonyms": ["speech reduction"], "antonyms": ["uncontracted form"], "tags": ["phonetics", "slang"]},
    {"headword": "elided form", "pronunciation": "/ɪˈlaɪdɪd fɔːm/", "partOfSpeech": "noun", "definition": "A word or phrase produced with omission of unstressed sounds or syllables in rapid spoken delivery.", "example": "Pronouncing 'camera' as two syllables instead of three demonstrates an elided form.", "translation": "الصيغة المحذوفة والمخففة صوتياً في النطق السريع", "collocations": ["produce an elided form", "common elided forms"], "synonyms": ["reduced form"], "antonyms": ["full citation form"], "tags": ["phonetics", "speech"]},
    {"headword": "reduced clause", "pronunciation": "/rɪˈdjuːst klɔːz/", "partOfSpeech": "noun", "definition": "A subordinate clause shortened by omitting the relative pronoun and auxiliary verb.", "example": "Changing 'the people who are waiting outside' to 'the people waiting outside' creates a reduced clause.", "translation": "الجملة التابعة المخففة والمختصرة نحوياً", "collocations": ["form a reduced clause", "use of reduced clauses"], "synonyms": ["elliptical clause"], "antonyms": ["full relative clause"], "tags": ["grammar", "syntax"]},

    # Expressive Structures, Syntax & Interactional Routines
    {"headword": "fronting structure", "pronunciation": "/ˈfrʌntɪŋ ˈstrʌktʃə/", "partOfSpeech": "noun", "definition": "Moving an element from its normal position to the very front of the sentence to give it prominence.", "example": "In the fronting structure 'Shocked, they stared at the wreckage', the emotion is highlighted first.", "translation": "بنية التقديم والتأخير اللفظي لإبراز عنصر في الجملة", "collocations": ["employ a fronting structure", "fronting structure for emphasis"], "synonyms": ["topicalization"], "antonyms": ["standard canonical syntax"], "tags": ["syntax", "style"]},
    {"headword": "cleft sentence", "pronunciation": "/kleft ˈsentəns/", "partOfSpeech": "noun", "definition": "A complex sentence dividing a single clause into two parts to highlight a specific piece of information.", "example": "The cleft sentence 'It was Susan who discovered the error' emphasizes Susan as the key agent.", "translation": "الجملة المشطورة التوكيدية للتركيز على معلومة محددة", "collocations": ["use a cleft sentence", "wh-cleft sentence"], "synonyms": ["split sentence", "focus construction"], "antonyms": ["simple sentence"], "tags": ["grammar", "emphasis"]},
    {"headword": "existential there", "pronunciation": "/ˌeɡzɪˈstenʃl ðeə/", "partOfSpeech": "noun", "definition": "The introductory unstressed 'there' used with the verb 'to be' to state that something exists.", "example": "In spoken English, 'There is a bakery on the corner' uses existential there to introduce new topics.", "translation": "تعبير الوجودية الإخباري (هناك / يوجد)", "collocations": ["use of existential there", "existential there construction"], "synonyms": ["dummy there"], "antonyms": ["locative there"], "tags": ["grammar", "syntax"]},
    {"headword": "dummy subject", "pronunciation": "/ˈdʌmi ˈsʌbdʒɪkt/", "partOfSpeech": "noun", "definition": "A pronoun like 'it' or 'there' that occupies the subject slot without having concrete semantic reference.", "example": "In 'It is raining outside', the word 'it' serves merely as a dummy subject fulfilling syntactic rules.", "translation": "الفاعل الشكلي النحوي الفارغ من الدلالة المادية", "collocations": ["function as a dummy subject", "dummy subject construction"], "synonyms": ["expletive subject", "empty subject"], "antonyms": ["referential subject"], "tags": ["syntax", "grammar"]},
    {"headword": "impersonal it", "pronunciation": "/ɪmˈpɜːsənl ɪt/", "partOfSpeech": "noun", "definition": "The pronoun 'it' used to refer to time, weather, distance, or general ambient conditions.", "example": "Sentences like 'It is past midnight' and 'It is five miles to town' rely on impersonal it.", "translation": "ضمير الغائب غير الشخصي لوصف الطقس والوقت والمسافة", "collocations": ["use of impersonal it", "impersonal it structure"], "synonyms": ["ambient it"], "antonyms": ["personal pronoun"], "tags": ["grammar", "pronouns"]},
    {"headword": "rhetorical question", "pronunciation": "/rɪˈtɒrɪkl ˈkwestʃən/", "partOfSpeech": "noun", "definition": "A question asked to produce an artistic effect or make a point rather than elicit an answer.", "example": "Asking 'Who doesn't want to live in a safer community?' is a powerful rhetorical question.", "translation": "السؤال البلاغي التقريري الذي لا ينتظر إجابة", "collocations": ["pose a rhetorical question", "answer with a rhetorical question"], "synonyms": ["erotesis"], "antonyms": ["genuine inquiry"], "tags": ["rhetoric", "speech"]},
    {"headword": "indirect question", "pronunciation": "/ˌɪndaɪˈrekt ˈkwestʃən/", "partOfSpeech": "noun", "definition": "A question embedded inside a polite introductory phrase or another clause.", "example": "'Could you tell me where the nearest station is?' is an indirect question featuring normal word order.", "translation": "السؤال غير المباشر المهذب المضمن في جملة أخرى", "collocations": ["form an indirect question", "polite indirect question"], "synonyms": ["embedded question"], "antonyms": ["direct question"], "tags": ["grammar", "politeness"]},
    {"headword": "exclamative structure", "pronunciation": "/ɪkˈsklæmətɪv ˈstrʌktʃə/", "partOfSpeech": "noun", "definition": "A grammatical clause introduced by 'What' or 'How' expressing surprise, shock, or admiration.", "example": "'What a breathtaking view!' and 'How generous of you!' are classic exclamative structures.", "translation": "التركيب النحوي التعجبي والانفعالي", "collocations": ["utter an exclamative structure", "use exclamative structures"], "synonyms": ["exclamatory sentence"], "antonyms": ["declarative statement"], "tags": ["grammar", "speech"]},
    {"headword": "emphatic do", "pronunciation": "/ɪmˈfætɪk duː/", "partOfSpeech": "noun", "definition": "The auxiliary verb 'do/did' inserted into an affirmative sentence to stress conviction or contrast.", "example": "In 'I do appreciate your assistance', emphatic do conveys genuine emotional warmth.", "translation": "استخدام do للتوكيد اللفظي في الجمل المثبتة", "collocations": ["use emphatic do", "stress with emphatic do"], "synonyms": ["affirmative do"], "antonyms": ["unemphatic form"], "tags": ["grammar", "emphasis"]},
    {"headword": "broad negative", "pronunciation": "/brɔːd ˈneɡətɪv/", "partOfSpeech": "noun", "definition": "A semi-negative adverb like 'rarely', 'seldom', 'hardly', or 'barely' that creates negative polarity.", "example": "Broad negatives like 'hardly ever' or 'seldom' qualify assertions without absolute negation.", "translation": "النفي التبعيضي وشبه النفي (نادراً، قلما، بالكاد)", "collocations": ["sentence with a broad negative", "use a broad negative"], "synonyms": ["semi-negative", "near-negative"], "antonyms": ["affirmative assertion"], "tags": ["grammar", "syntax"]},
    {"headword": "invariant tag", "pronunciation": "/ɪnˈveəriənt tæɡ/", "partOfSpeech": "noun", "definition": "A conversational tag like 'right?', 'yeah?', or 'eh?' whose grammatical form never changes.", "example": "Using the invariant tag 'right?' at the end of every sentence is ubiquitous among urban youth.", "translation": "اللاحقة التوكيدية الثابتة التي لا تتغير صيغتها", "collocations": ["use an invariant tag", "invariant tag right"], "synonyms": ["fixed question tag"], "antonyms": ["canonical tag question"], "tags": ["conversation", "sociolinguistics"]},
    {"headword": "response token", "pronunciation": "/rɪˈspɒns ˈtəʊkən/", "partOfSpeech": "noun", "definition": "A brief vocalization or word like 'mm', 'yeah', 'sure', or 'great' affirming comprehension in talk.", "example": "Dropping a timely response token shows that you are tracking the conversation attentively.", "translation": "رمز وإشارة التجاوب السريع لتأكيد المتابعة الشفاهية", "collocations": ["utter a response token", "frequent response tokens"], "synonyms": ["back-channel token"], "antonyms": ["silence"], "tags": ["conversation", "interaction"]},
    {"headword": "minimal response", "pronunciation": "/ˈmɪnɪml rɪˈspɒns/", "partOfSpeech": "noun", "definition": "A very short, concise verbal reply that fulfills the conversational turn without volunteering extra data.", "example": "When questioned about his weekend, the teenager offered only a minimal response: 'Fine.'", "translation": "الرد الشفاهي المقتضب والموجز للحد الأدنى", "collocations": ["provide a minimal response", "reply with a minimal response"], "synonyms": ["brief answer"], "antonyms": ["elaborate explanation"], "tags": ["speech", "conversation"]},
    {"headword": "agreement signal", "pronunciation": "/əˈɡriːmənt ˈsɪɡnl/", "partOfSpeech": "noun", "definition": "A verbal phrase or bodily nod indicating shared consensus with what a conversational partner just asserted.", "example": "Phrases like 'Totally', 'I couldn't agree more', and 'Spot on' function as energetic agreement signals.", "translation": "إشارة الموافقة والتأييد الشفاهية الفورية", "collocations": ["send an agreement signal", "clear agreement signal"], "synonyms": ["concurrence marker"], "antonyms": ["disagreement marker"], "tags": ["conversation", "pragmatics"]},
    {"headword": "repair initiator", "pronunciation": "/rɪˈpeə ɪˈnɪʃieɪtə/", "partOfSpeech": "noun", "definition": "An expression like 'Sorry?', 'Pardon?', or 'What did you say?' prompting a speaker to repeat or clarify.", "example": "Saying 'Come again?' functions as an informal repair initiator during a noisy reception.", "translation": "بادئ طلب التصحيح والاستيضاح في الحوار الشفاهي", "collocations": ["function as a repair initiator", "use a repair initiator"], "synonyms": ["clarification request"], "antonyms": [], "tags": ["conversation", "pragmatics"]},
    {"headword": "comprehension check", "pronunciation": "/ˌkɒmprɪˈhenʃn tʃek/", "partOfSpeech": "noun", "definition": "A question asked by the speaker like 'Does that make sense?' or 'Are you with me?' to confirm understanding.", "example": "Great instructors insert a frequent comprehension check before introducing challenging technical concepts.", "translation": "التحقق من الفهم والاستيعاب لدى المستمع", "collocations": ["perform a comprehension check", "conduct a comprehension check"], "synonyms": ["understanding check"], "antonyms": [], "tags": ["education", "speech"]},
    {"headword": "spoken discourse", "pronunciation": "/ˈspəʊkən ˈdɪskɔːs/", "partOfSpeech": "noun", "definition": "Language produced orally during real-time human interaction, featuring distinctive grammatical conventions.", "example": "Linguists analyze spoken discourse to identify natural pauses, overlapping speech, and intonation shifts.", "translation": "الخطاب الشفاهي المحكي وخصائصه التفاعلية", "collocations": ["patterns in spoken discourse", "features of spoken discourse"], "synonyms": ["oral interaction", "spoken language"], "antonyms": ["written prose"], "tags": ["linguistics", "conversation"]},
    {"headword": "conversational coherence", "pronunciation": "/ˌkɒnvəˈseɪʃənl kəʊˈhɪərəns/", "partOfSpeech": "noun", "definition": "The logical, thematic, and social connectedness that makes a spoken interaction feel smooth and orderly.", "example": "Even when topics drifted rapidly, the two lifelong friends maintained conversational coherence through shared jokes.", "translation": "الترابط والانسجام الحواري بين أطراف الحديث", "collocations": ["preserve conversational coherence", "maintain conversational coherence"], "synonyms": ["dialogue coherence"], "antonyms": ["conversational breakdown"], "tags": ["discourse", "pragmatics"]},
    {"headword": "interactional routine", "pronunciation": "/ˌɪntərˈækʃənl ruːˈtiːn/", "partOfSpeech": "noun", "definition": "A standardized sequence of communicative exchanges that recur in daily predictable social contexts.", "example": "Ordering coffee at a cafe involves an interactional routine of greetings, choices, and payments.", "translation": "الروتين التفاعلي النمطي المعتاد في المواقف اليومية", "collocations": ["participate in an interactional routine", "social interactional routine"], "synonyms": ["conversational script"], "antonyms": [], "tags": ["sociolinguistics", "pragmatics"]},
    {"headword": "everyday idiom", "pronunciation": "/ˈevrideɪ ˈɪdiəm/", "partOfSpeech": "noun", "definition": "A figurative idiomatic expression used regularly in spontaneous, casual day-to-day conversation.", "example": "'Bite the bullet' and 'hit the nail on the head' are examples of an everyday idiom familiar to all.", "translation": "التعبير الاصطلاحي الشائع والمستخدم يومياً", "collocations": ["use an everyday idiom", "familiar everyday idiom"], "synonyms": ["common idiom"], "antonyms": ["obscure idiom"], "tags": ["idioms", "vocabulary"]}
]

grammar_79 = [
    {
        "title": "Spoken Grammar: Ellipsis, Response Words, Informal Structures",
        "explanation": "Spoken English differs from written English because speech is created in real time under cognitive time constraints. Mastering natural spoken grammar requires familiarity with four primary mechanics:\n\n1. Situational Ellipsis:\n   In informal conversation, unstressed words at the start of a clause (pronouns, auxiliary verbs) are frequently omitted when clear from context.\n   - '(Have you) Seen my keys anywhere?'\n   - '(I am) Heading out now, catch you later.'\n   - '(It) Looks fantastic on you!'\n\n2. Response Words & Minimal Responses (Back-channeling):\n   Active listeners continually signal engagement without interrupting the speaker's turn. Common tokens include: 'Right', 'Totally', 'Fair enough', 'Indeed', 'I hear you', and 'Spot on'.\n\n3. Informal Tags & Invariant Tags:\n   Alongside standard tag questions ('It's hot, isn't it?'), spoken English relies heavily on invariant tags like 'right?', 'yeah?', or 'ok?':\n   - 'We are meeting at seven, right?'\n\n4. Fronting & Cleft Sentences for Focus:\n   Speakers shift key elements to the front to establish topics or create emphasis:\n   - 'That new documentary, I found it fascinating.' (Topic Fronting)\n   - 'It was Alex who solved the server problem.' (It-cleft)\n   - 'What I really need is a cup of hot tea.' (Wh-cleft)",
        "structures": [
            {"pattern": "Situational Ellipsis: (Auxiliary + Subject omitted): 'Got a minute?' / 'Seen the news?' / 'Looks great!'"},
            {"pattern": "Invariant tag: Statement + right? / yeah?: 'You finished the audit, right?'"},
            {"pattern": "Cleft emphasis: It + be + Focus + that / who: 'It was the repair strategy that saved the meeting.'"}
        ],
        "examples": [
            {
                "sentence": "Heading to the cafe for lunch; care to join?",
                "arabic": "ذاهب إلى المقهى لتناول الغداء؛ هل تود الانضمام؟ (حذف شفاهي للفاعل والفعل المساعد).",
                "usesVocabulary": ["ellipsis"]
            },
            {
                "sentence": "The presentation went smoothly, didn't it? Every response token from the client signaled strong interest.",
                "arabic": "سار العرض بسلاسة، أليس كذلك؟ كل إشارة تجاوب من العميل دلت على اهتمام كبير.",
                "usesVocabulary": ["tag question", "response token"]
            },
            {
                "sentence": "It was her subtle repair strategy that restored conversational coherence after that awkward false start.",
                "arabic": "كانت استراتيجيتها الدقيقة في تدارك الحديث هي التي أعادت الانسجام الحواري بعد تلك البداية المتعثرة.",
                "usesVocabulary": ["repair strategy", "conversational coherence", "false start"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "In formal academic writing, you can write: 'Seen the results yesterday.'",
                "right": "In formal academic writing, you must write: 'We examined the results yesterday.'",
                "explanation": "Situational ellipsis is an informal spoken feature; it must not be used in formal academic or technical writing."
            },
            {
                "wrong": "You called him yesterday, didn't you right?",
                "right": "You called him yesterday, didn't you? / You called him yesterday, right?",
                "explanation": "Do not combine a grammatical tag question ('didn't you') and an invariant tag ('right') in the same clause."
            }
        ]
    }
]

convs_79 = [
    {
        "title": "Coffee Break: Spontaneous Office Banter",
        "titleArabic": "استراحة القهوة: محادثة عفوية بين زملاء العمل",
        "setting": "Two colleagues chat by the office coffee machine after a demanding workshop.",
        "lines": [
            {"speaker": "Dan", "text": "Rough morning in there. Got any milk left?"},
            {"speaker": "Claire", "text": "Plenty in the fridge. That client presentation was intense, wasn't it?"},
            {"speaker": "Dan", "text": "Totally. At first, I had a false start and relied on every filler word imaginable."},
            {"speaker": "Claire", "text": "Noticed that, but your quick self-correction and smooth reformulation saved the moment."},
            {"speaker": "Dan", "text": "Thanks. I used a softening device and some vague language to avoid offending their senior director."},
            {"speaker": "Claire", "text": "Smart face-saving strategy. Their VP gave clear agreement signals and constant back-channeling."},
            {"speaker": "Dan", "text": "It was your timely comprehension check that cleared up their doubts about our pricing."},
            {"speaker": "Claire", "text": "Right? Good team effort. Ready to get back to our desks?"}
        ],
        "vocabularyUsed": ["ellipsis", "tag question", "false start", "filler word", "self-correction", "reformulation", "softening device", "vague language", "face-saving strategy", "agreement signal", "back-channeling", "comprehension check", "invariant tag"]
    },
    {
        "title": "Sociolinguistics Lab: Analyzing Spoken Discourse",
        "titleArabic": "مختبر علم اللغة الاجتماعي: تحليل الخطاب الشفاهي",
        "setting": "A linguistics professor and student examine audio transcripts of casual spoken conversations.",
        "lines": [
            {"speaker": "Professor", "text": "Notice how spontaneous spoken discourse relies on discourse particles and informal contractions like 'wanna' and 'gonna'."},
            {"speaker": "Student", "text": "Indeed. This speaker used an elided form alongside a fronting structure for emotional emphasis."},
            {"speaker": "Professor", "text": "Observe the turn-taking signal around minute three. A deliberate unfilled pause invited the interlocutor to respond."},
            {"speaker": "Student", "text": "And the listener supplied an immediate minimal response before asking an indirect question."},
            {"speaker": "Professor", "text": "When mutual understanding faltered, she deployed a polite repair initiator: 'Sorry, what did you mean?'"},
            {"speaker": "Student", "text": "That restored conversational coherence instantly. She also dropped an everyday idiom in context."},
            {"speaker": "Professor", "text": "Brilliant observation. Natural speech weaves pragmatic markers together into seamless interactional routines."},
            {"speaker": "Student", "text": "Analyzing genuine audio recordings reveals patterns that traditional grammar textbooks completely overlook."}
        ],
        "vocabularyUsed": ["spoken discourse", "discourse particle", "informal contraction", "elided form", "fronting structure", "turn-taking signal", "unfilled pause", "minimal response", "indirect question", "repair initiator", "conversational coherence", "everyday idiom", "idiom in context", "interactional routine"]
    },
    {
        "title": "Networking Event: Small Talk and Phatic Communion",
        "titleArabic": "فعالية تعارف مهني: الأحاديث الودية وبناء الألفة",
        "setting": "Two professionals meet at a tech mixer in downtown London.",
        "lines": [
            {"speaker": "Alex", "text": "Great turnout tonight, right? Mind if I grab the chair next to you?"},
            {"speaker": "Maya", "text": "Not at all, go right ahead! Classic London rain outside, to put it mildly."},
            {"speaker": "Alex", "text": "A bit of classic phatic communion never hurts! What brings you to this symposium?"},
            {"speaker": "Maya", "text": "That is an effective small talk formula. In a colloquial register, I do user research for fin-tech startups."},
            {"speaker": "Alex", "text": "Fascinating work. I noticed a subtle topic shift during the keynote when someone posed a rhetorical question about ethics."},
            {"speaker": "Maya", "text": "The speaker flouted Grice's conversational maxim to create an intriguing implicature."},
            {"speaker": "Alex", "text": "I do appreciate authentic debate. Let us connect on LinkedIn before we depart."},
            {"speaker": "Maya", "text": "Wonderful idea! It was an absolute pleasure sharing perspectives on communicative dynamics."}
        ],
        "vocabularyUsed": ["invariant tag", "phatic communion", "small talk formula", "colloquial register", "topic shift", "rhetorical question", "conversational maxim", "implicature", "emphatic do"]
    }
]

paras_79 = [
    {
        "title": "The Mechanics and Fluidity of Spontaneous Spoken Discourse",
        "titleArabic": "آليات وسيولة الخطاب الشفاهي العفوي في التواصل",
        "text": "Spontaneous spoken discourse operates under radically different communicative principles than edited written text. During fluid daily conversation, speakers rely extensively on situational ellipsis, omitting obvious subject pronouns and auxiliaries without impeding comprehension. To manage real-time cognitive formulation, interlocutors naturally introduce the occasional filler word, filled pause, or momentary unfilled pause before executing an agile self-correction or verbal reformulation. Concurrently, engaged listeners supply rhythmic back-channeling and supportive response tokens to signal attentiveness. When a minor misunderstanding occurs, introducing an intuitive repair strategy or gentle repair initiator swiftly restores conversational coherence.",
        "vocabularyUsed": ["spoken discourse", "ellipsis", "filler word", "filled pause", "unfilled pause", "self-correction", "reformulation", "back-channeling", "response token", "repair strategy", "repair initiator", "conversational coherence"]
    },
    {
        "title": "Pragmatic Politeness, Vagueness, and Face-Saving Strategies",
        "titleArabic": "الأدب التداولي، اللغة التقريبية، واستراتيجيات حفظ ماء الوجه",
        "text": "Navigating delicate social interactions demands sophisticated pragmatic competence and subtle softening devices. In everyday communication, participants intentionally employ vague language and approximate quantifiers to avoid sounding overly blunt or dogmatic. Rather than issuing direct commands, culturally aware communicators execute an indirect speech act or frame requests as polite indirect questions. When delivering difficult news, adopting a thoughtful face-saving strategy protects the dignity of all parties involved. Furthermore, by observing each conversational maxim and interpreting subtle conversational implicatures, listeners grasp subtext effortlessly. Ultimately, balancing polite hedging expressions with warm everyday idioms maintains harmonious social relationships.",
        "vocabularyUsed": ["softening device", "vague language", "indirect speech act", "indirect question", "face-saving strategy", "conversational maxim", "implicature", "hedging expression", "everyday idiom"]
    },
    {
        "title": "Social Bonding, Small Talk Formulas, and Expressive Syntax",
        "titleArabic": "التقارب الاجتماعي، قوالب الحديث الودي، والتراكيب التعبيرية",
        "text": "Forming authentic social connections often begins with seemingly modest phatic communion and conventional small talk formulas. When interacting within a colloquial register, speakers effortlessly sprinkle invariant tags and formulaic expressions into everyday dialogues. To emphasize key emotions or clarify narrative priorities, oral grammar frequently leverages fronting structures, cleft sentences, and emphatic do. Using an organic topic change marker facilitates seamless topic shifts without jarring listeners. From sharing an idiom in context to executing a familiar interactional routine at a neighborhood cafe, natural conversational patterns form the vibrant social glue binding human communities.",
        "vocabularyUsed": ["phatic communion", "small talk formula", "colloquial register", "invariant tag", "formulaic expression", "fronting structure", "cleft sentence", "emphatic do", "topic change marker", "topic shift", "idiom in context", "interactional routine"]
    }
]

# ==============================================================================
# DAY 80: Advanced Everyday Review (Review of advanced everyday English)
# Grammar: Review: Connectors, Clauses, Spoken Patterns
# ==============================================================================

vocab_80 = [
    # Linguistic Mastery, Fluency & Pragmatics
    {"headword": "register awareness", "pronunciation": "/ˈredʒɪstər əˈweənəs/", "partOfSpeech": "noun", "definition": "The conscious understanding of how language variety changes according to audience, purpose, and setting.", "example": "Developing register awareness enables language learners to avoid slang in boardrooms and stuffy jargon at social parties.", "translation": "الوعي بالسجلات اللغوية وملاءمة الأسلوب للمقام", "collocations": ["demonstrate register awareness", "cultivate register awareness"], "synonyms": ["stylistic sensitivity"], "antonyms": ["register insensitivity"], "tags": ["linguistics", "fluency"]},
    {"headword": "contextual appropriacy", "pronunciation": "/kənˈtekstʃuəl əˌprəʊpriˈeɪti/", "partOfSpeech": "noun", "definition": "The quality of language being socially and culturally suitable for a specific conversational situation.", "example": "Grammatical accuracy is worthless without contextual appropriacy in sensitive diplomatic negotiations.", "translation": "الملاءمة والمناسبة السياقية للموقف التواصلي", "collocations": ["ensure contextual appropriacy", "judge contextual appropriacy"], "synonyms": ["situational suitability"], "antonyms": ["inappropriateness"], "tags": ["pragmatics", "culture"]},
    {"headword": "pragmatic competence", "pronunciation": "/præɡˈmætɪk ˈkɒmpɪtəns/", "partOfSpeech": "noun", "definition": "The ability to understand and produce language that matches communicative intentions and social contexts.", "example": "Her outstanding pragmatic competence allowed her to interpret humor, irony, and unstated cultural assumptions flawlessly.", "translation": "الكفاءة التداولية والقدرة على فهم المقاصد الضمنية", "collocations": ["develop pragmatic competence", "high pragmatic competence"], "synonyms": ["pragmatic fluency"], "antonyms": ["pragmatic failure"], "tags": ["linguistics", "communication"]},
    {"headword": "discourse coherence", "pronunciation": "/ˈdɪskɔːs kəʊˈhɪərəns/", "partOfSpeech": "noun", "definition": "The macro-level logical unity and meaningful connection of ideas throughout a text or conversation.", "example": "Using advanced connectors strategically guarantees that an academic essay maintains immaculate discourse coherence.", "translation": "التماسك والانسجام المنطقي الكلي للخطاب", "collocations": ["maintain discourse coherence", "threaten discourse coherence"], "synonyms": ["thematic coherence"], "antonyms": ["discourse incoherence"], "tags": ["discourse", "writing"]},
    {"headword": "textual cohesion", "pronunciation": "/ˈtekstʃuəl kəʊˈhiːʒn/", "partOfSpeech": "noun", "definition": "The grammatical and lexical links that hold sentences together through pronouns, repetition, and conjunctions.", "example": "Textual cohesion is achieved through skillful reference words, ellipsis, and appropriate discourse markers.", "translation": "الاتساق والترابط النحوي واللفظي بين الجمل", "collocations": ["strengthen textual cohesion", "elements of textual cohesion"], "synonyms": ["grammatical cohesion"], "antonyms": ["textual fragmentation"], "tags": ["linguistics", "writing"]},
    {"headword": "lexical density", "pronunciation": "/ˈleksɪkl ˈdensəti/", "partOfSpeech": "noun", "definition": "A measure of the proportion of content words (nouns, verbs, adjectives) relative to grammatical function words.", "example": "Scientific journals exhibit high lexical density, packing dense technical information into concise clauses.", "translation": "الكثافة المعجمية ونسبة كلمات المضمون في النص", "collocations": ["high lexical density", "calculate lexical density"], "synonyms": ["content word ratio"], "antonyms": ["sparse vocabulary"], "tags": ["linguistics", "academic"]},
    {"headword": "syntactic complexity", "pronunciation": "/sɪnˈtæktɪk kəmˈpleksəti/", "partOfSpeech": "noun", "definition": "The sophistication of sentence structures characterized by embedding, subordinate clauses, and passives.", "example": "The student's writing evolved from simple compound sentences to impressive syntactic complexity with participle clauses.", "translation": "التعقيد والتركيب النحوي المتقدم للجمل", "collocations": ["exhibit syntactic complexity", "measure syntactic complexity"], "synonyms": ["structural sophistication"], "antonyms": ["syntactic simplicity"], "tags": ["syntax", "writing"]},
    {"headword": "semantic precision", "pronunciation": "/sɪˈmæntɪk prɪˈsɪʒn/", "partOfSpeech": "noun", "definition": "The exact and nuanced use of words to convey specific meanings without ambiguity or vagueness.", "example": "Legal contracts demand rigorous semantic precision to eliminate contradictory interpretations of liability.", "translation": "الدقة الدلالية والمعنوية في اختيار الألفاظ", "collocations": ["achieve semantic precision", "demand semantic precision"], "synonyms": ["terminological exactness"], "antonyms": ["semantic ambiguity"], "tags": ["linguistics", "semantics"]},
    {"headword": "communicative fluency", "pronunciation": "/kəˈmjuːnɪkətɪv ˈfluːənsi/", "partOfSpeech": "noun", "definition": "The ability to produce spoken and written language smoothly, expressively, and without disruptive pauses.", "example": "The intensive immersion program prioritized communicative fluency over rigid rote grammar drills.", "translation": "الطلاقة التواصلية والقدرة على التعبير بسلاسة", "collocations": ["attain communicative fluency", "foster communicative fluency"], "synonyms": ["conversational ease"], "antonyms": ["speech dysfluency"], "tags": ["fluency", "learning"]},
    {"headword": "interactional competence", "pronunciation": "/ˌɪntərˈækʃənl ˈkɒmpɪtəns/", "partOfSpeech": "noun", "definition": "The mastery of interactive social norms such as turn-taking, interrupting politely, and active listening.", "example": "Her interactional competence made her a formidable chairperson capable of steering heated debates productively.", "translation": "الكفاءة التفاعلية وإدارة الحوار التواصلي ببراعة", "collocations": ["demonstrate interactional competence", "aspects of interactional competence"], "synonyms": ["conversational skill"], "antonyms": [], "tags": ["sociolinguistics", "communication"]},
    {"headword": "sociolinguistic awareness", "pronunciation": "/ˌsəʊsiəʊlɪŋˈɡwɪstɪk əˈweənəs/", "partOfSpeech": "noun", "definition": "The conscious knowledge of how language intersects with social factors such as class, gender, and regional accents.", "example": "Developing sociolinguistic awareness helps interpreters navigate culturally sensitive idiomatic expressions.", "translation": "الوعي اللغوي الاجتماعي وتأثير المجتمع في اللغة", "collocations": ["possess sociolinguistic awareness", "promote sociolinguistic awareness"], "synonyms": ["sociolinguistic sensitivity"], "antonyms": [], "tags": ["sociolinguistics", "culture"]},
    {"headword": "cross-cultural communication", "pronunciation": "/krɒs ˈkʌltʃərəl kəˌmjuːnɪˈkeɪʃn/", "partOfSpeech": "noun", "definition": "Communication between individuals from differing cultural backgrounds and linguistic norms.", "example": "Global multinational corporations invest millions in workshops covering cross-cultural communication.", "translation": "التواصل العابر للثقافات والتفاهم بين الشعوب", "collocations": ["master cross-cultural communication", "challenges in cross-cultural communication"], "synonyms": ["intercultural communication"], "antonyms": ["monocultural communication"], "tags": ["culture", "communication"]},
    {"headword": "intercultural competence", "pronunciation": "/ˌɪntəˈkʌltʃərəl ˈkɒmpɪtəns/", "partOfSpeech": "noun", "definition": "The cognitive and behavioral capacity to function effectively and respectfully across diverse cultural environments.", "example": "Diplomats are selected for intercultural competence, enabling them to build bridges in polarized geopolitical climates.", "translation": "الكفاءة الثقافية التفاعلية والتكيف مع الثقافات", "collocations": ["cultivate intercultural competence", "core intercultural competence"], "synonyms": ["cultural intelligence", "CQ"], "antonyms": ["ethnocentrism"], "tags": ["culture", "diplomacy"]},
    {"headword": "language transfer", "pronunciation": "/ˈlæŋɡwɪdʒ ˈtrænsfɜː/", "partOfSpeech": "noun", "definition": "The application of rules and structures from one's native language when acquiring and using a second language.", "example": "Positive language transfer facilitates learning related vocabulary, whereas negative transfer causes grammatical slips.", "translation": "الانتقال والأثر اللغوي من اللغة الأم للغة المستهدفة", "collocations": ["negative language transfer", "influence of language transfer"], "synonyms": ["linguistic interference"], "antonyms": [], "tags": ["applied linguistics", "acquisition"]},
    {"headword": "fossilized error", "pronunciation": "/ˈfɒsəlaɪzd ˈerə/", "partOfSpeech": "noun", "definition": "A persistent, recurring language error that has become entrenched in a learner's interlanguage over time.", "example": "Targeted feedback helped the advanced speaker overcome a fossilized error with preposition choice.", "translation": "الخطأ اللغوي المتحجر والمزمن لدى المتعلم", "collocations": ["overcome a fossilized error", "correct a fossilized error"], "synonyms": ["entrenched mistake"], "antonyms": ["transient slip"], "tags": ["pedagogy", "acquisition"]},

    # Second Language Acquisition & Vocabulary Depth
    {"headword": "interlanguage", "pronunciation": "/ˌɪntəˈlæŋɡwɪdʒ/", "partOfSpeech": "noun", "definition": "The dynamic, evolving linguistic system created by a second language learner that incorporates elements of both tongues.", "example": "A student's interlanguage gradually approximates native speaker competence through continued immersion.", "translation": "اللغة البينية / المنظومة اللغوية المرحلية للمتعلم", "collocations": ["learner's interlanguage", "stages of interlanguage"], "synonyms": ["learner language"], "antonyms": ["native proficiency"], "tags": ["linguistics", "acquisition"]},
    {"headword": "explicit instruction", "pronunciation": "/ɪkˈsplɪsɪt ɪnˈstrʌkʃn/", "partOfSpeech": "noun", "definition": "Direct, structured teaching where grammatical rules, phonetics, and definitions are explained deliberately.", "example": "Research shows combining explicit instruction with communicative tasks yields the fastest vocabulary retention.", "translation": "التعليم المباشر الصريح للقواعد والمفاهيم", "collocations": ["benefit from explicit instruction", "provide explicit instruction"], "synonyms": ["direct teaching"], "antonyms": ["implicit learning"], "tags": ["pedagogy", "learning"]},
    {"headword": "implicit learning", "pronunciation": "/ɪmˈplɪsɪt ˈlɜːnɪŋ/", "partOfSpeech": "noun", "definition": "The acquisition of complex knowledge and grammatical patterns naturally without conscious awareness of rules.", "example": "Children acquire their mother tongue almost exclusively through implicit learning during playtime.", "translation": "التعلم الضمني العفوي دون وعي مباشر بالقواعد", "collocations": ["rely on implicit learning", "power of implicit learning"], "synonyms": ["unconscious acquisition"], "antonyms": ["explicit learning"], "tags": ["psychology", "learning"]},
    {"headword": "incidental learning", "pronunciation": "/ˌɪnsɪˈdentl ˈlɜːnɪŋ/", "partOfSpeech": "noun", "definition": "Learning that occurs casually as a secondary byproduct of engaging in other activities like reading novels.", "example": "Extensive reading of English thrillers fosters rich incidental learning of idiomatic collocations.", "translation": "التعلم العرضي العفوي غير المقصود لذاته", "collocations": ["foster incidental learning", "incidental learning of vocabulary"], "synonyms": ["unintentional learning"], "antonyms": ["deliberate learning"], "tags": ["education", "learning"]},
    {"headword": "deliberate vocabulary study", "pronunciation": "/dɪˈlɪbərət vəʊˈkæbjuləri ˈstʌdi/", "partOfSpeech": "noun", "definition": "Intentional, focused practice dedicated specifically to learning and memorizing words and collocations.", "example": "Pairing flashcard apps with deliberate vocabulary study dramatically expanded her lexicon before IELTS.", "translation": "الدراسة القصدية الواعية للمفردات والمصطلحات", "collocations": ["engage in deliberate vocabulary study", "results of deliberate vocabulary study"], "synonyms": ["targeted lexical study"], "antonyms": ["casual exposure"], "tags": ["learning", "vocabulary"]},
    {"headword": "lexical chunk", "pronunciation": "/ˈleksɪkl tʃʌŋk/", "partOfSpeech": "noun", "definition": "A multiword sequence stored and retrieved from memory as a prefabricated single unit of meaning.", "example": "Learning language in lexical chunks like 'on the other hand' accelerates spontaneous fluency.", "translation": "الكتلة المعجمية / العبارة المركبة المحفوظة كوحدة واحدة", "collocations": ["acquire lexical chunks", "speak in lexical chunks"], "synonyms": ["collocational chunk", "formulaic chunk"], "antonyms": ["isolated words"], "tags": ["vocabulary", "fluency"]},
    {"headword": "collocational knowledge", "pronunciation": "/ˌkɒləˈkeɪʃənl ˈnɒlɪdʒ/", "partOfSpeech": "noun", "definition": "An understanding of which words naturally co-occur together in authentic native speaker usage.", "example": "Knowing that we say 'heavy rain' rather than 'strong rain' demonstrates collocational knowledge.", "translation": "المعرفة بالمتلازمات اللفظية والكلمات المترافقة", "collocations": ["test collocational knowledge", "expand collocational knowledge"], "synonyms": ["word-partnership knowledge"], "antonyms": [], "tags": ["vocabulary", "linguistics"]},
    {"headword": "phraseological unit", "pronunciation": "/ˌfreɪziəˈlɒdʒɪkl ˈjuːnɪt/", "partOfSpeech": "noun", "definition": "A set phrase, idiom, or fixed expression whose overall meaning cannot be deduced from isolated parts.", "example": "Proverbs, idioms, and phrasal verbs constitute vital phraseological units in every living language.", "translation": "الوحدة التعبيرية الاصطلاحية المركبة", "collocations": ["analyze phraseological units", "rich in phraseological units"], "synonyms": ["set phrase", "idiomatic unit"], "antonyms": ["free word combination"], "tags": ["linguistics", "phraseology"]},
    {"headword": "multiword expression", "pronunciation": "/ˌmʌltiwɜːd ɪkˈspreʃn/", "partOfSpeech": "noun", "definition": "A linguistic unit composed of two or more words functioning as a single conceptual or syntactic entity.", "example": "Natural language processors struggle with multiword expressions like 'kick the bucket' due to non-compositionality.", "translation": "التعبير اللفظي متعدد الكلمات ذو المعنى الموحد", "collocations": ["identify multiword expressions", "classify multiword expressions"], "synonyms": ["MWE", "compound phrase"], "antonyms": ["single-word term"], "tags": ["computational linguistics", "vocabulary"]},
    {"headword": "fixed expression", "pronunciation": "/fɪkst ɪkˈspreʃn/", "partOfSpeech": "noun", "definition": "A conventional idiom or phrase that cannot be grammatically modified without sounding awkward or incorrect.", "example": "'All of a sudden' is a rigid fixed expression that permits zero grammatical alteration.", "translation": "التعبير الجامد الثابت غير القابل للتعديل النحوي", "collocations": ["memorize fixed expressions", "use a fixed expression"], "synonyms": ["immutable idiom"], "antonyms": ["flexible phrase"], "tags": ["idioms", "grammar"]},
    {"headword": "semi-fixed expression", "pronunciation": "/ˈsemi fɪkst ɪkˈspreʃn/", "partOfSpeech": "noun", "definition": "A formulaic phrase that has a constant grammatical framework but allows variable word insertions.", "example": "The phrase 'as far as [person/knowledge] is concerned' operates as a useful semi-fixed expression.", "translation": "التعبير شبه الثابت الذي يقبل إدراج كلمات متغيرة", "collocations": ["structure of a semi-fixed expression", "rely on semi-fixed expressions"], "synonyms": ["variable formula"], "antonyms": ["rigid fixed expression"], "tags": ["grammar", "vocabulary"]},
    {"headword": "productive knowledge", "pronunciation": "/prəˈdʌktɪv ˈnɒlɪdʒ/", "partOfSpeech": "noun", "definition": "The active linguistic competence required to produce words, structures, and idioms in speech and writing.", "example": "Transitioning vocabulary from passive recognition to confident productive knowledge takes deliberate practice.", "translation": "المعرفة اللغوية الإنتاجية الفعالة في التحدث والكتابة", "collocations": ["develop productive knowledge", "measure productive knowledge"], "synonyms": ["active vocabulary knowledge"], "antonyms": ["receptive knowledge"], "tags": ["acquisition", "pedagogy"]},
    {"headword": "receptive knowledge", "pronunciation": "/rɪˈseptɪv ˈnɒlɪdʒ/", "partOfSpeech": "noun", "definition": "The ability to comprehend and recognize words and structures when listening or reading.", "example": "Most learners possess far greater receptive knowledge than they can spontaneously mobilize when speaking.", "translation": "المعرفة اللغوية الاستقبالية في القراءة والاستماع", "collocations": ["receptive knowledge of vocabulary", "assess receptive knowledge"], "synonyms": ["passive vocabulary"], "antonyms": ["productive knowledge"], "tags": ["learning", "acquisition"]},
    {"headword": "depth of processing", "pronunciation": "/depθ əv ˈprəʊsesɪŋ/", "partOfSpeech": "noun", "definition": "A cognitive psychology principle stating that deeper, meaningful analysis leads to more durable memory traces.", "example": "Writing original sentences with new collocations creates a greater depth of processing than simple flashcards.", "translation": "عمق المعالجة الإدراكية لترسيخ الذاكرة", "collocations": ["increase depth of processing", "theory of depth of processing"], "synonyms": ["levels of processing"], "antonyms": ["shallow processing"], "tags": ["cognition", "psychology"]},
    {"headword": "spaced practice", "pronunciation": "/speɪst ˈpræktɪs/", "partOfSpeech": "noun", "definition": "A learning technique where study sessions are spaced out over intervals of time rather than crammed together.", "example": "Adopting spaced practice over three months guarantees long-term retention of irregular verb conjugations.", "translation": "الممارسة والمراجعة المتباعدة زمنياً لتعزيز الذاكرة", "collocations": ["implement spaced practice", "benefits of spaced practice"], "synonyms": ["spaced repetition", "distributed practice"], "antonyms": ["massed practice", "cramming"], "tags": ["learning", "psychology"]},

    # Learning Strategies, SLA Theories & Self-Assessment
    {"headword": "retrieval practice", "pronunciation": "/rɪˈtriːvl ˈpræktɪs/", "partOfSpeech": "noun", "definition": "A study method focused on actively recalling information from memory rather than passively re-reading it.", "example": "Testing yourself with closed-book flashcards is a proven form of high-impact retrieval practice.", "translation": "ممارسة الاسترجاع والاستدعاء النشط للمعلومات من الذاكرة", "collocations": ["engage in retrieval practice", "power of retrieval practice"], "synonyms": ["active recall", "testing effect"], "antonyms": ["passive review"], "tags": ["psychology", "education"]},
    {"headword": "elaborative interrogation", "pronunciation": "/ɪˈlæbərətɪv ɪnˌterəˈɡeɪʃn/", "partOfSpeech": "noun", "definition": "A learning strategy involving asking yourself 'why' a stated fact or concept is true to deepen understanding.", "example": "Using elaborative interrogation helps learners connect grammatical rules to their communicative rationale.", "translation": "الاستنطاق والشرح التوسعي بالسؤال عن علة الحقائق", "collocations": ["apply elaborative interrogation", "technique of elaborative interrogation"], "synonyms": ["why-questioning"], "antonyms": ["rote repetition"], "tags": ["pedagogy", "cognition"]},
    {"headword": "self-explanation technique", "pronunciation": "/self ˌekspləˈneɪʃn tekˈniːk/", "partOfSpeech": "noun", "definition": "A learning strategy where students explain the steps of their thought process aloud or in writing.", "example": "Employing the self-explanation technique while solving complex grammar exercises illuminates hidden misconceptions.", "translation": "تقنية الشرح الذاتي وتوضيح خطوات التفكير للنفس", "collocations": ["use the self-explanation technique", "benefit from self-explanation"], "synonyms": ["self-directed explanation"], "antonyms": [], "tags": ["pedagogy", "learning"]},
    {"headword": "dual coding", "pronunciation": "/ˌdjuːəl ˈkəʊdɪŋ/", "partOfSpeech": "noun", "definition": "The cognitive theory that combining visual imagery with verbal representations enhances information retention.", "example": "Language apps utilize dual coding by pairing vocabulary definitions with evocative visual icons.", "translation": "الترميز الثنائي بدمج الصور البصرية بالكلمات اللفظية", "collocations": ["theory of dual coding", "apply dual coding"], "synonyms": ["multimodal coding"], "antonyms": ["single-modality study"], "tags": ["psychology", "education"]},
    {"headword": "worked example", "pronunciation": "/wɜːkt ɪɡˈzɑːmpl/", "partOfSpeech": "noun", "definition": "A step-by-step demonstration of how to solve a problem or structure an essay provided to learners as a model.", "example": "Studying a worked example of a Band 9 essay gave candidates a crystal-clear template for discourse cohesion.", "translation": "نموذج محلول خطوة بخطوة للاقتداء والتعلم", "collocations": ["analyze a worked example", "provide a worked example"], "synonyms": ["annotated model"], "antonyms": ["unassisted trial and error"], "tags": ["education", "pedagogy"]},
    {"headword": "problem-based learning", "pronunciation": "/ˈprɒbləm beɪst ˈlɜːnɪŋ/", "partOfSpeech": "noun", "definition": "A student-centered pedagogy where learners acquire knowledge through solving open-ended real-world challenges.", "example": "Medical schools pioneered problem-based learning by presenting students with simulated diagnostic crises.", "translation": "التعلم القائم على حل المشكلات الحقيقية", "collocations": ["adopt problem-based learning", "PBL methodology"], "synonyms": ["PBL"], "antonyms": ["lecture-based teaching"], "tags": ["pedagogy", "education"]},
    {"headword": "task-based instruction", "pronunciation": "/tɑːsk beɪst ɪnˈstrʌkʃn/", "partOfSpeech": "noun", "definition": "A language teaching approach focusing on having students complete authentic, meaningful communicative tasks.", "example": "In task-based instruction, students learn hotel booking vocabulary by actually planning an itinerary.", "translation": "التعليم القائم على إنجاز المهام التواصلية الواقعية", "collocations": ["principles of task-based instruction", "TBLT approach"], "synonyms": ["TBLT"], "antonyms": ["grammar-translation method"], "tags": ["pedagogy", "language teaching"]},
    {"headword": "communicative approach", "pronunciation": "/kəˈmjuːnɪkətɪv əˈprəʊtʃ/", "partOfSpeech": "noun", "definition": "A language teaching methodology prioritizing meaningful communication and interaction over grammatical perfection.", "example": "The communicative approach transformed modern language academies by replacing drills with lively role-play.", "translation": "المدخل التواصلي في تدريس اللغات", "collocations": ["embrace the communicative approach", "foundations of the communicative approach"], "synonyms": ["CLT"], "antonyms": ["audio-lingual method"], "tags": ["pedagogy", "language teaching"]},
    {"headword": "noticing hypothesis", "pronunciation": "/ˈnəʊtɪsɪŋ haɪˈpɒθəsɪs/", "partOfSpeech": "noun", "definition": "The SLA theory stating that input cannot become linguistic intake unless consciously noticed by the learner.", "example": "According to the noticing hypothesis, color-coding past participles draws conscious attention to irregular forms.", "translation": "فرضية الملاحظة والوعي الواعي بالمدخلات اللغوية", "collocations": ["Schmidts noticing hypothesis", "support the noticing hypothesis"], "synonyms": ["conscious awareness hypothesis"], "antonyms": ["subliminal acquisition hypothesis"], "tags": ["linguistics", "acquisition"]},
    {"headword": "comprehensible input", "pronunciation": "/ˌkɒmprɪˈhensəbl ˈɪnpʊt/", "partOfSpeech": "noun", "definition": "Language input that can be understood by listeners despite containing words or grammar slightly above their level.", "example": "Stephen Krashen famously argued that comprehensible input is the single essential ingredient for second language acquisition.", "translation": "المدخلات اللغوية المفهومة (فرضية كراشن i+1)", "collocations": ["provide comprehensible input", "rich comprehensible input"], "synonyms": ["understandable input", "i+1"], "antonyms": ["incomprehensible noise"], "tags": ["acquisition", "pedagogy"]},
    {"headword": "output hypothesis", "pronunciation": "/ˈaʊtpʊt haɪˈpɒθəsɪs/", "partOfSpeech": "noun", "definition": "Merrill Swain's theory stating that producing spoken or written language pushes learners to process grammar deeply.", "example": "The output hypothesis explains why silent reading must be balanced with frequent conversational speaking practice.", "translation": "فرضية المخرجات اللغوية وضرورة الإنتاج الفعلي للغة", "collocations": ["Swains output hypothesis", "evidence for the output hypothesis"], "synonyms": ["pushed output theory"], "antonyms": ["input-only theory"], "tags": ["acquisition", "pedagogy"]},
    {"headword": "interaction hypothesis", "pronunciation": "/ˌɪntərˈækʃn haɪˈpɒθəsɪs/", "partOfSpeech": "noun", "definition": "The theory that second language proficiency is fostered through social interaction and active negotiation of meaning.", "example": "Long's interaction hypothesis demonstrates how conversational breakdowns push learners to refine their utterances.", "translation": "فرضية التفاعل الاجتماعي في اكتساب اللغة", "collocations": ["proponents of the interaction hypothesis", "Longs interaction hypothesis"], "synonyms": ["interactionist theory"], "antonyms": [], "tags": ["acquisition", "sociolinguistics"]},
    {"headword": "negotiation of meaning", "pronunciation": "/nɪˌɡəʊʃiˈeɪʃn əv ˈmiːnɪŋ/", "partOfSpeech": "noun", "definition": "The interactive process where speakers adjust their language through confirmation checks to resolve misunderstandings.", "example": "Active negotiation of meaning during paired tasks forces both students to clarify their lexical choices.", "translation": "التفاوض حول المعنى لتجاوز الغموض اللغوي", "collocations": ["engage in negotiation of meaning", "triggers for negotiation of meaning"], "synonyms": ["mutual meaning construction"], "antonyms": [], "tags": ["pedagogy", "pragmatics"]},
    {"headword": "language awareness", "pronunciation": "/ˈlæŋɡwɪdʒ əˈweənəs/", "partOfSpeech": "noun", "definition": "An explicit, conscious sensitivity to the forms, structures, and cultural subtleties of human language.", "example": "Developing deep language awareness enables translators to capture playful irony that machine tools miss.", "translation": "الوعي اللغوي الشامل بحساسيات النص ومستوياته", "collocations": ["foster language awareness", "heighten language awareness"], "synonyms": ["linguistic sensitivity"], "antonyms": ["linguistic blindness"], "tags": ["linguistics", "education"]},
    {"headword": "critical language study", "pronunciation": "/ˈkrɪtɪkl ˈlæŋɡwɪdʒ ˈstʌdi/", "partOfSpeech": "noun", "definition": "The academic examination of how language reflects, maintains, and challenges institutional power and social ideology.", "example": "In critical language study, scholars analyze how political rhetoric subtly manipulates public consent.", "translation": "الدراسة اللغوية النقدية وتحليل علاقات القوة والخطاب", "collocations": ["field of critical language study", "pursue critical language study"], "synonyms": ["critical discourse analysis", "CDA"], "antonyms": [], "tags": ["linguistics", "sociology"]},
    {"headword": "applied linguistics", "pronunciation": "/əˈplaɪd lɪŋˈɡwɪstɪks/", "partOfSpeech": "noun", "definition": "An interdisciplinary field of study that identifies, investigates, and offers solutions to language-related real-world problems.", "example": "Graduates in applied linguistics specialize in language teaching, bilingual education policy, and forensic speech analysis.", "translation": "اللسانيات واللغويات التطبيقية لحل مشكلات الواقع", "collocations": ["department of applied linguistics", "research in applied linguistics"], "synonyms": ["practical linguistics"], "antonyms": ["theoretical linguistics"], "tags": ["linguistics", "science"]},
    {"headword": "corpus-based learning", "pronunciation": "/ˈkɔːpəs beɪst ˈlɜːnɪŋ/", "partOfSpeech": "noun", "definition": "Using authentic databases of millions of real-world texts and transcripts to investigate real language use.", "example": "Corpus-based learning allows students to discover which prepositions authentic writers actually combine with adjectives.", "translation": "التعلم المستند إلى المعاجم والمدونات اللغوية الحاسوبية", "collocations": ["benefits of corpus-based learning", "conduct corpus-based learning"], "synonyms": ["corpus-informed learning"], "antonyms": ["intuition-based grammar"], "tags": ["linguistics", "data"]},
    {"headword": "authentic material", "pronunciation": "/ɔːˈθentɪk məˈtɪəriəl/", "partOfSpeech": "noun", "definition": "Real-world texts, podcasts, and video produced for native speakers rather than simplified for language learners.", "example": "Using authentic materials like podcast interviews and newspaper editorials bridges the gap to native fluency.", "translation": "المواد اللغوية الأصيلة المعدة للناطقين الأصليين", "collocations": ["expose to authentic material", "use authentic materials"], "synonyms": ["genuine realia"], "antonyms": ["graded reader", "simplified text"], "tags": ["pedagogy", "materials"]},
    {"headword": "language portfolio", "pronunciation": "/ˈlæŋɡwɪdʒ pɔːtˈfəʊliəʊ/", "partOfSpeech": "noun", "definition": "A structured personal collection of essays, voice recordings, and reflections documenting communicative progress.", "example": "Maintaining a European language portfolio provides tangible evidence of proficiency across academic semesters.", "translation": "ملف الإنجاز اللغوي لتوثيق تطور مهارات المتعلم", "collocations": ["compile a language portfolio", "European language portfolio"], "synonyms": ["learning portfolio"], "antonyms": [], "tags": ["assessment", "education"]},
    {"headword": "self-assessment rubric", "pronunciation": "/self əˈsesmənt ˈruːbrɪk/", "partOfSpeech": "noun", "definition": "A structured scoring guide enabling learners to evaluate their own speaking and writing against objective standards.", "example": "The self-assessment rubric helped students evaluate their discourse coherence before submitting final dissertations.", "translation": "معايير التقييم الذاتي المنضبطة للأداء اللغوي", "collocations": ["use a self-assessment rubric", "consult the self-assessment rubric"], "synonyms": ["self-scoring guide"], "antonyms": ["external grading"], "tags": ["assessment", "pedagogy"]}
]

grammar_80 = [
    {
        "title": "Review: Connectors, Clauses, Spoken Patterns",
        "explanation": "This culminating review brings together the core linguistic pillars of Stage 8 (Advanced Everyday English):\n\n1. Advanced Discourse Connectors:\n   Synthesize contrast (however, conversely, on the contrary, notwithstanding), addition (moreover, by extension, by the same token), and concession (with that said, that said) to create effortless thematic progression.\n\n2. Complex Clause Integration:\n   - Noun Clauses: 'What research indicates is that deliberate vocabulary study accelerates retention.'\n   - Participle Clauses: 'Having analyzed corpus-based learning data, the linguists revised their textbook.'\n   - Non-defining Relative Clauses: 'Task-based instruction, which emphasizes authentic communication, builds communicative fluency.'\n   - Mixed Conditionals: 'If the student had not practiced retrieval practice regularly, she would not exhibit such semantic precision today.'\n\n3. Stylistic & Register Fluidity:\n   Mastering the transition between formal academic prose (high lexical density, syntactic complexity) and spontaneous spoken discourse (situational ellipsis, invariant tags, responsive back-channeling).",
        "structures": [
            {"pattern": "Participle + Noun Clause: 'Having analyzed the corpus data, researchers discovered that multiword expressions dominate spoken fluency.'"},
            {"pattern": "Non-defining clause + Mixed Conditional: 'The noticing hypothesis, which emphasizes conscious attention, demonstrates why students would not have acquired fixed expressions without explicit instruction.'"},
            {"pattern": "Contrast connector + Spoken pattern: 'Notwithstanding the formal curriculum, casual spoken discourse relies heavily on situational ellipsis and response tokens.'"}
        ],
        "examples": [
            {
                "sentence": "Having cultivated register awareness, the bilingual author adapted his syntactic complexity to suit both formal journals and colloquial dialogue.",
                "arabic": "بعد أن نمّى وعيه بالسجلات اللغوية، طوّع الكاتب ثنائي اللغة تعقيده النحوي ليناسب كلاً من المجلات الأكاديمية الرسمية والحوار العامي.",
                "usesVocabulary": ["register awareness", "syntactic complexity"]
            },
            {
                "sentence": "Task-based instruction, which immerses learners in authentic materials, fosters remarkable communicative fluency and intercultural competence.",
                "arabic": "التعليم القائم على إنجاز المهام، والذي يغمر المتعلمين في مواد لغوية أصيلة، يعزز طلاقة تواصلية ملحوظة وكفاءة ثقافية تفاعلية.",
                "usesVocabulary": ["task-based instruction", "authentic material", "communicative fluency", "intercultural competence"]
            },
            {
                "sentence": "If the teacher had not integrated spaced practice and retrieval practice into the syllabus, students would struggle with semantic precision today.",
                "arabic": "لو لم يكن المعلم قد دمج الممارسة المتباعدة وممارسة الاسترجاع في المنهج، لكان الطلاب يعانون من نقص الدقة الدلالية اليوم.",
                "usesVocabulary": ["spaced practice", "retrieval practice", "semantic precision"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "Reviewing the language portfolio, several grammatical slips were noticed by the assessor.",
                "right": "Reviewing the language portfolio, the assessor noticed several grammatical slips.",
                "explanation": "Remember to avoid dangling participles. The subject performing the action ('the assessor') must immediately follow the participle clause."
            },
            {
                "wrong": "The corpus-based learning who researchers admire improves lexical chunks.",
                "right": "Corpus-based learning, which researchers admire, improves lexical chunk acquisition.",
                "explanation": "Use 'which' (not 'who') for non-human concepts, and enclose non-defining relative clauses in commas."
            }
        ]
    }
]

convs_80 = [
    {
        "title": "Applied Linguistics Colloquium: The Future of SLA",
        "titleArabic": "ندوة اللغويات التطبيقية: مستقبل اكتساب اللغة الثانية",
        "setting": "Two applied linguists review recent breakthroughs in second language acquisition research.",
        "lines": [
            {"speaker": "Dr. Aris", "text": "Having examined extensive corpus-based learning data, what do you consider the primary driver of communicative fluency?"},
            {"speaker": "Dr. Vance", "text": "According to the output hypothesis, learners must produce pushed language; however, Krashen's comprehensible input remains foundational."},
            {"speaker": "Dr. Aris", "text": "Schmidt's noticing hypothesis also shows that explicit instruction draws conscious focus to tricky phraseological units."},
            {"speaker": "Dr. Vance", "text": "Indeed. While incidental learning from authentic materials is valuable, deliberate vocabulary study accelerates productive knowledge."},
            {"speaker": "Dr. Aris", "text": "How can teachers prevent a fossilized error from taking root in a student's evolving interlanguage?"},
            {"speaker": "Dr. Vance", "text": "Through active negotiation of meaning and task-based instruction. The interaction hypothesis proves that collaborative tasks force repair."},
            {"speaker": "Dr. Aris", "text": "Integrating spaced practice and retrieval practice ensures that lexical chunks transition into long-term memory."},
            {"speaker": "Dr. Vance", "text": "Exactly. Combining that cognitive rigor with rich language awareness yields genuine pragmatic competence."}
        ],
        "vocabularyUsed": ["applied linguistics", "corpus-based learning", "communicative fluency", "output hypothesis", "comprehensible input", "noticing hypothesis", "explicit instruction", "phraseological unit", "incidental learning", "authentic material", "deliberate vocabulary study", "productive knowledge", "fossilized error", "interlanguage", "negotiation of meaning", "task-based instruction", "interaction hypothesis", "spaced practice", "retrieval practice", "lexical chunk", "language awareness", "pragmatic competence"]
    },
    {
        "title": "Academic Writing Mentorship: Lexical and Syntactic Refinement",
        "titleArabic": "إرشاد الكتابة الأكاديمية: الصقل المعجمي والتركيبي",
        "setting": "A graduate advisor coaches a PhD student on polishing her doctoral dissertation.",
        "lines": [
            {"speaker": "Advisor", "text": "Your literature review demonstrates admirable depth of processing and strong textual cohesion."},
            {"speaker": "PhD Student", "text": "Thank you. I practiced elaborative interrogation and the self-explanation technique to ensure each conceptual link was justified."},
            {"speaker": "Advisor", "text": "Notice, however, that your lexical density could be improved by replacing vague multiword expressions with precise academic collocations."},
            {"speaker": "PhD Student", "text": "I will consult our self-assessment rubric and analyze the worked examples you provided yesterday."},
            {"speaker": "Advisor", "text": "Furthermore, vary your syntactic complexity. Integrate participle clauses and cleft sentences to highlight critical findings."},
            {"speaker": "PhD Student", "text": "I noticed that negative language transfer occasionally influenced my preposition choices."},
            {"speaker": "Advisor", "text": "That is easily remedied. Maintaining a reflective language portfolio will sharpen your register awareness."},
            {"speaker": "PhD Student", "text": "I will apply these revisions immediately to achieve true academic distinction."}
        ],
        "vocabularyUsed": ["depth of processing", "textual cohesion", "elaborative interrogation", "self-explanation technique", "lexical density", "multiword expression", "collocational knowledge", "self-assessment rubric", "worked example", "syntactic complexity", "language transfer", "language portfolio", "register awareness"]
    },
    {
        "title": "Global Diplomacy Training: Cross-Cultural Competence",
        "titleArabic": "تدريب الدبلوماسية الدولية: الكفاءة عبر الثقافات",
        "setting": "A diplomatic academy trainer instructs foreign service candidates on cross-cultural negotiation.",
        "lines": [
            {"speaker": "Trainer", "text": "Effective diplomacy requires more than grammatical mastery; it demands deep intercultural competence and contextual appropriacy."},
            {"speaker": "Candidate", "text": "How do diplomats navigate sociolinguistic awareness when negotiating with high-context cultures?"},
            {"speaker": "Trainer", "text": "By mastering interactional competence and understanding how non-verbal cues alter pragmatic subtext."},
            {"speaker": "Candidate", "text": "In critical language study, we learned that discourse coherence often depends on implicit cultural assumptions."},
            {"speaker": "Trainer", "text": "Precisely. Problem-based learning simulations help candidates internalize both fixed expressions and semi-fixed expressions used in bilateral treaties."},
            {"speaker": "Candidate", "text": "Dual coding techniques have helped me memorize these multiword diplomatic formulas effectively."},
            {"speaker": "Trainer", "text": "Splendid. Achieving semantic precision while respecting cultural sensibilities is the hallmark of a world-class envoy."},
            {"speaker": "Candidate", "text": "Thank you, sir. I will continue refining my diplomatic language awareness."}
        ],
        "vocabularyUsed": ["intercultural competence", "contextual appropriacy", "sociolinguistic awareness", "cross-cultural communication", "interactional competence", "critical language study", "discourse coherence", "problem-based learning", "fixed expression", "semi-fixed expression", "dual coding", "semantic precision"]
    }
]

paras_80 = [
    {
        "title": "The Pillars of Advanced Linguistic Proficiency and Register Mastery",
        "titleArabic": "أركان الكفاءة اللغوية المتقدمة وإتقان السجلات التعبيرية",
        "text": "Attaining true mastery of the English language transcends memorizing isolated rules; it requires sophisticated register awareness and intuitive contextual appropriacy. Advanced communicators move effortlessly between the high lexical density, rigorous semantic precision, and rich syntactic complexity demanded by formal academic journals, and the relaxed cadence of spontaneous spoken discourse. By cultivating deep pragmatic competence, speakers decode implicit social subtext, irony, and conversational implicature with precision. Furthermore, maintaining disciplined textual cohesion and overarching discourse coherence ensures that multifaceted ideas flow logically across complex presentations. Ultimately, combining robust interactional competence with heightened sociolinguistic awareness empowers communicators to thrive across diverse global environments.",
        "vocabularyUsed": ["register awareness", "contextual appropriacy", "lexical density", "semantic precision", "syntactic complexity", "pragmatic competence", "textual cohesion", "discourse coherence", "interactional competence", "sociolinguistic awareness"]
    },
    {
        "title": "Second Language Acquisition: Theories, Input, and Output",
        "titleArabic": "اكتساب اللغة الثانية: النظريات، المدخلات، والمخرجات التفاعلية",
        "text": "The rich discipline of applied linguistics illuminates how adults acquire foreign languages with enduring native-like proficiency. According to Stephen Krashen, rich comprehensible input provides the essential foundation for natural acquisition, while Merrill Swain's output hypothesis proves that producing pushed language compels learners to process grammatical structures deeply. Concurrently, Schmidt's noticing hypothesis demonstrates that explicit instruction combined with corpus-based learning accelerates the internal organization of a student's evolving interlanguage. Through collaborative task-based instruction and lively problem-based learning, learners engage in continuous negotiation of meaning, eliminating persistent fossilized errors. Balancing authentic materials with deliberate vocabulary study ensures both receptive knowledge and productive knowledge flourish harmoniously.",
        "vocabularyUsed": ["applied linguistics", "comprehensible input", "output hypothesis", "noticing hypothesis", "explicit instruction", "corpus-based learning", "interlanguage", "task-based instruction", "problem-based learning", "negotiation of meaning", "fossilized error", "authentic material", "deliberate vocabulary study", "receptive knowledge", "productive knowledge"]
    },
    {
        "title": "Cognitive Strategies, Phraseology, and Lifelong Language Autonomy",
        "titleArabic": "الاستراتيجيات الإدراكية، علم العبارات، والاستقلالية اللغوية مدى الحياة",
        "text": "Achieving communicative fluency requires treating vocabulary not as isolated words, but as prefabricated lexical chunks, phraseological units, and collocational knowledge. Cognitive science reveals that employing spaced practice, deliberate retrieval practice, and dual coding dramatically amplifies depth of processing and long-term retention. When wrestling with challenging grammatical concepts, applying elaborative interrogation, the self-explanation technique, and analyzing a step-by-step worked example builds lasting confidence. Documenting communicative milestones within an evolving language portfolio while evaluating progress through a transparent self-assessment rubric fosters lifelong learning autonomy. Ultimately, heightening language awareness and pursuing critical language study empowers learners to navigate cross-cultural communication with profound intercultural competence.",
        "vocabularyUsed": ["communicative fluency", "lexical chunk", "phraseological unit", "collocational knowledge", "spaced practice", "retrieval practice", "dual coding", "depth of processing", "elaborative interrogation", "self-explanation technique", "worked example", "language portfolio", "self-assessment rubric", "language awareness", "critical language study", "cross-cultural communication", "intercultural competence"]
    }
]

if __name__ == "__main__":
    write_day(79, vocab_79, grammar_79, convs_79, paras_79)
    write_day(80, vocab_80, grammar_80, convs_80, paras_80)
    print("Day 79 and Day 80 generated successfully.")
