# -*- coding: utf-8 -*-
"""Builder for Day 61 and Day 62: Stage 7 (Problems, Decisions and Opinions)."""

import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts.curriculum_engine import write_day

# ==============================================================================
# DAY 61: Making Decisions (Choices and consequences)
# Grammar: ["Second Conditional"]
# ==============================================================================
vocab_61 = [
    # Weighing Options & Dilemmas (15)
    {"headword": "crossroads", "pronunciation": "/ˈkrɒsrəʊdz/", "partOfSpeech": "noun", "definition": "A critical point in life or decision-making where an important choice must be made.", "example": "If I stood at such a major career crossroads, I would consult trusted mentors before choosing.", "translation": "مفترق طرق / نقطة تحول حاسمة", "exampleArabic": "لو وقفت عند مفترق طرق مهني كهذا، لاستشرت مرشدين موثوقين قبل الاختيار.", "collocations": ["stand at a crossroads", "reach a crossroads"], "synonyms": ["turning point"], "antonyms": [], "tags": ["decisions", "choice"]},
    {"headword": "fork in the road", "pronunciation": "/fɔːk ɪn ðə rəʊd/", "partOfSpeech": "noun", "definition": "A point where two very different alternative courses of action diverge.", "example": "If our startup met a fork in the road, we would pivot toward enterprise software.", "translation": "مفترق مسارين / مفترق في الطريق", "exampleArabic": "لو واجهت شركتنا الناشئة مفترق مسارين، لتحولنا نحو برمجيات الشركات الكبرى.", "collocations": ["reach a fork in the road", "navigate a fork in the road"], "synonyms": ["divergence"], "antonyms": [], "tags": ["decisions", "idioms"]},
    {"headword": "weigh pros and cons", "pronunciation": "/weɪ prəʊz ənd kɒnz/", "partOfSpeech": "verb", "definition": "To carefully evaluate advantages and disadvantages before making a decision.", "example": "If she weighed the pros and cons logically, she would realize the relocation offers higher savings.", "translation": "يزن الإيجابيات والسلبيات", "exampleArabic": "لو وزنت الإيجابيات والسلبيات بمنطقية، لأدركت أن الانتقال يوفر مدخرات أعلى.", "verbForms": {"v1": "weigh pros and cons", "v2": "weighed pros and cons", "v3": "weighed pros and cons"}, "collocations": ["carefully weigh pros and cons", "stop and weigh pros and cons"], "synonyms": ["balance options"], "antonyms": [], "tags": ["decisions", "analysis"]},
    {"headword": "trade-off", "pronunciation": "/ˈtreɪd ɒf/", "partOfSpeech": "noun", "definition": "A balance achieved between two desirable but mutually incompatible features; a compromise.", "example": "If we accepted that demanding position, the difficult trade-off would be less weekend family time.", "translation": "مقايضة / تنازل متوازن", "exampleArabic": "لو قبلنا ذلك المنصب الشاق، لكانت المقايضة الصعبة قضاء وقت عائلي أقل في العطلات.", "collocations": ["difficult trade-off", "inevitable trade-off"], "synonyms": ["compromise"], "antonyms": [], "tags": ["decisions", "analysis"]},
    {"headword": "dealbreaker", "pronunciation": "/ˈdiːlbreɪkə/", "partOfSpeech": "noun", "definition": "A factor or issue that causes a negotiation, agreement, or relationship to fail.", "example": "If the employer refused remote work flexibility, that condition would become an absolute dealbreaker.", "translation": "عائق حاسم يلغي الاتفاق / شرط مفسخ", "exampleArabic": "لو رفض صاحب العمل مرونة العمل عن بُعد، لأصبح ذلك الشرط عائقاً حاسماً يلغي الاتفاق.", "collocations": ["potential dealbreaker", "ultimate dealbreaker"], "synonyms": ["non-negotiable"], "antonyms": [], "tags": ["decisions", "business"]},
    {"headword": "tipping point", "pronunciation": "/ˈtɪpɪŋ pɔɪnt/", "partOfSpeech": "noun", "definition": "The crisis stage or turning point in a situation at which a significant change takes place.", "example": "If product complaints crossed fifty a day, we would reach a catastrophic tipping point.", "translation": "نقطة التحول الحرجة / نقطة الحسم", "exampleArabic": "لو تجاوزت شكاوى المنتج خمسين شكوى يومياً، لوصلنا إلى نقطة تحول كارثية.", "collocations": ["reach a tipping point", "approach the tipping point"], "synonyms": ["critical threshold"], "antonyms": [], "tags": ["decisions", "events"]},
    {"headword": "decisive factor", "pronunciation": "/dɪˈsaɪsɪv ˈfæktə/", "partOfSpeech": "noun", "definition": "An element or circumstance that produces a definite result or determines an outcome.", "example": "If tuition costs were identical, campus research prestige would be the decisive factor.", "translation": "عامل حاسم / عنصر فاصل", "exampleArabic": "لو كانت تكاليف الرسوم الدراسية متطابقة، لكانت المكانة البحثية للحرم الجامعي هي العامل الحاسم.", "collocations": ["the decisive factor", "prove the decisive factor"], "synonyms": ["determining factor"], "antonyms": [], "tags": ["decisions", "logic"]},
    {"headword": "make up mind", "pronunciation": "/meɪk ʌp maɪnd/", "partOfSpeech": "verb", "definition": "To come to a definitive decision after doubt or hesitation.", "example": "If he made up his mind sooner, he would secure the discount airline seats.", "translation": "يحسم أمره / يتخذ قراره نهائياً", "exampleArabic": "لو حسم أمره مبكراً، لحجز مقاعد الطيران المخفضة.", "verbForms": {"v1": "make up mind", "v2": "made up mind", "v3": "made up mind"}, "collocations": ["finally make up mind", "struggle to make up mind"], "synonyms": ["decide firmly"], "antonyms": ["dither"], "tags": ["decisions", "idioms"]},
    {"headword": "ponder", "pronunciation": "/ˈpɒndə/", "partOfSpeech": "verb", "definition": "To think about something carefully and extensively, especially before reaching a conclusion.", "example": "If the architect pondered the zoning bylaws longer, she would design a safer parking structure.", "translation": "يتأمل بعمق / يتفكر بروية", "exampleArabic": "لو تأملت المهندسة المعمارية قوانين البناء بروية أطول، لصممت مبنى مواقف أكثر أماناً.", "verbForms": {"v1": "ponder", "v2": "pondered", "v3": "pondered"}, "collocations": ["ponder deeply", "ponder the question"], "synonyms": ["contemplate", "reflect upon"], "antonyms": [], "tags": ["thinking", "actions"]},
    {"headword": "deliberate carefully", "pronunciation": "/dɪˈlɪbəreɪt ˈkeəfəli/", "partOfSpeech": "verb", "definition": "To engage in long and careful consideration of serious issues.", "example": "If the hiring jury deliberated carefully, they would select the candidate with practical leadership skills.", "translation": "يتداول بتأنٍّ / يتشاور بحرص", "exampleArabic": "لو تداولت لجنة التوظيف بحرص، لاختارت المرشح ذا المهارات القيادية العملية.", "verbForms": {"v1": "deliberate carefully", "v2": "deliberated carefully", "v3": "deliberated carefully"}, "collocations": ["need to deliberate carefully", "deliberate carefully before voting"], "synonyms": ["consult thoroughly"], "antonyms": [], "tags": ["decisions", "thinking"]},
    {"headword": "second-guess", "pronunciation": "/ˈsekənd ɡes/", "partOfSpeech": "verb", "definition": "To anticipate, question, or criticize someone's actions or one's own decisions with hindsight.", "example": "If you second-guessed every small initiative, you would never launch any innovative feature.", "translation": "يشكك في قراره بأثر رجعي / يتردد بعد الحسم", "exampleArabic": "لو شككت في كل مبادرة صغيرة بأثر رجعي، فلن تطلق أي ميزة مبتكرة على الإطلاق.", "verbForms": {"v1": "second-guess", "v2": "second-guessed", "v3": "second-guessed"}, "collocations": ["constantly second-guess", "stop second-guessing yourself"], "synonyms": ["doubt post hoc"], "antonyms": ["trust intuition"], "tags": ["decisions", "thinking"]},
    {"headword": "gut feeling", "pronunciation": "/ɡʌt ˈfiːlɪŋ/", "partOfSpeech": "noun", "definition": "An instinctive feeling as opposed to an opinion based on logical thought.", "example": "If my gut feeling warned me against the investment, I would heed it instantly.", "translation": "شعور حدسي / إحساس داخلي", "exampleArabic": "لو حذرني شعوري الحدسي من الاستثمار، لاستمعت إليه على الفور.", "collocations": ["trust one's gut feeling", "strong gut feeling"], "synonyms": ["intuition", "instinct"], "antonyms": ["rational deduction"], "tags": ["intuition", "psychology"]},
    {"headword": "rational choice", "pronunciation": "/ˈræʃnəl tʃɔɪs/", "partOfSpeech": "noun", "definition": "A decision based on logical facts, cost balancing, and objective reasoning.", "example": "If investors made a rational choice, they would diversify capital across uncorrelated asset classes.", "translation": "خيار عقلاني / قرار رشيد", "exampleArabic": "لو اتخذ المستثمرون خياراً عقلانياً، لوزعوا رؤوس أموالهم عبر فئات أصول غير مترابطة.", "collocations": ["make a rational choice", "governed by rational choice"], "synonyms": ["sensible decision"], "antonyms": ["impulsive whim"], "tags": ["logic", "decisions"]},
    {"headword": "unintended consequence", "pronunciation": "/ˌʌnɪnˈtendɪd ˈkɒnsɪkwəns/", "partOfSpeech": "noun", "definition": "An unforeseen result that emerges from a purposeful action.", "example": "If the municipality raised parking fines too high, an unintended consequence would be empty downtown shops.", "translation": "نتيجة غير مقصودة / عاقبة غير محسوبة", "exampleArabic": "لو رفعت البلدية غرامات المواقف كثيراً، لكانت النتيجة غير المقصودة فراغ المتاجر بوسط المدينة.", "collocations": ["suffer unintended consequences", "foresee unintended consequences"], "synonyms": ["unexpected fallout"], "antonyms": ["intended objective"], "tags": ["outcomes", "analysis"]},
    {"headword": "judgment call", "pronunciation": "/ˈdʒʌdʒmənt kɔːl/", "partOfSpeech": "noun", "definition": "A subjective decision made on the basis of one's personal discretion rather than hard rules.", "example": "If the referee made that difficult judgment call, both teams would respect his authority.", "translation": "تقدير شخصي / قرار خاضع للاجتهاد", "exampleArabic": "لو اتخذ الحكم ذلك التقدير الشخصي الصعب، لاحترم كلا الفريقين سلطته.", "collocations": ["make a judgment call", "tough judgment call"], "synonyms": ["discretionary decision"], "antonyms": ["rule-bound mandate"], "tags": ["decisions", "discretion"]},

    # Decisiveness vs Hesitation (15)
    {"headword": "split-second decision", "pronunciation": "/ˌsplɪt ˈsekənd dɪˈsɪʒn/", "partOfSpeech": "noun", "definition": "A decision arrived at in a tiny fraction of time, often under emergency pressure.", "example": "If the airline pilot faced sudden engine failure, a split-second decision would save all passengers.", "translation": "قرار لحظي خاطف / قرار في جزء من الثانية", "exampleArabic": "لو واجه قائد الطائرة عطلاً مفاجئاً في المحرك، لأنقذ قرار لحظي خاطف جميع الركاب.", "collocations": ["require a split-second decision", "make a split-second decision"], "synonyms": ["instant decision"], "antonyms": ["protracted deliberation"], "tags": ["urgency", "decisions"]},
    {"headword": "hesitation", "pronunciation": "/ˌhezɪˈteɪʃn/", "partOfSpeech": "noun", "definition": "The action of pausing before saying or doing something due to uncertainty.", "example": "If you acted without hesitation during the interview, you would project powerful confidence.", "translation": "تردد / إحجام مؤقت", "exampleArabic": "لو تصرفت دون تردد أثناء المقابلة، لأظهرت ثقة قوية بنفسك.", "collocations": ["without hesitation", "brief hesitation"], "synonyms": ["vacillation", "pause"], "antonyms": ["promptness"], "tags": ["psychology", "actions"]},
    {"headword": "vacillate", "pronunciation": "/ˈvæsəleɪt/", "partOfSpeech": "verb", "definition": "To alternate or waver between different opinions or actions; to be indecisive.", "example": "If the cabinet minister vacillated further, public confidence in economic reform would dwindle.", "translation": "يتذبذب / يتردد بين أمرين", "exampleArabic": "لو تذبذب الوزير أكثر، لتضاءلت ثقة الجمهور في الإصلاح الاقتصادي.", "verbForms": {"v1": "vacillate", "v2": "vacillated", "v3": "vacillated"}, "collocations": ["vacillate between two views", "tend to vacillate"], "synonyms": ["fluctuate", "waver"], "antonyms": ["resolve firmly"], "tags": ["indecision", "actions"]},
    {"headword": "waver", "pronunciation": "/ˈweɪvə/", "partOfSpeech": "verb", "definition": "To become unsteady or falter in resolution, purpose, or conviction.", "example": "If our resolve wavered under market volatility, we would miss the seasonal recovery.", "translation": "يتزعزع / يترنح في عزمه", "exampleArabic": "لو تزعزعت عزيمتنا تحت وطأة تقلبات السوق، لفاتنا التعافي الموسمي.", "verbForms": {"v1": "waver", "v2": "wavered", "v3": "wavered"}, "collocations": ["never waver", "waver in determination"], "synonyms": ["falter", "hesitate"], "antonyms": ["persevere"], "tags": ["resolution", "actions"]},
    {"headword": "snap judgment", "pronunciation": "/snæp ˈdʒʌdʒmənt/", "partOfSpeech": "noun", "definition": "A rushed conclusion made quickly without taking time to consider all relevant facts.", "example": "If managers avoided snap judgments, they would evaluate candidate portfolios more fairly.", "translation": "حكم متعجل متسرع", "exampleArabic": "لو تجنب المديرون الأحكام المتعجلة، لقاموا بتقييم ملفات المرشحين بعدالة أكبر.", "collocations": ["avoid snap judgments", "make a snap judgment"], "synonyms": ["hasty conclusion"], "antonyms": ["deliberate assessment"], "tags": ["biases", "decisions"]},
    {"headword": "informed choice", "pronunciation": "/ɪnˈfɔːmd tʃɔɪs/", "partOfSpeech": "noun", "definition": "A decision made after acquiring full facts, risks, and pertinent insights.", "example": "If citizens reviewed municipal balance sheets, they would make an informed choice at elections.", "translation": "خيار مستنير / قرار عن معرفة وبينة", "exampleArabic": "لو اطلع المواطنون على الميزانيات العمومية للبلدية، لاتخذوا خياراً مستنيراً في الانتخابات.", "collocations": ["make an informed choice", "promote informed choice"], "synonyms": ["educated decision"], "antonyms": ["blind guess"], "tags": ["knowledge", "decisions"]},
    {"headword": "cost-benefit analysis", "pronunciation": "/ˌkɒst ˈbenɪfɪt əˈnæləsɪs/", "partOfSpeech": "noun", "definition": "A systematic approach to estimating the strengths and weaknesses of alternatives.", "example": "If the council conducted a rigorous cost-benefit analysis, they would build a rapid tramline.", "translation": "تحليل الجدوى والتكلفة مقابل العائد", "exampleArabic": "لو أجرى المجلس تحليلاً دقيقاً للتكلفة مقابل العائد، لبنوا خط ترام سريعاً.", "collocations": ["conduct a cost-benefit analysis", "favorable cost-benefit analysis"], "synonyms": ["economic evaluation"], "antonyms": [], "tags": ["business", "finance"]},
    {"headword": "irrevocable decision", "pronunciation": "/ɪˈrevəkəbl dɪˈsɪʒn/", "partOfSpeech": "noun", "definition": "A binding determination that cannot be undone, altered, or recalled.", "example": "If you resigned your tenured university professorship, it would be an irrevocable decision.", "translation": "قرار لا رجعة فيه / حسم نهائي بات", "exampleArabic": "لو استقلت من منصب أستاذ الجامعة الدائم، لكان ذلك قراراً لا رجعة فيه.", "collocations": ["make an irrevocable decision", "face an irrevocable decision"], "synonyms": ["permanent commitment"], "antonyms": ["tentative trial"], "tags": ["permanence", "decisions"]},
    {"headword": "point of no return", "pronunciation": "/ˌpɔɪnt əv nəʊ rɪˈtɜːn/", "partOfSpeech": "noun", "definition": "The stage in an action beyond which it is impossible to alter or stop the course.", "example": "If the spacecraft passed the lunar gravitational threshold, it would cross the point of no return.", "translation": "نقطة اللاعودة", "exampleArabic": "لو تجاوزت المركبة الفضائية عتبة الجاذبية القمرية، لاجتازت نقطة اللاعودة.", "collocations": ["cross the point of no return", "reach the point of no return"], "synonyms": ["watershed threshold"], "antonyms": [], "tags": ["critical", "events"]},
    {"headword": "calculated risk", "pronunciation": "/ˈkælkjuleɪtɪd rɪsk/", "partOfSpeech": "noun", "definition": "A hazard undertaken after careful estimation of the probable odds of success.", "example": "If our venture took that calculated risk, the market share payoff would be enormous.", "translation": "مخاطرة مدروسة ومحسوبة", "exampleArabic": "لو أقدم مشروعنا على تلك المخاطرة المحسوبة، لكان عائد الحصة السوقية هائلاً.", "collocations": ["take a calculated risk", "worth a calculated risk"], "synonyms": ["measured venture"], "antonyms": ["reckless gamble"], "tags": ["risk", "business"]},
    {"headword": "hedging bets", "pronunciation": "/ˈhedʒɪŋ bets/", "partOfSpeech": "noun", "definition": "Protecting oneself against loss by supporting more than one option or course.", "example": "If treasury managers avoided hedging bets with gold futures, their portfolios would suffer inflation shocks.", "translation": "التحوط لتقليل الخسائر / توزيع الرهانات", "exampleArabic": "لو تجنب مديرو الخزينة التحوط بعقود الذهب الآجلة، لعانت محافظهم من صدمات التضخم.", "collocations": ["practice hedging bets", "strategy of hedging bets"], "synonyms": ["risk mitigation"], "antonyms": ["going all-in"], "tags": ["finance", "strategy"]},
    {"headword": "sound judgment", "pronunciation": "/saʊnd ˈdʒʌdʒmənt/", "partOfSpeech": "noun", "definition": "The capacity to assess situations wisely, fairly, and draw practical conclusions.", "example": "If the managing director demonstrated sound judgment, the boardroom feud would dissolve quickly.", "translation": "رجاحة عقل / حكم صائب وسديد", "exampleArabic": "لو أظهر المدير التنفيذي رجاحة عقل، لتبدد الخلاف في مجلس الإدارة سريعاً.", "collocations": ["exercise sound judgment", "rely on sound judgment"], "synonyms": ["wisdom", "discernment"], "antonyms": ["poor judgment"], "tags": ["wisdom", "competence"]},
    {"headword": "indecisive", "pronunciation": "/ˌɪndɪˈsaɪsɪv/", "partOfSpeech": "adjective", "definition": "Not having or showing the ability to make decisions quickly and effectively.", "example": "If the incident commander were indecisive during emergencies, rescue operations would fail.", "translation": "متردد / عاجز عن الحسم", "exampleArabic": "لو كان قائد الحادث متردداً أثناء الطوارئ، لفشلت عمليات الإنقاذ.", "collocations": ["appear indecisive", "hopelessly indecisive"], "synonyms": ["irresolute"], "antonyms": ["decisive"], "tags": ["character", "behavior"]},
    {"headword": "dither", "pronunciation": "/ˈdɪðə/", "partOfSpeech": "verb", "definition": "To be indecisive and hesitate repeatedly over trivial or major choices.", "example": "If buyers dithered over property listings, competitive bidders would snatch the houses.", "translation": "يتلكأ متردداً / يماطل في اتخاذ القرار", "exampleArabic": "لو تلكأ المشترون مترددين بشأن العقارات المعروضة، لاقتنص المنافسون المنازل.", "verbForms": {"v1": "dither", "v2": "dithered", "v3": "dithered"}, "collocations": ["dither around", "stop dithering"], "synonyms": ["faff around", "shilly-shally"], "antonyms": ["act immediately"], "tags": ["actions", "indecision"]},
    {"headword": "buyers remorse", "pronunciation": "/ˌbaɪəz rɪˈmɔːs/", "partOfSpeech": "noun", "definition": "A sense of regret after having made a substantial or expensive purchase.", "example": "If you spent half your savings on that sports car, you would endure acute buyers remorse.", "translation": "ندم المشتري بعد الشراء", "exampleArabic": "لو أنفقت نصف مدخراتك على تلك السيارة الرياضية، لعانيت من ندم المشتري الشديد.", "collocations": ["experience buyers remorse", "suffer from buyers remorse"], "synonyms": ["post-purchase regret"], "antonyms": ["purchaser satisfaction"], "tags": ["psychology", "consumerism"]},

    # Taking Stances & Consequences (20)
    {"headword": "opt out", "pronunciation": "/ɒpt aʊt/", "partOfSpeech": "verb", "definition": "To choose not to participate in or belong to an established arrangement.", "example": "If employees opted out of the pension scheme, they would lose generous matching contributions.", "translation": "ينسحب باختياره / يفضل عدم المشاركة", "exampleArabic": "لو انسحب الموظفون باختيارهم من برنامج التقاعد، لفقدوا مساهمات أصحاب العمل السخية.", "verbForms": {"v1": "opt out", "v2": "opted out", "v3": "opted out"}, "collocations": ["opt out of program", "right to opt out"], "synonyms": ["withdraw", "decline"], "antonyms": ["opt in"], "tags": ["actions", "choice"]},
    {"headword": "stand by decision", "pronunciation": "/stænd baɪ dɪˈsɪʒn/", "partOfSpeech": "verb", "definition": "To remain faithful to and uphold a previous choice despite fierce pushback.", "example": "If the committee stood by their decision, historical architectural landmarks would remain protected.", "translation": "يتمسك بقراره / يثبت على موقفه", "exampleArabic": "لو تمسكت اللجنة بقرارها، لظلت المعالم المعمارية التاريخية محمية.", "verbForms": {"v1": "stand by decision", "v2": "stood by decision", "v3": "stood by decision"}, "collocations": ["firmly stand by decision", "courage to stand by decision"], "synonyms": ["uphold choice"], "antonyms": ["revoke choice"], "tags": ["commitment", "actions"]},
    {"headword": "reap consequences", "pronunciation": "/riːp ˈkɒnsɪkwənsɪz/", "partOfSpeech": "verb", "definition": "To experience the positive or negative outcomes of previous choices.", "example": "If students studied rigorously every week, they would reap the consequences in top-tier test scores.", "translation": "يجني العواقب / يحصد ثمار ما فعل", "exampleArabic": "لو اجتهد الطلاب بدقة كل أسبوع، لحصدوا ثمار ذلك في درجات اختبار ممتازة.", "verbForms": {"v1": "reap consequences", "v2": "reaped consequences", "v3": "reaped consequences"}, "collocations": ["reap the consequences of actions", "inevitably reap consequences"], "synonyms": ["bear the results"], "antonyms": [], "tags": ["outcomes", "actions"]},
    {"headword": "face the music", "pronunciation": "/feɪs ðə ˈmjuːzɪk/", "partOfSpeech": "verb", "definition": "To accept the unpleasant consequences of one's own past actions without evasion.", "example": "If the treasurer admitted the accounting ledger discrepancy, he would have to face the music.", "translation": "يواجه العواقب بشجاعة / يتحمل مسؤولية أخطائه", "exampleArabic": "لو اعترف أمين الصندوق بالتفاوت في دفاتر المحاسبة، لتوجب عليه مواجهة العواقب بشجاعة.", "verbForms": {"v1": "face the music", "v2": "faced the music", "v3": "faced the music"}, "collocations": ["ready to face the music", "compelled to face the music"], "synonyms": ["accept retribution"], "antonyms": ["shirk responsibility"], "tags": ["accountability", "idioms"]},
    {"headword": "rule of thumb", "pronunciation": "/ˌruːl əv ˈθʌm/", "partOfSpeech": "noun", "definition": "A broadly accurate guideline or practical principle based on experience rather than theory.", "example": "If junior coders applied this rule of thumb, their database queries would run twice as fast.", "translation": "قاعدة عملية تجريبية / معيار استرشادي عام", "exampleArabic": "لو طبق المبرمجون المبتدئون هذه القاعدة العملية، لعملت استعلامات قواعد بياناتهم بضعف السرعة.", "collocations": ["useful rule of thumb", "general rule of thumb"], "synonyms": ["practical guideline"], "antonyms": ["strict formula"], "tags": ["practical", "guidelines"]},
    {"headword": "flip a coin", "pronunciation": "/flɪp ə kɔɪn/", "partOfSpeech": "verb", "definition": "To decide between two equally matched alternatives by tossing a metal coin.", "example": "If we flipped a coin to settle the debate, neither participant would feel satisfied.", "translation": "يُلقي قرعة بالعملة المعدنية", "exampleArabic": "لو ألقينا قرعة بالعملة المعدنية لحسم النقاش، لما شعر أي من الطرفين بالرضا.", "verbForms": {"v1": "flip a coin", "v2": "flipped a coin", "v3": "flipped a coin"}, "collocations": ["flip a coin to decide", "resolve by flipping a coin"], "synonyms": ["toss a coin"], "antonyms": [], "tags": ["chance", "actions"]},
    {"headword": "gamut of choices", "pronunciation": "/ˈɡæmət əv ˈtʃɔɪsɪz/", "partOfSpeech": "noun", "definition": "The complete range or full spectrum of available options.", "example": "If travelers surveyed the gamut of choices, they would discover hidden mountain eco-lodges.", "translation": "طيف الخيارات الكامل / مجمل البدائل المتاحة", "exampleArabic": "لو استطلع المسافرون طيف الخيارات الكامل، لاكتشفوا نزلاً جبلية بيئية خفية.", "collocations": ["run the gamut of choices", "wide gamut of choices"], "synonyms": ["entire spectrum"], "antonyms": ["singular alternative"], "tags": ["options", "variety"]},
    {"headword": "deliberation", "pronunciation": "/dɪˌlɪbəˈreɪʃn/", "partOfSpeech": "noun", "definition": "Long and careful consideration or discussion of crucial points.", "example": "If the jury concluded their deliberation today, the historic trial would reach closure.", "translation": "مداولة / تشاور متأنٍّ", "exampleArabic": "لو اختتمت هيئة المحلفين مداولاتها اليوم، لوصلت المحاكمة التاريخية إلى نهايتها.", "collocations": ["after mature deliberation", "lengthy deliberation"], "synonyms": ["deep thought", "consultation"], "antonyms": ["impulsiveness"], "tags": ["thinking", "formal"]},
    {"headword": "contingency option", "pronunciation": "/kənˈtɪndʒənsi ˈɒpʃn/", "partOfSpeech": "noun", "definition": "A backup plan designed to be implemented if an unforeseen event occurs.", "example": "If sea shipments faced port blockages, our contingency option would route goods by rail.", "translation": "خيار طوارئ بديل / خطة احترازية", "exampleArabic": "لو واجهت الشحنات البحرية إغلاقات للموانئ، لوجه خيار الطوارئ البديل البضائع عبر السكك الحديدية.", "collocations": ["activate a contingency option", "rely on contingency options"], "synonyms": ["plan B", "fallback plan"], "antonyms": [], "tags": ["planning", "risk"]},
    {"headword": "arbitrary choice", "pronunciation": "/ˈɑːbɪtrəri tʃɔɪs/", "partOfSpeech": "noun", "definition": "A selection based on random whim or personal preference rather than reason or system.", "example": "If managers made an arbitrary choice, team morale would plummet swiftly.", "translation": "خيار عشوائي / قرار تعسفي أو اعتباطي", "exampleArabic": "لو اتخذ المديرون خياراً عشوائياً اعتباطياً، لانهارت الروح المعنوية للفريق سريعاً.", "collocations": ["avoid arbitrary choices", "seem an arbitrary choice"], "synonyms": ["whimsical decision"], "antonyms": ["principled choice"], "tags": ["bias", "decisions"]},
    {"headword": "compelling reason", "pronunciation": "/kəmˈpelɪŋ ˈriːzn/", "partOfSpeech": "noun", "definition": "A justification so convincing that it demands agreement or definitive action.", "example": "If there were a compelling reason to upgrade hardware, the board would approve funds.", "translation": "سبب وجيه ومقنع / مبرر قاطع", "exampleArabic": "لو كان هناك سبب وجيه ومقنع لتحديث الأجهزة، لوافق مجلس الإدارة على التمويل.", "collocations": ["give a compelling reason", "compelling reason to change"], "synonyms": ["persuasive justification"], "antonyms": ["flimsy excuse"], "tags": ["logic", "persuasion"]},
    {"headword": "overriding factor", "pronunciation": "/ˌəʊvəˈraɪdɪŋ ˈfæktə/", "partOfSpeech": "noun", "definition": "A primary element that takes precedence over all other considerations.", "example": "If passenger safety remained the overriding factor, the flight would stay grounded until storm winds calmed.", "translation": "عامل مهيمن يفوق ما سواه / اعتبار أسمى", "exampleArabic": "لو ظلت سلامة الركاب هي العامل الأسمى المهيمن، لبقيت الرحلة على الأرض حتى تهدأ رياح العاصفة.", "collocations": ["become the overriding factor", "primary overriding factor"], "synonyms": ["dominant consideration"], "antonyms": ["negligible detail"], "tags": ["priority", "decisions"]},
    {"headword": "decisiveness", "pronunciation": "/dɪˈsaɪsɪvnəs/", "partOfSpeech": "noun", "definition": "The ability to make decisions quickly, confidently, and firmly.", "example": "If the CEO demonstrated greater decisiveness, investor panics would cease.", "translation": "حسم / حزم وقدرة على اتخاذ القرار", "exampleArabic": "لو أظهر الرئيس التنفيذي قدراً أكبر من الحسم، لتوقفت مخاوف المستثمرين.", "collocations": ["act with decisiveness", "admirable decisiveness"], "synonyms": ["firmness", "resolution"], "antonyms": ["indecisiveness"], "tags": ["leadership", "competence"]},
    {"headword": "agonize over", "pronunciation": "/ˈæɡənaɪz ˈəʊvə/", "partOfSpeech": "verb", "definition": "To worry excessively and painfully about a complex decision.", "example": "If he agonized over every career step, he would suffer chronic emotional exhaustion.", "translation": "يتعذب قلقاً بسبب القرار / يتجرع الحيرة", "exampleArabic": "لو تعذب قلقاً بشأن كل خطوة مهنية، لعانى من إرهاق عاطفي مزمن.", "verbForms": {"v1": "agonize over", "v2": "agonized over", "v3": "agonized over"}, "collocations": ["agonize over decision", "no need to agonize over"], "synonyms": ["fret painfully"], "antonyms": ["decide calmly"], "tags": ["psychology", "actions"]},
    {"headword": "pro and con", "pronunciation": "/prəʊ ənd kɒn/", "partOfSpeech": "noun", "definition": "An argument or factor in favor of (pro) or against (con) a proposition.", "example": "If we scrutinized every pro and con, we would identify the contract loopholes.", "translation": "إيجابية وسلبية / حجة مؤيدة ومعارضة", "exampleArabic": "لو فحصنا بدقة كل إيجابية وسلبية، لاكتشفنا الثغرات في العقد.", "collocations": ["assess each pro and con", "balance pro and con"], "synonyms": ["advantage and disadvantage"], "antonyms": [], "tags": ["analysis", "debate"]},
    {"headword": "steer clear of", "pronunciation": "/stɪə klɪər əv/", "partOfSpeech": "verb", "definition": "To deliberately avoid a hazardous person, choice, or circumstance.", "example": "If prudent consumers steered clear of predatory loans, household debt would shrink.", "translation": "يبتعد عن / يتجنب بحذر", "exampleArabic": "لو تجنب المستهلكون الحكماء القروض الجائرة، لانكمشت ديون الأسر.", "verbForms": {"v1": "steer clear of", "v2": "steered clear of", "v3": "steered clear of"}, "collocations": ["steer clear of trouble", "wise to steer clear of"], "synonyms": ["avoid deliberately"], "antonyms": ["gravitate toward"], "tags": ["precaution", "actions"]},
    {"headword": "take the plunge", "pronunciation": "/teɪk ðə plʌndʒ/", "partOfSpeech": "verb", "definition": "To commit oneself resolutely to a momentous or risky course of action.", "example": "If she took the plunge and started her organic bakery, locals would flock to it.", "translation": "يُقدم على الخطوة الجريئة / يخوض التجربة بشجاعة", "exampleArabic": "لو أقدمت على تلك الخطوة الجريئة وأنشأت مخبزها العضوي، لتوافد عليها سكان الحي.", "verbForms": {"v1": "take the plunge", "v2": "took the plunge", "v3": "taken the plunge"}, "collocations": ["ready to take the plunge", "finally take the plunge"], "synonyms": ["make bold leap"], "antonyms": ["hold back"], "tags": ["courage", "idioms"]},
    {"headword": "sleep on it", "pronunciation": "/sliːp ɒn ɪt/", "partOfSpeech": "verb", "definition": "To delay making a decision until the following day to allow for calmer reflection.", "example": "If you slept on it before signing the mortgage, you would feel calmer tomorrow.", "translation": "يتمهل لليوم التالي قبل حسم القرار", "exampleArabic": "لو تمهلت ونمت ليلة قبل توقيع عقد الرهن العقاري، لشعرت بمزيد من الهدوء غداً.", "verbForms": {"v1": "sleep on it", "v2": "slept on it", "v3": "slept on it"}, "collocations": ["prefer to sleep on it", "promise to sleep on it"], "synonyms": ["defer decision overnight"], "antonyms": ["rush headlong"], "tags": ["patience", "idioms"]},
    {"headword": "mull over", "pronunciation": "/mʌl ˈəʊvə/", "partOfSpeech": "verb", "definition": "To think about a proposal, offer, or dilemma deeply over an extended period.", "example": "If the committee mulled over the budget draft, they would find surplus capital.", "translation": "يقلّب الأمر في ذهنه بروية", "exampleArabic": "لو قلبت اللجنة مسودة الميزانية في ذهنها بروية، لوجدت فائضاً في رأس المال.", "verbForms": {"v1": "mull over", "v2": "mulled over", "v3": "mulled over"}, "collocations": ["mull over an offer", "time to mull over"], "synonyms": ["chew over", "ponder"], "antonyms": ["dismiss instantly"], "tags": ["thinking", "actions"]},
    {"headword": "call the shots", "pronunciation": "/kɔːl ðə ʃɒts/", "partOfSpeech": "verb", "definition": "To be in the position of authority, determining policies, actions, and orders.", "example": "If you called the shots in this division, what structural improvements would you execute?", "translation": "يمسك بزمام الأمور / يقرر الأوامر والسياسات", "exampleArabic": "لو كنت أنت من يمسك بزمام الأمور في هذا القسم، فما التحسينات الهيكلية التي ستنفذها؟", "verbForms": {"v1": "call the shots", "v2": "called the shots", "v3": "called the shots"}, "collocations": ["who calls the shots", "earn right to call the shots"], "synonyms": ["be in charge"], "antonyms": ["obey orders"], "tags": ["authority", "idioms"]}
]

grammar_61 = [
    {
        "title": "Second Conditional",
        "titleArabic": "الحالة الشرطية الثانية (Second Conditional)",
        "explanation": "We use the Second Conditional to talk about hypothetical, imaginary, or improbable situations in the present or future, and their imagined consequences. The 'if' clause uses the Past Simple (expressing distance from reality, not past time), and the main clause uses 'would / wouldn't + base verb' (or 'could / might' for possibility). Note: In formal English, we use 'were' instead of 'was' for all persons in the if-clause ('If I were you...', 'If he were here...').",
        "explanationArabic": "نستخدم الحالة الشرطية الثانية للحديث عن مواقف افتراضية أو خيالية أو غير محتملة الوقوع في الحاضر أو المستقبل، والنتائج المترتبة عليها: تتكون جملة الشرط (If-clause) من زمن الماضي البسيط Past Simple (وهو ماضٍ افتراضي يدل على البعد عن الواقع وليس زمناً ماضياً)، وتتكون جملة جواب الشرط من 'would + المصدر' (أو could / might للتعبير عن القدرة أو الاحتمال). ملاحظة أسلوبية: في اللغة الدقيقة والرسمية، يُفضل استخدام 'were' مع جميع الضمائر في جملة الشرط ('If I were you...', 'If she were here...').",
        "structures": [
            {"label": "Standard Second Conditional · الصيغة القياسية", "pattern": "If + Subject + Past Simple, Subject + would + Base Verb", "explanation": "Used for imagined situations and their hypothetical outcomes.", "explanationArabic": "تُستخدم للمواقف التخيلية ونتائجها الافتراضية."},
            {"label": "Giving Advice with Were · تقديم النصيحة الافتراضية", "pattern": "If I were you, I would + Base Verb", "explanation": "The standard English idiom for putting oneself in someone else's place to advise.", "explanationArabic": "الأسلوب القياسي لتقديم النصيحة بوضع المتحدث نفسه مكان الطرف الآخر."},
            {"label": "Possibility / Ability in Outcome · الاحتمال والقدرة في الجواب", "pattern": "If + Subject + Past Simple, Subject + could / might + Base Verb", "explanation": "Expresses that the imaginary outcome is possible rather than guaranteed.", "explanationArabic": "يدل على أن النتيجة التخيلية محتملة أو ممكنة وليست مؤكدة."}
        ],
        "examples": [
            {"sentence": "If I stood at a major career crossroads, I would weigh the pros and cons meticulously.", "translation": "لو وقفت عند مفترق طرق مهني حاسم، لوزنت الإيجابيات والسلبيات بكل دقة.", "usesVocabulary": ["crossroads", "weigh pros and cons"]},
            {"sentence": "If our leadership exercised sound judgment, they wouldn't rush into an arbitrary choice.", "translation": "لو مارست قيادتنا حكماً سديداً، لما اندفعت نحو خيار عشوائي اعتباطي.", "usesVocabulary": ["sound judgment", "arbitrary choice"]},
            {"sentence": "If you took that calculated risk, an unintended consequence might complicate logistics.", "translation": "لو أقدمت على تلك المخاطرة المحسوبة، فقد تُعقد نتيجة غير محسوبة العمليات اللوجستية.", "usesVocabulary": ["calculated risk", "unintended consequence"]},
            {"sentence": "If she were in charge, she would call the shots and establish a clear rule of thumb.", "translation": "لو كانت هي المسؤولة، لأمسكت بزمام الأمور ووضعت قاعدة عملية واضحة.", "usesVocabulary": ["call the shots", "rule of thumb"]}
        ],
        "commonMistakes": [
            {"wrong": "If I would have more money, I would invest in startups.", "right": "If I had more money, I would invest in startups.", "note": "Never use 'would' in the 'if' clause of a conditional sentence.", "noteArabic": "لا تضع 'would' في جملة الشرط (if-clause) إطلاقاً."},
            {"wrong": "If he was the president, he will change the tax law.", "right": "If he were the president, he would change the tax law.", "note": "Match past subjunctive in if-clause with 'would' in main clause, not 'will'. Use 'were' for formal hypothetical condition.", "noteArabic": "طابق الماضي الافتراضي في جملة الشرط مع would في جواب الشرط، واستخدم were للأمر التخيلي الرسمي."}
        ],
        "commonUsage": [
            "Deliberating dilemmas: 'If I were in your shoes, I would sleep on it.' (تُستخدم للتأمل في الخيارات والنصائح اليومية.)",
            "Business strategy planning: 'If we faced a sudden dealbreaker, we would activate our contingency option.' (تُستخدم لتخطيط سيناريوهات الأعمال.)",
            "Evaluating risk: 'If we took the plunge, the trade-off would be reduced liquidity.' (تُستخدم لتقييم الموازنات والتبعات المالية.)"
        ]
    }
]

convs_61 = [
    {
        "title": "Navigating a Career Crossroads",
        "titleArabic": "التنقل عند مفترق طرق وظيفي حاسم",
        "setting": "Two senior professionals discuss whether to accept a tempting but high-risk overseas corporate transfer.",
        "lines": [
            {"speaker": "David", "text": "I feel like I am standing right at a pivotal career crossroads, Maya."},
            {"speaker": "Maya", "text": "If I were in your position, I would weigh the pros and cons on paper before panicking."},
            {"speaker": "David", "text": "The salary is generous, but relocating overseas presents a painful trade-off with family roots."},
            {"speaker": "Maya", "text": "Is the lack of international schooling a dealbreaker for your spouse?"},
            {"speaker": "David", "text": "Yes, if that tuition support were omitted, it would definitely prove a dealbreaker."},
            {"speaker": "Maya", "text": "Do not let indecisive hesitation paralyze you. What does your inner gut feeling whisper?"},
            {"speaker": "David", "text": "My gut feeling says this offer could become the tipping point of my executive career."},
            {"speaker": "Maya", "text": "Then take a calculated risk, sleep on it tonight, and make up your mind tomorrow!"}
        ],
        "vocabularyUsed": ["crossroads", "weigh pros and cons", "trade-off", "dealbreaker", "indecisive", "hesitation", "gut feeling", "tipping point", "calculated risk", "sleep on it", "make up mind"]
    },
    {
        "title": "Corporate Strategy Deliberation",
        "titleArabic": "مداولة استراتيجية في إدارة الشركات",
        "setting": "A venture partner and a company founder deliberate over acquisition terms in a conference room.",
        "lines": [
            {"speaker": "Founder", "text": "If we accepted their buyout bid today, it would be an irrevocable decision for our brand."},
            {"speaker": "Partner", "text": "Indeed; once papers are signed, we cross the point of no return."},
            {"speaker": "Founder", "text": "Would our existing engineering team suffer buyers remorse after losing independence?"},
            {"speaker": "Partner", "text": "If we conducted a thorough cost-benefit analysis, everyone would see the clear capital advantage."},
            {"speaker": "Founder", "text": "I want to ensure we steer clear of predatory lock-in clauses in the contract."},
            {"speaker": "Partner", "text": "If we stood by our decision to protect developer autonomy, they would respect our boundary."},
            {"speaker": "Founder", "text": "Let us prepare a contingency option in case their legal board rejects our valuation."},
            {"speaker": "Partner", "text": "Sound judgment always triumphs when we refuse to rush into snap judgments."}
        ],
        "vocabularyUsed": ["irrevocable decision", "point of no return", "buyers remorse", "cost-benefit analysis", "steer clear of", "stand by decision", "contingency option", "sound judgment", "snap judgment"]
    },
    {
        "title": "Resolving a Technical Dilemma",
        "titleArabic": "حسم معضلة تقنية بين مهندسي برمجيات",
        "setting": "Lead systems architect mentors a software team lead on infrastructure choices.",
        "lines": [
            {"speaker": "Lead Architect", "text": "If you called the shots on this cloud migration, which server provider would you select?"},
            {"speaker": "Team Lead", "text": "I would mull over the latency benchmarks rather than rely on arbitrary choices."},
            {"speaker": "Lead Architect", "text": "What is the decisive factor between the two competing vendors?"},
            {"speaker": "Team Lead", "text": "Global server uptime is the decisive factor; zero downtime is our overriding factor."},
            {"speaker": "Lead Architect", "text": "If junior engineers vacillated between microservices and monoliths, how would you guide them?"},
            {"speaker": "Team Lead", "text": "I would give them a practical rule of thumb: start simple and avoid premature optimization."},
            {"speaker": "Lead Architect", "text": "If we took the plunge right now, would we encounter any unintended consequence?"},
            {"speaker": "Team Lead", "text": "Database replication lag might emerge, so we should deliberate carefully."}
        ],
        "vocabularyUsed": ["call the shots", "mull over", "arbitrary choice", "decisive factor", "overriding factor", "vacillate", "rule of thumb", "take the plunge", "unintended consequence", "deliberate carefully"]
    }
]

paras_61 = [
    {
        "title": "The Anatomy of Rational Decision-Making",
        "titleArabic": "تشريح صناعة القرار العقلاني والرشيد",
        "text": "Every professional inevitably stands at a career crossroads where every single path carries a demanding trade-off. If individuals approached dilemmas logically, they would conduct a rigorous cost-benefit analysis rather than rely on snap judgment or arbitrary choice. Evaluating the full gamut of choices requires patience and deep deliberation. While listening to a strong gut feeling offers valuable intuitive guidance, an informed choice demands that leaders examine each pro and con objectively. If planners foresaw every unintended consequence, they would design robust contingency options before taking a calculated risk.",
        "vocabularyUsed": ["crossroads", "trade-off", "cost-benefit analysis", "snap judgment", "arbitrary choice", "gamut of choices", "deliberation", "gut feeling", "informed choice", "pro and con", "unintended consequence", "contingency option", "calculated risk"]
    },
    {
        "title": "Overcoming Hesitation and Analysis Paralysis",
        "titleArabic": "التغلب على التردد وشلل التحليل المفرط",
        "text": "When facing complex dilemmas, many managers vacillate endlessly and dither until golden opportunities vanish. If aspiring leaders developed true decisiveness, they would not agonize over minor operational uncertainties or second-guess every judgment call. While it is sensible to sleep on it and mull over major contracts overnight, prolonged hesitation breeds self-doubt and institutional stagnation. A reliable rule of thumb suggests that when you reach a critical tipping point with seventy percent verified data, you must take the plunge, stand by your decision, and move forward boldly.",
        "vocabularyUsed": ["vacillate", "dither", "decisiveness", "agonize over", "second-guess", "judgment call", "sleep on it", "mull over", "hesitation", "rule of thumb", "tipping point", "take the plunge", "stand by decision"]
    },
    {
        "title": "Facing Irrevocable Choices with Integrity",
        "titleArabic": "مواجهة القرارات المصيرية بنزاهة واستقامة",
        "text": "Some moments in institutional governance represent an irrevocable decision where an enterprise crosses the point of no return. If executives ignored their ethical compass during such trials, they would inevitably reap negative consequences and endure lasting buyers remorse. When unforeseen crises strike, true leaders refuse to steer clear of tough conversations or shirk accountability; instead, they face the music with fortitude. Exercising sound judgment ensures that when you call the shots, your choices reflect lasting principles rather than fleeting convenience.",
        "vocabularyUsed": ["irrevocable decision", "point of no return", "reap consequences", "buyers remorse", "steer clear of", "face the music", "sound judgment", "call the shots"]
    }
]

# Write Day 61
write_day(61, vocab_61, grammar_61, convs_61, paras_61)

# ==============================================================================
# DAY 62: Big and Small Problems (Everyday problems and solutions)
# Grammar: ["Second Conditional (Part 2)"]
# ==============================================================================
vocab_62 = [
    # Everyday Predicaments & Annoyances (15)
    {"headword": "predicament", "pronunciation": "/prɪˈdɪkəmənt/", "partOfSpeech": "noun", "definition": "A difficult, perplexing, or unpleasantly embarrassing situation.", "example": "If we found ourselves in such a sticky predicament, we would contact our emergency support team.", "translation": "مأزق محرج / ورطة عويصة", "exampleArabic": "لو وجدنا أنفسنا في مأزق محرج كهذا، لاتصلنا بفريق الدعم للطوارئ.", "collocations": ["awkward predicament", "escape a predicament"], "synonyms": ["quandary", "plight"], "antonyms": ["favorable situation"], "tags": ["problems", "circumstances"]},
    {"headword": "snag", "pronunciation": "/snæɡ/", "partOfSpeech": "noun", "definition": "An unexpected or hidden obstacle, drawback, or catch.", "example": "If the software update hit a technical snag, the automated rollback script would trigger.", "translation": "عقبة غير متوقعة / عائق مفاجئ", "exampleArabic": "لو واجه التحديث البرمجي عقبة تقنية غير متوقعة، لانطلق برنامج التراجع التلقائي.", "collocations": ["hit a snag", "minor snag"], "synonyms": ["hitch", "glitch"], "antonyms": ["smooth progress"], "tags": ["obstacles", "problems"]},
    {"headword": "hiccup", "pronunciation": "/ˈhɪkʌp/", "partOfSpeech": "noun", "definition": "A temporary minor problem, setback, or irregularity.", "example": "If there were a brief logistical hiccup, our local warehouse buffer would absorb it.", "translation": "تعثر عارض بسيط / إرباك مؤقت", "exampleArabic": "لو حدث تعثر عارض بسيط في الخدمات اللوجستية، لامتصه المخزون الاحتياطي بمستودعنا.", "collocations": ["minor hiccup", "temporary hiccup"], "synonyms": ["minor glitch"], "antonyms": ["flawless run"], "tags": ["delays", "problems"]},
    {"headword": "quandary", "pronunciation": "/ˈkwɒndəri/", "partOfSpeech": "noun", "definition": "A state of perplexity or uncertainty over what to do in a difficult situation.", "example": "If she remained in that ethical quandary, she would request confidential ombudsman counseling.", "translation": "حيرة بالغة / مأزق فكري أو أخلاقي", "exampleArabic": "لو ظلت في تلك الحيرة الأخلاقية البالغة، لطلبت استشارة سرية من ديوان المظالم.", "collocations": ["in a quandary", "ethical quandary"], "synonyms": ["dilemma", "perplexity"], "antonyms": ["certainty"], "tags": ["psychology", "problems"]},
    {"headword": "inconvenience", "pronunciation": "/ˌɪnkənˈviːniəns/", "partOfSpeech": "noun", "definition": "Trouble or difficulty caused to one's personal comfort, ease, or routine.", "example": "If the flight cancellation caused serious inconvenience, the airline would supply complimentary hotel suites.", "translation": "إزعاج / مشقة وإرباك للراحة", "exampleArabic": "لو تسبب إلغاء الرحلة في إزعاج ومشقة بالغة، لوفرت شركة الطيران أجنحة فندقية مجانية.", "collocations": ["cause inconvenience", "slight inconvenience"], "synonyms": ["trouble", "nuisance"], "antonyms": ["convenience"], "tags": ["discomfort", "daily"]},
    {"headword": "nuisance", "pronunciation": "/ˈnjuːsns/", "partOfSpeech": "noun", "definition": "A person, thing, or circumstance causing persistent annoyance or trouble.", "example": "If the neighbor's loud renovation proved a constant nuisance, we would lodge a formal noise complaint.", "translation": "مكروه مزعج / مصدر مضايقة مستمر", "exampleArabic": "لو أثبتت أعمال تجديد الجار الصاخبة أنها مصدر إزعاج مستمر، لرفعنا شكوى ضوضاء رسمية.", "collocations": ["public nuisance", "dreadful nuisance"], "synonyms": ["annoyance", "irritant"], "antonyms": ["blessing"], "tags": ["annoyance", "lifestyle"]},
    {"headword": "hassle", "pronunciation": "/ˈhæsl/", "partOfSpeech": "noun", "definition": "Irritating, tedious, or inconvenient inconvenience and trouble.", "example": "If renewing the visa were too much hassle in person, I would hire a licensed immigration expeditor.", "translation": "معاناة مرهقة / وجع دماغ ومشقة روتينية", "exampleArabic": "لو كان تجديد التأشيرة ينطوي على مشقة روتينية مرهقة شخصياً، لاستعنت بمعقب هجرة مرخص.", "collocations": ["too much hassle", "worth the hassle"], "synonyms": ["bother", "headache"], "antonyms": ["breeze"], "tags": ["routine", "frustration"]},
    {"headword": "fiasco", "pronunciation": "/fiˈæskəʊ/", "partOfSpeech": "noun", "definition": "A complete, disastrous, and humiliating failure or breakdown.", "example": "If the live product launch turned into an embarrassing fiasco, the PR director would resign.", "translation": "فشل ذريع مهين / إخفاق تام وفضيحة", "exampleArabic": "لو تحول إطلاق المنتج الحي إلى فشل ذريع مهين، لقدم مدير العلاقات العامة استقالته.", "collocations": ["total fiasco", "financial fiasco"], "synonyms": ["catastrophe", "debacle"], "antonyms": ["resounding triumph"], "tags": ["disaster", "failure"]},
    {"headword": "debacle", "pronunciation": "/deɪˈbɑːkl/", "partOfSpeech": "noun", "definition": "A sudden, catastrophic, and ignominious failure or collapse.", "example": "If the infrastructure funding collapsed, the entire construction debacle would become headline news.", "translation": "انهيار مدوٍّ / كارثة وفشل ساحق", "exampleArabic": "لو انهار تمويل البنية التحتية، لأصبح ذلك الانهيار والخراب الإنشائي حديث عناوين الأخبار.", "collocations": ["financial debacle", "prevent a debacle"], "synonyms": ["collapse", "ruin"], "antonyms": ["success"], "tags": ["collapse", "crisis"]},
    {"headword": "muddle", "pronunciation": "/ˈmʌdl/", "partOfSpeech": "noun", "definition": "An untidy, disordered, and thoroughly confused state or situation.", "example": "If our billing records were in such a chaotic muddle, audits would take months.", "translation": "فوضى عارمة / خلط وتخبط وارتباك", "exampleArabic": "لو كانت سجلات فواتيرنا في فوضى وتخبط كهذا، لاستغرقت عمليات التدقيق أشهراً.", "collocations": ["in a terrible muddle", "bureaucratic muddle"], "synonyms": ["mess", "shambles"], "antonyms": ["order"], "tags": ["disorder", "confusion"]},
    {"headword": "catch-22", "pronunciation": "/ˌkætʃ twenti ˈtuː/", "partOfSpeech": "noun", "definition": "A dilemma or difficult circumstance from which there is no escape because of mutually conflicting conditions.", "example": "If junior graduates faced this catch-22, they would volunteer to gain the required prerequisite experience.", "translation": "معضلة دائرية مستحيلة الحل / حلقة مفرغة", "exampleArabic": "لو واجه الخريجون الجدد هذه الحلقة المفرغة، لتطوعوا لاكتساب الخبرة المسبقة المطلوبة.", "collocations": ["classic catch-22", "faced with a catch-22"], "synonyms": ["vicious circle", "paradox"], "antonyms": [], "tags": ["logic", "dilemma"]},
    {"headword": "blind spot", "pronunciation": "/ˈblaɪnd spɒt/", "partOfSpeech": "noun", "definition": "An area in which one fails to exercise judgment, perception, or understanding.", "example": "If the leadership team recognized their marketing blind spot, they would appoint external brand consultants.", "translation": "نقطة عمياء / جانب غائب عن الإدراك", "exampleArabic": "لو أدرك فريق القيادة نقطتهم العمياء في التسويق، لعينوا مستشاري علامة تجارية خارجيين.", "collocations": ["critical blind spot", "cognitive blind spot"], "synonyms": ["unnoticed flaw"], "antonyms": ["full awareness"], "tags": ["psychology", "cognition"]},
    {"headword": "bottleneck", "pronunciation": "/ˈbɒtlnek/", "partOfSpeech": "noun", "definition": "A point of congestion or blockage that impedes progress or production.", "example": "If we eliminated the database server bottleneck, query latency would drop eighty percent.", "translation": "عنق زجاجة / نقطة اختناق وتعطيل", "exampleArabic": "لو قضينا على عنق الزجاجة في خادم قواعد البيانات، لانخفض وقت استجابة الاستعلامات بنسبة ثمانين بالمائة.", "collocations": ["production bottleneck", "traffic bottleneck"], "synonyms": ["chokepoint", "constriction"], "antonyms": ["smooth conduit"], "tags": ["operations", "delays"]},
    {"headword": "tight spot", "pronunciation": "/taɪt spɒt/", "partOfSpeech": "noun", "definition": "A precarious, difficult, or demanding situation, especially a financial one.", "example": "If the small enterprise were caught in a tight spot, they would renegotiate loan payments.", "translation": "موقف حرج / ضائقة مالية أو موقف ضيق", "exampleArabic": "لو وقعت المؤسسة الصغيرة في موقف حرج وضائقة، لأعادت التفاوض على دفعات القروض.", "collocations": ["in a tight spot", "get out of a tight spot"], "synonyms": ["tight corner", "pinch"], "antonyms": ["cushion"], "tags": ["difficulty", "idioms"]},
    {"headword": "quagmire", "pronunciation": "/ˈkwæɡmaɪə/", "partOfSpeech": "noun", "definition": "A complex, hazardous, and muddy situation from which it is difficult to free oneself.", "example": "If overseas forces entered that geopolitical quagmire, extracting troops would take decades.", "translation": "مستنقع معقد / ورطة موحلة يصعب الخروج منها", "exampleArabic": "لو دخلت القوات ذلك المستنقع الجيوسياسي، لاستغرق سحب الجنود عقوداً من الزمن.", "collocations": ["legal quagmire", "sink into a quagmire"], "synonyms": ["morass", "swamp"], "antonyms": ["safe harbor"], "tags": ["crisis", "complexity"]},

    # Complications, Strains & Challenges (15)
    {"headword": "minor annoyance", "pronunciation": "/ˈmaɪnər əˈnɔɪəns/", "partOfSpeech": "noun", "definition": "A petty, small problem that causes slight irritation without serious harm.", "example": "If intermittent flickering lights were merely a minor annoyance, we would postpone calling the electrician.", "translation": "مضايقة طفيفة / إزعاج بسيط", "exampleArabic": "لو كانت أضواء الوميض المتقطع مجرد مضايقة طفيفة، لأجلنا استدعاء الفني الكهربائي.", "collocations": ["dismiss as a minor annoyance", "suffer a minor annoyance"], "synonyms": ["petty irritant"], "antonyms": ["major catastrophe"], "tags": ["irritation", "mild"]},
    {"headword": "major headache", "pronunciation": "/ˈmeɪdʒə ˈhedeɪk/", "partOfSpeech": "noun", "definition": "A severely troublesome, stressful, and complicated problem.", "example": "If international customs clearance were delayed, it would become a major headache for shippers.", "translation": "صداع مزمن / ورطة تسبب إرهاقاً وتوتراً هائلاً", "exampleArabic": "لو تأخر التخليص الجمركي الدولي، لأصبح صداعاً كبيراً ومصدر قلق هائل لشركات الشحن.", "collocations": ["cause a major headache", "prove a major headache"], "synonyms": ["severe hassle"], "antonyms": ["walk in the park"], "tags": ["stress", "idioms"]},
    {"headword": "unforeseen complication", "pronunciation": "/ˌʌnfɔːˈsiːn ˌkɒmplɪˈkeɪʃn/", "partOfSpeech": "noun", "definition": "An unanticipated difficulty that makes a task or situation harder to solve.", "example": "If an unforeseen complication surfaced during surgery, the senior surgeon would step in.", "translation": "مضاعفة غير متوقعة / تعقيد طارئ", "exampleArabic": "لو ظهرت مضاعفة غير متوقعة أثناء الجراحة، لتدخل كبير الجراحين فوراً.", "collocations": ["encounter unforeseen complications", "arise from unforeseen complications"], "synonyms": ["unexpected twist"], "antonyms": ["predictable step"], "tags": ["complications", "events"]},
    {"headword": "logistical nightmare", "pronunciation": "/ləˈdʒɪstɪkl ˈnaɪtmeə/", "partOfSpeech": "noun", "definition": "An exceptionally chaotic, complicated, and disorganized operational undertaking.", "example": "If five hundred international guests arrived simultaneously without buses, it would be a logistical nightmare.", "translation": "كابوس لوجستي وتنظيمي", "exampleArabic": "لو وصل خمسمائة ضيف دولي في وقت واحد دون حافلات، لكان الأمر كابوساً لوجستياً.", "collocations": ["turn into a logistical nightmare", "avoid a logistical nightmare"], "synonyms": ["operational chaos"], "antonyms": ["seamless coordination"], "tags": ["operations", "hyperbole"]},
    {"headword": "spanner in the works", "pronunciation": "/ˌspænər ɪn ðə ˈwɜːks/", "partOfSpeech": "noun", "definition": "An event or action that disrupts smooth progress or ruins careful plans.", "example": "If unexpected transport strikes threw a spanner in the works, we would host the summit virtually.", "translation": "عصا في العجلة / إفساد للمخططات", "exampleArabic": "لو وضعت إضرابات النقل المفاجئة عصا في العجلة، لأقمنا القمة عبر تقنية الاتصال المرئي.", "collocations": ["throw a spanner in the works", "put a spanner in the works"], "synonyms": ["wrench in the gears", "disruption"], "antonyms": ["catalyst for success"], "tags": ["disruption", "idioms"]},
    {"headword": "teething troubles", "pronunciation": "/ˈtiːðɪŋ ˈtrʌblz/", "partOfSpeech": "noun", "definition": "Short-term problems that occur in the initial stages of a new project or system.", "example": "If the new metro ticketing app experienced teething troubles, customer service desks would assist riders.", "translation": "مشاكل وصعوبات البداية / عثرات التأسيس", "exampleArabic": "لو عانى تطبيق تذاكر المترو الجديد من عثرات البداية، لساعدت مكاتب خدمة العملاء الركاب.", "collocations": ["suffer teething troubles", "overcome teething troubles"], "synonyms": ["early glitches", "startup difficulties"], "antonyms": ["mature stability"], "tags": ["startups", "development"]},
    {"headword": "countermeasure", "pronunciation": "/ˈkaʊntəmeʒə/", "partOfSpeech": "noun", "definition": "An action taken to counteract a danger, threat, or unwanted condition.", "example": "If cyber attacks intensified, our security engineers would deploy an aggressive defensive countermeasure.", "translation": "إجراء مضاد / تدبير وقائي لمواجهة الخطر", "exampleArabic": "لو تكثفت الهجمات السيبرانية، لنشر مهندسو الأمن لدينا إجراءً دفاعياً مضاداً وحازماً.", "collocations": ["deploy a countermeasure", "effective countermeasure"], "synonyms": ["counteraction", "safeguard"], "antonyms": ["vulnerability"], "tags": ["security", "actions"]},
    {"headword": "remedial action", "pronunciation": "/rɪˈmiːdiəl ˈækʃn/", "partOfSpeech": "noun", "definition": "Steps taken to correct, alleviate, or improve a deficient situation.", "example": "If environmental inspections revealed emissions leaks, the factory would take swift remedial action.", "translation": "إجراء تصحيحي وعلاجي", "exampleArabic": "لو كشفت عمليات التفتيش البيئي عن تسرب في الانبعاثات، لاتخذ المصنع إجراءً علاجياً سريعاً.", "collocations": ["take remedial action", "urgent remedial action"], "synonyms": ["corrective step"], "antonyms": ["neglect"], "tags": ["corrections", "actions"]},
    {"headword": "quick fix", "pronunciation": "/ˌkwɪk ˈfɪks/", "partOfSpeech": "noun", "definition": "An easy, fast, but often temporary or superficial remedy for a problem.", "example": "If developers used a quick fix instead of refactoring, technical debt would compound.", "translation": "حل سريع سطحي / ترقيع مؤقت", "exampleArabic": "لو استخدم المطورون حلاً سريعاً مؤقتاً بدلاً من إعادة كتابة الشيفرة، لتراكمت الديون التقنية.", "collocations": ["rely on a quick fix", "no quick fix available"], "synonyms": ["patch", "expedient"], "antonyms": ["permanent cure"], "tags": ["solutions", "flaws"]},
    {"headword": "band-aid solution", "pronunciation": "/ˈbændeɪd səˈluːʃn/", "partOfSpeech": "noun", "definition": "A temporary or makeshift measure that does not address root underlying causes.", "example": "If the city council applied another band-aid solution, the potholes would reopen next winter.", "translation": "حل ترقيعي مؤقت / مسكن سطحي", "exampleArabic": "لو طبقت بلدية المدينة حلاً ترقيعياً مؤقتاً آخر، لعاودت الحفر الظهور في الشتاء القادم.", "collocations": ["mere band-aid solution", "criticize band-aid solutions"], "synonyms": ["stopgap measure", "makeshift remedy"], "antonyms": ["lasting remedy"], "tags": ["temporary", "solutions"]},
    {"headword": "stopgap measure", "pronunciation": "/ˈstɒpɡæp ˈmeʒə/", "partOfSpeech": "noun", "definition": "A temporary expedient adopted until a permanent replacement can be secured.", "example": "If the primary water pipe burst, the emergency generator pump would serve as a stopgap measure.", "translation": "إجراء سد خانة / تدبير طوارئ مؤقت", "exampleArabic": "لو انفجر أنبوب المياه الرئيسي، لعملت مضخة مولد الطوارئ كتدبير مؤقت لسد الخانة.", "collocations": ["serve as a stopgap measure", "temporary stopgap measure"], "synonyms": ["makeshift", "interim arrangement"], "antonyms": ["permanent installation"], "tags": ["temporary", "emergency"]},
    {"headword": "iron out", "pronunciation": "/ˈaɪən aʊt/", "partOfSpeech": "verb", "definition": "To resolve small difficulties, misunderstandings, or discrepancies through discussion.", "example": "If both trade delegations sat together, they would iron out remaining tariff discrepancies.", "translation": "يسوي الخلافات ويزيل العقبات / يذلل الصعاب", "exampleArabic": "لو جلس كلا الوفدين التجاريين معاً، لسووا التفاوتات المتبقية في الرسوم الجمركية.", "verbForms": {"v1": "iron out", "v2": "ironed out", "v3": "ironed out"}, "collocations": ["iron out differences", "iron out kinks"], "synonyms": ["resolve", "smooth over"], "antonyms": ["exacerbate"], "tags": ["actions", "solutions"]},
    {"headword": "salvage", "pronunciation": "/ˈsælvɪdʒ/", "partOfSpeech": "verb", "definition": "To rescue or save valuable parts of something from wreckage, ruin, or failure.", "example": "If the project missed its launch date, we would still salvage the core machine-learning models.", "translation": "ينقذ ما يمكن إنقاذه / يستنقذ", "exampleArabic": "لو فات موعد إطلاق المشروع، لاستنقذنا النماذج الأساسية للتعلم الآلي على الأقل.", "verbForms": {"v1": "salvage", "v2": "salvaged", "v3": "salvaged"}, "collocations": ["salvage the situation", "salvage key assets"], "synonyms": ["rescue", "retrieve"], "antonyms": ["abandon to ruin"], "tags": ["recovery", "actions"]},
    {"headword": "damage control", "pronunciation": "/ˈdæmɪdʒ kənˈtrəʊl/", "partOfSpeech": "noun", "definition": "Action taken to limit the detrimental effects of an accident or political scandal.", "example": "If corporate executives leaked confidential earnings, the communications team would initiate damage control.", "translation": "احتواء الأضرار والحد من الخسائر", "exampleArabic": "لو سرب مسؤولو الشركة الأرباح السرية، لبدأ فريق الاتصالات إجراءات احتواء الأضرار.", "collocations": ["exercise damage control", "damage control mode"], "synonyms": ["harm minimization"], "antonyms": [], "tags": ["crisis", "pr"]},
    {"headword": "extricate", "pronunciation": "/ˈekstrɪkeɪt/", "partOfSpeech": "verb", "definition": "To free someone or oneself from a constraint or difficult, hazardous situation.", "example": "If the diplomat were trapped in a host-country crisis, embassy security would extricate him.", "translation": "يخلّص من ورطة / ينتشل من مأزق", "exampleArabic": "لو حوصر الدبلوماسي في أزمة بالدولة المضيفة، لانتشله أمن السفارة وخلصه.", "verbForms": {"v1": "extricate", "v2": "extricated", "v3": "extricated"}, "collocations": ["extricate oneself from", "extricate safely"], "synonyms": ["disentangle", "extract"], "antonyms": ["entangle"], "tags": ["rescue", "actions"]},

    # Troubleshooting & Overcoming Hurdles (20)
    {"headword": "alleviate difficulty", "pronunciation": "/əˈliːvieɪt ˈdɪfɪkəlti/", "partOfSpeech": "verb", "definition": "To make problems, hardships, or pain less severe and more manageable.", "example": "If local clinics received mobile testing vans, it would alleviate difficulty for rural villagers.", "translation": "يخفف وطأة الصعوبات / ييسر المشاق", "exampleArabic": "لو استلمت العيادات المحلية شاحنات فحص متنقلة، لخفف ذلك وطأة الصعوبات على سكان القرى.", "verbForms": {"v1": "alleviate difficulty", "v2": "alleviated difficulty", "v3": "alleviated difficulty"}, "collocations": ["help alleviate difficulty", "aim to alleviate difficulty"], "synonyms": ["ease hardship"], "antonyms": ["aggravate difficulty"], "tags": ["relief", "actions"]},
    {"headword": "nip in the bud", "pronunciation": "/nɪp ɪn ðə bʌd/", "partOfSpeech": "verb", "definition": "To suppress or destroy something bad at an early stage before it develops fully.", "example": "If managers nipped interpersonal feuds in the bud, team cohesion would flourish.", "translation": "يقضي على الأمر في مهده / يئد المشكلة في بدايتها", "exampleArabic": "لو وأد المديرون الخلافات الشخصية في مهدها، لازدهر تماسك الفريق وتآلفه.", "verbForms": {"v1": "nip in the bud", "v2": "nipped in the bud", "v3": "nipped in the bud"}, "collocations": ["nip trouble in the bud", "essential to nip in the bud"], "synonyms": ["halt early", "quash immediately"], "antonyms": ["allow to fester"], "tags": ["prevention", "idioms"]},
    {"headword": "weather the storm", "pronunciation": "/ˈweðə ðə stɔːm/", "partOfSpeech": "verb", "definition": "To endure and survive a difficult period without suffering permanent ruin.", "example": "If small businesses held six months of operating reserves, they would weather the storm easily.", "translation": "يتجاوز العاصفة بسلام / يصمد أمام الأزمة", "exampleArabic": "لو احتفظت الشركات الصغيرة باحتياطيات تشغيلية لستة أشهر، لتجاوزت العاصفة وصمدت بسهولة.", "verbForms": {"v1": "weather the storm", "v2": "weathered the storm", "v3": "weathered the storm"}, "collocations": ["weather the financial storm", "manage to weather the storm"], "synonyms": ["endure hardship"], "antonyms": ["succumb", "capitulate"], "tags": ["resilience", "idioms"]},
    {"headword": "tide over", "pronunciation": "/taɪd ˈəʊvə/", "partOfSpeech": "verb", "definition": "To support someone temporarily through a difficult, impoverished period.", "example": "If an emergency grant tided the researcher over, she would complete her clinical trials.", "translation": "يسعف مؤقتاً / يعين على تجاوز الضائقة", "exampleArabic": "لو أسعفت منحة الطوارئ الباحثة مؤقتاً، لأكملت تجاربها السريرية.", "verbForms": {"v1": "tide over", "v2": "tided over", "v3": "tided over"}, "collocations": ["tide someone over until", "enough funds to tide over"], "synonyms": ["see through hardship"], "antonyms": [], "tags": ["assistance", "actions"]},
    {"headword": "bail out", "pronunciation": "/beɪl aʊt/", "partOfSpeech": "verb", "definition": "To rescue a person, organization, or company from financial collapse.", "example": "If the government bailed out insolvent airlines again, taxpayers would express outrage.", "translation": "ينقذ مالياً / يتدخل للإنقاذ من الإفلاس", "exampleArabic": "لو تدخلت الحكومة لإنقاذ شركات الطيران المعسرة مالياً مرة أخرى، لأبدى دافعو الضرائب غضباً عارماً.", "verbForms": {"v1": "bail out", "v2": "bailed out", "v3": "bailed out"}, "collocations": ["bail out bank", "refuse to bail out"], "synonyms": ["rescue financially"], "antonyms": ["let go bankrupt"], "tags": ["finance", "rescue"]},
    {"headword": "unravel problem", "pronunciation": "/ʌnˈrævl ˈprɒbləm/", "partOfSpeech": "verb", "definition": "To investigate, disentangle, and explain a complex, tangled mystery or difficulty.", "example": "If investigators unraveled the problem step by step, they would uncover fraudulent invoices.", "translation": "يفكك خيوط المشكلة / يحل العقدة", "exampleArabic": "لو فكك المحققون خيوط المشكلة خطوة بخطوة، لاكتشفوا الفواتير الاحتيالية.", "verbForms": {"v1": "unravel problem", "v2": "unraveled problem", "v3": "unraveled problem"}, "collocations": ["unravel the core problem", "seek to unravel problems"], "synonyms": ["disentangle", "solve"], "antonyms": ["complicate further"], "tags": ["investigation", "actions"]},
    {"headword": "smooth over", "pronunciation": "/smuːð ˈəʊvə/", "partOfSpeech": "verb", "definition": "To make problems, disagreements, or embarrassments appear less serious by tact.", "example": "If the mediator smoothed over ruffled feelings, the feuding departments would collaborate.", "translation": "يلطف الأجواء / يسوي الخلافات بلباقة", "exampleArabic": "لو لطّف الوسيط المشاعر الجريحة بلباقة، لتعاونت الأقسام المتناحرة مجدداً.", "verbForms": {"v1": "smooth over", "v2": "smoothed over", "v3": "smoothed over"}, "collocations": ["smooth over conflict", "attempt to smooth over"], "synonyms": ["conciliate", "gloss over"], "antonyms": ["stir up trouble"], "tags": ["diplomacy", "actions"]},
    {"headword": "coping mechanism", "pronunciation": "/ˈkəʊpɪŋ ˈmekənɪzəm/", "partOfSpeech": "noun", "definition": "An adaptation or behavioral tool that helps someone manage stress or trauma.", "example": "If workers developed a healthy coping mechanism, stressful quarterly audits would not induce burnout.", "translation": "آلية تأقلم ومواجهة للضغوط", "exampleArabic": "لو طور الموظفون آلية تأقلم صحية، لما أدت عمليات التدقيق الربع سنوية المرهقة إلى الاحتراق النفسي.", "collocations": ["healthy coping mechanism", "rely on coping mechanisms"], "synonyms": ["stress buffer"], "antonyms": ["maladaptive behavior"], "tags": ["psychology", "wellness"]},
    {"headword": "sticky situation", "pronunciation": "/ˈstɪki ˌsɪtʃuˈeɪʃn/", "partOfSpeech": "noun", "definition": "An awkward, embarrassing, or complicated circumstance requiring great diplomacy.", "example": "If you landed in such a sticky situation at the banquet, humor would help defuse tension.", "translation": "موقف حرج وشائك", "exampleArabic": "لو وقعت في موقف حرج وشائك كهذا في المأدبة، لساعدت الفكاهة على نزع فتيل التوتر.", "collocations": ["in a sticky situation", "handle a sticky situation"], "synonyms": ["tight spot", "awkward dilemma"], "antonyms": ["smooth sail"], "tags": ["social", "idioms"]},
    {"headword": "thorny issue", "pronunciation": "/ˈθɔːni ˈɪʃuː/", "partOfSpeech": "noun", "definition": "A topic or controversy that is full of difficulties and liable to cause contention.", "example": "If the parliament debated that thorny issue today, heated arguments would erupt.", "translation": "مسألة شائكة ومثيرة للجدل", "exampleArabic": "لو ناقش البرلمان تلك المسألة الشائكة اليوم، لاندلعت سجالات حادة.", "collocations": ["tackle a thorny issue", "address the thorny issue"], "synonyms": ["prickly topic"], "antonyms": ["straightforward matter"], "tags": ["politics", "problems"]},
    {"headword": "vexing puzzle", "pronunciation": "/ˈveksɪŋ ˈpʌzl/", "partOfSpeech": "noun", "definition": "A frustrating problem or enigma that defies an easy, obvious answer.", "example": "If mathematicians cracked this vexing puzzle, quantum cryptography would surge ahead.", "translation": "لغز محير ومستعصٍ", "exampleArabic": "لو حل علماء الرياضيات هذا اللغز المحير المستعصي، لقفز التشفير الكمي قفزات هائلة.", "collocations": ["confront a vexing puzzle", "solve a vexing puzzle"], "synonyms": ["knotty enigma"], "antonyms": ["simple riddle"], "tags": ["intellect", "problems"]},
    {"headword": "make the best of", "pronunciation": "/meɪk ðə ˈbest əv/", "partOfSpeech": "verb", "definition": "To cope as effectively as possible with an unfavorable or imperfect situation.", "example": "If we were stranded by heavy snowfall, we would make the best of it with board games.", "translation": "يتأقلم بإيجابية ويستغل الوضع بأفضل ما يمكن", "exampleArabic": "لو حوصرنا بسبب تساقط الثلوج الكثيف، لتأقلمنا بإيجابية ولعبنا ألعاب الطاولة.", "verbForms": {"v1": "make the best of", "v2": "made the best of", "v3": "made the best of"}, "collocations": ["make the best of bad situation", "try to make the best of"], "synonyms": ["look on bright side"], "antonyms": ["complain bitterly"], "tags": ["attitude", "idioms"]},
    {"headword": "troubleshooter", "pronunciation": "/ˈtrʌblʃuːtə/", "partOfSpeech": "noun", "definition": "A specialist employed to locate and eliminate systemic problems or faults.", "example": "If an industrial plant malfunctioned repeatedly, a certified troubleshooter would overhaul the assembly line.", "translation": "خبير حل المشكلات والأعطال", "exampleArabic": "لو تعطل المصنع الصناعي مراراً، لقام خبير حل الأعطال المعتمد بفحص خط التجميع وصيانته جذرياً.", "collocations": ["skilled troubleshooter", "hire a troubleshooter"], "synonyms": ["problem solver"], "antonyms": [], "tags": ["profession", "technical"]},
    {"headword": "ad hoc solution", "pronunciation": "/ˌæd ˈhɒk səˈluːʃn/", "partOfSpeech": "noun", "definition": "An improvised answer created specifically for a singular situation without wider application.", "example": "If field technicians improvised an ad hoc solution, the generator would operate until dawn.", "translation": "حل مؤقت لظرف خاص ومحدد", "exampleArabic": "لو ابتكر الفنيون الميدانيون حلاً مؤقتاً لظرفهم الخاص، لعمل المولد حتى مطلع الفجر.", "collocations": ["devise an ad hoc solution", "rely on ad hoc solutions"], "synonyms": ["improvised fix"], "antonyms": ["systematic method"], "tags": ["adaptation", "technical"]},
    {"headword": "find a workaround", "pronunciation": "/faɪnd ə ˈwɜːkəraʊnd/", "partOfSpeech": "verb", "definition": "To discover a method for overcoming a problem without eliminating the problem itself.", "example": "If browser security updates broke payment plugins, webmasters would find a workaround.", "translation": "يجد حيلة تقنية بديلة لتجاوز العطل", "exampleArabic": "لو عطلت تحديثات أمان المتصفح ملحقات الدفع، لوجد مسؤولو المواقع حيلة تقنية بديلة لتجاوز العطل.", "verbForms": {"v1": "find a workaround", "v2": "found a workaround", "v3": "found a workaround"}, "collocations": ["clever workaround", "find a quick workaround"], "synonyms": ["bypass obstacle"], "antonyms": ["hit wall"], "tags": ["technical", "actions"]},
    {"headword": "defuse crisis", "pronunciation": "/diːˈfjuːz ˈkraɪsɪs/", "partOfSpeech": "verb", "definition": "To make a tense or dangerous predicament calmer and less hazardous.", "example": "If experienced diplomats intervened early, they would defuse crisis negotiations gracefully.", "translation": "ينزع فتيل الأزمة / يهدئ الوضع المتأزم", "exampleArabic": "لو تدخل الدبلوماسيون ذوو الخبرة مبكراً، لنزعوا فتيل الأزمة في المفاوضات بلباقة.", "verbForms": {"v1": "defuse crisis", "v2": "defused crisis", "v3": "defused crisis"}, "collocations": ["defuse the crisis immediately", "ability to defuse crisis"], "synonyms": ["de-escalate"], "antonyms": ["ignite conflict"], "tags": ["diplomacy", "actions"]},
    {"headword": "patch up", "pronunciation": "/pætʃ ʌp/", "partOfSpeech": "verb", "definition": "To repair, settle, or improve something damaged or strained in a provisional way.", "example": "If both siblings apologized sincerely, they would patch up their strained relationship.", "translation": "يصلح الوضع مؤقتاً / يرأب الصدع", "exampleArabic": "لو اعتذر الشقيقان بصدق، لرأبا الصدع في علاقتهما المتوترة.", "verbForms": {"v1": "patch up", "v2": "patched up", "v3": "patched up"}, "collocations": ["patch up differences", "patch up leak"], "synonyms": ["mend temporarily"], "antonyms": ["break permanently"], "tags": ["relationships", "actions"]},
    {"headword": "bide one time", "pronunciation": "/baɪd wʌnz taɪm/", "partOfSpeech": "verb", "definition": "To wait patiently for a favorable opportunity before making a move.", "example": "If clever investors bided their time during panics, they would acquire undervalued blue-chip stocks.", "translation": "يتربص بالفرصة السانحة / يتحين الوقت المناسب بصبر", "exampleArabic": "لو تحين المستثمرون الأذكياء الوقت المناسب بصبر أثناء الذعر، لاشتروا أسهماً ممتازة بأقل من قيمتها.", "verbForms": {"v1": "bide one time", "v2": "bided one time", "v3": "bided one time"}, "collocations": ["bide one's time patiently", "wise to bide one's time"], "synonyms": ["wait in wings"], "antonyms": ["act precipitously"], "tags": ["patience", "idioms"]},
    {"headword": "clear a hurdle", "pronunciation": "/klɪər ə ˈhɜːdl/", "partOfSpeech": "verb", "definition": "To overcome an initial problem, challenge, or administrative barrier successfully.", "example": "If the biotech firm cleared this regulatory hurdle, clinical drug distribution would proceed.", "translation": "يتجاوز عقبة / يجتاز حاجزاً صعباً", "exampleArabic": "لو اجتازت شركة التكنولوجيا الحيوية هذه العقبة التنظيمية، لمضى توزيع الدواء السريري قدماً.", "verbForms": {"v1": "clear a hurdle", "v2": "cleared a hurdle", "v3": "cleared a hurdle"}, "collocations": ["clear a major hurdle", "clear the final hurdle"], "synonyms": ["surmount obstacle"], "antonyms": ["stumble"], "tags": ["achievement", "actions"]},
    {"headword": "bounce back from", "pronunciation": "/baʊns bæk frəm/", "partOfSpeech": "verb", "definition": "To recover quickly and fully from a setback, defeat, or severe misfortune.", "example": "If the resilient athlete injured his knee, he would bounce back from surgery through disciplined therapy.", "translation": "يتعافى سريعاً من / يسترد عافيته بعد كبوة", "exampleArabic": "لو أُصيب الرياضي الصبور في ركبته، لتعافى سريعاً من الجراحة عبر العلاج المنضبط.", "verbForms": {"v1": "bounce back from", "v2": "bounced back from", "v3": "bounced back from"}, "collocations": ["bounce back from defeat", "bounce back quickly"], "synonyms": ["recover rapidly", "rebound"], "antonyms": ["succumb to defeat"], "tags": ["resilience", "actions"]}
]

grammar_62 = [
    {
        "title": "Second Conditional (Part 2)",
        "titleArabic": "الحالة الشرطية الثانية — الجزء الثاني (Second Conditional: Variations & Inversions)",
        "explanation": "Expanding on hypothetical conditionals: 1) Using modal variations in the result clause: While 'would' states an imaginary certainty, 'could' expresses imaginary ability or opportunity ('If we had more staff, we could resolve the backlog'), and 'might' expresses imaginary possibility ('If the train were delayed, we might miss the introductory keynote'). 2) Question forms: 'What would you do if...?' or 'Would you still apply if the salary were lower?'. 3) Inversion with Were (Advanced style): Replacing 'If' by inverting 'Were + subject + to + base verb' ('Were a technical snag to arise, our team would deploy an immediate countermeasure').",
        "explanationArabic": "توسيع في استخدامات الحالة الشرطية الثانية: 1) تنويع الأفعال الناقصة في جواب الشرط: بينما تدل 'would' على نتيجة تخيلية شبه مؤكدة، تدل 'could' على قدرة أو إمكانية تخيلية ('لو كان لدينا موظفون أكثر، لاستطعنا حل تراكم الأعمال')، بينما تدل 'might' على احتمالية تخيلية ('لو تأخر القطار، لربما فاتتنا الكلمة الافتتاحية'). 2) صيغ الاستفهام: 'ماذا كنت ستفعل لو...؟' (What would you do if...?). 3) أسلوب التقديم المتقدم مع Were: حذف If وتقديم Were مثل: 'Were a snag to arise...' بمعنى 'لو حدثت أي عقبة...'.",
        "structures": [
            {"label": "Imaginary Ability / Opportunity · القدرة التخيلية (Could)", "pattern": "If + Subject + Past Simple, Subject + could + Base Verb", "explanation": "Expresses that an imaginary outcome would be possible or achievable.", "explanationArabic": "يعبر عن أن النتيجة التخيلية ستكون في مقدور الفاعل إنجازها."},
            {"label": "Imaginary Probability · الاحتمالية التخيلية (Might)", "pattern": "If + Subject + Past Simple, Subject + might + Base Verb", "explanation": "Expresses a tentative or uncertain hypothetical result.", "explanationArabic": "يعبر عن نتيجة تخيلية محتملة لكن دون جزم."},
            {"label": "Question Form · صيغة السؤال الافتراضي", "pattern": "What / How would you + Base Verb + if + Subject + Past Simple?", "explanation": "Asks what someone would choose or do in an imaginary problem.", "explanationArabic": "يستفهم عما سيفعله الشخص أو يختاره في مأزق تخيلي."}
        ],
        "examples": [
            {"sentence": "If the team encountered an unforeseen complication, a certified troubleshooter could salvage the project.", "translation": "لو واجه الفريق مضاعفة غير متوقعة، لاستطاع خبير حل الأعطال المعتمد استنقاذ المشروع.", "usesVocabulary": ["unforeseen complication", "troubleshooter", "salvage"]},
            {"sentence": "What would you do if you found yourself in such an awkward predicament?", "translation": "ماذا كنت ستفعل لو وجدت نفسك في مأزق محرج كهذا؟", "usesVocabulary": ["predicament"]},
            {"sentence": "If we cleared this final regulatory hurdle, the company could bounce back from recent market losses.", "translation": "لو اجتزنا هذا الحاجز التنظيمي الأخير، لاستطاعت الشركة التعافي سريعاً من خسائر السوق الأخيرة.", "usesVocabulary": ["clear a hurdle", "bounce back from"]},
            {"sentence": "If technicians deployed a quick fix instead of remedial action, minor annoyances might escalate.", "translation": "لو طبق الفنيون حلاً ترقيعياً سريعاً بدلاً من الإجراء العلاجي، لربما تفاقمت المضايقات البسيطة.", "usesVocabulary": ["quick fix", "remedial action", "minor annoyance"]}
        ],
        "commonMistakes": [
            {"wrong": "If you could solved the problem, what you would do?", "right": "If you could solve the problem, what would you do?", "note": "After 'could', always use base verb 'solve', and invert 'would you' for the question.", "noteArabic": "استخدم مصدر الفعل المجرد دائماً بعد could، وقدم would على الفاعل في صيغة السؤال."},
            {"wrong": "If there was a glitch, we might to miss the deadline.", "right": "If there were a glitch, we might miss the deadline.", "note": "Never use 'to' after modal 'might'. Prefer 'were' over 'was' in conditional if-clauses.", "noteArabic": "لا تضع 'to' إطلاقاً بعد might، واعتمد were في الجملة الشرطية الافتراضية."}
        ],
        "commonUsage": [
            "Troubleshooting hypothetical errors: 'If an error code surfaced, we could restart the database daemon.' (تُستخدم لمعالجة مشكلات الأنظمة برمجياً وتقنياً.)",
            "Managing operational crises: 'If a supplier defaulted, a stopgap measure might keep the assembly line running.' (تُستخدم لحل أزمات الإمداد والتشغيل.)",
            "Negotiating interpersonal friction: 'If both sides spoke calmly, they could smooth over the misunderstanding.' (تُستخدم لتجاوز الخلافات الإنسانية والمهنية.)"
        ]
    }
]

convs_62 = [
    {
        "title": "Solving an Office Operations Crisis",
        "titleArabic": "حل أزمة عمليات مكتبية طارئة",
        "setting": "An operations supervisor consults an executive assistant when multiple administrative breakdowns happen on the same morning.",
        "lines": [
            {"speaker": "Supervisor", "text": "The elevator is out of order and our internet router just failed. What an inconvenient muddle!"},
            {"speaker": "Assistant", "text": "If it were only a minor annoyance, I would ignore it, but this is turning into a major headache."},
            {"speaker": "Supervisor", "text": "If we called a skilled troubleshooter right now, could we salvage our morning meetings?"},
            {"speaker": "Assistant", "text": "Yes! If technicians established a mobile hotspot, that stopgap measure could tide us over."},
            {"speaker": "Supervisor", "text": "What about the international shipment that got stuck at airport customs?"},
            {"speaker": "Assistant", "text": "That delivery bottleneck is a classic logistical nightmare, but our broker will iron out the paperwork."},
            {"speaker": "Supervisor", "text": "Let us make sure we nip this trouble in the bud before the CEO arrives."},
            {"speaker": "Assistant", "text": "Agreed! Once we clear this hurdle, our morning routine will normalize."}
        ],
        "vocabularyUsed": ["muddle", "minor annoyance", "major headache", "troubleshooter", "salvage", "stopgap measure", "tide over", "bottleneck", "logistical nightmare", "iron out", "nip in the bud", "clear a hurdle"]
    },
    {
        "title": "Dealing with a Catch-22 in Business",
        "titleArabic": "التعامل مع حلقة مفرغة في عالم الأعمال",
        "setting": "Two young startup founders brainstorm how to secure venture funding without prior enterprise client contracts.",
        "lines": [
            {"speaker": "Founder A", "text": "Investors want paying corporate clients, but enterprise clients demand audited software history. It is a catch-22!"},
            {"speaker": "Founder B", "text": "If we stayed stuck in this quandary, our seed funding would dry up in three months."},
            {"speaker": "Founder A", "text": "How could we extricate ourselves from this sticky predicament?"},
            {"speaker": "Founder B", "text": "If we offered a free pilot to an educational non-profit, we could find a clever workaround."},
            {"speaker": "Founder A", "text": "That ad hoc solution could give us the verified case study we desperately need!"},
            {"speaker": "Founder B", "text": "Exactly; it would be far better than relying on a flimsy band-aid solution."},
            {"speaker": "Founder A", "text": "If we bided our time and perfected security protocols, investors would notice our diligence."},
            {"speaker": "Founder B", "text": "Then let us make the best of our small budget and build that pilot model today!"}
        ],
        "vocabularyUsed": ["catch-22", "quandary", "extricate", "predicament", "find a workaround", "ad hoc solution", "band-aid solution", "bide one time", "make the best of"]
    },
    {
        "title": "Managing High-Stakes Public Relations",
        "titleArabic": "إدارة العلاقات العامة في أزمة حساسة",
        "setting": "A corporate PR director briefs a newly appointed communications associate.",
        "lines": [
            {"speaker": "PR Director", "text": "If a confidential memo leaked to press reporters, how would you initiate damage control?"},
            {"speaker": "Associate", "text": "I would verify facts immediately to ensure we did not throw a spanner in the works with conflicting statements."},
            {"speaker": "PR Director", "text": "Good! If unverified rumors spread wildly, an embarrassing PR fiasco could unfold."},
            {"speaker": "Associate", "text": "Could a sincere public briefing smooth over angry customer feedback?"},
            {"speaker": "PR Director", "text": "Yes, if an executive explained remedial action clearly, it would defuse the crisis promptly."},
            {"speaker": "Associate", "text": "What if consumer trust suffered a sudden, severe blow?"},
            {"speaker": "PR Director", "text": "If an organization stayed transparent and humble, it could bounce back from any temporary setback."},
            {"speaker": "Associate", "text": "That strategic clarity reassures me; I am ready to tackle any thorny issue that emerges."}
        ],
        "vocabularyUsed": ["damage control", "spanner in the works", "fiasco", "smooth over", "remedial action", "defuse crisis", "bounce back from", "thorny issue"]
    }
]

paras_62 = [
    {
        "title": "The Spectrum of Everyday Workplace Predicaments",
        "titleArabic": "طيف المشكلات والمآزق اليومية في بيئة العمل",
        "text": "In any dynamic workplace, challenges range from a trivial minor annoyance to an all-out logistical nightmare. If an unexpected administrative snag arose during quarterly reporting, a well-prepared department could rely on a proven coping mechanism rather than sink into panic. While an occasional temporary hiccup is easily absorbed by operational buffers, ignoring a persistent chokepoint produces a damaging bottleneck. If project managers recognized their blind spot early, they would execute targeted remedial action instead of applying a superficial band-aid solution that merely masks deeper structural flaws.",
        "vocabularyUsed": ["minor annoyance", "logistical nightmare", "snag", "coping mechanism", "hiccup", "bottleneck", "blind spot", "remedial action", "band-aid solution"]
    },
    {
        "title": "Escaping the Quagmire of Flawed Solutions",
        "titleArabic": "النجاة من مستنقع الحلول الترقيعية القاصرة",
        "text": "When organizations confront a thorny issue or complex quandary, leaders often face intense pressure to deliver an immediate quick fix. However, if technical teams relied repeatedly on an ad hoc solution or makeshift stopgap measure, system fragility would deepen into a costly quagmire. If an experienced troubleshooter unraveled the problem at its structural roots, they could iron out hidden inconsistencies once and for all. Taking the time to nip systemic trouble in the bud saves companies from undergoing a humiliating operational fiasco.",
        "vocabularyUsed": ["thorny issue", "quandary", "quick fix", "ad hoc solution", "stopgap measure", "quagmire", "troubleshooter", "unravel problem", "iron out", "nip in the bud", "fiasco"]
    },
    {
        "title": "Building Organizational Resilience Against Adversity",
        "titleArabic": "بناء المناعة المؤسسية ضد المحن والأزمات",
        "text": "Every enterprise eventually encounters an unforeseen complication that threatens to derail strategic progress. If founders were caught in an awkward tight spot or financial debacle, their primary duty would be to execute decisive damage control and salvage core relationships. Instead of bemoaning an unfair catch-22, resilient managers learn to make the best of limited capital, bide their time strategically, and clear every regulatory hurdle with unwavering focus. Those who cultivate operational endurance will consistently weather the storm and bounce back from adversity stronger than before.",
        "vocabularyUsed": ["unforeseen complication", "tight spot", "debacle", "damage control", "salvage", "catch-22", "make the best of", "bide one time", "clear a hurdle", "weather the storm", "bounce back from"]
    }
]

# Write Day 62
write_day(62, vocab_62, grammar_62, convs_62, paras_62)

print("Day 61 and Day 62 written successfully.")
