# -*- coding: utf-8 -*-
"""Builder for Day 65 and Day 66: Stage 7 (Problems, Decisions and Opinions)."""

import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts.curriculum_engine import write_day

# ==============================================================================
# DAY 65: Causes and Effects (Reasons and results)
# Grammar: ["Cause and Effect: because of / due to / so...that"]
# ==============================================================================
vocab_65 = [
    # Chain Reactions, Catalysts & Triggers (15)
    {"headword": "chain reaction", "pronunciation": "/ˈtʃeɪn riˈækʃn/", "partOfSpeech": "noun", "definition": "A chemical or psychological process where a single event sets off an uncontrollable series of similar events.", "example": "The bank bankruptcy set off a disastrous chain reaction across European stock markets.", "translation": "تفاعل متسلسل / ردود فعل متعاقبة", "exampleArabic": "أطلق إفلاس البنك تفاعلاً متسلسلاً كارثياً عبر أسواق الأسهم الأوروبية.", "collocations": ["trigger a chain reaction", "unstoppable chain reaction"], "synonyms": ["domino effect", "cascade"], "antonyms": [], "tags": ["causality", "events"]},
    {"headword": "ripple effect", "pronunciation": "/ˈrɪpl ɪˈfekt/", "partOfSpeech": "noun", "definition": "The continuing and spreading results of an event or action spreading outwards gradually.", "example": "Rising fuel prices produced a painful ripple effect on food haulage costs.", "translation": "أثر تموجي متتابع / تداعيات متسعة", "exampleArabic": "أنتج ارتفاع أسعار الوقود أثراً تموجياً متتابعاً مؤلماً على تكاليف نقل المواد الغذائية.", "collocations": ["cause a ripple effect", "widespread ripple effect"], "synonyms": ["knock-on effect"], "antonyms": ["isolated event"], "tags": ["consequences", "economics"]},
    {"headword": "domino effect", "pronunciation": "/ˈdɒmɪnəʊ ɪˈfekt/", "partOfSpeech": "noun", "definition": "A cumulative effect produced when one event sets off a series of similar cascading events.", "example": "The closure of the main steel plant triggered a devastating domino effect in regional employment.", "translation": "تأثير أحجار الدومينو المتساقطة", "exampleArabic": "أدى إغلاق مصنع الصلب الرئيسي إلى إطلاق تأثير أحجار الدومينو المدمر في العمالة الإقليمية.", "collocations": ["set off a domino effect", "fear a domino effect"], "synonyms": ["cascade"], "antonyms": [], "tags": ["causality", "idioms"]},
    {"headword": "root origin", "pronunciation": "/ruːt ˈɒrɪdʒɪn/", "partOfSpeech": "noun", "definition": "The primary, fundamental source or starting point of a complex phenomenon.", "example": "Investigative historians traced the root origin of the dispute back to colonial border treaties.", "translation": "الأصل الجذري / المنبع الأساسي", "exampleArabic": "تتبع المؤرخون المحققون الأصل الجذري للنزاع وصولاً إلى معاهدات الحدود الاستعمارية.", "collocations": ["discover the root origin", "trace root origins"], "synonyms": ["fundamental genesis"], "antonyms": ["superficial symptom"], "tags": ["origins", "history"]},
    {"headword": "catalytic event", "pronunciation": "/ˌkætəˈlɪtɪk ɪˈvent/", "partOfSpeech": "noun", "definition": "An occurrence that decisively accelerates a process or precipitates dramatic change.", "example": "The unexpected viral lecture served as a catalytic event for universal open-access learning.", "translation": "حدث محفّز ومسرّع للتحول", "exampleArabic": "كانت المحاضرة واسعة الانتشار بمثابة حدث محفّز ومسرّع لتعليم مجاني ومفتوح للجميع.", "collocations": ["act as a catalytic event", "crucial catalytic event"], "synonyms": ["transformative spark"], "antonyms": ["dampening factor"], "tags": ["catalyst", "transformation"]},
    {"headword": "primary trigger", "pronunciation": "/ˈpraɪməri ˈtrɪɡə/", "partOfSpeech": "noun", "definition": "The main event, statement, or circumstance that initiates a broader reaction.", "example": "The abrupt cancellation of agricultural subsidies was the primary trigger for the farm strikes.", "translation": "الشرارة والمحفز الأولي الرئيسي", "exampleArabic": "كان الإلغاء المفاجئ للدعم الزراعي هو المحفز الأولي الرئيسي لإضرابات المزارعين.", "collocations": ["identify the primary trigger", "serve as the primary trigger"], "synonyms": ["initial spark"], "antonyms": ["calming factor"], "tags": ["causality", "crisis"]},
    {"headword": "antecedent", "pronunciation": "/ˌæntɪˈsiːdnt/", "partOfSpeech": "noun", "definition": "A thing or event that existed before or logically preceded another.", "example": "The political upheavals of the nineteenth century were direct antecedents to modern democracy.", "translation": "سابقة تاريخية / ظرف ممهد لما بعده", "exampleArabic": "كانت الاضطرابات السياسية في القرن التاسع عشر سوابق مباشرة مهدت للديمقراطية الحديثة.", "collocations": ["historical antecedent", "trace antecedents"], "synonyms": ["precursor", "forerunner"], "antonyms": ["sequel"], "tags": ["history", "logic"]},
    {"headword": "underlying cause", "pronunciation": "/ˌʌndəˈlaɪɪŋ kɔːz/", "partOfSpeech": "noun", "definition": "The basic, foundational reason for something, usually hidden beneath surface symptoms.", "example": "Chronic sleep deprivation was the underlying cause of the pilot's delayed reaction time.", "translation": "السبب الدفين الكامن وراء الأمر", "exampleArabic": "كان الحرمان المزمن من النوم هو السبب الدفين الكامن وراء تأخر سرعة استجابة الطيار.", "collocations": ["address the underlying cause", "root underlying cause"], "synonyms": ["fundamental factor"], "antonyms": ["incidental factor"], "tags": ["analysis", "medicine"]},
    {"headword": "direct consequence", "pronunciation": "/dəˈrekt ˈkɒnsɪkwəns/", "partOfSpeech": "noun", "definition": "A result that proceeds immediately and straight from a specific cause or action.", "example": "Severe traffic congestion was the direct consequence of the sudden highway lane closures.", "translation": "نتيجة مباشرة وفورية", "exampleArabic": "كان الازدحام المروري الخانق نتيجة مباشرة وفورية لإغلاق مسارات الطريق السريع المفاجئ.", "collocations": ["as a direct consequence of", "inevitable direct consequence"], "synonyms": ["immediate result"], "antonyms": ["indirect byproduct"], "tags": ["outcomes", "logic"]},
    {"headword": "inevitable aftermath", "pronunciation": "/ɪnˈevɪtəbl ˈɑːftəmæθ/", "partOfSpeech": "noun", "definition": "The unavoidable period or condition following a traumatic, momentous, or disastrous event.", "example": "Economic stagnation was the inevitable aftermath of the protracted civil conflict.", "translation": "التبعات الحتمية اللاحقة", "exampleArabic": "كان الركود الاقتصادي من التبعات الحتمية اللاحقة للنزاع الداخلي الذي طال أمده.", "collocations": ["deal with the inevitable aftermath", "during the inevitable aftermath"], "synonyms": ["unavoidable fallout"], "antonyms": [], "tags": ["outcomes", "events"]},
    {"headword": "long-term fallout", "pronunciation": "/ˌlɒŋ ˈtɜːm ˈfɔːlaʊt/", "partOfSpeech": "noun", "definition": "The extended, lingering negative consequences of an action, scandal, or catastrophe.", "example": "The financial sector spent an entire decade recovering from the long-term fallout of the credit crash.", "translation": "التداعيات والآثار السلبية طويلة الأجل", "exampleArabic": "أمضى القطاع المالي عقداً كاملاً في التعافي من التداعيات السلبية طويلة الأجل لانهيار الائتمان.", "collocations": ["mitigate long-term fallout", "suffer long-term fallout"], "synonyms": ["extended repercussions"], "antonyms": ["fleeting impact"], "tags": ["outcomes", "economics"]},
    {"headword": "secondary repercussion", "pronunciation": "/ˈsekəndri ˌriːpəˈkʌʃn/", "partOfSpeech": "noun", "definition": "An unintended or indirect consequence occurring after the main impact of an event.", "example": "Higher insurance premiums were an unexpected secondary repercussion of the coastal storm.", "translation": "تداعيات وتبعات ثانوية غير مباشرة", "exampleArabic": "كان ارتفاع أقساط التأمين من التداعيات الثانوية غير المباشرة للعاصفة الساحلية.", "collocations": ["face secondary repercussions", "serious secondary repercussions"], "synonyms": ["indirect reverberation"], "antonyms": ["primary impact"], "tags": ["effects", "complexity"]},
    {"headword": "knock-on effect", "pronunciation": "/ˈnɒk ɒn ɪˈfekt/", "partOfSpeech": "noun", "definition": "A secondary, indirect, or cumulative result caused by an earlier action.", "example": "Flight delays in Frankfurt had a knock-on effect across five international transit hubs.", "translation": "أثر ارتدادي متتابع / صدى غير مباشر", "exampleArabic": "أحدث تأخر الرحلات في فرانكفورت أثراً ارتدادياً متتابعاً عبر خمس محطات ترانزيت دولية.", "collocations": ["have a knock-on effect", "severe knock-on effects"], "synonyms": ["chain reaction", "ripple effect"], "antonyms": [], "tags": ["logistics", "consequences"]},
    {"headword": "snowball effect", "pronunciation": "/ˈsnəʊbɔːl ɪˈfekt/", "partOfSpeech": "noun", "definition": "A situation in which something increases in size or importance at an accelerating rate.", "example": "A small accounting discrepancy generated a snowball effect that brought down the firm.", "translation": "تأثير كرة الثلج المتدحرجة المتضخمة", "exampleArabic": "أحدث فارق حسابي صغير تأثيراً ككرة الثلج المتضخمة أدى في النهاية لإسقاط الشركة.", "collocations": ["create a snowball effect", "snowball effect gained momentum"], "synonyms": ["exponential growth"], "antonyms": ["stabilizing deceleration"], "tags": ["growth", "idioms"]},
    {"headword": "butterfly effect", "pronunciation": "/ˈbʌtəflaɪ ɪˈfekt/", "partOfSpeech": "noun", "definition": "The chaotic scientific principle that a minute localized change can cause large effects elsewhere.", "example": "Meteorologists study the butterfly effect to explain how slight temperature shifts spark hurricanes.", "translation": "أثر الفراشة (في نظرية الفوضى)", "exampleArabic": "يدرس خبراء الأرصاد الجوية أثر الفراشة لتفسير كيف تُطلق تغيرات طفيفة في الحرارة أعاصير عاتية.", "collocations": ["demonstrate the butterfly effect", "classic butterfly effect"], "synonyms": ["sensitive dependence"], "antonyms": [], "tags": ["science", "chaos"]},

    # Causality Verbs & Mechanisms (15)
    {"headword": "causality", "pronunciation": "/kɔːˈzæləti/", "partOfSpeech": "noun", "definition": "The relationship between cause and effect; the principle that everything has a cause.", "example": "Epidemiologists established clear causality between smoking and pulmonary diseases.", "translation": "السببية / علاقة العلة والمعلول", "exampleArabic": "أثبت علماء الأوبئة سببية قاطعة بين التدخين والأمراض الرئوية.", "collocations": ["establish causality", "prove direct causality"], "synonyms": ["causal relationship"], "antonyms": ["random correlation"], "tags": ["science", "logic"]},
    {"headword": "causation", "pronunciation": "/kɔːˈzeɪʃn/", "partOfSpeech": "noun", "definition": "The action of causing something; the relation between cause and effect in law or logic.", "example": "Correlation does not necessarily imply causation in statistical social sciences.", "translation": "التسبيب / إحداث الأثر", "exampleArabic": "لا يعني الارتباط الإحصائي بالضرورة وجود تسبيب وعلة في العلوم الاجتماعية.", "collocations": ["correlation vs causation", "prove causation"], "synonyms": ["agency", "causality"], "antonyms": ["coincidence"], "tags": ["statistics", "logic"]},
    {"headword": "spillover effect", "pronunciation": "/ˈspɪləʊvər ɪˈfekt/", "partOfSpeech": "noun", "definition": "An impact that seemingly unrelated events have on greater systems or outside parties.", "example": "Research funding in aerospace generated a lucrative spillover effect in consumer electronics.", "translation": "أثر الامتداد والفيضان الخارجي", "exampleArabic": "ولّد تمويل الأبحاث في علوم الفضاء أثراً امتدادياً مربحاً في الإلكترونيات الاستهلاكية.", "collocations": ["positive spillover effect", "cross-border spillover effect"], "synonyms": ["external effect"], "antonyms": ["contained impact"], "tags": ["economics", "innovation"]},
    {"headword": "collateral damage", "pronunciation": "/kəˈlætərəl ˈdæmɪdʒ/", "partOfSpeech": "noun", "definition": "Inadvertent, incidental damage, injury, or loss suffered by bystanders or innocent parties.", "example": "The currency devaluation caused terrible collateral damage to modest middle-class savings.", "translation": "أضرار جانبية / خسائر تبعية غير مقصودة", "exampleArabic": "تسبب خفض قيمة العملة في أضرار جانبية فادحة لمدخرات الطبقة المتوسطة البسيطة.", "collocations": ["suffer collateral damage", "inflict collateral damage"], "synonyms": ["incidental harm"], "antonyms": ["targeted outcome"], "tags": ["consequences", "harm"]},
    {"headword": "byproduct", "pronunciation": "/ˈbaɪprɒdʌkt/", "partOfSpeech": "noun", "definition": "An incidental or secondary product made in the manufacture or synthesis of something else.", "example": "Renewable methane gas was an unexpected byproduct of industrial water filtration.", "translation": "منتج ثانوي / ناتج عرضي", "exampleArabic": "كان غاز الميثان المتجدد منتجاً ثانوياً غير متوقع لتنقية مياه المصانع.", "collocations": ["useful byproduct", "natural byproduct"], "synonyms": ["side effect", "spin-off"], "antonyms": ["primary product"], "tags": ["industry", "science"]},
    {"headword": "culmination", "pronunciation": "/ˌkʌlmɪˈneɪʃn/", "partOfSpeech": "noun", "definition": "The highest or climatic point of something, especially attained after a long struggle.", "example": "Winning the Nobel Prize was the glorious culmination of her thirty-year biochemical career.", "translation": "ذروة التتويج / مسك الختام بعد جهد", "exampleArabic": "كان الفوز بجائزة نوبل ذروة التتويج المجيد لمسيرتها الكيموحيوية الممتدة لثلاثين عاماً.", "collocations": ["mark the culmination of", "reach its culmination"], "synonyms": ["climax", "pinnacle"], "antonyms": ["initial inception"], "tags": ["achievement", "outcomes"]},
    {"headword": "precipitating factor", "pronunciation": "/prɪˈsɪpɪteɪtɪŋ ˈfæktə/", "partOfSpeech": "noun", "definition": "An element that causes an undesirable event or clinical crisis to happen suddenly.", "example": "Dehydration was the precipitating factor that caused the marathon runner's collapse.", "translation": "العامل المعجل بحدوث الأزمة", "exampleArabic": "كان الجفاف هو العامل المعجل الذي تسبب في انهيار عداء الماراثون فجأة.", "collocations": ["major precipitating factor", "act as a precipitating factor"], "synonyms": ["trigger factor"], "antonyms": ["mitigating element"], "tags": ["medicine", "crisis"]},
    {"headword": "prime mover", "pronunciation": "/ˌpraɪm ˈmuːvə/", "partOfSpeech": "noun", "definition": "A person or thing that initiates a major development or action.", "example": "The governor was the prime mover behind the statewide high-speed rail initiative.", "translation": "المحرك والمبادر الرئيسي", "exampleArabic": "كان المحافظ هو المحرك الرئيسي والمبادر وراء مشروع قطار السرعة الفائقة بالولاية.", "collocations": ["act as the prime mover", "acknowledged prime mover"], "synonyms": ["instigator", "driving force"], "antonyms": ["passive observer"], "tags": ["leadership", "causality"]},
    {"headword": "contributory cause", "pronunciation": "/kənˈtrɪbjətəri kɔːz/", "partOfSpeech": "noun", "definition": "A condition that helps bring about a result, though not solely sufficient on its own.", "example": "Slippery wet asphalt was a contributory cause in the multicar highway collision.", "translation": "سبب مساهم ومشارك في الحدث", "exampleArabic": "كان الأسفلت الزلق المبلل سبباً مساهماً في تصادم السيارات المتعددة على الطريق السريع.", "collocations": ["recognized contributory cause", "play a contributory cause"], "synonyms": ["partial factor"], "antonyms": ["sole cause"], "tags": ["legal", "causality"]},
    {"headword": "stem from", "pronunciation": "/stem frəm/", "partOfSpeech": "verb", "definition": "To originate from, be caused by, or develop out of something specific.", "example": "Many modern social frictions stem from technological alienation and hyper-polarization.", "translation": "ينبع من / يتفرع عن أصل", "exampleArabic": "تنبع العديد من الاحتكاكات الاجتماعية المعاصرة من الاغتراب التكنولوجي والاستقطاب الحاد.", "verbForms": {"v1": "stem from", "v2": "stemmed from", "v3": "stemmed from"}, "collocations": ["stem from childhood", "directly stem from"], "synonyms": ["originate in", "emanate from"], "antonyms": ["culminate in"], "tags": ["origins", "actions"]},
    {"headword": "originate from", "pronunciation": "/əˈrɪdʒɪneɪt frəm/", "partOfSpeech": "verb", "definition": "To have a specified beginning, genesis, or original source.", "example": "The mysterious viral outbreak was shown to originate from wildlife trading markets.", "translation": "ينشأ عن / يعود أصله إلى", "exampleArabic": "ثبت أن التفشي الفيروسي الغامض نشأ عن أسواق تجارة الحيوانات البرية.", "verbForms": {"v1": "originate from", "v2": "originated from", "v3": "originated from"}, "collocations": ["originate from ancient rituals", "originate from laboratory"], "synonyms": ["spring from"], "antonyms": ["terminate in"], "tags": ["origins", "actions"]},
    {"headword": "give rise to", "pronunciation": "/ɡɪv raɪz tuː/", "partOfSpeech": "verb", "definition": "To cause or induce something to happen, exist, or develop.", "example": "The novel algorithm gave rise to an entire generation of generative visual tools.", "translation": "يؤدي إلى ظهور / يفسح المجال لـ", "exampleArabic": "أدت الخوارزمية المبتكرة إلى ظهور جيل كامل من أدوات التوليد البصري والذكاء الاصطناعي.", "verbForms": {"v1": "give rise to", "v2": "gave rise to", "v3": "given rise to"}, "collocations": ["give rise to speculation", "give rise to new industries"], "synonyms": ["engender", "provoke"], "antonyms": ["suppress"], "tags": ["creation", "actions"]},
    {"headword": "bring about", "pronunciation": "/brɪŋ əˈbaʊt/", "partOfSpeech": "verb", "definition": "To cause something momentous to occur; to produce change.", "example": "Dedicated grassroots campaigners brought about landmark civil rights legislation.", "translation": "يحدث / يولد ويسبب تغييراً جذرياً", "exampleArabic": "أحدث النشطاء الشعبيون المتفانون تغييراً وأقروا تشريعات تاريخية للحقوق المدنية.", "verbForms": {"v1": "bring about", "v2": "brought about", "v3": "brought about"}, "collocations": ["bring about change", "bring about revolution"], "synonyms": ["cause", "effectuate"], "antonyms": ["prevent"], "tags": ["change", "actions"]},
    {"headword": "spark off", "pronunciation": "/spɑːk ɒf/", "partOfSpeech": "verb", "definition": "To suddenly provoke, stimulate, or unleash an energetic event or conflict.", "example": "The referee's biased penalty call sparked off widespread riots in the grandstands.", "translation": "يشعل فتيل / يطلق شرارة أزمة", "exampleArabic": "أشعل قرار ركلة الجزاء المنحاز من الحكم فتيل أعمال شغب واسعة في المدرجات.", "verbForms": {"v1": "spark off", "v2": "sparked off", "v3": "sparked off"}, "collocations": ["spark off protests", "spark off debate"], "synonyms": ["ignite", "trigger"], "antonyms": ["extinguish"], "tags": ["conflict", "actions"]},
    {"headword": "trigger off", "pronunciation": "/ˈtrɪɡər ɒf/", "partOfSpeech": "verb", "definition": "To set in motion a sequence of explosive actions or emotional responses.", "example": "A sudden supply chain rumor triggered off aggressive consumer hoarding in supermarkets.", "translation": "يستحث / يُطلق العنان لموجة تصرفات", "exampleArabic": "استحثت شائعة مفاجئة عن سلاسل الإمداد موجة اكتناز وتخزين شرس من المستهلكين.", "verbForms": {"v1": "trigger off", "v2": "triggered off", "v3": "triggered off"}, "collocations": ["trigger off panic", "trigger off inflation"], "synonyms": ["set off", "precipitate"], "antonyms": ["quench"], "tags": ["behavior", "actions"]},

    # Impacts, Repercussions & Causal Links (20)
    {"headword": "culminate in", "pronunciation": "/ˈkʌlmɪneɪt ɪn/", "partOfSpeech": "verb", "definition": "To reach a final climatic stage or decisive result after sustained development.", "example": "Decades of escalating diplomatic friction culminated in an all-out trade embargo.", "translation": "ينتهي إلى ذروته في / يبلغ أوجه في", "exampleArabic": "بلغت عقود من الاحتكاك الدبلوماسي المتصاعد ذروتها في فرض حظر تجاري شامل.", "verbForms": {"v1": "culminate in", "v2": "culminated in", "v3": "culminated in"}, "collocations": ["culminate in victory", "culminate in disaster"], "synonyms": ["climax with"], "antonyms": ["start with"], "tags": ["outcomes", "actions"]},
    {"headword": "precipitate crisis", "pronunciation": "/prɪˈsɪpɪteɪt ˈkraɪsɪs/", "partOfSpeech": "verb", "definition": "To cause a dangerous, turbulent crisis to happen suddenly and prematurely.", "example": "The unexpected resignation of the central bank governor precipitated a currency crisis.", "translation": "يُعجل بوقوع أزمة عاصفة", "exampleArabic": "عجلت الاستقالة غير المتوقعة لمحافظ البنك المركزي بوقوع أزمة عملة خانقة.", "verbForms": {"v1": "precipitate crisis", "v2": "precipitated crisis", "v3": "precipitated crisis"}, "collocations": ["precipitate a constitutional crisis", "threaten to precipitate crisis"], "synonyms": ["hasten breakdown"], "antonyms": ["delay crisis"], "tags": ["crisis", "actions"]},
    {"headword": "unleash consequences", "pronunciation": "/ʌnˈliːʃ ˈkɒnsɪkwənsɪz/", "partOfSpeech": "verb", "definition": "To release or trigger a torrent of powerful, uncontrollable outcomes.", "example": "Careless deforestation unleashed devastating ecological consequences upon the river delta.", "translation": "يطلق العنان لعواقب مدمرة", "exampleArabic": "أطلقت إزالة الغابات المتهورة العنان لعواقب بيئية مدمرة على دلتا النهر.", "verbForms": {"v1": "unleash consequences", "v2": "unleashed consequences", "v3": "unleashed consequences"}, "collocations": ["unleash unforeseen consequences", "unleash destructive consequences"], "synonyms": ["let loose repercussions"], "antonyms": ["contain damage"], "tags": ["destruction", "actions"]},
    {"headword": "ensue from", "pronunciation": "/ɪnˈsjuː frəm/", "partOfSpeech": "verb", "definition": "To happen or occur afterwards as a direct logical consequence of something.", "example": "Tremendous civic pride ensued from the national soccer team's continental triumph.", "translation": "ينتج عن / يترتب تالياً على", "exampleArabic": "ترتب فخر مدني وشعبي هائل تالياً على الفوز القاري لمنتخب كرة القدم الوطني.", "verbForms": {"v1": "ensue from", "v2": "ensued from", "v3": "ensued from"}, "collocations": ["chaos ensued from", "difficulties ensue from"], "synonyms": ["follow from", "result from"], "antonyms": ["precede"], "tags": ["outcomes", "actions"]},
    {"headword": "correlate with", "pronunciation": "/ˈkɒrəleɪt wɪð/", "partOfSpeech": "verb", "definition": "To have a mutual relationship or connection, where one thing affects or depends on another.", "example": "High levels of childhood literacy correlate directly with lifetime socioeconomic security.", "translation": "يرتبط ارتباطاً طردياً مع", "exampleArabic": "ترتبط المستويات المرتفعة من محو أمية الأطفال ارتباطاً طردياً بالأمان الاجتماعي طوال الحياة.", "verbForms": {"v1": "correlate with", "v2": "correlated with", "v3": "correlated with"}, "collocations": ["strongly correlate with", "positively correlate with"], "synonyms": ["link with"], "antonyms": ["diverge from"], "tags": ["statistics", "actions"]},
    {"headword": "attributable to", "pronunciation": "/əˈtrɪbjətəbl tuː/", "partOfSpeech": "adjective", "definition": "Capable of being considered as caused by something specific.", "example": "The factory's record quarterly output was largely attributable to automated robotic welding.", "translation": "يُعزى إلى / ناجم عن", "exampleArabic": "كان الإنتاج الفصلي القياسي للمصنع يُعزى إلى حد كبير للحام الآلي المؤتمت.", "collocations": ["largely attributable to", "directly attributable to"], "synonyms": ["ascribable to", "due to"], "antonyms": [], "tags": ["causality", "logic"]},
    {"headword": "ascribe to", "pronunciation": "/əˈskraɪb tuː/", "partOfSpeech": "verb", "definition": "To attribute something to a cause, person, or origin.", "example": "Philosophers ascribe the emergence of written morality to early agricultural settlements.", "translation": "يعزو الشيء إلى / ينسب الفضل أو السبب لـ", "exampleArabic": "يعزو الفلاسفة ظهور الأخلاق المكتوبة للمستوطنات الزراعية البشرية الأولى.", "verbForms": {"v1": "ascribe to", "v2": "ascribed to", "v3": "ascribed to"}, "collocations": ["ascribe success to", "ascribe failure to"], "synonyms": ["attribute to"], "antonyms": [], "tags": ["attribution", "actions"]},
    {"headword": "trace back to", "pronunciation": "/treɪs bæk tuː/", "partOfSpeech": "verb", "definition": "To discover the primary origin or beginning of something by backtracking its history.", "example": "Linguists can trace modern Romance vocabularies back to colloquial Latin dialects.", "translation": "يتتبع الشيء وصولاً إلى أصله وجذوره", "exampleArabic": "يستطيع علماء اللسانيات تتبع مفردات اللغات الرومانسية وصولاً للهجات اللاتينية العامية.", "verbForms": {"v1": "trace back to", "v2": "traced back to", "v3": "traced back to"}, "collocations": ["trace ancestry back to", "trace roots back to"], "synonyms": ["derive from"], "antonyms": [], "tags": ["history", "actions"]},
    {"headword": "resultant impact", "pronunciation": "/rɪˈzʌltənt ˈɪmpækt/", "partOfSpeech": "noun", "definition": "The forceful effect produced as an immediate outcome of an event or shock.", "example": "The drought was so severe that the resultant impact on crop yields devastated farmers.", "translation": "الأثر والوطأة المترتبة على الحدث", "exampleArabic": "كان الجفاف شديداً جداً لدرجة أن الأثر المترتب على محاصيل الحبوب دمر المزارعين.", "collocations": ["measure resultant impact", "severe resultant impact"], "synonyms": ["consequential effect"], "antonyms": [], "tags": ["outcomes", "analysis"]},
    {"headword": "downstream effect", "pronunciation": "/ˌdaʊnstriːm ɪˈfekt/", "partOfSpeech": "noun", "definition": "A consequence that happens later in time or further along a process.", "example": "Microplastic contamination in mountain streams has alarming downstream effects on sea life.", "translation": "الأثر المتدفق لاحقاً في المراحل التالية", "exampleArabic": "يخلف تلوث الجسيمات البلاستيكية في الجداول الجبلية آثاراً مقلقة تتدفق لاحقاً على الحياة البحرية.", "collocations": ["negative downstream effects", "monitor downstream effects"], "synonyms": ["subsequent outcome"], "antonyms": ["upstream cause"], "tags": ["environment", "systems"]},
    {"headword": "far-reaching impact", "pronunciation": "/ˌfɑː ˈriːtʃɪŋ ˈɪmpækt/", "partOfSpeech": "noun", "definition": "An extensive influence that extends over a wide area, duration, or population.", "example": "The invention of movable type printing had a far-reaching impact on literacy worldwide.", "translation": "أثر بعيد المدى وبالغ الامتداد", "exampleArabic": "كان لاختراع الطباعة بالحروف المتحركة أثر بعيد المدى وبالغ الامتداد على محو الأمية عالمياً.", "collocations": ["have a far-reaching impact", "profound far-reaching impact"], "synonyms": ["wide-ranging influence"], "antonyms": ["limited effect"], "tags": ["history", "transformation"]},
    {"headword": "profound effect", "pronunciation": "/prəˈfaʊnd ɪˈfekt/", "partOfSpeech": "noun", "definition": "A deeply rooted, powerful, and fundamental influence on thoughts or events.", "example": "Mentorship during her teenage years had a profound effect on her scientific career.", "translation": "أثر عميق وجوهري", "exampleArabic": "كان للإرشاد في سنوات مراهقتها أثر عميق وجوهري على مسيرتها العلمية.", "collocations": ["exert a profound effect", "profound effect on personality"], "synonyms": ["deep impression"], "antonyms": ["superficial touch"], "tags": ["transformation", "emotions"]},
    {"headword": "causal link", "pronunciation": "/ˈkɔːzl lɪŋk/", "partOfSpeech": "noun", "definition": "A verified relationship demonstrating that one event directly causes another.", "example": "Medical researchers discovered an undeniable causal link between asbestos and lung cancer.", "translation": "رابط سببي موثق", "exampleArabic": "اكتشف باحثو الطب رابطاً سببياً لا يمكن إنكاره بين ألياف الأسبستوس وسرطان الرئة.", "collocations": ["prove a causal link", "missing causal link"], "synonyms": ["causal connection"], "antonyms": ["unrelated correlation"], "tags": ["science", "logic"]},
    {"headword": "cause and effect relationship", "pronunciation": "/ˌkɔːz ənd ɪˈfekt rɪˈleɪʃnʃɪp/", "partOfSpeech": "noun", "definition": "A connection between events where the first brings about the occurrence of the second.", "example": "Science teaches children to examine the cause and effect relationship in nature.", "translation": "علاقة السبب بالنتيجة", "exampleArabic": "يعلم العلم الأطفال فحص واستكشاف علاقة السبب بالنتيجة في الطبيعة.", "collocations": ["analyze cause and effect relationship", "direct cause and effect relationship"], "synonyms": ["causal interaction"], "antonyms": [], "tags": ["logic", "education"]},
    {"headword": "correlative link", "pronunciation": "/kəˈrelətɪv lɪŋk/", "partOfSpeech": "noun", "definition": "A statistical connection showing two variables changing together without proving causation.", "example": "Statisticians observed a strong correlative link between ice cream sales and drowning rates.", "translation": "رابط ترابطي تلازمي", "exampleArabic": "لاحظ الإحصائيون رابطاً ترابطياً تلازمياً وثيقاً بين مبيعات المثلجات ومعدلات الغرق.", "collocations": ["identify a correlative link", "mere correlative link"], "synonyms": ["statistical association"], "antonyms": ["causal link"], "tags": ["statistics", "logic"]},
    {"headword": "direct catalyst", "pronunciation": "/dəˈrekt ˈkætəlɪst/", "partOfSpeech": "noun", "definition": "A substance, person, or event that immediately provokes or quickens change.", "example": "The viral documentary acted as a direct catalyst for nationwide animal welfare laws.", "translation": "محفز مباشر مسرع للحدث", "exampleArabic": "عمل الفيلم الوثائقي واسع الانتشار كمحفز مباشر لتشريعات حماية الحيوان على مستوى البلاد.", "collocations": ["serve as a direct catalyst", "direct catalyst for reform"], "synonyms": ["primary accelerator"], "antonyms": ["inhibitor"], "tags": ["change", "catalyst"]},
    {"headword": "contributing element", "pronunciation": "/kənˈtrɪbjuːtɪŋ ˈelɪmənt/", "partOfSpeech": "noun", "definition": "A component or factor that plays a role in generating a complex result.", "example": "Lack of adequate street lighting was a major contributing element to nighttime pedestrian collisions.", "translation": "عنصر مساهم ومشارك في النتيجة", "exampleArabic": "كان غياب إنارة الشوارع الكافية عنصراً مساهماً رئيسياً في حوادث المشاة الليلية.", "collocations": ["significant contributing element", "key contributing element"], "synonyms": ["partial component"], "antonyms": [], "tags": ["analysis", "causality"]},
    {"headword": "subsequent result", "pronunciation": "/ˈsʌbsɪkwənt rɪˈzʌlt/", "partOfSpeech": "noun", "definition": "An outcome or event that takes place after and as a result of an initial event.", "example": "The subsequent result of opening international trade was a surge in port container traffic.", "translation": "النتيجة اللاحقة المترتبة", "exampleArabic": "كانت النتيجة اللاحقة المترتبة على فتح التجارة الدولية هي طفرة في حركة الحاويات بالموانئ.", "collocations": ["expect subsequent results", "subsequent result of action"], "synonyms": ["ensuing consequence"], "antonyms": ["antecedent"], "tags": ["outcomes", "events"]},
    {"headword": "inevitable culmination", "pronunciation": "/ɪnˈevɪtəbl ˌkʌlmɪˈneɪʃn/", "partOfSpeech": "noun", "definition": "An ultimate conclusion or climax that was bound to happen given historical trends.", "example": "The treaty signing was the inevitable culmination of twenty rounds of secret diplomacy.", "translation": "الذروة الحتمية المقدرة سلفاً", "exampleArabic": "كان توقيع المعاهدة هو الذروة الحتمية المقدرة لعشرين جولة من الدبلوماسية السرية.", "collocations": ["represent the inevitable culmination", "inevitable culmination of events"], "synonyms": ["predestined climax"], "antonyms": [], "tags": ["climax", "history"]},
    {"headword": "unintended fallout", "pronunciation": "/ˌʌnɪnˈtendɪd ˈfɔːlaʊt/", "partOfSpeech": "noun", "definition": "The unexpected, adverse secondary consequences resulting from a plan.", "example": "The unintended fallout of strict urban rental caps was an acute shortage of rental units.", "translation": "التبعات والتداعيات السلبية غير المقصودة", "exampleArabic": "كانت التداعيات السلبية غير المقصودة للحدود الصارمة لإيجارات المدن نقصاً حاداً في الوحدات المعروضة.", "collocations": ["suffer unintended fallout", "manage unintended fallout"], "synonyms": ["unforeseen backlash"], "antonyms": ["planned benefit"], "tags": ["economics", "consequences"]}
]

grammar_65 = [
    {
        "title": "Cause and Effect: because of / due to / so...that",
        "titleArabic": "السبب والنتيجة (Cause and Effect: Because of / Due to / So...that / Such...that)",
        "explanation": "We use cause and effect structures to show the connection between reasons and their results: 1) 'Because of' and 'Due to' are followed by a noun phrase or gerund to state the cause ('The game was postponed because of heavy snow'; 'His success was due to diligent research'). Formal tip: 'Due to' traditionally follows the verb be ('The delay was due to fog'), while 'because of' modifies action verbs ('Flights were canceled because of fog'). 2) 'So + adjective / adverb + that' shows result ('The storm was so fierce that rooftops were ripped off'). 3) 'Such + (a/an) + adjective + noun + that' also shows result ('It was such a severe drought that rivers dried up completely').",
        "explanationArabic": "نستخدم تراكيب السبب والنتيجة لتوضيح العلاقة الحتمية بين الأسباب والنتائج المترتبة عليها: 1) Because of و Due to (بسبب / نظراً لـ): يتبعهما اسم أو مصدر (Noun / Gerund) للتعبير عن السبب. ملاحظة دقيقة: تقليدياً تأتي due to بعد فعل be (مثل: 'The delay was due to...'), بينما تأتي because of مع الأفعال الحركية (مثل: 'We canceled because of...'). 2) So + صفة أو ظرف + that (لدرجة أن): للتعبير عن أن شدة الصفة أنتجت نتيجة معينة ('The drought was so severe that crops failed'). 3) Such + صفة + اسم + that (لدرجة أن): تؤدي نفس وظيفة النتيجة ولكن مع وجود اسم موصوف ('It was such a complex problem that auditors took weeks').",
        "structures": [
            {"label": "Prepositional Cause · السبب بحرف الجر (Because of / Due to)", "pattern": "Clause + because of / due to + Noun Phrase (or Gerund)", "explanation": "States the causal reason using a noun or noun phrase.", "explanationArabic": "يذكر سبب الحدث باستخدام اسم أو شبه جملة اسمية."},
            {"label": "Intensive Result with Adjective · النتيجة بالصفة (So...that)", "pattern": "Subject + Verb + so + Adjective / Adverb + that + Result Clause", "explanation": "Shows how an intense quality directly produces an extreme outcome.", "explanationArabic": "يوضح كيف أدت شدة الصفة أو الحال مباشرة لحدوث نتيجة معينة."},
            {"label": "Intensive Result with Noun · النتيجة بالاسم (Such...that)", "pattern": "Subject + Verb + such + (a/an) + Adjective + Noun + that + Result Clause", "explanation": "Shows result using an intensified descriptive noun phrase.", "explanationArabic": "يعبر عن النتيجة باستخدام تركيب وصفي يتضمن اسماً مسبوقاً بـ such."}
        ],
        "examples": [
            {"sentence": "The river water levels dropped so low that electricity generators ceased operating.", "translation": "انخفضت مستويات مياه النهر لدرجة منخفضة جداً جعلت مولدات الكهرباء تتوقف عن العمل.", "usesVocabulary": []},
            {"sentence": "Because of automated sorting robotics, the factory warehouse experienced a remarkable surge in productivity.", "translation": "بسبب روبوتات الفرز المؤتمتة، شهد مستودع المصنع طفرة ملحوظة في الإنتاجية.", "usesVocabulary": []},
            {"sentence": "It was such an intense catalytic event that it unleashed consequences across the global supply chain.", "translation": "لقد كان حدثاً محفزاً بالغ الشدة لدرجة أنه أطلق العنان لعواقب عبر سلسلة التوريد العالمية.", "usesVocabulary": ["catalytic event", "unleash consequences"]},
            {"sentence": "The port container backlog was due to a severe ripple effect stemming from winter blizzards.", "translation": "كان تراكم حاويات الميناء ناجماً عن أثر تموجي حاد نابع من العواصف الثلجية الشتوية.", "usesVocabulary": ["ripple effect", "stem from"]}
        ],
        "commonMistakes": [
            {"wrong": "The flight was delayed because of the pilot was sick.", "right": "The flight was delayed because the pilot was sick. (OR: because of the pilot's illness)", "note": "'Because of' requires a noun phrase; use 'because' before a full clause (subject + verb).", "noteArabic": "تتطلب 'because of' اسماً بعدها؛ بينما يتبع 'because' جملة كاملة بها فاعل وفعل."},
            {"wrong": "It was so difficult problem that nobody could solve it.", "right": "It was such a difficult problem that nobody could solve it. (OR: The problem was so difficult that...)", "note": "Use 'such a + adjective + noun' before a countable noun, not 'so'.", "noteArabic": "استخدم 'such a + صفة + اسم' مع الأسماء المعدودة بدلاً من so."}
        ],
        "commonUsage": [
            "Scientific and environmental reporting: 'The coastal erosion was due to rising tides.' (تُستخدم لشرح الظواهر المناخية والبيئية.)",
            "Economic trend analysis: 'Inflation accelerated so rapidly that central banks hiked interest rates.' (تُستخدم لتحليل التداعيات الاقتصادية والمالية.)",
            "Root-cause investigations: 'The train derailment was directly attributable to metal fatigue in the rails.' (تُستخدم لتحديد أسباب الحوادث والأعطال.)"
        ]
    }
]

convs_65 = [
    {
        "title": "Investigating a Regional Power Outage",
        "titleArabic": "التحقيق في انقطاع التيار الكهربائي الإقليمي",
        "setting": "A utility grid director interrogates a chief electrical systems engineer following a blackout across three provinces.",
        "lines": [
            {"speaker": "Director", "text": "What was the primary trigger that initiated this blackout across three provinces?"},
            {"speaker": "Engineer", "text": "Because of a lightning strike on substation four, a transformer tripped off automatically."},
            {"speaker": "Director", "text": "How did a localized substation trip spark off such a massive domino effect?"},
            {"speaker": "Engineer", "text": "Transmission lines were so heavily loaded that a rapid chain reaction cascaded along the grid."},
            {"speaker": "Director", "text": "Was inadequate grid maintenance a contributory cause in this operational debacle?"},
            {"speaker": "Engineer", "text": "Yes, thermal sensor degradation was an underlying cause attributable to deferred maintenance."},
            {"speaker": "Director", "text": "We must manage the inevitable aftermath and prevent long-term fallout on industrial contracts."},
            {"speaker": "Engineer", "text": "Our engineers will trace the fault back to its root origin and install automated circuit disconnects."}
        ],
        "vocabularyUsed": ["primary trigger", "spark off", "domino effect", "chain reaction", "contributory cause", "underlying cause", "attributable to", "inevitable aftermath", "long-term fallout", "trace back to", "root origin"]
    },
    {
        "title": "Analyzing an Economic Shock Wave",
        "titleArabic": "تحليل موجة صدمة اقتصادية في الأسواق",
        "setting": "Two macroeconomic analysts discuss the fallout of a foreign central bank's currency devaluation on domestic commerce.",
        "lines": [
            {"speaker": "Analyst A", "text": "The currency devaluation was such an abrupt policy shift that it produced an immediate ripple effect."},
            {"speaker": "Analyst B", "text": "Indeed; import tariffs were directly responsible for unleashing destructive consequences on domestic manufacturers."},
            {"speaker": "Analyst A", "text": "Did the central bank anticipate the negative downstream effect on consumer inflation?"},
            {"speaker": "Analyst B", "text": "They dismissed it as mere collateral damage, but the resultant impact on grocery prices is staggering."},
            {"speaker": "Analyst A", "text": "Rising raw material costs are a natural byproduct of such reckless monetary experiments."},
            {"speaker": "Analyst B", "text": "Economists can clearly identify a causal link connecting monetary expansion with commodity spikes."},
            {"speaker": "Analyst A", "text": "If inflation continues, it will precipitate a severe crisis across retail supply chains."},
            {"speaker": "Analyst B", "text": "Let us hope fiscal stimulus will bring about stability before unemployment accelerates."}
        ],
        "vocabularyUsed": ["ripple effect", "unleash consequences", "downstream effect", "collateral damage", "resultant impact", "byproduct", "causal link", "precipitate crisis", "bring about"]
    },
    {
        "title": "Tracing Technological Evolution",
        "titleArabic": "تتبع مسار التطور التكنولوجي وجذوره",
        "setting": "A science historian interviews a pioneering computer scientist regarding the genesis of machine learning.",
        "lines": [
            {"speaker": "Historian", "text": "Can we trace the emergence of artificial neural networks back to early biological research?"},
            {"speaker": "Scientist", "text": "Absolutely; modern algorithms stem directly from mathematical models of cerebral cortex neurons."},
            {"speaker": "Historian", "text": "What was the direct catalyst that accelerated deep learning in the early two thousands?"},
            {"speaker": "Scientist", "text": "The availability of graphical processing chips was a catalytic event that gave rise to rapid training models."},
            {"speaker": "Historian", "text": "Has generative intelligence exerted a profound effect upon modern scientific research?"},
            {"speaker": "Scientist", "text": "It has had such a far-reaching impact that every discipline from oncology to astrophysics is transformed."},
            {"speaker": "Historian", "text": "Many breakthroughs correlate with open-source software libraries, do they not?"},
            {"speaker": "Scientist", "text": "Yes, open collaboration was the prime mover that enabled this historic technological culmination."}
        ],
        "vocabularyUsed": ["trace back to", "stem from", "direct catalyst", "catalytic event", "give rise to", "profound effect", "far-reaching impact", "correlate with", "prime mover", "culmination"]
    }
]

paras_65 = [
    {
        "title": "The Interconnected Complexity of Causality",
        "titleArabic": "التعقيد المترابط لشبكات السببية والنتائج",
        "text": "In complex ecological and economic systems, identifying the single root origin of a catastrophe is often misleading. While an unexpected accident may act as a primary trigger, the underlying cause usually stems from systemic fragility accumulated over decades. Due to the delicate sensitivity of natural equilibria, even a minor localized perturbation can generate a dramatic butterfly effect. When a critical threshold collapses, a rapid chain reaction ensues, producing a devastating domino effect and spreading an uncontrollable ripple effect across dependent industries. Understanding the deep cause and effect relationship in nature teaches humanity to manage unintended fallout with humility.",
        "vocabularyUsed": ["root origin", "primary trigger", "underlying cause", "stem from", "butterfly effect", "chain reaction", "domino effect", "ripple effect", "cause and effect relationship", "unintended fallout"]
    },
    {
        "title": "Cascading Failures and Economic Spillover",
        "titleArabic": "الانهيارات المتتالية وآثار العدوى الاقتصادية",
        "text": "When a major sovereign financial institution becomes insolvent, the resultant impact on international markets is never confined to domestic borders. Because of interconnected banking networks, financial panic produces an acute spillover effect that triggers off credit rationing worldwide. Small regional enterprises that had no direct exposure to the troubled assets suddenly suffer devastating collateral damage. A small regulatory oversight can create a dangerous snowball effect that culminates in an all-out global liquidity squeeze. Economists who study market causation warn that secondary repercussions often inflict far greater harm than the initial localized catalytic event.",
        "vocabularyUsed": ["resultant impact", "spillover effect", "trigger off", "collateral damage", "snowball effect", "culminate in", "causation", "secondary repercussion", "catalytic event"]
    },
    {
        "title": "Technological Catalysts and Historical Culminations",
        "titleArabic": "المحفزات التكنولوجية وذروة التحولات التاريخية",
        "text": "Throughout human history, monumental civilizational leaps are rarely attributable to isolated occurrences. When visionary inventors synthesize decades of antecedent discoveries, their innovative synthesis acts as a direct catalyst for profound societal transformation. The Industrial Revolution was such a powerful historic epoch that it gave rise to modern urban civilization and brought about unprecedented scientific advances. Decades of labor reforms and technological innovations reached an inevitable culmination in modern workplace protections, exerting a far-reaching impact and profound effect on the quality of human life.",
        "vocabularyUsed": ["attributable to", "antecedent", "direct catalyst", "give rise to", "bring about", "inevitable culmination", "far-reaching impact", "profound effect"]
    }
]

# Write Day 65
write_day(65, vocab_65, grammar_65, convs_65, paras_65)

# ==============================================================================
# DAY 66: News and Media (Headlines and reporting events)
# Grammar: ["Reported Speech Review (Reporting News)"]
# ==============================================================================
vocab_66 = [
    # Newsroom, Formats & Journalism Roles (15)
    {"headword": "newsroom", "pronunciation": "/ˈnjuːzruːm/", "partOfSpeech": "noun", "definition": "The central office where journalists, editors, and reporters assemble to prepare news broadcasts or papers.", "example": "The frantic newsroom fell silent when the foreign correspondent reported that peace treaties had been ratified.", "translation": "غرفة الأخبار / صالة التحرير الصحفي", "exampleArabic": "ساد الصمت صالة التحرير المزدحمة عندما أفاد المراسل الخارجي بأنه تم التصديق على معاهدات السلام.", "collocations": ["bustling newsroom", "inside the newsroom"], "synonyms": ["editorial office"], "antonyms": [], "tags": ["journalism", "media"]},
    {"headword": "scoop", "pronunciation": "/skuːp/", "partOfSpeech": "noun", "definition": "An exclusive, important news story discovered and published before any rival media outlet.", "example": "The young investigative reporter secured a major scoop when government insiders leaked budget figures.", "translation": "سبق صحفي حصري / انفراد إخباري", "exampleArabic": "حقق الصحفي الاستقصائي الشاب سبقاً صحفياً كبيراً عندما سرب مسؤولون حكوميون أرقام الميزانية.", "collocations": ["major scoop", "exclusive scoop"], "synonyms": ["exclusive story"], "antonyms": [], "tags": ["news", "reporting"]},
    {"headword": "exclusive report", "pronunciation": "/ɪkˈskluːsɪv rɪˈpɔːt/", "partOfSpeech": "noun", "definition": "A detailed journalistic article published solely by a single media organization.", "example": "The evening broadcaster announced that their exclusive report would expose offshore tax shelters.", "translation": "تقرير إخباري حصري", "exampleArabic": "أعلن مذيع المساء أن تقريرهم الحصري سيكشف عن الملاذات الضريبية في الخارج.", "collocations": ["broadcast an exclusive report", "feature an exclusive report"], "synonyms": ["sole coverage"], "antonyms": ["syndicated story"], "tags": ["media", "exclusives"]},
    {"headword": "editorial board", "pronunciation": "/ˌedɪˈtɔːriəl bɔːd/", "partOfSpeech": "noun", "definition": "A committee of senior editors who decide the newspaper's official editorial policy and stance.", "example": "The newspaper's editorial board stated that they endorsed the municipal education bond.", "translation": "مجلس التحرير / هيئة التحرير", "exampleArabic": "ذكر مجلس تحرير الصحيفة أنهم يؤيدون سندات التعليم البلدية.", "collocations": ["opinion of the editorial board", "editorial board meeting"], "synonyms": ["senior editors committee"], "antonyms": [], "tags": ["journalism", "leadership"]},
    {"headword": "investigative journalism", "pronunciation": "/ɪnˈvestɪɡətɪv ˈdʒɜːnəlɪzəm/", "partOfSpeech": "noun", "definition": "A style of journalism where reporters deeply investigate a single topic of public corruption or crime.", "example": "International bodies awarded prestigious prizes to the team for their fearless investigative journalism.", "translation": "الصحافة الاستقصائية", "exampleArabic": "منحت الهيئات الدولية جوائز مرموقة للفريق على صحافتهم الاستقصائية الجريئة.", "collocations": ["prize-winning investigative journalism", "pursue investigative journalism"], "synonyms": ["muckraking", "in-depth reporting"], "antonyms": ["shallow tabloid gossip"], "tags": ["journalism", "profession"]},
    {"headword": "syndicated column", "pronunciation": "/ˈsɪndɪkeɪtɪd ˈkɒləm/", "partOfSpeech": "noun", "definition": "A regular article or commentary published simultaneously in multiple regional and global periodicals.", "example": "Her syndicated column appeared in over two hundred metropolitan daily newspapers.", "translation": "عمود صحفي موزع ومطبوع في عدة صحف", "exampleArabic": "نُشر عمودها الصحفي الموزع في أكثر من مائتي صحيفة يومية في كبرى المدن.", "collocations": ["write a syndicated column", "popular syndicated column"], "synonyms": ["widely circulated column"], "antonyms": [], "tags": ["press", "writing"]},
    {"headword": "media outlet", "pronunciation": "/ˈmiːdiə ˈaʊtlet/", "partOfSpeech": "noun", "definition": "A publication, television channel, radio station, or digital website that broadcasts news to the public.", "example": "Every major media outlet reported that parliament had dissolved ahead of snap elections.", "translation": "منفذ إعلامي / وسيلة إعلامية", "exampleArabic": "أفاد كل منفذ إعلامي رئيسي بأن البرلمان قد حُل تمهيداً لانتخابات مبكرة.", "collocations": ["independent media outlet", "reputable media outlet"], "synonyms": ["news organization"], "antonyms": [], "tags": ["media", "industry"]},
    {"headword": "tabloid", "pronunciation": "/ˈtæblɔɪd/", "partOfSpeech": "noun", "definition": "A popular newspaper format known for sensational headlines, celebrity gossip, and bold photos.", "example": "Tabloids claimed that the royal couple had separated, but official spokespersons denied the rumor.", "translation": "صحيفة شعبية مثيرة للفضائح (تابلويد)", "exampleArabic": "زعمت الصحف الشعبية الصفراء أن الزوجين الملكيين قد انفصلا، لكن المتحدثين الرسميين نفوا الشائعة.", "collocations": ["tabloid sensationalism", "read tabloids"], "synonyms": ["yellow press"], "antonyms": ["broadsheet", "quality press"], "tags": ["press", "sensationalism"]},
    {"headword": "broadsheet", "pronunciation": "/ˈbrɔːdʃiːt/", "partOfSpeech": "noun", "definition": "A standard large-format quality newspaper regarded as more serious, rigorous, and intellectual.", "example": "Respected broadsheets dedicated their front pages to in-depth analysis of the climate conference.", "translation": "صحيفة رصينة كبيرة القطع / صحافة جادة", "exampleArabic": "خصصت الصحف الرصينة الكبيرة صفحاتها الأولى للتحليل المتعمق لمؤتمر المناخ.", "collocations": ["respected broadsheet", "national broadsheet"], "synonyms": ["quality paper"], "antonyms": ["tabloid"], "tags": ["press", "journalism"]},
    {"headword": "circulation figure", "pronunciation": "/ˌsɜːkjəˈleɪʃn ˈfɪɡə/", "partOfSpeech": "noun", "definition": "The audited number of copies of a publication distributed on an average day.", "example": "Although digital readership surged, the newspaper's print circulation figure declined ten percent.", "translation": "أرقام التوزيع والمبيعات للصحيفة", "exampleArabic": "على الرغم من طفرة القراءات الرقمية، انخفضت أرقام التوزيع الورقي للصحيفة بنسبة عشرة بالمائة.", "collocations": ["audit circulation figures", "high circulation figure"], "synonyms": ["distribution count"], "antonyms": [], "tags": ["publishing", "business"]},
    {"headword": "live coverage", "pronunciation": "/ˌlaɪv ˈkʌvərɪdʒ/", "partOfSpeech": "noun", "definition": "Real-time broadcasting of an ongoing event on television, radio, or streaming channels.", "example": "Networks interrupted regular programming to provide live coverage of the international summit.", "translation": "تغطية حية ومباشرة على الهواء", "exampleArabic": "قطعت الشبكات برامجها المعتادة لتقديم تغطية حية ومباشرة للقمة الدولية.", "collocations": ["provide live coverage", "continuous live coverage"], "synonyms": ["real-time broadcast"], "antonyms": ["recorded replay"], "tags": ["broadcasting", "events"]},
    {"headword": "press briefing", "pronunciation": "/ˈpres ˌbriːfɪŋ/", "partOfSpeech": "noun", "definition": "A meeting conducted by government or corporate officials to give informational updates to reporters.", "example": "During the morning press briefing, the press secretary confirmed that bilateral talks had concluded.", "translation": "إيجاز صحفي / مؤتمر إعلامي موجز", "exampleArabic": "خلال الإيجاز الصحفي الصباحي، أكد السكرتير الصحفي أن المحادثات الثنائية قد اختتمت.", "collocations": ["attend a press briefing", "daily press briefing"], "synonyms": ["news conference"], "antonyms": [], "tags": ["government", "pr"]},
    {"headword": "on the record", "pronunciation": "/ˌɒn ðə ˈrekɔːd/", "partOfSpeech": "phrase", "definition": "Information stated officially that may be openly attributed to and quoted from the speaker by name.", "example": "The senator agreed to speak on the record, stating that he would oppose the proposed tariff bill.", "translation": "تصريح رسمي علني للنشر والاقتباس بالاسم", "exampleArabic": "وافق السيناتور على الحديث علناً للنشر، مصرحاً بأنه سيعارض مشروع قانون الرسوم المقترح.", "collocations": ["speak on the record", "state on the record"], "synonyms": ["officially quoted"], "antonyms": ["off the record"], "tags": ["journalism", "ethics"]},
    {"headword": "off the record", "pronunciation": "/ˌɒf ðə ˈrekɔːd/", "partOfSpeech": "phrase", "definition": "Information given in strict confidence that may not be quoted, released, or attributed to the source.", "example": "The general disclosed off the record that troops would reposition before morning dawn.", "translation": "حديث غير رسمي وغير مخصص للنشر / ليس للنشر", "exampleArabic": "كشف الجنرال في حديث غير مخصص للنشر أن القوات ستعيد تموضعها قبل فجر الصباح.", "collocations": ["tell someone off the record", "strictly off the record"], "synonyms": ["in confidence"], "antonyms": ["on the record"], "tags": ["confidential", "ethics"]},
    {"headword": "embargoed news", "pronunciation": "/ɪmˈbɑːɡəʊd njuːz/", "partOfSpeech": "noun", "definition": "News or press material released in advance on condition that it is not published before a set time.", "example": "The research journal distributed embargoed news to science journalists forty-eight hours ahead of release.", "translation": "أخبار محظورة النشر حتى موعد محدد", "exampleArabic": "وزعت المجلة البحثية أخباراً محظورة النشر لصحفيي العلوم قبل ثمانٍ وأربعين ساعة من موعد النشر.", "collocations": ["respect embargoed news", "leak embargoed news"], "synonyms": ["pre-release material"], "antonyms": ["breaking news"], "tags": ["publishing", "rules"]},

    # Reporting Ethics, Verification & Scandals (15)
    {"headword": "anonymous source", "pronunciation": "/əˈnɒnɪməs sɔːs/", "partOfSpeech": "noun", "definition": "An unidentified person who provides confidential information to a journalist under a guarantee of privacy.", "example": "An anonymous source inside the ministry claimed that the treasury had miscalculated foreign debts.", "translation": "مصدر مجهول الهوية / مصدر طلب عدم ذكر اسمه", "exampleArabic": "زعم مصدر مجهول الهوية داخل الوزارة أن الخزانة قد أخطأت في حساب الديون الخارجية.", "collocations": ["rely on an anonymous source", "protect anonymous sources"], "synonyms": ["unnamed insider"], "antonyms": ["named official"], "tags": ["journalism", "confidential"]},
    {"headword": "eyewitness account", "pronunciation": "/ˈaɪwɪtnəs əˈkaʊnt/", "partOfSpeech": "noun", "definition": "A first-hand description of an event delivered by an individual who observed it personally.", "example": "The correspondent broadcast vivid eyewitness accounts of the volcanic eruption.", "translation": "شهادة شاهد عيان / رواية من رأى الحدث بنفسه", "exampleArabic": "بث المراسل روايات وشهادات حية لشهود عيان شاهدوا الثوران البركاني بأنفسهم.", "collocations": ["compelling eyewitness account", "corroborate eyewitness accounts"], "synonyms": ["first-person testimony"], "antonyms": ["hearsay"], "tags": ["reporting", "evidence"]},
    {"headword": "retract statement", "pronunciation": "/rɪˈtrækt ˈsteɪtmənt/", "partOfSpeech": "verb", "definition": "To officially withdraw, recant, or take back a false or erroneous public statement.", "example": "The media network was forced to retract its statement after forensic video proved the politician was elsewhere.", "translation": "يسحب بيانه رسمياً / يتراجع عن تصريحه السابق", "exampleArabic": "اضطرت الشبكة الإعلامية لسحب بيانها بعد أن أثبت مقطع فيديو جنائي أن السياسي كان في مكان آخر.", "verbForms": {"v1": "retract statement", "v2": "retracted statement", "v3": "retracted statement"}, "collocations": ["publicly retract statement", "refuse to retract statement"], "synonyms": ["withdraw claim", "recant"], "antonyms": ["stand by statement"], "tags": ["corrections", "actions"]},
    {"headword": "sensationalist headline", "pronunciation": "/senˈseɪʃənəlɪst ˈhedlaɪn/", "partOfSpeech": "noun", "definition": "A dramatic title deliberately designed to shock, excite, or outrage readers.", "example": "Critics condemned the sensationalist headline for inciting unneeded public panic during the health alert.", "translation": "عنوان مثير يهدف للإثارة الرخيصة", "exampleArabic": "أدان النقاد العنوان المثير لتسببه في إثارة ذعر شعبي لا مبرر له أثناء حالة التأهب الصحي.", "collocations": ["run a sensationalist headline", "deplore sensationalist headlines"], "synonyms": ["lurid headline"], "antonyms": ["sober headline"], "tags": ["sensationalism", "press"]},
    {"headword": "clickbait", "pronunciation": "/ˈklɪkbeɪt/", "partOfSpeech": "noun", "definition": "Content on the web designed specifically to entice users to click a link, often deceptively.", "example": "Serious readers avoid online aggregators filled with misleading celebrity clickbait.", "translation": "طعم نقرات مضلل (كليك بيت)", "exampleArabic": "يتجنب القراء الجادون المواقع المجمعة على الإنترنت المليئة بطعم نقرات مضلل عن المشاهير.", "collocations": ["shameless clickbait", "accuse of using clickbait"], "synonyms": ["link bait"], "antonyms": ["substantive content"], "tags": ["internet", "sensationalism"]},
    {"headword": "soundbite", "pronunciation": "/ˈsaʊndbaɪt/", "partOfSpeech": "noun", "definition": "A brief, catchy recorded excerpt from a speech chosen for its succinct suitability in news broadcasts.", "example": "The candidate rehearsed a ten-second soundbite designed to dominate the nightly news clips.", "translation": "مقطع صوتي أو مرئي قصير ومثير / جملة رنانة للإعلام", "exampleArabic": "تدرب المرشح على مقطع قصير لمدة عشر ثوانٍ صُمم ليتصدر نشرات الأخبار الليلية.", "collocations": ["memorable soundbite", "reduce complex policy to soundbites"], "synonyms": ["catchphrase clip"], "antonyms": ["in-depth speech"], "tags": ["broadcasting", "politics"]},
    {"headword": "news ticker", "pronunciation": "/ˈnjuːz ˌtɪkə/", "partOfSpeech": "noun", "definition": "A running electronic display of concise headlines scrolling across the bottom of a television screen.", "example": "Breaking disaster reports flashed across the continuous news ticker at the bottom of the monitor.", "translation": "شريط الأخبار المتحرك أسفل الشاشة", "exampleArabic": "توالت تقارير الكوارث العاجلة على شريط الأخبار المتحرك المستمر أسفل الشاشة.", "collocations": ["scroll across the news ticker", "watch the news ticker"], "synonyms": ["crawl banner"], "antonyms": [], "tags": ["television", "graphics"]},
    {"headword": "photojournalism", "pronunciation": "/ˌfəʊtəʊˈdʒɜːnəlɪzəm/", "partOfSpeech": "noun", "definition": "Journalism that employs dramatic photographs as the primary medium to tell a news story.", "example": "His courageous photojournalism during the humanitarian crisis revealed the plight of stranded refugees.", "translation": "الصحافة المصورة (الفوتوغرافية)", "exampleArabic": "كشفت صحافته المصورة الشجاعة أثناء الأزمة الإنسانية محنة اللاجئين العالقين.", "collocations": ["pioneering photojournalism", "award for photojournalism"], "synonyms": ["visual news reporting"], "antonyms": [], "tags": ["visuals", "journalism"]},
    {"headword": "news dispatch", "pronunciation": "/ˈnjuːz dɪˈspætʃ/", "partOfSpeech": "noun", "definition": "An official written report on current affairs sent in from a distant war zone or foreign station.", "example": "The foreign editor published the war correspondent's harrowing news dispatch without alterations.", "translation": "برقية إخبارية مرسلة من الميدان / رسالة مراسل", "exampleArabic": "نشر محرر الشؤون الخارجية البرقية الإخبارية المؤثرة لمراسل الحرب دون أي تعديلات.", "collocations": ["filed a news dispatch", "urgent news dispatch"], "synonyms": ["field dispatch"], "antonyms": [], "tags": ["correspondence", "war"]},
    {"headword": "investigative expose", "pronunciation": "/ɪnˌvestɪɡətɪv ekˈspəʊzeɪ/", "partOfSpeech": "noun", "definition": "A journalistic report that reveals shocking, hidden, or corrupt facts about someone or an enterprise.", "example": "The investigative expose detailed how corporate directors had dumped toxic byproducts into the river.", "translation": "تحقيق استقصائي فاضح للفساد", "exampleArabic": "فصل التحقيق الاستقصائي الفاضح كيف ألقى مسؤولو الشركة مخلفات سامة في النهر.", "collocations": ["publish an investigative expose", "explosive expose"], "synonyms": ["revelation report"], "antonyms": ["whitewash"], "tags": ["investigation", "scandal"]},
    {"headword": "front page story", "pronunciation": "/ˌfrʌnt peɪdʒ ˈstɔːri/", "partOfSpeech": "noun", "definition": "The most prominent, important news article placed on the first page of a major periodical.", "example": "The diplomatic treaty breakthrough earned the honor of becoming tomorrow's front page story.", "translation": "قصة الصفحة الأولى الرئيسية", "exampleArabic": "نال الاختراق الدبلوماسي في المعاهدة شرف أن يكون قصة الصفحة الأولى الرئيسية لصحيفة الغد.", "collocations": ["make the front page story", "lead with a front page story"], "synonyms": ["headline story", "lead story"], "antonyms": ["back-page filler"], "tags": ["press", "prominence"]},
    {"headword": "breaking news alert", "pronunciation": "/ˌbreɪkɪŋ njuːz əˈlɜːt/", "partOfSpeech": "noun", "definition": "An urgent notification sent to smartphones or broadcast immediately regarding developing events.", "example": "Subscribers received a breaking news alert announcing the unexpected signing of the armistice.", "translation": "تنبيه خبر عاجل", "exampleArabic": "تلقى المشتركون تنبيه خبر عاجل يعلن التوقيع غير المتوقع لاتفاق الهدنة.", "collocations": ["push a breaking news alert", "flash a breaking news alert"], "synonyms": ["urgent bulletin"], "antonyms": [], "tags": ["mobile", "news"]},
    {"headword": "media literacy", "pronunciation": "/ˈmiːdiə ˈlɪtərəsi/", "partOfSpeech": "noun", "definition": "The essential critical ability to access, analyze, evaluate, and create media in various forms.", "example": "High school courses in media literacy teach teenagers how to identify deepfakes and algorithmic bias.", "translation": "الدراية والتربية الإعلامية النقدية", "exampleArabic": "تعلم دورات التربية الإعلامية في المدارس الثانوية المراهقين كيفية تمييز التزييف العميق والتحيز الخوارزمي.", "collocations": ["promote media literacy", "critical media literacy"], "synonyms": ["information literacy"], "antonyms": [], "tags": ["education", "critical"]},
    {"headword": "press censorship", "pronunciation": "/ˈpres ˈsensəʃɪp/", "partOfSpeech": "noun", "definition": "The state suppression or prohibition of news coverage that is deemed politically sensitive or offensive.", "example": "Authoritarian regimes enacted severe press censorship to silence reporting on domestic demonstrations.", "translation": "الرقابة على الصحافة والإعلام", "exampleArabic": "طبقت الأنظمة الاستبدادية رقابة صارمة على الصحافة لإسكات التقارير حول التظاهرات الداخلية.", "collocations": ["suffer from press censorship", "impose press censorship"], "synonyms": ["state suppression"], "antonyms": ["press freedom"], "tags": ["politics", "freedom"]},
    {"headword": "libel lawsuit", "pronunciation": "/ˈlaɪbl ˈlɔːsuːt/", "partOfSpeech": "noun", "definition": "A legal lawsuit filed against a publisher for printing false, defamatory statements that harm reputation.", "example": "The pharmaceutical executive filed a multimillion-dollar libel lawsuit against the local gossip tabloid.", "translation": "دعوى قضائية بتهمة القذف والتشهير المكتوب", "exampleArabic": "رفع مسؤول الأدوية دعوى قضائية بملايين الدولارات بتهمة القذف والتشهير ضد صحيفة الفضائح المحلية.", "collocations": ["threaten a libel lawsuit", "win a libel lawsuit"], "synonyms": ["defamation action"], "antonyms": [], "tags": ["legal", "media"]},

    # Modern Broadcasting & Free Speech (20)
    {"headword": "defamation claim", "pronunciation": "/ˌdefəˈmeɪʃn kleɪm/", "partOfSpeech": "noun", "definition": "A legal action alleging that an oral or written statement has damaged an entity's standing.", "example": "The television network settled the defamation claim out of court before the trial commenced.", "translation": "دعوى تشهير وتشويه سمعة", "exampleArabic": "سوت الشبكة التلفزيونية دعوى التشهير وتشويه السمعة ودياً خارج المحكمة قبل بدء المحاكمة.", "collocations": ["file a defamation claim", "face a defamation claim"], "synonyms": ["slander or libel action"], "antonyms": [], "tags": ["legal", "reputation"]},
    {"headword": "spin doctor", "pronunciation": "/ˈspɪn ˌdɒktə/", "partOfSpeech": "noun", "definition": "A spokesperson or public relations advisor employed to give favorable interpretation to events.", "example": "Political spin doctors worked through the night to reframe the debate disaster as a courageous stance.", "translation": "خبير تلميع الصورة وتوجيه الرأي العام (سبين دكتور)", "exampleArabic": "عمل خبراء تلميع الصورة طوال الليل لإعادة صياغة كارثة المناظرة كموقف شجاع.", "collocations": ["clever spin doctor", "rely on spin doctors"], "synonyms": ["PR propagandist"], "antonyms": ["truth teller"], "tags": ["politics", "pr"]},
    {"headword": "press freedom", "pronunciation": "/ˈpres ˈfriːdəm/", "partOfSpeech": "noun", "definition": "The constitutional right of journalists and newspapers to communicate and report freely.", "example": "International monitors declared that defending press freedom was fundamental to democratic health.", "translation": "حرية الصحافة والتعبير الإعلامي", "exampleArabic": "أعلن المراقبون الدوليون أن الدفاع عن حرية الصحافة أمر جوهري وأساسي لصحة الديمقراطية.", "collocations": ["champion press freedom", "erosion of press freedom"], "synonyms": ["freedom of the press"], "antonyms": ["censorship"], "tags": ["rights", "democracy"]},
    {"headword": "televised address", "pronunciation": "/ˈtelɪvaɪzd əˈdres/", "partOfSpeech": "noun", "definition": "A formal speech delivered live by a prime minister or president on public television.", "example": "In a solemn televised address, the head of state announced emergency pandemic restrictions.", "translation": "خطاب متلفز رسمي", "exampleArabic": "في خطاب متلفز مهيب، أعلن رئيس الدولة فرض قيود الطوارئ لمواجهة الوباء.", "collocations": ["deliver a televised address", "live televised address"], "synonyms": ["broadcast speech"], "antonyms": [], "tags": ["politics", "broadcasting"]},
    {"headword": "media scrutiny", "pronunciation": "/ˈmiːdiə ˈskruːtəni/", "partOfSpeech": "noun", "definition": "Intense, critical, and continuous examination of public figures or enterprises by reporters.", "example": "Corporate leaders must act transparently when their conduct comes under intense media scrutiny.", "translation": "رقابة وفحص إعلامي دقيق ومجهري", "exampleArabic": "يجب على قادة الشركات التصرف بشفافية عندما تخضع تصرفاتهم لرقابة وفحص إعلامي مجهري.", "collocations": ["come under media scrutiny", "endure media scrutiny"], "synonyms": ["press probe"], "antonyms": ["media neglect"], "tags": ["journalism", "accountability"]},
    {"headword": "news anchor", "pronunciation": "/ˈnjuːz ˌæŋkə/", "partOfSpeech": "noun", "definition": "The central television journalist who hosts and presents a news program from a studio.", "example": "The veteran news anchor looked into the lens and announced that historical treaties were signed.", "translation": "مذيع ومقدم الأخبار الرئيسي (نيوز أنكور)", "exampleArabic": "نظر مذيع الأخبار المخضرم إلى العدسة وأعلن أنه قد تم توقيع المعاهدات التاريخية.", "collocations": ["veteran news anchor", "prime-time news anchor"], "synonyms": ["newscaster", "broadcaster"], "antonyms": [], "tags": ["profession", "television"]},
    {"headword": "field reporter", "pronunciation": "/ˈfiːld rɪˈpɔːtə/", "partOfSpeech": "noun", "definition": "A journalist stationed outside the studio who broadcasts live on location from where events occur.", "example": "Our field reporter braved gale-force winds to broadcast live from the flooded harbor barrier.", "translation": "مراسل ميداني من موقع الحدث", "exampleArabic": "تحدى مراسلنا الميداني الرياح العاتية ليبث على الهواء مباشرة من حاجز الميناء الذي غمرته المياه.", "collocations": ["live field reporter", "courageous field reporter"], "synonyms": ["on-scene journalist"], "antonyms": ["studio presenter"], "tags": ["profession", "broadcasting"]},
    {"headword": "media mogul", "pronunciation": "/ˈmiːdiə ˈməʊɡl/", "partOfSpeech": "noun", "definition": "A powerful entrepreneur who controls a substantial empire of newspapers, television, and radio.", "example": "The media mogul acquired five regional television networks to expand his broadcasting footprint.", "translation": "قطب إعلامي / بارون الإمبراطوريات الإعلامية", "exampleArabic": "استحوذ القطب الإعلامي على خمس شبكات تلفزيونية إقليمية لتوسيع نفوذه الإذاعي.", "collocations": ["powerful media mogul", "billionaire media mogul"], "synonyms": ["press baron"], "antonyms": [], "tags": ["business", "power"]},
    {"headword": "fact-checking organization", "pronunciation": "/ˈfækt ˌtʃekɪŋ ˌɔːɡənaɪˈzeɪʃn/", "partOfSpeech": "noun", "definition": "An independent agency dedicated to verifying political statements and public claims for factual truth.", "example": "Independent fact-checking organizations verified that the economic statistics were genuine.", "translation": "مؤسسة تدقيق وتحقق من صحة الأخبار", "exampleArabic": "تحققت مؤسسات تدقيق الحقائق المستقلة من أن الإحصاءات الاقتصادية كانت صحيحة وموثوقة.", "collocations": ["consult a fact-checking organization", "independent fact-checking organization"], "synonyms": ["truth monitor"], "antonyms": [], "tags": ["journalism", "ethics"]},
    {"headword": "investigative journalist", "pronunciation": "/ɪnˈvestɪɡətɪv ˈdʒɜːnəlɪst/", "partOfSpeech": "noun", "definition": "A reporter who specializes in uncovering corruption, white-collar crime, and injustice.", "example": "The investigative journalist worked undercover for nine months inside the illicit offshore firm.", "translation": "صحفي استقصائي", "exampleArabic": "عمل الصحفي الاستقصائي متخفياً لتسعة أشهر داخل الشركة غير القانونية بالخارج.", "collocations": ["intrepid investigative journalist", "celebrated investigative journalist"], "synonyms": ["in-depth reporter"], "antonyms": [], "tags": ["profession", "journalism"]},
    {"headword": "war correspondent", "pronunciation": "/ˈwɔː kɒrɪˌspɒndənt/", "partOfSpeech": "noun", "definition": "A specialized journalist who travels into combat zones to report on frontline warfare.", "example": "The veteran war correspondent broadcast live from the frontlines despite artillery barrages.", "translation": "مراسل حربي في جبهات القتال", "exampleArabic": "بث المراسل الحربي المخضرم مباشرة من خطوط المواجهة على الرغم من القصف المدفعي.", "collocations": ["courageous war correspondent", "frontline war correspondent"], "synonyms": ["battlefield reporter"], "antonyms": [], "tags": ["war", "journalism"]},
    {"headword": "editorial cartoon", "pronunciation": "/ˌedɪˈtɔːriəl kɑːˈtuːn/", "partOfSpeech": "noun", "definition": "An illustration containing a political or social message relating to current news events.", "example": "Today's satirical editorial cartoon ridiculed the parliament's inability to balance national debt.", "translation": "كاريكاتير افتتاحي سياسي", "exampleArabic": "سخر الكاريكاتير الافتتاحي الساخر اليوم من عجز البرلمان عن موازنة الدين القومي.", "collocations": ["satirical editorial cartoon", "award-winning editorial cartoon"], "synonyms": ["political cartoon"], "antonyms": [], "tags": ["art", "satire"]},
    {"headword": "op-ed piece", "pronunciation": "/ˌɒp ˈed piːs/", "partOfSpeech": "noun", "definition": "An opinion article published in a newspaper opposite the editorial page by an invited guest contributor.", "example": "A renowned climate scientist penned an insightful op-ed piece on renewable battery grids.", "translation": "مقال رأي لكاتب زائر (أوب إيد)", "exampleArabic": "كتب عالم مناخ شهير مقال رأي قيّماً حول شبكات بطاريات الطاقة المتجددة.", "collocations": ["publish an op-ed piece", "penned an op-ed piece"], "synonyms": ["guest column", "opinion essay"], "antonyms": [], "tags": ["press", "opinion"]},
    {"headword": "news broadcast", "pronunciation": "/ˈnjuːz ˈbrɔːdkɑːst/", "partOfSpeech": "noun", "definition": "A radio or television transmission detailing current local, national, and world events.", "example": "Families gathered around the radio every evening to listen to the seven o'clock news broadcast.", "translation": "نشرة إخبارية إذاعية أو متلفزة", "exampleArabic": "اجتمعت العائلات حول المذياع كل مساء للاستماع إلى نشرة أخبار السابعة.", "collocations": ["evening news broadcast", "listen to the news broadcast"], "synonyms": ["newscast"], "antonyms": [], "tags": ["radio", "television"]},
    {"headword": "wire service", "pronunciation": "/ˈwaɪə ˌsɜːvɪs/", "partOfSpeech": "noun", "definition": "A news agency that supplies syndicated stories by electronic wire to subscribing newsrooms.", "example": "Subscribing newspapers depend on international wire services for immediate foreign bulletins.", "translation": "وكالة أنباء إلكترونية (واير سيرفيس)", "exampleArabic": "تعتمد الصحف المشتركة على وكالات الأنباء الدولية للحصول على النشرات الخارجية الفورية.", "collocations": ["subscribe to a wire service", "international wire service"], "synonyms": ["news agency"], "antonyms": [], "tags": ["news", "agencies"]},
    {"headword": "press gaggle", "pronunciation": "/ˈpres ˌɡæɡl/", "partOfSpeech": "noun", "definition": "An informal, impromptu briefing conducted on the move for a scrum of reporters.", "example": "The presidential spokesperson held an informal press gaggle aboard the executive aircraft.", "translation": "تجمع وتدافع صحفي عاجل / لقاء خاطف مع المراسلين", "exampleArabic": "عقد المتحدث الرئاسي لقاءً صحفياً خاطفاً وغير رسمي على متن الطائرة الرئاسية.", "collocations": ["hold a press gaggle", "join the press gaggle"], "synonyms": ["impromptu press cluster"], "antonyms": ["formal press conference"], "tags": ["politics", "press"]},
    {"headword": "leaked memo", "pronunciation": "/liːkt ˈmeməʊ/", "partOfSpeech": "noun", "definition": "An internal, confidential written document made public without official authorization.", "example": "A leaked memo from the board revealed secret plans to shutter three automobile assembly plants.", "translation": "مذكرة داخلية سرية مسربة", "exampleArabic": "كشفت مذكرة سرية مسربة من مجلس الإدارة عن خطط سرية لإغلاق ثلاثة مصانع لتجميع السيارات.", "collocations": ["publish a leaked memo", "obtain a leaked memo"], "synonyms": ["confidential disclosure"], "antonyms": [], "tags": ["leaks", "journalism"]},
    {"headword": "whistleblower account", "pronunciation": "/ˈwɪslbləʊər əˈkaʊnt/", "partOfSpeech": "noun", "definition": "A testimony or report provided by an insider exposing institutional corruption or malfeasance.", "example": "The whistleblower account revealed that aviation regulators had overlooked aircraft software flaws.", "translation": "رواية وإفادة كاشف الفساد / شهادة المبلغ الداخلي", "exampleArabic": "كشفت رواية كاشف الفساد أن مراقبي الطيران قد تغاضوا عن عيوب برمجيات الطائرات.", "collocations": ["rely on a whistleblower account", "credible whistleblower account"], "synonyms": ["insider disclosure"], "antonyms": [], "tags": ["whistleblowing", "ethics"]},
    {"headword": "media watchdog", "pronunciation": "/ˈmiːdiə ˈwɒtʃdɒɡ/", "partOfSpeech": "noun", "definition": "An independent organization that monitors journalists and news outlets for bias, ethics, and accuracy.", "example": "The media watchdog rebuked the cable network for broadcasting misleading election graphs.", "translation": "مرصد النزاهة الإعلامية / هيئة الرقابة على الإعلام", "exampleArabic": "وبخ مرصد النزاهة الإعلامية شبكة الكابل لبثها رسوماً بيانية انتخابية مضللة.", "collocations": ["independent media watchdog", "report by a media watchdog"], "synonyms": ["press ombudsman"], "antonyms": [], "tags": ["ethics", "oversight"]},
    {"headword": "prime-time bulletin", "pronunciation": "/ˌpraɪm ˈtaɪm ˈbʊlətɪn/", "partOfSpeech": "noun", "definition": "A major television news broadcast transmitted during peak evening viewership hours.", "example": "The network dedicated their entire prime-time bulletin to the peace treaty signing ceremony.", "translation": "نشرة أخبار وقت الذروة المسائية", "exampleArabic": "خصصت الشبكة نشرة أخبار وقت الذروة المسائية بالكامل لمراسم توقيع معاهدة السلام.", "collocations": ["lead the prime-time bulletin", "watch the prime-time bulletin"], "synonyms": ["flagship news hour"], "antonyms": [], "tags": ["television", "broadcasting"]}
]

grammar_66 = [
    {
        "title": "Reported Speech Review (Reporting News)",
        "titleArabic": "مراجعة الكلام المنقول وصياغة الأخبار (Reported Speech: Tense Backshift & Reporting Verbs)",
        "explanation": "In journalistic writing and news reporting, we frequently report what people, officials, and agencies said or claimed: 1) Tense backshift: Direct Present Simple becomes Past Simple ('I am ready' -> He said he was ready); Present Continuous becomes Past Continuous ('We are negotiating' -> They reported they were negotiating); Present Perfect becomes Past Perfect ('We have signed the accord' -> The envoy announced they had signed the accord); 'Will' becomes 'Would'; 'Can' becomes 'Could'. 2) Reporting verbs with nuances: Instead of simply using 'said', professional journalism utilizes varied reporting verbs: 'stated that...', 'claimed that...' (implies doubt), 'confirmed that...', 'denied that...', 'disclosed that...', 'admitted that...', 'insisted that...'. 3) Time and place shift: 'today' becomes 'that day'; 'yesterday' becomes 'the previous day / the day before'; 'tomorrow' becomes 'the following day / the next day'.",
        "explanationArabic": "في الكتابة الصحفية وصياغة التقارير الإخبارية، ننقل باستمرار ما قاله أو زفّه المسؤولون والوكالات: 1) تحويل الأزمنة للماضي (Backshift): يتحول المضارع البسيط إلى ماضٍ بسيط ('I am ready' -> He said he was ready)، ويتحول المضارع المستمر لماضٍ مستمر، ويتحول المضارع التام لماضٍ تام (have signed -> had signed)، وتتحول will إلى would و can إلى could. 2) تنويع أفعال النقل الصحفية: بدلاً من تكرار said فقط، تستخدم الصحافة أفعالاً ذات دلالات دقيقة: stated that (صرّح بأن)، claimed that (ادعى - تفيد التشكيك)، confirmed that (أكّد أن)، denied that (نفى أن)، disclosed that (كشف أن). 3) تغيير ظروف الزمان والمكان: تتحول today إلى that day، وتتحول yesterday إلى the day before، وتتحول tomorrow إلى the following day.",
        "structures": [
            {"label": "Standard News Reporting · الصياغة الإخبارية المنقولة", "pattern": "Spokesperson / Reporter + reported / stated / confirmed + that + Backshifted Clause", "explanation": "The standard formula for relaying official announcements in journalism.", "explanationArabic": "الأسلوب القياسي لنقل التصريحات والبيانات الرسمية في الصحافة."},
            {"label": "Reporting with Skepticism (Claimed / Alleged) · النقل المشكك", "pattern": "Subject + claimed / alleged + that + Backshifted Clause", "explanation": "Used when the reporter does not endorse the truth of the speaker's statement.", "explanationArabic": "يُستخدم عندما ينأى الصحفي بنفسه عن تأكيد صحة ادعاء المتحدث."},
            {"label": "Questions in Reported Speech · نقل التساؤلات الصحفية", "pattern": "Reporters asked + whether / if + Subject + Past Tense (Statement Order)", "explanation": "Used when reporting questions asked during press conferences.", "explanationArabic": "يُستخدم لنقل الأسئلة المطروحة في المؤتمرات الصحفية مع الحفاظ على ترتيب الجملة الخبرية."}
        ],
        "examples": [
            {"sentence": "The news anchor reported that the prime minister had delivered a televised address.", "translation": "أفاد مذيع الأخبار بأن رئيس الوزراء كان قد ألقى خطاباً متلفزاً.", "usesVocabulary": ["news anchor", "televised address"]},
            {"sentence": "A leaked memo disclosed that the corporate board had ignored several whistleblower accounts.", "translation": "كشفت مذكرة مسربة أن مجلس إدارة الشركة كان قد تجاهل عدة إفادات لكواشف الفساد.", "usesVocabulary": ["leaked memo", "whistleblower account"]},
            {"sentence": "The field reporter confirmed that peace envoys were meeting in an impromptu press gaggle.", "translation": "أكد المراسل الميداني أن مبعوثي السلام كانوا يجتمعون في لقاء صحفي خاطف عاجل.", "usesVocabulary": ["field reporter", "press gaggle"]},
            {"sentence": "An independent fact-checking organization verified that the front page story was accurate.", "translation": "تحققت مؤسسة تدقيق حقائق مستقلة من أن قصة الصفحة الأولى كانت دقيقة.", "usesVocabulary": ["fact-checking organization", "front page story"]}
        ],
        "commonMistakes": [
            {"wrong": "The journalist said me that the press briefing was canceled.", "right": "The journalist told me that the press briefing was canceled. (OR: said that...)", "note": "'Tell' requires an indirect personal object (told me); 'say' cannot take an object without 'to' (said to me).", "noteArabic": "يحتاج الفعل tell إلى مفعول به مباشر (told me)؛ بينما لا يأخذ say مفعولاً به إلا بحرف الجر to (said to me)."},
            {"wrong": "The correspondent asked what was the minister planning to do.", "right": "The correspondent asked what the minister was planning to do.", "note": "In reported questions, do not invert verb and subject; use statement order (Subject + Verb).", "noteArabic": "في الأسئلة المنقولة، لا تعكس الفاعل والفعل؛ بل استخدم الترتيب الخبري العادي (الفاعل ثم الفعل)."}
        ],
        "commonUsage": [
            "Newsroom wire dispatches: 'Officials announced that emergency reserves had been mobilized.' (تُستخدم في البرقيات الإخبارية للوكالات.)",
            "Press conference summaries: 'The defense secretary stated that peace negotiations would resume.' (تُستخدم لتلخيص المؤتمرات والبيانات الصحفية.)",
            "Legal reporting: 'The defendant denied that he had leaked confidential dossiers.' (تُستخدم لنقل أقوال المحاكمات والقضايا الجنائية.)"
        ]
    }
]

convs_66 = [
    {
        "title": "Breaking News in the Newsroom",
        "titleArabic": "تغطية خبر عاجل داخل صالة التحرير",
        "setting": "The executive news editor directs a breaking news alert with an investigative journalist and senior producer.",
        "lines": [
            {"speaker": "Editor", "text": "Listen up everyone! We just received a major scoop from an anonymous source inside the ministry."},
            {"speaker": "Journalist", "text": "Has our fact-checking organization verified that the leaked memo is authentic?"},
            {"speaker": "Editor", "text": "Yes; two independent legal auditors confirmed that the document was completely genuine."},
            {"speaker": "Producer", "text": "Shall I push a breaking news alert to our mobile app subscribers immediately?"},
            {"speaker": "Editor", "text": "Do it now, and scroll the headline across our live television news ticker!"},
            {"speaker": "Journalist", "text": "I will phone their press secretary and ask whether the minister will speak on the record."},
            {"speaker": "Editor", "text": "Ensure our report avoids sensationalist headlines; we are a respected broadsheet, not a gossip tabloid."},
            {"speaker": "Producer", "text": "Understood. Our prime-time bulletin will lead with this exclusive report!"}
        ],
        "vocabularyUsed": ["newsroom", "scoop", "anonymous source", "fact-checking organization", "leaked memo", "breaking news alert", "news ticker", "on the record", "sensationalist headline", "broadsheet", "tabloid", "prime-time bulletin", "exclusive report"]
    },
    {
        "title": "A Press Briefing Under Heavy Scrutiny",
        "titleArabic": "إيجاز صحفي خاضع لرقابة وتدقيق إعلامي مكثف",
        "setting": "A government spokesperson takes tough questions from reporters during a live broadcast briefing.",
        "lines": [
            {"speaker": "Reporter", "text": "Madam Secretary, did the ministry retract its statement regarding regional water pollution levels?"},
            {"speaker": "Spokesperson", "text": "The administration stated that updated environmental data was being prepared for publication."},
            {"speaker": "Reporter", "text": "Is it true that an internal whistleblower account alerted your inspectors two months ago?"},
            {"speaker": "Spokesperson", "text": "I cannot comment on personnel investigations, but our agency welcomes independent media scrutiny."},
            {"speaker": "Reporter", "text": "A viral op-ed piece claimed that political spin doctors had suppressed the initial findings."},
            {"speaker": "Spokesperson", "text": "That assertion is groundless; our minister stated on the record that safety was his highest priority."},
            {"speaker": "Reporter", "text": "Will the prime minister deliver a televised address tonight to reassure affected families?"},
            {"speaker": "Spokesperson", "text": "A formal televised address will be broadcast at eight o'clock across all national channels."}
        ],
        "vocabularyUsed": ["retract statement", "press briefing", "whistleblower account", "media scrutiny", "op-ed piece", "spin doctor", "on the record", "televised address"]
    },
    {
        "title": "Frontline Dispatch from a War Zone",
        "titleArabic": "برقية ميدانية لمراسل حربي من جبهات القتال",
        "setting": "A senior news anchor interviews a courageous war correspondent reporting live from an international border post.",
        "lines": [
            {"speaker": "Anchor", "text": "We go live now to our field reporter stationed along the humanitarian corridor. What is the latest?"},
            {"speaker": "Correspondent", "text": "Thank you. I have collected harrowing eyewitness accounts from families escaping the artillery zone."},
            {"speaker": "Anchor", "text": "Did military spokespersons confirm that humanitarian aid convoys had reached the regional hospital?"},
            {"speaker": "Correspondent", "text": "They stated off the record that severe shelling had forced supply trucks to pause overnight."},
            {"speaker": "Anchor", "text": "Our viewers are following your courageous news dispatch with deep solidarity and concern."},
            {"speaker": "Correspondent", "text": "Powerful photojournalism captured here today will illustrate tomorrow's front page story."},
            {"speaker": "Anchor", "text": "Thank you. Stay safe out there as you continue your vital work for international press freedom."},
            {"speaker": "Correspondent", "text": "Our wire service will transmit updated casualty figures as soon as communication lines stabilize."}
        ],
        "vocabularyUsed": ["news anchor", "field reporter", "eyewitness account", "off the record", "news dispatch", "photojournalism", "front page story", "press freedom", "wire service"]
    }
]

paras_66 = [
    {
        "title": "The Ethical Pillars of Investigative Journalism",
        "titleArabic": "الأركان الأخلاقية للصحافة الاستقصائية الرصينة",
        "text": "In an era saturated with sensationalist headlines and deceptive online clickbait, rigorous investigative journalism remains the bedrock of democratic accountability. When a dedicated investigative journalist conducts an in-depth probe, every single fact must be verified through a certified fact-checking organization before broadcast. While a fast-paced newsroom often scrambles to secure an exclusive scoop, responsible editors refuse to print an uncorroborated leaked memo or rely uncritically on an unvetted anonymous source. By prioritizing verified truth over fleeting digital traffic, quality media outlets protect their institutional reputation and defend constitutional press freedom.",
        "vocabularyUsed": ["sensationalist headline", "clickbait", "investigative journalism", "investigative journalist", "fact-checking organization", "newsroom", "scoop", "leaked memo", "anonymous source", "media outlet", "press freedom"]
    },
    {
        "title": "Broadcasting Integrity in Modern Television News",
        "titleArabic": "نزاهة البث في الإعلام المرئي الإخباري المعاصر",
        "text": "The architecture of television news broadcasting requires seamless collaboration between studio producers and brave journalists stationed across the globe. During major international crises, networks interrupt regular schedules to deliver uninterrupted live coverage and provide a continuous news ticker with breaking news alerts. While a veteran news anchor coordinates the prime-time bulletin, a dedicated field reporter or war correspondent delivers vivid eyewitness accounts directly from conflict zones. Despite relentless attempts by government spin doctors to manipulate soundbites, genuine photojournalism and authentic news dispatches bring unvarnished truth directly into the living rooms of citizens.",
        "vocabularyUsed": ["live coverage", "news ticker", "breaking news alert", "news anchor", "prime-time bulletin", "field reporter", "war correspondent", "eyewitness account", "spin doctor", "soundbite", "photojournalism", "news dispatch"]
    },
    {
        "title": "Media Literacy and Defending Truth in Public Discourse",
        "titleArabic": "التربية الإعلامية والدفاع عن الحقيقة في الفضاء العام",
        "text": "As algorithmic news delivery transforms civic life, fostering critical media literacy has become indispensable for informed citizenship. Readers must learn to distinguish between a rigorous broadsheet investigation and a manipulative tabloid rumor that risks an expensive libel lawsuit or defamation claim. When an independent media watchdog exposes journalistic malpractice, reputable agencies demonstrate integrity by choosing to publicly retract erroneous statements. When societies reject state press censorship and subject powerful institutions to fearless media scrutiny, the public sphere remains vibrant, transparent, and resilient.",
        "vocabularyUsed": ["media literacy", "broadsheet", "tabloid", "libel lawsuit", "defamation claim", "media watchdog", "retract statement", "press censorship", "media scrutiny"]
    }
]

# Write Day 66
write_day(66, vocab_66, grammar_66, convs_66, paras_66)

print("Day 65 and Day 66 written successfully.")
