# -*- coding: utf-8 -*-
"""Data definition for Day 30: Trips and Stories."""

vocab_day30 = [
    {
        "headword": "chronicle",
        "pronunciation": "/ˈkrɑːnɪkl/",
        "partOfSpeech": "noun",
        "definition": "A factual written account of important or historical events in the order of their occurrence.",
        "example": "His published travel chronicle detailed three years of backpacking through Asia.",
        "translation": "تاريخ وقائع / سجل أحداث زمني",
        "exampleArabic": "فصل سجل وقائع رحلاته المنشور ثلاث سنوات من السفر بحقيبة الظهر عبر آسيا.",
        "relatedForms": ["chronicles", "chronicled"],
        "collocations": ["written chronicle", "historical chronicle"],
        "synonyms": ["record", "annals", "history"],
        "antonyms": [],
        "tags": ["writing", "travel"]
    },
    {
        "headword": "anecdote",
        "pronunciation": "/ˈænɪkdoʊt/",
        "partOfSpeech": "noun",
        "definition": "A short, amusing or interesting story about a real incident or person.",
        "example": "He shared an amusing anecdote about bargaining in a Moroccan bazaar.",
        "translation": "طرفة / حكاية قصيرة ممتعة",
        "exampleArabic": "شارك قصة طريفة حول المساومة في سوق مغربي.",
        "relatedForms": ["anecdotes", "anecdotal"],
        "collocations": ["amusing anecdote", "tell an anecdote", "humorous anecdote"],
        "synonyms": ["tale", "yarn", "sketch"],
        "antonyms": [],
        "tags": ["storytelling", "communication"]
    },
    {
        "headword": "narrative",
        "pronunciation": "/ˈnærətɪv/",
        "partOfSpeech": "noun",
        "definition": "A spoken or written account of connected events; a story.",
        "example": "The author crafted a compelling travel narrative about overcoming hardship.",
        "translation": "سرد / رواية أحداث",
        "exampleArabic": "صاغ الكاتب سرداً مؤثراً للرحلة حول التغلب على الصعاب.",
        "relatedForms": ["narratives"],
        "collocations": ["travel narrative", "personal narrative", "gripping narrative"],
        "synonyms": ["story", "account", "chronicle"],
        "antonyms": [],
        "tags": ["writing", "communication"]
    },
    {
        "headword": "storyteller",
        "pronunciation": "/ˈstɔːritelər/",
        "partOfSpeech": "noun",
        "definition": "A person who tells or writes stories.",
        "example": "The elderly village storyteller captivated everyone around the evening campfire.",
        "translation": "حكواتي / راوي قصص",
        "exampleArabic": "أسر راوي القرية المسن الجميع حول نار المخيم المسائية.",
        "relatedForms": ["storytellers", "storytelling"],
        "collocations": ["gifted storyteller", "natural storyteller", "master storyteller"],
        "synonyms": ["narrator", "raconteur"],
        "antonyms": [],
        "tags": ["professions", "people"]
    },
    {
        "headword": "tale",
        "pronunciation": "/teɪl/",
        "partOfSpeech": "noun",
        "definition": "A fictitious or true story, especially one that is imaginatively recounted.",
        "example": "Grandfather loved to tell an exciting tale about his seafaring days.",
        "translation": "حكاية / قصة",
        "exampleArabic": "أحب جدي أن يروي حكاية مثيرة عن أيام إبحاره في البحر.",
        "relatedForms": ["tales"],
        "collocations": ["tall tale", "cautionary tale", "adventure tale"],
        "synonyms": ["story", "legend", "fable"],
        "antonyms": [],
        "tags": ["storytelling"]
    },
    {
        "headword": "memoir",
        "pronunciation": "/ˈmemwɑːr/",
        "partOfSpeech": "noun",
        "definition": "A historical account or biography written from personal knowledge and experience.",
        "example": "She wrote an inspiring memoir documenting her solo bicycle tour around the world.",
        "translation": "مذكرات شخصية / سيرة ذاتية",
        "exampleArabic": "كتبت مذكرات ملهمة توثق جولتها الفردية بالدراجة حول العالم.",
        "relatedForms": ["memoirs"],
        "collocations": ["publish a memoir", "bestselling memoir", "travel memoir"],
        "synonyms": ["autobiography", "reminiscence", "life story"],
        "antonyms": [],
        "tags": ["writing", "literature"]
    },
    {
        "headword": "journal",
        "pronunciation": "/ˈdʒɜːrnl/",
        "partOfSpeech": "noun",
        "definition": "A newspaper, magazine, or personal record of experiences kept on a regular basis.",
        "example": "Every night before sleeping, he wrote detailed reflections in his travel journal.",
        "translation": "يوميات / دفتر تدوين",
        "exampleArabic": "كل ليلة قبل النوم، كان يكتب تأملات مفصلة في دفتر يوميات سفره.",
        "relatedForms": ["journals", "journaling"],
        "collocations": ["keep a journal", "travel journal", "daily journal"],
        "synonyms": ["diary", "log", "record"],
        "antonyms": [],
        "tags": ["writing"]
    },
    {
        "headword": "diary",
        "pronunciation": "/ˈdaɪəri/",
        "partOfSpeech": "noun",
        "definition": "A book in which one keeps a daily record of events and personal experiences.",
        "example": "She locked her private diary in her travel backpack every morning.",
        "translation": "مذكرات يومية خاصة",
        "exampleArabic": "أغلقت مذكراتها اليومية الخاصة في حقيبة ظهر سفرها كل صباح.",
        "relatedForms": ["diaries"],
        "collocations": ["keep a diary", "secret diary", "personal diary"],
        "synonyms": ["journal", "daybook"],
        "antonyms": [],
        "tags": ["writing"]
    },
    {
        "headword": "logbook",
        "pronunciation": "/ˈlɔːɡbʊk/",
        "partOfSpeech": "noun",
        "definition": "An official record of events during the voyage of a ship or aircraft.",
        "example": "The ship captain methodically recorded wind speeds and coordinates in the logbook.",
        "translation": "سجل الرحلة الرسمي (للسفن أو الطائرات)",
        "exampleArabic": "سجل قبطان السفينة بشكل منهجي سرعات الرياح والإحداثيات في سجل الرحلة.",
        "relatedForms": ["logbooks"],
        "collocations": ["captain's logbook", "flight logbook", "official logbook"],
        "synonyms": ["ship log", "record book"],
        "antonyms": [],
        "tags": ["travel", "records"]
    },
    {
        "headword": "travelogue",
        "pronunciation": "/ˈtrævəlɔːɡ/",
        "partOfSpeech": "noun",
        "definition": "A movie, book, or illustrated lecture about places visited by a traveler.",
        "example": "We watched an engaging video travelogue about remote Scottish islands.",
        "translation": "أدب الرحلات / فيلم أو كتاب عن رحلة",
        "exampleArabic": "شاهدنا فيلماً وثائقياً جذاباً لأدب الرحلات عن الجزر الاسكتلندية النائية.",
        "relatedForms": ["travelogues"],
        "collocations": ["filmed travelogue", "fascinating travelogue", "published travelogue"],
        "synonyms": ["travel guide", "travel documentary"],
        "antonyms": [],
        "tags": ["travel", "media"]
    },
    {
        "headword": "recount",
        "pronunciation": "/rɪˈkaʊnt/",
        "partOfSpeech": "verb",
        "definition": "To tell someone about something; give an account of an event or experience.",
        "example": "He sat down to recount the dramatic events of the alpine storm.",
        "translation": "يسرد / يروي بتفصيل",
        "exampleArabic": "جلس ليروي الأحداث الدرامية للعاصفة الألبية.",
        "relatedForms": ["recounted", "recounting"],
        "collocations": ["recount an incident", "recount a memory", "recount in vivid detail"],
        "synonyms": ["narrate", "tell", "relate"],
        "antonyms": [],
        "tags": ["communication", "action"]
    },
    {
        "headword": "narrate",
        "pronunciation": "/ˈnæreɪt/",
        "partOfSpeech": "verb",
        "definition": "To deliver a spoken or written commentary on an event or story.",
        "example": "The documentary narrator will narrate the historical journey of the caravan.",
        "translation": "يروي / يقدم السرد",
        "exampleArabic": "سيقوم معلق الفيلم الوثائقي برواية الرحلة التاريخية للقافلة.",
        "relatedForms": ["narrated", "narrating", "narrator"],
        "collocations": ["narrate a story", "narrate the events"],
        "synonyms": ["tell", "recount", "chronicle"],
        "antonyms": [],
        "tags": ["action", "communication"]
    },
    {
        "headword": "describe in detail",
        "pronunciation": "/dɪˈskraɪb ɪn ˈdiːteɪl/",
        "partOfSpeech": "verb",
        "definition": "To give a thorough and specific account of something with all particulars.",
        "example": "Can you describe in detail what happened when the bus broke down?",
        "translation": "يصف بالتفصيل الدقيق",
        "exampleArabic": "هل يمكنك أن تصف بالتفصيل ما حدث عندما تعطلت الحافلة؟",
        "relatedForms": ["described in detail"],
        "collocations": ["describe in detail the scene", "please describe in detail"],
        "synonyms": ["elaborate on", "specify"],
        "antonyms": [],
        "tags": ["action", "communication"]
    },
    {
        "headword": "reminisce",
        "pronunciation": "/ˌremɪˈnɪs/",
        "partOfSpeech": "verb",
        "definition": "To indulge in enjoyable recollection of past events.",
        "example": "Old classmates met over dinner to reminisce about their university graduation trip.",
        "translation": "يستعيد الذكريات الجميلة بحنين",
        "exampleArabic": "التقى الزملاء القدامى على العشاء لاستعادة ذكريات رحلة تخرجهم الجامعية الجميلة.",
        "relatedForms": ["reminisced", "reminiscing", "reminiscence"],
        "collocations": ["reminisce about the past", "reminisce fondly"],
        "synonyms": ["remember", "recall", "look back"],
        "antonyms": [],
        "tags": ["emotion", "memory"]
    },
    {
        "headword": "relive",
        "pronunciation": "/ˌriːˈlɪv/",
        "partOfSpeech": "verb",
        "definition": "To experience a past event again in one's imagination or memory.",
        "example": "Browsing old photos allowed them to relive the magic of their safari.",
        "translation": "يعايش مجدداً في خياله",
        "exampleArabic": "أتاح لهم تصفح الصور القديمة معايشة سحر رحلة السفاري مجدداً.",
        "relatedForms": ["relived", "reliving"],
        "collocations": ["relive the moment", "relive the experience", "relive memories"],
        "synonyms": ["re-experience", "recapitulate"],
        "antonyms": [],
        "tags": ["memory", "action"]
    },
    {
        "headword": "vivid",
        "pronunciation": "/ˈvɪvɪd/",
        "partOfSpeech": "adjective",
        "definition": "Producing powerful feelings or strong, clear images in the mind.",
        "example": "She preserved a vivid memory of the turquoise waters surrounding the reef.",
        "translation": "حيوي / ناصع الوضوح في الذاكرة",
        "exampleArabic": "احتفظت بذكرى ناصعة الوضوح للمياه الفيروزية المحيطة بالشعاب.",
        "relatedForms": ["vividly", "vividness"],
        "collocations": ["vivid memory", "vivid description", "vivid colors"],
        "synonyms": ["graphic", "striking", "clear"],
        "antonyms": ["vague", "faint"],
        "tags": ["description", "memory"]
    },
    {
        "headword": "thrilling",
        "pronunciation": "/ˈθrɪlɪŋ/",
        "partOfSpeech": "adjective",
        "definition": "Causing excitement and pleasure; exhilarating.",
        "example": "Riding the cable car across the gorge was a thrilling experience.",
        "translation": "مثير ومبهج للغاية",
        "exampleArabic": "كان ركوب التلفريك عبر الخانق تجربة مثيرة ومبهجة للغاية.",
        "relatedForms": ["thrill", "thrilled"],
        "collocations": ["thrilling ride", "thrilling adventure", "thrilling climax"],
        "synonyms": ["exciting", "electrifying", "gripping"],
        "antonyms": ["dull", "boring"],
        "tags": ["emotion", "travel"]
    },
    {
        "headword": "dramatic",
        "pronunciation": "/drəˈmætɪk/",
        "partOfSpeech": "adjective",
        "definition": "Sudden, striking, and exciting or emotional.",
        "example": "A dramatic thunder storm rolled across the mountain peaks at sunset.",
        "translation": "درامي / حافل بالإثارة والتحولات",
        "exampleArabic": "اجتاحت عاصفة رعدية درامية قمم الجبال عند غروب الشمس.",
        "relatedForms": ["dramatically"],
        "collocations": ["dramatic scenery", "dramatic change", "dramatic rescue"],
        "synonyms": ["spectacular", "startling", "breathtaking"],
        "antonyms": ["monotonous", "peaceful"],
        "tags": ["description"]
    },
    {
        "headword": "humorous",
        "pronunciation": "/ˈhjuːmərəs/",
        "partOfSpeech": "adjective",
        "definition": "Causing lighthearted laughter and amusement; comical.",
        "example": "He told a humorous story about getting hopelessly lost in the subway.",
        "translation": "فكاهي / طريف / مضحك",
        "exampleArabic": "روى قصة فكاهية حول الضياع الميؤوس منه في مترو الأنفاق.",
        "relatedForms": ["humor", "humorously"],
        "collocations": ["humorous anecdote", "humorous tale", "humorous moment"],
        "synonyms": ["funny", "amusing", "witty"],
        "antonyms": ["serious", "grave"],
        "tags": ["description", "entertainment"]
    },
    {
        "headword": "spooky",
        "pronunciation": "/ˈspuːki/",
        "partOfSpeech": "adjective",
        "definition": "Sinister or ghostly in a way that causes a slight feeling of fear or unease.",
        "example": "Walking past the deserted castle ruins at midnight felt decidedly spooky.",
        "translation": "مريب / مخيف بشكل شبحي",
        "exampleArabic": "كان المرور بجوار أطلال القلعة المهجورة عند منتصف الليل أمراً مريباً ومخيفاً بالتأكيد.",
        "relatedForms": ["spookiness"],
        "collocations": ["spooky atmosphere", "spooky story", "spooky hallway"],
        "synonyms": ["eerie", "creepy", "ghostly"],
        "antonyms": ["cheerful", "comforting"],
        "tags": ["description"]
    },
    {
        "headword": "unexpected turn",
        "pronunciation": "/ˌʌnɪkˈspektɪd tɜːrn/",
        "partOfSpeech": "noun",
        "definition": "A sudden and unforeseen change in the direction or development of events.",
        "example": "Our peaceful camping weekend took an unexpected turn when heavy snow started falling.",
        "translation": "منعطف غير متوقع للأحداث",
        "exampleArabic": "اتخذت عطلة نهاية الأسبوع للتخييم منعطفاً غير متوقع عندما بدأت الثلوج الكثيفة في التساقط.",
        "relatedForms": ["unexpected turns"],
        "collocations": ["take an unexpected turn", "events took an unexpected turn"],
        "synonyms": ["surprise development", "twist"],
        "antonyms": [],
        "tags": ["storytelling", "events"]
    },
    {
        "headword": "plot twist",
        "pronunciation": "/plɑːt twɪst/",
        "partOfSpeech": "noun",
        "definition": "An unanticipated change in the expected direction or outcome of the plot of a story.",
        "example": "Discovering that the friendly tour guide was actually a retired pilot was a fun plot twist.",
        "translation": "حبكة مفاجئة / انعطاف مفاجئ في القصة",
        "exampleArabic": "كان اكتشاف أن المرشد السياحي الودود كان في الواقع طياراً متقاعداً حبكة مفاجئة وممتعة.",
        "relatedForms": ["plot twists"],
        "collocations": ["brilliant plot twist", "surprising plot twist", "unforeseen plot twist"],
        "synonyms": ["twist ending", "sudden turn"],
        "antonyms": [],
        "tags": ["storytelling"]
    },
    {
        "headword": "climax",
        "pronunciation": "/ˈklaɪmæks/",
        "partOfSpeech": "noun",
        "definition": "The most intense, exciting, or important point of something.",
        "example": "Reaching the windy peak of the volcano was the emotional climax of our trek.",
        "translation": "ذروة الأحداث / أوج الإثارة",
        "exampleArabic": "كان الوصول إلى قمة البركان العاصفة هو ذروة الإثارة العاطفية لرحلتنا.",
        "relatedForms": ["climactic"],
        "collocations": ["dramatic climax", "reach a climax", "story climax"],
        "synonyms": ["peak", "culmination", "apex"],
        "antonyms": ["anticlimax", "beginning"],
        "tags": ["storytelling", "events"]
    },
    {
        "headword": "mishap",
        "pronunciation": "/ˈmɪshæp/",
        "partOfSpeech": "noun",
        "definition": "An unlucky accident or minor unfortunate occurrence.",
        "example": "Despite a minor luggage mishap at customs, we arrived on schedule.",
        "translation": "حادث عارض مؤسف / ورطة خفيفة",
        "exampleArabic": "على الرغم من ورطة طفيفة تتعلق بالأمتعة في الجمارك، وصلنا في الموعد المحدد.",
        "relatedForms": ["mishaps"],
        "collocations": ["unfortunate mishap", "minor mishap", "avoid mishaps"],
        "synonyms": ["accident", "misfortune", "hiccup"],
        "antonyms": ["good luck"],
        "tags": ["travel", "trouble"]
    },
    {
        "headword": "misadventure",
        "pronunciation": "/ˌmɪsədˈventʃər/",
        "partOfSpeech": "noun",
        "definition": "An unfortunate incident or piece of bad luck.",
        "example": "Our road trip turned into a comical misadventure when the GPS guided us onto a farm.",
        "translation": "مغامرة فاشلة / نكبة طريفة",
        "exampleArabic": "تحولت رحلتنا البرية إلى مغامرة هزلية فاشلة عندما وجهنا نظام تحديد المواقع إلى داخل مزرعة.",
        "relatedForms": ["misadventures"],
        "collocations": ["series of misadventures", "comic misadventure"],
        "synonyms": ["mishap", "debacle"],
        "antonyms": ["success"],
        "tags": ["travel", "storytelling"]
    },
    {
        "headword": "setback",
        "pronunciation": "/ˈsetbæk/",
        "partOfSpeech": "noun",
        "definition": "A reversal or check in progress; an obstacle.",
        "example": "The ferry strike was a temporary setback, but we found an alternate coastal train.",
        "translation": "انتكاسة / عقبة مؤقتة",
        "exampleArabic": "كان إضراب العبّارات عقبة مؤقتة، لكننا وجدنا قطاراً ساحلياً بديلاً.",
        "relatedForms": ["setbacks"],
        "collocations": ["temporary setback", "major setback", "suffer a setback"],
        "synonyms": ["obstacle", "hindrance", "delay"],
        "antonyms": ["breakthrough", "advance"],
        "tags": ["trouble", "events"]
    },
    {
        "headword": "breakdown",
        "pronunciation": "/ˈbreɪkdaʊn/",
        "partOfSpeech": "noun",
        "definition": "A mechanical failure of a vehicle or machine.",
        "example": "An engine breakdown left us stranded on the mountain pass for three hours.",
        "translation": "عطل ميكانيكي",
        "exampleArabic": "تسبب عطل في المحرك في بقائنا عالقين في الممر الجبلي لمدة ثلاث ساعات.",
        "relatedForms": ["breakdowns"],
        "collocations": ["engine breakdown", "vehicle breakdown", "suffer a breakdown"],
        "synonyms": ["malfunction", "failure"],
        "antonyms": [],
        "tags": ["transport", "trouble"]
    },
    {
        "headword": "stranded",
        "pronunciation": "/ˈstrændɪd/",
        "partOfSpeech": "adjective",
        "definition": "Left without the means to move from somewhere; stuck.",
        "example": "Heavy snowfall left dozens of cars stranded along the alpine highway.",
        "translation": "عالق / مقطوع به السبيل",
        "exampleArabic": "تسبب تساقط الثلوج الكثيفة في بقاء عشرات السيارات عالقة على الطريق السريع الألبي.",
        "relatedForms": [],
        "collocations": ["stranded passengers", "stranded traveler", "left stranded"],
        "synonyms": ["marooned", "abandoned", "stuck"],
        "antonyms": ["rescued", "mobile"],
        "tags": ["travel", "trouble"]
    },
    {
        "headword": "lost baggage",
        "pronunciation": "/lɔːst ˈbæɡɪdʒ/",
        "partOfSpeech": "noun",
        "definition": "Suitcases or personal travel luggage that an airline or carrier fails to deliver.",
        "example": "She had to buy spare clothes when the airline reported her lost baggage.",
        "translation": "حقائب مفقودة",
        "exampleArabic": "اضطرت لشراء ملابس بديلة عندما أبلغت شركة الطيران عن فقدان حقائبها.",
        "relatedForms": [],
        "collocations": ["report lost baggage", "lost baggage claim"],
        "synonyms": ["missing luggage"],
        "antonyms": [],
        "tags": ["travel", "trouble"]
    },
    {
        "headword": "missed flight",
        "pronunciation": "/mɪst flaɪt/",
        "partOfSpeech": "noun",
        "definition": "An air travel booking that a passenger failed to board due to delay or late arrival.",
        "example": "A severe traffic jam on the expressway caused our missed flight.",
        "translation": "رحلة طيران فائتة",
        "exampleArabic": "تسبب ازدحام مروري خانق على الطريق السريع في تفويت رحلتنا الجوية.",
        "relatedForms": ["missed flights"],
        "collocations": ["rebook a missed flight", "compensate for a missed flight"],
        "synonyms": [],
        "antonyms": [],
        "tags": ["travel", "trouble"]
    },
    {
        "headword": "friendly stranger",
        "pronunciation": "/ˈfrendli ˈstreɪndʒər/",
        "partOfSpeech": "noun",
        "definition": "An unknown person who acts kindly, generously, or helpfully toward a traveler.",
        "example": "A friendly stranger offered us hot tea and guided us back to our guesthouse.",
        "translation": "غريب ودود / شخص غير معروف يقدم المساعدة بلطف",
        "exampleArabic": "عرض علينا شخص غريب ودود الشاي الساخن وأرشدنا للعودة إلى دار الضيافة.",
        "relatedForms": ["friendly strangers"],
        "collocations": ["kindness of a friendly stranger", "helped by a friendly stranger"],
        "synonyms": ["good Samaritan"],
        "antonyms": [],
        "tags": ["people", "travel"]
    },
    {
        "headword": "local hospitality",
        "pronunciation": "/ˈloʊkl ˌhɑːspɪˈtæləti/",
        "partOfSpeech": "noun",
        "definition": "The friendly and generous reception of guests and visitors by residents of an area.",
        "example": "We were touched by the warm local hospitality shown in every rural village.",
        "translation": "كرم الضيافة المحلي",
        "exampleArabic": "تأثرنا بكرم الضيافة المحلي الدافئ الذي ظهر في كل قرية ريفية.",
        "relatedForms": [],
        "collocations": ["warm local hospitality", "experience local hospitality"],
        "synonyms": ["cordiality", "welcoming nature"],
        "antonyms": ["hostility"],
        "tags": ["culture", "travel"]
    },
    {
        "headword": "lifesaver",
        "pronunciation": "/ˈlaɪfseɪvər/",
        "partOfSpeech": "noun",
        "definition": "A thing or person that saves someone from a serious difficulty or disaster.",
        "example": "Having a spare portable battery in my jacket was a true lifesaver.",
        "translation": "منقذ الموقف / طوق نجاة",
        "exampleArabic": "كان وجود بطارية متنقلة احتياطية في سترتي منقذاً حقيقياً للموقف.",
        "relatedForms": ["lifesavers"],
        "collocations": ["absolute lifesaver", "real lifesaver", "act as a lifesaver"],
        "synonyms": ["savior", "rescue"],
        "antonyms": [],
        "tags": ["slang", "expression"]
    },
    {
        "headword": "happy ending",
        "pronunciation": "/ˈhæpi ˈendɪŋ/",
        "partOfSpeech": "noun",
        "definition": "A conclusion of a story or event where all conflicts are resolved positively.",
        "example": "Despite all earlier delays, our family journey enjoyed a joyful happy ending.",
        "translation": "نهاية سعيدة",
        "exampleArabic": "على الرغم من كل التأخيرات السابقة، حظيت رحلتنا العائلية بنهاية سعيدة مبهجة.",
        "relatedForms": ["happy endings"],
        "collocations": ["guaranteed happy ending", "reach a happy ending"],
        "synonyms": ["positive resolution"],
        "antonyms": ["tragedy"],
        "tags": ["storytelling"]
    },
    {
        "headword": "lesson learned",
        "pronunciation": "/ˈlesn lɜːrnd/",
        "partOfSpeech": "noun",
        "definition": "Useful knowledge or wisdom gained through an experience, mistake, or ordeal.",
        "example": "Always backing up digital train tickets onto paper was an invaluable lesson learned.",
        "translation": "درس مستفاد",
        "exampleArabic": "كان الاحتفاظ بنسخة ورقية من تذاكر القطار درساً مستفاداً لا يقدر بثمن.",
        "relatedForms": ["lessons learned"],
        "collocations": ["important lesson learned", "takeaway lesson learned"],
        "synonyms": ["takeaway", "moral"],
        "antonyms": [],
        "tags": ["wisdom", "experience"]
    },
    {
        "headword": "reflection",
        "pronunciation": "/rɪˈflekʃən/",
        "partOfSpeech": "noun",
        "definition": "Serious thought or consideration about past events, actions, or choices.",
        "example": "Upon quiet reflection, he realized that traveling had broadened his perspective.",
        "translation": "تأمّل / تفكّر عميق في الماضي",
        "exampleArabic": "عند التأمل الهادئ، أدرك أن السفر قد وسّع أفقه ورؤيته للحياة.",
        "relatedForms": ["reflections", "reflective"],
        "collocations": ["quiet reflection", "upon reflection", "honest reflection"],
        "synonyms": ["contemplation", "pondering", "meditation"],
        "antonyms": [],
        "tags": ["mind", "writing"]
    },
    {
        "headword": "nostalgia",
        "pronunciation": "/nɑːˈstældʒə/",
        "partOfSpeech": "noun",
        "definition": "A sentimental longing or wistful affection for the past.",
        "example": "Hearing that old coastal song always fills me with pleasant travel nostalgia.",
        "translation": "حنين إلى الماضي (نوستالجيا)",
        "exampleArabic": "سماع تلك الأغنية الساحلية القديمة يملأني دائماً بحنين ممتع إلى ذكريات السفر.",
        "relatedForms": ["nostalgic", "nostalgically"],
        "collocations": ["sense of nostalgia", "sweet nostalgia", "wave of nostalgia"],
        "synonyms": ["longing", "yearning", "homesickness"],
        "antonyms": [],
        "tags": ["emotion"]
    },
    {
        "headword": "souvenir story",
        "pronunciation": "/ˌsuːvəˈnɪr ˈstɔːri/",
        "partOfSpeech": "noun",
        "definition": "A personal tale explaining how a particular keepsake or memento was obtained.",
        "example": "Behind every painted clay dish on her shelf rests a charming souvenir story.",
        "translation": "قصة تذكارية (القصة الكامنة وراء الهدية التذكارية)",
        "exampleArabic": "خلف كل طبق فخاري ملون على رفها تكمن قصة تذكارية ساحرة.",
        "relatedForms": ["souvenir stories"],
        "collocations": ["share a souvenir story", "favorite souvenir story"],
        "synonyms": [],
        "antonyms": [],
        "tags": ["travel", "storytelling"]
    },
    {
        "headword": "photo album",
        "pronunciation": "/ˈfoʊtoʊ ˈælbəm/",
        "partOfSpeech": "noun",
        "definition": "A book designed for keeping and displaying photographic prints.",
        "example": "We gathered in the living room to flip through our holiday photo album.",
        "translation": "ألبوم صور",
        "exampleArabic": "اجتمعنا في غرفة المعيشة لتصفح ألبوم صور العطلة الخاص بنا.",
        "relatedForms": ["photo albums"],
        "collocations": ["digital photo album", "family photo album", "wedding photo album"],
        "synonyms": ["picture album"],
        "antonyms": [],
        "tags": ["memory", "photography"]
    },
    {
        "headword": "snapshot",
        "pronunciation": "/ˈsnæpʃɑːt/",
        "partOfSpeech": "noun",
        "definition": "A casual photograph taken quickly, or a brief impression of a situation.",
        "example": "This faded snapshot captured our smiles right after climbing the mountain pass.",
        "translation": "لقطة سريعة / صورة فوتوغرافية عفوية",
        "exampleArabic": "وثقت هذه اللقطة الباهتة ابتساماتنا فور تسلق الممر الجبلي.",
        "relatedForms": ["snapshots"],
        "collocations": ["quick snapshot", "color snapshot", "candid snapshot"],
        "synonyms": ["photo", "photograph", "picture"],
        "antonyms": [],
        "tags": ["photography", "memory"]
    },
    {
        "headword": "just now",
        "pronunciation": "/dʒʌst naʊ/",
        "partOfSpeech": "adverb",
        "definition": "At this very moment, or a tiny fraction of time ago.",
        "example": "Our delayed passenger flight has landed just now on runway two.",
        "translation": "للتو / في هذه اللحظة بالذات",
        "exampleArabic": "هبطت رحلة الركاب المتأخرة للتو على المدرج الثاني.",
        "relatedForms": [],
        "collocations": ["happened just now", "heard just now", "arrived just now"],
        "synonyms": ["a moment ago", "right now"],
        "antonyms": [],
        "tags": ["grammar", "time"]
    },
    {
        "headword": "as of now",
        "pronunciation": "/æz əv naʊ/",
        "partOfSpeech": "adverb",
        "definition": "From this present time forward, or considering the situation at the present moment.",
        "example": "As of now, the airport rail express is operating on standard schedules.",
        "translation": "حتى الآن / اعتباراً من هذه اللحظة",
        "exampleArabic": "اعتباراً من هذه اللحظة، يعمل قطار المطار السريع وفق جداوله المعتادة.",
        "relatedForms": [],
        "collocations": ["as of now we are ready", "valid as of now"],
        "synonyms": ["currently", "presently", "from now on"],
        "antonyms": [],
        "tags": ["grammar", "time"]
    },
    {
        "headword": "not yet",
        "pronunciation": "/nɑːt jet/",
        "partOfSpeech": "adverb",
        "definition": "Not up to the present time; still awaiting occurrence.",
        "example": "Has the transfer bus arrived? No, not yet, but it is approaching.",
        "translation": "ليس بعد / لم يحدث بعد",
        "exampleArabic": "هل وصلت حافلة النقل؟ لا، ليس بعد، ولكنها تقترب.",
        "relatedForms": [],
        "collocations": ["not yet finished", "not yet arrived", "ready? not yet"],
        "synonyms": ["still pending", "so far not"],
        "antonyms": ["already"],
        "tags": ["grammar", "time"]
    },
    {
        "headword": "still pending",
        "pronunciation": "/stɪl ˈpendɪŋ/",
        "partOfSpeech": "adjective",
        "definition": "Awaiting decision or settlement; not yet finalized.",
        "example": "Our claim for the damaged luggage remains still pending with customer support.",
        "translation": "لا يزال معلقاً / قيد الانتظار",
        "exampleArabic": "لا تزال مطالبتنا بشأن الأمتعة التالفة معلقة لدى خدمة العملاء.",
        "relatedForms": [],
        "collocations": ["case is still pending", "approval still pending"],
        "synonyms": ["undecided", "unsettled", "open"],
        "antonyms": ["resolved", "settled"],
        "tags": ["status", "travel"]
    },
    {
        "headword": "recently happened",
        "pronunciation": "/ˈriːsntli ˈhæpənd/",
        "partOfSpeech": "phrase",
        "definition": "Occurred at a time only a short while in the past.",
        "example": "The unusual event recently happened during their stay in Vienna.",
        "translation": "حدث مؤخراً",
        "exampleArabic": "حدث الأمر غير المعتاد مؤخراً أثناء إقامتهم في فيينا.",
        "relatedForms": [],
        "collocations": ["what recently happened", "events that recently happened"],
        "synonyms": ["just occurred"],
        "antonyms": [],
        "tags": ["grammar", "events"]
    },
    {
        "headword": "finished trip",
        "pronunciation": "/ˈfɪnɪʃt trɪp/",
        "partOfSpeech": "noun",
        "definition": "A journey or holiday that has reached its conclusion.",
        "example": "A finished trip always leaves us eager to organize the next adventure.",
        "translation": "رحلة مكتملة ومنتهية",
        "exampleArabic": "تتركنا الرحلة المكتملة دائماً متلهفين لتنظيم المغامرة التالية.",
        "relatedForms": ["finished trips"],
        "collocations": ["memories of a finished trip", "review a finished trip"],
        "synonyms": ["completed journey"],
        "antonyms": ["ongoing journey"],
        "tags": ["travel"]
    },
    {
        "headword": "ongoing journey",
        "pronunciation": "/ˈɑːnɡoʊɪŋ ˈdʒɜːrni/",
        "partOfSpeech": "noun",
        "definition": "A voyage or travel experience that is currently continuing and not yet complete.",
        "example": "Their ongoing journey across the continent will take another four months.",
        "translation": "رحلة مستمرة / جولة متواصلة",
        "exampleArabic": "ستستغرق رحلتهم المستمرة عبر القارة أربعة أشهر أخرى.",
        "relatedForms": ["ongoing journeys"],
        "collocations": ["part of an ongoing journey", "record an ongoing journey"],
        "synonyms": ["continuing voyage"],
        "antonyms": ["finished trip"],
        "tags": ["travel"]
    },
    {
        "headword": "unforgettable trip",
        "pronunciation": "/ˌʌnfərˈɡetəbl trɪp/",
        "partOfSpeech": "noun",
        "definition": "A memorable and impactful travel experience that will always be remembered.",
        "example": "Visiting the northern fjords was truly an unforgettable trip for all of us.",
        "translation": "رحلة لا تُنسى",
        "exampleArabic": "كانت زيارة المضايق الشمالية حقاً رحلة لا تُنسى بالنسبة لنا جميعاً.",
        "relatedForms": ["unforgettable trips"],
        "collocations": ["experience an unforgettable trip", "plan an unforgettable trip"],
        "synonyms": ["trip of a lifetime"],
        "antonyms": [],
        "tags": ["travel"]
    },
    {
        "headword": "storyline",
        "pronunciation": "/ˈstɔːrilaɪn/",
        "partOfSpeech": "noun",
        "definition": "The plot or narrative thread of a story, novel, or personal account.",
        "example": "The intriguing storyline in her travel book kept readers hooked from page one.",
        "translation": "مسار القصة / الخيط الدرامي",
        "exampleArabic": "جعل مسار القصة المثير في كتاب رحلاتها القراء مشدودين منذ الصفحة الأولى.",
        "relatedForms": ["storylines"],
        "collocations": ["compelling storyline", "clear storyline", "main storyline"],
        "synonyms": ["plot", "narrative arc"],
        "antonyms": [],
        "tags": ["writing", "storytelling"]
    },
    {
        "headword": "memories made",
        "pronunciation": "/ˈmeməriz meɪd/",
        "partOfSpeech": "noun",
        "definition": "The personal recollections, experiences, and bonds formed during an event or travel.",
        "example": "The best part of any holiday is always the precious memories made with family.",
        "translation": "الذكريات المصنوعة والمكتسبة",
        "exampleArabic": "أفضل جزء في أي عطلة هو دائماً الذكريات الثمينة المصنوعة مع العائلة.",
        "relatedForms": [],
        "collocations": ["cherish memories made", "all the memories made"],
        "synonyms": ["recollections", "shared moments"],
        "antonyms": [],
        "tags": ["memory", "life"]
    }
]

grammar_day30 = [
    {
        "title": "Present Perfect with just, already, yet",
        "explanation": "We use the Present Perfect tense with 'just', 'already', and 'yet' to connect recent or pending actions with the present moment. 'Just' expresses that an action happened very recently. 'Already' indicates that an action occurred sooner than expected. 'Yet' is used in negative sentences and questions to show that an action is expected, and is placed at the end of the clause.",
        "explanationArabic": "نستخدم زمن المضارع التام مع الكلمات 'just' و 'already' و 'yet' لربط الأحداث القريبة أو المعلقة بالحاضر. تُستخدم 'just' لتدل على أن الفعل حدث للتو قبل قليل. وتُستخدم 'already' للإشارة إلى أن الفعل قد حدث بالفعل مبكراً أو قبل الموعد المتوقع (تأتيان بين have/has والتصريف الثالث). أما 'yet' فتُستخدم في الجمل المنفية والأسئلة لتدل على أن الشيء متوقع حدوثه، ومكانها في نهاية الجملة.",
        "rules": [
            "Use 'just' between have/has and the past participle (V3): 'I have just arrived.'",
            "Use 'already' between have/has and V3 (or at the end for emphasis): 'They have already boarded.'",
            "Use 'yet' at the end of negative sentences: 'We have not received the lost baggage yet.'",
            "Use 'yet' at the end of questions: 'Have you checked into the room yet?'"
        ],
        "rulesArabic": [
            "توضع 'just' بين have/has والتصريف الثالث للفعل: 'I have just arrived' (لقد وصلت للتو).",
            "توضع 'already' بين have/has والتصريف الثالث (أو في نهاية الجملة للتأكيد): 'They have already boarded' (لقد صعدوا بالفعل).",
            "توضع 'yet' في نهاية الجمل المنفية: 'We have not received the luggage yet' (لم نستلم الحقائب بعد).",
            "توضع 'yet' في نهاية الأسئلة: 'Have you checked into the room yet?' (هل سجلت دخولك للغرفة بعد؟)."
        ],
        "structures": [
            {
                "pattern": "Subject + have/has + just + V3",
                "explanation": "Expresses an action that occurred only a short moment ago.",
                "explanationArabic": "يُعبر عن حدث وقع منذ برهة وجيزة جداً (للتو)."
            },
            {
                "pattern": "Subject + have/has + already + V3",
                "explanation": "Expresses an action completed earlier than anticipated.",
                "explanationArabic": "يُعبر عن حدث تم إنجازه بالفعل في وقت أبكر مما كان متوقعاً."
            },
            {
                "pattern": "Have/Has + subject + V3 + ... + yet?",
                "explanation": "Asks if an expected event has taken place up to now.",
                "explanationArabic": "يسأل عما إذا كان حدث متوقع قد وقع حتى الآن."
            }
        ],
        "examples": [
            {
                "sentence": "I have just completed writing another chapter in my travel journal.",
                "translation": "لقد انتهيت للتو من كتابة فصل آخر في دفتر يوميات سفري.",
                "usesVocabulary": ["journal", "just now"]
            },
            {
                "sentence": "They have already published a bestselling memoir about that unforgettable trip.",
                "translation": "لقد نشروا بالفعل مذكرات حققت أعلى المبيعات حول تلك الرحلة التي لا تُنسى.",
                "usesVocabulary": ["memoir", "unforgettable trip"]
            },
            {
                "sentence": "We have not located our lost baggage at the international terminal yet.",
                "translation": "لم نحدد موقع حقائبنا المفقودة في صالة السفر الدولية بعد.",
                "usesVocabulary": ["lost baggage", "not yet"]
            },
            {
                "sentence": "Has the storyteller narrated the dramatic climax of the tale yet?",
                "translation": "هل روى الحكواتي ذروة الأحداث الدرامية للحكاية بعد؟",
                "usesVocabulary": ["storyteller", "climax", "tale"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "I have already not finished my packing.",
                "right": "I have not finished my packing yet.",
                "note": "Do not use 'already' in negative sentences when expressing pending completion; use 'yet' at the end.",
                "noteArabic": "لا تستخدم 'already' في الجمل المنفية للتعبير عن إتمام معلق، بل استخدم 'yet' في نهاية الجملة."
            },
            {
                "wrong": "Did the flight land yet?",
                "right": "Has the flight landed yet?",
                "note": "Standard British and formal international English requires Present Perfect with 'yet' for pending status.",
                "noteArabic": "الإنجليزية القياسية تتطلب استخدام المضارع التام مع 'yet' عند السؤال عن أمر متوقع إتمامه."
            }
        ]
    }
]

convs_day30 = [
    {
        "title": "Resolving Airport Travel Troubles",
        "titleArabic": "حل متاعب السفر في المطار",
        "setting": "Two passengers dealing with sudden airport delays and missing luggage",
        "settingArabic": "مسافران يتعاملان مع تأخيرات مفاجئة وحقائب مفقودة في المطار",
        "vocabularyUsed": ["lost baggage", "missed flight", "setback", "breakdown", "stranded", "lifesaver", "friendly stranger", "happy ending"],
        "lines": [
            {"speaker": "Hassan", "text": "I cannot believe the expressway shuttle breakdown made us miss our connecting flight!", "translation": "لا أصدق أن عطل حافلة المطار على الطريق السريع جعلنا نفوت رحلتنا المتصلة!"},
            {"speaker": "Amina", "text": "Take a deep breath; a missed flight is only a temporary setback, not the end of the world.", "translation": "خذ نفساً عميقاً؛ فرحلة الطيران الفائتة ليست سوى عقبة مؤقتة وليست نهاية العالم."},
            {"speaker": "Hassan", "text": "Have you heard any news regarding our lost baggage from the customer desk yet?", "translation": "هل سمعتِ أي أخبار بخصوص حقائبنا المفقودة من مكتب خدمة العملاء بعد؟"},
            {"speaker": "Amina", "text": "Not yet, but a friendly stranger waiting next to us advised us to file a digital claim immediately.", "translation": "ليس بعد، ولكن شخصاً غريباً ودوداً كان ينتظر بجوارنا نصحنا بتقديم مطالبة رقمية على الفور."},
            {"speaker": "Hassan", "text": "That helpful clerk was a real lifesaver; she rebooked our seats without any extra penalties.", "translation": "كانت تلك الموظفة المتعاونة منقذة حقيقية للموقف؛ فقد أعادت حجز مقاعدنا دون أي غرامات إضافية."},
            {"speaker": "Amina", "text": "Exactly. We were almost left stranded overnight, but now we board in two hours.", "translation": "بالضبط. كدنا أن نُترك عالقين طوال الليل، لكننا سنصعد للطائرة الآن في غضون ساعتين."},
            {"speaker": "Hassan", "text": "Every travel trial makes for a funny story once we reach our destination.", "translation": "كل محنة في السفر تصبح قصة مضحكة بمجرد وصولنا إلى وجهتنا."},
            {"speaker": "Amina", "text": "Indeed, as long as our adventure reaches a joyful happy ending, it is all worthwhile.", "translation": "بالفعل، فطالما أن مغامرتنا تصل إلى نهاية سعيدة مبهجة، فإن كل ذلك يستحق العناء."}
        ]
    },
    {
        "title": "Recounting Hilarious Road Misadventures",
        "titleArabic": "سرد المغامرات البرية الطريفة",
        "setting": "Friends laughing about mishaps while sharing a meal",
        "settingArabic": "أصدقاء يضحكون على الورطات أثناء مشاركة وجبة طعام",
        "vocabularyUsed": ["anecdote", "humorous", "mishap", "misadventure", "unexpected turn", "plot twist", "recount", "narrate"],
        "lines": [
            {"speaker": "Zaid", "text": "Do you remember when our rental car experienced that comical misadventure in the hills?", "translation": "هل تذكر عندما واجهت سيارتنا المستأجرة تلك المغامرة الكوميدية الفاشلة في التلال؟"},
            {"speaker": "Lina", "text": "How could I forget? Please recount that humorous anecdote for our new guests!", "translation": "كيف لي أن أنسى؟ يرجى أن تسرد تلك الطرفة الفكاهية لضيوفنا الجدد!"},
            {"speaker": "Zaid", "text": "Well, we followed a shortcut on our navigation app, but the road took an unexpected turn.", "translation": "حسناً، اتبعنا طريقاً مختصراً على تطبيق الملاحة، لكن الطريق اتخذ منعطفاً غير متوقع."},
            {"speaker": "Lina", "text": "We ended up surrounded by fifty peaceful sheep resting squarely across the gravel path!", "translation": "انتهى بنا المطاف محاطين بخمسين خروفاً وديعاً تستريح مباشرة عبر المسار الحصوي!"},
            {"speaker": "Zaid", "text": "And the ultimate plot twist was that the farmer invited us inside for fresh goat cheese and tea.", "translation": "وكانت الحبكة المفاجئة الكبرى أن المزارع دعانا إلى الداخل لتناول جبن الماعز الطازج والشاي."},
            {"speaker": "Lina", "text": "What started as an irritating travel mishap transformed into our favorite trip memory.", "translation": "ما بدأ كحادث سفر عارض مزعج تحول إلى ذكرى الرحلة المفضلة لدينا."},
            {"speaker": "Zaid", "text": "Travelers should always narrate both the triumphs and the silly blunders of their voyages.", "translation": "يجب على المسافرين دائماً رواية كل من النجاحات والهفوات السخيفة لرحلاتهم."},
            {"speaker": "Lina", "text": "The blunders definitely make for the most entertaining storytelling!", "translation": "من المؤكد أن الهفوات تصنع أمتع أساليب السرد القصصي!"}
        ]
    },
    {
        "title": "Flipping Through Old Travel Albums",
        "titleArabic": "تصفح ألبومات السفر القديمة",
        "setting": "Two relatives reminiscing over family photos",
        "settingArabic": "قريبان يستعيدان الذكريات على صور العائلة",
        "vocabularyUsed": ["photo album", "snapshot", "reminisce", "relive", "nostalgia", "souvenir story", "memories made", "vivid"],
        "lines": [
            {"speaker": "Mona", "text": "Look at this thick holiday photo album I just uncovered from the bookshelf upstairs.", "translation": "انظر إلى ألبوم صور العطلات السميك هذا الذي اكتشفته للتو من رف الكتب بالأعلى."},
            {"speaker": "Sami", "text": "What a treasure! It feels wonderful to reminisce about our family coastal adventures.", "translation": "يا له من كنز! من الرائع استعادة ذكريات مغامرات عائلتنا الساحلية بحنين."},
            {"speaker": "Mona", "text": "Here is a candid snapshot of all of us getting soaked under the waterfall spray.", "translation": "إليك لقطة عفوية لنا جميعاً ونحن نبتل تحت رذاذ الشلال."},
            {"speaker": "Sami", "text": "That brings back such vivid recollections; you can almost relive the cold refreshing mountain water.", "translation": "ذلك يعيد ذكريات ناصعة الوضوح؛ يمكنك تقريباً معايشة مياه الجبل الباردة المنعشة مجدداً."},
            {"speaker": "Mona", "text": "And do you see this carved wooden camel? There is a fascinating souvenir story behind it.", "translation": "وهل ترى هذا الجمل الخشبي المنحوت؟ هناك قصة تذكارية رائعة وراءه."},
            {"speaker": "Sami", "text": "Yes, we bartered with that artisan in the desert oasis just before sunset.", "translation": "نعم، قايضنا مع ذلك الحرفي في الواحة الصحراوية قبل غروب الشمس مباشرة."},
            {"speaker": "Mona", "text": "A sweet wave of nostalgia washes over me whenever I reflect on those golden years.", "translation": "تغمرني موجة حلوة من النوستالجيا كلما تفكرت في تلك السنوات الذهبية."},
            {"speaker": "Sami", "text": "The places may change, but the precious memories made will remain forever in our hearts.", "translation": "قد تتغير الأماكن، لكن الذكريات الثمينة التي صنعناها ستبقى إلى الأبد في قلوبنا."}
        ]
    }
]

paras_day30 = [
    {
        "title": "The Art of Travel Storytelling",
        "titleArabic": "فن سرد قصص السفر",
        "kind": "informative",
        "vocabularyUsed": ["chronicle", "narrative", "storyteller", "storyline", "spooky", "thrilling", "dramatic"],
        "text": "Every long journey naturally forms a rich narrative waiting to be shared. A talented storyteller understands how to shape a compelling storyline that balances picturesque scenes with genuine human challenges. Whether describing a spooky midnight walk through abandoned alleys or a thrilling climb across icy mountain passes, details matter deeply. A dramatic shift in the weather or an unexpected encounter elevates an ordinary chronicle into an enduring work of literature. Through authentic narration, readers experience distant lands without leaving their homes.",
        "translation": "تشكل كل رحلة طويلة بشكل طبيعي سرداً غنياً ينتظر مشاركته. ويدرك راوي القصص الموهوب كيفية تشكيل مسار قصة جذاب يوازن بين المشاهد الخلابة والتحديات الإنسانية الحقيقية. وسواء أكان يصف نزهة مريبة في منتصف الليل عبر أزقة مهجورة أم تسلقاً مثيراً عبر ممرات جبلية جليدية، فإن التفاصيل تهم للغاية. إن التحول الدرامي في الطقس أو اللقاء غير المتوقع يرفع شأن السجل العادي للأحداث إلى عمل أدبي خالد. ومن خلال السرد الأصيل، يعايش القراء أراضي بعيدة دون مغادرة منازلهم."
    },
    {
        "title": "Lessons from Unplanned Detours",
        "titleArabic": "دروس من المنعطفات غير المخطط لها",
        "kind": "reflective",
        "vocabularyUsed": ["diary", "logbook", "travelogue", "reflection", "lesson learned", "local hospitality", "describe in detail"],
        "text": "When mariners inspect an old sea logbook, they find records of sudden storms and difficult passages. Similarly, a traveler's personal diary captures moments when plans fall apart. It is easy to describe in detail the sunny beaches, but the true lesson learned usually emerges from unexpected detours. Being welcomed by local hospitality when lost teaches profound humility. Decades later, when authors review their early travelogue, that quiet reflection reveals that unforeseen detours shaped their character far more than planned luxury resorts ever could.",
        "translation": "عندما يتفقد البحارة سجل رحلة بحرية قديم، يجدون سجلات للعواصف المفاجئة والمسالك الصعبة. وبالمثل، تلتقط اليوميات الخاصة للمسافر لحظات تداعي الخطط وانهيارها. من السهل أن تصف بالتفصيل الشواطئ المشمسة، لكن الدرس الحقيقي المستفاد يظهر عادة من المنعطفات غير المتوقعة. إن الترحيب بك بكرم الضيافة المحلي عندما تضل طريقك يعلمك تواضعاً عميقاً. وبعد عقود، عندما يراجع المؤلفون أدب رحلاتهم المبكر، يكشف ذلك التأمل الهادئ أن المنعطفات غير المتوقعة شكلت شخصيتهم أكثر بكثير مما فعلته المنتجعات الفاخرة المخطط لها."
    },
    {
        "title": "Journeys Finished and Still Continuing",
        "titleArabic": "رحلات اكتملت وأخرى لا تزال مستمرة",
        "kind": "informative",
        "vocabularyUsed": ["finished trip", "ongoing journey", "as of now", "still pending", "recently happened", "not yet", "just now"],
        "text": "Every traveler recognizes the bittersweet emotion that accompanies a finished trip. While some vacation photos have just now been uploaded, other travel arrangements remain still pending confirmation. An ongoing journey across distant continents requires flexibility, because what recently happened can instantly alter upcoming itineraries. As of now, several transport routes have reopened, yet many travelers have not yet boarded their return shuttles. Embracing uncertainty is the defining characteristic of experienced wanderers who understand that every voyage continues in the mind long after arriving home.",
        "translation": "يدرك كل مسافر المشاعر المختلطة حلوها ومرها التي تصاحب الرحلة المنتهية. فبينما تم للتو رفع بعض صور العطلات، تظل ترتيبات السفر الأخرى قيد الانتظار في انتظار التأكيد. وتتطلب الرحلة المستمرة عبر قارات بعيدة مرونة فائقة، لأن ما حدث مؤخراً يمكن أن يغير مسارات السفر القادمة في الحال. واعتباراً من هذه اللحظة، أعيد فتح العديد من طرق النقل، ومع ذلك لم يصعد الكثير من المسافرين إلى حافلات عودتهم بعد. إن تقبل المجهول هو السمة المميزة للرحالة ذوي الخبرة الذين يدركون أن كل رحلة تستمر في العقل بعد الوصول إلى المنزل بوقت طويل."
    }
]
