# -*- coding: utf-8 -*-
"""Data definition for Day 29: Travel Experiences."""

vocab_day29 = [
    {
        "headword": "escapade",
        "pronunciation": "/ˈeskəpeɪd/",
        "partOfSpeech": "noun",
        "definition": "An act or incident involving excitement, daring, or adventure.",
        "example": "Our weekend escapade in the desert dunes was truly unforgettable.",
        "translation": "مغامرة جريئة / مغامرة طريفة",
        "exampleArabic": "كانت مغامرتنا في عطلة نهاية الأسبوع في الكثبان الصحراوية لا تُنسى حقاً.",
        "relatedForms": ["escapades"],
        "collocations": ["wild escapade", "youthful escapade", "daring escapade"],
        "synonyms": ["adventure", "exploit", "stunt"],
        "antonyms": [],
        "tags": ["travel", "adventure"]
    },
    {
        "headword": "memorable",
        "pronunciation": "/ˈmemərəbl/",
        "partOfSpeech": "adjective",
        "definition": "Easily remembered, especially because of being special or unusual.",
        "example": "Watching the sunrise over Mount Fuji was a memorable moment.",
        "translation": "لا يُنسى / جدير بالذكر",
        "exampleArabic": "كانت مشاهدة شروق الشمس فوق جبل فوجي لحظة لا تُنسى.",
        "relatedForms": ["memorably"],
        "collocations": ["memorable experience", "memorable event", "memorable occasion"],
        "synonyms": ["unforgettable", "notable", "impressive"],
        "antonyms": ["forgettable"],
        "tags": ["travel", "description"]
    },
    {
        "headword": "unforgettable",
        "pronunciation": "/ˌʌnfərˈɡetəbl/",
        "partOfSpeech": "adjective",
        "definition": "Impossible to forget; very memorable.",
        "example": "Swimming beside tropical sea turtles was an unforgettable encounter.",
        "translation": "خالد في الذاكرة / لا يُنسى",
        "exampleArabic": "كانت السباحة بجانب السلاحف البحرية الاستوائية لقاءً لا يُنسى.",
        "relatedForms": ["unforgettably"],
        "collocations": ["unforgettable trip", "unforgettable memory", "unforgettable journey"],
        "synonyms": ["haunting", "indelible", "memorable"],
        "antonyms": ["forgettable"],
        "tags": ["travel", "description"]
    },
    {
        "headword": "expedition",
        "pronunciation": "/ˌekspəˈdɪʃən/",
        "partOfSpeech": "noun",
        "definition": "A journey undertaken by a group of people with a particular purpose, especially exploration.",
        "example": "The scientific expedition ventured deep into the Amazon basin.",
        "translation": "رحلة استكشافية / بعثة",
        "exampleArabic": "غامرت البعثة الاستكشافية العلمية بالدخول إلى أعماق حوض الأمازون.",
        "relatedForms": ["expeditions"],
        "collocations": ["polar expedition", "research expedition", "mountain expedition"],
        "synonyms": ["voyage", "trek", "mission"],
        "antonyms": [],
        "tags": ["travel", "adventure"]
    },
    {
        "headword": "milestone",
        "pronunciation": "/ˈmaɪlstoʊn/",
        "partOfSpeech": "noun",
        "definition": "A significant stage or event in the development of something or someone's life.",
        "example": "Traveling solo across South America was a major personal milestone.",
        "translation": "إنجاز بارز / محطة فارقة",
        "exampleArabic": "كان السفر بمفردي عبر أمريكا الجنوبية محطة فارقة كبرى في حياتي.",
        "relatedForms": ["milestones"],
        "collocations": ["reach a milestone", "major milestone", "career milestone"],
        "synonyms": ["landmark", "turning point", "achievement"],
        "antonyms": [],
        "tags": ["life", "travel"]
    },
    {
        "headword": "bucket list",
        "pronunciation": "/ˈbʌkɪt lɪst/",
        "partOfSpeech": "noun",
        "definition": "A number of experiences or achievements that a person hopes to have or accomplish during their lifetime.",
        "example": "Seeing the Northern Lights is at the top of my travel bucket list.",
        "translation": "قائمة الأمنيات (قبل الموت)",
        "exampleArabic": "رؤية أضواء الشفق القطبي تقع على رأس قائمة أمنيات السفر الخاصة بي.",
        "relatedForms": [],
        "collocations": ["bucket list destination", "cross off bucket list", "item on bucket list"],
        "synonyms": ["wish list", "life goals"],
        "antonyms": [],
        "tags": ["travel", "lifestyle"]
    },
    {
        "headword": "lifetime",
        "pronunciation": "/ˈlaɪftaɪm/",
        "partOfSpeech": "noun",
        "definition": "The duration of a person's life.",
        "example": "Visiting Antarctica was truly the greatest adventure of my lifetime.",
        "translation": "مدى الحياة / العمر",
        "exampleArabic": "كانت زيارة القارة القطبية الجنوبية حقاً أعظم مغامرة في حياتي.",
        "relatedForms": [],
        "collocations": ["in my lifetime", "lifetime experience", "lifetime achievement"],
        "synonyms": ["life span", "all one's days"],
        "antonyms": [],
        "tags": ["time", "life"]
    },
    {
        "headword": "spectacular",
        "pronunciation": "/spekˈtækjələr/",
        "partOfSpeech": "adjective",
        "definition": "Beautiful in a dramatic and eye-catching way.",
        "example": "We enjoyed a spectacular panorama of the fjord from the cliff top.",
        "translation": "مذهل / استثنائي / خلاب",
        "exampleArabic": "استمتعنا بمشهد بانورامي خلاب للمضيق البحري من قمة الجرف.",
        "relatedForms": ["spectacularly"],
        "collocations": ["spectacular view", "spectacular scenery", "spectacular sunset"],
        "synonyms": ["breathtaking", "magnificent", "dazzling"],
        "antonyms": ["unimpressive", "dull"],
        "tags": ["description", "travel"]
    },
    {
        "headword": "breathtaking",
        "pronunciation": "/ˈbreθteɪkɪŋ/",
        "partOfSpeech": "adjective",
        "definition": "Astonishing or awe-inspiring in quality, so as to take one's breath away.",
        "example": "The sight of the snow-capped Himalayan peaks was absolutely breathtaking.",
        "translation": "يخطف الأنفاس / فائق الجمال",
        "exampleArabic": "كان منظر قمم الهيمالايا المغطاة بالثلوج يخطف الأنفاس تماماً.",
        "relatedForms": ["breathtakingly"],
        "collocations": ["breathtaking view", "breathtaking beauty", "breathtaking landscape"],
        "synonyms": ["awe-inspiring", "spectacular", "stunning"],
        "antonyms": ["boring", "ordinary"],
        "tags": ["description", "travel"]
    },
    {
        "headword": "bizarre",
        "pronunciation": "/bɪˈzɑːr/",
        "partOfSpeech": "adjective",
        "definition": "Very strange or unusual, especially so as to cause interest or amusement.",
        "example": "We tasted some bizarre street food delicacies at the night market.",
        "translation": "غريب جداً / شاذ ومدهش",
        "exampleArabic": "تذوقنا بعض مأكولات الشارع الغريبة والفريدة في السوق الليلي.",
        "relatedForms": ["bizarrely"],
        "collocations": ["bizarre customs", "bizarre spectacle", "bizarre phenomenon"],
        "synonyms": ["peculiar", "weird", "strange"],
        "antonyms": ["normal", "conventional"],
        "tags": ["description"]
    },
    {
        "headword": "exotic",
        "pronunciation": "/ɪɡˈzɑːtɪk/",
        "partOfSpeech": "adjective",
        "definition": "Originating in or characteristic of a distant foreign country.",
        "example": "The island botanical garden houses thousands of exotic orchids and palms.",
        "translation": "فريد / غريب ومثير / استوائي",
        "exampleArabic": "تضم الحديقة النباتية في الجزيرة آلاف بساتين الفاكهة وأشجار النخيل الاستوائية الفريدة.",
        "relatedForms": ["exotically"],
        "collocations": ["exotic animals", "exotic flowers", "exotic destinations"],
        "synonyms": ["tropical", "foreign", "unusual"],
        "antonyms": ["native", "domestic"],
        "tags": ["nature", "travel"]
    },
    {
        "headword": "marvelous",
        "pronunciation": "/ˈmɑːrvələs/",
        "partOfSpeech": "adjective",
        "definition": "Causing great wonder; extraordinary.",
        "example": "We spent a marvelous afternoon strolling through historical gardens.",
        "translation": "رائع / بديع",
        "exampleArabic": "أمضينا ظهيرة رائعة في التجول عبر الحدائق التاريخية.",
        "relatedForms": ["marvelously"],
        "collocations": ["marvelous weather", "marvelous time", "marvelous discovery"],
        "synonyms": ["wonderful", "splendid", "superb"],
        "antonyms": ["awful", "terrible"],
        "tags": ["description"]
    },
    {
        "headword": "astonishing",
        "pronunciation": "/əˈstɑːnɪʃɪŋ/",
        "partOfSpeech": "adjective",
        "definition": "Extremely surprising or impressive; amazing.",
        "example": "The architectural precision of the ancient ruins is truly astonishing.",
        "translation": "مذهل / مدهش للغاية",
        "exampleArabic": "الدقة المعمارية للآثار القديمة مذهلة حقاً.",
        "relatedForms": ["astonish", "astonishingly"],
        "collocations": ["astonishing achievement", "astonishing sight", "astonishing speed"],
        "synonyms": ["astounding", "staggering", "amazing"],
        "antonyms": ["predictable", "unremarkable"],
        "tags": ["description"]
    },
    {
        "headword": "stunning",
        "pronunciation": "/ˈstʌnɪŋ/",
        "partOfSpeech": "adjective",
        "definition": "Extremely impressive or attractive.",
        "example": "She took stunning photographs of the coastal cliffs during golden hour.",
        "translation": "فاتن / باهر / رائع الجمال",
        "exampleArabic": "التقطت صوراً فاتنة للمنحدرات الساحلية خلال الساعة الذهبية.",
        "relatedForms": ["stunningly"],
        "collocations": ["stunning view", "stunning backdrop", "stunning portrait"],
        "synonyms": ["gorgeous", "striking", "dazzling"],
        "antonyms": ["ugly", "plain"],
        "tags": ["description", "travel"]
    },
    {
        "headword": "fascinating",
        "pronunciation": "/ˈfæsɪneɪtɪŋ/",
        "partOfSpeech": "adjective",
        "definition": "Extremely interesting.",
        "example": "Learning about indigenous ocean navigation was a fascinating lecture.",
        "translation": "رائع / شيق للغاية / آسر",
        "exampleArabic": "كان التعلم عن الملاحة البحرية للسكان الأصليين محاضرة آسرة للغاية.",
        "relatedForms": ["fascinate", "fascination"],
        "collocations": ["fascinating history", "fascinating culture", "fascinating place"],
        "synonyms": ["captivating", "engrossing", "intriguing"],
        "antonyms": ["boring", "tedious"],
        "tags": ["description"]
    },
    {
        "headword": "monument",
        "pronunciation": "/ˈmɑːnjəmənt/",
        "partOfSpeech": "noun",
        "definition": "A statue, building, or other structure erected to commemorate a notable person or event.",
        "example": "Thousands of visitors gather daily around the national monument.",
        "translation": "نصب تذكاري / أثر",
        "exampleArabic": "يتجمع آلاف الزوار يومياً حول النصب التذكاري الوطني.",
        "relatedForms": ["monumental"],
        "collocations": ["historical monument", "national monument", "ancient monument"],
        "synonyms": ["memorial", "shrine", "statue"],
        "antonyms": [],
        "tags": ["travel", "history"]
    },
    {
        "headword": "historic site",
        "pronunciation": "/hɪˈstɔːrɪk saɪt/",
        "partOfSpeech": "noun",
        "definition": "An official location where pieces of political, military, cultural, or social history have been preserved.",
        "example": "The old castle grounds were designated an official historic site.",
        "translation": "موقع تاريخي",
        "exampleArabic": "تم تصنيف أراضي القلعة القديمة كموقع تاريخي رسمي.",
        "relatedForms": ["historic sites"],
        "collocations": ["visit a historic site", "preserved historic site", "world historic site"],
        "synonyms": ["heritage site"],
        "antonyms": [],
        "tags": ["history", "travel"]
    },
    {
        "headword": "ruins",
        "pronunciation": "/ˈruːɪnz/",
        "partOfSpeech": "noun",
        "definition": "The physical remains of a building, city, etc., that has suffered destruction or decayed.",
        "example": "We spent three hours exploring the Roman ruins in Baalbek.",
        "translation": "أطلال / آثار متبقية",
        "exampleArabic": "أمضينا ثلاث ساعات في استكشاف الآثار والأطلال الرومانية في بعلبك.",
        "relatedForms": ["ruin"],
        "collocations": ["ancient ruins", "crumbling ruins", "archaeological ruins"],
        "synonyms": ["remains", "relics", "vestiges"],
        "antonyms": [],
        "tags": ["history", "travel"]
    },
    {
        "headword": "ancient",
        "pronunciation": "/ˈeɪnʃənt/",
        "partOfSpeech": "adjective",
        "definition": "Belonging to the very distant past and no longer in existence.",
        "example": "They discovered ancient trade scrolls buried beneath the stone chamber.",
        "translation": "قديم جداً / عتيق",
        "exampleArabic": "اكتشفوا لفائف تجارية قديمة مدفونة تحت الحجرة الحجرية.",
        "relatedForms": ["anciently"],
        "collocations": ["ancient civilization", "ancient ruins", "ancient wisdom"],
        "synonyms": ["antique", "prehistoric", "archaic"],
        "antonyms": ["modern", "contemporary"],
        "tags": ["history", "description"]
    },
    {
        "headword": "temple",
        "pronunciation": "/ˈtempl/",
        "partOfSpeech": "noun",
        "definition": "A building devoted to the worship, or regarded as the dwelling place, of a god or other deities.",
        "example": "Incense filled the courtyard of the Buddhist temple at dawn.",
        "translation": "معبد",
        "exampleArabic": "ملأ البخور باحة المعبد البوذي عند الفجر.",
        "relatedForms": ["temples"],
        "collocations": ["ancient temple", "golden temple", "visit a temple"],
        "synonyms": ["sanctuary", "shrine", "house of worship"],
        "antonyms": [],
        "tags": ["religion", "travel"]
    },
    {
        "headword": "pyramid",
        "pronunciation": "/ˈpɪrəmɪd/",
        "partOfSpeech": "noun",
        "definition": "A monumental structure with a square or triangular base and sloping sides that meet in a point at the top.",
        "example": "Have you ever seen the Great Pyramid rising against the sunset?",
        "translation": "هرم",
        "exampleArabic": "هل سبق لك أن رأيت الهرم الأكبر يرتفع في مواجهة غروب الشمس؟",
        "relatedForms": ["pyramids", "pyramidal"],
        "collocations": ["Egyptian pyramid", "step pyramid", "ancient pyramid"],
        "synonyms": [],
        "antonyms": [],
        "tags": ["history", "travel"]
    },
    {
        "headword": "castle",
        "pronunciation": "/ˈkæsl/",
        "partOfSpeech": "noun",
        "definition": "A large building, typically of the medieval period, fortified against attack with thick walls and towers.",
        "example": "We hiked up the rocky hill to inspect the fortress castle.",
        "translation": "قلعة / قصر محصن",
        "exampleArabic": "صعدنا التل الصخري لتفقد القلعة الحصينة.",
        "relatedForms": ["castles"],
        "collocations": ["medieval castle", "royal castle", "castle moat"],
        "synonyms": ["fortress", "citadel", "stronghold"],
        "antonyms": [],
        "tags": ["history", "travel"]
    },
    {
        "headword": "palace",
        "pronunciation": "/ˈpæləs/",
        "partOfSpeech": "noun",
        "definition": "A large and impressive building forming the official residence of a ruler, pope, or sovereign.",
        "example": "The gilded mirrors inside the royal palace reflected dazzling chandeliers.",
        "translation": "قصر ملكي",
        "exampleArabic": "عكست المرايا المذهبة داخل القصر الملكي ثريات باهرة.",
        "relatedForms": ["palaces", "palatial"],
        "collocations": ["royal palace", "presidential palace", "palace courtyard"],
        "synonyms": ["mansion", "residence", "chateau"],
        "antonyms": [],
        "tags": ["architecture", "history"]
    },
    {
        "headword": "cathedral",
        "pronunciation": "/kəˈθiːdrəl/",
        "partOfSpeech": "noun",
        "definition": "The principal church of a diocese, with which the bishop is officially associated.",
        "example": "Stained-glass windows cast colorful beams across the stone cathedral.",
        "translation": "كاتدرائية",
        "exampleArabic": "ألقت النوافذ الزجاجية الملونة حزماً مضيئة متألقة عبر الكاتدرائية الحجرية.",
        "relatedForms": ["cathedrals"],
        "collocations": ["Gothic cathedral", "historic cathedral", "soaring cathedral"],
        "synonyms": ["basilica", "minster"],
        "antonyms": [],
        "tags": ["architecture", "religion"]
    },
    {
        "headword": "shrine",
        "pronunciation": "/ʃraɪn/",
        "partOfSpeech": "noun",
        "definition": "A place associated with or containing memorabilia of a revered person or thing.",
        "example": "Pilgrims walked miles in quiet devotion to reach the mountain shrine.",
        "translation": "ضريح / مزار مقدس",
        "exampleArabic": "مشى الحجاج أميالاً في خشوع صامت للوصول إلى المزار الجبلي.",
        "relatedForms": ["shrines"],
        "collocations": ["sacred shrine", "mountaintop shrine", "pilgrimage shrine"],
        "synonyms": ["sanctuary", "holy place"],
        "antonyms": [],
        "tags": ["religion", "travel"]
    },
    {
        "headword": "marvel",
        "pronunciation": "/ˈmɑːrvl/",
        "partOfSpeech": "verb",
        "definition": "To be filled with wonder, admiration, or astonishment.",
        "example": "Tourists marvel at the intricate mosaics decorating the courtyard.",
        "translation": "يتعجب / ينبهر",
        "exampleArabic": "ينبهر السياح بالفسيفساء المعقدة التي تزين الفناء.",
        "relatedForms": ["marveled", "marveling"],
        "collocations": ["marvel at the sight", "marvel at the beauty"],
        "synonyms": ["wonder", "gaze in awe", "admire"],
        "antonyms": [],
        "tags": ["emotion", "travel"]
    },
    {
        "headword": "safari",
        "pronunciation": "/səˈfɑːri/",
        "partOfSpeech": "noun",
        "definition": "An expedition to observe or photograph animals in their natural habitat.",
        "example": "Going on an African wildlife safari had been her lifelong dream.",
        "translation": "رحلة سفاري",
        "exampleArabic": "كان الذهاب في رحلة سفاري لمشاهدة الحياة البرية في أفريقيا حلم حياتها.",
        "relatedForms": ["safaris"],
        "collocations": ["wildlife safari", "guided safari", "safari tour"],
        "synonyms": ["game drive"],
        "antonyms": [],
        "tags": ["travel", "adventure"]
    },
    {
        "headword": "scuba diving",
        "pronunciation": "/ˈskuːbə ˌdaɪvɪŋ/",
        "partOfSpeech": "noun",
        "definition": "The sport or activity of swimming underwater using an aqualung.",
        "example": "She took a certification course for scuba diving in the Red Sea.",
        "translation": "الغوص بجهاز التنفس (سكوبا)",
        "exampleArabic": "حصلت على دورة معتمدة للغوص بجهاز التنفس (سكوبا) في البحر الأحمر.",
        "relatedForms": [],
        "collocations": ["go scuba diving", "scuba diving gear", "deep scuba diving"],
        "synonyms": ["deep-sea diving"],
        "antonyms": [],
        "tags": ["sports", "adventure"]
    },
    {
        "headword": "snorkeling",
        "pronunciation": "/ˈsnɔːrkəlɪŋ/",
        "partOfSpeech": "noun",
        "definition": "The practice of swimming on or through water while equipped with a diving mask and a shaped breathing tube.",
        "example": "We spent the sunny morning snorkeling among coral reefs.",
        "translation": "الغطس السطحي بأنبوب التنفس",
        "exampleArabic": "أمضينا الصباح المشمس في الغطس السطحي بين الشعاب المرجانية.",
        "relatedForms": ["snorkel"],
        "collocations": ["go snorkeling", "snorkeling gear", "reef snorkeling"],
        "synonyms": [],
        "antonyms": [],
        "tags": ["sports", "water"]
    },
    {
        "headword": "skydiving",
        "pronunciation": "/ˈskaɪdaɪvɪŋ/",
        "partOfSpeech": "noun",
        "definition": "The sport of jumping from an aircraft and performing acrobatic maneuvers in the air under free fall before landing by parachute.",
        "example": "Tandem skydiving gave him an exhilarating burst of pure adrenaline.",
        "translation": "القفز المظلي من الطائرة",
        "exampleArabic": "منحه القفز المظلي الثنائي دفعة مبهجة من الأدرينالين الخالص.",
        "relatedForms": ["skydive"],
        "collocations": ["tandem skydiving", "try skydiving", "extreme skydiving"],
        "synonyms": ["parachuting"],
        "antonyms": [],
        "tags": ["extreme sports", "adventure"]
    },
    {
        "headword": "bungee jumping",
        "pronunciation": "/ˈbʌndʒi ˌdʒʌmpɪŋ/",
        "partOfSpeech": "noun",
        "definition": "The activity of leaping from a high structure while attached to a thick elastic cord.",
        "example": "Have you ever considered bungee jumping off a suspension bridge?",
        "translation": "القفز بالحبال المطاطية (بانجي جامب)",
        "exampleArabic": "هل فكرت يوماً في القفز بالحبال المطاطية من فوق جسر معلق؟",
        "relatedForms": [],
        "collocations": ["try bungee jumping", "bungee jumping platform", "thrill of bungee jumping"],
        "synonyms": [],
        "antonyms": [],
        "tags": ["extreme sports", "adventure"]
    },
    {
        "headword": "paragliding",
        "pronunciation": "/ˈpærəɡlaɪdɪŋ/",
        "partOfSpeech": "noun",
        "definition": "The sport of gliding through the air attached to a wide canopy resembling a parachute.",
        "example": "We floated above the alpine valleys while paragliding with an instructor.",
        "translation": "الطيران الشراعي بالمظلة",
        "exampleArabic": "حلقنا فوق الوديان الجبلية أثناء الطيران الشراعي بمظلة مع مدرب.",
        "relatedForms": ["paraglide"],
        "collocations": ["go paragliding", "tandem paragliding", "alpine paragliding"],
        "synonyms": [],
        "antonyms": [],
        "tags": ["extreme sports", "adventure"]
    },
    {
        "headword": "rafting",
        "pronunciation": "/ˈræftɪŋ/",
        "partOfSpeech": "noun",
        "definition": "The sport or leisure activity of traveling down a river on an inflatable raft.",
        "example": "White-water rafting through the canyon rapids was exhilarating.",
        "translation": "التجديف بالقوارب المطاطية في الأنهار",
        "exampleArabic": "كان التجديف بالقوارب المطاطية عبر منحدرات الوادي مبهجاً ومثيراً.",
        "relatedForms": ["raft"],
        "collocations": ["white-water rafting", "river rafting", "go rafting"],
        "synonyms": [],
        "antonyms": [],
        "tags": ["sports", "water"]
    },
    {
        "headword": "cruise",
        "pronunciation": "/kruːz/",
        "partOfSpeech": "noun",
        "definition": "A voyage on a ship or boat taken for pleasure, typically calling in at several places.",
        "example": "They booked a luxury Mediterranean cruise for their twentieth wedding anniversary.",
        "translation": "رحلة بحرية سياحية (كروز)",
        "exampleArabic": "حجزوا رحلة بحرية فاخرة في البحر الأبيض المتوسط بمناسبة الذكرى العشرين لزواجهما.",
        "relatedForms": ["cruises", "cruising"],
        "collocations": ["luxury cruise", "caribbean cruise", "take a cruise"],
        "synonyms": ["sea voyage", "boat trip"],
        "antonyms": [],
        "tags": ["travel", "holiday"]
    },
    {
        "headword": "sail",
        "pronunciation": "/seɪl/",
        "partOfSpeech": "verb",
        "definition": "To travel in a boat or ship, especially using sails.",
        "example": "We plan to sail around the Greek islands during early autumn.",
        "translation": "يبحر",
        "exampleArabic": "نخطط للإبحار حول الجزر اليونانية في أوائل الخريف.",
        "relatedForms": ["sailed", "sailing", "sailor"],
        "collocations": ["sail across the ocean", "sail smoothly", "set sail"],
        "synonyms": ["navigate", "voyage", "boat"],
        "antonyms": [],
        "tags": ["travel", "water"]
    },
    {
        "headword": "navigate",
        "pronunciation": "/ˈnævɪɡeɪt/",
        "partOfSpeech": "verb",
        "definition": "To plan and direct the route or course of a ship, aircraft, or other form of transport.",
        "example": "Ancient mariners learned to navigate uncharted waters using the stars.",
        "translation": "يبحر موجهّاً / يوجّه الدفة / يتنقل",
        "exampleArabic": "تعلم البحارة القدامى توجيه دفتهم والملاحة في المياه المجهولة باستخدام النجوم.",
        "relatedForms": ["navigated", "navigating", "navigation"],
        "collocations": ["navigate through rough waters", "navigate the streets"],
        "synonyms": ["steer", "guide", "maneuver"],
        "antonyms": [],
        "tags": ["travel", "action"]
    },
    {
        "headword": "witness firsthand",
        "pronunciation": "/ˈwɪtnəs fɜːrstˈhænd/",
        "partOfSpeech": "verb",
        "definition": "To see or experience something personally with one's own eyes.",
        "example": "To witness firsthand the migration of wildebeest in the Serengeti is awe-inspiring.",
        "translation": "يشهد بنفسه مباشرة / يعاين بالعين المجردة",
        "exampleArabic": "إن مشاهدة هجرة الحيوانات البرية في سيرينغيتي بأم العين أمر يبعث على الرهبة.",
        "relatedForms": ["witnessed firsthand"],
        "collocations": ["witness firsthand the wonder", "privilege to witness firsthand"],
        "synonyms": ["observe personally", "see in person"],
        "antonyms": [],
        "tags": ["experience", "travel"]
    },
    {
        "headword": "conquer",
        "pronunciation": "/ˈkɑːŋkər/",
        "partOfSpeech": "verb",
        "definition": "To overcome and take control of a place, or successfully climb a challenging mountain summit.",
        "example": "Experienced mountaineers aspire to conquer challenging alpine peaks.",
        "translation": "يغزو / يقهر (قمة جبلية)",
        "exampleArabic": "يطمح متسلقو الجبال ذوو الخبرة إلى قهر القمم الألبية الصعبة.",
        "relatedForms": ["conquered", "conquering", "conqueror"],
        "collocations": ["conquer the summit", "conquer fears", "conquer heights"],
        "synonyms": ["overcome", "triumph over", "scale"],
        "antonyms": ["surrender", "fail"],
        "tags": ["adventure", "achievement"]
    },
    {
        "headword": "climb",
        "pronunciation": "/klaɪm/",
        "partOfSpeech": "verb",
        "definition": "To go or come up a slope, incline, or stairs, especially using feet and hands.",
        "example": "Have you ever dared to climb an active volcano?",
        "translation": "يتسلق",
        "exampleArabic": "هل تجرأت يوماً على تسلق بركان نشط؟",
        "relatedForms": ["climbed", "climbing", "climber"],
        "collocations": ["climb a mountain", "climb steep cliffs", "climb rocks"],
        "synonyms": ["scale", "ascend", "scramble up"],
        "antonyms": ["descend"],
        "tags": ["action", "sports"]
    },
    {
        "headword": "roam",
        "pronunciation": "/roʊm/",
        "partOfSpeech": "verb",
        "definition": "To move about or travel aimlessly or unsystematically, especially over a wide area.",
        "example": "We loved to roam the cobbled alleys of the old Mediterranean quarter.",
        "translation": "يتجول / يجوب بحرية",
        "exampleArabic": "أحببنا التجول في الأزقة المرصوفة بالحصى في الحي المتوسطي القديم.",
        "relatedForms": ["roamed", "roaming"],
        "collocations": ["roam freely", "roam the streets", "roam around"],
        "synonyms": ["wander", "stroll", "ramble"],
        "antonyms": [],
        "tags": ["action", "travel"]
    },
    {
        "headword": "ever",
        "pronunciation": "/ˈevər/",
        "partOfSpeech": "adverb",
        "definition": "At any time (used in questions, negative statements, and with superlatives).",
        "example": "Have you ever traveled to another continent alone?",
        "translation": "في أي وقت مضى / قط / أبداً",
        "exampleArabic": "هل سافرت قط إلى قارة أخرى بمفردك؟",
        "relatedForms": [],
        "collocations": ["hardly ever", "if you ever", "best trip ever"],
        "synonyms": ["at any point"],
        "antonyms": ["never"],
        "tags": ["grammar", "time"]
    },
    {
        "headword": "never before",
        "pronunciation": "/ˈnevər bɪˈfɔːr/",
        "partOfSpeech": "adverb",
        "definition": "Not at any time prior to the present moment.",
        "example": "Never before have I witnessed such magnificent natural wonders.",
        "translation": "لم يحدث من قبل أبداً",
        "exampleArabic": "لم أشهد من قبل أبداً مثل هذه العجائب الطبيعية الرائعة.",
        "relatedForms": [],
        "collocations": ["seen never before", "experienced never before"],
        "synonyms": ["not once previously"],
        "antonyms": ["frequently"],
        "tags": ["grammar", "time"]
    },
    {
        "headword": "once in a lifetime",
        "pronunciation": "/wʌns ɪn ə ˈlaɪftaɪm/",
        "partOfSpeech": "adjective",
        "definition": "Exceptionally special or rare, unlikely to be repeated.",
        "example": "Witnessing the total solar eclipse was a once in a lifetime opportunity.",
        "translation": "فرصة لا تتكرر في العمر / تحدث مرة بالعمر",
        "exampleArabic": "كانت مشاهدة الكسوف الكلي للشمس فرصة تحدث مرة واحدة في العمر.",
        "relatedForms": [],
        "collocations": ["once in a lifetime experience", "once in a lifetime chance"],
        "synonyms": ["unrepeatable", "unique"],
        "antonyms": ["commonplace"],
        "tags": ["description", "lifestyle"]
    },
    {
        "headword": "so far",
        "pronunciation": "/soʊ fɑːr/",
        "partOfSpeech": "adverb",
        "definition": "Until now; up to the present time.",
        "example": "I have visited sixteen countries so far on my gap year journey.",
        "translation": "حتى الآن",
        "exampleArabic": "لقد زرت ست عشرة دولة حتى الآن في رحلة سنة فراغي.",
        "relatedForms": [],
        "collocations": ["so far so good", "best so far"],
        "synonyms": ["up to now", "to date"],
        "antonyms": [],
        "tags": ["grammar", "time"]
    },
    {
        "headword": "up to now",
        "pronunciation": "/ʌp tə naʊ/",
        "partOfSpeech": "adverb",
        "definition": "Until the present time.",
        "example": "Up to now, our tour group has completed four challenging hikes.",
        "translation": "حتى هذه اللحظة / حتى الآن",
        "exampleArabic": "حتى هذه اللحظة، أكملت مجموعتنا السياحية أربع مسارات مشي مليئة بالتحدي.",
        "relatedForms": [],
        "collocations": ["up to now everything went well"],
        "synonyms": ["so far", "hitherto"],
        "antonyms": [],
        "tags": ["grammar", "time"]
    },
    {
        "headword": "in my life",
        "pronunciation": "/ɪn maɪ laɪf/",
        "partOfSpeech": "prepositional phrase",
        "definition": "Throughout the course of one's entire existence.",
        "example": "I have never seen a sunset that magnificent in my life.",
        "translation": "في حياتي كلها",
        "exampleArabic": "لم أرَ غروباً للشمس بتلك الروعة في حياتي كلها.",
        "relatedForms": [],
        "collocations": ["never in my life", "first time in my life"],
        "synonyms": ["in all my days"],
        "antonyms": [],
        "tags": ["grammar", "expression"]
    },
    {
        "headword": "have you ever",
        "pronunciation": "/hæv juː ˈevər/",
        "partOfSpeech": "phrase",
        "definition": "A question prompt used to ask about life experiences at any indefinite past time.",
        "example": "Have you ever traveled overnight on a sleeper train across Europe?",
        "translation": "هل سبق لك قط أن...؟",
        "exampleArabic": "هل سبق لك قط أن سافرت طوال الليل في قطار مجهز للنوم عبر أوروبا؟",
        "relatedForms": [],
        "collocations": ["have you ever seen", "have you ever been", "have you ever tried"],
        "synonyms": [],
        "antonyms": [],
        "tags": ["grammar", "questions"]
    },
    {
        "headword": "I have never",
        "pronunciation": "/aɪ hæv ˈnevər/",
        "partOfSpeech": "phrase",
        "definition": "A statement used to indicate that something has not occurred at any time in one's life.",
        "example": "I have never tasted genuine authentic paella outside Valencia.",
        "translation": "أنا لم يسبق لي قط أن...",
        "exampleArabic": "أنا لم يسبق لي قط أن تذوقت الباييلا الأصلية خارج فالنسيا.",
        "relatedForms": ["I've never"],
        "collocations": ["I have never visited", "I have never heard"],
        "synonyms": [],
        "antonyms": ["I have always"],
        "tags": ["grammar", "expression"]
    },
    {
        "headword": "visited",
        "pronunciation": "/ˈvɪzɪtɪd/",
        "partOfSpeech": "verb",
        "definition": "Past participle/past tense of visit: went to see and spend time in a place.",
        "example": "She has visited the ancient pyramids outside Cairo twice.",
        "translation": "زارَ / زرتُ",
        "exampleArabic": "لقد زارت الأهرامات القديمة خارج القاهرة مرتين.",
        "relatedForms": ["visit", "visiting"],
        "collocations": ["frequently visited", "never visited", "have visited"],
        "synonyms": ["toured", "frequented"],
        "antonyms": [],
        "tags": ["action", "travel"]
    },
    {
        "headword": "explored",
        "pronunciation": "/ɪkˈsplɔːrd/",
        "partOfSpeech": "verb",
        "definition": "Past participle/past tense of explore: traveled through an unfamiliar area to learn about it.",
        "example": "We have explored several remote mountain caves together.",
        "translation": "استكشفَ / استكشفتُ",
        "exampleArabic": "لقد استكشفنا عدة كهوف جبلية نائية معاً.",
        "relatedForms": ["explore", "exploring", "explorer"],
        "collocations": ["fully explored", "explored uncharted paths"],
        "synonyms": ["investigated", "traversed"],
        "antonyms": [],
        "tags": ["action", "travel"]
    }
]

grammar_day29 = [
    {
        "title": "Present Perfect (Have you ever...?)",
        "explanation": "We use the Present Perfect tense with 'ever' to ask questions about experiences at an unspecified time in a person's life. We answer with 'Yes, I have' or 'No, I haven't' / 'I have never + V3'. If we mention a specific time in the past (such as last year, yesterday, or in 2021), we must switch to the Past Simple.",
        "explanationArabic": "نستخدم زمن المضارع التام مع 'ever' للسؤال عن تجارب حدثت في وقت غير محدد في حياة الشخص حتى الآن. ونجيب بـ 'Yes, I have' أو 'No, I haven't' أو 'I have never + التصريف الثالث'. إذا ذكرنا وقتاً محدداً في الماضي (مثل last year أو yesterday أو in 2021)، يجب أن ننتقل إلى زمن الماضي البسيط (Past Simple).",
        "rules": [
            "Structure for questions: Have / Has + subject + ever + past participle (V3)?",
            "Structure for negative experiences: Subject + have/has + never + past participle (V3).",
            "Use 'ever' in questions to mean 'at any time in your life'.",
            "Do NOT use specific past time words (e.g. yesterday, last week) with Present Perfect for life experiences."
        ],
        "rulesArabic": [
            "صيغة السؤال: Have / Has + الفاعل + ever + التصريف الثالث للفعل (V3)؟",
            "صيغة النفي للتجارب الحياتية: الفاعل + have/has + never + التصريف الثالث للفعل.",
            "تُستخدم 'ever' في الأسئلة بمعنى 'في أي وقت مضى في حياتك'.",
            "لا تستخدم كلمات تدل على وقت ماضٍ محدد (مثل yesterday, last year) مع المضارع التام للتجارب الحياتية."
        ],
        "structures": [
            {
                "pattern": "Have you ever + past participle (V3)...?",
                "explanation": "Asks whether someone has experienced something at any time in their life.",
                "explanationArabic": "يسأل عما إذا كان الشخص قد عاش أو جرب شيئاً في أي وقت مضى من حياته."
            },
            {
                "pattern": "I have never + past participle (V3)...",
                "explanation": "States that the speaker has not had that experience in their life.",
                "explanationArabic": "يقر بأن المتحدث لم يعش تلك التجربة مطلقاً في حياته."
            },
            {
                "pattern": "Subject + have/has + visited / explored + noun",
                "explanation": "States life travel achievements up to the present moment.",
                "explanationArabic": "يوضح الإنجازات والوجهات التي تمت زيارتها واستكشافها حتى اللحظة الحالية."
            }
        ],
        "examples": [
            {
                "sentence": "Have you ever visited an ancient temple during a vacation?",
                "translation": "هل سبق لك قط أن زرت معبداً قديماً أثناء إجازة؟",
                "usesVocabulary": ["have you ever", "visited", "temple"]
            },
            {
                "sentence": "I have never explored the inside of an ancient pyramid.",
                "translation": "لم يسبق لي قط أن استكشفت داخل هرم قديم.",
                "usesVocabulary": ["I have never", "explored", "pyramid"]
            },
            {
                "sentence": "She has visited sixteen countries in her lifetime so far.",
                "translation": "لقد زارت ست عشرة دولة في حياتها حتى الآن.",
                "usesVocabulary": ["visited", "lifetime", "so far"]
            },
            {
                "sentence": "Never before have they enjoyed such breathtaking scenery while paragliding.",
                "translation": "لم يستمتعوا من قبل بمثل هذه المشاهد التي تخطف الأنفاس أثناء الطيران الشراعي بالمظلة.",
                "usesVocabulary": ["never before", "breathtaking", "paragliding"]
            }
        ],
        "commonMistakes": [
            {
                "wrong": "Did you ever visited that historic site?",
                "right": "Have you ever visited that historic site?",
                "note": "Use 'Have you ever' with the past participle, or 'Did you ever visit' with the base verb.",
                "noteArabic": "استخدم 'Have you ever' مع التصريف الثالث للفعل، أو 'Did you ever visit' مع مصدر الفعل."
            },
            {
                "wrong": "I have visited that cathedral yesterday.",
                "right": "I visited that cathedral yesterday. / I have visited that cathedral.",
                "note": "Do not combine a specific past time ('yesterday') with the Present Perfect tense.",
                "noteArabic": "لا تجمع بين تحديد زمن ماضٍ محدد ('yesterday') وزمن المضارع التام."
            }
        ]
    }
]

convs_day29 = [
    {
        "title": "Sharing Bucket List Adventures",
        "titleArabic": "مشاركة مغامرات قائمة الأمنيات",
        "setting": "Two backpackers at a hostel lounge comparing life experiences",
        "settingArabic": "رحالان في صالة نزل شباب يقارنان تجاربهما الحياتية",
        "vocabularyUsed": ["bucket list", "have you ever", "skydiving", "bungee jumping", "scuba diving", "unforgettable", "milestone"],
        "lines": [
            {"speaker": "Tariq", "text": "Have you ever tried any thrilling outdoor extreme sports during your travels?", "translation": "هل سبق لك قط أن جربت أي رياضات جريئة ومثيرة أثناء رحلاتك؟"},
            {"speaker": "Elena", "text": "Yes! Skydiving over the Swiss Alps was on my bucket list for five full years.", "translation": "نعم! كان القفز المظلي فوق جبال الألب السويسرية على قائمة أمنياتي لمدة خمس سنوات كاملة."},
            {"speaker": "Tariq", "text": "That is astonishing! Were you terrified before leaping from the aircraft door?", "translation": "هذا مذهل! هل كنت مرعوبة قبل القفز من باب الطائرة؟"},
            {"speaker": "Elena", "text": "Completely terrified, but soaring through clear blue sky was an unforgettable milestone.", "translation": "مرعوبة تماماً، لكن التحليق عبر السماء الزرقاء الصافية كان محطة فارقة لا تُنسى."},
            {"speaker": "Tariq", "text": "Have you ever dared to attempt bungee jumping off a high suspension bridge?", "translation": "هل تجرأتِ يوماً على محاولة القفز بالحبال المطاطية من فوق جسر معلق مرتفع؟"},
            {"speaker": "Elena", "text": "No, I have never tried bungee jumping, though I have done deep scuba diving.", "translation": "لا، لم يسبق لي قط تجربة القفز بالحبال، مع أنني قمت بالغوص العميق بأسطوانات التنفس."},
            {"speaker": "Tariq", "text": "Scuba diving among vibrant coral gardens must feel like visiting another planet.", "translation": "الغطس وسط حدائق الشعاب المرجانية النابضة بالحياة لا بد أنه يشبه زيارة كوكب آخر."},
            {"speaker": "Elena", "text": "It truly does. Every dive reveals colorful marine creatures you could never imagine.", "translation": "هو كذلك حقاً. تكشف كل غطسة عن كائنات بحرية ملونة لم يكن بإمكانك تخيلها أبداً."}
        ]
    },
    {
        "title": "Historical Landmarks and Wonders",
        "titleArabic": "المعالم والآثار التاريخية",
        "setting": "Friends discussing ancient architecture over coffee",
        "settingArabic": "أصدقاء يناقشون العمارة القديمة أثناء تناول القهوة",
        "vocabularyUsed": ["monument", "historic site", "ruins", "ancient", "temple", "pyramid", "castle", "palace"],
        "lines": [
            {"speaker": "Nadia", "text": "Have you ever walked through an ancient archaeological site that left you speechless?", "translation": "هل سبق لك قط أن مشيت في موقع أثري عريق جعلك عاجزاً عن الكلام؟"},
            {"speaker": "Karim", "text": "Yes, exploring the ruins of Petra in Jordan was an absolute revelation.", "translation": "نعم، كان استكشاف أطلال البتراء في الأردن اكتشافاً مبهراً بحق."},
            {"speaker": "Nadia", "text": "Carving an entire historic site and royal temple into rose-colored sandstone is genius.", "translation": "إن نحت موقع تاريخي كامل ومعبد ملكي داخل الحجر الرملي الوردي هو قمة العبقرية."},
            {"speaker": "Karim", "text": "Have you ever stood in front of the Great Pyramid in Giza?", "translation": "هل سبق لك أن وقفت أمام الهرم الأكبر في الجيزة؟"},
            {"speaker": "Nadia", "text": "Yes, I have. Standing before that ancient monument makes you feel wonderfully humble.", "translation": "نعم، لقد فعلت. فالوقوف أمام ذلك النصب الأثري العريق يجعلك تشعر بتواضع رائع."},
            {"speaker": "Karim", "text": "I also hope to visit a medieval fortress castle and a European royal palace someday.", "translation": "آمل أيضاً أن أزور قلعة حصينة من القرون الوسطى وقصراً ملكياً أوروبياً في يوم من الأيام."},
            {"speaker": "Nadia", "text": "You must visit Versailles; the golden hall of mirrors inside the palace is breathtaking.", "translation": "يجب عليك زيارة فرساي؛ فقاعة المرايا الذهبية داخل القصر تخطف الأنفاس."},
            {"speaker": "Karim", "text": "Adding both destinations to my travel notebook right away!", "translation": "سأضيف كلتا الوجهتين إلى دفتر رحلاتي على الفور!"}
        ]
    },
    {
        "title": "Adventures on Water and in Nature",
        "titleArabic": "مغامرات على الماء وفي الطبيعة",
        "setting": "Tourists sharing stories after returning from an expedition",
        "settingArabic": "سياح يتبادلون القصص بعد عودتهم من رحلة استكشافية",
        "vocabularyUsed": ["safari", "rafting", "cruise", "sail", "navigate", "witness firsthand", "snorkeling", "conquer"],
        "lines": [
            {"speaker": "Marcus", "text": "Have you ever gone on an open-savannah safari to watch lions in the wild?", "translation": "هل ذهبت يوماً في رحلة سفاري بالسافانا المفتوحة لمراقبة الأسود في البرية؟"},
            {"speaker": "Sophia", "text": "Yes, I did that last summer. To witness firsthand a pride resting under acacia trees was breathtaking.", "translation": "نعم، فعلت ذلك الصيف الماضي. وكانت مشاهدة عائلة أسود تستريح تحت أشجار الأكاسيا بأم العين أمراً يخطف الأنفاس."},
            {"speaker": "Marcus", "text": "Have you ever tried white-water rafting down a turbulent mountain river?", "translation": "هل سبق لك تجربة التجديف في المياه البيضاء بالقوارب المطاطية في نهر جبلي هائج؟"},
            {"speaker": "Sophia", "text": "I have! Our raft guide helped us navigate dangerous rapids and conquer ferocious currents.", "translation": "لقد فعلت! ساعدنا مرشد القارب في توجيه دفتنا عبر المنحدرات الخطرة وقهر التيارات الشرسة."},
            {"speaker": "Marcus", "text": "Next month, my family plans to embark on a Mediterranean island cruise.", "translation": "في الشهر المقبل، تخطط عائلتي للانطلاق في رحلة بحرية سياحية (كروز) بين جزر البحر الأبيض المتوسط."},
            {"speaker": "Sophia", "text": "Are you going to sail across the Aegean Sea or stay closer to the Italian coast?", "translation": "هل ستبحرون عبر بحر إيجه أم ستبقون بالقرب من الساحل الإيطالي؟"},
            {"speaker": "Marcus", "text": "We will sail near Greece and spend several sunny mornings snorkeling in crystal bays.", "translation": "سنبحر بالقرب من اليونان ونمضي عدة فترات صباحية مشمسة في الغطس السطحي في الخلجان النقية."},
            {"speaker": "Sophia", "text": "That sounds like an idyllic escapade filled with tranquility and marine wonder.", "translation": "هذا يبدو وكأنه مغامرة هانئة مليئة بالهدوء والروعة البحرية."}
        ]
    }
]

paras_day29 = [
    {
        "title": "The Wonder of Exploration",
        "titleArabic": "روعة الاستكشاف",
        "kind": "reflective",
        "vocabularyUsed": ["escapade", "memorable", "expedition", "fascinating", "marvel", "roam", "once in a lifetime", "in my life"],
        "text": "Every travel expedition teaches us profound lessons about humanity and nature. When travelers roam through foreign cities, they discover fascinating traditions that differ completely from their hometowns. Whether undertaking a challenging jungle escapade or admiring the sunset over quiet valleys, such moments become memorable treasures. People frequently marvel at how small encounters create lasting friendships across continents. Gaining genuine cultural appreciation is truly a once in a lifetime privilege that enriches our character and stays with us in my life forever.",
        "translation": "تعلمنا كل بعثة سفر استكشافية دروساً عميقة عن الإنسانية والطبيعة. فعندما يجوب المسافرون المدن الأجنبية، يكتشفون تقاليد آسرة تختلف تماماً عن بلداتهم الأصلية. وسواء أكان المرء يخوض مغامرة جريئة في الأدغال أم يتأمل غروب الشمس فوق الوديان الهادئة، فإن هذه اللحظات تصبح كنوزاً لا تُنسى. وكثيراً ما ينبهر الناس بكيفية نشوء صداقات دائمة عبر القارات من مجرد لقاءات بسيطة. إن اكتساب تقدير ثقافي أصيل هو حقاً ميزة فريدة في العمر تثري شخصيتنا وتبقى معنا طوال حياتنا."
    },
    {
        "title": "Treasures of Human Heritage",
        "titleArabic": "كنوز التراث البشري",
        "kind": "informative",
        "vocabularyUsed": ["cathedral", "shrine", "spectacular", "stunning", "astonishing", "marvelous", "bizarre", "exotic"],
        "text": "Human civilization has erected marvels that withstand centuries of change. In medieval Europe, stone builders constructed soaring cathedral vaults whose stained glass displays spectacular patterns of light. On mist-covered peaks in Asia, pilgrims ascend to a secluded sacred shrine to meditate in quiet reverence. Such locations present an astonishing contrast between historic craftsmanship and modern life. Travelers often marvel at bizarre cultural artifacts alongside exotic flora preserved inside surrounding botanical courtyards, creating a stunning atmosphere of enduring beauty.",
        "translation": "شيدت الحضارة البشرية عجائب تصمد في وجه قرون من التغير. ففي أوروبا في العصور الوسطى، بنى البناؤون الحجريون قباب كاتدرائيات شاهقة تعرض نوافذها الزجاجية الملونة أنماطاً ضوئية خلابة. وعلى القمم التي يكسوها الضباب في آسيا، يصعد الحجاج إلى ضريح مقدس منعزل للتأمل في خشوع هادئ. وتقدم مثل هذه المواقع تبايناً مدهشاً بين الحرفية التاريخية والحياة المعاصرة. وغالباً ما ينبهر المسافرون بالقطع الأثرية الثقافية الغريبة والمثيرة إلى جانب النباتات الاستوائية النادرة المحفوظة داخل الأفنية النباتية المحيطة، مما يخلق أجواءً فاتنة من الجمال الخالد."
    },
    {
        "title": "Reaching Beyond One's Limits",
        "titleArabic": "تجاوز الحدود الشخصية",
        "kind": "narrative",
        "vocabularyUsed": ["climb", "ever", "never before", "up to now", "so far", "I have never", "visited", "explored"],
        "text": "Before turning thirty, Sarah made a promise to challenge her physical and mental comfort boundaries. Up to now, she had lived a quiet urban life, having visited only nearby seaside resorts. Have you ever felt the urge to climb a steep mountain summit? Last spring, Sarah joined a hiking team that explored rugged trails in the Andes. Never before had she experienced such thin air and biting cold, yet she persisted every single day. Looking back so far, she realized that courage expands whenever we venture into the unknown.",
        "translation": "قبل بلوغها سن الثلاثين، قطعت سارة عهداً على نفسها بتحدي حدود راحتها الجسدية والنفسية. وحتى هذه اللحظة، كانت قد عاشت حياة حضرية هادئة، ولم تكن قد زارت سوى منتجعات شاطئية مجاورة. هل شعرت يوماً بالرغبة الملحة في تسلق قمة جبل شاهق؟ في الربيع الماضي، انضمت سارة إلى فريق مسير استكشف دروباً وعرة في جبال الأنديز. لم يسبق لها من قبل أن واجهت هواءً خفيفاً وبرداً قارساً كهذا، ومع ذلك فقد ثابرت في كل يوم بمفرده. وبالنظر إلى الوراء حتى الآن، أدركت أن الشجاعة تتسع كلما غامرنا بالدخول إلى المجهول."
    }
]
