# -*- coding: utf-8 -*-
"""Generator for Day 59: Goals and Motivation (Ambition and self-improvement)."""

import json, os, sys
from scripts.curriculum_engine import write_day

vocab_59 = [
    # Vision, Objectives & Plans (10)
    {"headword": "aspiration", "pronunciation": "/ˌæspəˈreɪʃn/", "partOfSpeech": "noun", "definition": "A hope or ambition of achieving something.", "example": "If you maintain your core aspiration, you will navigate every difficult semester.", "translation": "طموح / تطلع مستقبلي", "exampleArabic": "إذا حافظت على طموحك الأساسي، فستجتاز كل فصل دراسي صعب.", "collocations": ["lofty aspiration", "career aspiration"], "synonyms": ["ambition", "dream"], "antonyms": [], "tags": ["motivation", "goals"]},
    {"headword": "ambition level", "pronunciation": "/æmˈbɪʃn ˌlevl/", "partOfSpeech": "noun", "definition": "The degree or extent of one's determination to achieve success.", "example": "When your ambition level is high, minor setbacks will not deter your focus.", "translation": "مستوى الطموح والعزيمة", "exampleArabic": "حين يكون مستوى طموحك مرتفعاً، فلن تعيق الانتكاسات البسيطة تركيزك.", "collocations": ["elevate ambition level", "match ambition level"], "synonyms": ["drive"], "antonyms": [], "tags": ["motivation", "goals"]},
    {"headword": "long-range vision", "pronunciation": "/ˌlɒŋ reɪndʒ ˈvɪʒn/", "partOfSpeech": "noun", "definition": "A clear, overarching concept of what one intends to accomplish over years.", "example": "As soon as you articulate a long-range vision, daily distractions will lose their power.", "translation": "رؤية بعيدة المدى", "exampleArabic": "بمجرد أن تصيغ رؤية بعيدة المدى، ستفقد المشتتات اليومية تأثيرها.", "collocations": ["articulate a long-range vision", "strategic long-range vision"], "synonyms": ["future vision"], "antonyms": ["short-sightedness"], "tags": ["goals", "strategy"]},
    {"headword": "core objective", "pronunciation": "/kɔːr əbˈdʒektɪv/", "partOfSpeech": "noun", "definition": "The central goal or primary intended result of an endeavor.", "example": "If we align our resources with our core objective, productivity will surge.", "translation": "هدف جوهري / غاية أساسية", "exampleArabic": "إذا وجهنا مواردنا نحو هدفنا الجوهري، فسترتفع الإنتاجية بشكل ملحوظ.", "collocations": ["primary core objective", "achieve a core objective"], "synonyms": ["main goal"], "antonyms": [], "tags": ["goals", "strategy"]},
    {"headword": "strategic target", "pronunciation": "/strəˈtiːdʒɪk ˈtɑːɡɪt/", "partOfSpeech": "noun", "definition": "A measurable aim planned to advance a broader long-term strategy.", "example": "When the team meets this strategic target, regional expansion will commence immediately.", "translation": "هدف استراتيجي محدد", "exampleArabic": "حين يحقق الفريق هذا الهدف الاستراتيجي، سيبدأ التوسع الإقليمي على الفور.", "collocations": ["hit a strategic target", "set strategic targets"], "synonyms": ["milestone target"], "antonyms": [], "tags": ["goals", "strategy"]},
    {"headword": "roadmap", "pronunciation": "/ˈrəʊdmæp/", "partOfSpeech": "noun", "definition": "A detailed plan or guide to direct progress toward a goal.", "example": "As soon as you design a realistic roadmap, the path to mastery will become clear.", "translation": "خريطة طريق / خطة عمل مرحلية", "exampleArabic": "بمجرد أن تصمم خريطة طريق واقعية، سيتضح مسار الوصول إلى الإتقان.", "collocations": ["strategic roadmap", "development roadmap"], "synonyms": ["blueprint", "action guide"], "antonyms": [], "tags": ["strategy", "planning"]},
    {"headword": "action plan", "pronunciation": "/ˈækʃn plæn/", "partOfSpeech": "noun", "definition": "A proposed strategy or course of intended actions.", "example": "If you draft a detailed action plan tonight, you will execute tasks with confidence tomorrow.", "translation": "خطة عمل تنفيذية", "exampleArabic": "إذا أعددت خطة عمل تنفيذية الليلة، فستنفذ المهام بثقة غداً.", "collocations": ["detailed action plan", "execute an action plan"], "synonyms": ["execution plan"], "antonyms": [], "tags": ["planning", "productivity"]},
    {"headword": "benchmark goal", "pronunciation": "/ˈbentʃmɑːk ɡəʊl/", "partOfSpeech": "noun", "definition": "A standard or point of reference against which things may be compared.", "example": "When you surpass each benchmark goal, your professional credibility will expand.", "translation": "هدف قياسي معياري للمقارنة", "exampleArabic": "حين تتجاوز كل هدف قياسي، ستتعزز مصداقيتك المهنية.", "collocations": ["establish a benchmark goal", "reach a benchmark goal"], "synonyms": ["reference standard"], "antonyms": [], "tags": ["goals", "progress"]},
    {"headword": "stepping stone", "pronunciation": "/ˈstepɪŋ stəʊn/", "partOfSpeech": "noun", "definition": "An action or event that helps someone make progress toward a goal.", "example": "If you view entry-level work as a stepping stone, you will maintain enthusiastic energy.", "translation": "خطوة تمهيدية / حجر ارتقاء نحو الأفضل", "exampleArabic": "إذا نظرت إلى الوظيفة المبتدئة كحجر ارتقاء، فستحافظ على طاقتك وحماسك.", "collocations": ["valuable stepping stone", "use as a stepping stone"], "synonyms": ["springboard"], "antonyms": [], "tags": ["career", "motivation"]},
    {"headword": "catalyst for change", "pronunciation": "/ˈkætəlɪst fə ˈtʃeɪndʒ/", "partOfSpeech": "noun", "definition": "A person or thing that precipitates an event or significant transition.", "example": "When personal dissatisfaction peaks, it will act as a potent catalyst for change.", "translation": "حافز ومحرك للتغيير الجذري", "exampleArabic": "حين يصل الاستياء الشخصي إلى ذروته، سيعمل كحافز قوي للتغيير.", "collocations": ["serve as a catalyst for change", "powerful catalyst for change"], "synonyms": ["spark"], "antonyms": [], "tags": ["transformation", "motivation"]},

    # Internal Drive & Persistence (10)
    {"headword": "internal motivation", "pronunciation": "/ɪnˈtɜːnl ˌməʊtɪˈveɪʃn/", "partOfSpeech": "noun", "definition": "Motivation that comes from the pleasure or satisfaction derived from the task itself.", "example": "If you tap into deep internal motivation, external praise will matter far less.", "translation": "دافع ذاتي داخلي", "exampleArabic": "إذا استندت إلى دافع ذاتي داخلي عميق، فسيقل اهتمامك بالثناء الخارجي.", "collocations": ["harness internal motivation", "foster internal motivation"], "synonyms": ["intrinsic drive"], "antonyms": ["external pressure"], "tags": ["psychology", "motivation"]},
    {"headword": "external incentive", "pronunciation": "/ɪkˈstɜːnl ɪnˈsentɪv/", "partOfSpeech": "noun", "definition": "A reward or stimulus offered from the outside to encourage behavior.", "example": "While a bonus is an attractive external incentive, genuine passion sustains effort longer.", "translation": "حافز ومكافأة خارجية", "exampleArabic": "بينما تعتبر المكافأة حافزاً خارجياً جذاباً، فإن الشغف الحقيقي يديم الجهد لفترة أطول.", "collocations": ["financial external incentive", "provide an external incentive"], "synonyms": ["extrinsic reward"], "antonyms": ["internal motivation"], "tags": ["motivation", "psychology"]},
    {"headword": "drive to succeed", "pronunciation": "/ˈdraɪv tə səkˈsiːd/", "partOfSpeech": "noun", "definition": "An intense, persistent inner compulsion to accomplish significant goals.", "example": "When an ambitious youth possesses a fierce drive to succeed, obstacles will crumble.", "translation": "الدافع القوي للنجاح والظفر", "exampleArabic": "حين يمتلك الشاب الطموح دافعاً قوياً للنجاح، ستتلاشى العقبات أمامه.", "collocations": ["innate drive to succeed", "relentless drive to succeed"], "synonyms": ["ambition"], "antonyms": ["apathy"], "tags": ["motivation", "character"]},
    {"headword": "perseverance", "pronunciation": "/ˌpɜːsɪˈvɪərəns/", "partOfSpeech": "noun", "definition": "Persistence in doing something despite difficulty or delay in achieving success.", "example": "If you cultivate quiet perseverance, you will eventually conquer every steep mountain.", "translation": "مثابرة ودأب مستمر", "exampleArabic": "إذا نميت المثابرة الهادئة، فستقهر في نهاية المطاف كل جبل وعر.", "collocations": ["patient perseverance", "demonstrate perseverance"], "synonyms": ["persistence", "tenacity"], "antonyms": ["surrender"], "tags": ["character", "success"]},
    {"headword": "resilience", "pronunciation": "/rɪˈzɪliəns/", "partOfSpeech": "noun", "definition": "The capacity to recover quickly from difficulties; toughness.", "example": "As soon as you develop emotional resilience, professional criticism will inspire growth.", "translation": "مرونة نفسية وقدرة على التعافي", "exampleArabic": "بمجرد أن تطور مرونة نفسية، ستكون الانتقادات المهنية مصدر إلهام للنمو.", "collocations": ["build resilience", "remarkable resilience"], "synonyms": ["buoyancy", "toughness"], "antonyms": ["fragility"], "tags": ["character", "psychology"]},
    {"headword": "grit", "pronunciation": "/ɡrɪt/", "partOfSpeech": "noun", "definition": "Courage and resolve; strength of character over long timeframes.", "example": "When raw talent is paired with unrelenting grit, legendary achievements will follow.", "translation": "عزيمة فولاذية وصلابة شخصية", "exampleArabic": "حين تقترن الموهبة الفطرية بعزيمة صلبة لا تلين، ستتبعها إنجازات أسطورية.", "collocations": ["true grit", "unshakable grit"], "synonyms": ["pluck", "mettle"], "antonyms": ["cowardice"], "tags": ["character", "success"]},
    {"headword": "determination", "pronunciation": "/dɪˌtɜːmɪˈneɪʃn/", "partOfSpeech": "noun", "definition": "Firmness of purpose; resoluteness.", "example": "If her fierce determination remains intact, she will graduate top of her class.", "translation": "إصرار وعقد العزم", "exampleArabic": "إذا ظل إصرارها القوي ثابتاً، فستتخرج الأولى على دفعتها.", "collocations": ["fierce determination", "dogged determination"], "synonyms": ["resolve"], "antonyms": ["indecision"], "tags": ["character", "motivation"]},
    {"headword": "unwavering focus", "pronunciation": "/ʌnˈweɪvərɪŋ ˈfəʊkəs/", "partOfSpeech": "noun", "definition": "Concentration that does not hesitate, weaken, or get distracted.", "example": "As soon as you apply unwavering focus to your thesis, you will finish months early.", "translation": "تركيز لا يتزعزع وثبات انتباه", "exampleArabic": "بمجرد أن تطبق تركيزاً لا يتزعزع على أطروحتك، ستنهيها قبل أشهر من موعدها.", "collocations": ["maintain unwavering focus", "with unwavering focus"], "synonyms": ["laser focus"], "antonyms": ["scattered attention"], "tags": ["productivity", "mindset"]},
    {"headword": "tenacity", "pronunciation": "/təˈnæsəti/", "partOfSpeech": "noun", "definition": "The quality or fact of being able to grip something firmly; determination.", "example": "If an entrepreneur possesses stubborn tenacity, temporary rejections will not matter.", "translation": "إصرار عنيد وتشبث بالهدف", "exampleArabic": "إذا امتلك رائد الأعمال إصراراً عنيداً، فلن تؤثر الرفوض المؤقتة على مساره.", "collocations": ["stubborn tenacity", "admirable tenacity"], "synonyms": ["doggedness"], "antonyms": ["wavering"], "tags": ["character", "success"]},
    {"headword": "industriousness", "pronunciation": "/ɪnˈdʌstriəsnəs/", "partOfSpeech": "noun", "definition": "The quality of working energetically and devotedly; hard-working diligence.", "example": "When natural talent is absent, steady industriousness will bridge the capability gap.", "translation": "كدّ واجتهاد دؤوب / دأب في العمل", "exampleArabic": "حين تغيب الموهبة الفطرية، سيسد الكد والاجتهاد الدؤوب فجوة القدرات.", "collocations": ["remarkable industriousness", "praise one's industriousness"], "synonyms": ["diligence", "assiduousness"], "antonyms": ["laziness"], "tags": ["workplace", "character"]},

    # Overcoming Resistance & Daily Discipline (10)
    {"headword": "procrastination", "pronunciation": "/prəˌkræstɪˈneɪʃn/", "partOfSpeech": "noun", "definition": "The action of delaying or postponing something.", "example": "If you conquer chronic procrastination today, future anxiety will evaporate.", "translation": "تسويف ومماطلة وتأجيل", "exampleArabic": "إذا قهرت التسويف المزمن اليوم، فسيتبخر قلق المستقبل.", "collocations": ["overcome procrastination", "fall into procrastination"], "synonyms": ["delay", "hesitation"], "antonyms": ["action", "punctuality"], "tags": ["habits", "productivity"]},
    {"headword": "overcome hurdle", "pronunciation": "/ˌəʊvəkʌm ˈhɜːdl/", "partOfSpeech": "verb", "definition": "To successfully deal with a problem or difficulty.", "example": "When you overcome this hurdle, you will discover inner reserves of strength.", "translation": "يتغلب على عقبة / يتخطى حاجزاً صعباً", "exampleArabic": "حين تتغلب على هذه العقبة، ستكتشف مخزوناً داخلياً هائلاً من القوة.", "verbForms": {"v1": "overcome hurdle", "v2": "overcame hurdle", "v3": "overcome hurdle"}, "collocations": ["overcome major hurdle", "help overcome hurdles"], "synonyms": ["surmount obstacle"], "antonyms": ["succumb to hurdle"], "tags": ["actions", "success"]},
    {"headword": "setback recovery", "pronunciation": "/ˈsetbæk rɪˈkʌvəri/", "partOfSpeech": "noun", "definition": "The process of regaining stability after a reversal or failure.", "example": "As soon as you master rapid setback recovery, fear of failure will vanish.", "translation": "النهوض بعد التعثر / التعافي من الانتكاسة", "exampleArabic": "بمجرد أن تتقن النهوض السريع بعد التعثر، سيتلاشى الخوف من الفشل.", "collocations": ["resilient setback recovery", "accelerate setback recovery"], "synonyms": ["bounce-back"], "antonyms": [], "tags": ["resilience", "psychology"]},
    {"headword": "stumbling block", "pronunciation": "/ˈstʌmblɪŋ blɒk/", "partOfSpeech": "noun", "definition": "A circumstance that causes difficulty or hesitation.", "example": "If you reframe a stumbling block as a learning lesson, you will never truly fail.", "translation": "عثرة / حجر عثرة في الطريق", "exampleArabic": "إذا أعدت صياغة حجر العثرة كدرس تعليمي، فلن تفشل حقاً أبداً.", "collocations": ["remove a stumbling block", "major stumbling block"], "synonyms": ["obstacle", "impediment"], "antonyms": ["stepping stone"], "tags": ["challenges", "mindset"]},
    {"headword": "leap forward", "pronunciation": "/liːp ˈfɔːwəd/", "partOfSpeech": "noun", "definition": "A dramatic and rapid advancement or improvement.", "example": "When our team launches the automated tool, efficiency will make a gigantic leap forward.", "translation": "قفزة نوعية للأمام / طفرة تقدم كبيرة", "exampleArabic": "حين يطلق فريقنا الأداة المؤتمتة، ستحقق الكفاءة قفزة نوعية هائلة للأمام.", "collocations": ["take a leap forward", "giant leap forward"], "synonyms": ["breakthrough"], "antonyms": ["regression"], "tags": ["progress", "achievement"]},
    {"headword": "break free", "pronunciation": "/breɪk ˈfriː/", "partOfSpeech": "verb", "definition": "To escape from confinement or an unhelpful mental habit.", "example": "As soon as you break free from limiting beliefs, your potential will unfold.", "translation": "يتحرر / ينطلق متخلصاً من القيود", "exampleArabic": "بمجرد أن تتحرر من المعتقدات المقيدة، ستنطلق إمكاناتك الكاملة.", "verbForms": {"v1": "break free", "v2": "broke free", "v3": "broken free"}, "collocations": ["break free from limits", "break free completely"], "synonyms": ["emancipate oneself"], "antonyms": ["remain trapped"], "tags": ["mindset", "actions"]},
    {"headword": "reach potential", "pronunciation": "/riːtʃ pəˈtenʃl/", "partOfSpeech": "verb", "definition": "To achieve the highest degree of capability of which one is capable.", "example": "If you dedicate three hours daily to deliberate craft, you will reach your potential.", "translation": "يبلغ أقصى طاقاته وإمكاناته", "exampleArabic": "إذا كرست ثلاث ساعات يومياً لحرفتك بوعي، فستبلغ أقصى إمكاناتك وطاقاتك.", "verbForms": {"v1": "reach potential", "v2": "reached potential", "v3": "reached potential"}, "collocations": ["reach full potential", "help reach potential"], "synonyms": ["fulfill potential"], "antonyms": ["waste potential"], "tags": ["growth", "actions"]},
    {"headword": "strive for excellence", "pronunciation": "/straɪv fər ˈeksələns/", "partOfSpeech": "verb", "definition": "To make great efforts to achieve outstanding quality.", "example": "When craftsmen strive for excellence, their work endures across generations.", "translation": "يسعى للتميز والإتقان الرفيع", "exampleArabic": "حين يسعى الحرفيون للتميز والإتقان الرفيع، تدوم أعمالهم عبر الأجيال.", "verbForms": {"v1": "strive for excellence", "v2": "strove for excellence", "v3": "striven for excellence"}, "collocations": ["continually strive for excellence", "strive for excellence daily"], "synonyms": ["pursue perfection"], "antonyms": ["settle for mediocrity"], "tags": ["excellence", "actions"]},
    {"headword": "pursue relentlessly", "pronunciation": "/pəˈsjuː rɪˈlentləsli/", "partOfSpeech": "verb", "definition": "To follow or chase a goal with continuous, unyielding determination.", "example": "If you pursue your calling relentlessly, critics will eventually become admirers.", "translation": "يسعى وراء هدفه بلا هوادة ولا كلل", "exampleArabic": "إذا سعيت وراء رسالتك بلا هوادة ولا كلل، فسيتحول المنتقدون في النهاية إلى معجبين.", "verbForms": {"v1": "pursue relentlessly", "v2": "pursued relentlessly", "v3": "pursued relentlessly"}, "collocations": ["pursue relentlessly until done", "pursue goals relentlessly"], "synonyms": ["chase tirelessly"], "antonyms": ["give up"], "tags": ["actions", "motivation"]},
    {"headword": "stay disciplined", "pronunciation": "/steɪ ˈdɪsəplɪnd/", "partOfSpeech": "verb", "definition": "To maintain self-control and consistent adherence to rules or plans.", "example": "As soon as you commit to staying disciplined, morning routines will feel effortless.", "translation": "يحافظ على انضباطه الذاتي", "exampleArabic": "بمجرد أن تلتزم بالحفاظ على انضباطك، ستصبح العادات الصباحية سهلة المنال.", "verbForms": {"v1": "stay disciplined", "v2": "stayed disciplined", "v3": "stayed disciplined"}, "collocations": ["stay disciplined under stress", "struggle to stay disciplined"], "synonyms": ["remain focused"], "antonyms": ["slack off"], "tags": ["habits", "actions"]},

    # Accountability, Mindset & Empowerment (10)
    {"headword": "accountability partner", "pronunciation": "/əˌkaʊntəˈbɪləti ˈpɑːtnə/", "partOfSpeech": "noun", "definition": "A person who helps keep you committed to your goals through regular check-ins.", "example": "If you partner with an honest accountability partner, your completion rate will double.", "translation": "شريك الالتزام والمسؤولية المتبادلة", "exampleArabic": "إذا تعاونت مع شريك التزام صادق، فسيتضاعف معدل إنجازك للمهام.", "collocations": ["trusted accountability partner", "meet an accountability partner"], "synonyms": ["mentor peer"], "antonyms": [], "tags": ["accountability", "productivity"]},
    {"headword": "self-accountability", "pronunciation": "/ˌself əˌkaʊntəˈbɪləti/", "partOfSpeech": "noun", "definition": "The habit of taking personal responsibility for one's actions, choices, and progress.", "example": "When you embrace self-accountability, you will stop blaming external circumstances.", "translation": "محاسبة الذات والمسؤولية الشخصية", "exampleArabic": "حين تتبنى محاسبة الذات والمسؤولية، ستتوقف عن لوم الظروف الخارجية.", "collocations": ["practice self-accountability", "high self-accountability"], "synonyms": ["personal responsibility"], "antonyms": ["victim mentality"], "tags": ["character", "psychology"]},
    {"headword": "progress tracking", "pronunciation": "/ˈprəʊɡres ˌtrækɪŋ/", "partOfSpeech": "noun", "definition": "The continuous monitoring and recording of advancement toward targets.", "example": "As soon as you implement daily progress tracking, invisible growth will become tangible.", "translation": "تتبع التقدم ومراقبة الإنجاز", "exampleArabic": "بمجرد أن تطبق تتبع التقدم يومياً، سيصبح النمو غير المرئي ملموساً وواضحاً.", "collocations": ["rigorous progress tracking", "visual progress tracking"], "synonyms": ["monitoring advancement"], "antonyms": [], "tags": ["productivity", "tools"]},
    {"headword": "milestone tracker", "pronunciation": "/ˈmaɪlstəʊn ˌtrækə/", "partOfSpeech": "noun", "definition": "A tool or ledger used to record the achievement of major project stages.", "example": "If you log each completed chapter into the milestone tracker, motivation will soar.", "translation": "مؤشر أو أداة رصد المحطات الإنجازية", "exampleArabic": "إذا سجلت كل فصل مكتمل في مؤشر رصد الإنجازات، فسيعلو حماسك.", "collocations": ["digital milestone tracker", "update the milestone tracker"], "synonyms": [], "antonyms": [], "tags": ["productivity", "tools"]},
    {"headword": "celebrate win", "pronunciation": "/ˈselɪbreɪt wɪn/", "partOfSpeech": "verb", "definition": "To acknowledge, honor, and rejoice over a completed achievement.", "example": "When you hit quarterly targets, take time to celebrate wins with your family.", "translation": "يحتفل بالانتصار والإنجاز المتحقق", "exampleArabic": "حين تحقق الأهداف الفصلية، خذ وقتاً للاحتفال بالانتصارات مع عائلتك.", "verbForms": {"v1": "celebrate win", "v2": "celebrated win", "v3": "celebrated win"}, "collocations": ["celebrate small wins", "celebrate wins together"], "synonyms": ["rejoice in victory"], "antonyms": ["downplay success"], "tags": ["motivation", "actions"]},
    {"headword": "intrinsic reward", "pronunciation": "/ɪnˈtrɪnzɪk rɪˈwɔːd/", "partOfSpeech": "noun", "definition": "An intangible award of recognition or internal sense of satisfaction.", "example": "If you value intrinsic rewards, deep inner contentment will accompany every effort.", "translation": "مكافأة معنوية داخلية (الرضا الذاتي)", "exampleArabic": "إذا قدرت المكافآت المعنوية الداخلية، فسيرافق الرضا العميق كل جهد تبذله.", "collocations": ["rich intrinsic reward", "experience intrinsic rewards"], "synonyms": ["internal satisfaction"], "antonyms": ["extrinsic reward"], "tags": ["psychology", "motivation"]},
    {"headword": "extrinsic reward", "pronunciation": "/ekˈstrɪnzɪk rɪˈwɔːd/", "partOfSpeech": "noun", "definition": "An award that is tangible or physically given to you, such as a bonus or trophy.", "example": "When companies rely solely on extrinsic rewards, long-term creative drive often suffers.", "translation": "مكافأة مادية خارجية ملموسة", "exampleArabic": "حين تعتمد الشركات فقط على المكافآت المادية الخارجية، غالباً ما يتضرر الدافع الإبداعي.", "collocations": ["tangible extrinsic reward", "promise an extrinsic reward"], "synonyms": ["material reward"], "antonyms": ["intrinsic reward"], "tags": ["psychology", "motivation"]},
    {"headword": "vision board", "pronunciation": "/ˈvɪʒn bɔːd/", "partOfSpeech": "noun", "definition": "A collage of images and words representing a person's wishes or goals.", "example": "As soon as you pin your career targets on your vision board, they will inspire action.", "translation": "لوحة الرؤية والأهداف المستقبلية", "exampleArabic": "بمجرد أن تثبت أهدافك المهنية على لوحة الرؤية، ستلهمك للعمل الفعلي.", "collocations": ["create a vision board", "daily vision board"], "synonyms": ["dream board"], "antonyms": [], "tags": ["visualization", "tools"]},
    {"headword": "affirmation", "pronunciation": "/ˌæfəˈmeɪʃn/", "partOfSpeech": "noun", "definition": "A positive statement written or spoken to encourage and empower the self.", "example": "If you recite a focused affirmation every dawn, self-doubt will gradually dissipate.", "translation": "توكيد إيجابي / عبارات تثبيت الثقة بالنفس", "exampleArabic": "إذا رددت توكيداً إيجابياً مركزاً كل فجر، فسيتبدد الشك الذاتي تدريجياً.", "collocations": ["positive affirmation", "daily affirmation"], "synonyms": ["positive declaration"], "antonyms": ["negative self-talk"], "tags": ["psychology", "mindset"]},
    {"headword": "self-efficacy", "pronunciation": "/ˌself ˈefɪkəsi/", "partOfSpeech": "noun", "definition": "An individual's belief in their capacity to execute behaviors necessary for achievements.", "example": "When self-efficacy strengthens, people will tackle formidable problems without fear.", "translation": "الكفاءة الذاتية (إيمان المرء بقدرته على الإنجاز)", "exampleArabic": "حين تتعزز الكفاءة الذاتية، سيتصدى الأفراد للمشكلات العويصة دون خوف.", "collocations": ["high self-efficacy", "build self-efficacy"], "synonyms": ["confidence in ability"], "antonyms": ["self-doubt"], "tags": ["psychology", "character"]},

    # Mindset Mastery & Peak Performance (10)
    {"headword": "can-do attitude", "pronunciation": "/ˌkæn ˈduː ˈætɪtjuːd/", "partOfSpeech": "noun", "definition": "A buoyant, optimistic willingness to tackle problems with confidence.", "example": "If a team embraces a vibrant can-do attitude, creative solutions will proliferate.", "translation": "روح المبادرة وعقلية 'أنا قادر على الإنجاز'", "exampleArabic": "إذا تبنى الفريق روح المبادرة وعقلية 'أنا قادر'، فستتكاثر الحلول الإبداعية.", "collocations": ["foster a can-do attitude", "infectious can-do attitude"], "synonyms": ["positive mindset"], "antonyms": ["defeatist attitude"], "tags": ["mindset", "success"]},
    {"headword": "growth mindset", "pronunciation": "/ˈɡrəʊθ ˈmaɪndset/", "partOfSpeech": "noun", "definition": "The belief that abilities can be developed through dedication and hard work.", "example": "As soon as you adopt an authentic growth mindset, criticism will transform into insight.", "translation": "عقلية النمو والتطور المستمر", "exampleArabic": "بمجرد أن تتبنى عقلية نمو حقيقية، ستتحول الانتقادات إلى بصيرة وحكمة.", "collocations": ["develop a growth mindset", "embrace a growth mindset"], "synonyms": ["incremental theory of intelligence"], "antonyms": ["fixed mindset"], "tags": ["mindset", "psychology"]},
    {"headword": "empowerment", "pronunciation": "/ɪmˈpaʊəmənt/", "partOfSpeech": "noun", "definition": "The process of becoming stronger and more confident in controlling one's life.", "example": "When knowledge provides genuine empowerment, individuals will make bold decisions.", "translation": "تمكين واستشعار القوة الذاتية", "exampleArabic": "حين تمنح المعرفة تمكيناً حقيقياً، سيتخذ الأفراد قرارات شجاعة.", "collocations": ["personal empowerment", "foster empowerment"], "synonyms": ["strengthening"], "antonyms": ["helplessness"], "tags": ["mindset", "success"]},
    {"headword": "ignite passion", "pronunciation": "/ɪɡˈnaɪt ˈpæʃn/", "partOfSpeech": "verb", "definition": "To arouse or stimulate strong, enthusiastic emotion for a purpose.", "example": "If inspiring mentors ignite passion in students, extraordinary dedication will follow.", "translation": "يشعل الشغف والحماس الداخلي", "exampleArabic": "إذا أشعل المرشدون الملهمون الشغف لدى الطلاب، فسيتبع ذلك تفانٍ استثنائي.", "verbForms": {"v1": "ignite passion", "v2": "ignited passion", "v3": "ignited passion"}, "collocations": ["ignite passion for learning", "power to ignite passion"], "synonyms": ["spark enthusiasm"], "antonyms": ["dampen enthusiasm"], "tags": ["motivation", "actions"]},
    {"headword": "fuel ambition", "pronunciation": "/ˈfjuːəl æmˈbɪʃn/", "partOfSpeech": "verb", "definition": "To provide continuous energy, motivation, or support to one's desires.", "example": "As soon as small wins fuel ambition, long-term targets will seem within reach.", "translation": "يغذي الطموح ويمده بالطاقة", "exampleArabic": "بمجرد أن تغذي الانتصارات الصغيرة الطموح، ستبدو الأهداف البعيدة في متناول اليد.", "verbForms": {"v1": "fuel ambition", "v2": "fueled ambition", "v3": "fueled ambition"}, "collocations": ["fuel personal ambition", "fuel ambition constantly"], "synonyms": ["stimulate ambition"], "antonyms": ["stifle ambition"], "tags": ["motivation", "actions"]},
    {"headword": "relentless effort", "pronunciation": "/rɪˈlentləs ˈefət/", "partOfSpeech": "noun", "definition": "Unceasing, intense, and sustained hard work toward a goal.", "example": "When relentless effort becomes your daily standard, excellence will be inevitable.", "translation": "جهد دؤوب لا يعرف الكلل ولا الهوادة", "exampleArabic": "حين يصبح الجهد الدؤوب معيارك اليومي، سيكون التميز أمراً حتمياً.", "collocations": ["apply relentless effort", "combine talent with relentless effort"], "synonyms": ["tireless endeavor"], "antonyms": ["halfhearted attempt"], "tags": ["workplace", "character"]},
    {"headword": "transformative goal", "pronunciation": "/trænsˈfɔːmətɪv ɡəʊl/", "partOfSpeech": "noun", "definition": "A major objective capable of completely changing a person's life or organization.", "example": "If you establish a bold transformative goal, routine habits will elevate naturally.", "translation": "هدف تحويلي يغير مجرى الحياة", "exampleArabic": "إذا حددت هدفاً تحويلياً جريئاً، فسترتفع العادات الروتينية بطبيعتها.", "collocations": ["set a transformative goal", "achieve a transformative goal"], "synonyms": ["life-changing goal"], "antonyms": ["trivial target"], "tags": ["goals", "transformation"]},
    {"headword": "conquer challenge", "pronunciation": "/ˈkɒŋkə ˈtʃælɪndʒ/", "partOfSpeech": "verb", "definition": "To successfully overcome a major difficulty or demanding situation.", "example": "When disciplined partners conquer challenges together, shared bonds deepen profoundly.", "translation": "يقهر التحدي ويتغلب على الصعاب", "exampleArabic": "حين يقهر الشركاء المنضبطون التحديات معاً، تتعمق الروابط المشتركة بشكل عميق.", "verbForms": {"v1": "conquer challenge", "v2": "conquered challenge", "v3": "conquered challenge"}, "collocations": ["conquer every challenge", "unite to conquer challenges"], "synonyms": ["master difficulty"], "antonyms": ["succumb"], "tags": ["actions", "success"]},
    {"headword": "rise to occasion", "pronunciation": "/raɪz tə ði əˈkeɪʒn/", "partOfSpeech": "verb", "definition": "To show that you can deal successfully with an unexpected problem or difficult situation.", "example": "As soon as crises emerge, courageous leaders will rise to the occasion.", "translation": "يرتقي إلى مستوى المسؤولية والحدث", "exampleArabic": "بمجرد أن تنشأ الأزمات، سيرتقي القادة الشجعان إلى مستوى الحدث والمسؤولية.", "verbForms": {"v1": "rise to occasion", "v2": "rose to occasion", "v3": "risen to occasion"}, "collocations": ["rise to the occasion brilliantly", "ready to rise to occasion"], "synonyms": ["meet the challenge"], "antonyms": ["fail under pressure"], "tags": ["actions", "idioms"]},
    {"headword": "achieve greatness", "pronunciation": "/əˈtʃiːv ˈɡreɪtnəs/", "partOfSpeech": "verb", "definition": "To attain exceptional and distinguished preeminence through dedicated endeavor.", "example": "If you blend humble diligence with unyielding perseverance, you will achieve greatness.", "translation": "يحقق العظمة والرفعة والتميز الاستثنائي", "exampleArabic": "إذا مزجت الاجتهاد المتواضع بالمثابرة التي لا تلين، فستحقق العظمة والتميز الاستثنائي.", "verbForms": {"v1": "achieve greatness", "v2": "achieved greatness", "v3": "achieved greatness"}, "collocations": ["destined to achieve greatness", "aspire to achieve greatness"], "synonyms": ["attain excellence"], "antonyms": ["settle for mediocrity"], "tags": ["success", "actions"]}
]

grammar_59 = [
    {
        "title": "First Conditional + Time Clauses (when, as soon as)",
        "titleArabic": "الشرط الأول والعبارات الزمنية (when, as soon as)",
        "explanation": "We use the First Conditional to talk about realistic, probable future possibilities and their expected results: 'If + Present Simple, will + V1 (Base)'. Crucially, the same rule applies to Time Clauses introduced by conjunctions such as 'when', 'as soon as', 'until', 'before', and 'after'. Even though the time clause refers to a future moment, we MUST use the Present Simple (NEVER will) inside the time clause itself: 'As soon as you design a roadmap (Present Simple), you will achieve your goals (will + V1)'. 'When' emphasizes a certain future event, while 'as soon as' highlights immediate action without delay.",
        "explanationArabic": "نستخدم الحالة الشرطية الأولى للتعبير عن احتمالات مستقبلية واقعية وممكنة ونتائجها المنتظرة: 'If + مضارع بسيط, will + الفعل المجرد V1'. والأمر الجوهري هو أن نفس القاعدة الدقيقة تنطبق على الجمل الزمنية (Time Clauses) التي تبدأ بأدوات مثل: when (عندما)، as soon as (بمجرد أن)، until (حتى)، قبل وبعد. ورغم أن المعنى يشير للمستقبل، إلا أنه يُحظر تماماً استخدام will داخل جملة الشرط أو العبارة الزمنية بل يجب استخدام المضارع البسيط: 'بمجرد أن تصمم خريطة طريق (مضارع)، ستحقق أهدافك (will)'.",
        "structures": [
            {"label": "First Conditional (If) · أداة الشرط if", "pattern": "If + Subject + Present Simple, Subject + will + V1 (Base)", "explanation": "Expresses a realistic condition and its likely future consequence.", "explanationArabic": "يعبر عن شرط واقعي ونتيجته المستقبلية المتوقعة."},
            {"label": "Time Clause (When) · العبارة الزمنية when", "pattern": "When + Subject + Present Simple, Subject + will + V1 (Base)", "explanation": "Refers to a definite future trigger that will initiate a result.", "explanationArabic": "يشير إلى لحظة حدوث مستقبلية مؤكدة ستطلق النتيجة فور وقوعها."},
            {"label": "Time Clause (As soon as) · العبارة الزمنية as soon as", "pattern": "As soon as + Subject + Present Simple, Subject + will + V1 (Base)", "explanation": "Emphasizes immediate cause and effect in the future.", "explanationArabic": "يؤكد على الفورية والمباشرة بين وقوع الحدث وحدوث النتيجة المستقبلية."}
        ],
        "examples": [
            {"sentence": "If you draft a detailed action plan tonight, you will execute every strategic target with confidence.", "translation": "إذا وضعت خطة عمل تفصيلية الليلة، فستنفذ كل هدف استراتيجي بثقة.", "usesVocabulary": ["action plan", "strategic target"]},
            {"sentence": "When you overcome this hurdle, your self-efficacy and internal motivation will soar.", "translation": "حين تتغلب على هذه العقبة، سترتفع كفاءتك الذاتية ودافعك الداخلي عالياً.", "usesVocabulary": ["overcome hurdle", "self-efficacy", "internal motivation"]},
            {"sentence": "As soon as you design a realistic roadmap, the path to reach your potential will become clear.", "translation": "بمجرد أن تصمم خريطة طريق واقعية، سيتضح مسار بلوغ أقصى إمكاناتك.", "usesVocabulary": ["roadmap", "reach potential"]},
            {"sentence": "If our team stays disciplined, we will conquer this challenge and celebrate our win.", "translation": "إذا حافظ فريقنا على انضباطه، فسنقهر هذا التحدي ونحتفل بانتصارنا.", "usesVocabulary": ["stay disciplined", "conquer challenge", "celebrate win"]}
        ],
        "commonMistakes": [
            {"wrong": "As soon as you will arrive, we will start the progress tracking.", "right": "As soon as you arrive, we will start the progress tracking.", "note": "Never use 'will' directly inside a time clause (after when, as soon as, if); use Present Simple.", "noteArabic": "لا تضع will داخل جملة أداة الزمن (بعد when أو as soon as أو if) أبداً؛ بل استخدم المضارع البسيط."},
            {"wrong": "If he maintain his unwavering focus, he will achieve greatness.", "right": "If he maintains his unwavering focus, he will achieve greatness.", "note": "Remember the third-person -s in the present simple time clause (he maintains).", "noteArabic": "تذكر إضافة s المفرد للفعل في المضارع البسيط في جملة الشرط (he maintains)."}
        ],
        "commonUsage": [
            "Goal setting and timelines: 'When I complete the draft, I will send it to my accountability partner.' (تُستخدم لتحديد المواعيد والخطط التنفيذية.)",
            "Immediate cause and effect: 'As soon as morning breaks, I will practice my daily affirmations.' (تُستخدم للأفعال الفورية عند نقطة زمنية مستقبلية.)",
            "Motivational self-talk: 'If I persevere through pain, I will achieve my breakthrough.' (تُستخدم للتشجيع الذاتي وصياغة العزائم المستمرة.)"
        ]
    }
]

convs_59 = [
    {
        "title": "Mapping Career Ambitions with a Coach",
        "titleArabic": "رسم مسار الطموحات المهنية مع موجه القيادة",
        "setting": "An executive coach reviews personal goals with an aspiring young entrepreneur.",
        "lines": [
            {"speaker": "Coach", "text": "If you elevate your ambition level, you will naturally view entry-level work as a stepping stone."},
            {"speaker": "Entrepreneur", "text": "As soon as I define a clear long-range vision, I will draft my business action plan."},
            {"speaker": "Coach", "text": "When you establish a realistic roadmap, each benchmark goal will guide your daily routine."},
            {"speaker": "Entrepreneur", "text": "Will focusing on intrinsic rewards prevent burnout during long weeks?"},
            {"speaker": "Coach", "text": "Yes! If you cultivate strong internal motivation, external incentives will become secondary bonuses."},
            {"speaker": "Entrepreneur", "text": "I often struggle with chronic procrastination when tasks feel overwhelming."},
            {"speaker": "Coach", "text": "When you break large targets down into manageable steps, your drive to succeed will conquer hesitation."},
            {"speaker": "Entrepreneur", "text": "I will partner with an accountability partner today so I stay disciplined every single week!"}
        ],
        "vocabularyUsed": ["ambition level", "stepping stone", "long-range vision", "action plan", "roadmap", "benchmark goal", "intrinsic reward", "internal motivation", "external incentive", "procrastination", "drive to succeed", "accountability partner", "stay disciplined"]
    },
    {
        "title": "Overcoming Obstacles with Resilience",
        "titleArabic": "تجاوز العقبات بالمرونة والعزيمة الصلبة",
        "setting": "Two startup cofounders reflect on their product launch setback.",
        "lines": [
            {"speaker": "Karim", "text": "Our investor withdrew funding yesterday; this feels like an impossible stumbling block."},
            {"speaker": "Nadia", "text": "If we view this setback as a catalyst for change, we will discover unexpected opportunities."},
            {"speaker": "Karim", "text": "Can we really orchestrate a rapid setback recovery without additional capital?"},
            {"speaker": "Nadia", "text": "As soon as we embrace a growth mindset and can-do attitude, creative solutions will emerge."},
            {"speaker": "Karim", "text": "Our team has demonstrated remarkable resilience and authentic grit in past emergencies."},
            {"speaker": "Nadia", "text": "When we apply relentless effort to our marketing, we will overcome this hurdle together."},
            {"speaker": "Karim", "text": "If we maintain unwavering focus, we will conquer this challenge and celebrate our win!"},
            {"speaker": "Nadia", "text": "Courageous founders always rise to the occasion; let us get back to work!"}
        ],
        "vocabularyUsed": ["stumbling block", "catalyst for change", "setback recovery", "growth mindset", "can-do attitude", "resilience", "grit", "relentless effort", "overcome hurdle", "unwavering focus", "conquer challenge", "celebrate win", "rise to occasion"]
    },
    {
        "title": "Visualizing Greatness and Self-Efficacy",
        "titleArabic": "تصور النجاح وبناء الكفاءة الذاتية",
        "setting": "Two track athletes review their training log beside their dorm vision board.",
        "lines": [
            {"speaker": "Athlete A", "text": "Whenever I recite this daily affirmation, my self-efficacy feels invigorated."},
            {"speaker": "Athlete B", "text": "As soon as you pin your transformative goal on that vision board, your subconscious will respond."},
            {"speaker": "Athlete A", "text": "When we track daily split times on our milestone tracker, invisible progress becomes tangible."},
            {"speaker": "Athlete B", "text": "If you practice rigorous self-accountability, you will break free from past limitations."},
            {"speaker": "Athlete A", "text": "Does consistent industriousness matter more than raw genetic talent?"},
            {"speaker": "Athlete B", "text": "Absolutely! When you combine stubborn tenacity with patient perseverance, you will achieve greatness."},
            {"speaker": "Athlete A", "text": "Our coach promised that small daily victories would fuel ambition and ignite passion."},
            {"speaker": "Athlete B", "text": "If we pursue excellence relentlessly, we will make a tremendous leap forward this season!"}
        ],
        "vocabularyUsed": ["affirmation", "self-efficacy", "transformative goal", "vision board", "milestone tracker", "self-accountability", "break free", "industriousness", "tenacity", "perseverance", "achieve greatness", "fuel ambition", "ignite passion", "leap forward"]
    }
]

para1_text_59 = (
    "Architecting a purposeful life demands translating abstract aspirations into structured execution. When an ambitious individual "
    "articulates a bold long-range vision, vague hopes crystallize into a definitive core objective. By organizing a strategic target "
    "along an actionable roadmap, the path forward becomes systematic and clear. Forward-thinking achievers draft a meticulous action "
    "plan, establishing each benchmark goal as an empowering stepping stone toward ultimate mastery. When temporary dissatisfaction "
    "acts as a constructive catalyst for change, individuals break free from inertia. As soon as a creator aligns daily routines with "
    "their transformative goal, self-discipline ceases to be a burden and becomes the driving engine that guarantees continuous advancement."
)

para2_text_59 = (
    "True achievement is forged through an enduring alliance of internal motivation and psychological fortitude. While an external "
    "incentive can offer temporary encouragement, an authentic drive to succeed stems from profound personal values. When unforeseen "
    "reversals arise, individuals anchored in perseverance and emotional resilience execute swift setback recovery without despair. "
    "By cultivating legendary grit, fierce determination, and unwavering focus, master practitioners conquer every formidable stumbling "
    "block. When steadfast industriousness and stubborn tenacity replace chronic procrastination, practitioners overcome every hurdle, "
    "demonstrating that patient, relentless effort consistently outperforms erratic bursts of unchanneled talent."
)

para3_text_59 = (
    "Personal empowerment thrives within an intentional ecosystem of accountability and continuous reflection. When professionals "
    "collaborate with an insightful accountability partner and practice rigorous self-accountability, progress tracking transforms "
    "aspirations into measurable results. Recording accomplishments on a milestone tracker allows achievers to celebrate wins and savor "
    "every deep intrinsic reward. Surrounding oneself with visual affirmations and maintaining a vision board fosters high self-efficacy "
    "and a vibrant can-do attitude. As soon as an authentic growth mindset takes root, daily trials ignite passion and fuel ambition, "
    "empowering dedicated seekers to rise to the occasion, conquer challenges, and achieve greatness."
)

paras_59 = [
    {
        "title": "The Strategic Architecture of Vision and Action",
        "titleArabic": "المعمارية الاستراتيجية للرؤية والتنفيذ الفعلي",
        "kind": "informative",
        "text": para1_text_59,
        "translation": "يتطلب بناء حياة ذات غاية تحويل التطلعات المجردة إلى تنفيذ منظم. فحين يصيغ الشخص الطموح رؤية بعيدة المدى، تتبلور الآمال في هدف جوهري محدد. وبتنظيم الأهداف الاستراتيجية على خريطة طريق عملية، يصبح المسار واضحاً ومنهجياً. ويضع الناجحون خطة عمل تنفيذية، جاعلين من كل هدف قياسي حجر ارتقاء نحو الإتقان. وحين يعمل الاستياء كحافز للتغيير، يتحرر المرء من الجمود، لتصبح العادات اليومية محركاً حقيقياً يضمن التقدم المستمر.",
        "vocabularyUsed": ["aspiration", "long-range vision", "core objective", "strategic target", "roadmap", "action plan", "benchmark goal", "stepping stone", "catalyst for change", "break free", "transformative goal"]
    },
    {
        "title": "Fortitude, Resilience, and the Triumph over Procrastination",
        "titleArabic": "الصلابة النفسية والمرونة والانتصار على التسويف",
        "kind": "expository",
        "text": para2_text_59,
        "translation": "يُصنع الإنجاز الحقيقي عبر تحالف راسخ بين الدافع الداخلي والصلابة النفسية. فبينما تقدم الحوافز الخارجية تشجيعاً مؤقتاً، ينبع الدافع الحقيقي للنجاح من القيم العميقة. وحين تنشأ الانتكاسات، ينفذ المتسلحون بالمثابرة والمرونة نهوضاً سريعاً بعد التعثر دون يأس. وبتنمية العزيمة الصلبة والإصرار والتركيز الراسخ، يقهر الممارسون أحجار العثرة، مؤكدين أن الكد الدؤوب والجهد المستمر يهزمان التسويف ويتفوقان على الموهبة غير المنضبطة.",
        "vocabularyUsed": ["internal motivation", "external incentive", "drive to succeed", "perseverance", "resilience", "setback recovery", "grit", "determination", "unwavering focus", "stumbling block", "industriousness", "tenacity", "procrastination", "overcome hurdle", "relentless effort"]
    },
    {
        "title": "Accountability Systems and the Mindset of Greatness",
        "titleArabic": "أنظمة المسؤولية الذاتية وعقلية تحقيق العظمة",
        "kind": "reflective",
        "text": para3_text_59,
        "translation": "يزدهر التمكين الذاتي داخل منظومة واعية من المسؤولية والتأمل المستمر. فحين يتعاون المهني مع شريك التزام ويمارس محاسبة الذات، يحول تتبع التقدم التطلعات إلى نتائج ملموسة. ويتيح تسجيل الإنجازات في مؤشر الرصد الاحتفال بالانتصارات وتذوق المكافأة المعنوية الداخلية. وتدعم التوكيدات الإيجابية ولوحة الرؤية الكفاءة الذاتية وروح المبادرة. وبمجرد رسوخ عقلية النمو، يشتعل الشغف ويُغذى الطموح، ليرتقي الساعون لمستوى الحدث ويحققوا العظمة.",
        "vocabularyUsed": ["empowerment", "accountability partner", "self-accountability", "progress tracking", "milestone tracker", "celebrate win", "intrinsic reward", "affirmation", "vision board", "self-efficacy", "can-do attitude", "growth mindset", "ignite passion", "fuel ambition", "rise to occasion", "achieve greatness"]
    }
]

if __name__ == "__main__":
    print("Writing Day 59...")
    write_day(59, vocab_59, grammar_59, convs_59, paras_59)
