# -*- coding: utf-8 -*-
"""Generator for Day 58: Chances and Guesses (Probability and deduction)."""

import json, os, sys
from scripts.curriculum_engine import write_day

vocab_58 = [
    # Probability Measures & Degrees (10)
    {"headword": "likelihood", "pronunciation": "/ˈlaɪklihʊd/", "partOfSpeech": "noun", "definition": "The state or fact of something being likely; probability.", "example": "There is a strong likelihood that the missing documents were misfiled.", "translation": "أرجحية / احتمالية", "exampleArabic": "هناك أرجحية قوية لأن تكون المستندات المفقودة قد حُفظت في ملف خاطئ.", "collocations": ["strong likelihood", "high likelihood"], "synonyms": ["probability"], "antonyms": ["improbability"], "tags": ["probability", "logic"]},
    {"headword": "probability rate", "pronunciation": "/ˌprɒbəˈbɪləti reɪt/", "partOfSpeech": "noun", "definition": "The statistical frequency or likelihood of a specific event occurring.", "example": "Actuaries calculated that the annual accident probability rate must be minimal.", "translation": "معدل الاحتمالية الإحصائي", "exampleArabic": "حسب الخبراء الإكتواريون أن معدل احتمالية الحوادث السنوي يجب أن يكون ضئيلاً.", "collocations": ["calculate the probability rate", "low probability rate"], "synonyms": [], "antonyms": [], "tags": ["probability", "statistics"]},
    {"headword": "statistical chance", "pronunciation": "/stəˈtɪstɪkl tʃɑːns/", "partOfSpeech": "noun", "definition": "A mathematical likelihood of an outcome evaluated through empirical data.", "example": "There is a minute statistical chance that the experiment could produce anomalies.", "translation": "فرصة إحصائية / احتمال حسابي", "exampleArabic": "هناك فرصة إحصائية ضئيلة لأن تنتج التجربة أي اختلالات.", "collocations": ["minute statistical chance", "high statistical chance"], "synonyms": ["mathematical odds"], "antonyms": [], "tags": ["probability", "statistics"]},
    {"headword": "odds", "pronunciation": "/ɒdz/", "partOfSpeech": "noun", "definition": "The ratio between the probabilities of an event happening versus not happening.", "example": "Against all mathematical odds, the underdog team triumphed in the finals.", "translation": "احتمالات / أرجحية الحدوث", "exampleArabic": "رغم كل الاحتمالات الرياضية المعاكسة، انتصر الفريق الأقل ترشيحاً في النهائي.", "collocations": ["against all odds", "odds are in favor"], "synonyms": ["chances"], "antonyms": [], "tags": ["probability", "logic"]},
    {"headword": "plausibility", "pronunciation": "/ˌplɔːzəˈbɪləti/", "partOfSpeech": "noun", "definition": "The quality of seeming reasonable or probable.", "example": "The detective scrutinized the alibi to evaluate its factual plausibility.", "translation": "معقولية / إمكانية التصديق", "exampleArabic": "دقق المحقق في حجة الغياب لتقييم معقوليتها ومدى قابليتها للتصديق.", "collocations": ["assess plausibility", "lack plausibility"], "synonyms": ["credibility"], "antonyms": ["implausibility"], "tags": ["logic", "probability"]},
    {"headword": "conceivable", "pronunciation": "/kənˈsiːvəbl/", "partOfSpeech": "adjective", "definition": "Capable of being imagined or grasped mentally; plausible.", "example": "Engineers tested the bridge under every conceivable weather stress.", "translation": "ممكن تصوره / قابل للتخيل", "exampleArabic": "اختبر المهندسون الجسر تحت كل ضغط جوي يمكن تصوره.", "collocations": ["every conceivable scenario", "hardly conceivable"], "synonyms": ["imaginable", "thinkable"], "antonyms": ["inconceivable"], "tags": ["probability", "modality"]},
    {"headword": "feasible", "pronunciation": "/ˈfiːzəbl/", "partOfSpeech": "adjective", "definition": "Possible to do easily or conveniently; workable.", "example": "Building an electric high-speed transit line is technically feasible.", "translation": "قابل للتنفيذ عملياً / مجدٍ وممكن", "exampleArabic": "يُعد بناء خط نقل كهربائي فائق السرعة أمراً قابلاً للتنفيذ عملياً.", "collocations": ["economically feasible", "technically feasible"], "synonyms": ["practicable", "viable"], "antonyms": ["unfeasible"], "tags": ["possibility", "logic"]},
    {"headword": "highly probable", "pronunciation": "/ˈhaɪli ˈprɒbəbl/", "partOfSpeech": "adjective", "definition": "Having a very high chance of occurring or being true.", "example": "It is highly probable that interest rates will stabilize next quarter.", "translation": "مرجح للغاية / شديد الاحتمال", "exampleArabic": "من المرجح للغاية أن تستقر أسعار الفائدة في الربع القادم.", "collocations": ["deem highly probable", "remain highly probable"], "synonyms": ["most likely"], "antonyms": ["improbable"], "tags": ["probability", "degrees"]},
    {"headword": "moderately likely", "pronunciation": "/ˈmɒdərətli ˈlaɪkli/", "partOfSpeech": "adjective", "definition": "Having a reasonable, balanced chance of occurring.", "example": "Meteorologists predicted that rain was moderately likely along the coast.", "translation": "محتمل بدرجة متوسطة", "exampleArabic": "توقع خبراء الأرصاد أن هطول المطر محتمل بدرجة متوسطة على طول الساحل.", "collocations": ["consider moderately likely", "ranked moderately likely"], "synonyms": ["fairly probable"], "antonyms": [], "tags": ["probability", "degrees"]},
    {"headword": "barely possible", "pronunciation": "/ˈbeəli ˈpɒsəbl/", "partOfSpeech": "adjective", "definition": "Almost entirely impossible; having only an infinitesimally small chance.", "example": "Surviving the avalanche without shelter was barely possible.", "translation": "بالكاد ممكن / شبه مستحيل", "exampleArabic": "كانت النجاة من الانهيار الجليدي دون مأوى أمراً بالكاد ممكناً.", "collocations": ["considered barely possible", "remains barely possible"], "synonyms": ["remotely possible"], "antonyms": ["certain"], "tags": ["probability", "degrees"]},

    # Impossibility, Certainty & Inevitability (10)
    {"headword": "remote possibility", "pronunciation": "/rɪˈməʊt ˌpɒsəˈbɪləti/", "partOfSpeech": "noun", "definition": "A very slight or distant chance that something might happen.", "example": "There is only a remote possibility that the flight will be canceled.", "translation": "احتمال ضئيل وبعيد", "exampleArabic": "هناك احتمال ضئيل وبعيد فقط لأن تُُلغى الرحلة الجوية.", "collocations": ["mere remote possibility", "distant remote possibility"], "synonyms": ["slim chance"], "antonyms": ["strong likelihood"], "tags": ["probability", "degrees"]},
    {"headword": "improbable outcome", "pronunciation": "/ɪmˈprɒbəbl ˈaʊtkʌm/", "partOfSpeech": "noun", "definition": "A result that is not likely to be true or to happen.", "example": "A sudden market collapse was regarded as an improbable outcome.", "translation": "نتيجة مستبعدة / مآل غير مرجح", "exampleArabic": "اعتبر الانهيار المفاجئ للسوق نتيجة مستبعدة وغير مرجحة.", "collocations": ["face an improbable outcome", "deem an improbable outcome"], "synonyms": ["unlikely result"], "antonyms": ["probable outcome"], "tags": ["probability", "outcome"]},
    {"headword": "impossible scenario", "pronunciation": "/ɪmˈpɒsəbl səˈnɑːriəʊ/", "partOfSpeech": "noun", "definition": "A situation that cannot occur under any circumstances.", "example": "Perpetual motion without energy input is a physical impossible scenario.", "translation": "سيناريو مستحيل الحدوث", "exampleArabic": "تُعد الحركة الدائمة دون مدخلات طاقة سيناريو مستحيل الحدوث فيزيائياً.", "collocations": ["confront an impossible scenario", "render an impossible scenario"], "synonyms": ["unthinkable situation"], "antonyms": ["plausible scenario"], "tags": ["impossibility", "logic"]},
    {"headword": "unthinkable", "pronunciation": "/ʌnˈθɪŋkəbl/", "partOfSpeech": "adjective", "definition": "Too unlikely or unpleasant to be considered possible.", "example": "A total power grid failure was previously considered completely unthinkable.", "translation": "غير وارد إطلاقاً / لا يخطر على بال", "exampleArabic": "كان الانقطاع التام لشبكة الكهرباء يعتبر في السابق أمراً لا يخطر على بال إطلاقاً.", "collocations": ["virtually unthinkable", "previously unthinkable"], "synonyms": ["inconceivable"], "antonyms": ["thinkable"], "tags": ["impossibility", "modality"]},
    {"headword": "inevitable", "pronunciation": "/ɪnˈevɪtəbl/", "partOfSpeech": "adjective", "definition": "Certain to happen; unavoidable.", "example": "Technological advancement in renewable energy is an inevitable development.", "translation": "حتمي / لا مفر منه", "exampleArabic": "يُعد التقدم التكنولوجي في الطاقة المتجددة تطوراً حتمياً لا مفر منه.", "collocations": ["seem inevitable", "inevitable conclusion"], "synonyms": ["unavoidable", "inescapable"], "antonyms": ["preventable"], "tags": ["certainty", "logic"]},
    {"headword": "inescapable", "pronunciation": "/ˌɪnɪˈskeɪpəbl/", "partOfSpeech": "adjective", "definition": "Unable to be avoided or denied; inevitable.", "example": "The committee reached the inescapable conclusion that safety rules were breached.", "translation": "حتمي لا فكاك منه / محتوم", "exampleArabic": "توصلت اللجنة إلى استنتاج حتمي لا فكاك منه بأن قواعد السلامة قد خُرقت.", "collocations": ["inescapable truth", "inescapable reality"], "synonyms": ["unavoidable"], "antonyms": ["avoidable"], "tags": ["certainty", "logic"]},
    {"headword": "unavoidable", "pronunciation": "/ˌʌnəˈvɔɪdəbl/", "partOfSpeech": "adjective", "definition": "Not able to be avoided, prevented, or ignored.", "example": "Delays were unavoidable because of the ferocious snowstorm.", "translation": "لا يمكن تجنبه / حتمي الوقوع", "exampleArabic": "كانت التأخيرات أمراً لا يمكن تجنبه بسبب العاصفة الثلجية العاتية.", "collocations": ["unavoidable delay", "render unavoidable"], "synonyms": ["inevitable"], "antonyms": ["preventable"], "tags": ["certainty", "logic"]},
    {"headword": "conjecture", "pronunciation": "/kənˈdʒektʃə/", "partOfSpeech": "noun", "definition": "An opinion or conclusion formed on the basis of incomplete information.", "example": "Without forensic evidence, your accusation remains pure conjecture.", "translation": "تخمين / حدس بلا دليل قاطع", "exampleArabic": "دون أدلة جنائية، يظل اتهامك مجرد تخمين وظن بحت.", "collocations": ["pure conjecture", "matter of conjecture"], "synonyms": ["speculation", "guesswork"], "antonyms": ["fact"], "tags": ["deduction", "logic"]},
    {"headword": "supposition", "pronunciation": "/ˌsʌpəˈzɪʃn/", "partOfSpeech": "noun", "definition": "An uncertain belief or assumption.", "example": "The theory was constructed upon the supposition that atmospheric pressure was constant.", "translation": "افتراض مسبق / مبني على الظن", "exampleArabic": "بُنيت النظرية على افتراض مسبق بأن الضغط الجوي كان ثابتاً.", "collocations": ["erroneous supposition", "based on supposition"], "synonyms": ["assumption", "premise"], "antonyms": ["certainty"], "tags": ["deduction", "logic"]},
    {"headword": "hypothesis", "pronunciation": "/haɪˈpɒθəsɪs/", "partOfSpeech": "noun", "definition": "A proposed explanation made as a starting point for further investigation.", "example": "The scientist formulated a testable hypothesis to explain bacterial resistance.", "translation": "فرضية علمية قابلة للاختبار", "exampleArabic": "صاغ العالم فرضية قابلة للاختبار لتفسير المقاومة البكتيرية.", "collocations": ["test a hypothesis", "working hypothesis"], "synonyms": ["theory", "premise"], "antonyms": [], "tags": ["science", "deduction"]},

    # Deduction, Inference & Investigation (15)
    {"headword": "postulate", "pronunciation": "/ˈpɒstjuleɪt/", "partOfSpeech": "verb", "definition": "To suggest or assume the existence, fact, or truth of something as a basis for reasoning.", "example": "Physicists postulate that dark matter comprises most of cosmic mass.", "translation": "يفترض كمسلمة / يسلم بصحة", "exampleArabic": "يفترض علماء الفيزياء كمسلمة أن المادة المظلمة تشكل معظم كتلة الكون.", "verbForms": {"v1": "postulate", "v2": "postulated", "v3": "postulated"}, "collocations": ["postulate a theory", "boldly postulate"], "synonyms": ["posit", "assume"], "antonyms": [], "tags": ["logic", "science"]},
    {"headword": "speculate", "pronunciation": "/ˈspekjuleɪt/", "partOfSpeech": "verb", "definition": "To form a theory or conjecture about a subject without firm evidence.", "example": "Analysts can only speculate about the underlying causes of the currency drop.", "translation": "يتكهن / يرجح بدون دليل قاطع", "exampleArabic": "لا يسع المحللين سوى التكهن بالأسباب الكامنة وراء انخفاض العملة.", "verbForms": {"v1": "speculate", "v2": "speculated", "v3": "speculated"}, "collocations": ["speculate wildly", "speculate on causes"], "synonyms": ["hypothesize", "guess"], "antonyms": [], "tags": ["logic", "actions"]},
    {"headword": "deduce logically", "pronunciation": "/dɪˈdjuːs ˈlɒdʒɪkli/", "partOfSpeech": "verb", "definition": "To arrive at a fact or conclusion by reasoning based on known facts.", "example": "From the footprint depth, the detective can deduce logically the culprit's weight.", "translation": "يستنتج استنتاجاً منطقياً", "exampleArabic": "من عمق أثر القدم، يستطيع المحقق أن يستنتج استنتاجاً منطقياً وزن الجاني.", "verbForms": {"v1": "deduce logically", "v2": "deduced logically", "v3": "deduced logically"}, "collocations": ["deduce logically from facts", "ability to deduce logically"], "synonyms": ["infer"], "antonyms": [], "tags": ["deduction", "logic"]},
    {"headword": "infer from evidence", "pronunciation": "/ɪnˈfɜː frəm ˈevɪdəns/", "partOfSpeech": "verb", "definition": "To deduce or conclude information from reasoning and evidence rather than explicit statements.", "example": "Scientists can infer from evidence that global temperatures rose sharply.", "translation": "يستدل من واقع الأدلة والبراهين", "exampleArabic": "يستطيع العلماء الاستدلال من واقع الأدلة على أن درجات الحرارة العالمية ارتفعت بشدة.", "verbForms": {"v1": "infer from evidence", "v2": "inferred from evidence", "v3": "inferred from evidence"}, "collocations": ["infer from evidence directly", "safely infer from evidence"], "synonyms": ["gather", "deduce"], "antonyms": [], "tags": ["deduction", "logic"]},
    {"headword": "surmise", "pronunciation": "/səˈmaɪz/", "partOfSpeech": "verb", "definition": "To suppose that something is true without having evidence to confirm it.", "example": "We can only surmise that the ancient fortress was abandoned during wartime.", "translation": "يظن / يخمن على الأرجح", "exampleArabic": "لا يسعنا إلا أن نظن ونخمن أن الحصن القديم قد هُجر خلال أوقات الحرب.", "verbForms": {"v1": "surmise", "v2": "surmised", "v3": "surmised"}, "collocations": ["safely surmise", "surmise from clues"], "synonyms": ["guess", "infer"], "antonyms": [], "tags": ["deduction", "actions"]},
    {"headword": "extrapolate", "pronunciation": "/ɪkˈstræpəleɪt/", "partOfSpeech": "verb", "definition": "To estimate or conclude by extending known information.", "example": "Economists extrapolate future consumer spending from current retail metrics.", "translation": "يستقرئ / يتوقع عبر قياس المعطيات الحالية", "exampleArabic": "يستقرئ الاقتصاديون الإنفاق الاستهلاكي المستقبلي من مؤشرات التجزئة الحالية.", "verbForms": {"v1": "extrapolate", "v2": "extrapolated", "v3": "extrapolated"}, "collocations": ["extrapolate from trends", "extrapolate future growth"], "synonyms": ["project", "estimate"], "antonyms": [], "tags": ["deduction", "science"]},
    {"headword": "educated guess", "pronunciation": "/ˌedʒʊkeɪtɪd ˈɡes/", "partOfSpeech": "noun", "definition": "A guess based on some knowledge or experience, therefore likely to be correct.", "example": "His diagnosis was an educated guess based on forty years of clinical practice.", "translation": "تخمين قائم على الخبرة والدراسة / تقدير مستنير", "exampleArabic": "كان تشخيصه تقديراً مستنيراً قائماً على خبرة سريرية استمرت أربعين عاماً.", "collocations": ["make an educated guess", "hazard an educated guess"], "synonyms": ["informed guess"], "antonyms": ["blind guess"], "tags": ["deduction", "knowledge"]},
    {"headword": "hunch", "pronunciation": "/hʌntʃ/", "partOfSpeech": "noun", "definition": "A feeling or intuition that something is the case.", "example": "The detective acted on a sudden hunch that the suspect was hiding nearby.", "translation": "حدس / إحساس غريزي داخلي", "exampleArabic": "تصرف المحقق بناءً على حدس مفاجئ بأن المشتبه به كان يختبئ في الجوار.", "collocations": ["have a hunch", "follow a hunch"], "synonyms": ["intuition", "gut feeling"], "antonyms": [], "tags": ["intuition", "deduction"]},
    {"headword": "inkling", "pronunciation": "/ˈɪŋklɪŋ/", "partOfSpeech": "noun", "definition": "A slight knowledge or suspicion; a hint.", "example": "She had not the slightest inkling that her colleagues had organized a celebration.", "translation": "بادرة معرفة / تلميح أو إشعار طفيف", "exampleArabic": "لم تكن لديها أدنى بادرة معرفة أو إشعار بأن زملاءها قد أعدوا احتفالاً.", "collocations": ["faintest inkling", "have an inkling"], "synonyms": ["glimmer", "hint"], "antonyms": [], "tags": ["intuition", "knowledge"]},
    {"headword": "clue deduction", "pronunciation": "/ˈkluː dɪˈdʌkʃn/", "partOfSpeech": "noun", "definition": "The systematic process of drawing conclusions from forensic or factual clues.", "example": "Through careful clue deduction, Sherlock Holmes solved the baffling theft.", "translation": "استنتاج قائم على القرائن والأدلة", "exampleArabic": "من خلال الاستنتاج الدقيق القائم على القرائن، حل شيرلوك هولمز لغز السرقة المحير.", "collocations": ["process of clue deduction", "brilliant clue deduction"], "synonyms": [], "antonyms": [], "tags": ["deduction", "investigation"]},
    {"headword": "circumstantial evidence", "pronunciation": "/ˌsɜːkəmˈstænʃl ˈevɪdəns/", "partOfSpeech": "noun", "definition": "Evidence that relies on an inference to connect it to a conclusion of fact.", "example": "The prosecutor conceded that the conviction rested on circumstantial evidence.", "translation": "قرائن ظرفية / أدلة غير مباشرة", "exampleArabic": "أقر المدعي العام بأن الإدانة استندت إلى قرائن ظرفية غير مباشرة.", "collocations": ["rely on circumstantial evidence", "purely circumstantial evidence"], "synonyms": ["indirect evidence"], "antonyms": ["direct evidence"], "tags": ["legal", "evidence"]},
    {"headword": "conclusive proof", "pronunciation": "/kənˈkluːsɪv ˈpruːf/", "partOfSpeech": "noun", "definition": "Evidence that puts an end to any doubt or uncertainty.", "example": "DNA matching provided conclusive proof that established the suspect's presence.", "translation": "دليل قاطع وحاسم لا يدع مجالاً للشك", "exampleArabic": "قدمت مطابقة الحمض النووي دليلاً قاطعاً وحاسماً أثبت وجود المشتبه به.", "collocations": ["furnish conclusive proof", "constitute conclusive proof"], "synonyms": ["irrefutable proof"], "antonyms": ["questionable proof"], "tags": ["certainty", "evidence"]},
    {"headword": "indisputable fact", "pronunciation": "/ˌɪndɪˈspjuːtəbl ˈfækt/", "partOfSpeech": "noun", "definition": "A truth that is impossible to doubt or debate.", "example": "That planetary bodies revolve around their gravitational center is an indisputable fact.", "translation": "حقيقة دامغة لا جدال فيها", "exampleArabic": "دوران الأجرام حول مراكز جاذبيتها حقيقة دامغة لا جدال فيها.", "collocations": ["stand as an indisputable fact", "established indisputable fact"], "synonyms": ["undeniable truth"], "antonyms": ["contentious claim"], "tags": ["certainty", "facts"]},
    {"headword": "unquestionable", "pronunciation": "/ʌnˈkwestʃənəbl/", "partOfSpeech": "adjective", "definition": "Not able to be disputed or doubted; beyond dispute.", "example": "Her academic integrity and clinical devotion are unquestionable.", "translation": "لا شك فيه / فوق الشبهات والجدل", "exampleArabic": "نزاهتها الأكاديمية وإخلاصها السريري أمر لا شك فيه ولا جدال.", "collocations": ["unquestionable authority", "unquestionable loyalty"], "synonyms": ["indisputable"], "antonyms": ["doubtful"], "tags": ["certainty", "logic"]},
    {"headword": "undeniable", "pronunciation": "/ˌʌndɪˈnaɪəbl/", "partOfSpeech": "adjective", "definition": "Unable to be denied or disputed; distinctly clear.", "example": "The undeniable evidence proved that the digital database was breached.", "translation": "لا يمكن إنكاره / واضح وثابت", "exampleArabic": "أثبت الدليل الثابت الذي لا يمكن إنكاره أن قاعدة البيانات الرقمية قد اختُرقت.", "collocations": ["undeniable truth", "undeniable proof"], "synonyms": ["irrefutable"], "antonyms": ["deniable"], "tags": ["certainty", "logic"]},

    # Skepticism, Eliminating Possibilities & Idioms (15)
    {"headword": "dubious claim", "pronunciation": "/ˈdjuːbiəs kleɪm/", "partOfSpeech": "noun", "definition": "An assertion that is doubtful, questionable, or suspicious.", "example": "Scientists dismissed the miracle cure as a completely dubious claim.", "translation": "ادعاء مشكوك في صحته / زعم مثير للريبة", "exampleArabic": "رفض العلماء العلاج الإعجازي المزعوم باعتباره ادعاءً مشكوكاً فيه تماماً.", "collocations": ["make a dubious claim", "investigate a dubious claim"], "synonyms": ["suspicious assertion"], "antonyms": ["verified claim"], "tags": ["skepticism", "logic"]},
    {"headword": "questionable assertion", "pronunciation": "/ˈkwestʃənəbl əˈsɜːʃn/", "partOfSpeech": "noun", "definition": "A statement made without firm factual backing, open to dispute.", "example": "The auditor challenged the accountant's highly questionable assertion.", "translation": "تأكيد أو زعم محل تساؤل وشك", "exampleArabic": "اعترض المدقق على تأكيد المحاسب المثير للشكوك وعلامات الاستفهام.", "collocations": ["rely on a questionable assertion", "debunk a questionable assertion"], "synonyms": ["disputable claim"], "antonyms": ["indisputable fact"], "tags": ["skepticism", "logic"]},
    {"headword": "wild guess", "pronunciation": "/ˌwaɪld ˈɡes/", "partOfSpeech": "noun", "definition": "A conjecture made completely without knowledge or evidence.", "example": "Without consulting the telemetry data, your answer is merely a wild guess.", "translation": "تخمين عشوائي أعمى بلا أساس", "exampleArabic": "دون مراجعة بيانات القياس عن بعد، فإن إجابتك مجرد تخمين عشوائي أعمى.", "collocations": ["hazard a wild guess", "take a wild guess"], "synonyms": ["shot in the dark"], "antonyms": ["educated guess"], "tags": ["deduction", "skepticism"]},
    {"headword": "rule out", "pronunciation": "/ruːl ˈaʊt/", "partOfSpeech": "verb", "definition": "To exclude or eliminate something from consideration.", "example": "Physicians must rule out bacterial meningitis before initiating standard treatment.", "translation": "يستبعد نهائياً / ينفي الاحتمال", "exampleArabic": "يجب على الأطباء استبعاد التهاب السحايا البكتيري قبل البدء بالعلاج القياسي.", "verbForms": {"v1": "rule out", "v2": "ruled out", "v3": "ruled out"}, "collocations": ["rule out possibilities", "rule out completely"], "synonyms": ["eliminate", "exclude"], "antonyms": ["include"], "tags": ["logic", "actions"]},
    {"headword": "eliminate possibility", "pronunciation": "/ɪˈlɪmɪneɪt ˌpɒsəˈbɪləti/", "partOfSpeech": "verb", "definition": "To remove a potential explanation through diagnostic or investigative evidence.", "example": "Negative biopsy results eliminate the possibility of a malignant tumor.", "translation": "يقضي على الاحتمال / يستبعد الفرضية", "exampleArabic": "تقضي النتائج السلبية للخزعة على احتمال وجود ورم خبيث.", "verbForms": {"v1": "eliminate possibility", "v2": "eliminated possibility", "v3": "eliminated possibility"}, "collocations": ["methodically eliminate possibility", "eliminate every possibility"], "synonyms": ["disprove hypothesis"], "antonyms": [], "tags": ["logic", "actions"]},
    {"headword": "narrow down", "pronunciation": "/ˈnærəʊ daʊn/", "partOfSpeech": "verb", "definition": "To reduce the number of possibilities or choices to a small group.", "example": "Detectives were able to narrow down the suspects to three individuals.", "translation": "يقلص الخيارات / يحصر الاحتمالات", "exampleArabic": "تمكن المحققون من حصر وتقليص المشتبه بهم إلى ثلاثة أفراد.", "verbForms": {"v1": "narrow down", "v2": "narrowed down", "v3": "narrowed down"}, "collocations": ["narrow down options", "narrow down the list"], "synonyms": ["filter", "reduce"], "antonyms": ["broaden"], "tags": ["logic", "actions"]},
    {"headword": "lead to conclusion", "pronunciation": "/liːd tə kənˈkluːʒn/", "partOfSpeech": "verb", "definition": "To provide evidence or reasons that cause someone to decide something.", "example": "The financial anomalies lead to the conclusion that embezzlement occurred.", "translation": "يقود إلى استنتاج حتمي", "exampleArabic": "تقود الاختلالات المالية إلى استنتاج وقوع جريمة اختلاس.", "verbForms": {"v1": "lead to conclusion", "v2": "led to conclusion", "v3": "led to conclusion"}, "collocations": ["irresistibly lead to conclusion", "facts lead to conclusion"], "synonyms": ["point to outcome"], "antonyms": [], "tags": ["deduction", "actions"]},
    {"headword": "point toward", "pronunciation": "/pɔɪnt təˈwɔːd/", "partOfSpeech": "verb", "definition": "To indicate that something is likely or points to a specific cause.", "example": "All physical indicators point toward a sudden electrical surge.", "translation": "يشير بأصابع الاتهام نحو / يدل على", "exampleArabic": "تشير جميع المؤشرات المادية إلى حدوث تدفق كهربائي مفاجئ.", "verbForms": {"v1": "point toward", "v2": "pointed toward", "v3": "pointed toward"}, "collocations": ["evidence points toward", "clues point toward"], "synonyms": ["indicate", "suggest"], "antonyms": [], "tags": ["deduction", "actions"]},
    {"headword": "stand to reason", "pronunciation": "/stænd tə ˈriːzn/", "partOfSpeech": "verb", "definition": "To be obvious or logical.", "example": "It stands to reason that well-rested athletes perform with greater precision.", "translation": "يقتضيه العقل والمنطق / من البديهي", "exampleArabic": "من البديهي وما يقتضيه المنطق أن الرياضيين الذين نالوا قسطاً كافياً من الراحة يؤدون بدقة أكبر.", "verbForms": {"v1": "stand to reason", "v2": "stood to reason", "v3": "stood to reason"}, "collocations": ["it stands to reason that", "clearly stands to reason"], "synonyms": ["make logical sense"], "antonyms": [], "tags": ["logic", "idioms"]},
    {"headword": "logical inference", "pronunciation": "/ˈlɒdʒɪkl ˈɪnfərəns/", "partOfSpeech": "noun", "definition": "A conclusion reached on the basis of valid premises and reasoning.", "example": "Drawing a logical inference from the tire marks proved the car was speeding.", "translation": "استدلال منطقي سليم", "exampleArabic": "أثبت الاستدلال المنطقي السليم من علامات الإطارات أن السيارة كانت مسرعة.", "collocations": ["draw a logical inference", "valid logical inference"], "synonyms": ["deductive conclusion"], "antonyms": ["fallacy"], "tags": ["logic", "deduction"]},
    {"headword": "foregone conclusion", "pronunciation": "/ˌfɔːɡɒn kənˈkluːʒn/", "partOfSpeech": "noun", "definition": "A result that can be predicted with certainty; an inevitable outcome.", "example": "Their victory seemed a foregone conclusion after their overwhelming first-half lead.", "translation": "أمر مفروغ منه / نتيجة محسومة سلفاً", "exampleArabic": "بدا فوزهم أمراً مفروغاً منه ونتيجة محسومة سلفاً بعد تقدمهم الكاسح في الشوط الأول.", "collocations": ["treat as a foregone conclusion", "almost a foregone conclusion"], "synonyms": ["certainty"], "antonyms": ["toss-up"], "tags": ["certainty", "idioms"]},
    {"headword": "long shot", "pronunciation": "/ˈlɒŋ ʃɒt/", "partOfSpeech": "noun", "definition": "An attempt or guess that has very little chance of succeeding.", "example": "Finding the lost diamond ring on the vast sandy beach was an extreme long shot.", "translation": "فرصة ضئيلة للغاية / رهان بعيد الاحتمال", "exampleArabic": "كان العثور على خاتم الألماس المفقود على الشاطئ الرملي الفسيح رهاناً بعيد الاحتمال للغاية.", "collocations": ["admit it is a long shot", "worth a long shot"], "synonyms": ["remote possibility"], "antonyms": ["sure thing"], "tags": ["probability", "idioms"]},
    {"headword": "toss-up", "pronunciation": "/ˈtɒs ʌp/", "partOfSpeech": "noun", "definition": "A situation in which any of two or more alternatives is equally likely.", "example": "The mayoral election is a complete toss-up between the two leading candidates.", "translation": "احتمال متساوٍ 50-50 / قرعة مفتوحة الاحتمالات", "exampleArabic": "انتخابات عمدة المدينة احتمال متساوٍ تماماً بنسبة 50-50 بين المرشحين البارزين.", "collocations": ["virtual toss-up", "call it a toss-up"], "synonyms": ["fifty-fifty chance"], "antonyms": ["sure bet"], "tags": ["probability", "idioms"]},
    {"headword": "gamble outcome", "pronunciation": "/ˈɡæmbl ˈaʊtkʌm/", "partOfSpeech": "noun", "definition": "A result that depends largely on luck, chance, or unpredictable factors.", "example": "Investing in untested cryptocurrency startups is essentially a gamble outcome.", "translation": "نتيجة مقامرة قائمة على الحظ الخالص", "exampleArabic": "يُعد الاستثمار في الشركات الناشئة غير المجربة للعملات الرقمية نتيجة مقامرة في جوهرها.", "collocations": ["risky gamble outcome", "unpredictable gamble outcome"], "synonyms": ["risky venture"], "antonyms": ["guarantee"], "tags": ["probability", "risk"]},
    {"headword": "beyond shadow of doubt", "pronunciation": "/bɪˈjɒnd ˈʃædəʊ əv ˈdaʊt/", "partOfSpeech": "idiom", "definition": "With absolute certainty; without any lingering skepticism.", "example": "The surveillance camera recording established his innocence beyond shadow of doubt.", "translation": "بما لا يدع مجالاً لأدنى شك", "exampleArabic": "أثبت تسجيل كاميرا المراقبة براءته بما لا يدع مجالاً لأدنى شك.", "collocations": ["prove beyond shadow of doubt", "true beyond shadow of doubt"], "synonyms": ["conclusively"], "antonyms": ["dubious"], "tags": ["certainty", "idioms"]}
]

grammar_58 = [
    {
        "title": "May / Might / Must / Can't for Deduction",
        "titleArabic": "أفعال الاستنتاج والتخمين (May / Might / Must / Can't for Deduction)",
        "explanation": "We use modal verbs to make deductions and express our degree of certainty about present situations based on available evidence: 1) 'Must' expresses near certainty that something is true based on clear facts ('The laboratory lights are on; the scientist must be inside'). 2) 'Can't' (or 'couldn't') expresses certainty that something is impossible ('He can't be in London; I spoke to him in the cafeteria five minutes ago'). Note: do NOT use 'mustn't' for negative deduction! 3) 'May', 'Might', and 'Could' express that something is possible or plausible, but not certain ('The test results might be delayed due to equipment calibration').",
        "explanationArabic": "نستخدم هذه الأفعال الناقصة لصياغة الاستنتاجات والتعبير عن درجات اليقين والشك في الحاضر استناداً للأدلة المتاحة: 1) Must (لابد أنه...): تعبر عن شبه يقين بأن الشيء صحيح بناءً على قرائن قاطعة ('أضواء المختبر مضاءة؛ لابد أن العالم بالداخل'). 2) Can't (مستحيل أن يكون...): تعبر عن يقين جازم باستحالة الشيء ('مستحيل أن يكون في لندن؛ لقد تحدثت معه في الكافيتريا قبل خمس دقائق'). تنبيه: لا تستخدم mustn't للاستنتاج المنفي أبداً! 3) May / Might / Could (قد / ربما / يحتمل): تعبر عن إمكانية حدوث الشيء مع وجود شك وعدم يقين.",
        "structures": [
            {"label": "Strong Positive Deduction · استنتاج إيجابي مؤكد (Must)", "pattern": "Subject + must + be / V1 (Base)", "explanation": "Logically certain that something is true.", "explanationArabic": "شبه يقين منطقي بأن الأمر صحيح وحقيقي."},
            {"label": "Strong Negative Deduction · استنتاج سلبي جازم بالاستحالة (Can't)", "pattern": "Subject + can't + be / V1 (Base)", "explanation": "Logically certain that something is completely impossible.", "explanationArabic": "يقين منطقي جازم بأن الأمر مستحيل تماماً."},
            {"label": "Possibility / Uncertainty · الاحتمالية والشك (May / Might / Could)", "pattern": "Subject + may / might / could + be / V1 (Base)", "explanation": "Possible or plausible, but not 100% verified.", "explanationArabic": "محتمل أو ممكن الوقوع ولكن بدون جزم قطعي."}
        ],
        "examples": [
            {"sentence": "The lab results are conclusive; it must be an indisputable fact that the alloy is genuine.", "translation": "نتائج المختبر قاطعة؛ لابد أنها حقيقة دامغة لا جدال فيها بأن السبيكة أصلية.", "usesVocabulary": ["indisputable fact"]},
            {"sentence": "That dubious claim can't be true; all forensic clues lead to the opposite conclusion.", "translation": "مستحيل أن يكون ذلك الادعاء المشكوك فيه صحيحاً؛ فكل القرائن تقود للاستنتاج المعاكس.", "usesVocabulary": ["dubious claim"]},
            {"sentence": "The economic forecast might be an educated guess, but it stands to reason based on retail trends.", "translation": "قد يكون التوقع الاقتصادي تخميناً مستنيراً، لكنه منطقي استناداً لاتجاهات التجزئة.", "usesVocabulary": ["educated guess", "stand to reason"]},
            {"sentence": "We can't rule out the remote possibility that atmospheric interference disrupted satellite signals.", "translation": "لا يمكننا استبعاد الاحتمال البعيد بأن التشويش الجوي قد عطل إشارات الأقمار الصناعية.", "usesVocabulary": ["rule out", "remote possibility"]}
        ],
        "commonMistakes": [
            {"wrong": "He mustn't be the thief; he was out of the country.", "right": "He can't be the thief; he was out of the country.", "note": "Never use 'mustn't' for logical deduction of impossibility; always use 'can't'.", "noteArabic": "لا تستخدم mustn't أبداً للاستنتاج الدال على الاستحالة؛ بل استخدم دائماً can't."},
            {"wrong": "It must be rain tomorrow, the sky is cloudy.", "right": "It might rain tomorrow, the sky is cloudy. (OR: will definitely rain)", "note": "Use 'might/may' for future possibilities; modal deduction with 'must' applies to present logic or past with have.", "noteArabic": "استخدم might/may للاحتمالات المستقبلية، ولا تستخدم must لتوقع المستقبل."}
        ],
        "commonUsage": [
            "Forensic and logical deductions: 'He can't be working today; his car is missing.' (تُستخدم للتحليلات الجنائية والمنطقية اليومية.)",
            "Expressing scientific likelihood: 'The hypothesis may be confirmed after clinical trials.' (تُستخدم لترجيح الفرضيات العلمية.)",
            "Evaluating rumors: 'That story must be a wild guess; there is zero evidence.' (تُستخدم للحكم على الشائعات والأقاويل غير المثبتة.)"
        ]
    }
]

convs_58 = [
    {
        "title": "Investigating a Mystery in the Lab",
        "titleArabic": "التحقيق في لغز علمي داخل المختبر",
        "setting": "Two research scientists analyze anomalous data readings in an engineering laboratory.",
        "lines": [
            {"speaker": "Lead Scientist", "text": "Look at these voltage spikes! It can't be a random sensor error; the pattern repeats hourly."},
            {"speaker": "Colleague", "text": "There must be an undetected ground circuit leak. Let us examine the technical plausibility."},
            {"speaker": "Lead Scientist", "text": "Could someone have altered the calibration settings? That seems like an improbable outcome."},
            {"speaker": "Colleague", "text": "We cannot rule out that possibility yet, but our clue deduction points toward a power surge."},
            {"speaker": "Lead Scientist", "text": "It stands to reason that sudden thermal expansion could cause this anomaly."},
            {"speaker": "Colleague", "text": "Let us narrow down our working hypothesis and eliminate the possibility of network glitches."},
            {"speaker": "Lead Scientist", "text": "If we discover conclusive proof, the true cause will be established beyond shadow of doubt."},
            {"speaker": "Colleague", "text": "Let us test the backup generator; that must give us our answer!"}
        ],
        "vocabularyUsed": ["plausibility", "improbable outcome", "rule out", "clue deduction", "point toward", "stand to reason", "narrow down", "hypothesis", "eliminate possibility", "conclusive proof", "beyond shadow of doubt"]
    },
    {
        "title": "Forecasting an Election Outcome",
        "titleArabic": "استشراف نتائج الانتخابات بين محللين سياسيين",
        "setting": "Two political commentators discuss election polling numbers in a television studio.",
        "lines": [
            {"speaker": "Anchor", "text": "The latest statistical chance shows both candidates tied at forty-nine percent. What are the odds?"},
            {"speaker": "Analyst", "text": "The race is a complete toss-up; predicting an easy victor is a mere wild guess right now."},
            {"speaker": "Anchor", "text": "The incumbent claimed that victory was a foregone conclusion. That must be a questionable assertion!"},
            {"speaker": "Analyst", "text": "Indeed; that dubious claim ignores the strong likelihood of high voter turnout in the suburbs."},
            {"speaker": "Anchor", "text": "Do you speculate that minor parties might decide the gamble outcome?"},
            {"speaker": "Analyst", "text": "Based on demographic trends, we can extrapolate that independent voters will cast the deciding ballots."},
            {"speaker": "Anchor", "text": "An outright landslide victory appears to be an impossible scenario under current polarization."},
            {"speaker": "Analyst", "text": "That is an undeniable fact; every precinct count will matter down to the wire."}
        ],
        "vocabularyUsed": ["statistical chance", "odds", "toss-up", "wild guess", "foregone conclusion", "questionable assertion", "dubious claim", "likelihood", "speculate", "gamble outcome", "extrapolate", "impossible scenario", "undeniable"]
    },
    {
        "title": "Examining Indirect Clues",
        "titleArabic": "فحص القرائن غير المباشرة والأدلة الظرفية",
        "setting": "A senior detective mentors a junior investigator examining a crime scene.",
        "lines": [
            {"speaker": "Detective", "text": "What does your initial clue deduction tell you about the suspect's movements?"},
            {"speaker": "Investigator", "text": "I had a sudden hunch that the intruder must have possessed an authorized keycard."},
            {"speaker": "Detective", "text": "Careful; relying on a hunch without verified facts is mere conjecture."},
            {"speaker": "Investigator", "text": "The lock is undamaged; we can deduce logically that forced entry can't have occurred."},
            {"speaker": "Detective", "text": "That circumstantial evidence is compelling, but we must infer from evidence with utmost rigor."},
            {"speaker": "Investigator", "text": "Could there be an inkling of inside collusion among the security staff?"},
            {"speaker": "Detective", "text": "We cannot postulate guilt prematurely, but that logical inference warrants deeper inquiry."},
            {"speaker": "Investigator", "text": "I will review the surveillance logs to verify our educated guess."}
        ],
        "vocabularyUsed": ["clue deduction", "hunch", "conjecture", "deduce logically", "circumstantial evidence", "infer from evidence", "inkling", "postulate", "logical inference", "educated guess"]
    }
]

para1_text_58 = (
    "Scientific inquiry and criminal investigation both rely on systematic deduction to distinguish objective reality from mere "
    "supposition. When confronted with an unsolved riddle, researchers cannot rely on a baseless wild guess or accept an untested "
    "dubious claim. Instead, investigators formulate a testable hypothesis and methodically eliminate possibilities based on verified "
    "data. By analyzing circumstantial evidence, analysts deduce logically how an anomaly arose and infer from evidence which causes "
    "stand to reason. They methodically narrow down the field of inquiry until every indicator points toward a solitary root cause. "
    "When indisputable facts align with mathematical odds, the working theory is confirmed beyond shadow of doubt, transforming initial "
    "conjecture into celebrated conclusive proof."
)

para2_text_58 = (
    "Evaluating risk in high-stakes environments requires distinguishing between theoretical plausibility and empirical probability. "
    "While an impossible scenario can be ruled out immediately by physical laws, distinguishing a remote possibility from a highly "
    "probable event demands rigorous calculation of the probability rate. Planners test complex systems against every conceivable "
    "stress to determine if preventive mitigations are technically feasible. In complex markets, relying on an untested questionable "
    "assertion is an irresponsible gamble outcome. Analysts extrapolate longitudinal trends to anticipate outcomes that are moderately "
    "likely, acknowledging that while total predictability is a foregone conclusion in hindsight, foresight demands navigating odds "
    "with humility."
)

para3_text_58 = (
    "Human intuition frequently operates through subtle cognitive impressions that precede formal logical inference. An experienced "
    "specialist often acts on an instinctive hunch or faint inkling before empirical measurements provide undeniable corroboration. "
    "Veterans postulate innovative theories based on years of subconscious pattern recognition, offering an educated guess that "
    "frequently proves remarkably accurate. However, critical thinkers recognize that without unquestionable proof, even the most "
    "compelling conjecture must be treated with skepticism. By balancing intuitive insight with rigorous evidential deduction, scholars "
    "safeguard intellectual integrity while uncovering breakthroughs that transform our understanding of the universe."
)

paras_58 = [
    {
        "title": "Scientific Deduction and Evidential Rigor",
        "titleArabic": "الاستدلال العلمي والصرامة في فحص القرائن",
        "kind": "informative",
        "text": para1_text_58,
        "translation": "يعتمد البحث العلمي والتحقيق الجنائي كلاهما على الاستنتاج المنظم للتمييز بين الواقع الموضوعي والظن البحت. فعند مواجهة لغز محير، لا يمكن الاعتماد على التخمين الأعمى أو قبول ادعاء مشكوك فيه. بل يصوغ الباحثون فرضية قابلة للاختبار ويستبعدون الاحتمالات وفق بيانات محققة. وبتحليل القرائن الظرفية، يستنتجون منطقياً ما يقتضيه العقل، ويقلصون الخيارات حتى تشير الأدلة لسبب وحيد، ليتحول الظن إلى برهان قاطع لا يدع مجالاً للشك.",
        "vocabularyUsed": ["supposition", "wild guess", "dubious claim", "hypothesis", "eliminate possibility", "circumstantial evidence", "deduce logically", "infer from evidence", "stand to reason", "narrow down", "point toward", "indisputable fact", "odds", "beyond shadow of doubt", "conjecture", "conclusive proof"]
    },
    {
        "title": "Probability Distributions and Risk Assessment",
        "titleArabic": "توزيعات الاحتمالات وتقييم المخاطر المؤسسية",
        "kind": "expository",
        "text": para2_text_58,
        "translation": "يتطلب تقييم المخاطر في البيئات الحساسة التمييز بين المعقولية النظرية والاحتمالية التجريبية. فبينما يمكن استبعاد السيناريو المستحيل بقوانين الفيزياء، فإن تمييز الاحتمال البعيد عن الحدث شديد الاحتمال يتطلب حساب معدل الاحتمالية. ويختبر المخططون الأنظمة ضد كل ظرف متصور لتحديد ما هو ممكن عملياً. وتجنباً لنتائج المقامرة القائمة على ادعاءات مشكوك فيها، يستقرئ المحللون الاتجاهات لتوقع ما هو محتمل باعتدال، مدركين أن الحكمة تتطلب التواضع أمام الاحتمالات.",
        "vocabularyUsed": ["plausibility", "impossible scenario", "remote possibility", "highly probable", "probability rate", "conceivable", "feasible", "questionable assertion", "gamble outcome", "extrapolate", "moderately likely", "foregone conclusion", "odds"]
    },
    {
        "title": "Intuition, Inference, and Epistemic Humility",
        "titleArabic": "الحدس الفطري، والاستدلال، والتواضع المعرفي",
        "kind": "reflective",
        "text": para3_text_58,
        "translation": "يعمل الحدس البشري غالباً عبر انطباعات معرفية دقيقة تسبق الاستدلال المنطقي الشكلي. فكثيراً ما يتصرف المتخصص ذو الخبرة بناءً على حدس أو إشعار طفيف قبل أن تقدم القياسات تأكيداً لا يمكن إنكاره. ويسلم الخبراء بصحة نظريات مبتكرة بناءً على إدراك الأنماط مقترحين تخميناً مستنيراً يثبت دقته. غير أن المفكرين يدركون أنه دون دليل لا شك فيه، يجب التعامل مع الظن بحذر، ليحمي الموازنة بين الحدس والبرهان النزاهة الفكرية.",
        "vocabularyUsed": ["logical inference", "hunch", "inkling", "undeniable", "postulate", "educated guess", "unquestionable", "conjecture"]
    }
]

if __name__ == "__main__":
    print("Writing Day 58...")
    write_day(58, vocab_58, grammar_58, convs_58, paras_58)
