import json, re

day2_vocab = [
    ("mother", "/ˈmʌðər/", "noun", "a female parent", "My mother is a teacher.", ["mom (noun)"], ["loving mother"], ["mom", "mama"], ["father"], ["family"]),
    ("father", "/ˈfɑːðər/", "noun", "a male parent", "My father works in an office.", ["dad (noun)"], ["proud father"], ["dad", "papa"], ["mother"], ["family"]),
    ("parents", "/ˈpeərənts/", "noun", "a mother and father together", "My parents live in a quiet town.", ["parent (noun)"], ["both parents"], [], [], ["family"]),
    ("sister", "/ˈsɪstər/", "noun", "a female who has the same parents as you", "I have one older sister.", ["sisterly (adjective)"], ["older sister", "younger sister"], [], ["brother"], ["family"]),
    ("brother", "/ˈbrʌðər/", "noun", "a male who has the same parents as you", "My brother is twenty years old.", ["brotherly (adjective)"], ["older brother", "little brother"], [], ["sister"], ["family"]),
    ("son", "/sʌn/", "noun", "someone's male child", "They have one son and two daughters.", [], ["only son"], [], ["daughter"], ["family"]),
    ("daughter", "/ˈdɔːtər/", "noun", "someone's female child", "Their daughter goes to primary school.", [], ["eldest daughter"], [], ["son"], ["family"]),
    ("child", "/tʃaɪld/", "noun", "a young boy or girl", "The child is playing in the garden.", ["childhood (noun)"], ["only child"], ["kid"], ["adult"], ["family", "people"]),
    ("children", "/ˈtʃɪldrən/", "noun", "plural form of child; young people", "We have three happy children.", [], ["young children"], ["kids"], ["adults"], ["family", "people"]),
    ("baby", "/ˈbeɪbi/", "noun", "a very young child who cannot walk or talk", "The baby is sleeping peacefully.", [], ["newborn baby"], ["infant"], [], ["family", "people"]),
    ("grandmother", "/ˈɡrænmʌðər/", "noun", "the mother of your father or mother", "My grandmother bakes wonderful bread.", ["grandma (noun)"], ["loving grandmother"], ["grandma"], ["grandfather"], ["family"]),
    ("grandfather", "/ˈɡrænfɑːðər/", "noun", "the father of your father or mother", "My grandfather is seventy years old.", ["grandpa (noun)"], ["kind grandfather"], ["grandpa"], ["grandmother"], ["family"]),
    ("grandparents", "/ˈɡrænpeərənts/", "noun", "the parents of your parents", "We visit our grandparents every weekend.", [], ["elderly grandparents"], [], [], ["family"]),
    ("aunt", "/ɑːnt/", "noun", "the sister of your father or mother", "My aunt lives in London.", [], ["favorite aunt"], [], ["uncle"], ["family"]),
    ("uncle", "/ˈʌŋkl/", "noun", "the brother of your father or mother", "My uncle teaches history at school.", [], ["great uncle"], [], ["aunt"], ["family"]),
    ("cousin", "/ˈkʌzn/", "noun", "the child of your aunt or uncle", "I have a cousin who lives in Canada.", [], ["first cousin"], [], [], ["family"]),
    ("husband", "/ˈhʌzbənd/", "noun", "the man a woman is married to", "Her husband is a doctor.", [], ["caring husband"], [], ["wife"], ["relationships"]),
    ("wife", "/waɪf/", "noun", "the woman a man is married to", "His wife is an architect.", [], ["beloved wife"], [], ["husband"], ["relationships"]),
    ("married", "/ˈmærid/", "adjective", "having a husband or a wife", "They are happily married.", ["marriage (noun)"], ["get married", "happily married"], [], ["single"], ["status"]),
    ("single", "/ˈsɪŋɡl/", "adjective", "not married or in a relationship", "He is single and lives alone.", [], ["stay single"], ["unmarried"], ["married"], ["status"]),
    ("person", "/ˈpɜːsn/", "noun", "a human being", "She is a very friendly person.", ["personal (adjective)"], ["kind person", "nice person"], ["individual"], [], ["people"]),
    ("people", "/ˈpiːpl/", "noun", "human beings in general (plural of person)", "Many people live in this city.", [], ["young people", "friendly people"], ["persons"], [], ["people"]),
    ("family", "/ˈfæməli/", "noun", "a group of people related to each other", "My family is very important to me.", ["familiar (adjective)"], ["big family", "small family"], ["household"], [], ["family"]),
    ("relative", "/ˈrelətɪv/", "noun", "a member of your family", "We invite every relative to dinner.", ["relationship (noun)"], ["close relative", "distant relative"], ["relation"], [], ["family"]),
    ("tall", "/tɔːl/", "adjective", "having greater than average height", "My older brother is very tall.", ["tallness (noun)"], ["tall man", "tall and thin"], [], ["short"], ["appearance"]),
    ("short", "/ʃɔːt/", "adjective", "not tall in height", "My aunt is short and energetic.", [], ["short person"], [], ["tall"], ["appearance"]),
    ("young", "/jʌŋ/", "adjective", "having lived for only a short time", "The young boy is reading a book.", ["youth (noun)"], ["young girl", "young child"], [], ["old"], ["age"]),
    ("old", "/əʊld/", "adjective", "having lived for many years", "Our grandfather is eighty years old.", ["elderly (adjective)"], ["old man", "old friend"], ["aged", "elderly"], ["young"], ["age"]),
    ("friendly", "/ˈfrendli/", "adjective", "behaving in a kind and pleasant way", "Our neighbors are very friendly.", ["friendliness (noun)"], ["friendly smile", "friendly neighbor"], ["kind", "warm"], ["unfriendly"], ["personality"]),
    ("kind", "/kaɪnd/", "adjective", "caring about others and helpful", "She is always kind to children.", ["kindness (noun)"], ["kind words", "kind person"], ["gentle", "helpful"], ["mean", "cruel"], ["personality"]),
    ("smart", "/smɑːt/", "adjective", "clever and quick at learning", "My sister is smart and passes all exams.", ["smartness (noun)"], ["smart student"], ["clever", "intelligent"], ["stupid"], ["personality"]),
    ("happy", "/ˈhæpi/", "adjective", "feeling pleased and cheerful", "We are happy together as a family.", ["happiness (noun)"], ["happy family", "feel happy"], ["glad", "cheerful"], ["sad", "unhappy"], ["feeling"]),
    ("together", "/təˈɡeðər/", "adverb", "with each other in one place", "We eat dinner together every night.", [], ["live together", "stay together"], [], ["apart", "alone"], ["social"]),
    ("photo", "/ˈfəʊtəʊ/", "noun", "a picture made using a camera", "This is a photo of my family.", ["photograph (noun)"], ["family photo", "take a photo"], ["picture"], [], ["home"]),
    ("nephew", "/ˈnefjuː/", "noun", "the son of your brother or sister", "My nephew is starting kindergarten.", [], ["young nephew"], [], ["niece"], ["family"]),
    ("niece", "/niːs/", "noun", "the daughter of your brother or sister", "My niece has curly brown hair.", [], ["little niece"], [], ["nephew"], ["family"]),
    ("twin", "/twɪn/", "noun", "one of two children born at the same time", "My brothers are identical twins.", [], ["twin brother", "twin sister"], [], [], ["family"]),
    ("neighbor", "/ˈneɪbər/", "noun", "someone who lives near you", "Our neighbor is an elderly woman.", ["neighborhood (noun)"], ["next-door neighbor"], [], [], ["people"]),
    ("partner", "/ˈpɑːtnər/", "noun", "a person you live with or are in love with", "She and her partner bought a house.", ["partnership (noun)"], ["life partner"], ["companion"], [], ["relationships"]),
    ("colleague", "/ˈkɒliːɡ/", "noun", "someone you work with", "My colleague introduced me to her family.", [], ["work colleague"], ["coworker"], [], ["people", "work"]),
    ("adult", "/ˈædʌlt/", "noun", "a fully grown person", "This movie is suitable for any adult.", ["adulthood (noun)"], ["young adult"], ["grown-up"], ["child"], ["people"]),
    ("teenager", "/ˈtiːneɪdʒər/", "noun", "a person aged between 13 and 19", "My brother is a typical teenager.", ["teenage (adjective)"], ["rebellious teenager"], ["adolescent"], [], ["people", "age"]),
    ("age", "/eɪdʒ/", "noun", "the number of years someone has lived", "What is the age of your younger sister?", ["aged (adjective)"], ["at the age of", "same age"], [], [], ["people"]),
    ("member", "/ˈmembər/", "noun", "a person belonging to a group or family", "Every member of our family helps at home.", ["membership (noun)"], ["family member"], [], [], ["family"]),
    ("introduce", "/ˌɪntrəˈdjuːs/", "verb", "to tell someone another person's name", "Let me introduce my brother David.", ["introduction (noun)"], ["introduce yourself", "introduce a friend"], ["present"], [], ["communication"]),
    ("close", "/kləʊs/", "adjective", "having strong emotional connection", "I am very close to my sister.", ["closeness (noun)"], ["close friends", "close family"], ["tight-knit"], ["distant"], ["relationships"]),
    ("love", "/lʌv/", "verb / noun", "to care deeply about someone", "We love our grandparents very much.", ["lovely (adjective)"], ["fall in love", "true love"], ["adore"], ["hate"], ["feeling"]),
    ("smile", "/smaɪl/", "noun / verb", "a happy facial expression", "My grandmother always has a warm smile.", [], ["big smile", "smile at"], ["grin"], ["frown"], ["appearance"]),
    ("friendly face", "/ˈfrendli feɪs/", "phrase", "a kind appearance that looks welcoming", "It is nice to see a friendly face here.", [], ["see a friendly face"], [], [], ["appearance"]),
    ("look like", "/lʊk laɪk/", "phrase", "to be similar in appearance to someone", "I look like my father, but my brother looks like my mother.", [], ["look like someone"], ["resemble"], [], ["appearance"])
]

print("Count of vocab:", len(day2_vocab))
assert len(day2_vocab) == 50, f"Expected 50, got {len(day2_vocab)}"
